### ISSUE TITLE
SPDY & HTTP/2 detection only works in Firefox

### ISSUE THREAD

**Issue by rugk** [AliasIO/Wappalyzer#1000]
Based on the fact that SPDY and HTTP/2 are only detected by [a header](https://github.com/AliasIO/Wappalyzer/blob/6d895ddf9a5fb493cbf6ba25fcb083bd3370a31d/src/apps.json#L5135) which is [only set in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=736882#c1) I assume that the SPDY & HTTP/2 detection only works in Firefox.

That's sad and it would be great to make it detectable for all [drivers](https://github.com/AliasIO/Wappalyzer/wiki/Drivers).

**Comment by rugk** [comment]
(the reference to #1002 is wrong, this issue is not fixed)

**Comment by AliasIO** [comment]
It would be but last time I checked there isn't a way to do this.
