### ISSUE TITLE
Add webserver Openresty

### ISSUE THREAD

**Issue by rugk** [AliasIO/Wappalyzer#1001]
https://github.com/openresty/ngx_openresty
site: https://openresty.org/

**Comment by toastal** [comment]
I added support for OpenResty months ago. You can even see statistics @ https://wappalyzer.com/applications/openresty. Some results may be off though however if the `Server` header isn't saying `openresty`. A version I compiled recently just said `nginx`, but that's not a bug in Wappalyzer.

**Comment by rugk** [comment]
Okay, fixed. :smile:
