### ISSUE TITLE
Error ad.js on console

### ISSUE THREAD

**Issue by bigmumet** [AliasIO/Wappalyzer#1009]
Hi.. 
I use got error console when using Wapplizer extension
im using google chrome Version 37.0.2062.120 (64-bit) and Version 41.0.2272.35 beta (64-bit) on Ubuntu 12.04.
Both of them show error ad.js on line 70

![screenshot from 2015-10-23 14 34 07](https://cloud.githubusercontent.com/assets/1157158/10686822/2f1f94d4-7992-11e5-90b5-d2e29fc2ed70.png)

**Comment by q--** [comment]
As far as I'm aware Wappalyzer doesn't insert a script called ad.js. Check
if the error still occurs if you disable Wappalyzer. If it doesn't, and the
script isn't part of the web page either, check your computer for adware.

2015-10-23 9:28 GMT+02:00 Makara Dewangga <notifications@github.com>:

**Comment by AliasIO** [comment]
Chrome does, it's to detect ads. The issue has been fixed in code.
