### ISSUE TITLE
Cannot detect libraries packed with Webpack

### ISSUE THREAD

**Issue by Axure** [AliasIO/Wappalyzer#1013]
Angular it can detect, but lodash and vuejs (at least) it cannot.

**Comment by Axure** [comment]
Cannot even detect jQuery.

**Comment by Axure** [comment]
No reply? @AliasIO

**Comment by AliasIO** [comment]
There may be cases where it fails but Wappalyzer detects all the libraries you mention.

**Comment by nickforddesign** [comment]
This is still the case, when sites are bundled by webpack, wappalyzer will only list webpack, none of the above frameworks

**Comment by jvoisin** [comment]
Do feel free to provide ways to fingerprint them.

**Comment by nickforddesign** [comment]
Cool! I'll submit a PR :)

**Comment by nickforddesign** [comment]
Question about the js pattern: does this allow for using `document.querySelector`? It does look like the only guaranteed way to detect this requires a bit more than a regex pattern... but I am able to detect Vue pretty reliably using this:

```js
document.querySelector('*').__vue__

**Comment by jvoisin** [comment]
Nope, [it doesn't]( https://www.wappalyzer.com/docs/specification ) :/
But you're able to match on Objects, so something like `__vue__` might work?

**Comment by nickforddesign** [comment]
Unfortunately it looks like there are no globals at all in a production environment, so this might be a non-starter...

**Comment by nickforddesign** [comment]
Just submitted a PR that allows for detecting Vue.js even if bundled by webpack https://github.com/AliasIO/Wappalyzer/pull/2027
