### ISSUE TITLE
Add support for humans.txt

### ISSUE THREAD

**Issue by mamadoo** [AliasIO/Wappalyzer#1014]
Please add http://humanstxt.org/ into your plugin.
Thanx

**Comment by AliasIO** [comment]
Wappalyzer works by scanning the page you're on, it wouldn't be able to pick up on humans.txt unless you went to the file directly.

**Comment by mamadoo** [comment]
In website that use humans.txt, there is below link:
<link type="text/plain" rel="author" href="http://domain/humans.txt" />

then Wappalyzer can detect that website use humans.txt.
Thanx

**Comment by mamadoo** [comment]
In website that use humans.txt, there is below link:
```<link type="text/plain" rel="author" href="http://domain/humans.txt" />```
then Wappalyzer can detect that website use humans.txt.
Thanx
