### ISSUE TITLE
Report back to Wappalizer false positives

### ISSUE THREAD

**Issue by mikulabc** [AliasIO/Wappalyzer#1018]
https://adwords.google.com/cm/

![Image of what i see](http://i.imgur.com/f9QGfbQ.png)

I'm pretty sure Adwords from Google is not Magento & not PHP, where can I report back to Wappalizer that it's not and we can correct that 50% to 0% ? Maybe a button to the right side?

Is it? [YES](#) / [NO](#)
"clickable"...

**Comment by gadcam** [comment]
+1 I think we need to add a feature to report a potential false positive (and why not another to say an app is used).
The better would be to publish these information and delete them when it is corrected or proven wrong. (but it will require some efforts).
