### ISSUE TITLE
Differents infos between driver python and webapp

### ISSUE THREAD

**Issue by DPeltier** [AliasIO/Wappalyzer#1021]
Hello,
I am using both driver python and firefox plugin. I need the driver python for one of my script.
For http://bbc.com, I obtain
>driver python ( lib python requests==2.8.1 )
{"Optimizely":{"categories":["analytics"],"confidence":100,"version":""},"RequireJS":{"categories":["javascript-frameworks"],"confidence":100,"version":""},"Modernizr":{"categories":["javascript-frameworks"],"confidence":100,"version":""}}

> Firefox plugin
Apache, Web Server, RequireJS,JavaScript Framework,comScore,Analytics,Chartbeat,Analytics,Google AdSense,Advertising Network,Google Tag Manager,Tag Manager,Modernizr,JavaScript Framework

As we can, results are completely differents. I obtain much more informations with the firefox plugin. 
I am using for both of them the last version.

Any idea?

**Comment by q--** [comment]
The Python version only analyses the headers, URL and static HTML. The browser extensions will also analyze JavaScript variables and things added to the DOM dynamically. I believe the PhantomJS version will do this as well.

**Comment by AliasIO** [comment]
Yes, the PhantomJS driver is recommended for running Wappalyzer server side as it will evaluate JavaScript variables in the `window` object. The Python driver does not do this.
