### ISSUE TITLE
Sensitive data like FPD

### ISSUE THREAD

**Issue by danyalzafar420** [AliasIO/Wappalyzer#1028]
![wappalyser](https://cloud.githubusercontent.com/assets/10330087/11745490/62651cc8-a03a-11e5-8896-bd0389e38e40.PNG)

It should not be there as its helpful for a attacker in order to try some Queries to get more responses from your database.
When i install your extension then i looked at this issue was a sql error. 
patch it ASAP :)

**Comment by klonos** [comment]
Already reported, but no patch available: https://www.drupal.org/node/2419517

**Comment by klonos** [comment]
...a few suggestions of things to try here: https://www.drupal.org/node/1055296

**Comment by AliasIO** [comment]
I upgraded the server so it should be able to handle more connections now. I also turned off the error message display on the frontend.

**Comment by klonos** [comment]
:wink:
