### ISSUE TITLE
Add Angular 2 / Angular Dart

### ISSUE THREAD

**Issue by rayshan** [AliasIO/Wappalyzer#1030]
Hello, per this announcement:
http://angularjs.blogspot.com/2015/12/angular-2-beta.html

This product is supposed to use Angular 2:
https://fiber.google.com/cities/kansascity/fiberhoods/

But no Angular usage is detected on the page. It'll be nice if it is detected, and even nicer if AngularJS 1 and Angular2 can be distinguished, as 2 is a major rewrite.

---

Edit: they appear to be using Dart. Full sourcemaps are available.

![screen shot 2015-12-15 at 7 26 51 pm](https://cloud.githubusercontent.com/assets/3760840/11831275/f0d0f520-a361-11e5-855e-fab4c3428e6f.png)

**Comment by DaAwesomeP** [comment]
It probably wasn't detected because they're using dart. I don't know how we could distinguish between them besides checking for the "upgrade" library that lets you use both Angular 1 and 2 at the same time.

[Angular 1.x](https://angularjs.org/)
[Angular 2.x](https://angular.io/)

**Comment by DaAwesomeP** [comment]
Nevermind. I needed to change the `sessionAuth` policy:
```js
return res.send(401, {err: 401, msg: 'Unauthorized'});
```

**Comment by ameyanaik11** [comment]
That's an interesting case! :)
