### ISSUE TITLE
requirements for escaping in apps.json

### ISSUE THREAD

**Issue by siparker** [AliasIO/Wappalyzer#1034]
you mention in the specifications that / dont need escaping yet in the google analytics one it has

^https?://[^\\/]+\\.google-analytics\\.com\\/(?:ga|urchin|(analytics))\\.js\\;version:\\1?UA:

specifically after the \\.com it then has another escaping \\ before the forwardslash /

is this a mistake or am i missing soemhting

sorry for noob question

**Comment by q--** [comment]
Hi @siparker,

The way this works under the hood is that Wappalyzer will insert a `\` before every `/` that hasn't been escaped. So essentially, both `/` and `\/` will work, though just `/` is preferred because it's easier to read and write.

**Comment by siparker** [comment]
Hi

Thanks for that.

I just need to try and understand the rest of that regex now. if nayone has the time to do a quick explanation that would be awesome.

Other query i had was in ref to ENV variables. is there a simple way to identify these?

**Comment by q--** [comment]
I learned regular expressions mostly from the tutorials at www.regular-expressions.info.

For finding environment variables, I'm using [this bookmarklet](http://perfectionkills.com/detecting-global-variable-leaks/).

**Comment by siparker** [comment]
thats great thank you. i will go and work through the regex site first i think thats the most important
