### ISSUE TITLE
Google Tag Manager not detected. plus other google properties

### ISSUE THREAD

**Issue by siparker** [AliasIO/Wappalyzer#1036]
www.link-assistant.com contains

<script async="" src="//www.googletagmanager.com/gtm.js?id=GTM-TKVM4B"></script>

but google tag manager is not detected. i checked the match in apps.json and it had 

"html": "googletagmanager\\.com/ns\\.html[^>]+></iframe>",

I assume that is one way it is implemented.

as it was a src= i tried with a script tag
 
"script": "googletagmanager\\.com/gtm\\.js\\?id",

That did not work either

I can see the tech using ghostery and viewing in firebug but wappalyser isnt picking it up

Anything i can try?

**Comment by siparker** [comment]
google tag manager is still shown in apps.json but doesnt detect. any ideas as to why?

**Comment by siparker** [comment]
this is now fixed i believe if you can please check the pull request

Also if anyone could explain why certain thigns dont match whereas others do.

I used "script": "//www\\.googletagmanager\\.com/gtm\\.js", as the matching string. if i leave ?id on the end i tried escaping the ? and not escaping it never worked either way

if anyone has any instructions that might be able to help me please advise.

thanks

**Comment by AliasIO** [comment]
Let's move the discussion to the pull request.
