### ISSUE TITLE
Add new App anchorCache® Caching Class

### ISSUE THREAD

**Issue by ioli** [AliasIO/Wappalyzer#1037]
anchorCache® Caching Class

[ The anchorCache® hehigh-performance object caching system ever. ]

http://anchorcache.eu/

**Comment by rugk** [comment]
https://github.com/AliasIO/Wappalyzer/pull/1051

**Comment by ioli** [comment]
https://iconverticons.com/icons/ea6e4dfc9780e858/

**Comment by ioli** [comment]
"anchorCache": {
        "cats": [
            23
        ],
        "headers": {
            "X-anchor-Cache": ""
        },
        "icon": "anchorCache.png",
        "implies": "PHP",
        "website": "anchorcache.eu"
    },

**Comment by DaAwesomeP** [comment]
This can be closed now.
