### ISSUE TITLE
iframe blocking

### ISSUE THREAD

**Issue by gabrielefanplayr** [AliasIO/Wappalyzer#1038]
I'm randomly seeing an error being generated when iframes by 3rd party scripts are created on a website i'm browsing. The error seems to be caused by wappalyzer. I'm running on Chrome 47 for OSX 10.11. Please see attached example.

![screen shot 2015-12-22 at 23 49 31](https://cloud.githubusercontent.com/assets/16407061/11968067/b21364b0-a908-11e5-9290-4e656db5ec9e.png)

Thank you very much for your feedback.

**Comment by gadcam** [comment]
Can't reproduce : Chrome 47, Wappalyzer 2.44 (Win 10)
In my opinion the script on config1.veinteractive.com should be broken, I think it's something like [this](http://stackoverflow.com/questions/13446106/error-trying-to-access-a-iframe-in-javascript).
Why do you think it's related to Wappalyzer ?

**Comment by gabrielefanplayr** [comment]
Hi, thanks for your feedback; a couple comments:

- also using Wappalyzer 2.44
- yes, it appears to be random for me as; i'm not able to replicate it but it sometimes appear when i keep trying to force iframes to load
- it's not related to VeInteractive; in fact, i have the same error happening on other services that run on iframes like Fanplayr (see additional screenshot)
- i believe it's caused by Wappalyzer as clicking to expand the error it brings me to 
chrome-extension://gppongmhjkpfnbhagpmjfkannfbllamg/js/iframe.js which relates to the extension key of Wappalyzer

![image](https://cloud.githubusercontent.com/assets/16407061/12018625/9914e3a6-ad65-11e5-8881-0a03418a2528.png)

**Comment by gadcam** [comment]
I can't reproduce on Kiwoko nor.
> when i keep trying to force iframes to load

I don't understand this part.
On Kiwoko it's the same error: mixed content. To be sure Wappalyzer is the culprit you could try to disable it next time it occurs and see what happens.
>i believe it's caused by Wappalyzer as clicking to expand the error it brings me to chrome-extension://gppongmhjkpfnbhagpmjfkannfbllamg/js/iframe.js which relates to the extension key of Wappalyzer

I don't know this part of the code, @AliasIO could know what is happening.

**Comment by gabrielefanplayr** [comment]
>On Kiwoko it's the same error: mixed content.

On this one, please refer to the error below that one, Blocked Frame, which is the same as reported on piecesetpneus.com (just not expanded)

>when i keep trying to force iframes to load

The error only happens when the page is trying to load a frame from a 3rd party (like VeInteractive or Fanplayr in the examples); to reproduce you have to have the page load a frame; i have created a test for you at this URL:

www.kiwoko.com/?testwapp

it will load a Fanplayr iframe and it will keep loading it in each page after that for the duration of your session. I was able to have the error generate again after a few page views; disabling Wappalyzer did not generate the error, but i can't be 100% sure it's like that as it mostly is random.

**Comment by gadcam** [comment]
> www.kiwoko.com/?testwapp

You're right after a few times I managed to reproduce it. And without W. nothing after ten trials.

**Comment by gabrielefanplayr** [comment]
Any feedback on a possible fix?

**Comment by AliasIO** [comment]
@gabrielefanplayr Can you confirm this is still happening?

**Comment by gabrielefanplayr** [comment]
it did up to last week; i'm not able to replicate it today, did you pushed some fix?

**Comment by AliasIO** [comment]
Yes, a fix was pushed as part of another ticket. Please let me know if you notice it happening again.
