### ISSUE TITLE
Many false positives for "Google PageSpeed"

### ISSUE THREAD

**Issue by julfy** [AliasIO/Wappalyzer#1040]
Regexps for Google PageSpeed are a bit too general:
```json
"Google PageSpeed": {
			"cats": [
				23,
				33
			],
			"headers": {
				"X-Mod-Pagespeed": "([\\d.]+)\\;version:\\1",
				"X-Page-Speed": "(.+)\\;version:\\1"
			},
			"website": "developers.google.com/speed/pagespeed/mod"
		}
```
Things like this are considered as it's versions:
`coindugeek.com: Google PageSpeed POOOWEEEEEER ! - J.Clarkson`

**Comment by gadcam** [comment]
In my opinion it's not a false positive: they are using Google PageSpeed.
It's more a version detection bug and the problem occurs only when the version field has been changed by the user. (coindugeek's web server is also "powered by mana"..)
To avoid such a version we could change it to
```js
"X-Page-Speed": "([\\d.]+-\\d+)?\\;version:\\1"
```
