### ISSUE TITLE
app.json and logo as a Dependency

### ISSUE THREAD

**Issue by Preovaleo** [AliasIO/Wappalyzer#1048]
Hey,

Is it possible to put the app.json and the logo in another git.
this way, it can be used in another project as a submodule?
(git submodule)

thanks

**Comment by rugk** [comment]
Interesting idea. :+1:

**Comment by DaAwesomeP** [comment]
Kind of like CDNjs. The only problem would be when you actually compile it. It would take a very long time to download more than 100 git repos, even if it was just two files in a separate branch.

Maybe we could do something where everything is still stored here but there is a script that can update everything when run.

**Comment by Preovaleo** [comment]
My idea was only to put the file and all the logo in one other git

**Comment by berezuev** [comment]
If you need this images, you can create your own repository and add there app.json and icons (logo's) to use as a submodule. 
But you must add link to original repository in your repo.
GPL3 license [allows you](https://tldrlegal.com/license/gnu-lesser-general-public-license-v3-(lgpl-3)) to do this!

**Comment by DaAwesomeP** [comment]
I think that we should have a standard for this (i.e. a branch named `wappalyzer`).

**Comment by rugk** [comment]
@berezuev I think it's not about a legal issue or a "how to do that" question, but rather that including a submodule is easy and especially you can update it easily.

**Comment by rugk** [comment]
> (i.e. a branch named `wappalyzer`).

This would be quite misleading. A better name for the branch would be `webappsdetect-json` or something similar. At least `wappalyze-data` or `wappalyze-json`...
But I'd still prefer a separate repo. Otherwise contributing to the apps.json would get complicated (as you cannot contribute to the master branch).

**Comment by DaAwesomeP** [comment]
Well, in my past experience with submodules, they reference a commit. So, unless there is a way to reference the most up to date part of a branch, then this may not be very effective.

@rugk I just meant that it shouldn't be in the master branch of whatever project. A separate repo like you said would be better.

The other problem is with tests. There is no way to enforce testing the whole thing, which is especially important if it can be updated without approval at any time.

**Comment by rugk** [comment]
> Well, in my past experience with submodules, they reference a commit. So, unless there is a way to reference the most up to date part of a branch, then this may not be very effective.

That's what they do. With easy updating I just meant you can use a single command (`git submodule update`) to update it AFAIK.

**Comment by rugk** [comment]
As it seems this idea is not implemented. So you refuse this idea, @AliasIO? Could you please explain why?

It is quite impolite to close issues without any explanation.

**Comment by AliasIO** [comment]
I wouldn't mind seeing a use case for this but I'd prefer to keep everything in the one repository.
