### ISSUE TITLE
Why cannot detect back end info for some sites?

### ISSUE THREAD

**Issue by pengyuanzhao** [AliasIO/Wappalyzer#1061]
How is server info or backend language is detected?  Wappalyzer does not show complete info for some sites.

For example, it does not show PHP for facebook.com

Thanks!

**Comment by AliasIO** [comment]
Wappalyzer can only pick up on technologies that are somehow exposed on the frontend. In the case of PHP, Wappalyzer looks at URLs, cookies, response headers and other software that is know to be written in PHP.

Although Facebook is written in PHP I don't believe the website runs on PHP directly anymore. It's compiled to C++ and run as binary code.

https://en.wikipedia.org/wiki/HipHop_for_PHP
