### ISSUE TITLE
Question App

### ISSUE THREAD

**Issue by ioli** [AliasIO/Wappalyzer#1062]
Hello

What should I do in my application to recognize Wappalyzer ?

Must add code in my own application ?

I have performance this parameter !

"anchorCache": {
  "cats": [
    23
 ],
 "headers": {
    "X-anchor-Cache": ""
  },
   "icon": "anchorCache.png",
   "implies": "PHP",
   "website": "anchorcache.eu"
},

My application works with the parameter 

<?php include("anchorCache/anchorCache.php");?>

Wappalyzer CALL  anchorCache/anchorCache.php  ?

anchorCache.php  add wappalyzer code recognize ?

Thank you!

**Comment by AliasIO** [comment]
I merged one of your pull requests, it will be in the next release. Wappalyzer doesn't make network requests, you can't call PHP scripts directly.

**Comment by ioli** [comment]
does not need to enter some command my code for recognition ? Ok

please add my ICON https://iconverticons.com/icons/1e3d6a26badde7ea/

Wappalyzer add my Credits my Documents App
https://cloud.ioli.be/Documentation/#Credits2

Thank You!
