### ISSUE TITLE
Rails version didn't recognize well

### ISSUE THREAD

**Issue by TheCrott** [AliasIO/Wappalyzer#1066]
When I browse https://www.datacamp.com/ , wappalyzer mistakenly recognize Rails version. It should be Rails 4.x.x, not Rails 5.0.14

And why in app.json there's a confidence value of 50% of a website is using rails?

**Comment by Derekholio** [comment]
5.0.14 is being detected from this header:
X-Powered-By: Phusion Passenger 5.0.14
