### ISSUE TITLE
Do not show hosts unreachable from the public internet

### ISSUE THREAD

**Issue by ThiefMaster** [AliasIO/Wappalyzer#1081]
Right now wappalyzer easily exposes intranet hosts even if they are not even accessible from the public internet. Take https://wappalyzer.com/applications/indico for example. The current top-1 entry there is a developer's test system that's only accessible from our internal network. While it being listed there doesn't cause any harm, it's also pretty useless.

My suggestion would be to either

- hide systems that cannot be accessed via HTTP from your own servers or
- check a system again when it'd be displayed in a top list and only show it if you managed to retrieve the same information.

The second option would also prevent people from being able to submit spam URLs using scripts (I don't know if you already have safeguards against this).

**Comment by AliasIO** [comment]
I'm planning to implement host checking at some point. Currently URLs that look like internal domains are filtered out, such as .local and .dev.

**Comment by q--** [comment]
Also, this bug is a duplicate of  #1068
