### ISSUE TITLE
Question about combinations of identifiers

### ISSUE THREAD

**Issue by siparker** [AliasIO/Wappalyzer#1093]
in apps.json 

"Application Name": { 
    "website": "example.com", 
    "cats":    [ 1 ], 
    "headers": { "X-Powered-By": "Application Name" },
    "url":     ".+\\.application-name\\.com",
    "html":    "<link[^>]application-name\\.css", 
    "meta":    { "generator": [ "Application Name", "Alternative Application Name" ] },
    "script":  "application-name-([0-9.]+)\\.js\\;confidence:50\\;version:\\1",
    "env":     "ApplicationName",
    "implies": "PHP\\;confidence:50",
    "excludes": "Other Application Name"
    }

What is the current AND / OR  method? i know within a single part i can put a pipe to indicate an OR for detection but what if i want to have two or three thigns reliant on each other. for example there must be a src script but when that exists there must also be a html entity for this to pass.

Or do i have to do this via the confidence ?

Thanks

**Comment by AliasIO** [comment]
Everything is OR, you'd have to use confidence.
