### ISSUE TITLE
Feature - trigger secondary tests in certain cases

### ISSUE THREAD

**Issue by siparker** [AliasIO/Wappalyzer#1100]
is it possible when wappalyser identifies a certain type of platform that can trigger a secondary test that would help identify further?
For example with wordpress currently it doesnt find the version easily. on some wordpress sites the wp-links-opml.php page will show a generator tag with the full version. on others there are other indicators. There are ways to do this but they need to only really be run after a specific type of cms or software is found.

Is this possible within the framework?

**Comment by AliasIO** [comment]
It's possible but not desirable for Wappalyzer to perform requests every time a page is loaded.
