### ISSUE TITLE
Follow-up to: dual windows firefox - only works on second window #573 

### ISSUE THREAD

**Issue by patriiiiiiiiiick** [AliasIO/Wappalyzer#1102]
It seems the closed issue can't get in the radar so please consider fixing this. It makes Wappalyzer just useless. With Firefox 38.5 ESR.

Original bug:
dual windows firefox - only works on second window #573

**Comment by Solanar** [comment]
Just wanted to add that it's still an issue in Firefox 49.0.2

If I switch from the url location to the toolbar button, it works on multiple windows. It's only the icons in the url location that is limited to one window.

If I toggle the option in another window, it switches to that Window and works. I guess I'll go with the toolbar button for now.

**Comment by patriiiiiiiiiick** [comment]
Confirmed as not properly working on 45.4.0 ESR Windows and also not a great experience on latest FF on Linux.

My current experience is that it seems to be disabled when it isn't.

Toolbar button... Gonna try, thanks for the tip!

**Comment by patriiiiiiiiiick** [comment]
@AliasIO Could you please label this as a bug? Thanks in advance!

**Comment by patriiiiiiiiiick** [comment]
@AliasIO Why are you closing this? Is it going to be fixed?

**Comment by DaAwesomeP** [comment]
There is a new WebExtension version of the addon that will become mainstream at the very least when Firefox 57 is released and old SDK addons are discontinued. The new version will not have issues with e10s. The WebExtension is currently available for testing.
