### ISSUE TITLE
Show all icon's in statusbar

### ISSUE THREAD

**Issue by sapphireweb** [AliasIO/Wappalyzer#1104]
I find that having all the icons displayed in the address-bar can become a bit crowded.  When running firefox, it would be nice to be able to place Wapplayzer in the statusbar, oir a secondary statusbar, and have it display all the icons, just as it does when in the address-bar.

**Comment by ldong** [comment]
@sapphireweb I hear what you said, but I don't agree with you. For developers, please make it optional if you were going to make changes..
