### ISSUE TITLE
Get script URLs directly from the DOM to detect apps more reliably

### ISSUE THREAD

**Issue by q--** [AliasIO/Wappalyzer#1107]
Get script URLs directly from the DOM to detect apps more reliably

Currently, Wappalyzer [uses](https://github.com/AliasIO/Wappalyzer/blob/master/src/drivers/firefox/wappalyzer.js#L308) a regex to get the URLs the `script` patterns are matched against. However, this creates problems in a lot of cases:
- Protocol-relative URLs aren't matched by complete regular expressions. (This was brought up in #1105.) For example:
  
  ```
   //www.google-analytics.com/analytics.js
  ```
  
  isn't matched by
  
  ```
  /^https?:\/\/[^\/]+\.google-analytics\.com\/(?:ga|urchin|(analytics))\.js/i
  ```
- & is properly encoded as `&amp;` by the browser (even if it isn't in the original web page source). For example:
  
  ```
  http://example.com/foobar.php?baz=foo&amp;bar
  ```
  
  isn't matched by
  
  ```
  /\/foobar\.php\?baz=[^&]*&bar/i
  ```

These are just some examples I could think of. I'm sure there are more.

Since the browser will automatically return the complete URL for a script when accessing the `src` property of an `HTMLScriptElement`, I propose Wappalyzer should get its script URLs from the DOM instead of using a regex to find them.

For example:

```
var scriptUrls = [];
Array.prototype.forEach.call(document.getElementsByTagName('script'), function( node ){
  node.src && scriptUrls.push (node.src);
});
```

**Comment by gadcam** [comment]
@q-- @AliasIO  I think you can now close this issue.
