### ISSUE TITLE
Preferred the icon in the Omnibox instead of next to my other plugins

### ISSUE THREAD

**Issue by GoliathIAm** [AliasIO/Wappalyzer#1110]
As a web developer who uses alot of plugins regularly, like Wappalyzer, and Eyedropper, etc; with my theme (black everything pretty much) I think that the Wappalyzer icon looked better when it was in the Omni/Search/Url Box (Google Chrome). Now that it's next to my other icon's it's hardly noticeable and when it changes depending on the framework of the site I'm visiting, it's hard to see. 

Is there a reason it was moved?
Anyone else want it back where it was?

**Comment by aeblin** [comment]
Preferred it in the omnibox as well.

**Comment by ryanwohara** [comment]
+1

**Comment by Un3qual** [comment]
+1
Why the change?

**Comment by dawn2k** [comment]
@GoliathIAm
@Un3qual 
The change is probably due to the way [page actions](https://developer.chrome.com/extensions/pageAction) were ment to be used. Chrome developer manual states: 

> Page actions represent actions that can be taken on the current page, but that aren't applicable to all pages. 

Anyways, I'd like to get back the page action behavior as well.

**Comment by erickrawczyk** [comment]
:+1: I would also like the omnibox instead of an extension button. It looks like the transition to pageAction happened in #765 but I'm not sure what changed it back to browserAction behavior.

**Comment by Jesse97** [comment]
+1

Because of a recent update to Chrome, that displays all extensions in the extension-bar even if they don't have such functionality, I had confused Wappalyzer's icon with such a non-functioning icon and hid it, before not much later realizing it was the actual icon.

This is more of an pageAction-like extension anyway as it displays page-related stuff and is not visible on chrome://-pages where it isn't available.

**Comment by AliasIO** [comment]
Chrome 48 changed the way it treats pageAction extensions. It looks like it's not possible to have the extension icon in the omnibox any more.

https://github.com/AliasIO/Wappalyzer/blob/master/src/drivers/chrome/manifest.json#L12

**Comment by davidhellmann** [comment]
hm ok… very uncool but that looks like shit:
![image](https://cloud.githubusercontent.com/assets/764292/13509796/ae81d9d6-e18d-11e5-9585-e183ff203c4d.png)

maybe a dropdown or something else?

**Comment by Suxiaogang** [comment]
+1 for not easy to pick up the Wappalyzer in the messed up Chrome pageAction toolbar.
