### ISSUE TITLE
Wrong plugins detected

### ISSUE THREAD

**Issue by moffa13** [AliasIO/Wappalyzer#1111]
In my site, Twitter Bootstrap and TrackJs are detected but i'm not using them.

[https://beta.bigcoding.com](https://beta.bigcoding.com)

**Comment by katsos** [comment]
This is still showing TrackJs but no bootstrap any more.

TrackJS is shown by your call at ./BigTracker/track/ which is called by your ./js/BigTracker.js ajax request.
This i definetely a bug but not a major one.

**Comment by ScionOfBytes** [comment]
@moffa13 I can see a `<link rel="stylesheet" type="text/css" href="/css/bootstrap.css" data-primary="yes">` link being included in the page. Why is is this wrong?
