### ISSUE TITLE
Add option to show Wappalyzer icon inside the url bar (beside the star in Chrome).

### ISSUE THREAD

**Issue by josephan** [AliasIO/Wappalyzer#1112]
It's just a personal preference. I think it looks cleaner that way.
I will take a stab at it.

**Comment by Triloworld** [comment]
I confirm: 
Chrome 49.0.2623.75 m
No icons in adress bar. It works, it was usefull and pleas, bring it back!

**Comment by okaufmann** [comment]
Same here in chrome 48.0.2564.116 m

**Comment by azinasili** [comment]
Not sure what changed, but I also would love the icon to move back into the address bar.

**Comment by erickrawczyk** [comment]
duplicate of #1110
