### ISSUE TITLE
not able to detect some websites with phantomjs

### ISSUE THREAD

**Issue by mikhilmohanan123** [AliasIO/Wappalyzer#1116]
i am not able to retrieve technologies for some website especially with special characters.but technologies is being detected in chrome.any solutions?

**Comment by klonos** [comment]
Would help a lot if you provided some examples.

**Comment by mikhilmohanan123** [comment]
for example,
 when i go to website-http://www.bayerncode.de/
wappalyzer extension detects all the application and displays it in chrome but when i run the same in command line using phantonjs it detects no application.

this is my chrome output.
![workspace 1_003](https://cloud.githubusercontent.com/assets/15816239/13687233/23ea07f4-e740-11e5-8071-ca9d7211aa2a.png)

this is my command line output.

![selection_004](https://cloud.githubusercontent.com/assets/15816239/13687310/76a81c9c-e740-11e5-9c0c-4baf36813ecf.png)
