### ISSUE TITLE
apache not detected

### ISSUE THREAD

**Issue by thib3113** [AliasIO/Wappalyzer#1117]
Apache is not detected with header : 
```
Server: Apache/2.4.7 (Ubuntu)
```

**Comment by klonos** [comment]
Example URL please?

**Comment by thib3113** [comment]
No, I can't it's an intranet tool for my company . 
In fact, it's a php file, returning an image like a normal image url .

What do you need ?

**Comment by klonos** [comment]
Just to test and confirm on various OSes and browsers. Never mind then.

**Comment by q--** [comment]
There used to be some code in Wappalyzer that checks if the web page is an
(X)HTML document before running any analysis. (Which is actually a bit
weird, since scanning headers works fine for any other content as well.)

2016-03-15 20:11 GMT+01:00 Gregory Netsas <notifications@github.com>:
