### ISSUE TITLE
Wrong language detected

### ISSUE THREAD

**Issue by XadillaX** [AliasIO/Wappalyzer#1119]
http://school.souche.com/mobile/article/f4MCEiCTR1f

it's not written in Lua.

**Comment by toastal** [comment]
It's served on OpenResty... and the whole deal with OpenResty is allowing Lua scripting in the Nginx worker.

```bash
β ~ curl -I https://school.souche.com/mobile/article/f4MCEiCTR1f
HTTP/1.1 200 OK
Server: openresty
...
```
