### ISSUE TITLE
Ego Real Estate CMS not detected

### ISSUE THREAD

**Issue by adon90** [AliasIO/Wappalyzer#1128]
The CMS Ego Real Estate is not included in the detection:
It can be seen in this website for example: 
http://curberealestate.com/engb/property/858047/registration-of-title-of-higuey-registration-3000056124-la-altagracia
And there are tons of websites using this CMS:
http://www.egorealestate.es/PortalesInmobiliarios
It can be seen in the footer and in the meta content tags.

**Comment by revelt** [comment]
@adon90 I just checked, the http://www.egorealestate.es is being built, so nothing to see there. Upon the investigation I can see that "EGO Real Estate CMS" looks like a real thing, but none of their cited clients have the correct `meta` tag! I checked two sites from the clients list: http://www.predibisa.com/ and http://luxus.pt/ and none of them has ``<meta name="generator"` tag. It's up to EGO Real Estate developers to add the correct meta tag to the generated pages.

Until CMS adds a `meta generator` tag, Wappalyzer won't be able to detect this CMS. Imho, the footer links are not reliable way, we should follow semantic markup principles.

I suggest @AliasIO moderators to close this issue in the meantime.
