### ISSUE TITLE
Feature: Alarm when detecting technology on my list

### ISSUE THREAD

**Issue by b2000699** [AliasIO/Wappalyzer#1129]
Hi,

Thank you so much for this great tool!

It would be really great if I could define a list of technologies in the options of the Firefox-Plugin, so that the plugin would alarm me when I browse to a site which contains such technology, e.g. by making a sound and / or by prominently highlighting / animating the icon of the technology in my address bar.

This way I could instantly notice if a site that I browse to has technology which I am currently interested in, instead of remembering to look at all the icons in the address bar each time, even if I am concentrating on something entirely different while browsing.

Cheers

**Comment by klonos** [comment]
I would like that too. :+1:

**Comment by DeeJaVu** [comment]
+1 
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)![](https://assets-cdn.github.com/images/icons/emoji/unicode/2764.png)![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)![](https://assets-cdn.github.com/images/icons/emoji/unicode/2764.png)![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)![](https://assets-cdn.github.com/images/icons/emoji/unicode/2764.png)![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)![](https://assets-cdn.github.com/images/icons/emoji/unicode/2764.png)![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)![](https://assets-cdn.github.com/images/icons/emoji/unicode/2764.png)![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)![](https://assets-cdn.github.com/images/icons/emoji/unicode/2764.png)![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)![](https://assets-cdn.github.com/images/icons/emoji/unicode/2764.png)![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)![](https://assets-cdn.github.com/images/icons/emoji/unicode/2764.png)![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)![](https://assets-cdn.github.com/images/icons/emoji/unicode/2764.png)![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)![](https://assets-cdn.github.com/images/icons/emoji/unicode/2764.png)
