### ISSUE TITLE
Feature: Button to quickly report "Technology of current website" that was not detected

### ISSUE THREAD

**Issue by b2000699** [AliasIO/Wappalyzer#1131]
Hi there,

It would be great if there would be a convenient way to report a website that contains technology which has not been detected automatically. This way you could get tons of feedback about sites, which the user knows that they contain a specific technology but where the plugin has failed to detect it. This way you would get a lot of usable material to further refine your lists of regular expressions & algorithms!

Same the other way around, would be great, too, i.e. if a user could one-click-report a "false positive", i.e. if your plugin reported a technology to be present although the user knows that it isn't.

Cheers and thank you for this great tool!

**Comment by AliasIO** [comment]
It's a good idea but I don't have the capacity to respond to a large number of requests. Perhaps I could encourage people to submit a pull request though. :)
