### ISSUE TITLE
Nightly thinks that Wappalyzer is slow

### ISSUE THREAD

**Issue by DaAwesomeP** [AliasIO/Wappalyzer#1145]
In the most recent Nightly, I am regularly prompted to disable Wappalyzer because it may be causing Nightly to slow. I don't really know that it really matters or if it even is slow, but whatever is causing the message should be looked into.

**Comment by klonos** [comment]
I have 90 addons and nightly warns me about each and every one of them. Just click the ignore button.

**Comment by DaAwesomeP** [comment]
As I'm reading this message yet another message for another addon has appeared. I think that you're right.
