### ISSUE TITLE
[phantomjs driver] --resource-timeout doesn't seem to function properly

### ISSUE THREAD

**Issue by timneutkens** [AliasIO/Wappalyzer#1161]
Hi,
I'm working on adding a new check and just noticed `--resource-timeout` doesn't seem to function. You can't specify a new timeout number. So the only time [this](https://github.com/AliasIO/Wappalyzer/blob/master/src/drivers/phantomjs/driver.js#L25) is triggered is when you specify `--resource-timeout`. Which will set the timeout to the string `--resource-timeout`. There might need to be some parsing of the options / this option to allow something like this: `--resource-timeout=10000` or `--resource-timeout 10000`

**Comment by AliasIO** [comment]
Fixed in 5593dba22a3705954f30bc1cbc3a55e57476c611. Thank you.
