### ISSUE TITLE
yepnope.js should not have been removed

### ISSUE THREAD

**Issue by benharold** [AliasIO/Wappalyzer#1171]
https://github.com/AliasIO/Wappalyzer/commit/7b8c4454ae35b50699a266a4ad6e3ae8f9c617a3

While `yepnope.js` has been deprecated, it is still a "technology used on websites." What's the point in removing it?

**Comment by timneutkens** [comment]
Agreed. I removed it to fix the failing build. Yepnope was actually removed a bit earlier this year. So I assumed it had been discussed before.
See #1164 for a reference to which commit.

**Comment by AliasIO** [comment]
The method used for detecting the application was too broad and resulting in a lot of false positives; it was showing up everywhere. Since it was deprecated anyway we decided to remove it.
