### ISSUE TITLE
Wrong framework (Ink) detected

### ISSUE THREAD

**Issue by Dascr32** [AliasIO/Wappalyzer#1175]
Hi, recently this framework [Ink](http://ink.sapo.pt/) started to appear in a lot of websites that previously hasn't been detected. For instance in [tryruby.org](http://tryruby.org) Ink appears in the detected technologys, but if you search in the source for ```ink-``` (used in ink for css classes) not a single match is found.

![wap](https://cloud.githubusercontent.com/assets/10204977/16028106/198a1814-3199-11e6-8738-6526acfa6ea6.PNG)

Some other sites where ink is "detected":
* [Stackshare.io](http://stackshare.io/python)
* [Reddit](https://reddit.com)

Hope it helps.

**Comment by dipeshYnot** [comment]
Ink advertising?

**Comment by Jesse97** [comment]
Every single `script` tag with 'ink' somewhere in the `src` is matched by this.

For example the url `http://www.google-analytics.com/plugins/ua/linkid.js` is matched because l**ink**id.js

It should probably only be detected by the stylesheet or with more specific JS-regex.

**Comment by francocorreasosa** [comment]
Just came to post the same. It's time to **get this fixed** or _unlist_ Ink framework from Wappalyzer.

**Comment by AliasIO** [comment]
Fixed in f04a83121bc8b9e98a3ae991ef2cf28c999ee686.

**Comment by svarc** [comment]
as of today wappalyzer havent applied the patch that is fixing the false detection of Ink framework, so its more than obvious that either Ink is developed by someone close to the devs of wappalyzer or Ink is advertising them selfs this way...
are you fucking kidding me? there is someone dumb and ignorant enough in the team of wappalyzer that is detecting the Ink framework using this regular expression "<link [^>]*href=\"[^\"]+ink(?:\\.min)?\\.css" WTF?!

**Comment by AliasIO** [comment]
Did you see my last comment?

**Comment by klonos** [comment]
@AliasIO don't mind @svarc. He's only 5yo.
