### ISSUE TITLE
web framework ink.sapo.pt detected but not used

### ISSUE THREAD

**Issue by megcgo** [AliasIO/Wappalyzer#1189]
The web framework ink.sapo.pt is being detected in many websites but it isnt used on that sites..

**Comment by rondog** [comment]
I've been noticing this for a couple weeks. There is no way sites like reddit or linkedin is using this framework

**Comment by Nuruddinjr** [comment]
I also confirm this , many sites showing using Ink framework

**Comment by klonos** [comment]
Known issue I believe (#1175). Fixed but only after the latest release was out.

**Comment by megcgo** [comment]
It has already been fixed on issue #1175 
Maybe next update it will be ok. 👍

**Comment by klonos** [comment]
> Maybe next update it will be ok.

Exactly what I meant to say.
