### ISSUE TITLE
PDOException: SQLSTATE[HY000] [1040] 

### ISSUE THREAD

**Issue by bensonkb** [AliasIO/Wappalyzer#1192]
https://wappalyzer.com/applications/nodejs

Error

The website encountered an unexpected error. Please try again later.
Error messagePDOException: SQLSTATE[HY000] [1040] Too many connections in lock_may_be_available() (line 167 of /srv/wappalyzer.com/includes/lock.inc).

![image](https://cloud.githubusercontent.com/assets/4044180/16558726/2deecb02-4205-11e6-899f-07e7f155d730.png)

**Comment by AliasIO** [comment]
That's fixed now, thanks.
