### ISSUE TITLE
Wrong library detected: Ink Web Framework

### ISSUE THREAD

**Issue by GreenRobot777** [AliasIO/Wappalyzer#1195]
On my site [krasota70.ru](http://krasota70.ru/
)

was detected **Ink Web Framework**, but i don't use this library:
[wappalyzer.com/applications/ink](https://wappalyzer.com/applications/ink)

**Comment by klonos** [comment]
Already reported and fixed: #1189 / #1175 

...close this issue and patiently wait for the next version.
