### ISSUE TITLE
more options in settings menu 

### ISSUE THREAD

**Issue by Georgiel** [AliasIO/Wappalyzer#1197]
I'll be honest,  I can't think of what exactly (other than options for the icon such as fixed icon or fixed with count number) 

But it feels incredibly sparse and I'm sure there must be something.

**Comment by AliasIO** [comment]
Please let me know if you think of something, I don't want to add options for the sake of it. Fewer options means less maintenance, fewer bugs and more consistency. I'm a advocate of simple tools that do one thing well.

**Comment by Georgiel** [comment]
Option for fixed icon and option for fixed icon with counter.
