### ISSUE TITLE
wink and ink get detected on almost all websites that have ink in their name / content

### ISSUE THREAD

**Issue by timneutkens** [AliasIO/Wappalyzer#1206]
Title says it all.. but just take a close look at https://wappalyzer.com/applications/ink and https://wappalyzer.com/applications/wink. I work on a website that has the common dutch `winkel` (shop in english) suffix. All websites that have that suffix get a false positive on wink and ink.

**Comment by timneutkens** [comment]
Don't know if it's true.. but I have a feeling that ink even matches `<link>` tags

**Comment by alxs** [comment]
Actually this happens not only for domains with ink in their name. It even happens on local IP development servers sometimes on project of my own (where I haven't used Ink of course).

**Comment by timneutkens** [comment]
Yeah if you look at the stats sites like linkedin reddit etc get mentioned. But they don't actually use it.

**Comment by croshad** [comment]
Noticed this to. I was puzzled as to the popularity of Ink until i realized it's a bug.

**Comment by SlivTaMere** [comment]
The regex also match stuff like <script type='text/javascript' src='./assets/min-js/creative-link.min.js?ver=3.16.7'/>
Not sure how to correctly fix it.

**Comment by szepeviktor** [comment]
False positive on https://www.chickenbanana.com **without** any `ink` link.

**Comment by AliasIO** [comment]
I'm removing Ink until there is a more reliable way to detect it.

**Comment by timneutkens** [comment]
@AliasIO I was thinking of this last week 👍 Thank you 😄
