### ISSUE TITLE
Angular Material is falsely added on every AngularJS site

### ISSUE THREAD

**Issue by zwacky** [AliasIO/Wappalyzer#1208]
Sites that don't use Angular Material but use ng1 are falsely attributed with using Angular Material.

e.g.
- https://angularjs.org/
- https://itunesconnect.apple.com
- https://www.justwatch.com/us

maybe relevant: #1075

**Comment by ScionOfBytes** [comment]
Possibly because of this:
https://github.com/AliasIO/Wappalyzer/blob/master/src/apps.json#L461
Having `angular` in the environment doesn't automatically indicate angular material.

**Comment by AliasIO** [comment]
Fixed in source, thanks!
