### ISSUE TITLE
Wapp's icon being displayed, instead of website platform's icon

### ISSUE THREAD

**Issue by KellanH** [AliasIO/Wappalyzer#1209]
Hey Wappalyzer folks,

Ever since my recent updated, I'm seeing your icon in the browser where it used to show the icon on the software being used on a website...
Ex: https://monosnap.com/file/cu69ynWnSrAbJd0bY1LO8eikmgrn5D.png

This website is on our platform - shopify - and not showing our icon. 

Love your extension. Hope we can fix this.

**Comment by AliasIO** [comment]
Duplicate of #1168. Chrome doesn't support SVG icons, we'll need to convert them to PNG during build.
