### ISSUE TITLE
popup location bug on multi monitor

### ISSUE THREAD

**Issue by webzorg** [AliasIO/Wappalyzer#1210]
If I have firefox on a primary monitor and I click on url bar technology icons, the popup with technology descriptions shows up on a secondary monitor. This is fixed if I move browser to second monitor, reactivate popup and move it back to primary monitor.

**Comment by gadcam** [comment]
It's not a bug of Wappalyzer, you shoukd submit it to Mozilla.
It occurs with GIMP and Adobe Acrobat Reader too.
