### ISSUE TITLE
Multiple 'X-Powered-By' headers not supported

### ISSUE THREAD

**Issue by Sirikon** [AliasIO/Wappalyzer#1213]
For example, I have a Node.js application deployed in Azure, and Azure uses IIS in front of Node.js to serve the content.

So, this happens:

```
Response headers from an application running Node.js as an Azure Website.

Content-Encoding:gzip
Content-Length:481
Content-Type:text/html; charset=utf-8
Date:Thu, 28 Jul 2016 19:43:26 GMT
ETag:##################
Server:Microsoft-IIS/8.0
Vary:Accept-Encoding
X-Powered-By:Express
X-Powered-By:ASP.NET
```

"X-Powered-By" is added two times, and technically, both are true.

Would be nice if the pluggin supports this.

**Comment by AlexByte** [comment]
http://http://blogs.msmvps.com/
> Cache-Control:no-store, no-cache, must-revalidate, post-check=0, pre-check=0
> Content-Length:91283
> Content-Type:text/html; charset=UTF-8
> Date:Wed, 31 May 2017 17:39:56 GMT
> Expires:Thu, 19 Nov 1981 08:52:00 GMT
> Link:<http://blogs.msmvps.com/wp-json/>; rel="https://api.w.org/"
> Pragma:no-cache
> Server:Microsoft-IIS/7.5
> **X-Powered-By**:PHP/5.6.30
> **X-Powered-By**:ASP.NET

**Comment by gadcam** [comment]
@Sirikon  @AliasIO  I think you can now close this issue.
