### ISSUE TITLE
"Wappalyzer has been upgraded" message tab every time chrome is starting

### ISSUE THREAD

**Issue by unsaame** [AliasIO/Wappalyzer#1214]
Hi,

I reckon it's not a life threatening issue, but only a minor nuisance: every time I start chrome, a tab opens telling me that the extension has been installed...

Since it also happens for web developer tools, I suspect it may be a chrome issue, but I thought I would mention it here!

Cheers

**Comment by AliasIO** [comment]
For what it's worth, you can turn off 'Tell me about upgrades' in the extension options.
