### ISSUE TITLE
Port to Microsoft Edge

### ISSUE THREAD

**Issue by Revod** [AliasIO/Wappalyzer#1217]
Here are the news about the tools to port the extension to Microsoft Edge Browser: http://mspoweruser.com/microsofts-new-tool-lets-developers-convert-their-chrome-extensions-to-edge-extensions/

I'm trying to port it for test but I having a problem here, Getting this:
_manifest.json  .background : Missing required property: persistent_
![image](https://cloud.githubusercontent.com/assets/10109689/17453861/6556e21c-5b52-11e6-9e6c-cad21760304f.png)

**Comment by Revod** [comment]
**Edit: Now Working on Edge Without problem 💯** 
![image](https://cloud.githubusercontent.com/assets/10109689/17454861/dc0eb760-5b73-11e6-8381-7bcd02fa062d.png)

**Comment by Georgiel** [comment]
why on earth should an outdated browser be supported?

**Comment by Revod** [comment]
@Georgiel [Microsoft Edge](https://www.microsoft.com/en-us/windows/microsoft-edge) an outdated browser? WTF

**Comment by Georgiel** [comment]
@Revod yeah, it's atrocious in its support of HTML5 and of new Javascript technologies.

**Comment by Borderliner** [comment]
@Georgiel Although I hate Microsoft's guts and everything she produces, Edge supports more HTML5 elements than Mozilla Firefox 47.
![edge](https://cloud.githubusercontent.com/assets/2098879/17641275/a43d29a6-612d-11e6-860d-ff59a9eb1c97.png)

**Comment by gadcam** [comment]
@Revod if you send a pull request with your changes to port Wappalyzer to Edge I think @AliasIO would be delighted to merge it!

**Comment by jeyaprakashk** [comment]
Is it possible to fork or pull request this.. I am very interested in this..

**Comment by AlexMagik** [comment]
Same here. would love this extension on my Edge..

**Comment by ScionOfBytes** [comment]
@GeorgeWL I think you're talking about the IE browsers? Edge is actually pretty good in its support. And I'm a very vocal disliker of IE.

**Comment by DaAwesomeP** [comment]
@Revod Wappalyzer has moved onto a WebExtension stack using Mozilla's polyfill. Sadly, Edge's API doesn't support Promises but does use the `browser` variable. Would you help to get the extension to work in Edge?

**Comment by AliasIO** [comment]
It's working in Edge now (8774fb6b86d3ef3d4fe09ffa7077e608b57934c2). Getting it into the Windows App Store is a bit of a process, hopefully I can get it approved soon.

**Comment by DaAwesomeP** [comment]
@AliasIO So why exactly does Microsoft use the `browser` variable but not support promises? Doesn't that mean that the entire polyfill must simple be hard-coded on a case-by-case basis?

**Comment by GeorgeWL** [comment]
@DaAwesomeP Hopefully they'll change there mind about that.

**Comment by AliasIO** [comment]
@DaAwesomeP They acknowledged the issue here: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/9421085/

**Comment by DaAwesomeP** [comment]
If you may, anyone watching this issue should click the "Me too" button (requires a Microsoft login). It looks like they haven't done anything about it since October 2016.

**Comment by gadcam** [comment]
@AliasIO  Maybe you could close it as won't fix ?

There are only 80 extensions available for Edge, Microsoft doesn't seem to make a lot of effort to enable extension to be in their store cf  https://www.microsoft.com/en-us/store/collections/edgeextensions/pc

**Comment by AliasIO** [comment]
Yeah. Their last feedback was that it 'failed to install' on 'Windows 10 Desktop'. Apparently they don't know how to install an Edge extension. No way to respond to it either.

**Comment by AliasIO** [comment]
Wappalyzer is now available on Edge:

https://microsoftedge.microsoft.com/addons/detail/mnbndgmknlpdjdnjfmfcdjoegcckoikn
