### ISSUE TITLE
Problematic dimensions for Apache.svg

### ISSUE THREAD

**Issue by stefanos82** [AliasIO/Wappalyzer#1219]
I have noticed Apache.svg's dimensions are `169x51`, but in [wappalyzer-build#L41](https://github.com/AliasIO/Wappalyzer/blob/master/bin/wappalyzer-build#L41) we can obviously see standard dimensions `30x30` for width and height conversion respectively.

Is there anything we can do about it @AliasIO ?

**Comment by AlexByte** [comment]
Now svg is square, but png is old.

**Comment by DaAwesomeP** [comment]
Why does the SVG need to be square? It seems to scale properly.

**Comment by AlexByte** [comment]
@DaAwesomeP Its because of #1291 . SVG file is updated, but its not converted to png, so in extension is using old version.

**Comment by DaAwesomeP** [comment]
@AliasIO why is it that [Firefox uses the SVGs](https://github.com/AliasIO/Wappalyzer/blob/69a7459b69540aeb1e432cd7f7e0b0da77c5d5fa/src/drivers/firefox/driver.js#L252) but [Chrome requires the icons to be converted](https://github.com/AliasIO/Wappalyzer/blob/69a7459b69540aeb1e432cd7f7e0b0da77c5d5fa/src/drivers/chrome/js/driver.js#L201)?

**Comment by AliasIO** [comment]
Chrome doesn't support SVG for the extension icon.

The PNGs should be regenerated every build, not sure why it would be using an older version.

**Comment by AlexByte** [comment]
@AliasIO 
![old version png](https://cloud.githubusercontent.com/assets/25251772/23240875/e32d8458-f980-11e6-876d-c59103346d2d.PNG)

**Comment by stefanos82** [comment]
@AliasIO: Also I wanted to ask, why do I see a different extension image for Express.js under Firefox and a different under Chrome?

On Chrome I see the black 'e' logo, but on Firefox I see a nearly transparent 'ex' extension.

Do we know whether Express.js decided to drop the black 'e' logo in place of the new one they use on their website?

**Comment by AliasIO** [comment]
They should be the same:

https://github.com/AliasIO/Wappalyzer/blob/master/src/icons/Express.png

**Comment by stefanos82** [comment]
Weird...I still get the old logo for some reason. 

By the way, on Firefox my version is 3.2.8 and on Chromium is 2.47.

Does this help a bit?

**Comment by stefanos82** [comment]
Interesting. After I posted my last message I decided to check something. I deleted the installed extension and reinstalled it; now I have 2.50 for Chromium.

How come it didn't update on Chromium? I use them on daily basis for web programming and could see it auto-upgraded a couple of days ago on Firefox.

**Comment by netforhack** [comment]
![image](https://cloud.githubusercontent.com/assets/1379437/24414824/20f232f8-13e8-11e7-922b-46d9b6e5ae42.png)
Wappalyzer 2.52 on Google Chrome. Problem is still where.

**Comment by AlexByte** [comment]
@netforhack Because [this](https://github.com/AliasIO/Wappalyzer/issues/1415)  issue isn't closed.
