### ISSUE TITLE
Incorrectly identified Nginx version.

### ISSUE THREAD

**Issue by dcreagh-loggly** [AliasIO/Wappalyzer#1221]
I use WPEngine to host my WP site and when I ran a scan using Wappalyzer, it reported they were running Nginx 1.1.19. 
According to WPEngine team, they are running 1.11.1

Please update Wappalyzer te recognize the current version. 

Thanks

**Comment by ScionOfBytes** [comment]
@dcreagh-loggly Can you provide a link to the page where this is happening?
