### ISSUE TITLE
Enable detection using a JavaScript function

### ISSUE THREAD

**Issue by gadcam** [AliasIO/Wappalyzer#1226]
What about adding a new field named something like "test" where you can add a function that would return True when the application is present and False otherwise ? (or a version number..)
See https://github.com/johnmichel/Library-Detector-for-Chrome/blob/master/library/libraries.js.
What do you think @AliasIO ?

**Comment by AliasIO** [comment]
I'm not a fan of the idea as it can interfere with JavaScript on web pages. Wappalyzer does inject a script but it's very minimal, just to read variables in the window object.

**Comment by simonbrunel** [comment]
That would definitely help to determine the exact version number of a library loaded, for example, from a CDN that allows version range (https://cdn.jsdelivr.net/npm/chart.js@2/dist/Chart.js). Here, the detected version is `2` but it serves version `2.6.0`.

Though, I totally agree that running (potentially random) code inside web pages is not ideal for performance, neither for security. I really don't know what would be a better alternative (I'm sure you already spent time to figure out), maybe `env` could accept an extra parameter to test the string representation of the value of matching variables:

```javascript
// global variable
chartjs_version = '2.6.0';   
```

```json
// apps.json
"env": "^chartjs_version$\\;value:^([\\d.]+)$\\;version:\\1"
```
