### ISSUE TITLE
Adding Category: Live Chat

### ISSUE THREAD

**Issue by WydD** [AliasIO/Wappalyzer#1229]
I feel it does not belong in other categories like "Comment Systems".
Some of the technologies: [LiveChat](https://www.livechatinc.com/), [UserLike](https://www.userlike.com/) and [Tawk.To](https://tawk.to)

Assuming category id is number 52, here's the snippet of those technologies

``` javascript
"LiveChat": {
    "cats": [
        52
    ],
    "script": "cdn\\.livechatinc\\.com/staging/tracking\\.js",
    "website": "livechatinc.com",
    "icon": "LiveChat.png"
},
"UserLike": {
    "cats": [
        52
    ],
    "script": [
        "userlike\\.min\\.js",
        "userlikelib\\.min\\.js"
    ],
    "website": "userlike.com",
    "icon": "UserLike.png"
},
"Tawk.to": {
    "cats": [
        52
    ],
    "script": "embed\\.tawk\\.to",
    "website": "tawk.to"
}
```

edit: sorry for the early post

**Comment by WydD** [comment]
I prepared a branch in our repository https://github.com/datapublica/Wappalyzer/tree/chat with locales only for en and fr (and with the three technologies included). Tell me if you want a PR.

**Comment by AliasIO** [comment]
Yes please!

**Comment by WydD** [comment]
And done
