### ISSUE TITLE
In-page Banner Checks?

### ISSUE THREAD

**Issue by kingthorin** [AliasIO/Wappalyzer#1236]
Have you considered adding checks for in-page banners, such as those default on say Tomcat's bundled error pages?

A few example images (note the version info toward the bottom of the page....) : 
- http://i.stack.imgur.com/W3hdM.png
- http://www-01.ibm.com/support/docview.wss?uid=swg21429470&aid=1

Tomcat is the example that comes to mind when I think of this behavior, however, I'm sure it isn't unique.

**Comment by AliasIO** [comment]
Not sure if I understand the suggestion correctly, but that's just HTML isn't it? No reason Wappalyzer wouldn't be able to use it.

**Comment by kingthorin** [comment]
I guess the suggestion is just that the team or project enumerate/consider such patterns for existing matchers and when adding new ones.

**Comment by AliasIO** [comment]
Sure. I'll close this issue but you're welcome to submit a pull request to include this.
