### ISSUE TITLE
Please detect NodeBB forum

### ISSUE THREAD

**Issue by dandare76** [AliasIO/Wappalyzer#1243]
The NodeBB forum software is NOT detected by your toolbar. Please detect it. Thank you.

**Comment by craiglondon** [comment]
@dandare76 Could you provide some more information about this product?  URL?  Sample of where it is used?

**Comment by dandare76** [comment]
NodeBB is a forum software based on Node .JS. The main URL is https://nodebb.org/

Some examples of use:

https://community.nodebb.org/
https://forum.nfcring.com/
http://forum.leet.cc/
http://forum.tradle.io/

**Comment by ScionOfBytes** [comment]
@dandare76 Maybe make a PR?

**Comment by craiglondon** [comment]
https://github.com/AliasIO/Wappalyzer/pull/1458
