### ISSUE TITLE
e10s: Mark your addon as compatible

### ISSUE THREAD

**Issue by rugk** [AliasIO/Wappalyzer#1244]
Please change the manifest file to show that this add-on supports e10s.
Currently [ACP](https://addons.mozilla.org/de/firefox/addon/add-on-compatibility-reporter/) shows that it might not support e10s.

This is a follow-up of https://github.com/AliasIO/Wappalyzer/issues/996
(I just created a new issue for this now, so that it is not overlooked)

**Comment by DaAwesomeP** [comment]
This issue will be obsolete when v4 is pushed to Mozilla.
