### ISSUE TITLE
Virus in wappalyzer...

### ISSUE THREAD

**Issue by yuri25** [AliasIO/Wappalyzer#1246]
What is this?
chrome-extension://gppongmhjkpfnbhagpmjfkannfbllamg/options.html

**Comment by q--** [comment]
chrome-extension is the protocol used by Chrome for internal pages of
extensions; gppongmhjkpfnbhagpmjfkannfblla is the unique ID of the
Wappalyzer extension; and options.html is the name of the HTML file of the
Wappalyzer options page, which you can open by right-clicking the
Wappalyzer icon and then choosing "Options".

I see nothing suspicious about this. Do you have anything indicating there
might be something wrong?

(I'm not the owner of the extension by the way, just a contributor.)

2016-09-14 12:34 GMT+02:00 Yuran <notifications@github.com>:

**Comment by DaAwesomeP** [comment]
This is how Chrome identifies extensions. The URL accesses the extension's internal pages. This ID system works better than names in case two extensions have the same/similar name or odd characters. All extensions that package webpages to use with itself work this way. If you go to the official extension page in the Chrome Web Store, you'll see the same ID in the URL. You can Google it if you don't trust me or use this link: https://chrome.google.com/webstore/detail/wappalyzer/gppongmhjkpfnbhagpmjfkannfbllamg?hl=en

**Comment by ScionOfBytes** [comment]
I think this issue can be safely considered closed?
