### ISSUE TITLE
Wappalyzer list doesn't show in Chrome 53

### ISSUE THREAD

**Issue by lee-tms** [AliasIO/Wappalyzer#1257]
As you can see from the video, when you click on the icon the list now longer appears to show all of the technologies detected.

![wappalyzer](https://cloud.githubusercontent.com/assets/5928040/19033880/9627931c-8958-11e6-801a-2310008a7d9b.gif)

Using Chrome 53.0.2785.143 m
Win 10 with anniversary update

**Comment by neilhem** [comment]
Using Chrome Version 53.0.2785.143 m (64-bit)
Windows 10 with anniversary update
**Everything works fine**

**Comment by lee-tms** [comment]
Tried uninstalling and re-installing. No change.

If I use the bookmarklet I sometimes get a corner of the window that show appear, but no more than a small square. The bookmarklet works fine.

**Comment by lee-tms** [comment]
Looks like it was an issue with Chrome (I suspect installing Opera caused some sort of conflict). Uninstalling and re-installing Chrome fixed it.
