### ISSUE TITLE
Extension Tracks CMS, more Information on Website shows no results

### ISSUE THREAD

**Issue by rainerSchoenherr** [AliasIO/Wappalyzer#1261]
Recently the CMS Sulu was added to the knows CMS Systems in Wappalyzer.
The extension in the browser correctly shows the CSM Sulu used for example on sulu.io, keuchengoetter.de, www.intive.com, ....
But the more information area on the wappalyzer Website shows no website list, where Sulu is used. 
I have allowed the extension option  'Anonymously send reports on detected applications to wappalyzer.com for research' 
Whats wrong?
Thanks for your help.
Rainer

**Comment by AliasIO** [comment]
There is a threshold to show information on the website. If the number of websites is very small, it won't display.
