### ISSUE TITLE
All the websites are using React

### ISSUE THREAD

**Issue by musicq** [AliasIO/Wappalyzer#1262]
In my Wappalyzer, all the websites are using react, even they are not.

In fact this website is using angular2...

![image](https://cloud.githubusercontent.com/assets/8630596/19209603/5d2a02ac-8d40-11e6-8f5f-08fcbee9fad1.png)

**Comment by mukilarasan101** [comment]
@musicq , it may be due to one of your addons. Can you please disable all the  addons except Wappalyzer and check  it again.

**Comment by musicq** [comment]
@mukilarasan101 , yep! You are right. It seems one of my chrome plugins cause the problem.
