### ISSUE TITLE
Ignore js errors

### ISSUE THREAD

**Issue by chamnap** [AliasIO/Wappalyzer#1264]
Some websites have javascript errors, then causes `Wappalyzer` not be able to do the job with `phantomjs` driver. Is there any workaround to solve this problem?

```
$ /usr/local/bin/phantomjs --disk-cache=yes --load-images=yes --ignore-ssl-errors=yes --ssl-protocol=any lib/wappalyzer/driver.js http://www.iuoe649.org/

Here is the command output: STDOUT:

{"url":"http://www.iuoe649.org/","originalUrl":"http://www.iuoe649.org/","applications":[]}


STDERR:

TypeError: undefined is not a constructor (evaluating '$("#people-sortable").tablesorter({sortList: [[3,0]], headers: { 0: { sorter: false }, 4: { sorter: false }, 5: { sorter: false } }})')
```

I did try the `ruby` driver, but it gave far less information than the `phanthomjs`.

**Comment by AliasIO** [comment]
Fixed in 14c537fbc0e911fa403c3ed8d6f60f16995f5296, thanks. In addition you can use the `--quiet` flag to suppress error output.

**Comment by chamnap** [comment]
I did the same thing as you did, but inside my private repo. :)

**Comment by AliasIO** [comment]
Should have submitted a pull request. ;)
