### ISSUE TITLE
Multiple 'Server' headers not supported

### ISSUE THREAD

**Issue by Fahrradflucht** [AliasIO/Wappalyzer#1265]
Related to #1213 

If there are more then one `Server` fields in the header the second one overwrites the first.

This means that

```
HTTP/1.1 200 OK
Cache-Control: max-age=0, private, must-revalidate
Content-Length: 2688
Content-Type: text/html; charset=utf-8
Date: Mon, 17 Oct 2016 11:41:36 GMT
Server: Caddy
Server: Cowboy
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: o0gof32l10r52q123vksbrn5put04iai
X-Xss-Protection: 1; mode=block
```

will result in Wappalyzer showing Cowboy but not Caddy.

**Comment by sihaelov** [comment]
Could you provide any related website?

**Comment by Fahrradflucht** [comment]
The request I provided is from https://sozialoekonomie.klausurenarchiv.de/.

**Comment by AliasIO** [comment]
Duplicate of 1213.
