### ISSUE TITLE
UMI.CMS

### ISSUE THREAD

**Issue by UksusoFF** [AliasIO/Wappalyzer#1269]
UMI.CMS
Site: http://www.umi-cms.ru/
Icon: http://www.umi-cms.ru/favicon.ico
Detect:
```
<html xmlns:umi="http://www.umi-cms.ru/TR/umi" xmlns:xlink="http://www.w3.org/TR/xlink">
```

**Comment by wesharehoodies** [comment]
Not sure what the issue is. Could you elaborate?

**Comment by UksusoFF** [comment]
@wesharehoodies current version Wappalyzer not detect this CMS. So this is feature request.

**Comment by UksusoFF** [comment]
Why not detect yet? :(
