### ISSUE TITLE
increase script identification matrix

### ISSUE THREAD

**Issue by raininja** [AliasIO/Wappalyzer#1274]
Thanks for your work. 

It seems that the plugin doesn't identify every script, it seems, correctly.  I'm willing to work with you to widen the range of the plugin's ability to correctly name more scripts.

**Comment by AliasIO** [comment]
You're very welcome to help out. Please seen the wiki on how to contribute and feel free to open an issue if you need a hand with anything.

https://github.com/AliasIO/Wappalyzer/wiki/Contributing
