### ISSUE TITLE
NPM Produces different result from Chrome & Firefox extensions

### ISSUE THREAD

**Issue by benmcginnis** [AliasIO/Wappalyzer#1278]
Hi @AliasIO , 
I've been working with the NPM version of Wappalyzer and I noticed some sites unexpectedly coming back with nothing.  This site for example: http://thrive4lifenow.com/ comes back as Wordpress and a whole host of other things from the browser extensions (see screenshots).
![chrome](https://cloud.githubusercontent.com/assets/1206953/20355169/6bb9e55e-abee-11e6-8d2b-2e49311e4ba6.png)
![firefox](https://cloud.githubusercontent.com/assets/1206953/20355170/6bbfe1de-abee-11e6-9f76-75b54f58f65e.png)

However, when I modify the [check.js](https://github.com/AliasIO/Wappalyzer/blob/master/src/drivers/npm/check.js) to test it like so:
``` js
var wappalyzer = require("./index");

var options={
  url : "http://thrive4lifenow.com/",
  hostname:"thrive4lifenow.com",
  debug:true
}

wappalyzer.detectFromUrl(options,function  (err,apps,appInfo) {
  console.log(err,apps,appInfo);
})
```
and run it with `NODE_ENV=testing node check.js`
the output comes back as `null null undefined`.

This seems very strange to me.  Is there something I'm doing incorrectly with the npm version?

**Comment by benmcginnis** [comment]
@AliasIO if you could just give me a hint as to why this would be different I can take a more detailed dive on my own.

**Comment by AliasIO** [comment]
I'd recommend using the PhantomJS driver. The main difference is that the NPM driver doesn't evaluate JavaScript on web pages.
