### ISSUE TITLE
Top 1 Million Websites

### ISSUE THREAD

**Issue by RiaanBurger** [AliasIO/Wappalyzer#1283]
Alexa retired their free top 1 million websites list:

https://s3.amazonaws.com/alexa-static/top-1m.csv.zip now serves this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Need Alexa Top Sites data?  Find our APIs here: https://aws.amazon.com/alexa/ -->
```

No notice, but its confirmed:

https://twitter.com/Alexa_Support/status/800755671784308736

This list is used by so many security researchers as a seed (and by casual users like myself to make sites like http://topdrops.org/ which tracks the top Drupal CMS sites only).

Would it be possible to host a similar list from Whappalizer. If decent free hosting of it can be found, maybe for a weekly (but I'm sure for some a daily update would be best) updates, it will certainly highlight the paid-for options of Whappalizer which would help fund its development.

**Comment by jcrben** [comment]
Conclusion?
