### ISSUE TITLE
No info popup appears when clicking on icon(s) in Firefox

### ISSUE THREAD

**Issue by mark100net** [AliasIO/Wappalyzer#1284]
Firefox 50.0
macOS 10.12.1

Clicking on any icon saying "xxxx - Click for details - Wappalyzer" to the right of the address bar does nothing noticeable. 

Checked the dev console and see no error or message when clicking on the icon.

**Comment by ariq01** [comment]
Firefox 50.0.1
Windows 8.1

I got this problem too.
Seems like wappalyzer crash on updated firefox 
http://screencast.com/t/sHROdyENFa
