### ISSUE TITLE
Vagrant: "rsync was not detected as installed in your guest machine."

### ISSUE THREAD

**Issue by EvanGoss** [AliasIO/Wappalyzer#1288]
I'm trying to get the recommended dev environment setup and got the message below when running `vagrant up`.

```
Bringing machine 'default' up with 'docker' provider...
==> default: Docker host is required. One will be created if necessary...
    default: Docker host VM is already ready.
==> default: Syncing folders to the host VM...
"rsync" was not detected as installed in your guest machine. This
is required for rsync synced folders to work. In addition to this,
Vagrant doesn't know how to automatically install rsync for your
machine, so you must do this manually.
```

Hoping that this error was irrelevant, I immediately tried running `vagrant ssh` and received `=> default: The container is not currently running.` in response.

Any suggestions?  I'm new to Docker and Vagrant.

**Comment by benmcginnis** [comment]
I have this issue as well.

**Comment by dong77** [comment]
I'm experiencing the same issue

**Comment by flacle** [comment]
Same here, @EvanGoss did you find any possible solutions in the mean time?

**Comment by EvanGoss** [comment]
@flacle - Sorry, I haven't made any progress.

**Comment by EvanGoss** [comment]
Just to elaborate, I confirmed my Docker install is working by successfully running `docker run hello-world` and the nginx example from the [Get started with Docker for Mac](https://docs.docker.com/docker-for-mac/) page.

Running `vagrant up` results in the following output:
```
Bringing machine 'default' up with 'docker' provider...
==> default: Docker host is required. One will be created if necessary...
    default: Vagrant will now create or start a local VM to act as the Docker
    default: host. You'll see the output of the `vagrant up` for this VM below.
    default:
    default: Checking if box 'hashicorp/boot2docker' is up to date...
    default: Clearing any previously set forwarded ports...
    default: Clearing any previously set network interfaces...
    default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Forwarding ports...
    default: 2375 (guest) => 2375 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
    default: Running 'pre-boot' VM customizations...
    default: Booting VM...
    default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: docker
    default: SSH auth method: password
    default: Machine booted and ready!
==> default: Syncing folders to the host VM...
"rsync" was not detected as installed in your guest machine. This
is required for rsync synced folders to work. In addition to this,
Vagrant doesn't know how to automatically install rsync for your
machine, so you must do this manually.
```
Running `docker ps -a` allows me to confirm that the wappalyzer/dev container is not running, presumably due to the folder syncing issue.

Rsync is in the path of my local machine.

I tried modifying the Wappalyzer Vagrant file as follows (per [Vagrant's rsync doc page](https://www.vagrantup.com/docs/synced-folders/rsync.html), but got the same results:

```
Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", SYNCED_FOLDER, type: "rsync",
    rsync__args: ["--verbose", "--rsync-path='sudo rsync'"]
```

**Comment by flacle** [comment]
Perhaps this beats the purpose but I wanted to verify that rsync is the only issue preventing the image to run, adding
`config.vm.synced_folder ".", SYNCED_FOLDER, disabled: true`
bypasses it. In addition, I have upgraded rsync on my system to 3.2.1 with
`brew tap homebrew/dupes`
`brew install rsync`
to no avail - still getting the not detected error :(

**Comment by AliasIO** [comment]
I'm pushing up a new Docker image with rsync installed. Can you please try it again?

**Comment by EvanGoss** [comment]
Gladly!  https://hub.docker.com/r/wappalyzer/dev/ still says "last pushed: 4 months ago" so I guess it's still uploading.  I'll keep an eye out for the new image.

**Comment by AliasIO** [comment]
Should be there now.

**Comment by EvanGoss** [comment]
I deleted all existing wappalyzer containers and images and pulled down the new image.
```
$ docker images
REPOSITORY                            TAG                 IMAGE ID            CREATED             SIZE
wappalyzer/dev                        latest              b0cbf9d209b5        19 hours ago        468.9 MB
```
Same result after pulling down the updated image.
```
$ vagrant up
Bringing machine 'default' up with 'docker' provider...
==> default: Docker host is required. One will be created if necessary...
    default: Docker host VM is already ready.
==> default: Syncing folders to the host VM...
"rsync" was not detected as installed in your guest machine. This
is required for rsync synced folders to work. In addition to this,
Vagrant doesn't know how to automatically install rsync for your
machine, so you must do this manually.
```

**Comment by AliasIO** [comment]
Are you on OS X? Are you using Boot2Docker? Do you have rsync installed on your machine?

**Comment by EvanGoss** [comment]
Yes, OS X Sierra (v10.12.1).

rsync is installed and in the path
```
$ rsync --version
rsync  version 2.6.9  protocol version 29
Copyright (C) 1996-2006 by Andrew Tridgell, Wayne Davison, and others.
<http://rsync.samba.org/>
Capabilities: 64-bit files, socketpairs, hard links, symlinks, batchfiles,
              inplace, IPv6, 64-bit system inums, 64-bit internal inums
```
I'm not using Boot2Docker.  I have Docker for Mac v1.12.3 (13776).

**Comment by tdigangi5** [comment]
I know this thread is a little old but I am currently struggling with the same bug. Has there been any solution identified for this?

**Comment by EvanGoss** [comment]
Not by me. I haven't had any time to put into it. I'd make time to work on the code, but I don't really want to spin my wheels on getting the environment working.

**Comment by wardoost** [comment]
@EvanGoss Do you still have the rsync error? I had some problems too when using Boot2Docker with VirtualBox. I use Docker for Mac too but had to some settings to `Vagrantfile` to get it working. I described this in #1511

**Comment by markbosky** [comment]
I'm still having this issue as well on Mac OS X Sierra using latest dmgs of Vagrant and docker

**Comment by EvanGoss** [comment]
@wardoost I'll have to try what you described in 1511 and report back.

**Comment by AliasIO** [comment]
I removed Vagrant. With Docker installed, you can now run `./run` to access the dev tools.

Converting SVGs to PNGs doesn't work for some reason so I've commented it out in the build script for now.
