### ISSUE TITLE
Where to get wappalyzer.js and iframe.js source code?

### ISSUE THREAD

**Issue by EvanGoss** [AliasIO/Wappalyzer#1290]
I'm trying to work on the Chrome extension and these two files are in the .gitignore file.  Where can I find them or instructions on recreating them?

```
/src/drivers/chrome/js/wappalyzer.js
/src/drivers/chrome/js/iframe.js
```

I don't know if this is related, but I'm attempting to work on the Chrome extension without setting up the recommended Docker image because I got stuck getting that environment setup ([opened separate issue](https://github.com/AliasIO/Wappalyzer/issues/1288)).

**Comment by AliasIO** [comment]
The easiest way to get this to work is by running the Vagrant development environment, see the README. Alternatively you can run the `bin/wappalyzer-links` in a UNIX-like environment but this requires some manual preparation (such as defining the `$WAPPALYZER_ROOT` environment variable). Essentially those files are symlinked from the `src` folder.

**Comment by EvanGoss** [comment]
Thanks!
