### ISSUE TITLE
Incorrect icon in site vk.com

### ISSUE THREAD

**Issue by henrooster** [AliasIO/Wappalyzer#1291]
Hello! On site vk.com incorrect browser extension icon. See screenshot 
![image](https://cloud.githubusercontent.com/assets/5254654/20924510/c34a4514-bbc2-11e6-9314-7e34fd33fcb1.png)

**Comment by AliasIO** [comment]
Looks like the Apache SVG does get converted to a PNG correctly.

**Comment by stefanos82** [comment]
@AliasIO I have already reported this a long time ago; 

it's bug #1219, can we do something about it?

Also, another problem comes with Angular2. As soon as wappalyzer runs for identification, I can see which tools or services have been recognized but for default icon on wappalyzer toolbar I get a gray icon, nothing else.

Can we do something about it?

Cheers.

**Comment by stefanos82** [comment]
Please re-open this issue as it has not being resolved.

Browser: Google Chromium
Version: `57.0.2987.98`

Browser: Mozilla Firefox ESR
Version: `45.8.0`

Wappalyzer: `2.52`

OS: GNU / Linux Debian 9.0 (testing), 64-bit

The issue with Chromium is the same as @henrooster has pointed at as in the [first comment](https://github.com/AliasIO/Wappalyzer/issues/1291#issue-193752042), whereas in Firefox I get an empty extension icon which I have to click on that area to see what kind of apps have been detected.

**Comment by gadcam** [comment]
The current version of Wappalyzer for Firefox is <code>3.2.11</code>.
Could you please update the addon and tell us if everything is working then ?

**Comment by stefanos82** [comment]
@gadcam first of all, allow me to apologize for not providing the Firefox wappalyzer version; I thought I did.

My version is the one you have just mentioned.

Does this help in any way?

If there's anything else you would like me to double-check, please let me know.

Cheers.
