### ISSUE TITLE
Have Webhosting service Application Catagory

### ISSUE THREAD

**Issue by mehranxs** [AliasIO/Wappalyzer#1292]
Hello as you may know lots of hosting companies add their header in request for service on their shared or managed servers
it would be great if have a "Hosting Service" or "Hosting Company" as application category
Thanks all

**Comment by AliasIO** [comment]
Sure, let's call it 'Web Host'. Do you want to add it?

**Comment by mehranxs** [comment]
Hello
Yes it could be 
Web host
Or 
Hosting provider
Or hosting service provider 
We would be happy to register our self on that category 
Is it possible that wapplyzer analyze dns records and base on that decide what provider that site use? Absolutely beside of request headers 
Thanks

**Comment by AliasIO** [comment]
It can't be a DNS lookup, the information has to be present in the page response somehow.

**Comment by mehranxs** [comment]
i think hosting could add X-Hosted By or X-HostingService
when it wil be added and we and others could add their headers ?
