### ISSUE TITLE
Doesn't work on Firefox Nightly

### ISSUE THREAD

**Issue by ouraios** [AliasIO/Wappalyzer#1295]
The extension of Wappalyzer doesn't work on Firefox Nightly, icons doesn't show up either in URL bar or like a button.

**Comment by klonos** [comment]
I confirm this (and if I'm not mistaken, there's an issue filed for it already). It's been happening for some weeks now.

**Comment by AliasIO** [comment]
Which version on you on? It's working for me on 51.0a2.

**Comment by klonos** [comment]
I'm on latest 53.0a1 nightly (build 20161215061212)

Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:53.0) Gecko/20100101 Firefox/53.0 ID:20161215061212 CSet: c750a7de1194d71f2d2ef73f6a919d26b9640cae

**Comment by infomast** [comment]
Doesn't work on 54.0a1 (2017-02-13) (32 bits) either.

**Comment by AliasIO** [comment]
The WebExtension port is coming soon. You can try it out now:

https://github.com/AliasIO/Wappalyzer/tree/master/src/drivers/webextension

**Comment by DaAwesomeP** [comment]
Hi all,
You're probably having an issue related to e10s. Please try out the WebExtension.

@aliasio I recently submitted a new Opera and Firefox addon. The Opera moderators are very picky about the manifest, so there will need to be two separate packages. I'll have a pull soon.
