### ISSUE TITLE
Timeout on facebook

### ISSUE THREAD

**Issue by KrishMunot** [AliasIO/Wappalyzer#1301]
Doesn't work on any Facebook's domains.

**Comment by ScionOfBytes** [comment]
@KrishMunot Agreed it doesn't work on facebook domains, but is that happening due to a timeout or some other issue?

**Comment by KrishMunot** [comment]
@ScionOfBytes Not really, the pages load fine, but the info from the extensions don't load at all

**Comment by ScionOfBytes** [comment]
@KrishMunot Cool, so it's not a timeout issues. It's a failed detection issue.
