### ISSUE TITLE
Incorrect icon (WP) on the ProcessWire Sites

### ISSUE THREAD

**Issue by kasu64** [AliasIO/Wappalyzer#1306]
In the ProcessWire site, (and all created with PW)
Wappalyzer shows the WordPress Icon...

Look at the attached printscreen...

Can you change it, please ?

Many Thanks

Kasu64

![selection_999 064](https://cloud.githubusercontent.com/assets/1710109/21904546/54714fe8-d904-11e6-9578-15f9147c47db.png)

**Comment by jhewt** [comment]
Uhm, what's your wappalyzer version? There's no way that the plugin itself would detect Facebook, a flash element, bootstrap, wordpress, twitter, IIS, PHP, comscore, etc on that site.
Try disabling all of your active plugins and only leave wappalyzer and check again.

This is using the 2.49 version on Firefox 50.1
![captura](https://cloud.githubusercontent.com/assets/3622160/21960756/e89cef26-dad3-11e6-8cb1-4c31ecc9fa9e.JPG)

**Comment by ScionOfBytes** [comment]
Very different results for me:
![image](https://cloud.githubusercontent.com/assets/5138570/22190571/1fec4568-e14a-11e6-8ed5-d28928aad11f.png)

You should try with all your extensions disabled, @kasu64
