### ISSUE TITLE
BigCommerce is wronly detected

### ISSUE THREAD

**Issue by ptahchiev** [AliasIO/Wappalyzer#1325]
Hello,

from what I can tell here:

https://github.com/AliasIO/Wappalyzer/blob/master/src/apps.json#L825

You are trying to detect a javascript object that will match the `$compareProducts^` regex and if it exists you conclude the customer is using BigCommerce. This is really shallow - in my code I have the javascript following function:

````
function compareProducts() {
````

and becase of that you think I use BigCommerce, which I'm **not**.

**Comment by twindual** [comment]
Would you mind giving the site URL where this is incorrectly detecting BigCommerce?

**Comment by ptahchiev** [comment]
Here you go: http://blackbetty.com/
