### ISSUE TITLE
Drupal 8

### ISSUE THREAD

**Issue by landsman** [AliasIO/Wappalyzer#1329]
Hi, 
is possible add detection of this new version Drupal?
Thanks!

**Comment by jvoisin** [comment]
It's already implemented (you can check this [here]( https://www.drupal.com/why-drupal-8 )).

**Comment by landsman** [comment]
I was test about five sites and it working good. Thanks!

**Comment by jvoisin** [comment]
Feel free to close this issue then.

**Comment by landsman** [comment]
It must close @AliasIO i think
