### ISSUE TITLE
Umbraco detection

### ISSUE THREAD

**Issue by markwemekamp** [AliasIO/Wappalyzer#1333]
I was looking into the detection of Umbraco and I see the script is looking for /umbraco/login.aspx
This is working great for older versions, but in version 7 and up the login is moved to /umbraco

It would be nice if both ways were implemented

**Comment by jvoisin** [comment]
Please provide a website demonstrating this behaviour, I'll implement that.

**Comment by markwemekamp** [comment]
The Umbraco.com website runs on the new version. You can view the backend login at this url: https://umbraco.com/umbraco

**Comment by jvoisin** [comment]
Umbaco is successfully detected, what else do you want?

(also, feel free to open a pull-request instead ;) )

**Comment by markwemekamp** [comment]
Oh I see, Umbraco.com is probably being detected because of it's domain
www.carlsberg.com runs on Umbraco but is not detected

I would love to do some pull requests for this project in the future, can't do it on a short term unfortunetaly

**Comment by jvoisin** [comment]
http://www.carlsberg.com/umbraco is successfully detected as Umbraco too.

**Comment by markwemekamp** [comment]
Yes that´s the admin panel, but the front-end (carlsberg.com) of the website is not being detected as Umbraco.

**Comment by jvoisin** [comment]
Sure, but how do you think that it could be detected?
I fail to see any distinctive way of achieving this.

**Comment by markwemekamp** [comment]
Maybe I'm completely wrong, but I was under te impression that the following line did the same for the older versions:

"url": "/umbraco/login\\.aspx(?:$|\\?)",

So if the /umbraco/login.aspx page responds, the website is marked as an Umbraco website

**Comment by jvoisin** [comment]
Wappalyzer doesn't issue any request, so it will only detect umbraco when you're browser this specific url, or when the generator is `umbraco`, or when the webpage's content matches `powered by <a href=[^>]+umbraco`,or a header `X-Umbraco-Version`, or a global `Umbraco` javascript variable, …

**Comment by markwemekamp** [comment]
Ah I see, in that case I don't think it's possible to detect umbraco on the front-end

**Comment by jvoisin** [comment]
Me neither :)
Feel free to close this issue ;)
