### ISSUE TITLE
Add safari web extension support

### ISSUE THREAD

**Issue by futursolo** [AliasIO/wappalyzer#1343]
It would be nice if the safari web extension support could be added to this plugin.

https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/SafariExtensionsConversionGuide/Chapters/Chrome.html

**Comment by valentinocossar** [comment]
Please, add support for Safari extension.

**Comment by sunlee-newyork** [comment]
+1

**Comment by cybermatatu** [comment]
+1

**Comment by serhioli** [comment]
+1

**Comment by webjive** [comment]
+11

**Comment by phillips321** [comment]
+1

**Comment by mspaulding06** [comment]
+1

**Comment by davidyv** [comment]
+1

**Comment by matthinc** [comment]
+1

**Comment by shanbhardwaj** [comment]
+1

**Comment by jvoisin** [comment]
There is the handy :+1: thingy to upvote isues, instead of replying. This generates noise for contributor, and won't help your case :/

**Comment by simple-is-best** [comment]
+1

**Comment by StephenOwen07** [comment]
+1

**Comment by ruchern** [comment]
Hi,

Any update on the Safari extension?

**Comment by gadcam** [comment]
Hi @ruchern,
I am not aware of any work in this direction.
Do you want to try to do it ?
There seems to be some doc here : https://developer.apple.com/library/content/documentation/Tools/Conceptual/SafariExtensionGuide/ConvertingToSafari/ConvertingToSafari.html

**Comment by Aggr3ssor** [comment]
+1

**Comment by SergioSuarezDev** [comment]
+1

**Comment by kirillovapp** [comment]
+1

**Comment by michaelwoodruff** [comment]
+1

**Comment by AliasIO** [comment]
If someone wants to port the extension over to Safari, I'm happy to support it officially. I may get around to doing this myself eventually but prefer to wait until they support the WebExtension API.

**Comment by kyletaylored** [comment]
Man, what hot garbage this is.

https://stackoverflow.com/a/52555103/1539442

So it sounds like officially, it'll have to have some kind of Swift code around it to pass messages between the browser and extension. There was a neat workaround listed using a library called `JavascriptCore` in Swift so you don't have to re-write all that logic, but it still looks like a big haul.

**Comment by AliasIO** [comment]
Safari 14 finally supports WebExtensions and I ported Wappalyzer over. I'm in the process of getting it onto the App Store but there are a lot of hoops to jump through.  

<img width="594" alt="Screen Shot 2020-06-25 at 1 10 47 pm" src="https://user-images.githubusercontent.com/77259/89836675-a22cf500-dbaa-11ea-8d3d-9883289fef78.png">

**Comment by AliasIO** [comment]
Wappalyzer for Safari:

https://apps.apple.com/au/app/wappalyzer/id1520333300

**Comment by kyletaylored** [comment]
Safari support complete.
