### ISSUE TITLE
Jimdo not yet recognized

### ISSUE THREAD

**Issue by dominiklenne** [AliasIO/Wappalyzer#1347]
Jimdo is somthing like wix or squarespace. Nice to have.

**Comment by jvoisin** [comment]
Can you provide some url of websites using this particular software?

**Comment by dominiklenne** [comment]
Hi ,

you may look at https://www.labobineapois.com/
or some other from https://de.jimdo.com/beispiele/. 
I think you need to copy the urls into the address field to get to the original sites.

all the best

Dominik


Von: jvoisin 
Datum: Mittwoch, 8. Februar 2017 10:32
An: AliasIO/Wappalyzer 
Cc: dominiklenne ; Author 
Betreff: Re: [AliasIO/Wappalyzer] Jimdo not yet recognized (#1347)

Can you provide some url of websites using this particular software?
