### ISSUE TITLE
Wappalyzer interfering with Duo Dual Factor

### ISSUE THREAD

**Issue by sbubaron** [AliasIO/Wappalyzer#1348]
Been using Wappalyzer for years. Love the extension!

I just got back to work from vacation and noticed that Wappalyzer had been updated. 

During the course of my day I use a service that uses Duo Dual factor (https://duo.com/) and after authenticating successfully and getting the push notification on my phone, the session would terminate and state I had invalid credentials. My creds are good. 

After working with support we tracked the issue down to a cookie being issued from Duo that says I'm failing authentication. Tried clearing cookies in Chrome, but that didn't fix it. Tried a different browser and authenticated successfully. Tried Chrome Incognito mode and authenticated successfully. Disabled all extensions and tried normal Chrome and authenticated successfully. Enabled extensions one by one and found Wappalyzer to be the culprit. 

Not really sure whats going on under the hood, but this issue seems to be related to the latest release. 

Happy to help debug more if you have suggestions/questions. 

Thanks!

**Comment by AliasIO** [comment]
Would you be able to install Wappalyzer as an unpacked extension and inspect the 'background.html' view? It may show an error in the console.

https://github.com/AliasIO/Wappalyzer/wiki/Drivers#google-chrome

**Comment by sham0day** [comment]
I noticed a similar issue with Duo.  When I reach a website with the Duo prompt for my 2-factor authentication, after exactly 5 seconds the page switches to a server error that states: "Server error in '/' Application".  The page works fine with the Wappalyzer extension disabled.  This only started happening recently.  I'll check out the unpacked extension to look for an error.

**Comment by dvkndn** [comment]
@sham0day @sbubaron @AliasIO it is not really an error of Wappalyzer, but in the way the website (in this case Duo) handle postMessage

When Wappalyzer run as an extension, it can postMessage to the top parent under the origin of the current parent.

For example, if app.duo.com has auth.duo.com as an iframe, then app.duo.com will receive a message from Wappalyzer with the origin auth.duo.com

My suggestion is that you should check the way you handle message event, not only origin but also the syntax of the message

**Comment by AliasIO** [comment]
This should be fixed in the next update. Please re-open this ticket if the issue persists.
