### ISSUE TITLE
Use a default icons for applications

### ISSUE THREAD

**Issue by jvoisin** [AliasIO/Wappalyzer#1361]
[Some applications]( https://wappalyzer.com/applications ) do not have an icon, and thus are specified with a `default.png` one. It would be handy to use this icon by default when [none is provided ]( ee815119c7b3df100814dd1c9c1cbd5c1bd23b46 ).

**Comment by DaAwesomeP** [comment]
This can be closed as of #1512.

**Comment by jvoisin** [comment]
You're awsome ♥

**Comment by DaAwesomeP** [comment]
@jvoisin Nice pun. You're welcome.
