### ISSUE TITLE
iPresta details?

### ISSUE THREAD

**Issue by mehrshadz** [AliasIO/Wappalyzer#1367]
Hey,

As you can see [here](http://piltanshop.com), the Wappalyzer extension shows "iPresta" icon in the list but there is no further information about it, and when you click on it it only opens the Wappalyzer website and there is no "iPresta" in the list on website.

Could you please complete iPresta details?

Cheers

**Comment by jvoisin** [comment]
It doesn't show the *iPresta* account here, but Prestashop instead.

Also, the goal of Wappalyzer is to display what technologies are used on a website, not to document them.

**Comment by mehrshadz** [comment]
You may have checked with Mozila FireFox. It doesn't show iPresta there because it's not updated yet. But if you check with Google Chrome using Wappalyzer extension you can see the iPresta appears on the list.

You can see also the iPresta icon is listed here: https://github.com/AliasIO/Wappalyzer/tree/master/src/icons

I know Wappalyzer doesn't make a document of those technologies but each technology has a unique page on Wappalyzer website including sites using those technology (e.g. [here](https://wappalyzer.com/applications/jquery?pk_campaign=chrome&pk_kwd=popup)) but the iPresta doesnt have any page or any list of websites using it.

Thanks for your response

**Comment by jvoisin** [comment]
You're right, it works on Chrome :)

It seems that the website wasn't regenerated yet, this might explain why iPresta doesn't show up on it.
