### ISSUE TITLE
Removal of duplicate icons

### ISSUE THREAD

**Issue by jvoisin** [AliasIO/Wappalyzer#1379]
There are several duplicate icons in the source code:
- [ ] a-blog cms
- [ ] angular
- [ ] embedThis
- [ ] eCommercePy
- [ ] http2, HTTP2 and SPDY
- [ ] iCongo and Hybris
- [ ] Modrack, PhusionPassenger and Modrails
- [ ] Moment.sj and Moment Timezone
- [ ] Scheider and Schneider Web Server
- [ ] Sentinel
- [ ] Splunk and Splunkd
- [ ] Stackla
- [ ] Xiti
- [ ] [yahoo]( https://github.com/AliasIO/Wappalyzer/pull/1378 )

Do we want to clean this up?

**Comment by AliasIO** [comment]
Yep.

**Comment by powell759** [comment]
Searching through apps.json and the icon files

- a-blog cms does look like a duplicate (made a pull request for removal)
- I think Angular Material and Angular JS actually do have slightly different icons (one without border)

I can go through the rest and remove the duplicates / edit apps.json to reflect changes (like with the yahoo icons)

**Comment by jvoisin** [comment]
Be my guest :)
