### ISSUE TITLE
Bookmarklet doesn't detect the same technologies as Chrome extension

### ISSUE THREAD

**Issue by mammuth** [AliasIO/Wappalyzer#1386]
I'm using this bookmarklet (provided on wappalyzer.com on 24.02.2017):
`javascript: (function() { var d = document, e = d.getElementById('wappalyzer-container') ; if ( e !== null ) { d.body.removeChild(e); } var u = 'https://wappalyzer.com/bookmarklet/', t = new Date().getTime(), c = d.createElement('div'), p = d.createElement('div'), l = d.createElement('link'), s = d.createElement('script') ; c.setAttribute('id', 'wappalyzer-container'); l.setAttribute('rel', 'stylesheet'); l.setAttribute('href', u + 'css/wappalyzer.css'); d.head.appendChild(l); p.setAttribute('id', 'wappalyzer-pending'); p.setAttribute('style', 'background-image: url(' + u + 'images/pending.gif) !important'); c.appendChild(p); s.setAttribute('src', u + 'js/wappalyzer.js?' + t); s.onload = function() { s = d.createElement('script'); s.setAttribute('src', u + 'js/apps.js?' + t); s.onload = function() { s = d.createElement('script'); s.setAttribute('src', u + 'js/driver.js?' + t); c.appendChild(s); }; c.appendChild(s); }; c.appendChild(s); d.body.appendChild(c); })();`

Sadly, it doesn't detect all the technologies as the Chrome extension.

For example, it doesn't detect Django or Django CMS at all. Example sites:

- https://ofa24.de
- https://blueshoe.de
- https://control.divio.com/auth/login/

**ofa24.de**
On this page, the chrome extension detects the following:
<img width="232" alt="screen shot 2017-02-24 at 10 28 34" src="https://cloud.githubusercontent.com/assets/3121306/23298298/782c6ac2-fa7d-11e6-8b6c-83c4cd6a1b2b.png">

And the bookmarklet only:
<img width="255" alt="screen shot 2017-02-24 at 10 36 13" src="https://cloud.githubusercontent.com/assets/3121306/23298287/6ed7270a-fa7d-11e6-9b45-290b15973123.png">

**Comment by AliasIO** [comment]
The bookmarklet hasn't been updated in a little while but also has the limitation that it can't scan response headers. It's unable to pick up on many server-side applications for that reason.

**Comment by AliasIO** [comment]
I realised the bookmarklet does scan response headers but something was broken. I'll have a fix for this soon-ish.

**Comment by AliasIO** [comment]
Should be fixed.
