### ISSUE TITLE
Bookmarklet doesn't displays apps if url contains hash sign

### ISSUE THREAD

**Issue by AlexByte** [AliasIO/Wappalyzer#1394]
Although apps are detected.
![wapp hash](https://cloud.githubusercontent.com/assets/25251772/23393557/b14f5af2-fd94-11e6-9e2d-50c7ac72c3cf.png)

**Comment by AliasIO** [comment]
Fixed in 3a8e9e2896e26397f61e696c1519800f68ef3b1f. You'll need to grab the new bookmarklet from https://wappalyzer.com/download in a couple of days (the change takes some time to roll out).
