### ISSUE TITLE
Wappalyzer does not work on my website.

### ISSUE THREAD

**Issue by miklcct** [AliasIO/Wappalyzer#1395]
When I opens https://miklcct.com/ , Wappalyzer does not have any sign of detection, just like when the chrome home page is opened. It functions normally in the various web applications under that but not the home page which I have written in PHP.

![wappalyzer not working](https://cloud.githubusercontent.com/assets/2827264/23395968/3f9eac40-fdcc-11e6-8605-2778b665b2a9.png)

**Comment by jvoisin** [comment]
This is expected, because there is no sign at all on your webpage that you're using php. Your website could legitimately be written in Python or whatever; WappAlyzer can't divine technologies ;)

**Comment by miklcct** [comment]
My site has sent the appropriate headers:

````
HTTP/1.1 200 OK
Date: Tue, 28 Feb 2017 08:11:09 GMT
Server: Apache/2.4.10 (Debian) PHP/7.1.2-2+0~20170218111804.16+jessie~1.gbpb36eec OpenSSL/1.0.1t
X-Powered-By: PHP/7.1.2-2+0~20170218111804.16+jessie~1.gbpb36eec
Vary: Accept
Content-Security-Policy: default-src https:; script-src 'self'; style-src 'self'; object-src 'none'
Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block
Content-Length: 5155
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: application/xhtml+xml; charset=utf-8
````

**Comment by AlexByte** [comment]
It's because extension only analyzing headers if `Content-Type` is `text/html`. (https://github.com/AliasIO/Wappalyzer/blob/master/src/drivers/chrome/js/driver.js#L139)

**Comment by AlexByte** [comment]
@AliasIO I think it's worthwhile to analyze headers for all Content-Types.
