### ISSUE TITLE
Improve setup

### ISSUE THREAD

**Issue by wesharehoodies** [AliasIO/Wappalyzer#1410]
Hello, I would like to contribute, but the setup is already a pain in the ass.

![img](https://d1zjcuqflbd5k.cloudfront.net/files/acc_472088/SAve?response-content-disposition=inline;%20filename=Screen%20Shot%20on%202017-03-03%20at%2017%3A12%3A04.png&Expires=1488554268&Signature=MarEj9W8Bd3NtT03KiX1kwtxW3FXtCiqoo5ILdD2fT0eIYPilRCd3n4tPXB1wb766NYLb3ndkcNsLr445obvVMyZHg9ryOKFRPn86QvKVnX9eNLZepHam7qCgy~ftsexHguvYWqR5Crm6K~jWjnEX1Y0xIeqQzm5wXy7welx7LY_&Key-Pair-Id=APKAJTEIOJM3LSMN33SA)

Not sure what kind of password it's asking. How can we make this better?

**Comment by AlexByte** [comment]
Please reupload the image

**Comment by ezkl** [comment]
> Not sure what kind of password it's asking.
The image you posted doesn't load, but I assume the password you're looking for is the SSH password for boot2docker: https://github.com/boot2docker/boot2docker#ssh-into-vm

**Comment by AliasIO** [comment]
Try `tcuser` as the password. The setup does need work, especially on Mac OS.
