### ISSUE TITLE
Add hover labels to pie chart

### ISSUE THREAD

**Issue by richarddewit** [AliasIO/Wappalyzer#1413]
The color legend of all purple (?) colors is pretty hard to destinguish for colorblind(ish) people. Would you please add something like a label-on-hover?

**Comment by AliasIO** [comment]
Yep, that page and chart is still a work in progress. It's hard to find a set of colours that's on brand but contrasting at the same time.

**Comment by AlexByte** [comment]
@AliasIO It is possible to choose random contrasting colors.

**Comment by AliasIO** [comment]
Contrasting colour added.

https://www.wappalyzer.com/categories/ecommerce
