### ISSUE TITLE
iframe.js causes high cpu usage.

### ISSUE THREAD

**Issue by peterwang** [AliasIO/Wappalyzer#1419]
What's the purpose of this script file? 

I just had a quick look at the file and found that it searches in the DOM trees of all frames for something like Ads containers? How does this have anything to do with detecting technologies? 

What's more, it worries me that it collects and sends back lots of data without good reasons.
https://github.com/AliasIO/Wappalyzer/blob/master/src/drivers/chrome/js/driver.js#L227

I think issues #1407 and #1414 are caused by this.

Could you make this optional?

**Comment by jvoisin** [comment]
About the tracking thingy, you can disable it in the preferences I think.

**Comment by peterwang** [comment]
@jvoisin Thanks. Yes, you are right. The tracking can be disabled, however, disabling tracking does not stop iframe.js doing heavy DOM searching.

**Comment by DenisBitrix** [comment]
Disabling tracking also doesn't prevent my issue https://github.com/AliasIO/Wappalyzer/issues/1414

**Comment by AliasIO** [comment]
CPU issue should be fixed. Preventing the script from running when tracking is disabled is coming soon.

**Comment by jvoisin** [comment]
It would be nice to link the commit fixing the issue ♥
