### ISSUE TITLE
Adding some static analysis

### ISSUE THREAD

**Issue by jvoisin** [AliasIO/Wappalyzer#1425]
What about using something like [scrutinizer]( https://scrutinizer-ci.com/g/jvoisin/Wappalyzer/?branch=master ) to improve the code/find low-hanging bugs?

**Comment by craiglondon** [comment]
That's an impressive tool!   I recommend!

**Comment by altern8tif** [comment]
Seems like it doesn't support Javascript.

**Comment by jvoisin** [comment]
Of course it does, just click the link.

**Comment by AliasIO** [comment]
Great idea, not sure if it's worth €50/mo. We can incorporate something into the build script.

**Comment by craiglondon** [comment]
Ouch.  Yeah 50 euros is overly expensive for the size of this project.

**Comment by jvoisin** [comment]
>  We do not charge for open-source repositories, you can add as many as you like. 

;)

**Comment by jvoisin** [comment]
I'm currently running it on my fork, and it works fine.

**Comment by AliasIO** [comment]
Done. There's some work to do by the looks of it.

https://scrutinizer-ci.com/g/AliasIO/Wappalyzer/

**Comment by jvoisin** [comment]
Feel free to add the corresponding badge in the README file, next to the one from Travis-ci.

**Comment by jvoisin** [comment]
It would be interesting to add [CodeClimate]( https://codeclimate.com/ ) too.
