### ISSUE TITLE
Firefox WebExtension

### ISSUE THREAD

**Issue by DaAwesomeP** [AliasIO/Wappalyzer#1426]
Firefox is ditching the old Addon SDK and replacing it with WebExtensions. The Chrome addon may already be compatible (I haven't tried it), but there is one change to it that would be beneficial. Sadly, displaying all of the icons in the URL bar will be no longer possible, but [Firefox places the `pageAction` buttons/popups in the URL bar](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/pageAction), so at least the Wappalyzer button will still have the option of not cluttering the toolbar.

**Comment by AliasIO** [comment]
[I ported the Chrome extension to WebExtension](8b946ee3bf7847ce69dcedec5e50973403a1f2ef).

It works in Firefox but in Chrome the 'get_apps' `sendMessage` call doesn't get a response and doesn't populate the popup with detected applications. It looks like the [polyfill](https://github.com/mozilla/webextension-polyfill) may not be working as advertised.

**Comment by DaAwesomeP** [comment]
I tried running the WebExtension driver in FF, but it says that it's missing `js/iframe.js`.

**Comment by DaAwesomeP** [comment]
The WebExtension (in Firefox) doesn't work properly for me. The pageAction appears in every tab, and the first detected app is the icon of the pageAction. However, the popup from clicking on it is always Google Analytics and jQuery, which I assume is what was detected in one particular tab.

**Comment by DaAwesomeP** [comment]
It seems that `sendMessage` isn't working in Firefox nor Chrome.

**Comment by DaAwesomeP** [comment]
OK this is odd—after reloading the addon, it is working perfectly.

**Comment by DaAwesomeP** [comment]
I see a lot of `TypeError: chrome.extension.sendRequest is not a function`. This might be your issue: http://stackoverflow.com/a/15641460/2852590

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/sendMessage

**Comment by AliasIO** [comment]
I did change those calls but didn't commit the files correctly. That's pushed now.

**Comment by DaAwesomeP** [comment]
Thanks for pushing.

I found the issue and will submit a pull shortly. The polyfill doesn't work for both sides of the messages (sending and receiving). I'm really not sure why the polyfill goes to such lengths to rework `sendMessage()` and `onMessage`, because the syntax is exactly the same for `chrome` and `browser`!

**Comment by AliasIO** [comment]
Are you sure? Chrome accepts a response callback whereas WebExtensions uses a promise.

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/sendMessage
https://developer.chrome.com/extensions/runtime#method-sendMessage

**Comment by DaAwesomeP** [comment]
@AliasIO It works. That's all I can say. Since it works, I'm probably just ignoring the response or error from a function. Creating pull now.

The syntax for `onMessage` is 100% the same:
```js
browser.runtime.onMessage.addListener(funciton(message, sender, sendResponse){})
chrome.runtime.onMessage.addListener(funciton(message, sender, sendResponse){})
// sendResponse(object message) for both
```
In the case of `sendMessage()`, the code was using callbacks (not Promises), and this seems to work in Firefox (I guess they left this part compatible). So, the syntax is again the same:
```js
browser.runtime.sendMessage({ id: 'get_apps', tab: tabs[0] }, function (response){});
chrome.runtime.sendMessage({ id: 'get_apps', tab: tabs[0] }, function (response){});
```

**Comment by DaAwesomeP** [comment]
See #1431
