### ISSUE TITLE
Links don't work with the newest version

### ISSUE THREAD

**Issue by stefanos82** [AliasIO/Wappalyzer#1430]
With the latest updated Wappalyzer version on both Firefox and Chrome, detected apps are not working properly.

In other words, nothing works I'm afraid.

An example for **socket.io**: https://wappalyzer.com/applications/socketio?pk_campaign=firefox&pk_kwd=panel

@AliasIO is this behavior normal or is it something that has to do with the new framework wappalyzer is currently using?

**Comment by AliasIO** [comment]
The correct link for Socket.IO is this:

https://wappalyzer.com/applications/socket-io

I'll review the function that creates the URL slugs in the extension.

What do you mean by 'nothing works' though?

**Comment by AliasIO** [comment]
Fixed in 7d2952049f731eb262bc4b7b68bbca832fa25809.

**Comment by stefanos82** [comment]
I meant none of icon links really works when you click on it to find out more information about it.

I didn't mean wappalyzer is complete unusable, that sounded wrong indeed; my apologies.

Sometimes when I don't know how to write it in English, I do the naive mistake to translate from my language in English and changes the whole meaning completely lol.

**Comment by AlexByte** [comment]
@stefanos82 Nothing works often say those who do not understand computers. This is a meme.

**Comment by stefanos82** [comment]
As you can see above, I have clarified my position. It's not something I did on purpose, but rather from sheer naivety.

**Comment by AlexByte** [comment]
@stefanos82 да

**Comment by stefanos82** [comment]
пожалуйста
