### ISSUE TITLE
Angular 2 support?

### ISSUE THREAD

**Issue by memark** [AliasIO/Wappalyzer#1434]
Is there any support planned for Angular 2+? Right now those sites don't even get the Angular 1 icon.

**Comment by jvoisin** [comment]
How can you tell apart Angular from Angular2?

**Comment by memark** [comment]
Since Angular 1 sites show up, and Angular 2 sites don't, there is obviously a difference. :)

**Comment by jvoisin** [comment]
Like [this]( https://github.com/AliasIO/Wappalyzer/blob/master/src/apps.json#L508 )

**Comment by alpiepho** [comment]
(I'm a newbie so forgive me if I'm off base).  It looks like the detection is matching a pattern to a <script> tag in the HTML.  With the limited sites I have looked at, those Angular2  javascript modules are packed into a "*vendor.js".  Look at http://akveo.com/ng2-admin/#/pages/dashboard references from https://www.dunebook.com/5-best-open-source-project-examples-built-using-angular-2/.

**Comment by zealitude** [comment]
How about look for the ng-version attribute ?

```javascript
<body md-no-ink="">
  <app-root _nghost-c0="" ng-version="4.1.0"><div _ngcontent-c0="" class="app-content" ng-reflect-class-base="app-content">
  ```

```javascript
<body>
<app ng-version="4.0.1">
    <main bathemerun="" class="ng2">
```

**Comment by gadcam** [comment]
#1911 was merged so I think we can close this one.
