### ISSUE TITLE
React.js listed on almost all the websites I check

### ISSUE THREAD

**Issue by mattaningram** [AliasIO/Wappalyzer#1435]
Recently I've noticed that the Wappalyzer extension lists React.js on essentially every site I check with it. It even appears on my site which pretty much only uses a few lines of jQuery. Any idea what's going on here?

**Comment by craiglondon** [comment]
Can you provide some sample URLs of the false positives?

**Comment by craiglondon** [comment]
Check this issue, it might be what you are experiencing.  https://github.com/AliasIO/Wappalyzer/issues/1262

**Comment by mattaningram** [comment]
@craiglondon Ah that makes sense, but is rather annoying. Is there any way for Wappalyzer to not parse plugin code?

**Comment by craiglondon** [comment]
@mattaningram I don't have an answer to that question.  Maybe Alias does

**Comment by AliasIO** [comment]
Not if the extension injects React into web pages.
