### ISSUE TITLE
These dependencies were not found

### ISSUE THREAD

**Issue by kenpeter** [AliasIO/Wappalyzer#1437]
Full code: https://github.com/kenpeter/wapplyzer_vue

How to reproduct the error:
`git clone git@github.com:kenpeter/wapplyzer_vue.git`
`yarn install`
`yarn dev`

Error:
```
These dependencies were not found:

* child_process in ./~/@wappalyzer/wappalyzer/index.js, ./~/phantomjs-prebuilt/lib/phantomjs.js
* fs in ./~/phantomjs-prebuilt/lib/phantomjs.js

To install them, you can run: npm install --save child_process fs
```

I try yarn add child_process fs, no use.

**Comment by andrew-jung** [comment]
did you try updating yarn?

**Comment by AliasIO** [comment]
Use the `wappalyzer` package, not `@wappalyzer/wappalyzer`.

https://www.npmjs.com/package/wappalyzer
