### ISSUE TITLE
Add detection to InfernoJS

### ISSUE THREAD

**Issue by 4leem** [AliasIO/Wappalyzer#1439]
As a best ReactJS alternative, InfernoJS is catching up and many seems to adopt it. Could you please add support to detect InfernoJS ? 

https://github.com/infernojs/inferno

**Comment by jvoisin** [comment]
Sure, be my guest, it's not hard to implement a new detection :)

**Comment by craiglondon** [comment]
https://github.com/AliasIO/Wappalyzer/pull/1449
