### ISSUE TITLE
How to add new CMS

### ISSUE THREAD

**Issue by simonvdfr** [AliasIO/Wappalyzer#1440]
Hello

I start using git and I would like to add a CMS but it tells me:
Autorisation à AliasIO / Wappalyzer.git refusée à simonvdfr.

I would like to add the following content :
`"Translucide": {
			"cats": [
				1
			],			
			"implies": [
				"PHP",
				"jQuery"
			],
			"icon": "translucide.svg",
			"script": "lucide\\.init\\.js",
			"website": "http://www.translucide.net"
		},`

and icon : [translucide.svg](https://github.com/AliasIO/Wappalyzer/files/841026/translucide.zip)

**Comment by jvoisin** [comment]
You need to create a fork on github.
You should read the documentation about [how to use github]( https://help.github.com/ ).
