### ISSUE TITLE
Firefox (Linux), list shows up on second monitor

### ISSUE THREAD

**Issue by aditya3098** [AliasIO/Wappalyzer#1441]
I am running firefox (52) on linux, I have two monitors. When I have the firefox on the first monitor, the list pops up in the second. It doesnt do the same for the second monitor. Same for gnome-shell and awesome window manager.
![image](https://cloud.githubusercontent.com/assets/1984211/23900924/0e3c8490-08e1-11e7-9003-a1d7256ff662.png)
![image](https://cloud.githubusercontent.com/assets/1984211/23900947/1dd9ced0-08e1-11e7-933e-06efa252fd1d.png)
issue is the same when maximised

**Comment by gadcam** [comment]
It's not a Wappalyzer bug see #1276

**Comment by aditya3098** [comment]
Ah, sorry

**Comment by DaAwesomeP** [comment]
@aditya3098 would you like to test out the WebExtension version of the addon? It places only one icon in the URL bar, but it uses a new method to show the popup.

**Comment by aditya3098** [comment]
@DaAwesomeP sure, where can I get it?

**Comment by DaAwesomeP** [comment]
@aditya3098 would you like to build it yourself or should I send you a ZIP? It's simple to build. You just need a Vagrant/Docker install.

**Comment by aditya3098** [comment]
@DaAwesomeP I can build it.
