### ISSUE TITLE
Bookmarklet isn't working

### ISSUE THREAD

**Issue by AlexByte** [AliasIO/Wappalyzer#1452]
- https://wappalyzer.com/css/bookmarklet.css
- https://wappalyzer.com/bookmarklet/wappalyzer.js
- https://wappalyzer.com/bookmarklet/apps.js
- https://wappalyzer.com/bookmarklet/driver.js

are 301 redirected to
https://wappalyzer.com/download#bookmarklet

**Comment by derek-duncan** [comment]
Here's the safari error
```
[blocked] The page at __SITE__ was not allowed to run insecure content from http://wappalyzer.com/download#bookmarklet.
```

**Comment by AliasIO** [comment]
Thanks, that's fixed.
