### ISSUE TITLE
I cannot contribute

### ISSUE THREAD

**Issue by alvinbakker** [AliasIO/Wappalyzer#1456]
Somehow I cannot contribute. I keep getting a 403 error. Do I need to be on a paid plan at GitHub?

**Comment by craiglondon** [comment]
You don't need a paid account.   Did you fork the repo then do a pull request?

**Comment by alvinbakker** [comment]
Hi,

I pulled master, then created a new branch apps/spincms and commited it.
When doing a push I get the error 403

Kind regards / Met vriendelijke groet,
Alvin Bakker

SPIN Internet Media
Chonchorogaiweg 9, Willemstad, Curacao. T +5999 738 5611 http://www.spin.cw



Please consider the environment before printing this email

Confidentiality Warning: This e-mail contains information intended only for
the use of the individual or entity named above. If the reader of this
e-mail is not the intended recipient or the employee or agent responsible
for delivering it to the intended recipient, any dissemination, publication
or copying of this e-mail is strictly prohibited. The sender does not
accept any responsibility for any loss, disruption or damage to your data
or computer system that may occur while using data contained in, or
transmitted with, this e-mail. If you have received this e-mail in error,
please immediately notify us by return e-mail.Thank you.

**Comment by jvoisin** [comment]
You might want to read the [documentation]( https://help.github.com/ ) to figure out how github is working.

**Comment by craiglondon** [comment]
@alvinbakker Looking at your GitHub profile, i do not see that you have forked Wappalyzer.

**Comment by alvinbakker** [comment]
Got it. I am sorry for the silly questions, was the first time I wanted to contribute

**Comment by craiglondon** [comment]
No problem. Everyone has their first time
