### ISSUE TITLE
using another dom manipulating engine rather than phantomjs

### ISSUE THREAD

**Issue by hbakhtiyor** [AliasIO/Wappalyzer#1476]
what do you think about using jsdom or cheerio or zombiejs instead of phantomjs?

**Comment by AliasIO** [comment]
I'd have to understand the difference/benefit.

**Comment by hbakhtiyor** [comment]
@AliasIO some links worth to read 

https://github.com/tmpvar/jsdom#jsdom-vs-phantomjs

cheerio claims 8x faster than JSDOM, but with limited features
https://github.com/cheeriojs/cheerio#what-about-jsdom

zombiejs like phantomjs, but uses jsdom rather than real browser webkit engine.

if one of them will be suitable for your use case, it'll be fast than current phantomjs solution

**Comment by AliasIO** [comment]
It's interesting, especially now that the PhantomJS maintainer has stepped down. Would you be interested in creating a port?

**Comment by AlexByte** [comment]
Now Zombie.js is used.

**Comment by AliasIO** [comment]
Yep, thanks for the suggestion @hbakhtiyor.

**Comment by hbakhtiyor** [comment]
@AliasIO anytime :+1:
