### ISSUE TITLE
Inform users about tracking and use of cookies on your website

### ISSUE THREAD

**Issue by LeBaux** [AliasIO/Wappalyzer#1482]
I do not mind you using my browsing data to analyze websites I visit (and selling the datasets to third parties), but I am not OK with your plugin constantly opening the ["wappalyzer was updated"](https://wappalyzer.com/upgraded?pk_campaign=firefox&pk_kwd=upgrade) webpage with or without tracking codes in URL. It is annoying, but more importantly illegal. Doing this with each update, you track wappalyzer users and there is **no way to opt-out** from this kind of tracking. Please offer a way to opt-out and update your website to contain information on cookie use, as you are already required by EU cookie laws. Thanks!

**Comment by gadcam** [comment]
Could you please give information on how to reproduce your bug ?
Which browser are you using with which version of Wappalyzer ?
As a user of Wappalyzer 3.2.11 on Firefox 52.0.2 I don't have this sort of behavior.

**Comment by LeBaux** [comment]
Mate I am not sure how to put it more clearly, but I will try. Every time wappalyzer updates, it purposefully opens mentioned webpage. So unless there is something very wrong with my firefox on 3 computers and 2 different operating systems, it is not a bug, but intended behavior.

The is problematic for 3 major reasons:

1. It is annoying, not only this is the only extension that has the need to inform me every time it updates, but the updates are frequent, sometimes multiple times in a week. To make matter worse, this update notification is always opened on every firefox installation I am using. Very reason I opened the issue.
2. The website that is being opened uses cookies and tracks the users.
3. There is no way to opt-out of this behavior and there is no disclosure how you handle the collected data (I am not talking about the intended collection of data - detecting website technologies user visits).
4. The whole process looks like you are purposefully collecting data on your users without disclosing it.
5. On the top of that, all of this is illegal in Europe.

You can fix this issue multiple ways, but obviously I am implying you should just stop opening that dreaded webpage on every update.

**Comment by AlexByte** [comment]
@LeBaux What about option "Notify about updates" in extension settings?

**Comment by LeBaux** [comment]
Sure, show me where.

**Comment by LeBaux** [comment]
No such an option in firefox, or?

![image](https://cloud.githubusercontent.com/assets/5657511/24507800/c78cb9ce-1561-11e7-843f-f8dbd99152ea.png)

**Comment by AliasIO** [comment]
The option has been added in v4. The upgrade notification is not there for the purpose of tracking users.

**Comment by LeBaux** [comment]
It is pretty obvious I was using the tracking argument to stop with the bullshit notifications popups but since you are not getting it, I might as well exercise my rights and warn authorities about this [deliberate act of deception](deliberate act of deception), I mean at least I will get a second unbiased opinion on this right? I was always curious how seriously will EU intervene if someone was clearly breaking their somehow questionable rules and this seems like a good opportunity to do just that. Fun weekend project plus they are obliged to take it seriously. Europeans pay top dollar to have these kind of people, you know.

Or you know you can still remove that garbage popup, or if you really just want to be more passively aggressive then me just add a cookie notice to your webpage, disclosing how you use cookies. Your choice really.

**Comment by gadcam** [comment]
Stop being paranoid. 
This practice is also being used by Firebug, to quote a famous example, and for the same purpose : only giving information to users. Moreover I don't see how you could use it with this updating frequency..
