### ISSUE TITLE
Chrome plugin: Uncaught (in promise)

### ISSUE THREAD

**Issue by drakon** [AliasIO/Wappalyzer#1492]
There seems to be a problem coming from the Chrome plugin since the last update of it. 

When I go to any site with the Wappalyzer plugin active there are a lot of these error messages in the console output:

Uncaught (in promise): "The message port closed before a reponse was received."

![wappalzer-bug](https://cloud.githubusercontent.com/assets/220959/24582905/20b4af2c-173b-11e7-92d8-31b2d1a277bc.PNG)

Browser: Chrome 57.0.2987.133 under Windows 7. Same happens with the latest Chrome under MacOS

**Comment by AliasIO** [comment]
Fixed in #1491, I'll push an update today.

**Comment by drakon** [comment]
Alright, just realized that there are issues already open. Didn't search in the closed issues.

**Comment by AliasIO** [comment]
No worries, thanks for reporting the issue.
