### ISSUE TITLE
Polish translation for Wappalyzer

### ISSUE THREAD

**Issue by clamsioPL** [AliasIO/Wappalyzer#1493]
Hello.
I've done polish translation for Wappalyzer.
[https://github.com/clamsioPL/Wappalyzer/blob/master/src/drivers/webextension/_locales/pl/messages.json](https://github.com/clamsioPL/Wappalyzer/blob/master/src/drivers/webextension/_locales/pl/messages.json)

**Comment by AliasIO** [comment]
Thanks!
