### ISSUE TITLE
Node command line application collects the console output and concatenate it with the return JSON array

### ISSUE THREAD

**Issue by ppshobi** [AliasIO/Wappalyzer#1497]
I don't know if it's an intended behavior, if yes,please close it

**steps to reproduce,** 
1.goto `node_modules/@wappalyzer/wappalyzer`
2.issue `node index.js http://cloudways.com `

**Output**

`New-relic loaded...
GTM loaded...
Lazy init
Facebook tracker loaded...!
Hubspot Loaded...!
Push crew Loaded...!
Mouseflow Loaded...!
Live chat Loaded...!
`

and this output is concatenated to the JSON array and written to the stdout.
So direct json_decode() on the output was not working for my need, Even if this is an intended behavior, it would be nice if it is wrapped inside the object rather than just concatenating it with the return JSON, because it makes harder to read the output, in my case I wrote some regex to find the start of the JSON array, then strip off other parts to get back the exact array.

**Comment by AliasIO** [comment]
Please use the `wappalyzer` package, not `@wappalyzer/wappalyzer`.
