### ISSUE TITLE
Yoast SEO is not a marketing automation app

### ISSUE THREAD

**Issue by dttg** [AliasIO/Wappalyzer#1499]
Should we add an SEO Category apps? 
We could add: 
- SimilarWeb;
- Alexa;
- Comscore;
- Moz
- Semrush
- Ahrefs
etc.

**Comment by AliasIO** [comment]
Sounds good. Do you want to add it?

**Comment by GeorgeWL** [comment]
@AliasIO I woyldn't mind trying it...but I'm not really sure on the structure of the app. 

Where are the categories and apps lists stored? Can you link to the blob?

**Comment by AliasIO** [comment]
Thanks! Categories are defined here:

https://github.com/AliasIO/Wappalyzer/blob/master/src/apps.json#L10374

Each locale will need an entry for new the new category as well:

https://github.com/AliasIO/Wappalyzer/tree/master/src/drivers/webextension/_locales

**Comment by robwent** [comment]
I would second this. It makes the stats a bit of a joke as it's used on loads of wp sites and dilutes the real marketing automation solutions.

Will add a pull.
