### ISSUE TITLE
Tag releases on GitHub

### ISSUE THREAD

**Issue by DaAwesomeP** [AliasIO/Wappalyzer#1513]
For future releases, it would be nice if the version of the repo could be tagged:
```bash
git commit -m "update manifests to v4.0.1"
git push origin master
git tag v4.0.1
git push --tags origin master
```
This helps to keep track of exactly what happened in what version by bookmarking different points. After a tag, you can go into the releases tab of the repo on GitHub and upload a prebuilt ZIP of the extension for that release. This allows for easier testing of the addon and different versions in different browsers (ex. Opera or the Firefox WebExtension). You can even setup Travis CI to publish the prebuilt binaries whenever a tag is pushed.

**Comment by AliasIO** [comment]
Yeah, I should do that. How does publishing work with Travis CI?

**Comment by DaAwesomeP** [comment]
See #1514. Basically GitHub allows you to "publish" a tag and add release notes and built files to download. You will need to edit the Travis file as I specified in the pull. I added checksums for verification that the built files came from Travis.
