### ISSUE TITLE
add virtuoso detection

### ISSUE THREAD

**Issue by seralf** [AliasIO/Wappalyzer#1516]
Adding [virtuoso](https://virtuoso.openlinksw.com/) detection could be useful, since many linked open data projects used it. 
In many installation the default theme is used, than it's simple to detect its usage from header and footer, however other way to recognize it could be looking for paths like `/fct/{something}.vsp`

**Comment by jvoisin** [comment]
Do you have a list of websites where this framework/application/… is deployed?

**Comment by seralf** [comment]
there are many, why the list?

2017-04-20 16:12 GMT+02:00 jvoisin <notifications@github.com>:

**Comment by jvoisin** [comment]
So I can implement its detection and tests it.

**Comment by seralf** [comment]
Hi I've added a first draft for Virtuoso detection.

Those are examples of endpoints provided with Virtuoso:
+ http://dbpedia.org/sparql
+ http://live.dbpedia.org/sparql
+ http://bio2rdf.org/sparql
+ http://lod.openlinksw.com/sparql

Actually there could be other pages on the sites as well as the sites themselves hosted on Virtuoso (for example: http://lod.openlinksw.com/), but it's not simple to detect them. The endpoint is simpler to analyze since it usually has a standard URL, but on the other hand not all the SPARQL endpoint are hosted on Virtuoso.
