### ISSUE TITLE
Truncated dropdown list

### ISSUE THREAD

**Issue by cicciomanna** [AliasIO/Wappalyzer#1521]
often, when i visit a site with so many frameworks, the wappalizer list is truncated like in the attached image:

<img width="249" alt="schermata 2017-04-13 alle 10 17 44" src="https://cloud.githubusercontent.com/assets/13085523/24996256/7e5aedf8-2032-11e7-94de-791ec9537935.png">

**Comment by gadcam** [comment]
Duplicate of #1510.
