### ISSUE TITLE
e-commerce category problem in chrome

### ISSUE THREAD

**Issue by mehrshadz** [AliasIO/Wappalyzer#1524]
When you click on Wappalyzer extension in **chrome** it works great but there is a small problem with e-commerce category. For example open this [link](http://fo.demo.prestashop.com/en/) and you can see all technologies' categories are mentioned bellow them except the "PrestaShop" which is in ecommerce category.
Or, if you check this [link](https://ipresta.ir) you can see the "iPresta" technology which is in ecommerce category, the category is not mentioned too.

**P.S:** there is no problem with Mozilla FireFox add-on. It only appears on **Chrome extension**.

Please check it and fix this in the next update.

Thanks

**Comment by AlexByte** [comment]
The same for the category `Hosting Panels`.

**Comment by AliasIO** [comment]
Fixed in 574e7b1245efff91ba4eb0bcb87d44bdcfddf6de. Not sure what happened there.
