### ISSUE TITLE
Headers are not analyzed

### ISSUE THREAD

**Issue by AlexByte** [AliasIO/Wappalyzer#1529]
Its because Object patters isn't an array and doesn't have a length field [wappalyzer.js#L519](https://github.com/AliasIO/Wappalyzer/blob/f445a79/src/wappalyzer.js#L519)

**Comment by AliasIO** [comment]
Thanks!

**Comment by AlexByte** [comment]
Why the isssue is closed, but the code isn't fixed?

**Comment by AliasIO** [comment]
https://github.com/AliasIO/Wappalyzer/commit/f0073652cb4cc6dc96fd35c64078fa2e7325a985#diff-d7f544c6575fa5815df4b466a9e04f40R495

**Comment by AlexByte** [comment]
Sorry, I looked into another method.
