### ISSUE TITLE
phantomjs analyse the only HTML

### ISSUE THREAD

**Issue by pifagor87** [AliasIO/Wappalyzer#1534]
https://github.com/AliasIO/Wappalyzer/tree/master/src/drivers/phantomjs
Run from the command line
$ node index.js https://wappalyzer.com --quiet

**How to analyse the only HTML in command line?**

**Comment by AliasIO** [comment]
You can't. You can call `wappalyzer.analyze()` with just HTML but you'd have to make changes to index.js and driver.js.
