### ISSUE TITLE
Colorbox support?

### ISSUE THREAD

**Issue by AlexByte** [AliasIO/Wappalyzer#1540]
What about to support a customizable lightbox plugin for jQuery?
https://github.com/jackmoore/colorbox

**Comment by AliasIO** [comment]
I don't want to add detection for plugins to Wappalyzer, there are too many.

**Comment by AlexByte** [comment]
Why detection of fancybox was added?

**Comment by AliasIO** [comment]
That one must have slipped through!

**Comment by AlexByte** [comment]
fancybox should be removed?

**Comment by AliasIO** [comment]
Yes, I'd say so.

**Comment by AlexByte** [comment]
What about prettyPhoto, Slimbox, other plugins that use jQuery?

> At first sight jQuery FancyBox plug-in very much reminds LightBox. But he has several counters which do this gallery of worthy separate article.
> ### Advantages
> - Can display images, HTML elements, SWF rollers, and also iframe and results of Ajax of inquiries.
> - The user control by means of parameters and through CSS.
> - It is possible to group several elements and to add to them navigation.
> - If to connect a plug-in of jquery.mousewheel, then FancyBox will also react to wheel events of a mouse.
> - Support of the various animated transitions, using jquery.easing plug-in.

**Comment by AliasIO** [comment]
I'd like to remove those too.

**Comment by AlexByte** [comment]
@craiglondon What do you think?

**Comment by craiglondon** [comment]
Doesn't matter to me.  I thought the purpose of Wappalyzer was to detect things so I've written PR's to detect stuff that I have encountered or use.

**Comment by craiglondon** [comment]
I think plugin is the wrong term.  It's jQuery dependent.  We detect a Twittee Bootstrap JS.  It is also jQuery dependent.  Zurb probably is too but I haven't looked to confirm.
