### ISSUE TITLE
Only one icon displaying in Firefox.

### ISSUE THREAD

**Issue by powell759** [AliasIO/Wappalyzer#1541]
With the current version of the extension everything is fine.

![screenshot from 2017-04-28 13-28-31](https://cloud.githubusercontent.com/assets/10932655/25540323/a6ed5be2-2c18-11e7-8004-4bfd1e56d20a.png)

However, I built yesterday from a fresh pull and only one icon is displaying in the url bar (all the same technologies are appearing in the dropdown however). I'm guessing this has something to do with the switch to the webextension driver?

![screenshot from 2017-04-28 13-29-25](https://cloud.githubusercontent.com/assets/10932655/25540332/ae6f5384-2c18-11e7-86a5-efa8916e8501.png)

If this is the way it is supposed to be now I'll close this.

**Comment by AlexByte** [comment]
I guess its related with https://github.com/AliasIO/Wappalyzer/issues/1426

**Comment by powell759** [comment]
So if this display is no longer an option shouldn't it would be nice to have it display a set Wappalyzer icon instead of a arbitrary icon from the list of detected technology? I could try to this if that's something that would be wanted.

**Comment by AlexByte** [comment]
Its not random icon, its icon of one of technologies with most significant category. Like in Chrome.

**Comment by powell759** [comment]
Not too fond of this, but I guess it's not an issue. Not sure the priorities match up with mine.. I'll just tweak my own build. I'll go ahead and close.

**Comment by AliasIO** [comment]
There is a setting to always display the Wappalyzer icon.

**Comment by powell759** [comment]
Thank you. Would it be possible to give options to set display priority? For example, I'm mostly interested in seeing JavaScript frameworks right now, but Web Frameworks take higher priority. Would this be something worth including if worked on it?

**Comment by AliasIO** [comment]
Sure. Perhaps we can add a dropdown to the options page to nominate a single category that will be used for the icon.

**Comment by powell759** [comment]
Awesome. After all my finals I'll get a start on that.
