### ISSUE TITLE
Add WF Framework

### ISSUE THREAD

**Issue by wahyufebriyana** [AliasIO/Wappalyzer#1547]
"WF Framework": {
			"cats": [
				"18"
			],
			"headers": {
				"Set-Cookie": "wahyufebriyana_session"
			},
			"icon": "WF32.png",
			"implies": "PHP",
			"website": "http://wahyufebriyana.com"
		},
![wf32](https://cloud.githubusercontent.com/assets/20764595/25647134/781a9bac-2fe9-11e7-836f-3f80dad7ea84.png)

**Comment by ctl** [comment]
Please open pull request
I think it's better idea than opening issue

**Comment by jvoisin** [comment]
The website isn't the "right" one, and it seems that the framework is used by nobody,expect @wahyufebriyana himself.
