### ISSUE TITLE
Getting the phantomJS driver to work on Mac OSX

### ISSUE THREAD

**Issue by seanhamlin** [AliasIO/Wappalyzer#1553]
I am hoping I am missing something obvious here. The phantomJS version I have is the pre build binary from http://phantomjs.org/download.html.

```
~/projects/Wappalyzer/src/drivers/phantomjs on master*
$ phantomjs --version
2.1.1
```

When I try to run the sample from https://github.com/AliasIO/Wappalyzer/wiki/Drivers#phantomjs it just hangs, and has a weird error:

```
~/projects/Wappalyzer/src/drivers/phantomjs on master*
$ phantomjs driver.js -v https://www.google.co.nz
ReferenceError: Can't find variable: wappalyzer

  phantomjs://code/driver.js:222
^C
```

Any ideas on how to fix? Should the command be run from within the `src/drivers/phantomjs` folder?

**Comment by AliasIO** [comment]
Either spin up the Vagrant environment or run `./bin/wappalyzer-links .` from the repository root. It will hard-link wappalyzer.js and apps.json to the various drivers.

**Comment by seanhamlin** [comment]
```
~/projects/Wappalyzer on master
$ ./bin/wappalyzer-links .
Creating hard links...
OK
```

And now it works, thankyou.
