### ISSUE TITLE
Create new UI framework category

### ISSUE THREAD

**Issue by AlexByte** [AliasIO/Wappalyzer#1557]
- Create new separate category ~~`Front-end framework`~~ or `CSS framework` or `UI framework` for Bootstrap, Foundation, Materialize CSS, Milligram, (bq/)Penguin, Pure CSS, Semantic UI, UIKit, Visual WebGUI.
- ~~Add `Widget` category to Bootstrap, Foundation and Penguin, Semantic UI (everything that above?).~~
- Change category of Kendo UI, Angular Material and jQuery UI from `Web-framework` to `Widgets`.

**Comment by DaAwesomeP** [comment]
I don't understand the `Widget` category. I like the `UI framework` idea though.

**Comment by AliasIO** [comment]
Widgets was intended for embedded code like Google Maps and tweets. It's not as commonplace at it used to be.

I wouldn't mind differentiating between back and frontend frameworks. Perhaps web frameworks can be reserved for backend and we add a new category UI frameworks for frontend.

**Comment by kyletaylored** [comment]
I like this idea, I think the only thing is just getting semantics right, then we can start reorganizing. I'm thinking:

- Convert "Web Framework" to "Web Application Framework"
  - This would encompass apps like .NET, Laravel, Symfony, MeteorJS, etc.
- Add a new category "UI Framework"
  - This is loose enough to cover actual Frontend Frameworks, like Bootstrap and Zurb, but include smaller, more tailored UI tools like Tailwind, Skeleton, etc. Also there's no "Backend" category, so it wouldn't make sense to add / change that now.

**Comment by AliasIO** [comment]
Sounds good!
