### ISSUE TITLE
Add a note in the wiki that SVG icon should have viewBox attribute

### ISSUE THREAD

**Issue by AlexByte** [AliasIO/Wappalyzer#1564]
Also update info about "Adding a new translation".

**Comment by DaAwesomeP** [comment]
Why does it have to be square? The images scale properly.

**Comment by AlexByte** [comment]
Because it is not so.

**Comment by AlexByte** [comment]
[Some](https://github.com/DmitryKrekota/Wappalyzer/blob/256f1d8103812775b70e4c5e22c61981b91bad51/src/icons/PHP.svg) SVG icons don't scale properly because of manually selected not same width and height without setting viewBox.
![image](https://cloud.githubusercontent.com/assets/25251772/25830807/446ddd72-3468-11e7-893c-8fd88d08b42e.png)
_Actually, I thought that all the icons are incorrectly scaled._

**Comment by DaAwesomeP** [comment]
That would be very hard to enforce on already-added icons. Maybe it would be better to amend this stylesheet to only specify `width: 16px; height: auto` so that it scales: https://github.com/AliasIO/Wappalyzer/blob/master/src/drivers/webextension/css/popup.css#L20

**Comment by AlexByte** [comment]
Change icons probably because there are not many such icons.
![image](https://cloud.githubusercontent.com/assets/25251772/25832341/a80069a4-3472-11e7-9614-fdcfa54b9524.png)
![image](https://cloud.githubusercontent.com/assets/25251772/25832343/b0c5be86-3472-11e7-8536-5d063e9fc48f.png)

**Comment by DaAwesomeP** [comment]
I don't think that we see the same issue. I think that this is an issue with the SVG converter and not the SVGs themselves. The SVGs display fine in Firefox are technically correct.

**Comment by AlexByte** [comment]
> DaAwesomeP: Maybe it would be better to amend this stylesheet to only specify width: 16px; height: auto so that it scales: 

In this case, the horizontal icons will be higher than they should, and the horizontal ones will be too high.

![image](https://cloud.githubusercontent.com/assets/25251772/25833100/8c74d558-3477-11e7-9c5e-e9413e235685.png)

**Comment by AlexByte** [comment]
> DaAwesomeP: The SVGs display fine in Firefox are technically correct.

Only square icons without the viewBox attribute are displayed correctly. Try this [non-square](https://github.com/DmitryKrekota/Wappalyzer/blob/256f1d8103812775b70e4c5e22c61981b91bad51/src/icons/PHP.svg).

**Comment by DaAwesomeP** [comment]
OK, try `width: 16px; height: auto; max-height: 16px;`.

**Comment by DaAwesomeP** [comment]
OK, so the viewBox issue is separate from an icon simply being not square. The non-square don't scale properly and the viewBox issue causes them not to be converted properly.

**Comment by AlexByte** [comment]
@DaAwesomeP a tried and All horizontal icons are located higher than they should. Why you don't try? In any case, CSS doesn't solve the problem with the conversion.

**Comment by DaAwesomeP** [comment]
@AlexByte they are probably shifting up because of the [vertical align](https://github.com/AliasIO/Wappalyzer/blob/master/src/drivers/webextension/css/popup.css#L24). I suppose that the images could be placed in a 16x16 div that aligns the image to the center of itself but the div itself if aligned to the top. I'll try it out myself when I have more time.

**Comment by AlexByte** [comment]
@DaAwesomeP Yes, `vertical-align: middle;` aligns to the vertical center.

**Comment by AliasIO** [comment]
Added a note the SVGs should be square.

**Comment by AlexByte** [comment]
@AliasIO SVG can be not square.

**Comment by AlexByte** [comment]
@AliasIO Icons without `viewBox` are incorrectly converted to PNG, which led to https://github.com/AliasIO/Wappalyzer/issues/1622.
