### ISSUE TITLE
problem of detecting website as joomla

### ISSUE THREAD

**Issue by TechieForFun** [AliasIO/Wappalyzer#1567]
hi, when try to add this kinda parameter as below to url, plugin tells that it uses joomla.
like: ```google.com?option=com_users```. wappalyzer tells that google is joomla based.

**Comment by jvoisin** [comment]
And if you add `wiki.jsp` to it, it'll will detect it as Apache JSPWiki.
This is an expected behaviour for url-based detection, what were you expecting?

**Comment by TechieForFun** [comment]
actually i think it's better to using (not sure) text, for this kinda detection.

**Comment by gadcam** [comment]
@TechieForFun I don't understand what is your point of view : could you elaborate a bit more ?
Did you encounter a real case where you have an URL like this <code>google.com/?option=com_users</code> ?
If not if I'm right you are making the hypothesis that someone could craft the URL to make a false positive, which is true, but how could we prevent Wappalyzer from it ?

**Comment by TechieForFun** [comment]
hi @gadcam, sorry about the delay. please consider this scenario that a project use URL parameters like option=com_users, that idea of such parameterization is coming from Joomla, but in real, system is developed in Java, and web server info + programming language are not available in server response. so in this case i think Wappalyzer should say not sure it's Joomla but maybe. how do you think?

**Comment by gadcam** [comment]
Hi @TechieForFun,
Look at [apps.json](https://github.com/AliasIO/Wappalyzer/blob/master/src/apps.json) and tell me for which pattern you couldn't  say that ?
Wappalyzer relies on the postulate that the dev is not lying to you and that we can find patterns that are unique (or almost) for a given technology.
When we know that two technologies might be in conflict we try to write better patterns and we use the [exclude field](https://github.com/AliasIO/Wappalyzer/wiki/Specification#json-fields) in case of utmost necessity.
I'm afraid that with a **passive** analyzer there is nothing more to do than writing patterns with care.

**Comment by TechieForFun** [comment]
ok @gadcam, 
thanks for referring to exclude field
and thanks to all of you because of this awesome utility.
