### ISSUE TITLE
Question: Why is not working on Facebook?

### ISSUE THREAD

**Issue by Encr1pt3d** [AliasIO/Wappalyzer#1580]
Wappalyzer is not working on Facebook, why?

**Comment by gadcam** [comment]
Can't reproduce with Win 10, Firefox 53.0.3, Wappalyzer 3.2.11 : HTTP/2 is detected.
What are your OS, browser and Wappalyzer version ?

**Comment by jvoisin** [comment]
I can reproduce with `Wappalyzer 4.1.0`,  on `Chromium Version 58.0.3029.110 Built on Ubuntu , running on Ubuntu 17.04 (64-bit)`, on the login page.

**Comment by AlexByte** [comment]
Its working, but cannot detect any technology. I think that extension should show this info.
