### ISSUE TITLE
iPresta is not shown

### ISSUE THREAD

**Issue by mehrshadz** [AliasIO/Wappalyzer#1581]
As I checked today there are 2 problems with iPresta app ( https://wappalyzer.com/applications/ipresta ):

1. It doesn't show any data in this [link](https://wappalyzer.com/applications/ipresta) but there are a lot of sites using iPresta such as http://piltanshop.com . and also the iPresta logo is not shown on your website.

2. The iPresta icon is not shown on Wappalyzer popup. It was OK before the last update, but now for instance if you check the piltanshop.com website, you'll see that the <meta name="designer" content="iPresta"> tag `<meta name="designer" content="iPresta">` is there but it doesn't show iPresta icon on popup list.

Thanks

**Comment by AlexByte** [comment]
Its because of bug which already fixed. https://github.com/AliasIO/Wappalyzer/pull/1571#issuecomment-302903537

**Comment by mehrshadz** [comment]
Thanks for your response. Also the first problem I mentioned is fixed in #1571 ?

> It doesn't show any data in this link but there are a lot of sites using iPresta such as http://piltanshop.com . and also the iPresta logo is not shown on your website.

**Comment by AlexByte** [comment]
https://github.com/AliasIO/Wappalyzer/issues/1432#issuecomment-292682691

**Comment by AlexByte** [comment]
This issue should be closed.

**Comment by mehrshadz** [comment]
Thanks the second problem is solved but the first problem still exist. Please check the picture I have attached.
![wappalyzer websites using ipresta](https://cloud.githubusercontent.com/assets/7273999/26538449/0c805daa-445c-11e7-89aa-bece6cc549cd.jpg)


> It doesn't show any data in this link but there are a lot of sites using iPresta such as http://piltanshop.com . and also the iPresta logo is not shown on your website.

**Comment by AlexByte** [comment]
You should check this comment https://github.com/AliasIO/Wappalyzer/issues/1432#issuecomment-292682691

**Comment by mehrshadz** [comment]
Thanks for answer. Got it.
