### ISSUE TITLE
Webpack miscategorized

### ISSUE THREAD

**Issue by cohrs** [AliasIO/Wappalyzer#1586]
Why is webpack considered a CI Build System like Jenkins? Though it may be possible to use webpack as a ci build system that is not now it is being used by ~99.99% of the sites which it is recognized.

**Comment by AliasIO** [comment]
What category should it be in?

**Comment by jvoisin** [comment]
> webpack is a module bundler. Its main purpose is to bundle JavaScript files for usage in a browser, yet it is also capable of transforming, bundling, or packaging just about any resource or asset.

I would say `Miscellaneous`.
