### ISSUE TITLE
Typing Mistake in "Plesk Application"

### ISSUE THREAD

**Issue by pthoelken** [AliasIO/Wappalyzer#1587]
In the Attachment, you can see a typing mistake in the String. 

Normally it's calling "Hosting Panels" in the actally version is calling "Houtin Panels" (without the last char "g"). 

![image](https://cloud.githubusercontent.com/assets/12643853/26492338/c839d742-4213-11e7-841b-0024b3ac127b.png)

**Comment by AliasIO** [comment]
Fixed, thanks!
