### ISSUE TITLE
Application icon seems to work less well since last update

### ISSUE THREAD

**Issue by drakon** [AliasIO/Wappalyzer#1588]
Hi

I'm not 100% sure but it seems the application icons now seem to be less reliable than just a couple of days ago.

For example this site is clearly Wordpress: http://www.freethinkmedia.com/

But it still shows the Wappalyzer icon (Wordpress is even in the overflow list of used tech). Some other sites still get recognized correctly. Maybe it's just WP sites?

**Comment by AlexByte** [comment]
This is because now the name of the converted icon does not include the name of the original SVG extension
`Could not load action icon 'images/icons/converted/%name%.svg.png'.`

Also, the author does not test the extension for Chrome.

**Comment by hearvox** [comment]
Same issue, just adding this screenshot. For most WordPress sites, Wappalyzer is displaying the Twitter Emoji icon in the location bar (Mac Chrome) instead of the more-relevant CMS- WordPress icon:
![wappalyzer-icon](https://cloud.githubusercontent.com/assets/275759/26689402/c47ede4c-46b2-11e7-9d9b-08521c67541c.png)

**Comment by AlexByte** [comment]
@hearvox No, it's the default icon.

**Comment by hearvox** [comment]
Gotcha, thanks.

**Comment by AliasIO** [comment]
Fixed in f14e45c431ad4123a38a4710584669a6df3d4440.

**Comment by AlexByte** [comment]
@AliasIO Why not release the fix to the store?

**Comment by xstatic** [comment]
I concur on the icons working less well since last update. It seems that each time the Chrome extension is updated, it introduces some new nuances that make it much less usable.

**Comment by AlexByte** [comment]
@xstatic These bugs are successfully fixed.

**Comment by xstatic** [comment]
Not fixed in my Chrome extension. Will another update be coming down? Still
see the Wappalyzer icon for most sites...

**Comment by AlexByte** [comment]
It's fixed in the repository.

**Comment by xstatic** [comment]
Thanks @AlexByte but my original comments were related specifically to that fact that the Chrome extension is not updated. I'm just going to switch over to BuiltWith... Wappalyzer extension is just too buggy, all the time.

**Comment by hearvox** [comment]
Gotta disagree with @xstatic: Wappalyzer is a wonderful product, glad to have it.

**Comment by AlexByte** [comment]
> the Chrome extension is not updated
The last update was recently on 26 may/
