### ISSUE TITLE
Confusion between Spectre CSS and Bootstrap

### ISSUE THREAD

**Issue by carlos-duran** [AliasIO/Wappalyzer#1589]
![confusion](https://cloud.githubusercontent.com/assets/15650777/26589634/1c141df2-451e-11e7-9fee-395e21a309ce.png)

Spectre is very different than Bootstrap. Please, don't confuse :+1:

**Comment by gadcam** [comment]
This false positive is triggered by the <code>col-xs-12</code> class in the page with this pattern https://github.com/AliasIO/Wappalyzer#L8209
