### ISSUE TITLE
Wappalyzer got confused by domain name?

### ISSUE THREAD

**Issue by stefanos82** [AliasIO/Wappalyzer#1592]
This website https://bloggercms.github.io/ which is hosted on GitHub as a static website (see the actual code here: https://github.com/bloggercms/bloggercms.github.io) it's identified by Wappalyzer as Google's Blogger.

As I have said in ticket's title, can a domain name confuse Wappalyzer?

I have also noticed this behavior with **.pl** top level domain names that are falsely identified as Perl websites, even though **.pl** is the TLD for Poland.

Any thoughts on this matter @AliasIO ?

**Comment by AliasIO** [comment]
The generator meta tag confused Wappalyzer. Both issues have been fixed in 4f7b42906fe87f87d6bbae48e21b0cbb68585bfd.
