### ISSUE TITLE
Error in Kitematic

### ISSUE THREAD

**Issue by galaxy3000** [AliasIO/Wappalyzer#1595]
Hello, I use Kitematic to fecth the wappalyzer/cli，when I start it, it report the below infomation:

---
Error opening /usr/local/wappalyzer/--ssl-protocol: No such file or directory
Failed to fetch page
{"url":"--ssl-protocol","originalUrl":"--ssl-protocol","applications":[]}
---

please help me, thank you very much

**Comment by AliasIO** [comment]
Did you pass it a URL? It should be used like this:

```
docker run --rm wappalyzer/cli http://example.com
```
