### ISSUE TITLE
Question: Why Nikola is not included in Wappalyzer applications?

### ISSUE THREAD

**Issue by stefanos82** [AliasIO/Wappalyzer#1596]
The title says it all to be honest with you.

Here's their generator tag that confirms it: `<meta name="generator" content="Nikola (getnikola.com)">`

**Comment by AlexByte** [comment]
Why you haven't created pull request?

**Comment by stefanos82** [comment]
So, should I pull a request to ask a question? Next time I should have that in mind then.

**Comment by AlexByte** [comment]
Pull request are opened to add techologieses https://github.com/AliasIO/Wappalyzer/wiki/Specification

**Comment by stefanos82** [comment]
Anyway...
