### ISSUE TITLE
Extension was great, now too many bugs

### ISSUE THREAD

**Issue by idenis-s** [AliasIO/Wappalyzer#1599]
It was working great, now if I click on the icon it doesn't slide down properly, I need to click like 5 times again to make it work https://cl.ly/1t2M1n360h23/Screen%20Shot%202017-06-07%20at%2012.13.59%20PM.png

Also in the settings I clicked to show App icon not your logo but it still shows W logo on every website (was showing Ruby or other icons before) https://cl.ly/3z472s183s1Z/Screen%20Shot%202017-06-07%20at%2012.15.27%20PM.png

**Comment by AlexByte** [comment]
Known bugs https://github.com/AliasIO/Wappalyzer/issues/1588
