### ISSUE TITLE
How can i get the former Firefox Addon

### ISSUE THREAD

**Issue by juliustip** [AliasIO/Wappalyzer#1602]
The new version isn't letting me move the icon to a designated area on the task bar. Anyway to get the old version back?

**Comment by DaAwesomeP** [comment]
@juliustip The addon has become a WebExtension to ensure that it is compatible with future Firefox versions, which will only support WebExtensions. Unfortunately, WebExtensions only allow for one pageAction and/or toolbar button.

You can still install older versions from Mozilla, but they will not receive database/application list updates:
https://addons.mozilla.org/en-US/firefox/addon/wappalyzer/versions/

**Comment by juliustip** [comment]
@DaAwesomeP Thanks alot for the link.
As for the WebExtension, maybe i would migrate when new versions allow me to move the icon to my desired position. For now, i would stick with the old version.
Thanks again
