### ISSUE TITLE
XML rendering in Firefox messed up by Wappalyzer

### ISSUE THREAD

**Issue by hsleisink** [AliasIO/Wappalyzer#1603]
The latest version of Wappalyzer makes Firefox mess up the XML rendering. Take for example the XML file at http://www.leisink.net/test.xml With the Wappalyzer addon disabled, it looks like http://www.leisink.net/disabled.png. With the addon enabled, it looks like http://www.leisink.net/enabled.png

**Comment by DaAwesomeP** [comment]
@AliasIO are `application/xml` and `text/xml` excluded from checking?

**Comment by AliasIO** [comment]
Fixed in a43b4c83ffd0cd1d193a86d2e349c08cccaa1cf7.
