### ISSUE TITLE
Can you add WordPress.com to apps.json?

### ISSUE THREAD

**Issue by samwilcoxon** [AliasIO/Wappalyzer#1609]
WordPress.com is very different that Wordpress.org open source sites.

"WordPress.com": {
			"cats": [
				"1",
				"11"
			],
			"html": "<meta name=\"generator\" content=\"WordPress.com\">",
			"implies": "WordPress",
			"website": "http://wordpress.com"
		}

**Comment by jvoisin** [comment]
Please issue a pull-request then :)

**Comment by samwilcoxon** [comment]
Done! https://github.com/AliasIO/Wappalyzer/pull/1619
