### ISSUE TITLE
Dropdown menu is broken

### ISSUE THREAD

**Issue by joebui** [AliasIO/Wappalyzer#1611]
When clicking on the extension's icon, the dropdown menu is sometimes broken
<img width="254" alt="screen shot 2017-06-16 at 10 57 25 am" src="https://user-images.githubusercontent.com/9984201/27211328-c64280d6-5282-11e7-9472-56c24db8e74a.png">

**Comment by synnz** [comment]
Same problem, only with macOS

**Comment by AlexByte** [comment]
Dublicate https://github.com/AliasIO/Wappalyzer/issues/1510
macOS sucks
