### ISSUE TITLE
Why need to rebuild the html content when its length exceeds 50000?

### ISSUE THREAD

**Issue by chamnap** [AliasIO/wappalyzer#1614]
I'm so curious why we need to do this at https://github.com/AliasIO/Wappalyzer/blob/master/src/drivers/npm/driver.js#L183-L185?

I have a problem where the html content exceeds 50000, and this reconcat html breaks the app detection? When remove these lines, everything works.

When that rebuild happens, it makes the html to be cropped some parts. You can try this website, http://www.o2fitnessclubs.com/.

**Comment by AliasIO** [comment]
If it exceeds 50,000 characters, it grabs the top and bottom part of the page and discards what's in between. Usually that's where the most relevant code is. Scanning pages larger than that can cause delays and CPU overhead. What is it breaking?

**Comment by AlexByte** [comment]
@AliasIO Now i faced it, detection by class name did not work.

**Comment by AliasIO** [comment]
Using selectors is a great idea.
