### ISSUE TITLE
Wappalyzer keeps opening "updated" page

### ISSUE THREAD

**Issue by tsirolnik** [AliasIO/Wappalyzer#1615]
I don't know why, but the page keeps re-opening for no apparent reason.

**Comment by gadcam** [comment]
Can't reproduce on my setup.
What is your OS, browser (with version) and Wappalyzer version ?

**Comment by krasnovskyy** [comment]
Same problem.
Chrome - Version 59.0.3071.115 (Official Build) (64-bit)
OS - Windows 10 (x64)
Wappalyzer  - 4.1.5

**Comment by ctl** [comment]
Same problem , it's very weird bug

**Comment by tsirolnik** [comment]
Could it be related to [this part](https://github.com/AliasIO/Wappalyzer/blob/5febcb537eca86826ae572a96a9d4be5975599d5/src/drivers/webextension/js/driver.js#L93)?

**Comment by AliasIO** [comment]
Things have changed quite a bit, please let me know if this is still an issue.

**Comment by aaronrosenberg** [comment]
Just started happening for me - 

Firefox Developer Edition 65.0b2
Mac OS 10.14
