### ISSUE TITLE
How do I set the user agent when running using the docker version?

### ISSUE THREAD

**Issue by anoopjohn** [AliasIO/Wappalyzer#1616]
I am trying to run wappalyzer from the CLI using the docker image. Is there a parameter that allows you to set the UserAgent string when doing this?

Thanks in advance for your help

**Comment by sdoering** [comment]
Didn't find one myself and wasn't able to build a new image with a changed browser agent - so resorted to install it locally (without Docker) and use phantomjs to run the checks after editing driver.js.

**Comment by AliasIO** [comment]
There is no option for it currently but I'm in favour of adding this in.

**Comment by AliasIO** [comment]
Added in 3327fa18c80700ad48101784ea6acc66604f37bf. In the next version you can pass `--user-agent=<string>`.
