### ISSUE TITLE
Does Wappalyzer execute js while analyzing?

### ISSUE THREAD

**Issue by DenisBY** [AliasIO/Wappalyzer#1624]
In other words is it safe to analyze sites which could have some JS malware?

**Comment by jvoisin** [comment]
Yes.

Long answer: the extension will kicks on when the page is loaded. Since it's written in javascript, you can said that yes, javascript will be executed, but not in the dom context: a webpage won't be able to interact with Wappalyzer in other way than modifying the DOM, which will lead, at worst, to false-positives.

I would still recommend to use a virual-machine to analyse malwares, just in case ;)

**Comment by DenisBY** [comment]
Sorry not to mention it in original question, but I'm talking about cli version of Wappalyzer, not extension.

**Comment by AlexByte** [comment]
phantomjs opens pages in the sandbox.

**Comment by AliasIO** [comment]
The only code that's run in the context of the page is [`inject.js`](https://github.com/AliasIO/Wappalyzer/blob/master/src/drivers/webextension/js/inject.js), which communicates back to the extension via an event. There is no way for a page to execute code in the extension as far as I know.

**Comment by AliasIO** [comment]
Just read your second comment. The NPM driver has been rewritten to use Zombie.js instead of Phantom.js but both are safe from websites executing code.

**Comment by chamnap** [comment]
@AliasIO, zombie.js could not run javascript from that site, right? 

Let's say, I want to detect technologies on site `example.com`,  which has content generated by angular or react (after page loaded). I tested with `Wappalyzer` version 4 (Phantomjs) and 5(Zombie.js), both of them could not get that generated content by angular or react as I debugged. I'm not sure why. Any idea?

**Comment by AlexByte** [comment]
@chamnap zombie.js is a full browser and executes javascript.

**Comment by chamnap** [comment]
@AlexByte, some people have issue here, https://github.com/assaf/zombie/issues/1119. I have the same problem.
```
var Browser = require("zombie");
var browser = new Browser();

browser.visit("http://www.greenlocusyoga.com/yoga-classes/online-schedule/", function() {
  console.log(browser.html());
});
```

That console log doesn't have content of that big table. I tested with capybara poltergeist (ruby), it works just fine.

**Comment by AlexByte** [comment]
@chamnap > It's because of timeout error.
answered [here](https://github.com/assaf/zombie/issues/1119#issuecomment-327475856)

**Comment by chamnap** [comment]
@AlexByte, look like it's still the same. I tested several times. 

Thanks anyway.

**Comment by AlexByte** [comment]
@chamnap For your site the error is
> Bootstrap's JavaScript requires jQuery
```
> browser.visit("http://www.greenlocusyoga.com/yoga-classes/online-schedule", 
function (err, browser) {
...   if (err) { console.log('Error:' + err.message); }
...   else { console.log('Page loaded successfully'); }
... });
null
> Error:Bootstrap's JavaScript requires jQuery
```

**Comment by chamnap** [comment]
Yeah, thank you for pointing out. +1

Running with phantomjs, always get this error, "Operation canceled".

**Comment by AlexByte** [comment]
@chamnap https://github.com/assaf/zombie/issues/573

**Comment by AlexByte** [comment]
@chamnap give a piece of code.

**Comment by chamnap** [comment]
I was tested again Wappalyzer v4 and v5 (phanthomjs and zombie)... With v4, it has "Operation canceled" error. Look like it's phanthomjs issue.
