### ISSUE TITLE
empty pop up page

### ISSUE THREAD

**Issue by mreza-kiani** [AliasIO/Wappalyzer#1629]
since I have updated my extension, when I click ext. icon to see modules, the box is empty.

![screenshot from 2017-07-04 12-17-30](https://user-images.githubusercontent.com/20886423/27820193-d11ab65c-60b2-11e7-934f-98f47c402a87.png)

and now when I used chrome inspect pop up feature I saw these errors:

![screenshot from 2017-07-04 12-19-04](https://user-images.githubusercontent.com/20886423/27820235-00800b4a-60b3-11e7-96bf-21d90eb06e1d.png)

Please fix this issue as soon as you can because I really want to use this ext.
thanks

My Chrome version: 53.0.2785.143 (64-bit)
OS: Ubuntu 16.04

**Comment by AliasIO** [comment]
What version of Wappalyzer are you using?

**Comment by mreza-kiani** [comment]
4.1.3

**Comment by AliasIO** [comment]
Please try 4.1.5 which was published today.

**Comment by mreza-kiani** [comment]
Thank you, it is fixed in new version
