### ISSUE TITLE
How to know exactly CMS Version with Wappalyzer?

### ISSUE THREAD

**Issue by rinodung** [AliasIO/Wappalyzer#1645]
Wappalyzer is perfect tool help me to detect cms like wordpress, drupal, joomla... but i do not know Wappalyzer can detect specific version of CMS... Ex: Wordress 4.5, Drupal 7.1....?

**Comment by jvoisin** [comment]
Yes it can and does.

**Comment by rinodung** [comment]
In the same  URL [http://mtt.ui.edu.vn](http://mtt.ui.edu.vn ) the extenstion show version number but javascript code can not show it.
<img width="1252" alt="screen shot 2017-07-17 at 09 31 41" src="https://user-images.githubusercontent.com/7805715/28253965-c98c8850-6ad2-11e7-8248-806f2a0bda54.png">
This image show **Wordress 4.8** it's nice!! But i use javascript....

```
const wappalyzer = require('wappalyzer');

wappalyzer.run(['https://wappalyzer.com', '--quiet'], function(stdout, stderr) {
  if ( stdout ) {
    process.stdout.write(stdout);
  }

  if ( stderr ) {
    process.stderr.write(stderr);
  }
});
```

<img width="572" alt="screen shot 2017-07-17 at 09 29 27" src="https://user-images.githubusercontent.com/7805715/28253978-deaf5078-6ad2-11e7-8ac2-40489029d5f4.png">

Can you show me more option parameter in javascript to show exactly version number. Thank you so much!!!

**Comment by jvoisin** [comment]
It __can__ detect the version number and application, this doesn't mean that it detects every single one of them :)

Sometimes it's not possible to passively detect the version (or even the application).

**Comment by gadcam** [comment]
I think the question of rinodung was more about why is there a difference in detection between the browser addon and the NodeJS version.

**Comment by rinodung** [comment]
Yep! Why is there a difference in detection between the browser addon and the NodeJS version?
Is it difference code? Or anything else?

**Comment by AlexByte** [comment]
Confirmed
![image](https://user-images.githubusercontent.com/25251772/28299431-d9116a5c-6b81-11e7-9320-1013307ed1d9.png)

**Comment by AlexByte** [comment]
The root is is that meta tags are not being checked.
In extension this is [fixed](https://github.com/AliasIO/Wappalyzer/pull/1571#issuecomment-302903537).

**Comment by rinodung** [comment]
@AlexByte It means that i have to download release 4.1.5 and npm install wapplyzer again, right?

**Comment by AlexByte** [comment]
You should type `npm install` only.

**Comment by AlexByte** [comment]
Or you can just replace `manifest.json` file with the new version.

**Comment by rinodung** [comment]
Not working now!
Step-by-step: 
1. git clone https://github.com/AliasIO/Wappalyzer.git  (get newest version)
2. npm i wappalyzer
3. cd node_modules/wappalyzer
4. replace wappalyzer.js with new wappalyzer.js(new version from git clone)
5. node index.js https://wappalyzer.com
![untitled](https://user-images.githubusercontent.com/7805715/28303131-a55c5ce6-6bbb-11e7-9777-63bb149667fd.png)

**Comment by AlexByte** [comment]
Genius.

**Comment by AlexByte** [comment]
What did i have said? 
>You should type npm install only.

**Comment by AlexByte** [comment]
1. `git clone https://github.com/AliasIO/Wappalyzer.git (get newest version)`
1.5. copy wappalyzer.js and apps.json to src/driver/npm
2. `cd src/driver/npm`
3. `npm install`

**Comment by AlexByte** [comment]
Second way step by step
1. replace `wappalyzer.js` with new `wappalyzer.js` (new version from git clone)

**Comment by rinodung** [comment]
I follow your stop but get this error:
```
$ node index.js https://wappalyzer.com
{"url":"https:\\wappalyzer.com","originalUrl":"https:\\wappalyzer.com","applicat
ions":[]}
```
Take a look: https://www.youtube.com/watch?v=q19_tULj9DM&feature=youtu.be

**Comment by AlexByte** [comment]
I don't know. Check another URL. my Node.js version is v6.10.0.

**Comment by rinodung** [comment]
Ok thank AlexByte so much!!! I test with javascript code, i work like a charm!!!
```
const wappalyzer = require('wappalyzer');

wappalyzer.run(['https://wappalyzer.com', '--quiet'], function(stdout, stderr) {
  if ( stdout ) {
    process.stdout.write(stdout);
  }

  if ( stderr ) {
    process.stderr.write(stderr);
  }
});
```

![untitled](https://user-images.githubusercontent.com/7805715/28304730-22eb79ce-6bc3-11e7-95c4-24087f6ce0c3.png)
