### ISSUE TITLE
Not working with facebook

### ISSUE THREAD

**Issue by rbhatia46** [AliasIO/Wappalyzer#1648]
A great tool and very useful but it does not show any technology on facebook.com and it does not work there.

**Comment by gadcam** [comment]
Could give your OS, browser with version and Wappalyzer version ? It is working for me on Firefox 54.0.1 (Win 64) with Wappalyzer version 4.1.5.

**Comment by AlexByte** [comment]
Duplicate https://github.com/AliasIO/Wappalyzer/issues/1580

**Comment by rbhatia46** [comment]
Works now but showing only RxJS and no other technology. I am using Chrome browser.

**Comment by vaidas-lungis** [comment]
Duplicate of https://github.com/AliasIO/Wappalyzer/issues/1580

**Comment by AlexByte** [comment]
@vaidas-lungis I already wrote it.
