### ISSUE TITLE
Wappalyzer icon it's not showing in Mozilla Firefox 54

### ISSUE THREAD

**Issue by cyborggnu** [AliasIO/Wappalyzer#1649]
Wappalyzer icon it's not showing in Mozilla Firefox 54

**Comment by gadcam** [comment]
Could you provide more information ?
I'm using Firefox 54.0.1 (Win 64 bits) and Wappalyzer 4.1.5 and everything seems to be working.

**Comment by cyborggnu** [comment]
Mozilla Firefox 54.0.1 32 bits and Wappalyser 4.1.5 running on MS Windows 7 Prof 64 bits

**Comment by AlexByte** [comment]
Its showing.

**Comment by Necrontyrr** [comment]
I can't see it either. I tried to disable all plugins but that, and nothing.

**Comment by clamsioPL** [comment]
I have similar problem.
Using **Firefox 55.0.1 (64-bit)** on **Windows 10 Pro 64-bit** and **Wappalyzer 5.0.6** and icon not showing.

**Comment by AlexByte** [comment]
Icon is showing in **Firefox  54.0.1 (32-bit)** on **Windows 8.1 64-bit** and **Wappalyzer 5.0.6**.

**Comment by zhilevan** [comment]
The same problem, sometimes  wappalyzer not showing in firefox on windows.

**Comment by grahamperrin** [comment]
## Firefox 55.0–55.0.3, e10s

At `about:addons` if multiprocess is enabled, maybe try this: 

1. `about:config`
2. boolean `browser.tabs.remote.force-disable`
3. `true`
4.  restart Firefox

– then tell whether the issue is reproducible. 

If disabling multiprocess seems to work around the issue, then please note the value of `dom.ipc.processCount`. 

Thanks

**Comment by maicol07** [comment]
Hi, I tried the instructions and these are my results:
With Multiprocess disabled, the icon shows and it works. With this enabled, the icon doesn't show many times.
Value of dom.ipc.processCount: 6
Thanks

**Comment by mrandreastoth** [comment]
No extension icon under Firefox Developer Edition 60.0b2 (64-bit). The "browser.tabs.remote.force-disable" setting doesn't exist so cannot test that suggestion.

**Comment by blisstees** [comment]
You can try the following steps to get your problem solved:
1. Go to HELP menu on Menu Bar of Firefox & click on "Restart with Add-ons disabled"
2. Your browser will restart & will be in Safe mode. You won't be able to see the menu bar, so Right click on the top section of your browser and select Menu bar option. you will not be able to see the menu bar
3. Click on HELP menu & click on "Restart with Add-ons enabled"

You will now be able to see the Wappalyzer icon on your address bar. I have just tried the above steps & have successfully started the Wappalyzer.

**Comment by checor** [comment]
This also worked for me. Thanks!

**Comment by aashutoshrathi** [comment]
Thanks, @blisstees
Works for me

Arch Linux
Firefox 64.0b4 (64-bit)

**Comment by tauh33dkhan** [comment]
> You can try the following steps to get your problem solved:
> 
>     1. Go to HELP menu on Menu Bar of Firefox & click on "Restart with Add-ons disabled"
> 
>     2. Your browser will restart & will be in Safe mode. You won't be able to see the menu bar, so Right click on the top section of your browser and select Menu bar option. you will now be able to see the menu bar
> 
>     3. Click on HELP menu & click on "Restart with Add-ons enabled"
> 
> 
> You will now be able to see the Wappalyzer icon on your address bar. I have just tried the above steps & have successfully started the Wappalyzer.

This works me also on firefox ESR 52.8.1 (32-bit)
