### ISSUE TITLE
More information about version detection

### ISSUE THREAD

**Issue by rinodung** [AliasIO/Wappalyzer#1653]
I look in code https://github.com/AliasIO/Wappalyzer/blob/master/src/apps.json, the version number only detect by **"headers":** or **"Meta"** attribute. It can be hidden by web administrator, can anybody show me more methods to detect exactly version number of the website(URL)? 
**Example:** 
```
"Apache Tomcat": {
			"cats": [
				"22"
			],
			"headers": {
				"Server": "Apache-Coyote(/1\\.1)?\\;version:\\1?4.1+:",
				"X-Powered-By": "\bTomcat\b(?:-([\\d.]+))?\\;version:\\1"
			},
			"icon": "Apache Tomcat.svg",
			"implies": "Java",
			"website": "http://tomcat.apache.org"
		},
```

**Comment by gadcam** [comment]
If it is possible to detect a version with a pattern we do this. You can check we use other field like here https://github.com/AliasIO/Wappalyzer/blob/master/src/apps.json#L519
If your question is how to detect a version number without using patterns this sort of question is out of the scope of Wappalyzer : it's a **passive** analyzer.

**Comment by rinodung** [comment]
@gadcam I wonder if we should have any solution to detect version number without using pattern(header, meta, script...). 
For example,Drupal 6 has a different directory structure than Drupal 7.8....Something like that... thanks for your reply!
