### ISSUE TITLE
Bug: Top list for MyBB has false positives

### ISSUE THREAD

**Issue by Azareal** [AliasIO/Wappalyzer#1658]
https://wappalyzer.com/applications/mybb

Are you sure these educational sites (Blackboard, edu domains, etc.) *actually run* MyBB?

**Comment by jvoisin** [comment]
I don't know, since those applications are behind a login page. How do you know that they aren't?

**Comment by Azareal** [comment]
It seems to be mostly educational sites which use Blackboard or similar systems, I have never seen MyBB used in any such situation before, but of course I might be mistaken.

Also, it would mean that you're collecting information which you shouldn't have access to, and could possibly facilitate a security breach in these systems.

**Comment by jvoisin** [comment]
It is a security issue, but there is not much that we can do about: it's written in the documentation that wappalyzer will (by default) report the technologies that are used on websites that you're browsing. Maybe a bigger warning would be nice? I don't know.

We don't crawl *indexed sites*, people are browsing the web, handing the data back.

**Comment by AlexByte** [comment]
Unused technologies must be removed from the site.

**Comment by jvoisin** [comment]
I think that we can close this issue.

**Comment by AlexByte** [comment]
@jvoisin why?

**Comment by AliasIO** [comment]
I'll leave this open for now, some of the results are obviously Blackboard and not MyBB. It's a little difficult to debug without access to a Blackboard website though.

**Comment by jvoisin** [comment]
I'm for closing it, because there is nothing that we can do about it :/

**Comment by kyletaylored** [comment]
It looks like these were largely fixed from what I can tell.
