### ISSUE TITLE
Wappalyzer icon doesn't change to identified technology

### ISSUE THREAD

**Issue by Zaseth** [AliasIO/Wappalyzer#1662]
Recently I have this issue where Wappalyzer just keeps this purple icon instead of the identified technology icon of the website. I'm using Chrome 60.0.3112.78 with Windows 10. Also, when a website uses Angular, the icon of Wappalyzer just turns blank. Edit: If this is part of some new update that the icon stays purple, it's a bad choice. It is really useful to see the technology of the website's icon at first looks. Edit: it seems like a lot of users are having the same issue here. This is also happening in fire so there seems to be a problem with the app itself. Edit: Just found this in the options: 
![img](https://user-images.githubusercontent.com/24899039/28887772-aaf7cf00-77be-11e7-9316-77e69b6f1d94.png)

It still gets the Wappalyzer icon. There seems to be a huge issue with this option. Edit: To get this issue, you just install Wappalyzer on Chrome/Firefox. Even when I reinstalled Wappalyzer, it still happened. Turning the above option on and off also does nothing.

**Comment by geff21st** [comment]
Same problem. I always see Wappalyzer's purple icon. Chrome 59.0.3071.115, macOS Sierra 10.12.6

**Comment by benolot** [comment]
Same problem for every website I visit. Chrome 59.0.3071.115 64 bit on both Windows 10 Creators update and MacOS Sierra latest

**Comment by nyaapass** [comment]
Same problem. 

- Chrome 60.0.3112.78.
- macOS 10.12.6

**Comment by xczizz** [comment]
Same problem.

- Chrome  59.0.3071.115 64 bit
- Windows 7

**Comment by ethanguy** [comment]
Same! Running Chrome 59.0.3071.115 on macOS 10.12.4

**Comment by Sojaner** [comment]
Same problem.

- Chrome 60.0.3112.78 64-bit
- Windows Server 2012 R2 Datacenter

**Comment by AlexByte** [comment]
It's happened again

**Comment by HoiJean** [comment]
It's not just only Chrome but Firefox too

**Comment by davedenis** [comment]
I imagine they get the point by now but here's another +1 on this.

**Comment by xstatic** [comment]
This happens every single time the Chrome extension is updated... EVERY TIME!

**Comment by AliasIO** [comment]
Fixed in c4328afa302c657e796e2889d8cdd06a29e35903.

**Comment by Zaseth** [comment]
Yep it's working great now! Thank you.
