### ISSUE TITLE
npm package - returning browser console output

### ISSUE THREAD

**Issue by prees1** [AliasIO/Wappalyzer#1670]
See [here](https://gist.github.com/prees1/7e8222c7fdfad8ee544c98a44cb35372) for the code and output.

I am wondering why the output of the console is being returned here? Also what is the best way to avoid returning that?

Will wappalyzer always return its results last? So I can safely take the last line of output? And always safely parse that as JSON?

**Comment by AliasIO** [comment]
Which version are you running? Version 5 was released recently.

**Comment by prees1** [comment]
I am using the npm package v 3.0.9 from [here](https://www.npmjs.com/package/@wappalyzer/wappalyzer). I see the latest v5.0.5 release here on github. What is the process to build the npm package?

**Comment by AliasIO** [comment]
Please use this package: https://www.npmjs.com/package/wappalyzer

**Comment by prees1** [comment]
perfect, thanks! It is confusing that there seems to be two packages for this project.
