### ISSUE TITLE
return codes 

### ISSUE THREAD

**Issue by macarthy** [AliasIO/Wappalyzer#1681]
Is there a list of return codes/ exit codes that running from the command line will return .

E.g. I got a return code of 1 , is that a timeout or ? 

Thanks

**Comment by AlexByte** [comment]
https://github.com/AliasIO/Wappalyzer/blob/f0654e5bc0f90374362ff4f094ba73190dccd631/src/drivers/npm/index.js#L9-L13

**Comment by AliasIO** [comment]
It's 0 zero for success and 1 for any failure.
