### ISSUE TITLE
Old logo of Webpack is still shown (extension icon)

### ISSUE THREAD

**Issue by ctl** [AliasIO/Wappalyzer#1685]
![image](https://user-images.githubusercontent.com/27558814/29249605-acd9cd66-803b-11e7-89e1-ef854aa8dd24.png)

**Comment by jvoisin** [comment]
This was changed [the 31 July]( https://github.com/AliasIO/Wappalyzer/commit/bf1f4cf1e5a23565be10f05662f410cdb21787bf ), you should wait for the next release, since the last one was created the [31th](https://github.com/AliasIO/Wappalyzer/releases).

**Comment by ctl** [comment]
@jvoisin , so why there is  new and old logo?

**Comment by jvoisin** [comment]
Ho, in the icon and in the popup? Excellent question :D

**Comment by ctl** [comment]
Yes

**Comment by AlexByte** [comment]
@jvoisin It's not true, the extension has already been updated on August 4

**Comment by AlexByte** [comment]
@AliasIO You must uncomment this line https://github.com/AliasIO/Wappalyzer/blob/f0654e5bc0f90374362ff4f094ba73190dccd631/bin/build#L15

**Comment by AliasIO** [comment]
The SVG to PNG converter doesn't work in the Docker container for some reason, I've been running it manually on my machine instead. I have to remember to do it though.
