### ISSUE TITLE
Mistake with analytic! 

### ISSUE THREAD

**Issue by jamalabo1** [AliasIO/Wappalyzer#1687]
Guys! I have Installed WordPress in another folder in the subdomain! https://license.crackcloud.io and the Wapplayzer tell that site running is WordPress but it not! I have developed the page and the WordPress installed in another page hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh

**Comment by jvoisin** [comment]
![]( http://i.imgur.com/UwMak2a.png )

I can't reproduce your issue.

**Comment by jamalabo1** [comment]
![2017-08-16](https://user-images.githubusercontent.com/25992049/29372531-17b961e4-82b4-11e7-8d65-4079f6f109c3.png)

**Comment by jamalabo1** [comment]
![2017-08-16 1](https://user-images.githubusercontent.com/25992049/29372545-23457cd2-82b4-11e7-84b7-a588564b20cc.png)

**Comment by gadcam** [comment]
Can't reproduce too.

**Comment by jvoisin** [comment]
I'm currently using `Wappalyzer 5.0.6`, are you up to date?

**Comment by jamalabo1** [comment]
Me too 5.0.6
