### ISSUE TITLE
No sanitization strategy has been configured.

### ISSUE THREAD

**Issue by bravik** [AliasIO/Wappalyzer#1689]
Crawling http://amur-tiger.ru...
200 http://amur-tiger.ru/

pascalprecht.translate.$translateSanitization: No sanitization strategy has been configured. This can have serious security implications. See http://angular-translate.github.io/docs/#/guide/19_security for details.

Stopped

**Comment by AliasIO** [comment]
That looks like an error on the website that's being crawled, not Wappalyzer.
