### ISSUE TITLE
Detect Wt and jWt

### ISSUE THREAD

**Issue by bertvandepoel** [AliasIO/Wappalyzer#1691]
Wt and jWt are toolkit for writing websites based on a widget-like system as used on desktop (Qt etc.) in either C++ or Java: webtoolkit.eu

They can be easily detected because links will contain wtd=, besides that window.Wt and WtX_Y_Z will be set in javascript.

**Comment by jvoisin** [comment]
Unfortunately, `wtf=` is too small and thus will lead to false-positives, thanks to javascript "compressors". As for the `window.Wt` property, unfortunately, Wappalyzer doesn't allow inspection of properties, only of globals.

**Comment by jvoisin** [comment]
Unfortunately, `wtf=` is too small and thus will lead to false-positives, thanks to javascript "compressors". As for the `window.Wt` property, unfortunately, Wappalyzer doesn't allow inspection of properties, only of globals.

**Comment by bertvandepoel** [comment]
How about the global Wt in javascript (which contains an object)? Or would that be too short?

If wtd in links in the HTML is too short, maybe Wt-history-field (the name of a hidden input). It's always on a Wt page except if they use embedded widgets instead of doing the full page in Wt (which isn't very common). 

You can of course test it out on their website webtoolkit.eu (as I've been doing).

**Comment by jvoisin** [comment]
This would be too short to, compressors are typically using 2 or 3 letters for variables :/

`Wt-history-field` might fit :)

**Comment by bertvandepoel** [comment]
Cool, I talked to a friend of mine who knows a lot about Wt, The Wt global contains an object that always contains a _p_ object and an emit function. Don't know whether that helps. There is also a Wt version obect of the form ^Wt[0-9]+_[0-9]+_[0-9]+$

Those might be nice extras on top of Wt-history-field perhaps ^^

**Comment by jvoisin** [comment]
There is no way to access properties from Wappalyzer.

The Wt version object and the `Wt-history-field` one might be interesting though.

**Comment by AlexByte** [comment]
@jvoisin Why not to add support of checking properties?

**Comment by jvoisin** [comment]
This is a design decision, feel free to ask @AliasIO about this :)

**Comment by AlexByte** [comment]
@jvoisin I'v asked here https://github.com/AliasIO/Wappalyzer/issues/863#issuecomment-327461945

**Comment by bertvandepoel** [comment]
Does the close mean this has been implemented? I'm not too sure why this weird debate about checking properties started happening in this issue, I'd just like Wt to get detected properly.

**Comment by AliasIO** [comment]
It looks like there isn't a good way to identify the application. If you have a solution, please submit a pull request if you can.
