### ISSUE TITLE
Chrome: can't load extension from src

### ISSUE THREAD

**Issue by wamatt** [AliasIO/Wappalyzer#1693]
![image](https://user-images.githubusercontent.com/1271434/29722695-b3e5044a-89b9-11e7-8a86-1cc5fbf5c962.png)

![image](https://user-images.githubusercontent.com/1271434/29722648-8bc5ec0e-89b9-11e7-917c-5e3919a993a1.png)

I get the following error when trying to load:

`Failed to load extension from: ~/repos/Wappalyzer/src/drivers/webextension
Could not load javascript 'node_modules/webextension-polyfill/dist/browser-polyfill.js' for content script.`

Latest stable Chrome and macOS:

Chrome: Version 59.0.3071.86 (Official Build) (64-bit)
macOS: 10.12.6

Any ideas?

**Comment by AliasIO** [comment]
Fixed in 735e00383fe2ec1ae92a4aded1cafaf40455182a. Alternatively you can run `yarn install` or `npm i` in `src/drivers/webextension`.

**Comment by wamatt** [comment]
Thanks, that worked perfectly
