### ISSUE TITLE
Expand the popup at full height

### ISSUE THREAD

**Issue by AlexByte** [AliasIO/Wappalyzer#1697]
Need of scrolling disturbs.
_I like the new interface with the grouping, I wanted to suggest it._

**Comment by AliasIO** [comment]
The fixed height is to fix #1510.

**Comment by AlexByte** [comment]
It would be reasonable to apply this only to MacOS or add a setting.

**Comment by AlexByte** [comment]
@AliasIO What fixes: height of `body` or `,container`?

**Comment by AliasIO** [comment]
Either, as long as the popup window stays the same size.
