### ISSUE TITLE
Wordpress icon is not displayed in the Chrome Toolbar

### ISSUE THREAD

**Issue by AlexByte** [AliasIO/Wappalyzer#1698]
This is because SVG icons are converted into not square PNG.
It also leads to stretching of the icons, which have greater width than height.
![image](https://user-images.githubusercontent.com/25251772/29747734-749e6962-8b0c-11e7-9a76-1c0dd0743c99.png) ↖ [typecho](https://github.com/AliasIO/Wappalyzer/blob/fdb5176af725d8700b07c6bc5b41e7793b86be0e/src/icons/typecho.svg) icon

**Comment by tstricklin-atmosol** [comment]
FWIW, I'm seeing the same issue with the Shopify icon--though I don't know if it's SVG.

**Comment by AlexByte** [comment]
@tstricklin-atmosol It is SVG https://github.com/AliasIO/Wappalyzer/blob/master/src/icons/Shopify.svg

**Comment by AliasIO** [comment]
Should be fixed in today's update.
