### ISSUE TITLE
the panel show scrollbar when the content not overflow

### ISSUE THREAD

**Issue by xiaohp** [AliasIO/Wappalyzer#1707]
the screen capture
![mark](http://oih6hf7qs.bkt.clouddn.com/blog/20170828-184623575.png)

**Comment by pagoru** [comment]
Same...

**Comment by AlexByte** [comment]
It's fixid in the https://github.com/AliasIO/Wappalyzer/commit/cd4b8b1224a302d8cffa07fc52beb1ae15297cd2
