### ISSUE TITLE
Bookmarklet is broken

### ISSUE THREAD

**Issue by AlexByte** [AliasIO/Wappalyzer#1711]
> Uncaught ReferenceError: wappalyzer is not defined
>     at bookmarklet/apps.js:10820
>     at bookmarklet/apps.js:10820

**Comment by jsto** [comment]
There is quite a bit of stuff going wrong here:
- new Wappalyzer doesn't get initialised in the global scope (creating that error)
- the driver log function is not accepting the correct arguments
- the driver displayApps function is not taking any arguments
- the driver analyze function is called twice and the second result overwrites the first and doesn't append to it

**Comment by brandontamm** [comment]
+1 Broken for me too

**Comment by tim-west** [comment]
Unfortunately the bookmarklet is broken for me too. Is there a time line on when this might be fixed?

**Comment by tim-west** [comment]
Unfortunately the bookmarklet is broken for me too. Is there a timeline on when this might be fixed?

**Comment by brykov** [comment]
+1 broken

**Comment by AliasIO** [comment]
Fixed in 0c909ae0248a49916c0719253f0dc46695b5e529. Please reinstall the bookmarklet from the [download page](https://wappalyzer.com/download).

**Comment by AlexByte** [comment]
@AliasIO Suggesting to move the bookmarklet initialization script into a separate script on the site and in the bookmarker, only call it. This is necessary so that you do not have to reinstall the bookmarklet when upgrading.
