### ISSUE TITLE
Resources loaded from JS not inspected

### ISSUE THREAD

**Issue by mrvik** [AliasIO/Wappalyzer#1712]
### XHR and `fetch` API resources aren't inspected
If a resource is loaded on this way,  wappalyzer doesn't recognize it

**Comment by AlexByte** [comment]
What resources?

**Comment by mrvik** [comment]
Resources loaded with those apis. For example, when I load Materialize after the inspector.js script of wappalyzer, the framework is not added into wappayzer

**Comment by AlexByte** [comment]
I don't know what is `inspector.js`.

**Comment by mrvik** [comment]
Sorry, just mean `inject.js`. The script that makes wappalyzer detects

**Comment by mrvik** [comment]
To reproduce the issue 
- [ ] Load a web
- [ ] Open devTools and load a framework that is not included in the page. 
- [ ] `fetch(cdnurl).then(a=>a.text()).then(eval) `
After that, wappalyzer remains unchanged.

**Comment by AlexByte** [comment]
How do you think Wappalyzer should detect the execution of scripts?

**Comment by mrvik** [comment]
Maybe a interval to reexecute wappalyzer detection

**Comment by AlexByte** [comment]
Wappalyzer detects Materialize script tag in `body` outerHTML. https://github.com/AliasIO/Wappalyzer/blob/e96fb5ba30aecca00b4aa2db8429f2d0eb8b26de/src/apps.json#L4895

**Comment by mrvik** [comment]
I said Materialize to give an example, but it affects to any other script.
Then AFAIK, a `MutationObserver` on the `head` tag would be enought.

**Comment by AlexByte** [comment]
using `fetch(cdnurl).then(a=>a.text()).then(eval)` `head` isn't changing.

**Comment by mrvik** [comment]
Know it, but for CSS changes, it would be OK.
For scripts, the `self` object shold be watched, but there isn't a method to do it, so the only way is a timeout and look for mutations

**Comment by AlexByte** [comment]
Why use eval if you can add a script tag and not even use AJAX?

**Comment by AlexByte** [comment]
Dynamically adding resources, this does not mean that XHR, you can add script tags and link.

**Comment by mrvik** [comment]
> Why do you need to dynamically add scripts and CSS?

Beacuse the script needs of the initial splash are different of the user's navigation requests, so the resources are loaded dinamically with the user interaction

> Why use eval if you can dynamically add a script tag and not even use AJAX?

That's a good idea :thinking: 
I didn't care about many webs change it's DOM very frecuently and rescan on DOM change breaks apps performance

Just a question. Could be possible to add a reload button to wappalyzer in order to rerun detects?

**Comment by AliasIO** [comment]
Wappalyzer uses a delay to give scripts a chance to render page changes. AJAX requests are not inspected to avoid performance issues.
