### ISSUE TITLE
Travis check is broken

### ISSUE THREAD

**Issue by AlexByte** [AliasIO/Wappalyzer#1722]
> ERROR: An error occured while trying to parse your .travis.yml file.
>
> Please make sure that the file is valid YAML.
>
> http://lint.travis-ci.org can check your .travis.yml.
>
> The log message was: Build config file had a parse error: found unknown escape character while parsing a quoted scalar at line 11 column 95.
>
> Done: Job Cancelled

**Comment by jvoisin** [comment]
This is a serious issue, since we lose the ability to give automatic feedback to contributors :/

**Comment by AliasIO** [comment]
Fixed.

**Comment by jvoisin** [comment]
♥
