### ISSUE TITLE
Lag issues

### ISSUE THREAD

**Issue by salarcode** [AliasIO/Wappalyzer#1723]
Wappalyzer 5.1.2 cause Firefox 55 to lag when working with tabs.
This includes opening links/closing tabs and switching between tabs sometimes.
After disabling Wappalyzer everything returned to normal state.

Any more info you need from me to resolve the issue?

**Comment by AlexByte** [comment]
How long have you been using Wappalyzer?

**Comment by salarcode** [comment]
Since its early days i guess :-)

**Comment by AlexByte** [comment]
From what version of firefox lags began?

**Comment by salarcode** [comment]
Since 2 or 3 days ago which I think was when version 5.1.2 Wappalyzer released.

**Comment by alvarogzp** [comment]
I can add that after updating to Firefox 57, it adds a noticeable lag to every page load.
It is specially noticeable on https://duckduckgo.com/, which spends a few seconds using 100% of CPU before ending loading the page (blocking the browser). If I disable the add-on, the page load immediately.

**Comment by gadcam** [comment]
@alvarogzp I can reproduce it. What is your OS and arch ?

**Comment by alvarogzp** [comment]
It is Linux (Ubuntu) 64 bits. Wappalyzer 5.1.6.

To be fair, I also had lagging issues in Firefox 56, but I don't know if they were because of the add-on, as I attributed them to having Firefox opened for a few weeks and didn't tried disabling the add-on.

**Comment by AliasIO** [comment]
Wappalyzer now uses asynchronous execution. Let me know if this is still an issue.
