### ISSUE TITLE
Force refresh/update detected technologies

### ISSUE THREAD

**Issue by jemhuntr** [AliasIO/Wappalyzer#1724]
It would be great if there was an option to force refresh the detected stack. Currently, I believe Wappalyzer is storing URLs with associated technologies somewhere, which is then fetched when the user visits the URL.

This becomes an issue especially for localhost applications, where two completely different apps can run on the same port at different times.

The reason why I ask this is simple, I can never be sure that any output of Wappalyzer is reliable. Why? Because a website at some domain can partially or completely migrate their systems into different technologies, but Wappalyzer would still report the previous stack.

**Comment by AlexByte** [comment]
Wappalyzer storing URLs with associated technologies only during session in browser.

**Comment by jemhuntr** [comment]
That's great to hear. Thanks! That solves my problems :)
