### ISSUE TITLE
Add support for Episerver and Episerver Commerce

### ISSUE THREAD

**Issue by andyjohansson** [AliasIO/Wappalyzer#1725]
Would be great if Wappalyzer could add support for Episerver and Episerver Commerce.
http://www.episerver.com/

**Comment by AlexByte** [comment]
Already.

**Comment by andyjohansson** [comment]
I have some example sites that it does not detect, for example:
https://www.hiab.com/

**Comment by AlexByte** [comment]
where did you get this site to use episerver?

**Comment by andyjohansson** [comment]
I know the develops who works on the site.

**Comment by AlexByte** [comment]
He hides the fact of using this CMS.
