### ISSUE TITLE
Unable to push new application

### ISSUE THREAD

**Issue by julienszabados** [AliasIO/Wappalyzer#1732]
Hello,

when i'm trying to push a new application to your repository, i have this following error :
```
remote: Permission to AliasIO/Wappalyzer.git denied to julienszabados.
fatal: unable to access 'https://github.com/AliasIO/Wappalyzer.git/': The requested URL returned error: 403
```

What happened ? :(

**Comment by gadcam** [comment]
Hello,
I think you tried to push something directly to the repository of AliasIO but you don't have the permission to do so.
So you need to push to your own repository on github and then do a pull request which will be accepted, or not, by the owner of the repository (see https://help.github.com/articles/about-pull-requests/)

**Comment by julienszabados** [comment]
My bad. It's OK ^^
