### ISSUE TITLE
Add problem (Failure & Pending)

### ISSUE THREAD

**Issue by idpack** [AliasIO/Wappalyzer#1734]
How can we add our (App or Technology) to Wappalyzer in GitHub?

**Comment by AlexByte** [comment]
You should create a pull-request.

**Comment by idpack** [comment]
What is problem of this pull request? https://github.com/AliasIO/Wappalyzer/pull/1718

**Comment by AlexByte** [comment]
https://github.com/AliasIO/Wappalyzer/wiki/Contributing

**Comment by hfrid** [comment]
Well how do you upload the icon? It wont build without the icon being present?
