### ISSUE TITLE
Issue with ASP.NET identified as EPages 

### ISSUE THREAD

**Issue by jooiiee** [AliasIO/Wappalyzer#1744]
Pages sending X-Powered-By: ASP.NET and X-AspNet-Version: 4.0.30319 are incorrectly labled as as EPages. 

Maybe a syntax issue? From line 2280 in the apps.json in master. 

`"EPages": {  
			"cats": [  
				"6"  
			],  
			"headers": {  
				"X-Powered-By": "epages 6"  
			},  
			"html": "<div class=\"BoxContainer\">",  
			"icon": "epages.png",  
			"website": "http://www.epages.com/"  
		},  
		"EPiServer": {  
			"cats": [  
				"1"  
			],  
			"headers": {  
				"Set-Cookie": "EPi(?:Trace|Server)[^;]*="  
			},  
			"icon": "EPiServer.png",  
			"implies": "Microsoft ASP.NET",  
			"meta": {  
				"generator": "EPiServer"  
			},  
			"website": "http://episerver.com"  
},`

**Comment by AlexByte** [comment]
Give sites to test.
