### ISSUE TITLE
Wappalyzer got very different result from version5.0.0.

### ISSUE THREAD

**Issue by yasmineyan** [AliasIO/Wappalyzer#1747]
Hi, all:
I've installed Wappalyzer4.1.0 in /usr/lib/node_modules/ and Wappalyzer5.0.7 in /home/node_modules/. They got very different result in many webs:
in 4.1.0:
node /usr/lib/node_modules/wappalyzer/index.js https://wappalyzer.com/
{
    "url": "https://wappalyzer.com/",
    "originalUrl": "https://wappalyzer.com/",
    "applications": [
        {
            "name": "Amazon Cloudfront",
            "confidence": "100",
            "version": "",
            "icon": "Amazon-Cloudfront.svg",
            "website": "http://aws.amazon.com/cloudfront/",
            "categories": [
                "CDN"
            ]
        },
        {
            "name": "Google Analytics",
            "confidence": "100",
            "version": "UA",
            "icon": "Google Analytics.svg",
            "website": "http://google.com/analytics",
            "categories": [
                "Analytics"
            ]
        },
        {
            "name": "Nginx",
            "confidence": "100",
            "version": "1.10.3",
            "icon": "Nginx.svg",
            "website": "http://nginx.org/en",
            "categories": [
                "Web Servers"
            ]
        },
        {
            "name": "Snap.svg",
            "confidence": "100",
            "version": "",
            "icon": "Snap.svg.png",
            "website": "http://snapsvg.io",
            "categories": [
                "JavaScript Frameworks"
            ]
        },
        {
            "name": "Swiftlet",
            "confidence": "100",
            "version": "",
            "icon": "Swiftlet.png",
            "website": "http://swiftlet.org",
            "categories": [
                "Web Frameworks"
            ]
        },
        {
            "name": "Ubuntu",
            "confidence": "100",
            "version": "",
            "icon": "Ubuntu.png",
            "website": "http://www.ubuntu.com/server",
            "categories": [
                "Operating Systems"
            ]
        },
        {
            "name": "PHP",
            "confidence": "100",
            "version": "",
            "icon": "PHP.svg",
            "website": "http://php.net",
            "categories": [
                "Programming Languages"
            ]
        }
    ]
}

and in 5.0.7:
node /home/node_modules/wappalyzer/index.js https://wappalyzer.com/
resolve https://wappalyzer.com/
[
    {
        "name": "Google Analytics",
        "confidence": "100",
        "version": "UA",
        "icon": "Google Analytics.svg",
        "website": "http://google.com/analytics",
        "categories": [
            {
                "10": "Analytics"
            }
        ]
    }
]

Both of them are different from the plugin：
![1506505979 1](https://user-images.githubusercontent.com/5929147/30907288-d13f5830-a3ac-11e7-980b-149ec3a93c73.png)

Please tell me how to fix it. Thx.

P.S.
My node version: v6.11.0

and operation system:
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.3.1611 (Core) 
Release:	7.3.1611
Codename:	Core

**Comment by AlexByte** [comment]
Duplicate https://github.com/AliasIO/Wappalyzer/issues/1719
