### ISSUE TITLE
Wappalyzer stops global functions from running when query string is added to URL

### ISSUE THREAD

**Issue by g5insider** [AliasIO/Wappalyzer#1750]
I'm writing a backbone app and using the wappalyzer chrome extension. Whenever I add a query string parameter to my URL that has already loaded it causes my app to fail.

Hit route #aboutme
Page loads fine no issues
Hit route #aboutme?action=benefits
Page reloads, fails to execute global functions and causes my application to log the user out due to loss of data that is provided in the global function.

This only happens when I have the extension running. If I disable wappalyzer the app works with no error.
Seems like the newest update to wappalyzer is causing these issues.

**Comment by AlexByte** [comment]
Why you have closed the issue?

**Comment by g5insider** [comment]
This is actually related to a Chrome bug not wappalyzer.

**Comment by AlexByte** [comment]
> If I disable wappalyzer the app works with no error.

but why bug rotated with the enabling of a wappalyzer?

**Comment by g5insider** [comment]
The way my app is written is to stop certain behavior when multiple tabs on the browser are open. I have two tabs open after disabling wappalyzer. When I tested the app I thought it was because wappalyzer was no longer running but what it really was, was that I had multiple tabs open.

The issue I have run into is happening with other users who have not used wappalyzer. It is a Chrome bug that was introduced recently and is fixed in beta.
