### ISSUE TITLE
Overly Aggressive polling of robots.txt by Web Extension

### ISSUE THREAD

**Issue by jrjenk** [AliasIO/wappalyzer#1751]
I have noticed that my system has started triggering mod_evasive on some Apache Web Servers.  When I looked into the issue it seems my browser is repeatedly trying to load the robots.txt file, eventually triggering the too many requests for the same URI and blocking me.

While the unblock window is fairly small, this seems like this might catch other people as well.

There is no robots.txt file on the server, so it seems like it should probably cache, at least for a little while, that trying to fetch the robots.txt returned a 404.

**Comment by jvoisin** [comment]
Wappalyzer doesn't issue http requests on its own. Your issue might come from something else.

**Comment by AlexByte** [comment]
@jvoisin Surprise, it's issue.

**Comment by jrjenk** [comment]
@jvoisin , are you sure?

I was pretty sure I saw something in 'src/drivers/webextension/js/driver.js' in 'wappalyzer.driver.getRobotsTxt' which was using the fetch method to grab the robots.txt file which is why I opened the issue here. 

```
/**
 * Fetch and cache robots.txt for host
 */
wappalyzer.driver.getRobotsTxt = (host, secure = false) => {
  return new Promise((resolve, reject) => {
    getOption('robotsTxtCache')
      .then(robotsTxtCache => {
        robotsTxtCache = robotsTxtCache || {};

        if ( host in robotsTxtCache ) {
          resolve(robotsTxtCache[host]);
        } else {
          var url = 'http' + ( secure ? 's' : '' ) + '://' + host + '/robots.txt';

          fetch('http' + ( secure ? 's' : '' ) + '://' + host + '/robots.txt')
            .then(response => {
              if ( !response.ok ) {
                if ( response.status === 404 ) {
                  return '';
                } else {
                  throw 'GET ' + response.url + ' was not ok';
                }
              }

              return response.text();
            })
            .then(robotsTxt => {
              robotsTxtCache[host] = wappalyzer.parseRobotsTxt(robotsTxt);

              setOption('robotsTxtCache', robotsTxtCache);

              resolve(robotsTxtCache[host]);

              var hostname = host.replace(/:[0-9]+$/, '')
            })
            .catch(reject);
        }
      });
  });
};
```

It looks to me like it is only caching if it receives response text, which is why I was suggesting it might be better to cache the 404 somehow.

@AlexByte Thanks for commenting.

**Comment by jvoisin** [comment]
Damn, you're right, this is indeed an issue, sorry for the noise :/

**Comment by jrjenk** [comment]
@jvoisin It's all good. I should have provided more detail on why I thought this might be the issue in the first place, I was just in too much of a hurry.

**Comment by AliasIO** [comment]
It specifically handles 404 by returning an empty string, which then gets cached. When I test this on example.com it only attempts to fetch robots.txt once. Would you be able to share a URL for testing?

**Comment by jrjenk** [comment]
@AliasIO 

I missed that you were caching the empty string, I am afraid ES6 and Promises are things I am not overly proficient with so I completely overlooked that when skimming the code originally.

Now that I see that the caching is there I am thinking this might be something unrelated to the extension itself, but that because the extension is making the request I am seeing it get caught by mod_evasive.  Since I wasn't expecting the extension to make a web request (I thought it just analyzed the page's DOM for patterns), I probably jumped the gun on opening an issue.

However, just in case you are curious and want to know, the site that it has happened to me the most on is www3.ca.uky.edu.  You won't really see anything on that web address though as we just use it to host registration forms and there are not currently any open.  The main page really just returns a text string of the hostname. So I am not sure it is a great test right this moment.

I can't get you server side logs or look at the server configuration until Monday, but if you let me know the approximate time and what IP address you connect from I can pull something if needed.  

Given the above insights, a couple of other things did occur to me:

- It does seem to happen the most frequently when resuming Chrome and having multiple tabs open.  There is a chance I had multiple pages from that host open in more than one tab.  is it possible that the Browser Extension is invoked concurrently if multiple tabs are open?  Most pages on the site would have unique URLs, but the robots.txt file is a fixed entity so if extension events get fired for all tabs as soon as Chrome launches, that might explain it.
- This one is more for me, but perhaps I should examine the mod_evasive configuration more closely.  There is always a chance the DOSSiteCount/DOSSiteInterval settings are lower than I thought. Since I am on the same network the round trip time is pretty quick, perhaps mod_evasive is actually triggering before the extension attempts to fetch robots.txt, and I what I am seeing is its first request and then any retries it might make since it received a 503 response when it was blocked, which wouldn't be cached.

Thanks for taking the time to look, I will update this on Monday just to let you know what I see.

-jrj

**Comment by AliasIO** [comment]
I suspect it's your second point as I'm not seeing this behaviour on that URL. It's not ideal that Wappalyzer attempts request robots.txt once for every detected application in case of an error though, perhaps we should add a cooldown period.

Note that robots.txt will not be fetched if tracking is turned off in the extension settings.

**Comment by jrjenk** [comment]
So it turns out there is a form live at https://www3.ca.uky.edu/forestry/forest-management/new.php if you want to see one that is live. For that site Wappalzer is showing me 6 items in use, so from what you said it would try to grab robots.txt file (assuming it wasn't cached) 6 times?  If that is the case and it tried to process those requests in parallel then that might explain it. 

The server is configured to block people if the exact same resource is requested 4 times within 1 second.

When you said that the robots.txt file will be hit only when tracking is turned on, did you mean then 'Anonymously send reports on detected applications to wappalyzer.com for research' option?  I don't see any option specifically about "tracking" in the options of the extension:

![wappalyzer-options](https://user-images.githubusercontent.com/4514665/31082770-c7a84854-a75d-11e7-889d-b683dc1f21b1.png)

Additionally, if I click on "Inspect Views" in Chrome and look at the contents of 'Local Storage' I don't see any entry for 'robotsTxtCache' and changing the options on the options above don't seem to change any of the stored values in the Local Storage Cache.  But this could be completely normal since I know that chrome tries to separate the page's local storage from content scripts local storage and I am not sure how to view the data used by the content scripts, I just wanted to provide some additional details.

![wappalyzer-inspect](https://user-images.githubusercontent.com/4514665/31082906-201a1422-a75e-11e7-8584-9ce751183e63.png)

**Comment by AliasIO** [comment]
> For that site Wappalzer is showing me 6 items in use, so from what you said it would try to grab robots.txt file (assuming it wasn't cached) 6 times?

Only if fetching robots.txt repeatedly returns an error. The extension still isn't likely to be the cause of the issue.

> When you said that the robots.txt file will be hit only when tracking is turned on, did you mean then 'Anonymously send reports on detected applications to wappalyzer.com for research' option?

Yes, that's the one.

> Additionally, if I click on "Inspect Views" in Chrome and look at the contents of 'Local Storage' I don't see any entry for 'robotsTxtCache' and changing the options on the options above don't seem to change any of the stored values in the Local Storage Cache.

Right, you probably can't see values stored by extensions. Not sure about this though.

**Comment by ExiaSR** [comment]
Any update? It broke my company's SSO log page all the time.

**Comment by kyletaylored** [comment]
This still seems to be somewhat prevalent, so I'll mark as a bug and take a look later.

**Comment by luciddr34m3r** [comment]
I'm experiencing this defect as well.
