### ISSUE TITLE
Choose Wappalyzer's language manually.

### ISSUE THREAD

**Issue by brownsugar** [AliasIO/Wappalyzer#1754]
Recently I've noticed that Wappalyzer widget's title starts displaying Simplified Chinese, but I want it keeps using English title, I wish there is a way to change it for myself.
![image](https://user-images.githubusercontent.com/2935980/31088277-a9aa4292-a7d2-11e7-8420-fc12ec9ebf05.png)

**Comment by AliasIO** [comment]
It should be the same as your browser language, is that not the case? There is no option to change it in the extension.

**Comment by brownsugar** [comment]
Nope. My language is Traditional Chinese, but it shows Simplified Chinese.

**Comment by gadcam** [comment]
Can you confirm [this file](https://github.com/AliasIO/Wappalyzer/blob/master/src/drivers/webextension/_locales/zh/messages.json) is Simplified Chinese ? If it is the case could you help us translate in Traditional Chinese by translating this file ?

**Comment by brownsugar** [comment]
Yes, it's Simplified Chinese.
Sure I can help translate it, so what I need to do is to fork and make pull request?

**Comment by gadcam** [comment]
Yes if you can do that it would be perfect and we will be glad to have one more translation for Wappalyzer!
