### ISSUE TITLE
sitecore is still not detected on some sites

### ISSUE THREAD

**Issue by softineer** [AliasIO/Wappalyzer#1757]
Sitecore is still not detected on some sites that are built on Sitecore.  Is there a way to look for "Sitecore" within the files described in the below stackoverflow link "i.e. default.aspx"?

> You could check for other Sitecore files, but again depending on the deployment these may or may not be there or accessible to the public at least. I would look for files outside of the /sitecore folder, e.g.:
> 
> default.aspx
> default.css
> default.js
> webedit.css

https://stackoverflow.com/questions/21938171/detect-whether-a-site-is-build-on-sitecore

**Comment by AlexByte** [comment]
Now it's not possible.

**Comment by gadcam** [comment]
However we could try to detect to detect the cookies see https://stackoverflow.com/a/21939101/1906722

**Comment by softineer** [comment]
This sounds good.  I tried this on a couple of sites that I know are Sitecore, but that Wappalyzer doesn't identify as such, and I noticed that some have the cookie but others don't have the cookie but have access to certain Sitecore assets that I listed below.

Also, another cookie that I discovered that's Sitecore is:

SC_EXPVIEW
This analytics cookie is provided by Sitecore. It stores whether or not the Sitecore Experience View Mode is enabled. This cookie is not used to identify individuals using the website.

**Below are some sites that Wappalyzer is **_NOT_** identifying as Sitecore, even though they appear to be so:**
https://www.tacobell.com/~/media/System/Template%20Thumbnails/audio.ashx  (this one also has the sp_expview cookie)

http://www.crayola.com/sitecore/shell/sitecore.version.xml

https://www.sitecore.net/ (uses the SC_ANALYTICS_GLOBAL_COOKIE)

http://www.mayoclinic.org/~/media/System/Simulator%20Backgrounds/blackberry.ashx

**Comment by gadcam** [comment]
Ok so if the patterns seem good to you maybe you could do a pull request.
You have a little "contributing" guide [here](https://github.com/AliasIO/Wappalyzer/wiki/Contributing) to help you.
For the crayola website the only thing I could find is
```html
<div class="hide" id="sitecore_popup-location">
````
it looks like the website is ran by Demandware (partly at least).

**Comment by jvoisin** [comment]
If there is no interest in adding this detection, this issue can be closed :)
