### ISSUE TITLE
Use application icon instead of Wappalyzer logo

### ISSUE THREAD

**Issue by gomesphoto** [AliasIO/Wappalyzer#1763]
I absolutely love this chrome extension and really appreciate the frequent updates and improvements.

I have a suggestion for when the user enables  the option "Use application icon instead of Wappalyzer logo". Could we give priority to the icon for the Javascript Framework used over icons from other tools like Analytics, Cache and Issue Trackers. In my opinion this is these are the most relevant tools after maybe Web Server probably

**Comment by AliasIO** [comment]
It's currently prioritised over analytics and caching tools. Issue trackers is higher up because I'd argue it's usually the primary application.

https://github.com/AliasIO/Wappalyzer/blob/master/src/apps.json#L10787
