### ISSUE TITLE
Speed issues between versions

### ISSUE THREAD

**Issue by newmanships** [AliasIO/Wappalyzer#1765]
Hi,
I've noticed big speed differences between the latest version and v4.1.5 (which uses phantomjs). The older version is always around ~1sec to run, whereas the current version (which uses zombiejs) time averages around 6 seconds, with the fastest I've seen is 4seconds. Any idea how to improve the performance?

Thanks.

**Comment by AliasIO** [comment]
I'm not seeing a significant speed difference. Can you try running it on http://localhost to get an idea of speed without fetching a page from the internet?

**Comment by fones** [comment]
When running in AWS Lambda, with 128MB of RAM it takes from 20 to 90 sec, and its a pain.

**Comment by michaelrimbach** [comment]
Same here

**Comment by AliasIO** [comment]
I believe that's because Lambda scales CPU with RAM. Allocating a larger amount makes it significantly faster.

**Comment by AliasIO** [comment]
I get ~700 ms on a small page with 768 MB RAM.

![screen shot 2017-11-27 at 8 54 12 am](https://user-images.githubusercontent.com/77259/33244735-bdb12f7c-d350-11e7-9c38-bb855dcd1126.png)

**Comment by fones** [comment]
This can be a solution!

128MB cost $0.000000208 per 100ms, and wapp run there for 40 sec, so the total cost is $0,000083200

768 MB cost $0.000001250 per 100ms, and wapp run there fo 1 sec, so the total cost is $0.000012500

We can save up to 40% running on 768MB.
