### ISSUE TITLE
aframejs is not detected

### ISSUE THREAD

**Issue by vyaspranjal33** [AliasIO/Wappalyzer#1772]
@AliasIO

**Comment by jvoisin** [comment]
Apparently, [aframejs]( https://github.com/aframevr/aframe/ ) is a popular javascript framework for doing VR stuff.

@vyaspranjal33 Feel free to submit a pull-request, it's [pretty simple] ( https://wappalyzer.com/docs) :)

**Comment by vyaspranjal33** [comment]
i can't upload icon file @AliasIO

**Comment by vyaspranjal33** [comment]
@jvoisin i've submitted PR but its not merged yet 😞

**Comment by vyaspranjal33** [comment]
@jvoisin can u please add it a way to detect aframejs as i am not able to do thanks in advance

**Comment by jvoisin** [comment]
It's ok, we're not in a hurry, you have the time to learn and do it on your own.

**Comment by vyaspranjal33** [comment]
its not about learning i am just unable to understand so i ve just requested you to do stuff @jvoisin
