### ISSUE TITLE
Add support for prism.js

### ISSUE THREAD

**Issue by phonicmouse** [AliasIO/Wappalyzer#1779]
http://prismjs.com/
https://github.com/PrismJS/prism

**Comment by jvoisin** [comment]
Hello @phonicmouse 

since you know javascript, what about submiting a pull-request to support prism.js?
Everything is explained in the [(nice) documentation]( https://wappalyzer.com/docs ) :)

**Comment by phonicmouse** [comment]
Thanks!

**Comment by jvoisin** [comment]
This was done in 7790c29e

This issue can be closed.
