### ISSUE TITLE
Is it possible to implement Wappalyzer support for Golang?

### ISSUE THREAD

**Issue by pifagor87** [AliasIO/Wappalyzer#1780]
Is it possible to implement Wappalyzer support for Go (Golang)?
Golang could use Wappalyzer.

**Comment by AliasIO** [comment]
It's supported but there aren't many ways to pick up on it, other than identifying applications that are known to be built on Go.

https://wappalyzer.com/applications/go

**Comment by pifagor87** [comment]
I am not meant to identify Golang as a programming language.
I am thinking of running wappalyzer scripts with Golang

**Comment by AliasIO** [comment]
Ah, yes. You could interface with the Node driver and write a wrapper in Go, or use something like [otto](https://github.com/robertkrimen/otto) to interpret JavaScript in Go (I have never used either so I'm not sure what's involved). I'm usually not in favour porting all of Wappalyzer to a different language as it makes it much harder to maintain.

**Comment by pifagor87** [comment]
@AliasIO 
About https://github.com/AliasIO/Wappalyzer/tree/master/src/drivers/npm

Can I not use content download functionality here - 
`const wappalyzer = new Wappalyzer ('https://www.wappalyzer.com', options);`

And use analyze existing content? How?

**Comment by AliasIO** [comment]
You can create you own `driver.js`, which is a wrapper around `wappalyzer.js`. To analyse a HTML string you can call `wappalyzer.analyze()` like so: 

https://github.com/AliasIO/Wappalyzer/blob/master/src/drivers/npm/driver.js#L129

**Comment by altsab** [comment]
I made simple version of Wappalyzer in Go, check it out here: https://github.com/altsab/gowap .

**Comment by grafov** [comment]
Another implementation of Wappalyzer support for Go with ready to use utility: https://github.com/rverton/webanalyze

**Comment by kyletaylored** [comment]
Seems like workarounds exist.
