### ISSUE TITLE
Devextreme about

### ISSUE THREAD

**Issue by mtemel123** [AliasIO/Wappalyzer#1781]
Hi everyone
DevExtreme is very flexible and quality compenent, but wappalyzer doesnt detected. Can we add typescript angular and jquery version. 
https://js.devexpress.com/Demos/WidgetsGallery/
https://github.com/DevExpress/DevExtreme/
I think category js freamwork.

Regard

**Comment by jvoisin** [comment]
Hello @mtemel123  

since you know javascript, what about submiting a pull-request to support prism.js?
It's pretty easy, and everything is explained in the [(nice) documentation]( https://wappalyzer.com/docs ) :)
