### ISSUE TITLE
No applications detected, yet gives Google icon.

### ISSUE THREAD

**Issue by Zaseth** [AliasIO/Wappalyzer#1783]
When I took a visit on Lua's website, it gave me the Google icon, yet it tells me there's no application detected.

As seen here:

![alt text](https://i.gyazo.com/dab8a41de14a62a42edc7827b973da8e.png "wtf?")

**Comment by AlexByte** [comment]
Because no applications, except Cherokee, are used.

**Comment by AlexByte** [comment]
not confirmed

**Comment by jvoisin** [comment]
I can't reproduce too: Cherokee webserver is detected.

**Comment by gadcam** [comment]
Solved by 9eaf963 (see #1785).

**Comment by AlexByte** [comment]
@gadcam The problem was not this. It's unclear why Google icon was showed on Zaseth's screen.
