### ISSUE TITLE
fails to detect the Cherokee web server on lua.org

### ISSUE THREAD

**Issue by divinity76** [AliasIO/Wappalyzer#1785]
should be easy, given the http response header `Server: Cherokee`

**Comment by divinity76** [comment]
guess that they try to avoid exposing theoretical security vulnerabilities by not disclosing the version running. Cherokee is already in the db, here is the regex

`"Server": "Cherokee/([\\d.]+)\\;version:\\1"`

maybe change it to
`"Server": "Cherokee(?:/([\\d.]+)\\;version:\\1)"` 
would fix it?   (there's also something to be said about using ^ which would probably be faster to execute, but i feel that's for another discussion)

**Comment by gadcam** [comment]
I think so but you have to write it like this as the version tag is processed separately (i.e. it is not a part of the regex)
```js
"Server": "Cherokee(?:/([\\d.]+))?\\;version:\\1"
```

**Comment by jvoisin** [comment]
This is been done in 9eaf963f. This issue can be closed.

**Comment by divinity76** [comment]
nice.
