### ISSUE TITLE
Getting fewer results when using NodeJS as driver

### ISSUE THREAD

**Issue by anthonycali** [AliasIO/Wappalyzer#1789]
Hi there,

I have been seeing some weird behavior when using NodeJS as the driver. Sometimes I get fewer results when using NodeJS.

I noticed this today when I tested Wappalyzer with stripe.com.

For most requests I get 6 results back (Facebook, Google Analytics, Mixpanel, Nginx, Segment, Stripe). Every once in a while tho, I will run wappalyzer using NodeJS and I get back just Nginx and Stripe. Usually if I run it again, I will get back the full results. However, If I want for a few minutes and try again, there is a good chance I will get the smaller list again. 

Another weird that is happening is that when it prints out the correct 6 results, the execution will actually hang and node will not return. I have to kill the process. When it just gets 2 results, it doesn't hang. Not sure if this helps, but I figured I should mention it (it was also referenced [here](https://github.com/AliasIO/Wappalyzer/issues/1719#issuecomment-333792944) )

I never got "fewer" results with Docker, the extension or the bookmarklet.

Has this happened to anybody else? 

Details:
NodeJS version: Have tested with v8.8.1 and 6.11.5 (same results in both)
Operating System: macOS Sierra

**Comment by AlexByte** [comment]
Duplicate https://github.com/AliasIO/Wappalyzer/issues/1719
You have to build a new version of the node module yourself.

**Comment by joaobatalha** [comment]
@AlexByte I did clone the repo and ran `npm install /Wappalyzer/src/drivers/npm`, and I'm still getting the same results. Is there anything I'm missing?

**Comment by anthonycali** [comment]
@AlexByte I did clone the repo and ran npm install /Wappalyzer/src/drivers/npm, and I'm still getting the same results. Is there anything I'm missing?

**Comment by AlexByte** [comment]
I have three results on https://stripe.com/

![image](https://user-images.githubusercontent.com/25251772/32202585-dd96ee7a-bdee-11e7-9de9-04a2c78b4a51.png)

**Comment by AliasIO** [comment]
If you click around on the Stripe website it will pick up on more technologies and remember them. That might explain why the browser version is showing more results for you.

**Comment by anthonycali** [comment]
@AliasIO what about docker? 
Only node is giving me a different result (same 6 results for extension, bookmarklet and docker).  It also seems like a bug because sometimes I will run it 5 times and 4 will return the full results and one will have fewer.

**Comment by AlexByte** [comment]
>  it will pick up on more technologies 

What does it mean?

**Comment by AliasIO** [comment]
Docker is just a [wrapper around the NPM driver](https://github.com/AliasIO/Wappalyzer/blob/master/src/drivers/npm/Dockerfile). Have you tried installing Wappalyzer through NPM?

**Comment by AliasIO** [comment]
> > it will pick up on more technologies.

> What does it mean?

I means that different technologies may be identified on pages other than the homepage. You often get more results the more pages you view.

**Comment by AlexByte** [comment]
In my opinion, the results are remembered only for this url and are remembered only in the extension.

**Comment by AlexByte** [comment]
Why install the old version with NPM?

**Comment by anthonycali** [comment]
@AliasIO I did try installing wappalyzer thru NPM (`npm install wappalyzer`). same results. Could the node version be an issue?

**Comment by AliasIO** [comment]
Does the NPM version hang as well? I don't think it's a Node issue but perhaps a dependency has been updated. You're using Wappalyzer version 5.1.3?

**Comment by AlexByte** [comment]
This is because the site is not friendly with zombie.js, which has a DOM implementation other than WebKit. Similar already [was](https://github.com/AliasIO/Wappalyzer/issues/1624#issuecomment-327480958).

```
>node
> var Browser = require("zombie");
undefined
> var browser = new Browser();
undefined
> browser.visit("https://stripe.com",
...   function (err, browser) {
.....     if (err) { console.log('Error:' + err.message); }
.....     else { console.log('Page loaded successfully'); }
..... });
null
> Error:runkitEnabled is not defined
```

**Comment by AlexByte** [comment]
It's because of [this](https://github.com/AliasIO/Wappalyzer/issues/1624#issuecomment-327476319). In this case, there is not enough time to execute js.

**Comment by AliasIO** [comment]
Good to know. Sounds like we may need to specify a timeout value.

**Comment by AlexByte** [comment]
Default wait duration is 
https://github.com/assaf/zombie/blob/22236d46102c5a97d38e382a6c7299e27fb75010/src/index.js#L252

**Comment by anthonycali** [comment]
@AliasIO Yes the NPM version hangs. I just spun an ec2 instance with Ubuntu 16.04, installed node 6.11.5, installed wappalyzer (npm install wappalyzer), and tried getting the technologies of stripe.com (using the script included [here](https://www.npmjs.com/package/wappalyzer)) and it hangs.

@AlexByte Did you mean that the "hanging" was because of a timeout error? Or were you referring to not getting all of the technologies back?

**Comment by AliasIO** [comment]
This should be fixed by 3327fa18c80700ad48101784ea6acc66604f37bf. Wappalyzer will wait for resources on the page to load. The default timeout for this is three seconds, you can change it by passing `--max-wait=<ms>`.

**Comment by AlexByte** [comment]
@AliasIO  Why the default timeout is lesser than it was?

**Comment by AliasIO** [comment]
To make it more responsive. Usually it's enough to identify most applications.

**Comment by AlexByte** [comment]
@AliasIO What's good about scanning is less accurate?

**Comment by AliasIO** [comment]
It's a trade-off, it makes a big difference when scanning a lot of pages. Note that the browser extension doesn't wait at all. In any case, it's configurable.
