### ISSUE TITLE
False positive for "Now" on Google Translate

### ISSUE THREAD

**Issue by Jesse97** [AliasIO/Wappalyzer#1793]
On Google Translate, the webserver *Now* is detected by Wappalyzer.

It seems that Wappalyzer checks for 'now' in the `server` header, while the full header is `server: HTTP server (unknown)` (note 'now' being in 'unknown').

**Comment by q--** [comment]
Seems like this isn't the only false positive either; the top result on the Now  [Wappalyzer.com page](https://wappalyzer.com/applications/now) is keepvid.com, which sends the header `Server: Tengine/unknown`
