### ISSUE TITLE
Easiest way to use latest version of Wappalyzer in my project

### ISSUE THREAD

**Issue by anthonycali** [AliasIO/Wappalyzer#1796]
Hi there - This isn't really an issue with the project but I've been struggling with it for a while now, so I thought I might ask. 

This should be a pretty basic question, but I am having trouble setting up the latest version of Wappalyzer as a dependency on my project. I want to use `v5.1.4`, but right now if I do `npm i wappalyzer` it will install `5.1.3`. At first I thought I could just point npm to the github, but that didn't work (from my understanding it's because you need to run `./run links` before you can tell npm to install the package in the folder `./src/drivers/npm` - Let me know if I'm wrong here)

This seems like a very basic question but I'm stuck on this. Would appreciate some help. 
Thanks!

**Comment by AliasIO** [comment]
You could execute `./run links` with a [postinstall script](https://docs.npmjs.com/misc/scripts) or use [`npm link`](https://docs.npmjs.com/cli/link) to include the package from a local folder. I'll probably push a new version up soon though.
