### ISSUE TITLE
NodeJS driver can't find technologies for some websites

### ISSUE THREAD

**Issue by anthonycali** [AliasIO/Wappalyzer#1805]
I was testing out the most recent release (5.1.5) and if I try `node index.js https://www.twotap.com` I don't get any technologies back (it seems that a JavaScript error might be halting the execution of? - tho from taking a quick look at the code that should not be possible). 

If I use docker, the chrome extension or the bookmarklet on that same website I can get back the results.

**Comment by AliasIO** [comment]
Fixed in 5c68a1503f62a775453f6351bb7fe82e09382191, thanks.
