### ISSUE TITLE
Strange random freeze on http://alexa.com using npm driver

### ISSUE THREAD

**Issue by avasilkov** [AliasIO/Wappalyzer#1814]
I'm using latest commit 77c867a48f1e13c45b8f1769fff0e4f874fccac1
I'm setting maxWait to 15000, tried 100000 as well (without freezes it needs 3s of requests and 10s total of wall time for full processing)
And sometimes it gets processed ok, but other times it hangs after it enters visit() but before it enters wait()
then it waits until maxWait has expired and only then continues, what might be the problem? Tried with zombie debug on, nothing of note there when it hangs, tried cross reference the urls from debug output and they are the same both times(not 100% sure, extracted them from output using this https://www.browserling.com/tools/extract-urls )

node src/drivers/npm/index.js http://alexa.com --maxWait=15000 --userAgent=noua

Another small question, could anyone explain the difference between wait(param) and Browser(waitDuration:param), does it work like this? - waitDuration counts total wall time for all requests(without including wappalyzer analyze time) and maxWait that goes into wait(maxWait) sets limit only on each requestseperately, is this correct?

**Comment by AliasIO** [comment]
I'm getting consistent results with a `maxWait` of 3000.

`wait` will exit when all resources are loaded, or when it's waited for `maxWait` millseconds. I don't think the `waitDuration` option exists any more. 

http://zqdevres.qiniucdn.com/data/20110811173813/index.html

**Comment by avasilkov** [comment]
Well, maybe you are right, doesn't matter if it gets all the requests through, this way it can be really slow and not even influence the end result.

Here's waitDuration option
https://github.com/assaf/zombie/blob/master/src/index.js#L33
And if you print browser.waitDuration in driver.js, it will show '5s'. Although I'm not sure if it influences anything or if it's being overridden by wait param.

**Comment by AliasIO** [comment]
Looks like it's the same option, it sets `options.duration` to the first argument if it's a number and `Browser.waitDuration` otherwise.

Is using a lower value not an option for you?

**Comment by avasilkov** [comment]
No, it's okay, I was just thinking maybe it needed more time on slow websites.
I'm not very good with javascript/nodejs,
we are calling visit() and then wait() inside it, right? and visit accepts options - we pass only callback and url so options are {} https://github.com/assaf/zombie/blob/master/src/index.js#L538 and then it calls wait internally with these options and since they are {}, it uses waitDuration as wait param for this internal call. and maxWait is only used for our external call. If my thinking is wrong, I'm sorry, please ignore it, it's not very important I guess, and I have no idea how promises work.
I guess you could close this if this behavior is not important for the wappalyzer.

On a different note, if you are interested:
http://lemse.com.br breaks on this website
```
/home/saya/node_modules/zombie/lib/eventloop.js:594
            throw error;
            ^
TypeError: Cannot read property 'response' of undefined
    at browser.visit.error (/home/saya/testwap/Wappalyzer/src/drivers/npm/driver.js:64:40)
```

**Comment by AliasIO** [comment]
> it uses waitDuration as wait param for this internal call. and maxWait is only used for our external call

I'm not sure what you mean by this. It's using the `maxWait` option because it ends the request after three seconds if you set it to `3000`.

I made a fix (8db38ca79ad2545b0eeb31f201a0cdb8b5279c8f) for the 'Cannot read property 'response' of undefined' error.

**Comment by avasilkov** [comment]
Thanks for the fix!

What I've meant is browser.visit(url, error=>{browser.wait(maxWait).etc() })
we don't pass any options to visit, https://github.com/assaf/zombie/blob/92080eb770266e45c4fa1c0eb55bc2050c1d10eb/src/index.js#L538 and options become {}, then it calls https://github.com/assaf/zombie/blob/92080eb770266e45c4fa1c0eb55bc2050c1d10eb/src/index.js#L548 it calls https://github.com/assaf/zombie/blob/92080eb770266e45c4fa1c0eb55bc2050c1d10eb/src/index.js#L325 and since our options for visit were {} it uses waitDuration https://github.com/assaf/zombie/blob/92080eb770266e45c4fa1c0eb55bc2050c1d10eb/src/index.js#L272

**Comment by AliasIO** [comment]
I've changed this in the most recent version.
