### ISSUE TITLE
List of cryptominers with idea to implement detection

### ISSUE THREAD

**Issue by gadcam** [AliasIO/Wappalyzer#1821]
- [x] Should we create a separate category for cryptominers ?

Here is a list of popular webmining library I do not have time to include for the moment, fell free to add them if you have some time to do it :
- [x] Coin-Have <script src="https://coin-have.com/c/J5jd.js"></script>
- [x] Minero <script src="//minero.pw/miner.min.js"></script>
- [x] inwemo.com
- [x] webmine.cz/ authedwebmine.cz
- [x] https://coinlab.biz/en
- [x] cloudcoins.co // cdn.cloudcoins.co/javascript/cloudcoins.min.js // js pattern CLOUDCOINS
- [x] http://monerominer.rocks/

**Comment by jvoisin** [comment]
Yes we should ♥

This issue is related to #1820

**Comment by craiglondon** [comment]
I concur

**Comment by AliasIO** [comment]
Me too.

**Comment by jvoisin** [comment]
I opened a [pull-request]( https://github.com/AliasIO/Wappalyzer/pull/1859 ) about this.

**Comment by kkadosh** [comment]
@gadcam About the Minero webmining library, i found this other library : 
https://minero.cc which seem to be different from https://minero.pw/#/

Have you got an idea on how can we implement both of them since they have the same name?

**Comment by jvoisin** [comment]
It looks like both are scams.

Minero.pw isn't even working apparently :/

**Comment by gadcam** [comment]
The best could be to call them minero.cc and minero.pw.

**Comment by jvoisin** [comment]
Have you checked that they aren't using the same code by the way?

**Comment by kkadosh** [comment]
Yes they don't seem to use the same code. 
But now minero.cc is down.

**Comment by gadcam** [comment]
Minero.pw is a clone of CoinHive in the end so we do not need to care about it.
Thank you @kkadosh  for adding all these cryptominers!
So just cloudcoins and we are done! But maybe with the current hype there are new ones...

**Comment by gadcam** [comment]
100% implemented thanks to @kkadosh !
