### ISSUE TITLE
Google Analytics not detected

### ISSUE THREAD

**Issue by andywaite** [AliasIO/Wappalyzer#1829]
Sites which use Google Tag manager like this are not being detected.

https://www.rovanoarchitecture.co.uk

**Comment by gadcam** [comment]
Google Analytics & Google Tag Manager are both detected for me with Firefox and the last version of Wappalyzer.
What is your setup ?

**Comment by andywaite** [comment]
Using the command line Nodejs tool for the site I gave as an example, I only get Nginx detected.

`$ nodejs ./node_modules/wappalyzer/index.js https://www.rovanoarchitecture.co.uk/
[{"name":"Nginx","confidence":"100","version":"1.12.1","icon":"Nginx.svg","website":"http://nginx.org/en","categories":[{"22":"Web Servers"}]}]
`

**Comment by andywaite** [comment]
It looks like the reason for this is the spider Wappalyzer nodejs client uses is being 403'd - so not a bug here
