### ISSUE TITLE
Docker Timeout: did not get to load all resources

### ISSUE THREAD

**Issue by 8bitben** [AliasIO/Wappalyzer#1835]
Hi, I am having trouble running the docker packaged version of Wappalyzer - it frequently (and randomly) is exiting with error code "Timeout: did not get to load all resources on this page", even with a very long --max-wait time. Running via a Python 3 script.

```
Fetching technology for https://www.<removed>.com/
Traceback (most recent call last):
  File "dock.py", line 43, in <module>
    wapp_results = fetch_tech(site['site_url'])
  File "dock.py", line 18, in fetch_tech
    output = client.containers.run("wappalyzer/cli", url,"--max-wait=30000")
  File "/usr/local/lib/python3.5/dist-packages/docker/models/containers.py", line 741, in run
    raise ContainerError(container, exit_status, command, image, out)
docker.errors.ContainerError: Command 'https://www.<removed>.com/' in image 'wappalyzer/cli' returned non-zero exit status 1: b'Error: Timeout: did not get to load all resources on this page\n'
```

Any ideas on why this is failing? Should I just run it again until it gets a valid result or am I flagging max wait time incorrectly? Thanks.

**Comment by avasilkov** [comment]
Parameter for maxWait should be without '-'

**Comment by 8bitben** [comment]
Thanks for the suggestion, I don't think it's working though.

I changed the line in the python to        

```
 output = client.containers.run(
            "wappalyzer/cli", url, "--maxWait=3000")
```
...and yet timing shows that it's still failing after less than 15s:

```
Fetching technology for https://www.<removed>.com/
Fetch Failed
That function took 11.996739387512207 seconds
```

**Comment by avasilkov** [comment]
You forgot to add a zero? or is it only here 3000 and in the code it's still 30000?
What site are you trying to analyze btw?

**Comment by 8bitben** [comment]
I tried it with several different values (30,000//300,000//etc) and it did not seem to change anything. The site it's failing on is https://www.libertymutual.com/

**Comment by AliasIO** [comment]
The parameter `--max-wait` is correct, although `--maxWait` will work too. I'll try to update the Docker image this weekend and get you to test it again.

**Comment by AliasIO** [comment]
This should be fixed now, the image was updated last week.
