### ISSUE TITLE
Bootstrap naming 

### ISSUE THREAD

**Issue by gijsbotje** [AliasIO/Wappalyzer#1843]
As of lately bootstrap should not be linked to twitter
ref: http://getbootstrap.com/docs/4.0/about/brand/#name

I have a branch ready on my fork to resolve this
i am wondering though: does this break the current stats gathered with `Twitter Bootstrap`?
If so: how to fix it then?
https://github.com/gijsbotje/Wappalyzer/tree/bootstrap-naming

other questions
- the glyphicons have been deleted with the new v4 version, should it stay in for older versions?
- and what about the `env` statement, is that even correct?
- should the scripts attributes get an update?

**Comment by AliasIO** [comment]
Renaming an application means it will get a new page alongside the old one. I think that's OK though, the old page will eventually drop off.

- The glyphicon pattern can stay.
- The `env` pattern doesn't seem right, it should probably be removed.
- You can add new script patterns, using an array.
