### ISSUE TITLE
Add redirect from apex domain wappalyzer.com to WWW

### ISSUE THREAD

**Issue by AlexByte** [AliasIO/Wappalyzer#1862]
Add redirect redirect from https://wappalyzer.com to https://www.wappalyzer.com

**Comment by AliasIO** [comment]
It's annoying because I can't CNAME the root domain and Amazon CloudFront doesn't provide a static IP. I can't use an S3 bucket because it doesn't support Elastic IP either. I don't want to rely on a third party to issue the redirect so my only option is to use Amazon Route53, which is crazy expensive, or run a separate server, which is also a cost.

**Comment by AlexByte** [comment]
You are relying on a third party to issue the redirect actually.

**Comment by AlexByte** [comment]
The problem is only with accessing by https, it is clear.

**Comment by AliasIO** [comment]
Ah yep, that's what I meant. To host a certificate for the root domain I'd have to run a separate server, or use CloudFront with Route53. Not many people will navigate to the root domain over HTTPS directly, the problem is old links that I haven't been able to update.

**Comment by AlexByte** [comment]
You are using CloudFront because of DOS attacks?

**Comment by AliasIO** [comment]
For performance mainly, and free SSL.

**Comment by AlexByte** [comment]
You can use Let's encrypt for free certificate.

**Comment by AliasIO** [comment]
Last time I checked the certificate needs to be manually renewed and installed every three months unless you let their script manage your Nginx configuration (which I don't want to do).

**Comment by AlexByte** [comment]
@AliasIO yes, it's inconvenient.

**Comment by AliasIO** [comment]
I'll have a look into it again if I can find the time, once every three months isn't that bad I suppose.
