### ISSUE TITLE
robots.txt file request error with MS Sharepoint React framework

### ISSUE THREAD

**Issue by SKempin** [AliasIO/Wappalyzer#1865]
I have found a conflict when using Wappalyzer when developing MS Sharepoint webparts. Wappalzyer seems to be causing a request for a missing robots.txt file. The issue is detailed fully in the Sharepoint bug below.:

https://github.com/SharePoint/sp-dev-fx-webparts/issues/372

```
  Request: [::1] '/robots.txt'
Error: ENOENT: no such file or directory, stat 'C:\UOB\spfx\uob_listview\dist\public\robots.txt'

```

**Comment by AliasIO** [comment]
I think f5882705796179d455c7c41b3d588daa2b4bfd56 will fix this.
