### ISSUE TITLE
No support for iconless technologies

### ISSUE THREAD

**Issue by fedekau** [AliasIO/Wappalyzer#1885]
As the title says there is no support for sites without an icon, for example [https://www.inspectlet.com/](https://www.inspectlet.com/) has no logo, it's "logo" it is just a text with a specific font.

Maybe a solution can be taking a screenshot of the "logo" but it would fit horribly in a 32x32 or in a 64x64 png.

Do you think this is worth adding?

Thanks for the great app!

**Comment by jvoisin** [comment]
There is a logo: ![]( https://www.inspectlet.com/includes/assets/landing/images/favicon.ico )

**Comment by fedekau** [comment]
Ahmm I didn't new that! Thanks 😄
