### ISSUE TITLE
Missing Favicon 

### ISSUE THREAD

**Issue by ilyaGoncharov** [AliasIO/Wappalyzer#1892]
That's all, please add it

**Comment by ilyaGoncharov** [comment]
Chrome Version 62.0.3202.94 (Official Build) (64-bit)

**Comment by gadcam** [comment]
What do you mean ?

**Comment by maxibanki** [comment]
I think he mean the favicon on [www.wappalyzer.com](https://www.wappalyzer.com/). There is one, but that's a SVG. SVG's aren't supported in all major browsers, the best practice is to use PNGs or ICO's. 

The site isn't public on GitHub on my research, so we can't fix that.

**Comment by gadcam** [comment]
Thank you for the explanation. I do not know if we can say using that using an ICO is a good practice.. but you are right SVG are not supported by Chrome but Safari & Firefox support it : https://caniuse.com/#feat=link-icon-svg
Maybe we will be able to use SVG favicon in "a couple of quarters" https://bugs.chromium.org/p/chromium/issues/detail?id=294179#c43

**Comment by jvoisin** [comment]
@AliasIO ^ this is up to you :)

**Comment by AliasIO** [comment]
It's been there from the beginning.

https://www.wappalyzer.com/favicon.ico

**Comment by mxschmitt** [comment]
@AliasIO yes, but that's a SVG. SVG's are not officially supported as favicons. The best practice is to use PNGs there.

**Comment by AliasIO** [comment]
Added, cheers.
