### ISSUE TITLE
Mhonarc isn't detected

### ISSUE THREAD

**Issue by jvoisin** [AliasIO/Wappalyzer#1919]
MHonArc isn't detected on [full disclosure]( http://seclists.org/fulldisclosure/2017/Dec/38 ) and I don't get why :<

**Comment by gadcam** [comment]
It is because the comment we want to detect if before the html tag.
What we do to get HTML is not picking comments outside of this tag.
```js
var html = document.documentElement.outerHTML;
```
(cf https://github.com/AliasIO/Wappalyzer/blob/master/src/drivers/webextension/js/content.js#L4)

**Comment by jvoisin** [comment]
Thank you ♥
