### ISSUE TITLE
elixir and phoenix

### ISSUE THREAD

**Issue by anka09** [AliasIO/Wappalyzer#1932]
please add elixir and phoenix detection.

**Comment by fpoumian** [comment]
I've been noticing that the extension detects websites that use Cowboy as the server, but it doesn't detect Phoenix as the framework or Elixir as the language.

**Comment by jvoisin** [comment]
@anka09 Please do provide more information: What are elixir and phoenix? What websites are using them? Do you know how we could fingerprint them? …

**Comment by anka09** [comment]
http://elixir-companies.com/

ex: https://www.kittysplit.com/en/

**Comment by fpoumian** [comment]
@jvoisin Elixir is a functional programming language that targets the Erlang virtual machine:
http://elixir-lang.github.io/

Phoenix is the most popular MVC web framework for elixir:
http://phoenixframework.org/

I haven't found any way to fingerprint Elixir/Phoenix websites yet, but I'll submit a PR as soon as I do.

**Comment by kyletaylored** [comment]
I couldn't find any way to fingerprint these sites since by default they don't provide any custom headers or other types of detections. Closing to wait for future PR.
