### ISSUE TITLE
UI issue in Firefox

### ISSUE THREAD

**Issue by cfjedimaster** [AliasIO/Wappalyzer#1937]
In the latest Firefox, there is a small UI issue:

![image](https://user-images.githubusercontent.com/393660/34110693-0e0756a4-e3cd-11e7-84fb-4b783025bec3.png)

See the cut off text at the bottom? I was scrolled down as far as I could go.

**Comment by gadcam** [comment]
I have the same issue and also sometimes icons won't show up. But I think the problem is on Mozilla part...

![firefox](https://user-images.githubusercontent.com/1693643/34117347-b45ac452-e41b-11e7-96f4-5ab0a7963eff.png)

**Comment by gadcam** [comment]
These issues are described in https://bugzilla.mozilla.org/show_bug.cgi?id=1420865, https://bugzilla.mozilla.org/show_bug.cgi?id=1418677 & https://bugzilla.mozilla.org/show_bug.cgi?id=1380622

I suggest that those who want this issue to be solved to upvote these 3 bugs in bugzilla.

**Comment by AlexByte** [comment]
@gadcam how do you inspect this pop?

**Comment by gadcam** [comment]
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Debugging#Debugging_popups ;)
