### ISSUE TITLE
Google docs recognizes as Java application

### ISSUE THREAD

**Issue by maxibanki** [AliasIO/Wappalyzer#1951]
[Google docs](https://docs.google.com/document/u/0/) will recognize as a Java Application.

Code Pointer:
https://github.com/AliasIO/Wappalyzer/blob/e4cfe4599f161833dafe499ca54c2bf82000a40f/src/apps.json#L4427-L4436

As far as I can see, a `JSESSIONID` cookie is required for the detection. I tried to check the headers of Google Docs, but I don't find this header.

Best regards

Max

**Comment by gadcam** [comment]
The detection of OpenGSE is implying the use of Java. See https://github.com/AliasIO/Wappalyzer/blob/master/src/apps.json#L6534 and https://www.wappalyzer.com/docs/specification.

**Comment by maxibanki** [comment]
Ah okay. Thanks @gadcam!
