### ISSUE TITLE
Spelling and JSON errors on Specification page

### ISSUE THREAD

**Issue by ApCoder123** [AliasIO/Wappalyzer#1974]
On https://www.wappalyzer.com/docs/specification there are quite a few typos and errors. 
1. Apps.jon
> Patterns (regular expressions) are kept in **`src/apps.jon`.** The following is an example of an application fingerprint.
2.  Missing comma in JSON
```
"Application Name": {
  "cats": [
    "1"
  ],
	"js": {
		"ApplicationName.method": "",
	}
  "excludes": "Other Application Name" **MISSING COMMA **
  "headers": {
    "X-Powered-By": "Application Name"
  },
```

**Comment by AliasIO** [comment]
Fixed, thank you.
