### ISSUE TITLE
Invalid requests

### ISSUE THREAD

**Issue by Goblin80** [AliasIO/Wappalyzer#1978]
I was looking over my traffic and noticed some weird requests coming out Wappalyzer:
```
connecting e3648ce0-d022-4d98-a1d9-1559c0ee813c:80
unknown hostname e3648ce0-d022-4d98-a1d9-1559c0ee813c
```
running Wappalyzer 5.3.2 on Firefox 57.0.3 (64-bit).

**Comment by AliasIO** [comment]
Should be fixed in the next update.
