### ISSUE TITLE
Remove useless application

### ISSUE THREAD

**Issue by kkadosh** [AliasIO/Wappalyzer#1991]
Can we remove this application ?
```     
"Schneider": {
      "cats": [
        "45"
      ],
      "icon": "Schneider.png",
      "website": "http://schneider-electric.com"
    },
```
This application is only use as an implication of ```"Schneider Web Server" ```

**Comment by AliasIO** [comment]
It's not really useless if it can be identified but it looks like either of them are almost never picked up, so it can be removed.

**Comment by rizcheldayao** [comment]
Can I work on this issue?

**Comment by AliasIO** [comment]
Go for it!

**Comment by rizcheldayao** [comment]
Should Schneider Web Server be removed as well?

**Comment by AliasIO** [comment]
Yes, they can both go. Thank you!
