### ISSUE TITLE
Wappalyzer's NPM package supports which version of nodejs.

### ISSUE THREAD

**Issue by wujunze** [AliasIO/Wappalyzer#2000]
Wappalyzer's NPM package supports which version of nodejs.
The use of "wappalyzer" : "^ 5.1.3 in nodejs v. 6.9.5 test OK
Does "wappalyzer "support node 7 node 8?
![image](https://user-images.githubusercontent.com/12997869/34716353-91cd0552-f56a-11e7-82e9-f45514b9a120.png)
![image](https://user-images.githubusercontent.com/12997869/34716374-9eae8976-f56a-11e7-8d85-cd57b7870324.png)

**Comment by AliasIO** [comment]
I've tested it on 6.10, 7 and 8 should work too. I'll add it to the dependency list.

**Comment by wujunze** [comment]
@AliasIO   OK  Thanks
