### ISSUE TITLE
Subdirectory fingerprinting to detect admin panels

### ISSUE THREAD

**Issue by fuerbringer** [AliasIO/Wappalyzer#2002]
I believe I've stumbled upon a limitation when trying to add the [KeystoneJS CMS](http://keystonejs.com/) ([GitHub link](https://github.com/keystonejs/keystone)). Due to Keystones flexible nature it's really only possible to fingerprint it correctly by seeing if `<domain.tld>/keystone/signin` returns the expected admin login page. As fas as I'm concerned the existing patterns in the [specifications](https://www.wappalyzer.com/docs/specification) can't accomplish that.

Is subdirectory or subdomain fingerprinting planned, or is there a way to detect the above mentioned CMS using existing patterns?

My idea would be to add a key to check if `<current_domain>/<custom/sub>` returns a 200 HTTP response.

**Comment by AliasIO** [comment]
It's not planned. The extension would have to fire off dozens of requests on every website to identify technologies this way, which would interfere with people's browsing. You can still add the pattern but it would only pick up on the CMS when you visit that particular URL.

**Comment by gadcam** [comment]
It seems that on http://demo.keystonejs.com/keystone/signin there is a js variable <code>keystone</code> maybe we can find it in other setup on other pages.

**Comment by kkadosh** [comment]
There is also this pattern : ```Powered by <a href='http://keystonejs.com' rel='external'>KeystoneJS</a>``` in https://www.sydjs.com/ which allow to fingerprint without checking the ```/keystone/signin``` subdirectory

**Comment by fuerbringer** [comment]
@kkadosh I guess that's better than nothing and less resource blocking than checking for a subdirectory. It is after all by default injected by the [keystone-generator](https://github.com/keystonejs/generator-keystone/search?utf8=%E2%9C%93&q=Powered+by&type=).

Would it be OK if I created a PR which would check for that pattern? I'd also throw in a check for the signin page (but not with separate HTTP requests like @AliasIO said).

**Comment by fuerbringer** [comment]
@jvoisin The idea initially was to do a request to that signin page to detect that the site's running the CMS so outside visitors would know right away. Wappalyzer would know the site is running that CMS without actually being on the signin page. But again, like @AliasIO said it'd probably slow down things.
