### ISSUE TITLE
Getting a crash when testing on bourbon.batterii.com

### ISSUE THREAD

**Issue by lepolt** [AliasIO/Wappalyzer#2003]
https://cloudup.com/crzEX-UAk_o

**Comment by gadcam** [comment]
Can't reproduce with Wappalyzer 5.4.4 and Firefox 57.0.4
However sometimes it crashes randomly after and takes something like 10% of my CPU.
Maybe @jvoisin or @AliasIO do you have any idea to debug this sort of problem ?

**Comment by AliasIO** [comment]
Same issue as #2008.
