### ISSUE TITLE
Uncaught (in promise) again

### ISSUE THREAD

**Issue by k1r8r0wn** [AliasIO/Wappalyzer#2008]
![screen shot 2018-01-11 at 2 28 55 pm](https://user-images.githubusercontent.com/8123661/34815515-d1b29ee4-f6db-11e7-94d3-5658ef6b08d9.png)

Wappalyzer version: 5.4.4
Browser: Chrome v.63.0.3239.132

**Comment by gadcam** [comment]
Can you tell us a bit more on how to reproduce this ? Does it happen on regular web pages ?

**Comment by k1r8r0wn** [comment]
Actually, I've seen it  on my localhost dev environment, but then I turned off this extension - everything is clear in my console.

**Comment by cweb187** [comment]
+1 I'm also getting it on a local dev environment (hosts file DNS pointing to a local webserver)

**Comment by AliasIO** [comment]
The should be fixed, thanks.
