### ISSUE TITLE
Detect AMP pages

### ISSUE THREAD

**Issue by igrigorik** [AliasIO/Wappalyzer#2013]
As the title says, it would be great if we could identify [AMP](https://www.ampproject.org/) powered pages.

Example AMP page: https://www.ampproject.org/

**Comment by AliasIO** [comment]
Do you want to add it?

**Comment by rviscomi** [comment]
One thing that would be useful is to know if the page has an alternate AMP page. This can be detected with the [\<link rel="amphtml">](https://www.ampproject.org/docs/fundamentals/discovery) tag.

But I'm wondering if it'd be appropriate to add it to the AMP detector. For example, a page that has an alternate AMP page is not itself an AMP page, so marking it as an AMP app could be misleading. I wonder if there's a way to use the "implies" property to somehow suggest that AMP is present without claiming that the page is AMP?

FWIW I've got [a commit](https://github.com/rviscomi/Wappalyzer/commit/88db1ef708dfc483d5df72f658a09a8448966eaf) ready for PR to show how I'd add this link tag detection.

@AliasIO curious to hear your thoughts.

**Comment by AliasIO** [comment]
@rviscomi I don't think we should add that in, for the reason you mention. The popup should display the technologies used on that page.
