### ISSUE TITLE
Assuming Flask when Werkzeug present

### ISSUE THREAD

**Issue by robinsax** [AliasIO/Wappalyzer#2024]
Server headers containing Werkzeug/0.14.1 cause Flask to be identified, even when it isn't present. Explicit in Flask regex

**Comment by jvoisin** [comment]
I don't think that there are many setups where Werkzeug is used without Flask, are there?

**Comment by robinsax** [comment]
Right, the majority of setups using werkzeug are also using Flask, I guess unless Flask identifies itself explicitly there isn't a better alternative.
