### ISSUE TITLE
Add jeasyui, jquery ui, bootstrap ui, angularjs bootstrap ui

### ISSUE THREAD

**Issue by moham96** [AliasIO/Wappalyzer#2025]
Hi,
can someone add detection for these apps ? unfortunately i couldn't find a fingerprint to detect them

jeasyui
Site: https://www.jeasyui.com/
Demo: https://www.jeasyui.com/demo/main/index.php
Jqueryui
Site: https://jqueryui.com/
Demo: https://jqueryui.com/draggable/
boostrap ui:
Site: http://www.bootstrap-ui.com/
Demo: http://demo.bootstrap-ui.com/

angularjs bootstrap ui:
Site: https://angular-ui.github.io/bootstrap/

**Comment by sigfriedseldeslachts** [comment]
jQuery and jQuery UI are already added. AngularJS Boostrap is just Bootstrap.

**Comment by jvoisin** [comment]
No one is using [bootstrap-ui]( https://github.com/visionappscz/bootstrap-ui )
