### ISSUE TITLE
Reporting incorrect platform

### ISSUE THREAD

**Issue by Mynken** [AliasIO/Wappalyzer#2028]
https://futuresoftware.org/
Shows inccorect language. First time all was correct - IIS 8.5.
And now this extinsion shows PHP.

**Comment by gadcam** [comment]
Can you provide the exact web page where the detection could be wrong ? I could not spot neither IIS nor PHP.

**Comment by jvoisin** [comment]
Me neither.

**Comment by sigfriedseldeslachts** [comment]
Same as @gadcam
