### ISSUE TITLE
Uncaught SyntaxError: Unexpected token o in JSON at position 1 at JSON.parse (<anonymous>)

### ISSUE THREAD

**Issue by joanna-szuba** [AliasIO/Wappalyzer#2032]
To whom it may concern.

I'm a quality assurance. Found this error in one of the product I'm responsible for. Had to hide confidential data. Did anyone else notice this?

Env: Google Chrome, version 63.0.3239.108.

![error](https://user-images.githubusercontent.com/25527053/35226181-d3b8c53a-ff8a-11e7-836e-7f942106539e.png)

**Comment by gadcam** [comment]
Could you provide us more context ? To me it looks like there is no problem on Wappalyzer side.

**Comment by AliasIO** [comment]
Looks like the issue might be with `postMessage` from `inject.js`? Can you provide the URL of the page where you noticed this?

**Comment by gadcam** [comment]
I think this issue can be closed.
