### ISSUE TITLE
finding source codes of detecting

### ISSUE THREAD

**Issue by robertnicjoo** [AliasIO/Wappalyzer#2035]
Hi,

One of my clients has bought template from `themeforest` website and it seems that seller downloaded an online website and pull out html,css,js codes, and selling it there!!

Anyway, the issue is the website I'm creating base on that template shows that I'm using `Shopify` which obviously I'm not.  Now I wonder where exactly `Wappalyzer` get info that shows my website is Shopify based so I can remove that part and show the true back-end that I use?

thanks.

**Comment by robertnicjoo** [comment]
anyone?

**Comment by gadcam** [comment]
You can find the pattern here : https://github.com/AliasIO/Wappalyzer/blob/master/src/apps.json
For Shopify it is here to be accurate https://github.com/AliasIO/Wappalyzer/blob/master/src/apps.json#L8472
