### ISSUE TITLE
Ignoring HTTPS certificate errors

### ISSUE THREAD

**Issue by hixss** [AliasIO/Wappalyzer#2038]
driver.js  
strictSSL: false, 
Ignoring HTTPS certificate errors
--------------------------------------------
...
 visit(pageUrl, timerScope, resolve) {
    const browser = new Browser({
      silent: true,
      strictSSL: false,
      userAgent: this.options.userAgent,
      waitDuration: this.options.maxWait,
    });
...

**Comment by Lamboona** [comment]
This would be useful as an option to the top level Wappalyzer class, that was then passed down into zombie, much like the user agent option.

**Comment by mtbike61384** [comment]
This is a must add! We are running into this exact issue right now with hundreds of sites that won't return any results because we can't pass a flag to the CLI to disable certificate checks.

**Comment by AliasIO** [comment]
Added in 09ebc4aa486b5151ab05344e7611006a877408c2, thanks!

**Comment by mtbike61384** [comment]
Thank you so much! Do you know when Docker will get updated with this new commit? I did a Docker pull but it said it was already the latest.

**Comment by AliasIO** [comment]
I'll update it today.
