### ISSUE TITLE
401 authorization website cannot get HTTP data

### ISSUE THREAD

**Issue by hixss** [AliasIO/Wappalyzer#2039]
401 basic authorization website cannot get HTTP data

**Comment by jvoisin** [comment]
I don't understand your issue. 

Can you please give an example of what you're trying to do?

**Comment by hixss** [comment]
diver.js
...
resource.response.status !== 200 && resource.response.status !== 401
...

**Comment by AliasIO** [comment]
The NPM driver will scan pages that are fetched successfully. If authentication is required there isn't much left to do.
