### ISSUE TITLE
backend -Gazelle?

### ISSUE THREAD

**Issue by xrTor** [AliasIO/Wappalyzer#2047]
add support in Gazelle sites and it's Dependencies
https://github.com/WhatCD/Gazelle
memcache and sphinx

Memcached
Sphinx
procps-ng
Git
GCC/G++
Boost
and more

**Comment by jvoisin** [comment]
Care to provide a list of  websites that are using it?

**Comment by xrTor** [comment]
all gazelle sites are invite only register but wcd-mixtape you can just login with 'Rippy' username (auto) just wait and click login
http://159.89.252.33/index.php
