### ISSUE TITLE
Many logs in browser console after the last update

### ISSUE THREAD

**Issue by smelukov** [AliasIO/Wappalyzer#2053]
My browser console was flooded with logs from wappalyzer after the last update :(

![image](https://user-images.githubusercontent.com/6654581/35733723-8271bb2a-082f-11e8-825d-ee9b97418c56.png)

![image](https://user-images.githubusercontent.com/6654581/35733753-a502894e-082f-11e8-9042-11148758c129.png)

**Comment by hanzichi** [comment]
i find it too, pls remove it 😢

**Comment by cweb187** [comment]
+1

**Comment by Alximicus** [comment]
+))

**Comment by robinbentley** [comment]
Use reactions rather than +1 😢

**Comment by AliasIO** [comment]
This has been fixed, apologies.
