### ISSUE TITLE
Annoying console log forgotten

### ISSUE THREAD

**Issue by cristovao-alves** [AliasIO/Wappalyzer#2055]
A forgotten console.log() is showing all the time and it's showing in the middle of my own console log's. Please remove this.
![screenshot from 2018-02-02 16-26-59](https://user-images.githubusercontent.com/24396483/35743624-0d011988-0836-11e8-95e4-91799e056348.png)

**Comment by pcnate** [comment]
I can confirm this is Wappalyzer

**Comment by weary-adventurer** [comment]
Can confirm.
![image](https://user-images.githubusercontent.com/30081929/35749333-4831503c-0862-11e8-8deb-78f251a8e72e.png)

**Comment by AliasIO** [comment]
Fix has been pushed, sorry about that.
