### ISSUE TITLE
Remove console logging of message event in inject.js

### ISSUE THREAD

**Issue by rafaelklaessen** [AliasIO/Wappalyzer#2058]
Since v5.4.6 inject.js is logging some message event:
![screen shot 2018-02-03 at 00 14 23](https://user-images.githubusercontent.com/15846964/35759011-5c90ad6a-0877-11e8-97ee-e42ffffc4678.png)

This clutters the console which is kind of annoying.
It could be fixed by simply removing the `console.log` from inject.js

Thanks for the amazing tool! :)

**Comment by AliasIO** [comment]
This happened in 5.4.5 and has been fixed in 5.4.6.
