### ISSUE TITLE
Strange bug for Google detection (Joomla)

### ISSUE THREAD

**Issue by SaeedFazlollahzadeh** [AliasIO/Wappalyzer#2060]
![screenshot from 2018-02-03 20-21-56](https://user-images.githubusercontent.com/29482470/35769429-0d4b9392-0920-11e8-9826-c1679b385aaa.png)

Joomla!

**Comment by gadcam** [comment]
This part of the [html pattern](https://github.com/AliasIO/Wappalyzer/blob/master/src/apps.json#L4732) is the culprit
```regex
<[^>]+(?:feed|components)/com_
```
So whenever there is a link to a website using Joomla, Joomla will be detected.
Here it is the last link of Google last result with the request "download burning board 5".

I do not really know what we need to do as the confidence is already 50%.
Should we keep it like this, remove it or do we have a way to improve it ?

**Comment by SaeedFazlollahzadeh** [comment]
It's strange for me as it recognized Google having Joomla CMS.
Another example: google "can't copy files in linux site:askubuntu.com"
For me it again showed the same.
Your answer: "Should we keep it like this, remove it or do we have a way to improve it ?" "Surely remove it."
I remember in the previous versions, it detected google as nothing rather than google.

Last link? You mean https://www.scoop.it/t/burning-board-2-download ?
It doesn't have joomla.

**Comment by AliasIO** [comment]
I updated the pattern to `<(?:link|script)[^>]+(?:feed|components)/com_`, that should fix it.
