### ISSUE TITLE
Wappalyzer Causes Errors w/ DigitalOcean Monitoring

### ISSUE THREAD

**Issue by jswny** [AliasIO/Wappalyzer#2095]
Recently I stumbled upon a very odd situation. DigitalOcean by default shows a few graphs including public bandwidth, private bandwidth, CPU, and disk I/O. However, you can install the `do-agent` on your server to enable advanced monitoring such as top processes. However, when the Wappalyzer Chrome extension is enabled, the DigitalOcean server dashboard shows errors in the JavaScript console, and Wappalyzer causes some kind of disruption in the detection of these new monitoring capabilities and thus the ability for the page to show the new graphs. When the extension is disabled, the server dashboard functions as normal and shows the improved graphs.

The error from the console is as follows:
```
Uncaught (in promise)
message: "The message port closed before a response was received."
```

DIgitalOcean support has acknowledged this issue also with other customers:
![DO Support](https://i.imgur.com/O4QY8vD.png)

Screenshot of the new graphs which display when the extension is disabled:
![Proper graphs](https://i.imgur.com/vqLsZKH.png)

Screenshot of the basic graphs and console errors with extension enabled:
![Wrong graphs](https://i.imgur.com/P0SNa3l.png)

**Comment by AliasIO** [comment]
This should be fixed in the next update. It looks like `onMessage` expects a return value of `true` or a promise.

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/onMessage

https://github.com/AliasIO/Wappalyzer/commit/24c460f86fa6d88bdeb24f728e05405635cd996d#diff-810b4f4b3efe5b5bc0b99ade94beecccR220
