### ISSUE TITLE
Please add the new Google Analytics gtag.js version

### ISSUE THREAD

**Issue by litan1106** [AliasIO/Wappalyzer#2098]
Please add the new Google Analytics gtag.js version

<script async src="https://www.googletagmanager.com/gtag/js?id=GA_TRACKING_ID"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'GA_TRACKING_ID');
</script>

**Comment by jvoisin** [comment]
Is `Google Tag Manager` the same things than `Google Analytics`?

**Comment by litan1106** [comment]
They are different. gtagjs is the newer version of analytics.js

https://developers.google.com/analytics/devguides/collection/gtagjs/
https://developers.google.com/analytics/devguides/collection/analyticsjs/

**Comment by da2x** [comment]
No, they’re not the same – they’re separate products.

**Comment by litan1106** [comment]
We already have urchin.js, ga.js, analytics.js in one item. We should just add gtag.js to it as well. 

`"Google Analytics": {
      "cats": [
        10
      ],
      "js": {
        "gaGlobal": "",
        "GoogleAnalyticsObject": ""
      },
      "headers": {
        "Set-Cookie": "__utma"
      },
      "icon": "Google Analytics.svg",
      "script": "google-analytics\\.com\\/(?:ga|urchin|(analytics))\\.js\\;version:\\1?UA:",
      "website": "http://google.com/analytics"
    },`

**Comment by kyletaylored** [comment]
Google Tag Manager is being detected separately.
