### ISSUE TITLE
Chrome extension give elfinder debug: [error] [elfinder] Impossibile aprire "#"

### ISSUE THREAD

**Issue by LucaMiozzo** [AliasIO/Wappalyzer#2100]
When the Extension in enable, 
visiting some websites, they doesn't work.
In console appear the error:
elfinder debug: [error] [elfinder] Impossibile aprire "#"

**Comment by AlexByte** [comment]
Give example of site.

**Comment by gadcam** [comment]
Looks like an error of https://github.com/Studio-42/elFinder.
I can not reproduce on the demo website https://studio-42.github.io/elFinder/

**Comment by gadcam** [comment]
I think we can close this issue.
