### ISSUE TITLE
Show all application icons in the adress bar

### ISSUE THREAD

**Issue by maicol07** [AliasIO/Wappalyzer#2104]
Hi,s it possible to show all the icons of the apps in the adress bar instead of only one? (Firefox 58.0.2 x64)
Thanks

**Comment by gadcam** [comment]
It used to be possible but it is not anymore.
Now we have to use this API https://developer.mozilla.org/fr/Add-ons/WebExtensions/API/pageAction 
This a duplicate of/This is linked to #1426 & #1541 & #1601 
You can check #1601 to see why it is not possible to work around this limitation.

**Comment by maicol07** [comment]
Ok thanks for the info!
