### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by mxschmitt** [AliasIO/Wappalyzer#2132]
I can reproduce it by surfing on facebook.com and using Google Chrome.

![image](https://user-images.githubusercontent.com/17984549/36810519-374e76dc-1ccb-11e8-8cb3-77c66ba0a3a9.png)

**Comment by Lazza** [comment]
Indeed. Facebook also completely crashes the browser when using Wappalyzer on Firefox.

**Comment by gadcam** [comment]
Should be fixed by 74bb8fa.
@AliasIO when do you plan to push the next release ?

**Comment by gadcam** [comment]
@mxschmitt @Lazza  can you still reproduce this bug with Wappalyzer 5.4.11 ?
I pushed a fix for a lookalike issue which was merged in 27e1fa1.
If it did not fix I need a *reproducible* way to debug it : so at least a complete URL and maybe some preconditions.

**Comment by Lazza** [comment]
I will try to use it for a while.

**Comment by AliasIO** [comment]
Please let us know if this still happens and I'll reopen the issue.

**Comment by mxschmitt** [comment]
@AliasIO happends me again on Chrome 65 with Wappalyzer 5.4.11 while I was visiting facebook.

**Comment by gadcam** [comment]
@mxschmitt Facebook & Messenger can be pretty ressource consuming.
How do you know it is linked with Wappalyzer ?
Could try to extract some debug infos when it happens ?

**Comment by mxschmitt** [comment]
Not 100% sure, if it's the fault of Wappalyzer. But the Facebook tab was consuming over 3gig ram. It was so resource consuming, that i wasn't able to open the chrome internal task manager. When it will happen again, I try to extract more debug information. What do you need exactly? Or what can us help? (Maybe memory profile? idk)

**Comment by gadcam** [comment]
@mxschmitt The high RAM consumption is very probably not linked with Wappalyzer. (I never saw this at least)
High CPU consumption can be linked with Wappalyzer when there is a catastrophic backtracking case.

You can use this tutorial to debug an extension https://developer.chrome.com/apps/tut_debugging

In the end, I could reproduce the issue and I think it is quite easy to understand what is going on haha
 
![image](https://user-images.githubusercontent.com/1693643/38056409-a40adbea-32dc-11e8-8744-37fe20d0d6e8.png)

I push a fix in a few minutes.

PS: As you can see the heap consumption of Wappalyzer is maximum 18 Mo in this case
