### ISSUE TITLE
New category suggestion: Call Tracking

### ISSUE THREAD

**Issue by litan1106** [AliasIO/wappalyzer#2136]
I didn't find any call tracking related category.

- Google AdWords Call Tracking
- CallRail
- Marchex
- Convirza

**Comment by AliasIO** [comment]
Would you like to help add these? I'm in favour of adding it.

**Comment by jngnyc** [comment]
@litan1106 Is call-tracking simply tracking of calls? (forgive me if I'm misunderstanding what those services actually do)
If yes, it seems logical for call-tracking to fall under the "Analytics" umbrella category - https://github.com/AliasIO/Wappalyzer/blob/master/src/apps.json#L3703
