### ISSUE TITLE
Doesn't work on chrome extension pages.

### ISSUE THREAD

**Issue by jayaganthan** [AliasIO/Wappalyzer#2152]
Some chrome extensions(like momentum) uses web pages to display something or customize the addon.
Those sites starts with chrome-extension://

Example page url:
chrome-extension://laookkfknpbbblfpciffpaejjkokdgca/dashboard.html

It it not possible for wappalyzer to parse or analyze these type of pages?

**Comment by AliasIO** [comment]
Technically possible but it's disabled by design. Wappalyzer only requests permissions for `http` and `https` URLs. In most cases it's not useful to analyse `chrome` and `chrome-extension` pages.
