### ISSUE TITLE
Detect ProcessWire CMS

### ISSUE THREAD

**Issue by MichaLueth** [AliasIO/Wappalyzer#2157]
The [ProcessWire CMS](https://processwire.com/) is not detected by Wappalyzer.
ProcessWire can be detected by:
```
<meta name=generator content="ProcessWire">
```
or 
```
<meta name=generator content="ProcessWire x.y.z">
```

AFIK, typical paths generated by PW for e.g. asstets are `/site/templates/`.

**Comment by jvoisin** [comment]
The project [doesn't seem to be super popular]( https://github.com/processwire/processwire/ ) :/

**Comment by MichaLueth** [comment]
Yeah, I know :/ It's only a proposal, of course you can reject/close this issue.

**Comment by AliasIO** [comment]
Closing this one for now. Thank you.
