### ISSUE TITLE
Wappalyzer icon not showing under Firefox Developer Edition 60.0b2 (64-bit)

### ISSUE THREAD

**Issue by mrandreastoth** [AliasIO/Wappalyzer#2164]
As per closed issue https://github.com/AliasIO/Wappalyzer/issues/1649.

No extension icon under Firefox Developer Edition 60.0b2 (64-bit). The "browser.tabs.remote.force-disable" setting (as suggested in #1649) doesn't exist so cannot test that suggestion.

**Comment by gadcam** [comment]
Can you go to this page https://www.wappalyzer.com/ and copy paste the content of the console of Wappalyzer here ?
(To find the console you need to go to about:debugging and select debug on Wappalyzer)

**Comment by vip3rousmango** [comment]
I am also experiencing this but only when looking at sites using localhost; browsing other sites it appears in the Address bar as expected.

using: Win7 - FF:DE v60.0b5

**Comment by mrandreastoth** [comment]
It's working now and may always have been working but I cannot be sure it wasn't due to an update or that I was looking in the wrong area all the time - I expected the icon to show up as a standard extension icon and not as an address field icon. Perhaps this needs to be part of the instructions to avoid such confusions by others (or have the icon display some hint on first use)?

**Comment by AliasIO** [comment]
It's a 'page action' extension which means it lives in the address bar (in Firefox) and only activates when a page is loaded. It doesn't show an icon unless there are results to display. It should show up on the installation page that loads when the extension is installed.

**Comment by gadcam** [comment]
@AliasIO  What do you think about always displaying a shadowed version of the W. icon if nothing is detected ? It would avoid confusion.

**Comment by AliasIO** [comment]
Yeah, we can do that.

**Comment by AliasIO** [comment]
In the next update the default icon will be shown when no technologies are identified, with a message in the popup.
