### ISSUE TITLE
Webpack icon doesn't shown ?

### ISSUE THREAD

**Issue by shankhadevpadam** [AliasIO/Wappalyzer#2169]
I have developed my app using laravel 5.5 and vuejs 2.5.13 with webpack but i didn't seen the webpack icon in my wappalyzer. How to configure webpack in laravel 5.5 to get webpack icon in laravel.

**Comment by gadcam** [comment]
Can you provide a page URL to test it ?
FYI the paper used to detected webpack is here https://github.com/AliasIO/Wappalyzer/blob/master/src/apps.json#L12306

**Comment by shankhadevpadam** [comment]
https://booking.magicalnepal.com/

**Comment by trekshimalayas** [comment]
Treks Himalaya trekking company in Nepal offers wide verities of tours package activities such as trekking, helicopter tour, mountain flight, peak climbing, sightseeing tour, Tibet tour, Bhutan tour and many more on your demand please feel free to visit below without any hesitation. https://www.trekshimalaya.com
