### ISSUE TITLE
wrong source map hint in browser-polyfill.js

### ISSUE THREAD

**Issue by ErikKrause** [AliasIO/Wappalyzer#2184]
version 5.4.11 on Firefox 60.0b1 (64-Bit).
There is a wrong source map hint in /node_modules/webextension-polyfill/dist/browser-polyfill.js causing a warning message in the web console.

**Comment by gadcam** [comment]
Do you mean
```js
//# sourceMappingURL=browser-polyfill.js.map
```
need to be removed from the extension to avoid it ?

**Comment by ErikKrause** [comment]
Yes. That's it. Forgot to write: the error message only appears if you have source maps enabled in devtools settings.

**Comment by AliasIO** [comment]
I'll remove that, thanks.

**Comment by BartVB** [comment]
This still or again seems to be a problem with the current version (5.8.4) of Wappalizer.

I get this in my console:
```
Source map error: TypeError: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://ad03bd01-30fa-a64c-ba09-3a192f18b35a/node_modules/webextension-polyfill/dist/browser-polyfill.js
Source Map URL: browser-polyfill.js.map
```

**Comment by swrobel** [comment]
@AliasIO I'm still seeing this in 5.8.5
