### ISSUE TITLE
Seems to miscategorize some technologies

### ISSUE THREAD

**Issue by Thatkookooguy** [AliasIO/Wappalyzer#2189]
**Do you want to request a *feature*, a *new application detection* or report a *bug*?** bug

**Is your issue about WebExtension driver (Chrome & Firefox), the website, the NPM driver or the bookmarklet ?** web extention

**What is the current behavior ?** some technologies weren't recognized correctly

**If the current behavior is a bug, please provide the steps to reproduce and if possible a demo of the problem.**
1. go to https://achievibit.kibibit.io/
1. check the tool

**What is the expected behavior ?**
the site is served on `Heroku`, using a `Node.js` with `Express.js` as the server technology
Maybe the library `materialize CSS` use `Erlang` or `Hammer.js`, but `cowboy` is defently not the server side technology.
maybe it's something that is added because of `Heroku`? I would still expect to at least see `express.js` written somewhere

**Which versions of Wappalyzer, and which browser / OS are affected by this issue ? Did this work in previous versions ?**
didn't check previous versions.

chrome version: `Version 65.0.3325.162 (Official Build) (64-bit)`
Wappalyzer version: `5.4.11`

**Comment by gadcam** [comment]
I do not think we have <code>Heroku</code> detection as it is hard to find a pattern for it.
For <code>express.js</code> we have [a pattern](https://github.com/AliasIO/Wappalyzer/blob/master/src/apps.json#L3001) <code>"X-Powered-By": "^Express$"</code> which is not present in this website.
I think it is right to say that there is <code>cowboy</code> somewhere in the process to run this website cf https://github.com/heroku/cowboy (which implies <code>Erlang</code>).

We need the server to leak something to detect a technology but I could not find anything relevant at your URL.

This matter has already been discussed in #849, so if no new elements are raised I think we should close this issue as it is a technical limitation.
