### ISSUE TITLE
Gitlab false positive on Github

### ISSUE THREAD

**Issue by MartinMuzatko** [AliasIO/Wappalyzer#2190]
**Do you want to request a *feature*, a *new application detection* or report a *bug*?**

Bug

**Is your issue about WebExtension driver (Chrome & Firefox), the website, the NPM driver or the bookmarklet ?**

Extension for Chrome

**What is the current behavior ?**

Gitlab is identified on Github, because it is part of the URL.

![image](https://user-images.githubusercontent.com/2950505/37661878-0c0d1b64-2c56-11e8-9ec7-120dc17a31e7.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a demo of the problem.**

Visit https://github.com/gitlabhq/gitlabhq

**What is the expected behavior ?**

Identify Gitlab not via URL only.

**Which versions of Wappalyzer, and which browser / OS are affected by this issue ? Did this work in previous versions ?**

**Comment by gadcam** [comment]
The URL is not taken into account here to do detection.
If you want, you can check the patterns here  [apps.json#L3555](https://github.com/AliasIO/Wappalyzer/blob/master/src/apps.json#L3555) and look at [the doc](https://www.wappalyzer.com/docs/specification) to interpret them.

Looks like the meta description pattern is at work here and matching against this
```html
<meta property="og:description" content="gitlabhq - GitLab CE | Please open new issues in our issue tracker on GitLab.com" />
```
and the pattern would match any description starting by Gitlab...
So I offer to remove it in #2191.

**Comment by MartinMuzatko** [comment]
Thanks for the quick reply. Makes sense to me :)
