### ISSUE TITLE
Soundmanager version detection isn't working

### ISSUE THREAD

**Issue by jvoisin** [AliasIO/Wappalyzer#2194]
Apparently, the version detection of SoundManager isn't working, on Chrome on Linux with the latest ( 5.4.11) Wappalyzer version. This can be reproduced [here](http://www.larousse.fr/dictionnaires/francais/photique/60400), where SoundManager is detected, but not its version.

![screenshot](http://i.imgur.com/WyD2wWO.png)

**Comment by gadcam** [comment]
I do not understand the detection should be working : 

![screenshot](https://user-images.githubusercontent.com/1693643/37713671-e73eb294-2d17-11e8-8603-39881a49553f.png)

And in the popup there is no clue of any version detection. (checked by reading the source of it)
Maybe the variable is initialized later ?
(Firefox)

**Comment by AliasIO** [comment]
Appears to be working now.
