### ISSUE TITLE
Non-Secure Origins

### ISSUE THREAD

**Issue by irfanfadilah** [AliasIO/Wappalyzer#2199]
Open Developer Tools > Reload Page > Security Tab

chrome-extension://gppongmhjkpfnbhagpmjfkannfbllamg - Your connection to this origin is not secure.

What is this "inject.js" thing? Is this normal? Can we fix this to pass the security warning?

**Comment by gadcam** [comment]
There is nothing scary when you have the explanation ;)

<code>inject.js</code> is needed to make <code>js</code> patterns work. (You can check the source code if you are interested in how it works https://github.com/AliasIO/Wappalyzer/blob/master/src/drivers/webextension/js/inject.js)

The security warning looks like a CORS problem: the website is not waiting anything from any extension so there is a warning.
Maybe we need to add a rule in the manifest to avoid it.
 
Here are 3 linked bug in other addons
https://github.com/bufferapp/buffer-chrome/issues/26
https://github.com/MetaMask/metamask-extension/issues/977
https://github.com/facebook/react-devtools/issues/236

**Comment by AliasIO** [comment]
Is the issue just that scripts loaded from the 'chrome-extension' are marked as not secure? Because that would be expected behaviour. It shouldn't cause console or SSL errors on the page.

**Comment by gadcam** [comment]
Yes, I think you are right and that you can close the issue.
