### ISSUE TITLE
WRONG PHP VERSION  WITH NEWEST VERSION 5.4.12

### ISSUE THREAD

**Issue by rinodung** [AliasIO/Wappalyzer#2202]
I have just tested newest version 5.4.12 with url: http://mmt.uit.edu.vn(NodeJS NPM driver) and get wrong information about php version like this:
![wappalyzer](https://user-images.githubusercontent.com/7805715/37946460-a45d796e-31af-11e8-80e5-a1d600f36cb9.png)
Please give me any commit with cause this issue as soon as possible, thank!

**Comment by jvoisin** [comment]
I can't reproduce with the browser extension, so it seems to be a NodeJS driver related issue.

**Comment by gadcam** [comment]
The detection here is made with the header pattern on X-Powered-By.
So the culprit line could in #2122 or #2129

**Comment by AliasIO** [comment]
This is currently working correctly.
