### ISSUE TITLE
apps.json  PHP misinformation

### ISSUE THREAD

**Issue by mapengfei2016** [AliasIO/Wappalyzer#2206]
I see the https://github.com/AliasIO/Wappalyzer/blob/master/src/apps.json
in line 7247 the rule       "url": "\\.php(?:$|\\?)",
Deployed to the build environment and found to generate a large number of false positives， like this url
https://www.google.com/a.php
so please remove it，Thanks

**Comment by gadcam** [comment]
Can you please share a real world URL causing this sort of problems ?

**Comment by mapengfei2016** [comment]
![image](https://user-images.githubusercontent.com/20885056/38284422-b914d6ec-37ed-11e8-84ff-9a3a0f69a552.png)

https://www.google.com/a.php this url
