### ISSUE TITLE
Load Balancer Category

### ISSUE THREAD

**Issue by mtbike61384** [AliasIO/Wappalyzer#2207]
Wanted to open up a discussion about creating a web load balancer category.

**Comment by AliasIO** [comment]
Do you have a few candidate technologies for the category?

**Comment by mtbike61384** [comment]
A handful of the big ones that come to mind are Incapsula, Amazon ELB, F5 Big IP, Dyn, and Citrix NetScaler.

**Comment by mtbike61384** [comment]
I would if I knew how. I don't have much programming experience especially in Java and would probably screw something up : )

**Comment by AliasIO** [comment]
Would you be able to provide examples of websites using those load balancers? There may not be a way to externally identify them.

**Comment by mtbike61384** [comment]
wix.com uses Incapsula, 34.206.197.37 for Amazon ELB, xoom.com for F5 BigIP, 192.149.219.70 for Citrix NetScaler. So where you will usually see these technologies is in the 301 redirect page.

**Comment by mxschmitt** [comment]
| Loadbalacer | How can I detect it? |
| ------------- | ---------------------- |
| Incapsula | `X-CDN` Header is equal to `Incapsula` |
| Amazon ELB |  |
| F5 BigIP |  |
| Citrix NetScaler |  |

For the others I have no clue how we can identify them.

**Comment by assetgrower** [comment]
here's some good signatures for WAFs https://github.com/EnableSecurity/wafw00f/tree/master/wafw00f/plugins
