### ISSUE TITLE
Underscore.js version detection isn't working

### ISSUE THREAD

**Issue by jvoisin** [AliasIO/Wappalyzer#2209]
Apparently, the version detection of Underscore.js isn't working, on Chrome on Linux with the latest ( 5.4.11) Wappalyzer version. This can be reproduced [here](https://www.fastly.com/), where Underscore.js is detected, but not its version. Could this be similar to #2194?

![screenshot]( http://i.imgur.com/KSYJPwa.png )

**Comment by nacimgoura** [comment]
Same issue with the [official website](http://underscorejs.org)

**Comment by AliasIO** [comment]
Fixed with some trickery in a0cc689e1dff9a96baf3d0488433b89d320fb062. Underscore.js and Lodash were using the same pattern and were always detected together.
