### ISSUE TITLE
False positive for Magento

### ISSUE THREAD

**Issue by azdanov** [AliasIO/Wappalyzer#2212]
A fresh install of [yii2](https://github.com/yiisoft/yii2-app-advanced) yields mixed results for Magento.

<img width="466" alt="screen shot 2018-04-06 at 14 35 58" src="https://user-images.githubusercontent.com/6123841/38419123-dda43082-39a7-11e8-84fa-c3d28c5e4a8c.png">

**Comment by gadcam** [comment]
Can you share the URL of the installation ?
Maybe we can do better, however it is not really a false-positive as it is not 100% sure.

**Comment by azdanov** [comment]
I was testing on my local machine. I could try putting it online if it helps.

**Comment by kitsaravana** [comment]
example site : https://recreativ.ru/

**Comment by gadcam** [comment]
These detections are caused by the last two patterns

```js
"script": [
        "js/mage",
        "skin/frontend/(?:default|(enterprise))\\;version:\\1?Enterprise:Community",
        "static/_requirejs\\;confidence:50\\;version:2",
        "static/frontend\\;confidence:20\\;version:2"
],
```
In https://recreativ.ru it triggers on
```html
<script src="//recreativ.ru/static/frontend/js/script.js?seed=1522238110"></script>
```

As I have no knowledge about Magento I can not even tell if there is magento or not behind this website but I think it would be good to write a better pattern or to remove it if we do not have a way to do better.

**Comment by jvoisin** [comment]
[reactiv.ru](https://recreativ.ru/) isn't a Magento.

I think that we can trash the last pattern, since it's a pretty common one. I don't know about `static/_requirejs` though.
