### ISSUE TITLE
need some option for deeply analyzing html content

### ISSUE THREAD

**Issue by hbakhtiyor** [AliasIO/Wappalyzer#2218]
the current is [hard coded](https://github.com/AliasIO/Wappalyzer/blob/master/src/drivers/npm/driver.js#L221), and can't recognize some apps, need some option or optimization algorithm for recognizing it. 

```
      if ( html.length > 50000 ) {
        html = html.substring(0, 25000) + html.substring(html.length - 25000, html.length);
      }
```

**Comment by gadcam** [comment]
Duplicate of #1614.

**Comment by AliasIO** [comment]
I'm adding `htmlMaxCols` and `htmlMaxRows` options to configure this in the next version.
