### ISSUE TITLE
Why does the Wappaluser not analyze headers?

### ISSUE THREAD

**Issue by spinzhar** [AliasIO/Wappalyzer#2220]
I'm trying to analyze the site https://www.coursera.org/
in the result I get : 
[wappalyzer debug] [driver] [timer] fetch; url: https://www.coursera.org/; depth: 1; delay: NaNms; lapsed: 0s / 0s
[wappalyzer debug] [driver] [timer] browser.visit start; url: https://www.coursera.org/; lapsed: 0s / 0s
[wappalyzer debug] [driver] [timer] browser.visit end; url: https://www.coursera.org/; lapsed: 9.97s / 9.97s
[wappalyzer debug] [core] 5 apps detected: Facebook, Google Analytics, Google Tag Manager, React, webpack on https://www.coursera.org/
{ urls: [ 'https://www.coursera.org/' ],
  applications:
   [ { name: 'Facebook',
       confidence: '100',
       version: '',
       icon: 'Facebook.svg',
       website: 'http://facebook.com',
       categories: [Array] },
     { name: 'Google Analytics',
       confidence: '100',
       icon: 'Google Analytics.svg',
       website: 'http://google.com/analytics',
       categories: [Array] },
     { name: 'Google Tag Manager',
       confidence: '100',
       version: '',
       icon: 'Google Tag Manager.png',
       website: 'http://www.google.com/tagmanager',
       categories: [Array] },
     { name: 'React',
       confidence: '100',
       version: '',
       icon: 'React.png',
       website: 'http://facebook.github.io/react',
       categories: [Array] },
     { name: 'webpack',
       confidence: '100',
       version: '',
       icon: 'webpack.svg',
       website: 'http://webpack.github.io',
       categories: [Array] } ],
  meta: { language: 'en' } }

5 apps detected
Why not found Express and other app?

**Comment by jvoisin** [comment]
What version of wappalyzer are your using? I'm guessing that you're using the nodejs driver?

**Comment by spinzhar** [comment]
updated version wappalyzer to 5.4.13 and everything worked
Thank you.

**Comment by jvoisin** [comment]
Do feel free to close this issue then :)
