### ISSUE TITLE
Google use CMS Drupal

### ISSUE THREAD

**Issue by GuiguiWeb** [AliasIO/Wappalyzer#2221]
Hello,

When i am loading google.fr, Wappalyzer detect google used the CMS Drupal . 

<img width="945" alt="capture d ecran 2018-04-10 a 12 35 45" src="https://user-images.githubusercontent.com/26392178/38552232-c8dbe96c-3cbb-11e8-9d35-c6ecc9287dc7.png">

Best regards,
Guillaume

**Comment by GuiguiWeb** [comment]
Nb: I use version 5.4.11

**Comment by AliasIO** [comment]
Closing this as we're unable to reproduce it. Please feel free to revive this issue if you see it happen again.
