### ISSUE TITLE
display version jquery ui don't work

### ISSUE THREAD

**Issue by nacimgoura** [AliasIO/Wappalyzer#2227]
Hello,
When I go to this [site](https://pouletarmy.arnaudlab.net/about).
jQueryUI doesn't display its version number correctly, it displays a hash instead.

![bugjqueryui](https://user-images.githubusercontent.com/9990521/38608545-f8437d6c-3d7b-11e8-8a85-0cfe7bc86cdb.png)

**Comment by gadcam** [comment]
Sadly for you, the behavior of the addon is correct : the content of <code>jQuery.ui.version</code> is <code>c0ab71056b936627e8a7821f03c044aec6280a40</code>.
We have to trust the website to do detection there is not much to do about it :/
However in this case the detection seem 100% correct cf https://searchcode.com/codesearch/view/64321654/

**Comment by nacimgoura** [comment]
Thanks, I don't understand because when I go to this [site](https://www.freepik.com/) it displays the correct version number.

**Comment by jvoisin** [comment]
It __is__ working correctly. If you check the version of JQueryUI on the [first website]( https://pouletarmy.arnaudlab.net/about), you'll see that it's `c0ab71056b936627e8a7821f03c044aec6280a40`. You can check this by typing `jQuery.ui.version` in the console of your browser.

**Comment by nacimgoura** [comment]
Thanks, I understand!
