### ISSUE TITLE
What is the purpose of the iframe.js file?

### ISSUE THREAD

**Issue by jvoisin** [AliasIO/Wappalyzer#2233]
Hello,

I was wondering the point of the [iframe.js]( https://github.com/AliasIO/Wappalyzer/blob/master/src/drivers/webextension/js/iframe.js ) file. It seems to be used to detect some ads, but the info isn't displayed anywhere, and only used to transmit back to the telemetry  on https://ad.wappalyzer.com/log/wp/ 
This behaviour isn't documented anywhere :/

**Comment by AliasIO** [comment]
Right, it's to track ads across the web. It can be turned off in the settings. It's not currently being used to display advertising networks in the popup but I'm hoping to tie it back in at some point.

**Comment by jvoisin** [comment]
What about merging it directly into `app.json` then?
