### ISSUE TITLE
Twitter Emoji should not be in the JavaScript Graphics Category

### ISSUE THREAD

**Issue by chesucr** [AliasIO/Wappalyzer#2241]
I was checking the most used Graphic Technologies and I have realized that Twitter Emoji is the most used. But I think that library shouldn´t be there. I would only keep the plotting libraries in that category such as D3 and HighCharts. 

![image](https://user-images.githubusercontent.com/11211829/38860355-4ec48e2a-4230-11e8-932a-aa3bf41c562c.png)

**Comment by gadcam** [comment]
I agree, I offer that we move it to miscellaneous categorie as I did not find any good categorie for it.
