### ISSUE TITLE
Wix Detection changed

### ISSUE THREAD

**Issue by tobybellwood** [AliasIO/Wappalyzer#2245]
It looks like Wix sites have headers that differ from the ones in apps.json.

The headers present now appear to be:
```
X-Wix-Request-Id: 1524033694.91253411397319655
X-Wix-Server-Artifact-Id: wix-answers-war
```
instead of 
`"X-Wix-Renderer-Server": ""`

**Comment by jvoisin** [comment]
Maybe we should simply use `X-Wix-.+` .

**Comment by AliasIO** [comment]
Thanks!

**Comment by tobybellwood** [comment]
Perfect - love your work @jvoisin and @AliasIO!!
