### ISSUE TITLE
Can't extract technologies of https://www.economist.com

### ISSUE THREAD

**Issue by tracykennedy** [AliasIO/Wappalyzer#2251]
Using the npm driver I've been finding a few websites for which I cannot extact technologies for. https://www.economist.com is the most recent example I found. It goes on for a good while and then it times out.

**Comment by AliasIO** [comment]
Thanks for the example. I found that Zombie.js hanged when evaluating the script loaded from `//js-sec.indexww.com/ht/p/184475-137819213763014.js`. I managed to get around it with a patch, which will be applied in the next version.

https://github.com/AliasIO/Wappalyzer/blob/master/patches/zombie-vm-timeout.patch
