### ISSUE TITLE
Detection of Digital User Experience

### ISSUE THREAD

**Issue by LeslieMurphy** [AliasIO/Wappalyzer#2258]
**What is the current behavior ?**

Customer experience (CX) products are put into inappropriate buckets.

ClickTale in Documentation Tools 
Crazy Egg in Ecommerce
Optimizely in JS Graphics
HotJar in Font Scripts
Visual Website Optimizer and VisualPath in Maps along with Google Maps

**What is the expected behavior ?**

All of these should be in a single category such as "Digital User Experience"

ClickTale
Crazy Egg
HotJar
Optimizely
Inspectlet
FullStory
QuantumMetric
MouseFlow
CoreMetrics (IBM)
Lucky Orange
m-pathy UX-Insight
Userzoom
eTracker
Decibel Insight

**Comment by jvoisin** [comment]
I fail to understand the term "Digital User Experience", and the [wikipedia article]( https://en.wikipedia.org/wiki/Customer_experience ) about "customer experience" is full of `citation needed`. Can you please elaborate?

**Comment by kyletaylored** [comment]
These were all redirected under `Analytics`.
