### ISSUE TITLE
Headers processing isn't working in the web extension

### ISSUE THREAD

**Issue by jvoisin** [AliasIO/Wappalyzer#2264]
I'm using the latest (`5.4.14`) Wappalyzer version, and it doesn't detect several technologies via headers on http://share.ez.no/ : 

![screenshot_2018-04-24_15-04-58](https://user-images.githubusercontent.com/325724/39188810-fca80bf2-47d0-11e8-98f0-22246e826756.png)

**Comment by AliasIO** [comment]
Fixed in 3402b850ed988d527c43d9ff9ff230766a9c7ce4.
