### ISSUE TITLE
use outerHTML instead of innerHTML for body

### ISSUE THREAD

**Issue by pmeenan** [AliasIO/Wappalyzer#2271]
https://github.com/AliasIO/Wappalyzer/blob/dc0031e917d9c3e45273989adb99e4908aa9b6bc/src/drivers/bookmarklet/driver.js#L37

innerHTML doesn't include the <html> tag and will miss the "Accelerated Mobile Pages" detection.  Using outerHTML instead fixes the issue (and should be supported across virtually all browsers).

**Comment by gadcam** [comment]
See #2273 for a fix.
Even <code>outerHTML</code> is not enough in fact cf #615.

**Comment by AliasIO** [comment]
AMP detection is working now, thank you.
