### ISSUE TITLE
Timeout from Lambda when using MaxWait

### ISSUE THREAD

**Issue by CBox** [AliasIO/Wappalyzer#2280]
Hey,

I'm using the NPM driver and it's working great on my local machine but wheb upload it to Lambda I always get timeout.

I've timeout of the Lambda to 10s and used max-wait: 5000. It's like the timeout not working on Lambda for some reason.

`const options = {
    maxWait: 5000,
    debug: true,
    maxDepth: 1,
    maxUrls: 1
  };

  const wappalyzer = new Wappalyzer(url, options);

  wappalyzer.analyze()
  .then(json => {
      return callback(null, responder(200, json));
  })
  .catch(error => {
    return callback(null, responder(200, error));
  });`

What I get from Lambda:
[wappalyzer debug] [driver] [timer] fetch; url: https://www.awwwards.com/; depth: 1; delay: 0ms; lapsed: 0s / 0.04s
[wappalyzer debug] [driver] [timer] browser.visit start; url: https://www.awwwards.com/; lapsed: 0.06s / 0.1s
[wappalyzer debug] [driver] [timer] browser.visit end; url: https://www.awwwards.com/; lapsed: 9.22s / 9.32s

Any idea?

**Comment by AliasIO** [comment]
Try increasing the available memory. This will give the function more CPU to play with as well, which should speed things up.

**Comment by CBox** [comment]
Yes but there is no chance to tell the script and after Xms to stop and return whatever being found? this is not the maxWait: 5000 option?
