### ISSUE TITLE
Icons transparency and contrast with dark browsers themes

### ISSUE THREAD

**Issue by meduzen** [AliasIO/Wappalyzer#2286]
Hi folks! This is more an **enhancement request** than a bug.

Depending on the browser theme, some app icons may be unreadable because of a lack of contrast. That’s at least the case on Firefox with the default dark theme (the browser ships with two themes: one dark and one light).

Let’s take the [Wordpress SVG](https://github.com/AliasIO/Wappalyzer/blob/master/src/icons/WordPress.svg):
<img width="154" alt="wordpress svg" src="https://user-images.githubusercontent.com/9340937/39664938-0e2cceb2-508c-11e8-9d08-4092faba9e6b.png">

Because the inner part is transparent, here’s how it displays on Firefox Nightly (MacOS):
![wappalyzer-wp](https://user-images.githubusercontent.com/9340937/39664960-71ba795c-508c-11e8-8a3d-29c31b5198f9.gif)

This readability issue can be avoided by filling the inner part of the icons with their _native_ colors (for Wordpress, it’s white).

I know it’s not an easy choice nor an easy mission, because it also concerns icons where an inner fill is impossible (examples below: Ruby and Laravel):
<img width="98" alt="Ruby icon on dark theme" src="https://user-images.githubusercontent.com/9340937/39665027-3bec3198-508d-11e8-871a-ba909224d350.png"> <img width="86" alt="Laravel icon on dark theme" src="https://user-images.githubusercontent.com/9340937/39665029-4d7672e8-508d-11e8-9b11-0998110d1c8e.png">
In this case, a white thin outline may help, like the one on the HeadJS icon:
<img width="59" alt="Head JS icon" src="https://user-images.githubusercontent.com/9340937/39665121-3a44a2f6-508f-11e8-840d-3a96f23d1edb.png">
The outline is visible on a dark theme:
<img width="94" alt="Head JS icon on dark theme" src="https://user-images.githubusercontent.com/9340937/39665124-53a03de6-508f-11e8-9d0b-ea0b23cf18fd.png">

Of course, you should not have to deal with annoying themes behaviour, even when they comes by default, but some icons could definitely benefit of some inner color fill to provide better readability.

**Comment by jsomedon** [comment]
@AliasIO I am having this issue as well. Setting background color, or any other ugly hack that could make icons more visible in dark theme would be really nice for dark theme users like me..
