### ISSUE TITLE
Misinterperating Variables as Frameworks

### ISSUE THREAD

**Issue by johnpyp** [AliasIO/Wappalyzer#2289]
It seems that Wappalyzer is detecting frameworks that don't exist. Causation, to me, seems to be because global variables are exposed. I noticed this on the new Gmail, where Wappalyzer detected Yii framework and Deployd backend. Both of these seemed odd, because Google has its own frontend and backend frameworks. Looking into it, deployed normally exposes a dpd window variable, and sure enough gmail did as well, except it was just a random minified variable. Same thing with Yii.

Chrome 66 Ubuntu 18.04

**Comment by ebinmanuval** [comment]
Same behavior in firefox 60.0 Windows 10 <br>
![wappalyzer](https://user-images.githubusercontent.com/7802869/39963937-886073c4-568a-11e8-8bb0-b4bb19c4ef11.jpg)
