### ISSUE TITLE
[NodeJS] Analyzing TechCrunch completes though does not return

### ISSUE THREAD

**Issue by jcmdln** [AliasIO/Wappalyzer#2291]
**Do you want to request a *feature*, a *new application detection* or report a *bug*?**
This is a Bug report.

**Is your issue about WebExtension driver (Chrome & Firefox), the website, the NPM driver or the bookmarklet ?**
This is in regards to the NodeJS package for Wappalyzer, v5.4.15: https://www.npmjs.com/package/wappalyzer

**What is the current behavior ?**
When using the example code at https://www.npmjs.com/package/wappalyzer#run-from-a-script though removing the process.exit(0) within `.then`, the Promise does print data to stdout though the promise does not appear to complete. This issue has only impacted TechCrunch during my testing, and it f

**If the current behavior is a bug, please provide the steps to reproduce and if possible a demo of the problem.**

0. Create a new folder, `npm init -y`, and `npm install wappalyzer`
1. Save the following code as `main.js`:
```
const Wappalyzer = require('wappalyzer')

const options = {
  debug: true,
  delay: 500,
  maxDepth: 3,
  maxUrls: 10,
  maxWait: 5000,
  recursive: true,
  userAgent: 'Wappalyzer',
  htmlMaxCols: 2000,
  htmlMaxRows: 2000,
}
 
const wappalyzer = new Wappalyzer("https://techcrunch.com", options)

wappalyzer.analyze()
  .then(json => {
    process.stdout.write(JSON.stringify(json, null, 2) + '\n')

    // Don't kill the entire script like the original example does
    //process.exit(0)
  })
  .catch(error => {
    process.stderr.write(error + '\n') 
    process.exit(1)
})
```
2. Run it with `node main.js`
3. JSON data prints to console
4. Console never returns, even after waiting upwards of 10 minutes. Running `top`, `htop`, or `ps` will show the process is still active despite the data being retrieved.

**What is the expected behavior ?**
After fulfilling the promise and receiving the return data, the promise should complete. When debugging is `true`, long-running processes could report they are still active to make debugging these situations a bit easier.

Something I must elaborate on is my purpose for submitting this bug. I cannot use `process.exit(0)` once the promise returns `json` as my intention is to use Wappalyzer to iterate over a list of domains as opposed to performing a one-off lookup. It is certainly possible that I am misunderstanding something about Promises rather than this being an issue with Wappalyzer, though other domains I've tested against do resolve and complete as expected.

**Which versions of Wappalyzer, and which browser / OS are affected by this issue ? Did this work in previous versions ?**

Fedora 28
NodeJS v8.11.0
Wappalyzer v5.4.15

I have not tested any other versions of the above.

**Comment by AliasIO** [comment]
You need to exit the script. If you want to run Wappalyzer over multiple URLs, you can use `Promise.all`:

```javascript
const promises = [
  new Wappalyzer('https://techcrunch.com', options).analyze(),
  new Wappalyzer('https://example.com', options).analyze(),
];

Promise.all(promises)
  .then(results => {
    process.stdout.write(JSON.stringify(results, null, 2) + '\n');

    process.exit(0);
  })
  .catch(error => {
    process.stderr.write(error + '\n')

    process.exit(1);
  });
```

**Comment by jcmdln** [comment]
Ah, thank you for the clarification! This is exactly what I needed :)
