### ISSUE TITLE
NPM driver hangs forever after calling browser.visit(), force quit does nothing

### ISSUE THREAD

**Issue by avasilkov** [AliasIO/Wappalyzer#2292]
BUG

npm driver  @ current master

Wappalyzer hangs forever and uses 100% cpu, force quit feature in index.js does nothing.
Expected behavior: force quit quits the program

Steps to reproduce:
node index.js http://www.wine.com.br --userAgent='Mozilla/5.0 (Windows NT 6.1; rv:52.0) Gecko/20100101 Firefox/52.0' --debug=1

calling without useragent goes smooth

I think the problem is in Zombie.js but since Wappalyzer relies on it, has force quit feature that has to work and even has one patch already, I'm posting it here. Is there a way to fix it from inside Wappalyzer to avoid other such unforseen things?

Log with browser.debug() called before browser.visit() call.
`
/usr/bin/node index.js http://www.wine.com.br --userAgent=Mozilla\/5.0\ \(Windows\ NT\ 6.1\;\ rv:52.0\)\ Gecko\/20100101\ Firefox\/52.0 --debug=1
[wappalyzer debug] [driver] [timer] fetch; url: http://www.wine.com.br/; depth: 1; delay: 0ms; lapsed: 0s / 0s
[wappalyzer debug] [driver] [timer] browser.visit start; url: http://www.wine.com.br/; lapsed: 0s / 0s
  zombie Opened window http://www.wine.com.br/  +0ms
  zombie GET http://www.wine.com.br/ => 301 https://www.wine.com.br/ +58ms
  zombie GET https://www.wine.com.br/ => 200 +600ms
  zombie Loaded document https://www.wine.com.br/ +641ms
  zombie GET https://www.wine.com.br/dwr/interface/customerAjaxController.js?20180515 => 200 +81ms
  zombie GET https://www.wine.com.br/dwr/interface/autocompleteSearchResultAjaxController.js?20180515 => 200 +0ms
  zombie GET https://www.wine.com.br/dwr/interface/productSuggestionAjaxController.js?20180515 => 200 +1ms
  zombie GET https://www.wine.com.br/dwr/util.js?20180515 => 200 +0ms
  zombie GET https://www.wine.com.br/dwr/interface/shoppingCartAjaxController.js?20180515 => 200 +1ms
  zombie GET https://www.wine.com.br/dwr/interface/searchSuggestionAjaxController.js?20180515 => 200 +2ms
  zombie GET https://www.wine.com.br/dwr/engine.js?20180515 => 200 +1ms
  zombie GET https://www.wine.com.br/dwr/interface/recommendationAjaxController.js?20180515 => 200 +1ms
  zombie GET https://www.wine.com.br/dwr/interface/clubePrimeAjaxController.js?20180515 => 200 +1ms
  zombie GET https://www.wine.com.br/dwr/interface/productAjaxController.js?20180515 => 200 +0ms
  zombie GET https://www.wine.com.br/dwr/interface/listaAjaxController.js?20180515 => 200 +2ms
  zombie GET https://www.wine.com.br/template-resources/068a50259fc/build/commons.bundle.js?20180515 => 200 +0ms
  zombie GET https://www.wine.com.br/template-resources/068a50259fc/build/home.bundle.js?20180515 => 200 +2ms
  zombie GET https://www.wine.com.br/dwr/interface/hotsiteAjaxController.js?20180515 => 200 +2ms
  zombie GET https://www.googletagmanager.com/gtag/js?id=UA-5733415-1 => 200 +171ms
  zombie GET https://www.googletagmanager.com/gtm.js?id=GTM-5D87B2D => 200 +15ms
  zombie GET https://www.google.com/recaptcha/api.js?onload=vueRecaptchaApiLoaded&render=explicit&hl=pt-BR => 200 +23ms
  zombie Fired setTimeout after 0ms delay +77ms
  zombie GET https://www.google-analytics.com/analytics.js => 200 +198ms
  zombie GET https://imgs.ebit.com.br/ebitBR/selo-ebit/js/getSelo.js?827 => 200 +481ms
  zombie XHR readystatechange https://www.wine.com.br/dwr/call/plaincall/searchSuggestionAjaxController.listAllSearchSuggestions.dwr +120ms
  zombie XHR loadstart https://www.wine.com.br/dwr/call/plaincall/searchSuggestionAjaxController.listAllSearchSuggestions.dwr +1ms
  zombie XHR readystatechange https://www.wine.com.br/dwr/call/plaincall/autocompleteSearchResultAjaxController.findProducts.dwr +18ms
  zombie XHR loadstart https://www.wine.com.br/dwr/call/plaincall/autocompleteSearchResultAjaxController.findProducts.dwr +0ms
  zombie XHR readystatechange https://www.wine.com.br/dwr/call/plaincall/customerAjaxController.getLoggedCustomer.dwr +7ms
  zombie XHR loadstart https://www.wine.com.br/dwr/call/plaincall/customerAjaxController.getLoggedCustomer.dwr +0ms
  zombie XHR readystatechange https://www.wine.com.br/dwr/call/plaincall/shoppingCartAjaxController.getShoppingCart.dwr +9ms
  zombie XHR loadstart https://www.wine.com.br/dwr/call/plaincall/shoppingCartAjaxController.getShoppingCart.dwr +1ms
  zombie XHR readystatechange https://www.wine.com.br/dwr/call/plaincall/productAjaxController.getProductHotsiteViewBean.dwr +38ms
  zombie XHR loadstart https://www.wine.com.br/dwr/call/plaincall/productAjaxController.getProductHotsiteViewBean.dwr +0ms
  zombie XHR readystatechange https://www.wine.com.br/dwr/call/plaincall/productAjaxController.getProductHotsiteViewBean.dwr +3ms
  zombie XHR loadstart https://www.wine.com.br/dwr/call/plaincall/productAjaxController.getProductHotsiteViewBean.dwr +0ms
  zombie XHR readystatechange https://www.wine.com.br/dwr/call/plaincall/productAjaxController.getProductHotsiteViewBean.dwr +0ms
  zombie XHR loadstart https://www.wine.com.br/dwr/call/plaincall/productAjaxController.getProductHotsiteViewBean.dwr +1ms
  zombie XHR readystatechange https://www.wine.com.br/dwr/call/plaincall/recommendationAjaxController.listRecommendations.dwr +4ms
  zombie XHR loadstart https://www.wine.com.br/dwr/call/plaincall/recommendationAjaxController.listRecommendations.dwr +0ms
  zombie XHR readystatechange https://www.wine.com.br/dwr/call/plaincall/hotsiteAjaxController.getProductsByHotsiteUrl.dwr +9ms
  zombie XHR loadstart https://www.wine.com.br/dwr/call/plaincall/hotsiteAjaxController.getProductsByHotsiteUrl.dwr +0ms
  zombie Fired setTimeout after 0ms delay +92ms
  zombie Opened window about:blank  +31ms
  zombie Opened window https://8177467.fls.doubleclick.net/activityi;src=8177467;type=invmedia;cat=uu9tcwvf;ord=4833216493067;gtm=G4r;u2=%2F;%7Eoref=https%3A%2F%2Fwww.wine.com.br%2F?  +4ms
  zombie Fired setTimeout after 0ms delay +50ms
  zombie Fired setTimeout after 0ms delay +10ms
  zombie Fired setTimeout after 0ms delay +0ms
  zombie Fired setTimeout after 0ms delay +0ms
  zombie Fired setTimeout after 50ms delay +0ms
  zombie Fired setTimeout after 50ms delay +1ms
  zombie Fired setTimeout after 100ms delay +0ms
  zombie Fired setTimeout after 0ms delay +1ms
  zombie Fired setTimeout after 0ms delay +0ms
  zombie Fired setTimeout after 0ms delay +0ms
  zombie Fired setTimeout after 0ms delay +0ms
  zombie Fired setTimeout after 0ms delay +0ms
  zombie Fired setTimeout after 0ms delay +0ms
  zombie Fired setTimeout after 0ms delay +0ms
  zombie Fired setTimeout after 0ms delay +0ms
  zombie Fired setTimeout after 0ms delay +0ms
  zombie Fired setTimeout after 0ms delay +0ms
  zombie Fired setTimeout after 0ms delay +1ms
  zombie Fired setTimeout after 0ms delay +0ms
  zombie Fired setTimeout after 0ms delay +0ms
  zombie Fired setTimeout after 0ms delay +0ms
  zombie Fired setTimeout after 0ms delay +0ms
  zombie Fired setTimeout after 0ms delay +0ms
  zombie Fired setTimeout after 0ms delay +0ms
  zombie Fired setTimeout after 0ms delay +0ms
  zombie Fired setTimeout after 0ms delay +0ms
  zombie Fired setTimeout after 0ms delay +0ms
  zombie Fired setInterval every 40ms +0ms
  zombie Fired setInterval every 40ms +1ms
  zombie Fired setInterval every 40ms +26ms
  zombie Fired setInterval every 40ms +0ms
  zombie GET https://media.richrelevance.com/rrserver/js/1.2/p13n.js => 200 +33ms
  zombie GET https://media.richrelevance.com/rrserver/js/1.2/p13n.js => 200 +2ms
  zombie Fired setInterval every 40ms +6ms
  zombie Fired setInterval every 40ms +0ms
  zombie Fired setInterval every 40ms +39ms
  zombie Fired setInterval every 40ms +1ms
  zombie Fired setInterval every 40ms +46ms
  zombie Fired setInterval every 40ms +1ms
  zombie GET https://js-agent.newrelic.com/nr-spa-1071.min.js => 200 +1ms
  zombie Fired setInterval every 40ms +36ms
  zombie Fired setInterval every 40ms +0ms
  zombie GET https://www.gstatic.com/recaptcha/api2/v1525674693836/recaptcha__pt_br.js => 200 +6ms
  zombie GET https://8177467.fls.doubleclick.net/activityi;src=8177467;type=invmedia;cat=uu9tcwvf;ord=4833216493067;gtm=G4r;u2=%2F;%7Eoref=https%3A%2F%2Fwww.wine.com.br%2F? => 200 +25ms
  zombie Opened window https://adservice.google.com/ddm/fls/i/src=8177467;type=invmedia;cat=uu9tcwvf;ord=4833216493067;gtm=G4r;u2=%2F;_dc_1=1;%7Eoref=https%3A%2F%2Fwww.wine.com.br%2F  +6ms
  zombie Loaded document https://8177467.fls.doubleclick.net/activityi;src=8177467;type=invmedia;cat=uu9tcwvf;ord=4833216493067;gtm=G4r;u2=%2F;%7Eoref=https%3A%2F%2Fwww.wine.com.br%2F? +2ms
  zombie Fired setInterval every 40ms +3ms
  zombie Fired setInterval every 40ms +1ms
  zombie Fired setInterval every 40ms +39ms
  zombie Fired setInterval every 40ms +1ms
  zombie Fired setTimeout after 500ms delay +31ms
  zombie Fired setTimeout after 500ms delay +7ms
  zombie Fired setInterval every 40ms +1ms
  zombie Fired setInterval every 40ms +0ms
  zombie Fired setInterval every 40ms +40ms
  zombie Fired setInterval every 40ms +0ms
  zombie >> reCAPTCHA couldn't find user-provided function: vueRecaptchaApiLoaded +44ms
  zombie Fired setInterval every 40ms +10ms
  zombie Fired setInterval every 40ms +1ms
  zombie Fired setInterval every 40ms +38ms
  zombie Fired setInterval every 40ms +0ms
  zombie GET https://adservice.google.com/ddm/fls/i/src=8177467;type=invmedia;cat=uu9tcwvf;ord=4833216493067;gtm=G4r;u2=%2F;_dc_1=1;%7Eoref=https%3A%2F%2Fwww.wine.com.br%2F => 200 +28ms
  zombie Opened window https://adservice.google.by/ddm/fls/i/src=8177467;type=invmedia;cat=uu9tcwvf;ord=4833216493067;gtm=G4r;u2=%2F;_dc_1=3;%7Eoref=https%3A%2F%2Fwww.wine.com.br%2F  +4ms
  zombie Loaded document https://adservice.google.com/ddm/fls/i/src=8177467;type=invmedia;cat=uu9tcwvf;ord=4833216493067;gtm=G4r;u2=%2F;_dc_1=1;%7Eoref=https%3A%2F%2Fwww.wine.com.br%2F +1ms
  zombie Fired setInterval every 40ms +7ms
  zombie Fired setInterval every 40ms +1ms
  zombie POST https://www.wine.com.br/dwr/call/plaincall/customerAjaxController.getLoggedCustomer.dwr => 200 +27ms
  zombie XHR readystatechange https://www.wine.com.br/dwr/call/plaincall/customerAjaxController.getLoggedCustomer.dwr +1ms
  zombie XHR readystatechange https://www.wine.com.br/dwr/call/plaincall/customerAjaxController.getLoggedCustomer.dwr +0ms
  zombie XHR readystatechange https://www.wine.com.br/dwr/call/plaincall/customerAjaxController.getLoggedCustomer.dwr +1ms
  zombie XHR progress https://www.wine.com.br/dwr/call/plaincall/customerAjaxController.getLoggedCustomer.dwr +0ms
  zombie XHR load https://www.wine.com.br/dwr/call/plaincall/customerAjaxController.getLoggedCustomer.dwr +0ms
  zombie XHR loadend https://www.wine.com.br/dwr/call/plaincall/customerAjaxController.getLoggedCustomer.dwr +0ms
  zombie POST https://www.wine.com.br/dwr/call/plaincall/searchSuggestionAjaxController.listAllSearchSuggestions.dwr => 200 +3ms
  zombie XHR readystatechange https://www.wine.com.br/dwr/call/plaincall/searchSuggestionAjaxController.listAllSearchSuggestions.dwr +0ms
  zombie XHR readystatechange https://www.wine.com.br/dwr/call/plaincall/searchSuggestionAjaxController.listAllSearchSuggestions.dwr +0ms
  zombie XHR readystatechange https://www.wine.com.br/dwr/call/plaincall/searchSuggestionAjaxController.listAllSearchSuggestions.dwr +1ms
  zombie XHR progress https://www.wine.com.br/dwr/call/plaincall/searchSuggestionAjaxController.listAllSearchSuggestions.dwr +0ms
  zombie XHR load https://www.wine.com.br/dwr/call/plaincall/searchSuggestionAjaxController.listAllSearchSuggestions.dwr +0ms
  zombie XHR loadend https://www.wine.com.br/dwr/call/plaincall/searchSuggestionAjaxController.listAllSearchSuggestions.dwr +0ms
  zombie Fired setInterval every 40ms +17ms
  zombie POST https://www.wine.com.br/dwr/call/plaincall/autocompleteSearchResultAjaxController.findProducts.dwr => 200 +1ms
  zombie POST https://www.wine.com.br/dwr/call/plaincall/shoppingCartAjaxController.getShoppingCart.dwr => 200 +0ms
  zombie POST https://www.wine.com.br/dwr/call/plaincall/productAjaxController.getProductHotsiteViewBean.dwr => 200 +0ms
  zombie Fired setInterval every 40ms +2ms
  zombie XHR readystatechange https://www.wine.com.br/dwr/call/plaincall/autocompleteSearchResultAjaxController.findProducts.dwr +0ms
  zombie XHR readystatechange https://www.wine.com.br/dwr/call/plaincall/autocompleteSearchResultAjaxController.findProducts.dwr +1ms
  zombie XHR readystatechange https://www.wine.com.br/dwr/call/plaincall/autocompleteSearchResultAjaxController.findProducts.dwr +0ms
  zombie XHR progress https://www.wine.com.br/dwr/call/plaincall/autocompleteSearchResultAjaxController.findProducts.dwr +0ms
  zombie XHR load https://www.wine.com.br/dwr/call/plaincall/autocompleteSearchResultAjaxController.findProducts.dwr +0ms
  zombie XHR loadend https://www.wine.com.br/dwr/call/plaincall/autocompleteSearchResultAjaxController.findProducts.dwr +0ms
  zombie XHR readystatechange https://www.wine.com.br/dwr/call/plaincall/shoppingCartAjaxController.getShoppingCart.dwr +1ms
  zombie XHR readystatechange https://www.wine.com.br/dwr/call/plaincall/shoppingCartAjaxController.getShoppingCart.dwr +0ms
  zombie POST https://www.wine.com.br/dwr/call/plaincall/productAjaxController.getProductHotsiteViewBean.dwr => 200 +1ms
  zombie XHR readystatechange https://www.wine.com.br/dwr/call/plaincall/shoppingCartAjaxController.getShoppingCart.dwr +1ms
  zombie XHR progress https://www.wine.com.br/dwr/call/plaincall/shoppingCartAjaxController.getShoppingCart.dwr +0ms
  zombie XHR load https://www.wine.com.br/dwr/call/plaincall/shoppingCartAjaxController.getShoppingCart.dwr +0ms
  zombie XHR loadend https://www.wine.com.br/dwr/call/plaincall/shoppingCartAjaxController.getShoppingCart.dwr +0ms
  zombie XHR readystatechange https://www.wine.com.br/dwr/call/plaincall/productAjaxController.getProductHotsiteViewBean.dwr +1ms
  zombie XHR readystatechange https://www.wine.com.br/dwr/call/plaincall/productAjaxController.getProductHotsiteViewBean.dwr +0ms
  zombie XHR readystatechange https://www.wine.com.br/dwr/call/plaincall/productAjaxController.getProductHotsiteViewBean.dwr +1ms
  zombie XHR progress https://www.wine.com.br/dwr/call/plaincall/productAjaxController.getProductHotsiteViewBean.dwr +0ms
  zombie XHR load https://www.wine.com.br/dwr/call/plaincall/productAjaxController.getProductHotsiteViewBean.dwr +0ms
  zombie XHR loadend https://www.wine.com.br/dwr/call/plaincall/productAjaxController.getProductHotsiteViewBean.dwr +0ms
`

UPD: accident or not, after testing this, I've lost the ability to connect to trello through chrome or firefox, ping to it still worked though.

**Comment by AliasIO** [comment]
Closing this one a duplicate.
