### ISSUE TITLE
Bug: 1&1 MyWebsite (Homepage-Editor) misinterpreted as Jimdo

### ISSUE THREAD

**Issue by josch87** [AliasIO/Wappalyzer#2293]
**Do you want to request a *feature*, a *new application detection* or report a *bug*?**
Bug

**Is your issue about WebExtension driver (Chrome & Firefox), the website, the NPM driver or the bookmarklet ?**
Chrome Extension v 5.4.14

**What is the current behavior ?**
Wappalyzer is showing Jimdo instead of 1&1 MyWebsite

**If the current behavior is a bug, please provide the steps to reproduce and if possible a demo of the problem.**
1. Go to a Website that is build using 1&1 MyWebsite / [Example](https://www.danielbaaden.de/)
2. Open Wappalyzer Chrome Extension
3. CMS is recognized as Jimdo

**What is the expected behavior ?**
- Extension should say 1&1 MyWebsite or at least not show Jimdo

**Which versions of Wappalyzer, and which browser / OS are affected by this issue ? Did this work in previous versions ?**
- Wappalyzer Chrome Extension v5.4.14
- Chrome Version 66.0.3359.170 (Offizieller Build) (64-Bit)

**Comment by jvoisin** [comment]
This website you're providing is using jimdo. We don't have detection for "1&1 MyWebsite" in wappalyzer, so this is an perfectly normal and expected behaviour.
