### ISSUE TITLE
Feature request : use proxy in NPM driver

### ISSUE THREAD

**Issue by sclikaflon** [AliasIO/Wappalyzer#2298]
It would be nice to be able to use a proxy with Wappalyzer (NPM driver).

Using environment variables is an easy way to do this. In src/drivers/npm/driver.js, line 122, add :

```
if('HTTP_PROXY' in process.env) {
  browser.proxy = process.env.HTTP_PROXY;
}
```

**Comment by AliasIO** [comment]
I added an option for it in the master branch, would you be able to test it? From the command line you can pass `--proxy=<string>`

**Comment by sclikaflon** [comment]
It works ! Thanks a lot !

**Comment by superhac** [comment]
This doesn't appear to work with HTTPS proxies.  Can we get HTTPS support?

Thanks!
