### ISSUE TITLE
New Category: User Onboarding

### ISSUE THREAD

**Issue by enginaryum** [AliasIO/Wappalyzer#2307]
Hey guys, I am one of the founders of [UserGuiding ](https://userguiding.com)-user onboarding product.
I've just searched for user onboarding tools on Wappalyzer, but couldn't find one.
So, I wanted to open up a discussion about creating a **user onboarding** category.

**Comment by AliasIO** [comment]
Would you be happy to help include some of your competitors as well? A new category makes sense if we have a handful of technologies to include.

**Comment by enginaryum** [comment]
Yeah, definitely happy to include them as well. 
Here is a wiki post on Quora. 
https://www.quora.com/What-tools-are-companies-using-to-onboard-new-users
Should I open a PR for this?

**Comment by AliasIO** [comment]
Yes, thanks!

**Comment by AlexByte** [comment]
> Answers to this question fall broadly into five main categories of tools: analytics tools to track key events, and user onboarding guide tools, email tools, A/B-testing tools, user survey tools, client onboarding for high-ticket sales and generalized support tools to support users.

Why do you need a generic category?

**Comment by enginaryum** [comment]
Better use `User Onboarding In-App Tools` then?

**Comment by AlexByte** [comment]
https://github.com/AliasIO/Wappalyzer/blob/69f575c83f4a15bf1489f1529c96ed1f1cd36648/src/apps.json#L12558
