### ISSUE TITLE
Is wappalyzer supposed to crawl urls from third party websites in recursive mode?

### ISSUE THREAD

**Issue by avasilkov** [AliasIO/Wappalyzer#2316]
**Do you want to request a *feature*, a *new application detection* or report a *bug*?**
BUG?

**Is your issue about WebExtension driver (Chrome & Firefox), the website, the NPM driver or the bookmarklet ?**
NPM master

**What is the current behavior ?**
npm driver crawls all links on a website, even those that lead to third party

**What is the expected behavior ?**
I was thinking it should crawl urls only leading to same host

The line in question

`link.protocol.match(/https?:/) || link.hostname === this.origPageUrl.hostname || extensions.test(link.pathname)`
I think it should be
`link.protocol.match(/https?:/) && link.hostname === this.origPageUrl.hostname && extensions.test(link.pathname)`

I've attached a PR if needed

**Comment by AliasIO** [comment]
PR merged, thank you!
