### ISSUE TITLE
perl version detection isn't working

### ISSUE THREAD

**Issue by jvoisin** [AliasIO/wappalyzer#2324]
With the latest (5.4.14) Wappalyzer version in Chrome, I can't get the version of Perl from [thinkgeek](https://www.thinkgeek.com/), despite it being present in the `Server` header: `Apache/2.4.6 (CentOS) mod_apreq2-20090110/2.8.0 mod_perl/2.0.10 Perl/v5.16.3`.

**Comment by gadcam** [comment]
Perl is deduced because of the detection of <code>mod_perl</code> and Wappalyzer is displaying the version number for <code>mod_perl</code> so it is an expected behavior.

**Comment by jvoisin** [comment]
Perl should be detected via the headers too:

```json
    "Perl": {
      "cats": [
        27
      ],
      "headers": {
        "Server": "\bPerl\b(?: ?/?v?([\\d.]+))?\\;version:\\1"
      },
      "icon": "Perl.png",
      "website": "http://perl.org"
    },
```
