### ISSUE TITLE
Not detecting VueJS

### ISSUE THREAD

**Issue by Sarke** [AliasIO/Wappalyzer#2328]
**Do you want to request a *feature*, a *new application detection* or report a *bug*?**
Detection

**Is your issue about WebExtension driver (Chrome & Firefox), the website, the NPM driver or the bookmarklet ?**
Chrome Extension

**What is the current behavior ?**
Not detecting Vue 2 and Vuex

**If the current behavior is a bug, please provide the steps to reproduce and if possible a demo of the problem.**
Several demos here: https://github.com/vuejs/awesome-vue#examples

Example: https://vue-hn.now.sh/top

I'm not sure how Wappalyzer detects libraries, but `window.Vue` will be available if Vue is loaded.

If `.js` files are scanned, a good way to detect them is to use the `^\s*\* (?<name>.+) v(?<version>[\d\.]+)$` pattern.  Example:

```
/*!
 * Vue.js v2.5.16
 * (c) 2014-2018 Evan You
 * Released under the MIT License.
 */

/**
 * vuex v3.0.1
 * (c) 2017 Evan You
 * @license MIT
 */
```
These minimal headers are part of the minified assets.

**What is the expected behavior ?**
Detect Vue

**Which versions of Wappalyzer, and which browser / OS are affected by this issue ? Did this work in previous versions ?**
5.4.14, Chrome

**Comment by jvoisin** [comment]
Vue is detected here (Wappalyzer 5.4.14 on Chrome).

**Comment by Sarke** [comment]
Very strange, now it is.  Ignore.

**Comment by lloydjatkinson** [comment]
It still doesn't detect it.

**Comment by jvoisin** [comment]
It's detecting Vue here.

@lloydjatkinson what version of wappalyzer are you using?

**Comment by lloydjatkinson** [comment]
5.5.3

See my repo for an example: https://github.com/lloydjatkinson/crimson (http://crimson.netlify.com/)

**Comment by jvoisin** [comment]
On http://crimson.netlify.com/ there is no `Vue` object, nor an inclusion of a script named vue-something. How could wappalyzer detect the usage of Vue ?

**Comment by lloydjatkinson** [comment]
There are a few ways. I don't know if the apps.json approach is flexible enough for apps built with build tools though.

https://github.com/vuejs/vue-devtools/blob/e34da177b909255a46a13667d63681639672c8a3/shells/chrome/src/detector.js

**Comment by jvoisin** [comment]
This possible detection is blocked by #2450

**Comment by freerider7777** [comment]
Not working (Chrome for Windows 70.0.3538.102), though "Vue DevTools" extension does.
