### ISSUE TITLE
New gmail layout

### ISSUE THREAD

**Issue by azdanov** [AliasIO/Wappalyzer#2335]
False positive on new gmail layout.

https://mail.google.com/

<img width="467" alt="screen shot 2018-06-05 at 01 16 05" src="https://user-images.githubusercontent.com/6123841/40944611-19dd57b0-685e-11e8-9476-e1bea3b80709.png">

**Comment by AlexByte** [comment]
@jvoisin All is good 
![image](https://user-images.githubusercontent.com/25251772/41131455-88eb49c4-6ac4-11e8-891d-21476fc25cc2.png)

**Comment by AlexByte** [comment]
Not confirmed by me

**Comment by azdanov** [comment]
`5.4.18` fixed this for me.
