### ISSUE TITLE
--max-wait option broken for anyting over 9999 ms

### ISSUE THREAD

**Issue by superhac** [AliasIO/Wappalyzer#2341]
I'm using Wappalyzer with a proxy as shown below:
`
node /home/redteam/wappalyzer/node_modules/wappalyzer/index.js https://news.com --proxy=http://1.1.1.2:8080 --max-depth=1 --max-wait=15000`

Anytime the value of max-wait is greater than 9999, I get the non-descriptive, "force quit".  The reason I need higher values is due to the fact i'm using the new "--proxy" option.  Proxies are slow...

Thanks!

**Comment by AliasIO** [comment]
There is a hardcoded 10 second timeout, I might change to use the `maxWait` value. For now you can comment it out:

https://github.com/AliasIO/Wappalyzer/blob/master/src/drivers/npm/index.js#L32

**Comment by superhac** [comment]
That was it.  I cranked up the SetTimeout value you referred to 60000 and set my --maxWait to 50000 and it worked as expected!   Thanks for your help on this!

**Comment by AliasIO** [comment]
Cheers!
