### ISSUE TITLE
Can we analyze iframe's on a page?

### ISSUE THREAD

**Issue by AlexByte** [AliasIO/Wappalyzer#2343]

**Comment by AliasIO** [comment]
Technically yes but it will require a bit of work. Right now we don't pay attention to requests that don't match the tab URL.

https://github.com/AliasIO/Wappalyzer/blob/master/src/drivers/webextension/js/driver.js#L120
https://github.com/AliasIO/Wappalyzer/blob/master/src/drivers/webextension/js/driver.js#L135

**Comment by DylanTusler** [comment]
Would it be possible to report iframes as a technology used by a website? Just like other technologies?

**Comment by AlexByte** [comment]
@DylanTusler yes, by regex of html https://www.wappalyzer.com/docs/specification

**Comment by kyletaylored** [comment]
It might be misleading to infer the functionality of a site based on the content of an iframe, especially when you consider things like tracking scripts that use them as a cookie proxy.
