### ISSUE TITLE
Websites specify what is shown in Wappalyzer

### ISSUE THREAD

**Issue by Stryxus** [AliasIO/Wappalyzer#2347]
To improve detection (mainly for websites that have unique minification/compression or they are just in general hard to detect anything on) would wappalyzer be able to look for a .json file in the root directory?

So for instance, wappalyzer on my website (https://www.stryxus.net) would look for 'https://www.stryxus.net/wappalyzer.json' which specifies the technologies used within the website.

**Comment by AliasIO** [comment]
It's a nice idea but I don't think we'd want to rely on websites reporting their own stack. I also think not many websites will make use of this feature. Finally, Wappalyzer intentionally doesn't make any requests to websites.
