### ISSUE TITLE
Support for basic auth

### ISSUE THREAD

**Issue by SecSamDev** [AliasIO/Wappalyzer#2349]
New Feature: basic authentication

Currently not supported, but zombie browser supports it by default:
[zombie authentication](https://www.npmjs.com/package/zombie#authentication)
```
browser.on('authenticate', function(authentication) {
  authentication.username = 'myusername';
  authentication.password = 'mypassword';
});

browser.visit('/mypage');
```

**Comment by AliasIO** [comment]
Added in 0083cf14f1d0429c9ee5617b43806cb8c6a526f8.
