### ISSUE TITLE
Updating SPIP icon identifying

### ISSUE THREAD

**Issue by YannDX** [AliasIO/Wappalyzer#2355]
The free CMS "SPIP" has recently upgraded its graphic identity (see https://contrib.spip.net/5014 - https://contrib.spip.net/4918 ).
So I suggest you to **upgrade visual icon for SPIP**, by using this file
![spip](https://user-images.githubusercontent.com/40489779/41785932-5c5285b8-7644-11e8-9bb8-15b8b49d2ca7.png).

Thanks a lot !

YannX
_Enjoying Wappalyzer.._

**Comment by jvoisin** [comment]
You can [do it yourself]( https://www.wappalyzer.com/docs ), it's not that complicated :)
