### ISSUE TITLE
Bug: Wrong link for Gitbook.io

### ISSUE THREAD

**Issue by ashussen** [AliasIO/Wappalyzer#2359]
Bug: Wrong website link for Gitbook.io

They are using [gitbook.com](https://www.gitbook.com/) as their landing page. Not gitbook.io anymore, it returns error on that page.

**Comment by jvoisin** [comment]
`gitbook.io` is issuing a `301` to `gitbook.com` here.
It's ok, we can keep gitbook.io

**Comment by AliasIO** [comment]
Fixed in de5453f8a26845c996ae271d34f856e4824f8f93, thanks.
