### ISSUE TITLE
./run validate, missing file

### ISSUE THREAD

**Issue by craiglondon** [AliasIO/Wappalyzer#2361]
**Do you want to request a *feature*, a *new application detection* or report a *bug*?**
BUG

**Is your issue about WebExtension driver (Chrome & Firefox), the website, the NPM driver or the bookmarklet ?**
NPM? Docker?

**What is the current behavior ?**
Terminal display a message that a file is missing

**If the current behavior is a bug, please provide the steps to reproduce and if possible a demo of the problem.**
```
$ ./run validate
yarn install v1.1.0
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.46s.
yarn install v1.1.0
warning package.json: No license field
warning No license field
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.29s.
patching file src/drivers/npm/node_modules/zombie/lib/document.js
patch: can't open 'src/drivers/npm/node_modules/zombie/lib/document.js': No such file or directory
Creating links...
Done.
```

**What is the expected behavior ?**
Expect all files to be present

**Which versions of Wappalyzer, and which browser / OS are affected by this issue ? Did this work in previous versions ?**
5.4.18

**Comment by AliasIO** [comment]
Fixed in 0f89faacc486d30865d67c6926e4313e7f2fe7cd, thanks.
