### ISSUE TITLE
Bundling of technologies when including Revolution Slider

### ISSUE THREAD

**Issue by oncena** [AliasIO/Wappalyzer#2362]
I've been coding my own projects for a while now and I'm a bit pedantic when it comes to using certain libraries such as Revolution Slider. While I'm not using MySQL, WordPress or even PHP for that matter, including Revolution Slider jQuery Plugin in the project outputs all of the technologies above in the Wappalyzer pane. I'd really appreciate it if you could take a little time to do something about it. Thank y'all!

**Comment by jvoisin** [comment]
Since you're a coder, you can add it yourself, it's not [that complicated]( https://www.wappalyzer.com/docs ) :)

**Comment by oncena** [comment]
LOL maybe I will, but it's not an add, it's a separation kinda situation.

**Comment by kyletaylored** [comment]
This is because currently when Revo is detected, it's implied that the site is using WordPress. I can see how if you're using only the jQuery plugin, it'd be misleading. I'll get a patch.
