### ISSUE TITLE
Wappalyzer cause VISA payments at a FirstData CONNECT gateway to failed (CANCELED)

### ISSUE THREAD

**Issue by tolispy** [AliasIO/Wappalyzer#2364]
When Wappalyzer Google Chrome Plugin is active, VISA payments at modirum.com (FirstData CONNECT gateway) are failing (marked as CANCELED, no payment is done).

When Wappalyzer is off the payments are not failing.

When you enter the VISA cart number into:

`<input class="ovaltextboxCard" id="card.pan" name="card.pan" type="text" maxlength="19" value="censored" onfocus="setBonusFocus('payform1', 'card.pan', this.value);setOldPan(this.value);" onblur="ResetPayMethodIfNeeded('payform1',this.value);checkBonus(this.value);" readonly="">`

the payment gateway runs a javascript to calculate "Bonus points". Although, it displays the bonus points, there is a warning:

`SyntaxError: Unexpected token o in JSON at postition 1`
`	at JSON.parse(<anonymous>)`
`	at receiveBonusMessage (https://alpha.test.modirum.com/vpos/js/xlsbonus.js:105:22)`

the warning does not popup up, when Wappalyzer is off

> https://alpha.test.modirum.com/vpos/shophandlermpi is a FORM Action POST URL for test payments
> https://www.alphaecommerce.gr/vpos/shophandlermpi is a FORM Action POST URL for real payments

you press OK to close the message
you fill all correct info and you press the "Payment" button
and then you redirect to the eshop website that initiate the payment process, saying that the payment was CANCELED.
And it ready did, no payment was made.

I email the bank, about payments are failing (without mentioning the Wappalyzer plugin, I did not know what was causing the problem), and they reply:

> if you have installed Wappalyzer, turn it off or uninstall ! ! !

So, they are aware about the issue, but of course the are not going to do something. Their site works well, when there is no Wappalyzer plugin.

Can you check, what causing the malfunction?

If not, can you add an option to exclude certain websites/URLs, so Wappalyzer plugin is not loading.
per example:

`*.modirum.com/*`
`https://www.alphaecommerce.gr/*`
`*/vpos/*`

Thanks a lot !

**Comment by AliasIO** [comment]
I added the exclusion rules for those domains to the manifest. Really all they need to do is validate the message content before parsing it.

https://github.com/AliasIO/Wappalyzer/commit/42fd5f91535208399dd8c3154b4579559226a4b2#diff-15e99d1034c08afc85840ace414889f3
