### ISSUE TITLE
Falsely Showing Google Analytics and Google Fonts included

### ISSUE THREAD

**Issue by Peazyyy** [AliasIO/Wappalyzer#2374]
**Do you want to request a *feature*, a *new application detection* or report a *bug*?**

No

**Is your issue about WebExtension driver (Chrome & Firefox), the website, the NPM driver or the bookmarklet ?**

WebExtension for Chrome

**What is the current behavior ?**

Falsely Showing Google Analytics and Google Fonts being included

![image](https://user-images.githubusercontent.com/28291445/42272122-6c2dffb8-7f85-11e8-8b74-6c3dd500a526.png)

**What is the expected behavior ?**

Not showing Google Analytics and Google Fonts

**Comment by Peazyyy** [comment]
https://advoauto.de/index.php There you go. Google Fonts magically disappeared but the Issue with GA still persists

**Comment by AliasIO** [comment]
Thanks for the example. I can't reproduce the issue though, neither Google Analytics or Google Fonts show up for me.

**Comment by Peazyyy** [comment]
As far as I can comprehend, this might have been a cache issue or something. After checking the website out over a month later I can't find a google analytics entry myself either. 

Thank you for your time anyway.

Take care!
