### ISSUE TITLE
NPM driver returns inconsistent results

### ISSUE THREAD

**Issue by xde013** [AliasIO/wappalyzer#2375]
## What is the current behavior ?
Wappalyzer fails sometimes to get response from server and thus outputting empty result. 
Other times it returns incomplete list of detected services.

**Empty result**
![image](https://user-images.githubusercontent.com/21088699/42273850-c1e506ea-7f8a-11e8-8eee-9f0ed4981025.png)

**Incomplete result**
![image](https://user-images.githubusercontent.com/21088699/42277856-16cdee70-7f99-11e8-8217-f757779f791d.png)

**the steps to reproduce the problem**

```
const url = 'https://www.engadget.com'
const wappalyzer = new Wappalyzer(url, options); 
wappalyzer.analyze()
  .then(json => {
    process.stdout.write(JSON.stringify(json, null, 2) + '\n') 
    process.exit(0);
  })
  .catch(error => {
    process.stderr.write(error + '\n')
 
    process.exit(1);
});
```
**What is the expected behavior ?**

*Output complete list of all services*

![image](https://user-images.githubusercontent.com/21088699/42277887-309f87aa-7f99-11e8-8e15-bad50140e6a4.png)

**Comment by AliasIO** [comment]
I'm not sure what causes this. It's an issue with Zombie.js most likely.

**Comment by xde013** [comment]
@AliasIO is there any possibility to switch to another browser?

**Comment by AliasIO** [comment]
What do you suggest?

**Comment by dege88** [comment]
Headless chrome is really nice to work with. Especially with puppeteer ( https://github.com/GoogleChrome/puppeteer ).
Unfortunately I've some issues with zombie too (it's crashing the entire node process on some websites)

**Comment by AliasIO** [comment]
Zombie.js is much, much leaner than headless Chrome and runs entirely in JavaScript, making it more portable.

**Comment by AliasIO** [comment]
It's now possible to use a different headless browser by crearting a wrapper, like this one for Zombie.js:

https://github.com/AliasIO/Wappalyzer/blob/master/src/drivers/npm/browsers/zombie.js

**Comment by juffardm** [comment]
Hi, I try to use Wappalyzer with Puppeteer. Do you have a working wrapper for this browser? :)
(I have troubles to get the js of the page I want to analyze)

**Comment by ThomasLohner** [comment]
@juffardm Did you succeed? Can anyone share a working example of using wappalyzer with puppeteer?

**Comment by ThomasLohner** [comment]
@xde013 @juffardm This will be fixed by adding Puppeteer support in #2711. Until then as a workaround you can grab [pupeteer.js](https://github.com/realhidden/Wappalyzer/blob/feature/puppeteer/src/drivers/npm/browsers/puppeteer.js) from [realhidden/Wappalyzer](https://github.com/realhidden/Wappalyzer/) and put it in your project.

You will need to change the line
```
const Browser = require('../browser');
```
to
```
const Browser = require('wappalyzer/browser');
```

Add Puppeteer & Puppeteer-Cluster `npm i puppeteer puppeteer-cluster`. 

Now your fine to go with this working example:

```
const url = 'https://www.google.com';

const options = {
  debug: false,
  delay: 500,
  maxDepth: 3,
  maxUrls: 10,
  maxWait: 5000,
  recursive: true,
  userAgent: 'Wappalyzer',
  htmlMaxCols: 2000,
  htmlMaxRows: 2000,
};

const Wappalyzer = require('wappalyzer/driver.js');
const Browser = require('./puppeteer.js');
const wappalyzer = new Wappalyzer(Browser, url, options);
 
wappalyzer.analyze()
  .then(json => {
    process.stdout.write(`${JSON.stringify(json, null, 2)}\n`);
 
    process.exit(0);
  })
  .catch(error => {
    process.stderr.write(`${error}\n`);
 
    process.exit(1);
});
```

**Comment by rainbowhat** [comment]
@ThomasLohner Thank you so much for your codes, it seems to be working fine detecting full technologies. I realized you use puppeteer-cluster , based on this latest comment on Jul 30, is there any way to push a list of URLs into the puppeteer-clusters instead of one URL?

**Comment by ThomasLohner** [comment]
@rainbowhat I don't know ;-) I'm just using code from https://github.com/realhidden/Wappalyzer/ which is pending here in #2711. I guess you should ask @realhidden if there is a way to push multiple urls at once into puppeteer-cluster / wappalyzer.

**Comment by hugoobauer** [comment]
The support of Puppeteer has been released, but I have still inconsistency between Chrome Plugin and NPM driver.
For https://www.tsr-recyclage.fr/, Google Analytics is detected with the plugin, but not with the driver

```
  const maxWait = req.query.maxWait || 5000;
  const options = {
    browser: 'puppeteer',
    debug: true,
    delay: 0,
    maxDepth: 1,
    maxUrls: 1,
    maxWait: maxWait,
    recursive: false,
    userAgent: "Wappalyzer"
  };

  const wappalyzer = new Wappalyzer("https://www.tsr-recyclage.fr/", options);
  wappalyzer
    .analyze()
    .then(json => {
      process.stdout.write(`${JSON.stringify(json, null, 2)}\n`);
 
      process.exit(0);
    })
    .catch(error => {
      process.stderr.write(`${error}\n`);
 
      process.exit(1);
    });
```

```
[wappalyzer debug] [core] Identified Lodash, Nginx (www.tsr-recyclage.fr)
```

Do you know where this might be coming from?

**Comment by AliasIO** [comment]
@hugoobauer It looks like GA is only being loaded after accepting cookies on that website.
