### ISSUE TITLE
New category suggestion: JS Libraries/Plugins

### ISSUE THREAD

**Issue by katexue** [AliasIO/Wappalyzer#2383]
There are quite a few JS libraries/plugins been marked as JavaScript Frameworks. Wonder if it's a better idea to have a new category JS Libraries to separate them out from Frameworks?

**Comment by AliasIO** [comment]
Added in 483696a480ae8b8794bd9649b1af1b6415fd9ff1. Do you want to submit a pull request to move technologies into this category? 🐕
