### ISSUE TITLE
Possible copyright infringment

### ISSUE THREAD

**Issue by jvoisin** [AliasIO/Wappalyzer#2393]
Hello,

it seems that [purplemet]( https://twitter.com/purplemet ) ([site](https://t.co/6v5N5kGGay )) might be using Wappalyzer's database, which is released under GPLv3, without providing the source.

I might be wrong; do we want to investigate further?

**Comment by AliasIO** [comment]
The GPL doesn't require attribution for use of the software.

**Comment by jvoisin** [comment]
Actually, [it does]( https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3) ), by requiring to include the copyright.

And even if it wouldn't require it, I still want to see the source code anyway ;)

**Comment by AliasIO** [comment]
They need to retain the copyright and license when distributing the code, and make available any changes made. The don't need to attribute the copyright holders on their website if they simply use the software.

**Comment by jvoisin** [comment]
Ho, you're right, I was thinking about AGPL, my bad ♥
