### ISSUE TITLE
Can I do something to keep the Wappalyzer icon something recognizable?

### ISSUE THREAD

**Issue by tonyd85** [AliasIO/Wappalyzer#2394]
**Do you want to request a *feature*, a *new application detection* or report a *bug*?**
REQUEST .ICO
**Is your issue about WebExtension driver (Chrome & Firefox), the website, the NPM driver or the bookmarklet ?**

**What is the current behavior ?**
CHROME EXT .ICO CHANGES BETWEEN SITES. I CANNOT FIND WAPPALYZER EASILY
**If the current behavior is a bug, please provide the steps to reproduce and if possible a demo of the problem.**

**What is the expected behavior ?**
I WANT TO SEE A CONSISTENT WAPPALYZER ICON.
**Which versions of Wappalyzer, and which browser / OS are affected by this issue ? Did this work in previous versions ?**

**Comment by AliasIO** [comment]
There is an option for it in the settings.

**Comment by tonyd85** [comment]
Thank you!

**Comment by littlepiggy03** [comment]
@AliasIO I've unticked "Use technology icon instead of Wappalyzer logo" in setting but it still doesn't show the Wapplyzer logo. I'm now using Wappalyzer 5.5.3. I think is a bug in the new version because the setting don't work after update (probably 5.5.3). Could you check it out?

**Comment by trvrfrd** [comment]
I'm also seeing the technology logo regardless of checking/unchecking the setting in Wappalyzer 5.5.3 on Firefox 62. Had never seen it before the most recent update.

**Comment by rotsee** [comment]
Same issue in `5.5.7` on Chrome 71 (and multiple previous versions); Un-checking “Use technology icon instead of Wappalyzer logo” in the settings does not seem to have any effect.

**Comment by littlepiggy03** [comment]
This issue may related to #2490 .

**Comment by AliasIO** [comment]
Yes, this should be fixed now.
