### ISSUE TITLE
Priorities are wrong again

### ISSUE THREAD

**Issue by jvoisin** [AliasIO/Wappalyzer#2397]
It seems that the priorities are a [bit messed]( https://github.com/AliasIO/Wappalyzer/pull/2396 ) again. Shall I spend some time to reorder them @AliasIO ?

**Comment by AliasIO** [comment]
That would be awesome. 👍

**Comment by jvoisin** [comment]
[here]( https://github.com/AliasIO/Wappalyzer/pull/2400 ) you go ;)

**Comment by jvoisin** [comment]
Merged ♥
