### ISSUE TITLE
reCaptcha is not being reported

### ISSUE THREAD

**Issue by DylanTusler** [AliasIO/Wappalyzer#2399]
**Do you want to request a *feature*, a *new application detection* or report a *bug*?**
Bug
**Is your issue about WebExtension driver (Chrome & Firefox), the website, the NPM driver or the bookmarklet ?**
Extension + website

**What is the current behavior ?**
reCaptcha presence is not reported. For instance, www.wappalyzer.com uses reCaptcha. If I enter that website into the web form or use the Chrome plugin, reCaptcha is not reported even when it is visible on the page (see for example https://www.wappalyzer.com/datasets )

**If the current behavior is a bug, please provide the steps to reproduce and if possible a demo of the problem.**
Using the chrome plugin visit https://www.wappalyzer.com/datasets then scroll down the page to verify that there is a reCaptcha on the page (above the "Request Quote" button). Check the installed technologies on the plugin and observe that reCaptcha is not on the list.

**What is the expected behavior ?**
reCaptcha should be there.

**Which versions of Wappalyzer, and which browser / OS are affected by this issue ? Did this work in previous versions ?**
Current version. I never saw this working in older versions as I never used older versions. However reCaptcha is definitely in the dataset: https://www.wappalyzer.com/technologies/recaptcha

**Comment by AliasIO** [comment]
Fixed in 53e73202f4132c656d24ffec42f8e4aeeb1e466f, thanks.
