### ISSUE TITLE
Wrong to detect: React

### ISSUE THREAD

**Issue by mxschmitt** [AliasIO/Wappalyzer#2415]
**Do you want to request a *feature*, a *new application detection* or report a *bug*?**: Bug

**Is your issue about WebExtension driver (Chrome & Firefox), the website, the NPM driver or the bookmarklet ?**: Chrome Extension

**What is the current behavior ?**: Does incorrect detection: React

**If the current behavior is a bug, please provide the steps to reproduce and if possible a demo of the problem.**:

- visit this site: `https://www.google.de/search?q=pdffactory+Drucker.&rlz=1C1GCEA_enDE805DE805&oq=pdffactory+Drucker.&aqs=chrome..69i57&sourceid=chrome&ie=UTF-8`
- then the following apps will be detected: Optimizely, React and Google Web Server

**What is the expected behavior ?**Google Web Server and maybe Optimizely

**Which versions of Wappalyzer, and which browser / OS are affected by this issue ? Did this work in previous versions ?** yes, I don't know. I'm using Chrome 67 and Wappalyzer 5.5.2

**Comment by jvoisin** [comment]
I can't reproduce this behaviour with Wappalyzer 5.5.2 and Chromium  68.0.3440.75

**Comment by mxschmitt** [comment]
Hm, can I see easily which rules are matching?
What are your apps which are matching?

**Comment by jvoisin** [comment]
Here, only Google web server is matching.

**Comment by mxschmitt** [comment]
Hm, no clue what was going on. Now I can't reproduce it anymore.
