### ISSUE TITLE
Wappalyzer freezes on certain urls

### ISSUE THREAD

**Issue by fbergroth** [AliasIO/Wappalyzer#2418]
Wappalyzer 5.5.1 (installed via npm) freezes on the following urls:

```
wappalyzer http://xn--flgger-4ya.se
wappalyzer http://p-eebygg.se
```
I haven't debugged it further, just though I'd report it here.

**Comment by jalutin** [comment]
Hello,

I am experiencing the same issue.
I am using Wappalyzer 5.8.2 and I initialized new instance with this config.
```
const wappalyzer = new Wappalyzer(url, {
    debug: true,
    delay: 100,
    maxDepth: 3,
    maxUrls: 10,
    maxWait: 10000,
    recursive: false,
    userAgent: "Wappalyzer"
  });
```

when I try to analyze this url "www.jimdo.com" by using wappalyzer.analyze() function,
it is freezing forever after printing this log.
```
[wappalyzer debug] [core] Identified Google Analytics, Google Tag Manager, Jimdo, Nginx, TrackJs, Varnish (www.jimdo.com)
```

Hope this approach will reproduce the same issue on your side exactly.
Can you please check this issue and let me know how I can fix this problem?

**Comment by kyletaylored** [comment]
Seems to be working now.

![image](https://user-images.githubusercontent.com/1759794/68185514-4bcdbe80-ff67-11e9-953b-3dd5885f48f0.png)
