### ISSUE TITLE
Microsoft Edge support

### ISSUE THREAD

**Issue by Stryxus** [AliasIO/Wappalyzer#2420]
Iv been planning to move to Edge for a while now but there are something drawing me back and the lack of support of Edge is one of thing. I dont feel like im experienced enough to make an extension yet, let alone a port. Just putting this out there since there hasnt been one hint of a port.

**Comment by AliasIO** [comment]
There was a functioning port as some point but Microsoft's approval process is so atrocious that I gave up on it entirely. You can find Edge packages in older releases but they're no longer supported. You can use the bookmarklet version of Wappalyzer in Edge.

**Comment by Stryxus** [comment]
I can confirm the Bookmarklet version doesn't work on Edge and loading the extension version doesn't work either. Also the last I heard the Edge team are only accepting sponsored/select few extensions so far and will open the store freely in the future.

**Comment by AliasIO** [comment]
I'll look into why the bookmarklet isn't working.

I went through all the motions with Microsoft and was invited to submit Wappalyzer to the store. Paid for a Windows license, developer license, supplied assets and information, filled out countless forms including tax details and what not, only to have the extension rejected without a reason or way to contact the reviewer. Not to mention their implementation of WebExtension is not up to spec with [bugs they won't fix](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/9421085/) and the packaging process doesn't work natively on Linux or Mac OS. In contrast, submitting to Chrome and Firefox is as simple as uploading a ZIP file. Microsoft reached out to me a full year later offering some help but by that time I had already given up entirely.

Older releases include APPX packages for Edge but I'm not sure at what point the started/stopped working. You can try your luck here:

https://github.com/AliasIO/Wappalyzer/releases?after=v5.1.6

**Comment by Stryxus** [comment]
Thanks ill test them.

**Comment by Stryxus** [comment]
Can confirm neither of the webextension and appx work. webextension requires the 'persistent' property under 'background' but that was an easy fix, after that Wappalyzer shows nothing because of the bug you linked.

**Comment by Stryxus** [comment]
@AliasIO Due to the fact that it has been confirmed that Edge will now use Chromium and most likely the same extension framework, it could be possible to add the extension to Edge when they start releasing previews in April.
