### ISSUE TITLE
CDN : Akamai on website hm.com is not discovered

### ISSUE THREAD

**Issue by Lnunno76** [AliasIO/Wappalyzer#2430]
I know the company, but for be sure :

ping www.hm.com
PING e13670.b.akamaiedge.net (23.43.115.237): 56 data bytes
64 bytes from 23.43.115.237: icmp_seq=0 ttl=56 time=88.592 ms

Wappalyzer doesn't discovery it.
The same is for dailymail.co.uk and some other

**Comment by jvoisin** [comment]
The website doesn't send any akamai-related headers for Wappalyzer to fingerprint, so this is an expected behaviour.

**Comment by jvoisin** [comment]
Wappalyzer is a passive tool, active checks are out of scope.

**Comment by ThomasLohner** [comment]
Wouldn't it be possible to add another regex check on hostname / ip in addition to html, scripts, cookies, headers and js? This would also identify Hosting Providers ;-)

**Comment by jvoisin** [comment]
Wappalyzer doesn't have access to the IP range, and the hostname here is hm.com

**Comment by kyletaylored** [comment]
Akamai is now detected.
