### ISSUE TITLE
Error when website is using recaptcha

### ISSUE THREAD

**Issue by TomPradat** [AliasIO/Wappalyzer#2431]
**Do you want to request a *feature*, a *new application detection* or report a *bug*?**

Report a bug

**Is your issue about WebExtension driver (Chrome & Firefox), the website, the NPM driver or the bookmarklet ?**

I'm using the Chrome extension (version 5.5.3) on Chrome Version 68.0.3440.106

**What is the current behavior ?**

I'm having the following errors in my console when using recaptcha with the wappalyzer extension on. 
<img width="920" alt="capture d ecran 2018-08-24 a 13 25 52" src="https://user-images.githubusercontent.com/16164512/44582367-b864ff00-a7a1-11e8-8b72-39bb2d8c42da.png">

**If the current behavior is a bug, please provide the steps to reproduce and if possible a demo of the problem.**

Go on https://www.google.com/recaptcha/intro/v3beta.html with wappalyzer extension on.

**What is the expected behavior ?**

Not have an error in the console.

**Which versions of Wappalyzer, and which browser / OS are affected by this issue ? Did this work in previous versions ?**

I don't know

**Comment by jvoisin** [comment]
I can't reproduce this with firefox.

**Comment by Ahmdrza** [comment]
I have these in chrome.

**Comment by rondog** [comment]
I also am having this issue in chrome
