### ISSUE TITLE
Request a Feature on discover Netlify

### ISSUE THREAD

**Issue by SukkaW** [AliasIO/Wappalyzer#2434]
**Do you want to request a *feature*, a *new application detection* or report a *bug*?**

feature.

**What is the current behavior ?**

Wappalyzer can't recognize the website hosted on [Netlify](https://www.netlify.com)

**What is the expected behavior ?**

Netlify server has 2 specified Response Header: `server: Netlify` and `x-nf-request-id`

**Which versions of Wappalyzer, and which browser / OS are affected by this issue ? Did this work in previous versions ?**

5.5.3

**Comment by semoal** [comment]
Actually this feature it's already implemented.
Web Server category.

**Comment by SukkaW** [comment]
@semoal There are some page using cloudflare or anything else in front of the Netlify, the response header `server: Netlify` will be overridden. The other response header `x-nf-request-id` may be more accurate.
That why I open this issue.

**Comment by marataziat** [comment]
Can you also add 404-page detection? Netlify's 404 pages are usually the same: https://mkhitaryan.me/fdfasdfasdf https://docs.phalconphp.com/ru/3.4 so you can add detection

**Comment by jvoisin** [comment]
Nope: wappalyzer doesn't do requests on its own.
