### ISSUE TITLE
sudo ./run links command is showing errors in ubantu

### ISSUE THREAD

**Issue by dharmatv** [AliasIO/Wappalyzer#2436]
**Do you want to request a *feature*, a *new application detection* or report a *bug*?**

**Is your issue about WebExtension driver (Chrome & Firefox), the website, the NPM driver or the bookmarklet ?**

**What is the current behavior ?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a demo of the problem.**

**What is the expected behavior ?**

**Which versions of Wappalyzer, and which browser / OS are affected by this issue ? Did this work in previous versions ?**

**Comment by dharmatv** [comment]
npm WARN wappalyzer No repository field.
npm WARN wappalyzer No license field.

audited 368 packages in 4.085s
found 0 vulnerabilities

npm notice created a lockfile as npm-shrinkwrap.json. You should commit this file.
npm WARN webextension No description
npm WARN webextension No repository field.
npm WARN webextension No license field.

audited 1 package in 3.349s
found 0 vulnerabilities



   ╭───────────────────────────────────────────────────────────────╮
   │                                                               │
   │      New minor version of npm available! 6.1.0 -> 6.4.0       │
   │   Changelog: https://github.com/npm/npm/releases/tag/v6.4.0   │
   │               Run npm install -g npm to update!               │
   │                                                               │
   ╰───────────────────────────────────────────────────────────────╯

npm notice created a lockfile as npm-shrinkwrap.json. You should commit this file.


   ╭───────────────────────────────────────────────────────────────╮
   │                                                               │
   │      New minor version of npm available! 6.1.0 -> 6.4.0       │
   │   Changelog: https://github.com/npm/npm/releases/tag/v6.4.0   │
   │               Run npm install -g npm to update!               │
   │                                                               │
   ╰───────────────────────────────────────────────────────────────╯

audited 198 packages in 8.87s
found 0 vulnerabilities

npm notice created a lockfile as npm-shrinkwrap.json. You should commit this file.
patching file src/drivers/npm/node_modules/zombie/lib/document.js
Hunk 1 FAILED 281/281.
       // The current window, postMessage and window.close need this
       browser._windowInScope = window;
       var result = undefined;
-      if (typeof code === 'string' || code instanceof String) result = VM.runInContext(code, window, { filename: filename });else if (code) result = code.call(window);
+      if (typeof code === 'string' || code instanceof String) result = VM.runInContext(code, window, { filename: filename, timeout: 1000 });else if (code) result = code.call(window);
       browser.emit('evaluated', code, result, filename);
       return result;
     } catch (error) {
Creating links...
Done.
Creating links...
Done.

**Comment by dharmatv** [comment]
Errors are showing above

**Comment by semoal** [comment]
I think the problem is the original code, located on:

> +++ src/drivers/npm/node_modules/zombie/lib/document.js	2018-04-20 14:34:25.699317000 +1000

Has changed, so the patch is outdated because on line 281 it is not the currently lines of patch. 

Technically the patch should look something like this: 

```
> --- src/drivers/npm/node_modules/zombie/lib/document.js	2018-04-20 14:36:04.097829977 +1000
> +++ src/drivers/npm/node_modules/zombie/lib/document.js	2018-04-20 14:34:25.699317000 +1000
> @@ -245,7 +245,7 @@
>       // The current window, postMessage and window.close need this
>       browser._windowInScope = window;
>       let result;
>       if (typeof code == 'buffer' || code instanceof Buffer) code = code.toString();
> -     if (typeof code === 'string' || code instanceof String) result = VM.runInContext(code, context, { filename });else if (code) result = code.call(window);
> +     if (typeof code === 'string' || code instanceof String) result = VM.runInContext(code, window, { filename: filename, timeout: 1000 });else if (code) result = code.call(window);
>       browser.emit('evaluated', code, result, filename);
>       return result;
>     } catch (error) {
> 
```
Anyways, the issue didn't disappear yet but i'll look more closely this afternoon!

**Comment by jvoisin** [comment]
Why would you run this with sudo!?

**Comment by dharmatv** [comment]
Thanks for reply! 

for permissions purpose in Ubuntu

**Comment by RamyHegazy** [comment]
@dharmatv  I have the same error with mac and Ubuntu.

**Comment by gnowland** [comment]
This is again related to the file `zombie-vm-timeout.patch` in the `./patches/` directory, which is outdated. Removing the patch file resolves the error, although it is unclear as to whether the `timeout: 1000` that was being added by that patch is ultimately necessary... if @AliasIO could comment on the relevance of 3fdd32f that would be great.

**Comment by th0rgall** [comment]
I'm also still having this issue on Mac OS X.
