### ISSUE TITLE
detect some technologies and also especially doesn't detect social links(like facebook) 

### ISSUE THREAD

**Issue by dharmatv** [AliasIO/Wappalyzer#2439]
**Do you want to request a *feature*, a *new application detection* or report a *bug*?**

**Is your issue about WebExtension driver (Chrome & Firefox), the website, the NPM driver or the bookmarklet ?**

**What is the current behavior ?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a demo of the problem.**

**What is the expected behavior ?**

**Which versions of Wappalyzer, and which browser / OS are affected by this issue ? Did this work in previous versions ?**

**Comment by dharmatv** [comment]
when i am run this command(sudo docker run --rm wappalyzer/cli website_name) in ubantu terminal. It will show only some technologies and especially social links are doesn't show.

**Comment by jvoisin** [comment]
We'll need more details.

**Comment by dharmatv** [comment]
Thanks for reply 
I did Wappalyzer repository clone into my local system, and tested by using terminal in Ubuntu , In that terminal shows json after run sudo ./run links, In that json shows only some technologies and also there is no social links, Please reply as soon as possible

**Comment by jvoisin** [comment]
Wappalyzer detects technologies used by the website. It's normal that it doesn't detect "social links".
What do you mean "only some technologies"? What are the ones that you have, the ones that are expected, …

**Comment by dharmatv** [comment]
For example consider  **Zoho Crm** website, result will like 

**Terminal(git hub repository)**

Drupal,Google Tag Manager,PHP,meta                       



**Wappalyzer website:**


(Terminal)+
goole analytics,Amazon cloudfront, Gravatar, Twitter, Font Awesome, ReactGoogle Font API, Youtube, Google Plus, Yoast SEO, Wordpress, Jquery, Jquery UI, Mysql, Modernizr, Bootstrap, Jquery Migrate, Prism, Facebook, TwitterEmoji.

**Comment by dharmatv** [comment]
Thanks for reply
