### ISSUE TITLE
Chrome console error: iframe.js:143 Uncaught SyntaxError: Unexpected token )

### ISSUE THREAD

**Issue by kester36** [AliasIO/Wappalyzer#2448]
Bug:
Google Chrome dev-tools console shows error:
``` iframe.js:143 Uncaught SyntaxError: Unexpected token ) ```

How to fix:
Delete coma in _Wappalyzer/src/drivers/webextension/js/lib/iframe.js_
https://github.com/AliasIO/Wappalyzer/blob/f5a77f3453c796c66f3e597fb30edbc3e2a285c8/src/drivers/webextension/js/lib/iframe.js#L142

**Comment by kester36** [comment]
fixed in PR: https://github.com/AliasIO/Wappalyzer/pull/2449

**Comment by AliasIO** [comment]
Thank you.
