### ISSUE TITLE
Extend JS Detection beyond global variables?

### ISSUE THREAD

**Issue by developit** [AliasIO/wappalyzer#2450]
Hi there! 👋 

JavaScript libraries bundled via Webpack or Rollup generally don't expose or leak any variables into global scope. Given the prevalence of bundling, this seems like it might make a good case for extending Wappalyzer's [current JS detection approach](https://github.com/AliasIO/Wappalyzer/blob/f5a77f3453c796c66f3e597fb30edbc3e2a285c8/src/drivers/webextension/js/inject.js#L3) to allow more than global nested property access.

I'd love to help out with this, assuming we can agree on a detection strategy that works across the existing 3 drivers.  For the DOM drivers (extension and bookmarklet), it seems like a TreeWalker strategy would be useful. This would allow detection to define DOM properties or attributes that signal the presence of Elements rendered by a particular framework or library.

In terms of an implementation, there are two possible approaches one could take. First, a single complete TreeWalker pass could invoke a precomputed list of DOM property detection rules derived from the full Wappalyzer detection config.  This has the advantage of using only a single TreeWalker, but the drawback is that a complete traversal is always required in order to ensure there are no false negatives.

A second approach (and one I'm curious to benchmark) would be to create a TreeWalker for each detection rule.  This specialized traversal using the filter predicate would potentially be faster, and has the advantage of being able to traverse only until the first match is discovered.

Here's a rough sketch of what the first approach might look like:

```js
const rules = {
  preact: {
    dom: node =>  '__preactattr_' in node
  },
  vue: {
    dom: node => '_isVue' in node
  }
];

executeDomFilters(rules);

function executeDomFilters(rules) {
  const getDomFilter = name => rules[name].dom;
  const names = Object.keys(rules).filter(getDomFilter);
  const filters = names.map(getDomFilter);
  const found = [];
  function testNode(node) {
    for (let i=0; i<names.length; i++) {
      const name = names[i];
      const filter = filters[i];
      if (filter(node)) {
        found.push(name);
        names.splice(i, 1);
        filters.splice(i, 1);
      }
    }
  }
  const treeWalker = document.createTreeWalker(document.body, 3, testNode);
  while (names.length > 0 && treeWalker.nextNode());
}
```

/cc @igrigorik @rviscomi

**Comment by igrigorik** [comment]
@AliasIO wdyt? Would love to see this happen.

**Comment by jvoisin** [comment]
I'm a bit afraid of the performance issues :/

**Comment by justinfagnani** [comment]
@developit make sure any approach traverses into ShadowRoots. And of course this won't work with closed ShadowRoots at all.

**Comment by AliasIO** [comment]
Sorry for the late reply. This is interesting. For a while now I've been thinking of using query selectors instead of regular expressions for HTML but it looks like the TreeWalker API is more suited? I'm not familiar with it.

**Comment by developit** [comment]
@AliasIO I think the key is that TreeWalker provides the ability to query arbitrary element properties rather than just attributes. In the example above, neither `__preactattr_` or `__isVue` could be detected using `querySelector` since they are not exposed as attributes.

@justinfagnani no solution will work with closed shadow roots, since the detector is injected too late to patch `Element.prototype.attachShadow` and only has access to DOM APIs.

**Comment by rviscomi** [comment]
Bumping this thread. I think @developit's proposal would mend a significant blind spot in the detector. Especially when running this tool at scale (https://almanac.httparchive.org/en/2019/javascript#frameworks-and-ui-libraries), the false negatives may affect our analysis.

@AliasIO it sounds like you're open to it. Is the next step for @developit to draft a PR? (assuming he has time to work on this?)

**Comment by AliasIO** [comment]
@rviscomi @developit A PR would be awesome. I'm adding this to my own backlog but I'm not sure when I'll get around to doing it.

**Comment by rviscomi** [comment]
Another idea, @developit if you could write a JS snippet that more reliably detects a few sample frameworks (React, Preact, Vue) we can add that as a custom metric to HTTP Archive's February crawl to get a better sense of the scope of the blind spot. It'd also be super useful to have a few sample URLs of pages that are know to be built with these tools but fail to be detected by Wappalyzer.

**Comment by AliasIO** [comment]
Finally picking this up again.

I'm not a fan of the idea of probing every single node but we may not need to. I added a new 'dom' inspection method that uses query selectors in ea27dce1a374b88588ad05447cb1d7da2cc714a7 (NPM driver only for now). This lets us inspect text content, attributes and properties of any element.

I believe React.js and Vue.js apps will often have a root container with ID `app` or `root`. We can look for those specifically, or even just `body > div`.

```json
"dom": {
  "#root": {
    "properties": {
      "_reactRootContainer": ""
    }
  }
}
```

This successfully identifies React on pages where it didn't before.

Thoughts?

**Comment by rviscomi** [comment]
Thanks @AliasIO that sounds really promising!

@developit WDYT?

**Comment by developit** [comment]
That check will only work on applications that happen to render an element with that ID. It's possible that works for Create React App, but not in the general case, and would be fairly easily broken by an update to any popular React-associated tool. 

A thought: walking the DOM isn't terribly expensive if done one time and only over Element nodes. The various detectors could provide information like your descriptor, which could be collected into a single set of conditions that get evaluated on each node by a tree walker. This would also allow any mutually-exlusive detections (if thats a thing) to terminate the tree walk. Already-detected frameworks could be skipped by the visitor, which would reduce the performance impact for common root cases like what you showed above. 

One additional option would be to define separate "stable" and "fast" detectors. The fast detectors could check for properties on known root nodes (document.body.children would be a relatively good start). If a fast detection is triggered, it's corresponding stable detection would then be bypassed.

**Comment by AliasIO** [comment]
@developit What about `body > div`?

I'll have a go the method you're suggesting. I'm already doing something similar to check JS variables and properties.

**Comment by rockeynebhwani** [comment]
@AliasIO - What's the latest on this?

**Comment by AliasIO** [comment]
I may be missing something but I believe the current `dom` method covers everything.

**Comment by developit** [comment]
@rviscomi it satisfies the most common case. Implementing Preact detection required using 4 selectors, which causes 4 querySelector invocations that likely take longer to execute than a partial recursive tree walk, but it does mean detection searches up to 4 nodes deep within `<body>`.

It still won't find things like Svelte components or "islands" unless otherwise marked by an attribute, since there's limited likelihood of them being found at the root of the DOM.
