### ISSUE TITLE
Wrong Front-End framework detection

### ISSUE THREAD

**Issue by developerk001** [AliasIO/Wappalyzer#2451]
![screenshot 11](https://user-images.githubusercontent.com/27365475/45447589-b7175a00-b6ef-11e8-8340-40795ada21a6.png)
**It Should show react but showing angular in udemy.com??**

**Comment by semoal** [comment]
If you see Source Code, you will see there's more information about AngularJs on sources, than React.
Probably they're using a small react component on the website, that's why react extension detects it.
In my opinion, is not a bug. The website is mostly done with Angular

**Comment by developerk786** [comment]
![screenshot from 2018-09-13 15-36-03](https://user-images.githubusercontent.com/27365475/45481242-c5ef2280-b76a-11e8-8af0-d687a94cfe01.png)
Then what about this sir, its saying Javascript framework react but the react dev tool by facebook(correct me if i am wrong) saying react not detected?
