### ISSUE TITLE
Detection on Jiasule CDN

### ISSUE THREAD

**Issue by SukkaW** [AliasIO/Wappalyzer#2454]
**Do you want to request a *feature*, a *new application detection* or report a *bug*?**

New application detection

**What is the expected behavior ?**

The detection on a CDN service

**Which versions of Wappalyzer, and which browser / OS are affected by this issue ? Did this work in previous versions ?**

Chrome 71 in Windows, Webappalyzer 5.5.3

----

The [Jiasule CDN](https://www.yunaq.com/jsl/) is a China CDN Provider providing Anti-DDoS & WAF services. Here is an example of website using Jiasule CDN.

- https://www.yunaq.com/ - The CDN provider's own website
- https://static.yunaq.com/ - The CDN provider's static service which is also run on Jiasule CDN
- https://www.ipip.net & https://tools.ipip.net - The website that using Jiasule CDN

----

There is a way to detect Jiasule CDN:

The response header: `X-Via-JSL`

**Comment by AliasIO** [comment]
This should be fixed in the most recent version, thanks.
