### ISSUE TITLE
Discrepency between chrome extension and website results

### ISSUE THREAD

**Issue by ChillarAnand** [AliasIO/Wappalyzer#2464]
I am checking tech stack of https://avilpage.com

In chrome extension, it is showing only 6 tools.
![screenshot from 2018-09-28 08-06-46](https://user-images.githubusercontent.com/4463796/46185004-cd2f3800-c2f5-11e8-964f-161df470018d.png)

In website, it is showing a lot of tools.
![screenshot from 2018-09-27 19-54-54](https://user-images.githubusercontent.com/4463796/46185013-d4eedc80-c2f5-11e8-85d4-a6f8d3fdcc1c.png)

Is it possible to get these in browser extension?

**Comment by sir-dunxalot** [comment]
Could be related to #2421.

**Comment by kyletaylored** [comment]
Closing to redirect in favor of #2375 (more concise info there).
