### ISSUE TITLE
Address bar icons are sometimes invisible in Firefox dark theme

### ISSUE THREAD

**Issue by jschrab** [AliasIO/Wappalyzer#2469]
**UX Bug - WebExtension driver (Firefox)** 

**What is the current behavior ?**
On macOS Mojave, Firefox 62.0.2 Dark Theme, the Wordpress icon (for sites that should report it) is invisible. There may be other icons that exhibit this behavior.

Using Wappalyzer Firefox extension 5.5.3

**What is the expected behavior ?**

Site feature icons should respond to browser/OS theme changes and always be visible.

**Comment by AliasIO** [comment]
I don't want to maintain two sets of icons, if there are any icons that are particularly problematic we can try finding a version that works on both light and dark backgrounds. Please submit a pull request if you'd like to help with that.
