### ISSUE TITLE
Version Tag Inconsistencies

### ISSUE THREAD

**Issue by kingthorin** [AliasIO/Wappalyzer#2472]
https://www.wappalyzer.com/docs/specification outlines a special syntax for use in version tags. However apps.json contains seemingly inconsistent application for the format.

Ex:
https://github.com/AliasIO/Wappalyzer/blob/master/src/apps.json#L7971
`"<meta [^>]*(?:content=\"([^\"]+)[^>]+ id=\"rlAppVersion\"|id=\"rlAppVersion\"[^>]+ content=\"([^\"]+))\\;version:\\1?\\1:\\2"`

https://github.com/AliasIO/Wappalyzer/blob/master/src/apps.json#L8861
`"(?:(shopware)|/web/cache/[0-9]{10}_.+)\\.js\\;version:\\1?4:5"`

<sub>Note: those are just examples, there are plenty of others.</sub>

Should the place values be escaped (double slash)? Which form is "correct"? The spec seems to suggest the shopware version is what's expected, however, apps.json seems inconsistent.

**Comment by jvoisin** [comment]
The two forms are valid:
the first one will show matches (either the first, or the second one) as the version number, the second will show `4` as the version number if there is a match, `5` otherwise.

**Comment by kingthorin** [comment]
So `1?1:2` and `1?\\1:\\2` are equivalent?

**Comment by jvoisin** [comment]
No: `\1` is a [backreference]( https://en.wikipedia.org/wiki/Regular_expression#backreferences ) in the regex world, and since the regexp is embeded in json, the `\` has to be escaped, hence `\\1`

**Comment by kingthorin** [comment]
Ok thanks.
