### ISSUE TITLE
SweetAlert is detected instead of SweetAlert2

### ISSUE THREAD

**Issue by limonte** [AliasIO/Wappalyzer#2484]
**Do you want to request a *feature*, a *new application detection* or report a *bug*?**

Bug.

**Is your issue about WebExtension driver (Chrome & Firefox), the website, the NPM driver or the bookmarklet ?**

WebExtension driver (Chrome)

**What is the current behavior ?**

On the official page of SweetAlert**2** https://sweetalert2.github.io/ SweetAlert**2** is not detected, instead SweetAlert is detected:

![image](https://user-images.githubusercontent.com/6059356/46579542-d36f9380-ca1c-11e8-9fa4-974e26cce6e7.png)

**What is the expected behavior ?**

On the official page of SweetAlert**2** https://sweetalert2.github.io/ SweetAlert**2** is should be detected.

**Technical background**

Here's the related code: https://github.com/AliasIO/Wappalyzer/blob/master/src/apps.json#L9541-L9565

Wappalyzer should iterate SweetAlert first, detect it because there's `window.swal`. After that SweetAlert2 should be detected because there's `window.Sweetalert2`. Also, because there's `"excludes": "SweetAlert"` in `SweetAlert2`, `SweetAlert` should be excluded.

**Which versions of Wappalyzer, and which browser / OS are affected by this issue ? Did this work in previous versions ?**

Brave Version 0.56.2 Chromium: 70.0.3538.35 (Official Build) dev (64-bit)
Wappalyzer 5.5.5

**Comment by jvoisin** [comment]
I can't reproduce this behaviour here, with Wappalyzer 5.5.5 and Chromium:

![]( http://i.imgur.com/CTFTRbm.png )

**Comment by limonte** [comment]
Hm, looks like a false alarm, sorry. Now everything works fine for me both in Chrome and Brave.

Thanks @jvoisin  for the quick reply!
