### ISSUE TITLE
Incapsula protection breaks html detection

### ISSUE THREAD

**Issue by cachrisman** [AliasIO/Wappalyzer#2485]
**Do you want to request a *feature*, a *new application detection* or report a *bug*?**

Bug

**Is your issue about WebExtension driver (Chrome & Firefox), the website, the NPM driver or the bookmarklet ?**

WebExtension driver

**What is the current behavior ?**

html parsing and detection doesn't work on sites with Incapsula protection.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a demo of the problem.**

Navigate to https://www.cmhheli.com/
Contentful should be detected, but isn't.

**What is the expected behavior ?**

If I copy the html of the webpage from the DevTools, save it as an html page, serve it locally, and view it, then Contentful is detected.

**Which versions of Wappalyzer, and which browser / OS are affected by this issue ? Did this work in previous versions ?**

Wappalyzer v5.5.5
Chrome 69.0.3497.100
Firefox Quantum 62.0.3
macOS 10.13.6

Unknown if this previously worked.

**Comment by jvoisin** [comment]
I can reproduce on Firefox and the latest (5.5.5) wappalyzer

**Comment by AliasIO** [comment]
Fixed in 9ce95a665da09902d8abadb47f4970e12f9e5876, thanks!
