### ISSUE TITLE
Breaks login to bitbucket

### ISSUE THREAD

**Issue by joeytwiddle** [AliasIO/Wappalyzer#2489]
**Do you want to request a *feature*, a *new application detection* or report a *bug*?**

Bug

**Is your issue about WebExtension driver (Chrome & Firefox), the website, the NPM driver or the bookmarklet ?**

Chrome extension (might also happen in Firefox)

**What is the current behavior ? If the current behavior is a bug, please provide the steps to reproduce and if possible a demo of the problem.**

If I go to https://bitbucket.com/ and try to log in, after submitting my password, Bitbucket takes me to a page that reports "You sent a malformed request" (or some similar error message).

If I turn off Wappalyzer, I can log in fine.

**Which versions of Wappalyzer, and which browser / OS are affected by this issue ? Did this work in previous versions ?**

I am using version 5.5.5 in Google Chrome 69 on macOS. I'm sorry I don't know when this started breaking.

**Comment by AliasIO** [comment]
Are you still having this issue? I can't reproduce it.
