### ISSUE TITLE
Issue with Wappalyzer logo visibility in Chrome

### ISSUE THREAD

**Issue by reheda** [AliasIO/Wappalyzer#2490]
I am using Wappalyzer extension (v 5.5.5) in Chrome (Version 69.0.3497.100 (Official Build) (64-bit)) on my Mac (macOS High Sierra 10.13.6 (17G65)).
I prefer using Wappalyzer logo instead technology icon, so I've unchecked the proper checkbox in the options. But every time I reload my Chrome, technology icon goes visible instead of Wappalyzer logo.

**Do you want to request a *feature*, a *new application detection* or report a *bug*?**
report a bug

**Is your issue about WebExtension driver (Chrome & Firefox), the website, the NPM driver or the bookmarklet ?**
issue about WebExtension driver

**What is the current behavior ?**
Wappalyzer logo changed to technology icon after reloading Chrome

**If the current behavior is a bug, please provide the steps to reproduce and if possible a demo of the problem.**
Go to Wappalyzer options, uncheck checkbox  "Use technology icon instead of Wappalyzer logo", reload Chrome.
demo GIF : https://gfycat.com/TenderNeighboringBudgie

**What is the expected behavior ?**
Wappalyzer logo should be visible instead of technology icon after reloading Chrome.

**Which versions of Wappalyzer, and which browser / OS are affected by this issue ? Did this work in previous versions ?**
This issue was on previous versions (of Chrome and Wappalyzer) too.
Wappalyzer extension (v 5.5.5)
Chrome (Version 69.0.3497.100 (Official Build) (64-bit)) 
Mac (macOS High Sierra 10.13.6 (17G65))

**Comment by AliasIO** [comment]
This should be fixed in the next update.
