### ISSUE TITLE
.well-known/ directory fingerprint

### ISSUE THREAD

**Issue by blshkv** [AliasIO/Wappalyzer#2503]
There are several useful files might be in .well-known directory which can be used for fingerprinting.
The full list of files is here:
https://www.iana.org/assignments/well-known-uris/well-known-uris.xhtml
https://tools.ietf.org/html/rfc5785

You might want to parse this information as well.

**Comment by jvoisin** [comment]
Wappalyzer doesn't perform web requests, so this method is out of scope :/

**Comment by blshkv** [comment]
Ok, no problem. Thanks!
