### ISSUE TITLE
Here some Lead Generation applications tags

### ISSUE THREAD

**Issue by Lnunno76** [AliasIO/Wappalyzer#2538]
Lead Champion : cdn.leadchampion.com/leadchampion.js
Albacross : serve.albacross.com/track.js
Jabmo : b2btagmgr.azalead.com
Lead Forensics : tracker.leadforensics.com
Clearbt : reveal.clearbit.com
Optinmonster : a.optmnstr.com/app/js/api.min.js

Thank you

**Comment by jvoisin** [comment]
Feel free to issue pull-request to implement the detection of everything you linked, the documentation is [here]( https://www.wappalyzer.com/docs/specification ).

I think that it's unlikely that anyone will do it for you, and odds are that this issue will be closed soon™.
