### ISSUE TITLE
Extension does not honor saved settings

### ISSUE THREAD

**Issue by DanH42** [AliasIO/Wappalyzer#2559]
This is a more general issue covering the likely cause of #2490 and #2531.

I dislike all of Wappalyzer's default options (notify on update, use technology icon, send analytics to developer), so I have them all disabled. However, I still sometimes get notified when a new version is installed, and I often see technology icons being used in place of the generic Wappalyzer logo. Further investigation revealed that the extension is also sending tracking data back to the developers. When I visit the options page on chrome://extensions, all options still show as disabled.

I've found that re-enabling each option, then re-disabling it, then refreshing each tab I have open seems to correct the issue temporarily, but a few days later the default behavior returns.

**Do you want to request a *feature*, a *new application detection* or report a *bug*?**
Report a bug

**Is your issue about WebExtension driver (Chrome & Firefox), the website, the NPM driver or the bookmarklet ?**
WebExtension (Chrome)

**What is the current behavior ?**
Extension usually (but not always) uses default settings, ignoring user-selected options

**If the current behavior is a bug, please provide the steps to reproduce and if possible a demo of the problem.**
Change options to non-default settings, use the browser for a bit (exact trigger unknown)

**What is the expected behavior ?**
Options chosen by user should always be the ones used

**Which versions of Wappalyzer, and which browser / OS are affected by this issue ? Did this work in previous versions ?**
All recent versions of Wappalyzer for Chrome on multiple OSes

**Comment by dreamerblue** [comment]
Same here.
The technology icon is really noisy and I cannot disable it fully. Sometimes it will reopen but in options it's off! OMG...

**Comment by AliasIO** [comment]
This should be fixed in https://github.com/AliasIO/Wappalyzer/commit/ea900bfd1f1855424f1fd346f3ced47694d8711f#diff-810b4f4b3efe5b5bc0b99ade94beeccc.
