### ISSUE TITLE
The web identifier detects more than via command line

### ISSUE THREAD

**Issue by adon90** [AliasIO/Wappalyzer#2567]
For instance, lets say these 2 websites via web:
-https://confirming.bancopopular.es/ -> IIS 7.5 , ASP.NET
-https://www.bancosantander.es/es/particulares/ -> Liferay

Via command line it doesn't identify those products, the second I can understand, because it doesn't follow redirects (not sure if it's possible) but the first one, why it doesn't identify it? I run the command like this:

`docker run --rm wappalyzer/cli <URL>`

Thank you so much

**Comment by AliasIO** [comment]
By default only the URL you pass is scanned. You need to pass `--recursive=1` to crawl the website.
