### ISSUE TITLE
Wappalyzer classifying a WordPress site referencing a cross domain script on a Drupal site as using both WordPress and Drupal

### ISSUE THREAD

**Issue by billydavies** [AliasIO/Wappalyzer#2570]
**Do you want to request a *feature*, a *new application detection* or report a *bug*?**

Report a bug.

**Is your issue about WebExtension driver (Chrome & Firefox), the website, the NPM driver or the bookmarklet ?**

The NPM driver

**What is the current behavior ?**

Wappalyzer is detecting both Drupal and WordPress for a WordPress site referencing a JavaScript file on a DRupal site at another domain.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a demo of the problem.**

Run Wappalyzer on https://novahealthcare.co.uk/ and see that the site is marked as using both Drupal and WordPress.  In reality that site only uses WordPress but it includes a third party JavaScript file located on a Drupal site (https://www.cqc.org.uk/sites/all/modules/custom/cqc_widget/widget.js?data-id=1-764278383&data-host=www.cqc.org.uk&type=location)

**What is the expected behavior ?**

I would expect Wappalyzer to detect that the site only uses WordPress.

**Which versions of Wappalyzer, and which browser / OS are affected by this issue ? Did this work in previous versions ?**

I tested this using 5.5.5 and also 5.4.3 and the issue was present in both versions.  I am not sure beyond that whether the issue was present or not.

From the looks of it this stems from the 'html' pattern for Drupal matching both absolute and relative asset paths:

"<(?:link|style)[^>]+sites/(?:default|all)/(?:themes|modules)/",

I think that 'real' Drupal sites reference some relative paths to assets natively, e.g. https://www.zodiacmedia.co.uk/, https://www.cla.org.uk/, http://www.bbfc.co.uk/, https://www.aberdeencity.gov.uk, so modifying the check to something like the below would fix this:

"<(?:link|style|script)[^>]+\"/sites/(?:default|all)/(?:themes|modules)/",

I guess strictly speaking that site is using scripts from both WordPress and Drupal so perhaps that is the more correct behaviour, but it is not the expected behaviour for my particular use case.

**Comment by AliasIO** [comment]
Thanks, I'm including your suggested change.
