### ISSUE TITLE
WebExtension opens new tab Every time Firefox starts, reporting update to v5.5.6

### ISSUE THREAD

**Issue by davecoeio** [AliasIO/Wappalyzer#2574]
Firefox 63.0.3 (64-bit)
Arch Linux Kernel Release: 4.19.4

After an automatic update, every time FF is launched, the web extension opens a new tab reporting the new upgrade "Wappalyzer has been upgraded v5.5.6" (https://www.wappalyzer.com/upgraded?v5.5.6).

I've also unchecked "Tell me about upgrades" in WebExtension options and still produces same behaviour.

Also tried a reinstall and deleting browser-extension-data from Firefox profile, producing the same results.

Expecting to be notified once upon upgrade and failing that user preferences "Tell me about upgrades" unchecked would remove all notifications of upgrades.

**Comment by TomaszGasior** [comment]
I can confirm this issue. Very annoying.

**Comment by snydox** [comment]
It is happening to me as well. I reinstalled the extension and the problem persists. I also unchecked "tell me about upgrades." I rebooted the computer many times but no go.

I'm running Ubuntu 18.04 BTW.

**Comment by Darth-Revan** [comment]
Can confirm this issue on both Fedora 28 (64 Bit) with Firefox 63.0.3 and on Windows 10 Enterprise with Firefox 60.3.0esr.

**Comment by xopez** [comment]
Same here

FF 63.0.3
Build-ID: 20181114214635
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0

**Comment by AliasIO** [comment]
Sorry about that. I just pushed another update to fix this. Please check your settings after upgrading to v5.5.7.
