### ISSUE TITLE
Elementor Page builder is shown as CMS Blog and landing page

### ISSUE THREAD

**Issue by csandreas1** [AliasIO/Wappalyzer#2578]
Elementor is just a page builder, why it is shown as blog and cms?
![image](https://user-images.githubusercontent.com/21238024/49688743-25b55980-fb1f-11e8-9f7e-cf692fb24b15.png)
![image](https://user-images.githubusercontent.com/21238024/49688748-32d24880-fb1f-11e8-915c-b23496725452.png)

**Comment by kyletaylored** [comment]
Agreed, this is incorrect, it is only a Landing Page Builder. I'll add a PR to update the categories.
