### ISSUE TITLE
Add custom request matching

### ISSUE THREAD

**Issue by hazcod** [AliasIO/Wappalyzer#2581]
**Do you want to request a *feature*, a *new application detection* or report a *bug*?**
Feature.

**Is your issue about WebExtension driver (Chrome & Firefox), the website, the NPM driver or the bookmarklet ?**
NPM driver.

**What is the current behavior ?**
There is no way to fetch a specific request.

**What is the expected behavior ?**
Some detections require a crafted request to be sent, and matched against a response.
e.g. https://github.com/EnableSecurity/wafw00f/blob/master/wafw00f/plugins/betterwpsecurity.py

So I suggest a 'requests' key in apps.json;
```
"requests": {
    "/wp-content/plugins/better-wp-security/": "HTTP/200",
}
```

**Which versions of Wappalyzer, and which browser / OS are affected by this issue ? Did this work in previous versions ?**
latest, all.

**Comment by kyletaylored** [comment]
This requires extra calls outside of just scanning the response object, which I don't think we'd be building in anytime soon. This functionality could be built in a script around Wappalyzer to embellish the results.
