### ISSUE TITLE
[FR] Import WAFs from wafw00f

### ISSUE THREAD

**Issue by hazcod** [AliasIO/Wappalyzer#2583]
**Do you want to request a *feature*, a *new application detection* or report a *bug*?**
New app detections

Import Web firewalls from wafw00f project: https://github.com/EnableSecurity/wafw00f/tree/master/wafw00f/plugins

**Comment by kyletaylored** [comment]
Some or most of these are already detected, and some of these are only detected when returning an error (403 or auth denied), which isn't really useful to Wappalyzer. Most of these are some kind of CDN or PaaS anyways, so you could PR some of these into the current app list, but not all would be able to be detected.
