### ISSUE TITLE
Bug on widescreen monitor

### ISSUE THREAD

**Issue by mantas-done** [AliasIO/Wappalyzer#2596]
On a widescreen monitor, wappalyzer window is zoomed. Screenshot: https://snag.gy/5kTrKm.jpg
Monitor specs: https://www.lg.com/us/monitors/lg-34UM88-P-ultrawide-monitor

**Comment by kyletaylored** [comment]
Couldn't replicate on very, very wide screen.

**Comment by mantas-done** [comment]
Thanks for looking into it. I think it was fixed several months ago.
