### ISSUE TITLE
"server: ESF" in Google services

### ISSUE THREAD

**Issue by szepeviktor** [AliasIO/Wappalyzer#2604]
What could the `server: ESF` HTTP response header mean in Google services?

> This field should only be used to define system APIs in ESF.

https://cloud.google.com/service-infrastructure/docs/service-management/reference/rest/v1/services.configs

**Comment by kyletaylored** [comment]
Probably "Everyware Software Framework" used as an internal networking tool between API services.

**Comment by denist-huma** [comment]
@szepeviktor 
> ESF is a custom web server developed by Google, and as of early 2022, it is widely in use in the Google ecosystem because out-of-the-box solutions were not enough for YouTube's needs.

Source: https://www.educative.io/courses/grokking-modern-system-design-interview-for-engineers-managers

```sh
$ lynx -head -dump http://www.youtube.com
HTTP/1.0 301 Moved Permanently
Content-Type: application/binary
X-Content-Type-Options: nosniff
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: Mon, 01 Jan 1990 00:00:00 GMT
Date: Thu, 03 Nov 2022 12:05:15 GMT
Location: https://www.youtube.com/
Content-Length: 0
Server: ESF
X-XSS-Protection: 0
X-Frame-Options: SAMEORIGIN
```
