### ISSUE TITLE
[Missing rules] ElasticSearch and AWstats

### ISSUE THREAD

**Issue by CaledoniaProject** [AliasIO/Wappalyzer#2614]
Wappalyze was unable to recognize the following sites:

1. ElasticSearch at http://106.14.150.161:9200/
2. AWstats at https://elix-lsf.fr/index.php?month=all&year=2018
3. cPanel at https://demo.cpanel.net:2083/
4. MyBB at https://www.rooshvforum.com/
5. DirectAdmin control panel at https://ikdirectadmin17.ikoula.com:2222/
6. AfterLogic mail server at http://200.41.191.126/webmail_php/webmail/
7. SonicWall SSL VPN server at https://158.106.88.171/cgi-bin/welcome
8. Golang beego webserver at http://35.180.208.36:8083/

**Comment by jvoisin** [comment]
Pull-requests are more than welcome.
Moreover:
1. http://106.14.150.161:9200/ → This is a webpage with only json on it
2. We have no rules for awstats, but one can always check the footer
3. I added a rule for cpanel in #2616
4. MyBB is detected
5. I'm not a big fan of detecting admin panels on the internet, so I guess it's more a feature than a bug
6. We have no rules for it, feel free to open a PR to add some
7. Same as the previous point
8. Also same as 6.

**Comment by CaledoniaProject** [comment]
I can submit a PR but how do I test this in cli?

**Comment by q--** [comment]
> I'm not a big fan of detecting admin panels on the internet, so I guess it's more a feature than a bug

Wappalyzer does have rules for detecting DirectAdmin, so I'd say it's a bug

https://www.wappalyzer.com/categories/hosting-panels

**Comment by q--** [comment]
> I can submit a PR but how do I test this in cli?

Developer instructions are [here](https://www.wappalyzer.com/docs).

The way I often go about creating Wappalyzer rules is by copy-pasting an existing ruleset from elsewhere in [apps.json](https://github.com/AliasIO/Wappalyzer/blob/master/src/apps.json), editing it to add the right rules, adding an icon and pushing it to GitHub.

If I need to write more complicated regular expressions, I go to https://regex101.com/, set the flavor to ECMAScript, paste the string I want to detect and write my regex so I can see if it's working. Then once I have a working RegEx I [convert it to JSON](https://www.functions-online.com/json_encode.html) and add it to the ruleset.

**Comment by kyletaylored** [comment]
The DirectAdmin detection works, which looks like the only issue listed. I'm going to go ahead and close this to clean up the queue, and any other specific app requests can be re-submitted.
