### ISSUE TITLE
Vue.js not detected despite presence in jsdoc/comments

### ISSUE THREAD

**Issue by Nicnl** [AliasIO/wappalyzer#2620]
### Bug

The Chrome extension is not able to detect Vue.js, despite obvious jsdoc presence in the javascript files.

### Is your issue about WebExtension driver (Chrome & Firefox), the website, the NPM driver or the bookmarklet ?

Tested on the WebExtension (Chrome)  
I presume the Firefox version is also impacted

### Current behavior

Even if the Vue.js version is clearly present and readable in plain text in the JS files,  
Wappalyzer is unable to detect a lot of different Vue.js apps.  

Screenshot of detected libraries:

![image](https://user-images.githubusercontent.com/1387951/52627143-0c30e500-2eb5-11e9-84c4-7928c517c94f.png)

The vendor file, packed with WebPack, contains the following in plain text:

```javascript
[...]
function(t){
/*!
 * Vue.js v2.5.17
 * (c) 2014-2018 Evan You
 * Released under the MIT License.
 */
var e=Object.freeze({});
[...]
```

```javascript
[...]
function(t,n,e){"use strict";
/**
  * vue-router v3.0.1
  * (c) 2017 Evan You
  * @license MIT
  */function r(t,n){0}function i(t){return
[...]
```

### Expected behavior

I feel that, since the javascript file contains obvious jsdoc showing Vue.js is used along with it's version, Wappalyzer should be able to detect it.

It should detect the following:  
- `Vue.js` version `2.5.17`
- `vue-router` version `3.0.1` 

### Which versions of Wappalyzer, and which browser / OS are affected by this issue ?

All of them.  
Tested under chrome on Mac OS X, Windows and Linux.  
Version used: `5.7.3`

### Did this work in previous versions ?

No

**Comment by jvoisin** [comment]
Can you please share a website url so we can easily reproduce your issue?
Also, how are you expecting Wappalyzer to detect the "jsdoc"? Applying a multiline-regexp to every single javascript file doesn't sound like a great idea :/

**Comment by Nicnl** [comment]
Hello,

Thank you for your response, sorry for the delay

I have created an untouched/vanilla hello-world app using Vue.js' official guide  
(https://cli.vuejs.org/guide/creating-a-project.html#vue-create)

You can access it with the following URL:  
https://vue-hello-world.nicnl.com/

**Comment by Nicnl** [comment]
**Additional informations**

![image](https://user-images.githubusercontent.com/1387951/52798105-8f9a3400-3077-11e9-8f6d-4dea8602cf6a.png)

The index.html is not very large:

```html
<!DOCTYPE html>
<html lang=en>
<head>
    <meta charset=utf-8>
    <meta http-equiv=X-UA-Compatible content="IE=edge">
    <meta name=viewport content="width=device-width,initial-scale=1">
    <link rel=icon href=/favicon.ico>
    <title>hello-world</title>
    <link href=/js/about.a40338b8.js rel=prefetch>
    <link href=/css/app.00eb9c76.css rel=preload as=style>
    <link href=/js/app.c35a7418.js rel=preload as=script>
    <link href=/js/chunk-vendors.4a01be28.js rel=preload as=script>
    <link href=/css/app.00eb9c76.css rel=stylesheet>
</head>
<body>
<noscript><strong>We're sorry but hello-world doesn't work properly without JavaScript enabled. Please enable it to
    continue.</strong></noscript>
<div id=app></div>
<script src=/js/chunk-vendors.4a01be28.js></script>
<script src=/js/app.c35a7418.js></script>
</body>
</html>
```

It contains three js files:  
- [`/js/about.a40338b8.js`](https://vue-hello-world.nicnl.com/js/about.a40338b8.js)
- [`/js/app.c35a7418.js`](https://vue-hello-world.nicnl.com/js/app.c35a7418.js)
- [`/js/chunk-vendors.4a01be28.js`](https://vue-hello-world.nicnl.com/js/chunk-vendors.4a01be28.js)

The last one being the vendor files, it contains the following:

```js
/*!
 * Vue.js v2.6.6
 * (c) 2014-2019 Evan You
 * Released under the MIT License.
 */
```

```js
/*!
  * vue-router v3.0.2
  * (c) 2018 Evan You
  * @license MIT
  */
```

_____________________________

**Comment by Nicnl** [comment]
Following your concern

> Also, how are you expecting Wappalyzer to detect the "jsdoc"? Applying a multiline-regexp to every single javascript file doesn't sound like a great idea :/

I must admit that I don't see an immediate solution to this issue.  

I created this issue, because, well...  
Wappalyzer is unable to detect Vue.js in it's most basic form (a hello-world app from the official guide) depite the exact Vue.js version being there, readable in plain text  
As it, it feels a bit too flimsy

As you just said, I'm not sure applying multiple regexes over gigantic js files is a great idea, except for tanking performances  
Maybe writing a piece of code searching for /** using some strpos equivalent would be faster?  
I don't know

**Comment by Nicnl** [comment]
I noticed that the vue-devtools were able to detect the presence of Vue.js without any issues

![image](https://user-images.githubusercontent.com/1387951/52939817-5c042600-3365-11e9-9abe-dad62e5f7011.png)

I wondered how they did this, so I sifted through their code.  
Here is a permalink to their code:  
https://github.com/vuejs/vue-devtools/blob/e34da177b909255a46a13667d63681639672c8a3/shells/chrome/src/detector.js#L10-L51

I'm going to tinker a bit with this and I'll see if I can do something

**Comment by Nicnl** [comment]
Okay, with the following piece of code executed from Chrome's JS console I'm able to detect the Vue.js version.

```javascript
var all = document.querySelectorAll('*');

for (let i=0; i<all.length;i++) {
    if (all[i].__vue__) {
        let Vue = Object.getPrototypeOf(all[i].__vue__).constructor;

        while (Vue.super) {
            Vue = Vue.super;
        }

        if (Vue.version) {
            console.log('Vue.js detected: ' + Vue.version);
            break;
        }
    }
}
```

![image](https://user-images.githubusercontent.com/1387951/52940480-f5800780-3366-11e9-8705-1bd9f4820034.png)

**Comment by Nicnl** [comment]
I'm not familiar at all with Wappalyzer's code.  
If someone here with more knowledge about the project could find a way to integrate this nicely, that would be fantastic.  
I don't trust myself and I'm sure I'll be breaking things if I were to do it.

Paging @jvoisin and @AliasIO

**Comment by Nicnl** [comment]
Okay, I managed to detect **both** Vue.js **and** vue-router.

Sample code:

```javascript
var all = document.querySelectorAll('*');

for (let i=0; i<all.length;i++) {
    if (all[i].__vue__) {
        let vueInstance = all[i].__vue__;

        if (vueInstance.$router) {
            let Router = Object.getPrototypeOf(vueInstance.$router).constructor;
            if (Router.version) {
                console.log('vue-router detected: ' + Router.version);
            }
        }

        let Vue = Object.getPrototypeOf(vueInstance).constructor;

        while (Vue.super) {
            Vue = Vue.super;
        }

        if (Vue.version) {
            console.log('Vue.js detected: ' + Vue.version);
            break;
        }
    }
}
```

![image](https://user-images.githubusercontent.com/1387951/52942056-77256480-336a-11e9-884d-3439095534e2.png)
