### ISSUE TITLE
empty popup

### ISSUE THREAD

**Issue by SabeBarker** [AliasIO/Wappalyzer#2624]
**What is the current behavior ?**
Blank Popup

**If the current behavior is a bug, please provide the steps to reproduce and if possible a demo of the problem.**
Install addon. Close firefox. Open firefox. Navigate to site. Select wappalyzer tech icon in address bar to open popup. Popup is blank.
![wappalyzer-issue](https://user-images.githubusercontent.com/692119/52892621-00cb0b80-318c-11e9-87b1-ac2bf2c16f19.jpg)

**What is the expected behavior ?**
Popup to not be blank and show other tech icons.

**Which versions of Wappalyzer, and which browser / OS are affected by this issue ? Did this work in previous versions ?** Wappalyzer 5.7.3 / Firefox 65.0.1 / Windows 10 - Worked in earlier versions. Not sure how long it hasn't worked for. Addon may have been updated a few times before I noticed. However, I have uninstalled and reinstalled. Restarting firefox at each step.

**Comment by jvoisin** [comment]
Navigate to what site?

**Comment by SabeBarker** [comment]
any site.

**Comment by jvoisin** [comment]
I can't reproduce this :/
Do you have any errors in the console?

**Comment by SabeBarker** [comment]
There are errors in the debug console to do with `firstPartyDomain` as per image.
![wappalyzer-debug-console](https://user-images.githubusercontent.com/692119/53004492-35a7be80-3429-11e9-8c56-df43fa7a0f34.jpg)

**Comment by mhtmht** [comment]
+1 for this issue.

Firefox 65.0.1
Linux(Debian based)
Wappalyzer 5.7.3

First party isolation enabled.

Debug log:
![wappalyzer-firefox-popup](https://user-images.githubusercontent.com/1146203/53012722-8381ee00-344c-11e9-8d19-9d8073a88512.png)

**Comment by SabeBarker** [comment]
I have reproduced this on another device: Wappalyzer 5.7.3 / Firefox 65.0.1 / Windows 10

@mhtmht comment reminds me that I don't run standard settings and have changed many in about:config as per [Firefox: Privacy Related "about:config" Tweaks](https://www.privacytools.io/#about_config)

I have being using settings from privacytools.io for a while now and wappalyzer had no issues up until recently. Hope the extra info helps.

**Comment by bssb** [comment]
@SabeBarker I also had this issue using the about:config settings from privacytools.io.

I "fixed" it by setting `privacy.firstparty.isolate` back to the default value of false. From what I understand, that setting prevents data from being sent to wappalyzer.com for purposes of enumerating the different web technologies being used.

**Comment by SabeBarker** [comment]
Yes this is the issue. I now use First Party Isolation firefox extension to toggle this setting when I want to use wappalyzer. Works for me.
