### ISSUE TITLE
Wrong recognition of Java

### ISSUE THREAD

**Issue by bolinocroustibat** [AliasIO/Wappalyzer#2634]
Wrong recognition of Java on WebExtension driver (Chrome 72, Wappalyzer 5.7.3).
Currently detects Java on my personal website, even though there is absolutely no Java involved.

<img width="479" alt="capture d ecran 2019-03-06 a 23 18 04" src="https://user-images.githubusercontent.com/4353767/53918199-acb69700-4066-11e9-9dec-de0bf9af110f.png">

**Comment by jvoisin** [comment]
Please do provide the address of your website so that we can understand what's going on.

**Comment by bolinocroustibat** [comment]
Sure, sorry, it's https://adriencarpentier.com

**Comment by jvoisin** [comment]
I can't reproduce your issue on Chrome nor Firefox.

**Comment by bolinocroustibat** [comment]
Thanks. Does that mean that it depends on the user client?

**Comment by jvoisin** [comment]
Are you using the latest version of Wappalyzer?

**Comment by bolinocroustibat** [comment]
Yes, 5.7.3 is the latest version
