### ISSUE TITLE
./run links is it not working 

### ISSUE THREAD

**Issue by Sshetty2** [AliasIO/Wappalyzer#2635]
**What is the current behavior ?**

After forking repo and entering home directory ./run links does nothing. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a demo of the problem.**

Clone repo and follow instruction on developer documentation.

**What is the expected behavior ?**

Presumably this is a shell script that will initiate further docker scripts..

**Comment by AliasIO** [comment]
Do you see any output at all? What operating system are you on?

**Comment by Sshetty2** [comment]
Hello, Apologies, this was because the unix commands were apparently not formatted for my machine correctly? 

I am running Windows Linux Subsystem on 64-bit Windows 10

I had to install and run dos2unix then

`$dos2unix ./run`


Now, I'm having problems with configuring docker on the Windows Linux Subsystem, but this is a separate issue that I will resolve. 

Thanks.
