### ISSUE TITLE
Indiscriminate handling of messages in iframe.js

### ISSUE THREAD

**Issue by apokryfos** [AliasIO/Wappalyzer#2638]
**Do you want to request a *feature*, a *new application detection* or report a *bug*?**

Technically request a feature but I do think it's actually a bug. 

**Is your issue about WebExtension driver (Chrome & Firefox), the website, the NPM driver or the bookmarklet ?**

WebExtension driver

**What is the current behavior ?**

The code in function `onPostMessage` in  [iframe.js](https://github.com/AliasIO/Wappalyzer/blob/master/src/drivers/webextension/js/lib/iframe.js#L987) will run on every message posted and run a (slightly) expensive `JSON.parse`. If someone is using a `window.postMessage` heavy page this will have a performance impact. Specifically I was using react-dev-tools while developing a page which seems to be a `postMessage` heavy extension. This resulted in a noticeable performance impact to the react code on heavy component updates.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a demo of the problem.**

Technically I wouldn't say it's a bug 

**What is the expected behavior ?**

Ideally `onPostMessage` should terminate if the event received is not one it should be handling and this should happen before the call to `JSON.parse`. 

**Which versions of Wappalyzer, and which browser / OS are affected by this issue ? Did this work in previous versions ?**

Wappalyzer 5.7.3
Google Chrome  72.0.3626.121
Windows 10

**Comment by AliasIO** [comment]
This will be fixed in the next update, thanks!
