### ISSUE TITLE
Uncaught TypeError: value.hasOwnProperty is not a function

### ISSUE THREAD

**Issue by falstack** [AliasIO/Wappalyzer#2643]
**Do you want to request a *feature*, a *new application detection* or report a bug?**

bug

Is your issue about WebExtension driver (Chrome & Firefox), the website, the NPM driver or the bookmarklet ?

chrome extension： Wappalyzer  5.7.4
chrome version： 73.0.3683.86
website（mobile mode）：[www.jianshu.com](https://www.jianshu.com)

**What is the current behavior ?**

when i open [www.jianshu.com](https://www.jianshu.com), if i open Wappalyzer, i will see：
``` javascript
Uncaught TypeError: value.hasOwnProperty is not a function
```
error at chrome devtool console, when i close Wappalyzer, this error disappear

![image](https://user-images.githubusercontent.com/16357724/54905280-9db35e00-4f1b-11e9-8d7d-225900bf6747.png)

**What is the expected behavior ?**

no error

**Which versions of Wappalyzer, and which browser / OS are affected by this issue ? Did this work in previous versions ?**

chrome extension： Wappalyzer  5.7.4
chrome version： 73.0.3683.86
this error begin long long ago

**Comment by kyletaylored** [comment]
This looks like it's another extension that is affecting Wappalyzer, because there are no `vendor.x.js` scripts included in Wappalyzer as far as I know.
