### ISSUE TITLE
google detects as PHP and opencart

### ISSUE THREAD

**Issue by TheYkk** [AliasIO/Wappalyzer#2650]
**Do you want to request a *feature*, a *new application detection* or report a *bug*?** bug

**Is your issue about WebExtension driver (Chrome & Firefox), the website, the NPM driver or the bookmarklet ?**chrome extension

![image](https://user-images.githubusercontent.com/21688838/55433690-85d47d80-559e-11e9-9c6b-3e91b4948dc2.png)

**Comment by nvma** [comment]
Came here to report the same.

**Comment by kyletaylored** [comment]
My guess is the regex for OpenCart is a little loose. If you just Google "opencart", it'll show up. The issue is the regex for OpenCart is only looking for a link that includes OpenCart.

![image](https://user-images.githubusercontent.com/1759794/56371045-fb0c9900-61c1-11e9-8f4c-f3d3f4cb90ac.png)
