### ISSUE TITLE
Bug - 404 when clicking vuejs button

### ISSUE THREAD

**Issue by NickStees** [AliasIO/Wappalyzer#2654]
When testing a site at [https://www.wappalyzer.com/](https://www.wappalyzer.com/) that uses vue.js for example `gridsome.org` when you click that vuejs button after the test finishes it leads to a 404 https://www.wappalyzer.com/technologies/vuejs

**Comment by NickStees** [comment]
So I found the correct URL the button is supposed to linkto https://www.wappalyzer.com/technologies/vue-js it works properly on [www.wappalyzer.com/categories/javascript-frameworks](https://www.wappalyzer.com/categories/javascript-frameworks)

**Comment by AliasIO** [comment]
Fixed! Thanks.
