### ISSUE TITLE
Web Server vs Web Hosts category

### ISSUE THREAD

**Issue by kyletaylored** [AliasIO/Wappalyzer#2657]
I couldn't find any issue quite related to this, even though some issues touch on it. I wanted to see if there is an interest in adding a new category for Web Hosts in addition to Web Servers.

I work predominantly in the Drupal / WordPress space, so I was starting to add [Pantheon](https://pantheon.io) as a Web Server since their competitor, Acquia Cloud, is listed there as well.

I don't know if we want to nitpick this, but there's a difference between "where" a site is hosted, and "what" the site is being served with.

In the case of Pantheon, they use Nginx as the server, Fastly as the CDN, and generates Let's Encrypt certs on the fly. Acquia uses Apache, Varnish, CloudFlare, and Nginx as a reverse proxy. We can assume almost 95% of the time the applications are PHP (because they only host Drupal and WordPress sites).

But Acquia is listed as a Web Server, but really it uses Apache as the web server, and it's just the host. There's a few others in there that could also be broken out.

|Web Server|Web Host|
|--|--|
|Apache|Acquia Cloud|  
|Nginx|Pantheon|  
|Apache Traffic Server|Netlify|  
|Microsoft IIS|Azure|

**this table isn't one for one, just an example list of each*

Would that make sense to separate the hosting platforms from the server technology they use? I'm a new contributor, but a big fan of Wappalyzer, and hope this makes sense!

**Comment by AliasIO** [comment]
I think Pantheon fits under Hosting Panels. Acquia Cloud, Netlify and Azue are all PaaS providers. I've moved Acquia Cloud into the correct category but feel free to add the 'implied' technologies such as Apache. Thanks!
