### ISSUE TITLE
Bug - No detection for Django CMS

### ISSUE THREAD

**Issue by kyletaylored** [AliasIO/Wappalyzer#2663]
**Do you want to request a *feature*, a *new application detection* or report a *bug*?**
Bug

**What is the current behavior ?**
There is zero detection patterns for Django CMS (was listed under the 2018 projects for removal).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a demo of the problem.**
Go to any Django CMS site, you probably won't see Django CMS, including their website.

https://www.django-cms.org

Will submit PR related to this.

**Comment by kyletaylored** [comment]
Hmm. The simple detection is the header `"x-aldryn-app": "(?:django-cms)"`, but of all the Django CMS samples I'm looking at, most don't expose that.

**Comment by AliasIO** [comment]
I'll leave it in there as a placeholder for now, Django CMS is difficult to identify as you've found. Please let me know if you find a pattern that works.
