### ISSUE TITLE
Add support for global installation

### ISSUE THREAD

**Issue by DanielRuf** [AliasIO/Wappalyzer#2664]
**Do you want to request a *feature*, a *new application detection* or report a *bug*?**

Feature

**Is your issue about WebExtension driver (Chrome & Firefox), the website, the NPM driver or the bookmarklet ?**

NPM

**What is the current behavior ?**

A global install is not possible.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a demo of the problem.**

**What is the expected behavior ?**

A global install should be possible and a binary name should be provided in package.json.

**Which versions of Wappalyzer, and which browser / OS are affected by this issue ? Did this work in previous versions ?**

**Comment by AliasIO** [comment]
`npm i -g wappalyzer` works as expected. What isn't working for you?

**Comment by DanielRuf** [comment]
So far https://github.com/AliasIO/Wappalyzer/blob/master/package.json does not mention the binary name for global installs and has other things missing.

It seems there are completely different things uploaded, see https://unpkg.com/wappalyzer@5.6.3/package.json

Also the docs do not mention the global install. This is very confusing.

**Comment by AliasIO** [comment]
This is the correct file:

https://github.com/AliasIO/Wappalyzer/blob/master/src/drivers/npm/package.json

A binary name isn't required for a global installation. The command I shared before works.

**Comment by DanielRuf** [comment]
> A binary name

Ah, there is the binary name: https://github.com/AliasIO/Wappalyzer/blob/master/src/drivers/npm/package.json#L22

Thanks for the clarification =)

**Comment by DanielRuf** [comment]
Can we add this to the readme?
https://www.npmjs.com/package/wappalyzer
Because `npm i wappalyzer` is a local install.

**Comment by AliasIO** [comment]
Done!
