### ISSUE TITLE
Broken link on Developer Documentation

### ISSUE THREAD

**Issue by armanarr** [AliasIO/Wappalyzer#2666]
There is an issue in the link to the Specification tab on page https://www.wappalyzer.com/docs.

**Do you want to request a *feature*, a *new application detection* or report a *bug*?**
Bug

**Is your issue about WebExtension driver (Chrome & Firefox), the website, the NPM driver or the bookmarklet ?**
The website

**What is the current behavior ?**
Link to Specification in documentation text does not work

**If the current behavior is a bug, please provide the steps to reproduce and if possible a demo of the problem.**
![Image of bug](https://i.ibb.co/8MCgqwR/Screenshot-from-2019-04-16-20-49-48.png)
![Image of bug](https://i.ibb.co/N6mbLKY/Selection-149.png)

**What is the expected behavior ?**
"#" must be replaced by "/", as in the main link to the tab:
![Image of bug](https://i.ibb.co/D9Jdn6y/Screenshot-from-2019-04-16-20-53-02.png)

**Which versions of Wappalyzer, and which browser / OS are affected by this issue? Did this work in previous versions ?**
Browsers:
- Google Chrome Version 73.0.3683.75 (Official Build) (64-bit)
- Firefox Web Browser 66.0.2 (64-bit)

**Comment by AliasIO** [comment]
Thanks! This will be fixed shortly.
