### ISSUE TITLE
Missing site cookies from subdomains

### ISSUE THREAD

**Issue by kyletaylored** [AliasIO/Wappalyzer#2676]
Unsure if bug, feature, or adjustment.

Currently how Wappalyzer searches for cookies is using the literal hostname of the website, that includes the subdomain. This means if a site utilizes a subdomain (www, docs, etc) and shares a cookie between them, we would never be able to detect that cookie.

An example scenario would be a website utilizing an e-commerce system on a subdomain (like shop.example.com), we wouldn't be able to detect that the website is using that technology.

In an example here, you can see that on this website, there are a number of cookies shared on the domain, but Wappalyzer only picks up a fraction of them that are specific to the domain.

If we go to perotmuseum.org, you can see they use `www` as their primary subdomain, and we use that at the domain key for the cookie search.

**Below: using the literal hostname to search for cookies** 
![Screen Shot 2019-04-19 at 1 18 04 PM](https://user-images.githubusercontent.com/1759794/56439774-fb359300-62ac-11e9-9f5f-52cd9e5dac01.png)

But you can see all the relevant cookies that _could be_ keyed off of by trimming the domain to the root domain.

**Below: all cookies related to the root domain** 
![Screen Shot 2019-04-19 at 1 19 29 PM](https://user-images.githubusercontent.com/1759794/56439810-130d1700-62ad-11e9-914f-69d1781fd7e0.png)

**Comment by AliasIO** [comment]
I think `www` is a legitimate case but a website on a `docs` subdomain is likely to use different technologies than the root domain. Sites on subdomains don't typically set cookies on the root domain.
