### ISSUE TITLE
Installing wappalyzer 5.8.0 via npm fails

### ISSUE THREAD

**Issue by lbtuda** [AliasIO/Wappalyzer#2679]
*bug*

Hi, installing wappalyzer 5.8.0 via npm fails with:

npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '.../node_modules/wappalyzer/cli.js'
npm ERR! enoent This is related to npm not being able to find a file.

5.6.3 works.

I think you accidentally deleted the file from the repo.

Best regards 
Lukas

**Comment by AliasIO** [comment]
Fixed, thanks!
