### ISSUE TITLE
Wrong to detect framework

### ISSUE THREAD

**Issue by yulimchen** [AliasIO/Wappalyzer#2680]
**Do you want to request a *feature*, a *new application detection* or report a *bug*?**
bug

**Is your issue about WebExtension driver (Chrome & Firefox), the website, the NPM driver or the bookmarklet ?**
Chrome 

**What is the current behavior ?**
I'm using Vue.js on my website, but Wappalyzer detects my site using React.
![Snipaste_2019-04-22_10-59-29](https://user-images.githubusercontent.com/5179249/56481130-0f1d0700-64f0-11e9-9998-485d803ebfbb.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a demo of the problem.**
I using Vue.js as my web frameworks , and Ant Design Vue as my UI components . Open the site in dev mode.

**Which versions of Wappalyzer, and which browser / OS are affected by this issue ? Did this work in previous versions ?**
Latest.

**Comment by kyletaylored** [comment]
Is there a public version of your site somewhere? It looks like React has some detections that could fire a false-positive. With the detections below, it might be because you're including a script that has "react" in the path name somewhere. Could you confirm any of these?

```json
"React":{  
   "cats":[  
      12
   ],
   "html":"<[^>]+data-react",
   "icon":"React.png",
   "js":{  
      "React.version":"^(.+)$\\;version:\\1",
      "react.version":"^(.+)$\\;version:\\1"
   },
   "script":[  
      "react(?:-with-addons)?[.-]([\\d.]*\\d)[^/]*\\.js\\;version:\\1",
      "/([\\d.]+)/react(?:\\.min)?\\.js\\;version:\\1",
      "react.*\\.js"
   ],
   "website":"https://reactjs.org"
}```

**Comment by yulimchen** [comment]
> Is there a public version of your site somewhere? It looks like React has some detections that could fire a false-positive. With the detections below, it might be because you're including a script that has "react" in the path name somewhere. Could you confirm any of these?
> 
> ```
> "React":{  
>    "cats":[  
>       12
>    ],
>    "html":"<[^>]+data-react",
>    "icon":"React.png",
>    "js":{  
>       "React.version":"^(.+)$\\;version:\\1",
>       "react.version":"^(.+)$\\;version:\\1"
>    },
>    "script":[  
>       "react(?:-with-addons)?[.-]([\\d.]*\\d)[^/]*\\.js\\;version:\\1",
>       "/([\\d.]+)/react(?:\\.min)?\\.js\\;version:\\1",
>       "react.*\\.js"
>    ],
>    "website":"https://reactjs.org"
> }
> ```

I'm sorry , there is no public version of my site . Here is the directory of my site , and the path name doesn't include "react".
![Snipaste_2019-04-22_12-54-25](https://user-images.githubusercontent.com/5179249/56484352-a9397b00-6501-11e9-8ae7-a23bd2c10076.png)

**Comment by kyletaylored** [comment]
Can you check any of those above rules? For example, elements with the attribute "data-react", or global Javascript objects called `React.version`, etc?

**Comment by yulimchen** [comment]
> Can you check any of those above rules? For example, elements with the attribute "data-react", or global Javascript objects called `React.version`, etc?

Elements without the attribute "react" . I have checked the rules just now , the keyword "react.version" was not found in the js file.
![Snipaste_2019-04-22_14-24-02](https://user-images.githubusercontent.com/5179249/56486794-87dd8c80-650b-11e9-989e-3437a597d3ae.png)
![Snipaste_2019-04-22_14-31-24](https://user-images.githubusercontent.com/5179249/56486810-93c94e80-650b-11e9-8faa-e1e276696176.png)
![Snipaste_2019-04-22_14-30-28](https://user-images.githubusercontent.com/5179249/56486818-9cba2000-650b-11e9-9eb4-0f6dd8b46544.png)

**Comment by yulimchen** [comment]
> Is there a public version of your site somewhere? It looks like React has some detections that could fire a false-positive. With the detections below, it might be because you're including a script that has "react" in the path name somewhere. Could you confirm any of these?
> 
> ```
> "React":{  
>    "cats":[  
>       12
>    ],
>    "html":"<[^>]+data-react",
>    "icon":"React.png",
>    "js":{  
>       "React.version":"^(.+)$\\;version:\\1",
>       "react.version":"^(.+)$\\;version:\\1"
>    },
>    "script":[  
>       "react(?:-with-addons)?[.-]([\\d.]*\\d)[^/]*\\.js\\;version:\\1",
>       "/([\\d.]+)/react(?:\\.min)?\\.js\\;version:\\1",
>       "react.*\\.js"
>    ],
>    "website":"https://reactjs.org"
> }
> ```

You can check the same situation as my site . [https://pro.loacg.com/](https://pro.loacg.com/)

**Comment by kyletaylored** [comment]
Oh, I see. It's detecting React because you're using Ant Design, which implies React because it's a React UI library.

https://ant.design/docs/react/introduce

```
{  
   "Ant Design":{  
      "cats":[  
         12
      ],
      "html":[  
         "<[^>]*class=\"ant-(?:btn|col|row|layout|breadcrumb|menu|pagination|steps|select|cascader|checkbox|calendar|form|input-number|input|mention|rate|radio|slider|switch|tree-select|time-picker|transfer|upload|avatar|badge|card|carousel|collapse|list|popover|tooltip|table|tabs|tag|timeline|tree|alert|modal|message|notification|progress|popconfirm|spin|anchor|back-top|divider|drawer)",
         "<i class=\"anticon anticon-"
      ],
      "icon":"Ant Design.svg",
      "implies":[  
         "React"
      ],
      "js":{  
         "antd":""
      },
      "website":"https://ant.design"
   }
}
```

**Comment by yulimchen** [comment]
> Oh, I see. It's detecting React because you're using Ant Design, which implies React because it's a React UI library.
> 
> https://ant.design/docs/react/introduce
> 
> ```
> {  
>    "Ant Design":{  
>       "cats":[  
>          12
>       ],
>       "html":[  
>          "<[^>]*class=\"ant-(?:btn|col|row|layout|breadcrumb|menu|pagination|steps|select|cascader|checkbox|calendar|form|input-number|input|mention|rate|radio|slider|switch|tree-select|time-picker|transfer|upload|avatar|badge|card|carousel|collapse|list|popover|tooltip|table|tabs|tag|timeline|tree|alert|modal|message|notification|progress|popconfirm|spin|anchor|back-top|divider|drawer)",
>          "<i class=\"anticon anticon-"
>       ],
>       "icon":"Ant Design.svg",
>       "implies":[  
>          "React"
>       ],
>       "js":{  
>          "antd":""
>       },
>       "website":"https://ant.design"
>    }
> }
> ```

Ok , But the Ant Design I am using is for Vue.js version. The rules should be changed ...
https://vue.ant.design/docs/vue/introduce/
