### ISSUE TITLE
ASP.NET Core 2.2 detects as Windows Server&IIS

### ISSUE THREAD

**Issue by zhiwen-kooboo** [AliasIO/Wappalyzer#2687]
**Do you want to request a *feature*, a *new application detection* or report a *bug*?**
Bug

**Is your issue about WebExtension driver (Chrome & Firefox), the website, the NPM driver or the bookmarklet ?**
WebExtension in Chrome

**What is the current behavior ?**
I am developing a AspNet Core 2.2 website in Linux but it's recognizing it as Windows Server&IIS

**If the current behavior is a bug, please provide the steps to reproduce and if possible a demo of the problem.**
http://47.100.220.174/

**What is the expected behavior ?**
shouldn't list Windows Server&IIS

**Which versions of Wappalyzer, and which browser / OS are affected by this issue ? Did this work in previous versions ?**
Wappalyzer V 5.8.2 - Chrome V 70.0.3538.102 32bit

**Comment by kyletaylored** [comment]
This is true, and I can find supporting docs for Linux deployment of ASP.NET apps.

https://jakeydocs.readthedocs.io/en/latest/publishing/linuxproduction.html

I think the key here is that when ASP.NET is detected, it implies a 50% confidence that the server running the application is IIS. It's not for sure, but more than likely it is. So it's not wrong, it's just providing a best guess based on the information given.
