### ISSUE TITLE
Sometimes, icons in the upper right area is blank.(firefox65.0.5)

### ISSUE THREAD

**Issue by iamsurfing** [AliasIO/Wappalyzer#2690]
![捕获4](https://user-images.githubusercontent.com/16305191/57568839-4e6bb300-741f-11e9-85fb-21e6a586cdf1.PNG)
![捕获](https://user-images.githubusercontent.com/16305191/57568840-4f044980-741f-11e9-8d33-3b73c711f156.PNG)
![捕获2](https://user-images.githubusercontent.com/16305191/57568841-4f9ce000-741f-11e9-9b8b-8e372e5f1bba.PNG)
![捕获3](https://user-images.githubusercontent.com/16305191/57568842-50ce0d00-741f-11e9-9df3-525642f22977.PNG)

**Comment by kyletaylored** [comment]
Can you provide any console logs (from the background.html) to show if these are having network issues loading, or anything else? Will close for now, but please re-open when you get this data!

![image](https://user-images.githubusercontent.com/1759794/67930305-78f82680-fb8d-11e9-82b9-2f034f37b664.png)
