### ISSUE TITLE
Website and Extension difference in technologies shown

### ISSUE THREAD

**Issue by mitaky** [AliasIO/Wappalyzer#2693]
**Do you want to request a *feature*, a *new application detection* or report a *bug*?**
Bug
**Is your issue about WebExtension driver (Chrome & Firefox), the website, the NPM driver or the bookmarklet ?**
Chrome webExtension and the website

**What is the current behavior ?**
The website shows a full list of technologies used, but not the extension
**If the current behavior is a bug, please provide the steps to reproduce and if possible a demo of the problem.**
Lookup mashines.bg on the website and you will see that they use OpenCart
https://gyazo.com/085896bc509bcdbaa0702460ec2acfb3

Do it from the extension and you don't see OpenCart being used
https://gyazo.com/b1a68b4256a3865364a30d112b9e423a
**What is the expected behavior ?**

**Which versions of Wappalyzer, and which browser / OS are affected by this issue ? Did this work in previous versions ?**
I have Wappalyzer 5.8.2 running on Chrome 74. Did not try previous versions

**Comment by freerider7777** [comment]
Same thing... Extension does not show technologies for facebook.com, tinkoff.ru etc

**Comment by tholst** [comment]
Yes, that's still a problem. I love wappalyzer but this is a show stopper.

## nytimes.com in Chrome Extension

![image](https://user-images.githubusercontent.com/2027794/67634081-e9febc00-f8b7-11e9-9a13-a04f1f31acdd.png)

## nytimes.com on Website (wappalyzer.com)

![image](https://user-images.githubusercontent.com/2027794/67634088-04389a00-f8b8-11e9-8452-d1b15e15fd81.png)

**Comment by kyletaylored** [comment]
Closing to redirect in favor of #2375 (more concise info there).
