### ISSUE TITLE
Wappalyzer says my site uses Ruby (but it doesn't)

### ISSUE THREAD

**Issue by samdutton** [AliasIO/Wappalyzer#2701]
**Do you want to request a *feature*, a *new application detection* or report a *bug*?**
bug

**Is your issue about WebExtension driver (Chrome & Firefox), the website, the NPM driver or the bookmarklet ?**
WebExtension

**What is the current behavior ?**
Wappalyzer extension reports use of Ruby and Ruby on Rails for my site https://simpl.info.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a demo of the problem.**
 Click on Wappalyzer extension icon.

**What is the expected behavior ?**
Wappalyzer would not report use of Ruby.

**Which versions of Wappalyzer, and which browser / OS are affected by this issue ? Did this work in previous versions ?**
Chrome 74.0.3729.157 
Mac OS 10.14.5.

**Comment by samdutton** [comment]
Actually — I think I answered my own question.

The site is using GitHub Pages which (I guess) uses Ruby on Rails.

**Comment by kyletaylored** [comment]
Yep. It's part of the dependency chain, so you can probably close this issue.

**Comment by samdutton** [comment]
Thanks @kyletaylored!
