### ISSUE TITLE
Add detections for all known WordPress hosts

### ISSUE THREAD

**Issue by rviscomi** [AliasIO/Wappalyzer#2703]
**Do you want to request a *feature*, a *new application detection* or report a *bug*?**

Feature

**Is your issue about WebExtension driver (Chrome & Firefox), the website, the NPM driver or the bookmarklet ?**

[apps.json](https://github.com/AliasIO/Wappalyzer/blob/master/src/apps.json)

**What is the current behavior ?**

The [PaaS](https://www.wappalyzer.com/categories/paas) category includes a few known WordPress hosts like Pantheon and WP Engine.

**What is the expected behavior ?**

I'd like to see this expanded to include a more comprehensive list of hosts.

I'm not directly in the WordPress space to know what that ideal list would look like or how to detect each of them, but I'd be very interested to perform analyses on the downstream detections using [HTTP Archive](https://httparchive.org), in which we run Wappalyzer on millions of websites monthly. We're also creating a "[State of CMS](https://github.com/HTTPArchive/almanac.httparchive.org/issues/16)" report in which this could be useful.

Since this research benefits the WordPress industry, I'm hopeful that we can find experts to curate the list of hosts and their corresponding detections.

cc @amedina

**Comment by kyletaylored** [comment]
I added the Pantheon and WP Engine detections since I was working with those at the time, but I wouldn't say I'm in the WP community either 😅.  This issue is very, very open in terms of what should be done on it, but the first step would likely be to either:

1. Start researching popular WordPress hosts and provide that list here, and then make an issue or PR for each. If it's an issue, at least people can check if there's some kind of fingerprint for those platforms.
2. Reach out to the WP community (either the forums, Slack groups, or Twitter?) and see if you can build a list that way.

Other than that, this seems more like a "hey can you do the research AND work for me? thx", so hopefully at least your initial research push can give people things to start working on!

**Comment by rviscomi** [comment]
> Other than that, this seems more like a "hey can you do the research AND work for me? thx", so hopefully at least your initial research push can give people things to start working on!

Yes, I don't want to give the impression that I'm freeloading! For example [here's some research](https://docs.google.com/document/d/1i5VceKSoa95F2W1EZ_OenK0Hb1CeWv6osc2UX_E_qiQ/edit?usp=sharing) I've already done for those unfamiliar. I used Wappalyzer's excellent list of CMSs for the CMS comparison, but had to resort to a manually-curated list of 6 hosts for the host comparison. Would love to see more community contributions for the latter.

**Comment by kyletaylored** [comment]
> Yes, I don't want to give the impression that I'm freeloading! For example [here's some research](https://docs.google.com/document/d/1i5VceKSoa95F2W1EZ_OenK0Hb1CeWv6osc2UX_E_qiQ/edit?usp=sharing)

Totally. And sorry, I wasn't trying to come off as a jerk, it was just a big ask! :)

Actually, I see a few hosts in that list that could get started on:

- Kinsta
- Automaticc (likely WordPress.com or WP VIP?)
- Siteground
- Seravo

Some others that could be added would be:
- Bluehost
- FlyWheel

But most of these would depend on that fingerprints are available, usually only on the managed platforms. Kinsta for example, the only thing I could see that would be detected is if you use their cache/CDN and it exposes a `kinsta-cache` header. But these would be a good start.

**Comment by kyletaylored** [comment]
I couldn't find anything specific / consistent for Siteground or Bluehost, but they're a little more generic hosting anyways.

**Comment by rviscomi** [comment]
Here's an updated file with all of the hosting detection I have so far: https://github.com/rviscomi/ismyhostfastyet/blob/master/ttfb.sql

Siteground is in there with their MD5 hashes. Not ideal but should be uniquely identifiable.

**Comment by kyletaylored** [comment]
I think we have a lot of the WP hosts in here, so I'm going to close this ticket, but feel free to open a new one for any new WP hosts!
