### ISSUE TITLE
add WordPress theme

### ISSUE THREAD

**Issue by Dedi-Data** [AliasIO/Wappalyzer#2710]
Hi,
We created a WordPress theme which it works as a Framework on WordPress
is it possible to add this theme to the source?
https://wordpress.org/themes/free-template/
Free Template is not just a theme but it is a framework for creating any WordPress themes.
Regards

**Comment by kyletaylored** [comment]
A WordPress theme doesn't fit any of the current categories, and is too specific of a thing to detect. There are many, very popular WordPress frameworks like Genesis, Gantry, Roots, etc that aren't added to be detected either.

I would recommend closing this issue.

**Comment by dakshhmehta** [comment]
What if we just read the style.css comment and mention the theme name?

**Comment by Dedi-Data** [comment]
@kyletaylored
So we can add a new category !

**Comment by kyletaylored** [comment]
If they were to add a new category for WordPress themes, you'd have to add detection for a whole host of themes on different frameworks and content management systems, and that just isn't the purpose of Wappalyzer.

I would still recommend closing this ticket. It's meant to be for research, not as an advertising tool.

**Comment by dakshhmehta** [comment]
Could we read the style.css and mention the Theme Name used as additional information.

Maybe how WPScan works...
