### ISSUE TITLE
[BUG] Build 5.8.2 on NodeJS fails on extensions.test()

### ISSUE THREAD

**Issue by FlashT** [AliasIO/wappalyzer#2720]
There is a bug in extensions test in the latest build.

`const extensions = /^([^.]+$|\.(asp|aspx|cgi|htm|html|jsp|php)$)/;`

in reducedLinks definition we got:

```
if (... && extensions.test(link.pathname)) {
}

```
But, it fails for example when link is like:

`http://blablabla.bla/index.php?route=product/category&path=255`

Even when `link.pathname is` just `/index.php`.

Example site: http://hurt-winter.pl
NodeJS v10.16.0

**Comment by kyletaylored** [comment]
Resolved in latest.
