### ISSUE TITLE
No CMS detect

### ISSUE THREAD

**Issue by sracine** [AliasIO/Wappalyzer#2742]
when i run the command docker run --rm wappalyzer/cli https://**** i can't see the CMS in the json response but when i check with the chrome extension i can see the CMS.

Is it a limitation of the docker ?

**Comment by ThomasLohner** [comment]
@sracine This is caused by Zombie.js which is used as a browser in the docker image. You need to use Chromium to fix this. Setup your own project and follow the workaround in #2375.
