### ISSUE TITLE
Please Add Easytax Php Framework

### ISSUE THREAD

**Issue by samtax01** [AliasIO/Wappalyzer#2743]
It is a new framework similar to Laravel but more friendly, Please add support or it. http://easytax.xamtax.com/ and github address is https://github.com/easytax/easytax-framework/

**Comment by kyletaylored** [comment]
This looks private or closed down.

**Comment by samtax01** [comment]
We renamed it to EHEX. And the new repo is https://github.com/ehexphp/ehex-framework
