### ISSUE TITLE
Unchecked runtime.lastError: The message port closed before a response was received.

### ISSUE THREAD

**Issue by craiglondon** [AliasIO/Wappalyzer#2759]
**Do you want to request a *feature*, a *new application detection* or report a *bug*?**
BUG

**Is your issue about WebExtension driver (Chrome & Firefox), the website, the NPM driver or the bookmarklet ?**
Chrome Webextension

**What is the current behavior ?**
When the extension is enabled, every page displays the console error, when the extension is disabled, the error goes away.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a demo of the problem.**
See above

**What is the expected behavior ?**
No console error when the extension is enabled

**Which versions of Wappalyzer, and which browser / OS are affected by this issue ? Did this work in previous versions ?**
This has been around for a few months that I can recall.
MacOS
Chrome
Latest version of Wappalyzer as of 08/28/2019

**Comment by kyletaylored** [comment]
Could you provide a screenshot or screen recording that shows this and re-open the ticket? And if you can, please provide the actual versions for Wappalyzer and Chrome - this helps with debugging!

**Comment by jg2703** [comment]
Happening to me on Chrome 86.0.4240.198 (Official Build) (64-bit) and Windows 10 Pro v20H2 Build 19042.610

Both disabled and enabled images below - as soon as the extension is reenabled this console error shows.

![ExtDisabled](https://user-images.githubusercontent.com/14931301/99045515-60d12a80-2589-11eb-9b0b-08c11885827b.png)
![ExtEnabled](https://user-images.githubusercontent.com/14931301/99045516-6169c100-2589-11eb-9180-22394f0f6e3b.png)

Looks like a few others have found disabling helps them too...https://stackoverflow.com/questions/54126343/how-to-fix-unchecked-runtime-lasterror-the-message-port-closed-before-a-respon#comment114568423_54614440

**Comment by unclescooby** [comment]
Same here, error appears in all tabs.

Windows 10 home (10.0.19041), Chrome 86.0.4240.193 (64bit)

@AliasIO please reopen this issue.
