### ISSUE TITLE
Mapplic detection

### ISSUE THREAD

**Issue by gusdleon** [AliasIO/wappalyzer#2761]
*new application detection*

www.mapplic.com

**What is the current behavior ?**
Mapplic Is not detected

the website [https://www.uanl.mx/campus-ciudad-universitaria/](https://www.uanl.mx/campus-ciudad-universitaria/) contains a map made with Mapplic and is not detected 

**What is the expected behavior ?**
Mapplic is detected
**Which versions of Wappalyzer, and which browser / OS are affected by this issue ? Did this work in previous versions ?**
Wappalyzer 5.8.3
Chrome  76.0.3809.100

**Comment by AliasIO** [comment]
This has been added, thank you.
