### ISSUE TITLE
Extend detection to make requests to admin assets

### ISSUE THREAD

**Issue by vladox** [AliasIO/Wappalyzer#2787]
**Do you want to request a *feature*, a *new application detection* or report a *bug*?**

feature: 

**Is your issue about WebExtension driver (Chrome & Firefox), the website, the NPM driver or the bookmarklet ?**

Webextension: I tried to add Wagtail ([wagtail.io](https://wagtail.io/)) to the detected CMS list but the only way would be to detect its default admin URL or something in it. Without that it's impossible.

here an example: [https://www.crafft.ch/](https://www.crafft.ch/)

**What is the current behavior ?**

Only assets loaded in the page itself are being analyzed.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a demo of the problem.**

**What is the expected behavior ?**

Possibility to do extra requests to detect admin assets 

**Which versions of Wappalyzer, and which browser / OS are affected by this issue ? Did this work in previous versions ?**

Wappalyzer 5.8.4

**Comment by AliasIO** [comment]
For this to work the extension would need to try and access the admin URLs for every known technology, on every website you visit. This would interfere with regular browsing, which is why this hasn't been included.
