### ISSUE TITLE
ExpressJS detection

### ISSUE THREAD

**Issue by atefBB** [AliasIO/Wappalyzer#2796]
Hi, when the `X-Powered-By` header is in `lowercase` (see this [site](https://lableb.com/)) the extension fails to detect `expressjs`, how to fix it?
https://github.com/AliasIO/Wappalyzer/blob/0d714bc347bec8b8d722c6c634bd64f579f95eda/src/apps.json#L3294

**Comment by q--** [comment]
That's odd. As far as I can tell, the bookmarket and webextension driver should [convert all headers to lowercase](https://github.com/AliasIO/Wappalyzer/search?q=tolowercase&unscoped_q=tolowercase) before analyzing them.  
Wappalyzer does detect Express on that site for me (using Wappalyzer 5.8.4 on Firefox).

Are you using the *npm* driver? Or perhaps an outdated version of Wappalyzer?

**Comment by atefBB** [comment]
I'm using the version `5.8.4` of the extension in my `Brave` browser!
The version is outdated?

**Comment by q--** [comment]
Same version as me, so that shouldn't be a problem. Odd how it detects Express for you but not for me.

**Comment by atefBB** [comment]
Maybe an browser issue? You are using Firefox but I'm using Brave.

**Comment by kyletaylored** [comment]
I tried recreating this issue in Chrome, Brave, and Firefox. There are two other things I'll point out as well:

1. Like @q-- mentioned, the headers are all converted to lower case
https://github.com/AliasIO/Wappalyzer/blob/31b71ba45432844261e8e398c1317f70db287fac/src/wappalyzer.js#L607

2. In addition, the regex utilizes the case insensitive setting
https://github.com/AliasIO/Wappalyzer/blob/31b71ba45432844261e8e398c1317f70db287fac/src/wappalyzer.js#L373

When you're using Brave, you **have to make sure** you have your Shield turned off - or else it will block a lot of the detections.
