### ISSUE TITLE
Youtube Opencart detection issue

### ISSUE THREAD

**Issue by engr-ibraheem** [AliasIO/Wappalyzer#2797]
https://www.wappalyzer.com/technologies/opencart
It shows YouTube uses OpenCart. When visiting https://www.youtube.com OpenCart not detected. Looks like a glitch.

**Comment by kyletaylored** [comment]
Make sure you're running the latest Wappalyzer - this issue was fixed recently.

https://github.com/AliasIO/Wappalyzer/issues/2650

**Comment by kyletaylored** [comment]
Closing until validated.
