### ISSUE TITLE
Essential JS 2, false positive on YouTube

### ISSUE THREAD

**Issue by craiglondon** [AliasIO/Wappalyzer#2799]
**Do you want to request a *feature*, a *new application detection* or report a *bug*?**
Bug

**Is your issue about WebExtension driver (Chrome & Firefox), the website, the NPM driver or the bookmarklet ?**
Chrome, Web Extension

**What is the current behavior ?**
False detection

**If the current behavior is a bug, please provide the steps to reproduce and if possible a demo of the problem.**
https://www.youtube.com/watch?v=Z1BCujX3pw8

**What is the expected behavior ?**
Is this a false positive?

**Which versions of Wappalyzer, and which browser / OS are affected by this issue ? Did this work in previous versions ?**
Unknown

**Comment by craiglondon** [comment]
@UmaMaheswariChandrabose
Can you check to see if this is a false positive on Youtube?

**Comment by UmaMaheswariChandrabose** [comment]
> @UmaMaheswariChandrabose
> Can you check to see if this is a false positive on Youtube?

@craiglondon, I have made a commit request to correct that issue in this pull request https://github.com/AliasIO/Wappalyzer/pull/2771

**Comment by craiglondon** [comment]
Thanks @UmaMaheswariChandrabose!
