### ISSUE TITLE
Feature Request: config option to choose between dark and light mode regardless of the browser theme

### ISSUE THREAD

**Issue by 49616e** [AliasIO/wappalyzer#2814]
IMHO currently the dark theme looks very poor, and I'd like to have the ability to revert to light mode without switching the browser theme to a light one.

**Comment by kyletaylored** [comment]
Just added a PR for this, should be fixed soon enough.

**Comment by septatrix** [comment]
This can be closed

**Comment by 49616e** [comment]
> This can be closed

Indeed. Thanks for fixing it Kyle.
