### ISSUE TITLE
Incorrect technologies shown?

### ISSUE THREAD

**Issue by adititipnis** [AliasIO/Wappalyzer#2816]
**Do you want to request a *feature*, a *new application detection* or report a *bug*?**
bug

**Is your issue about WebExtension driver (Chrome & Firefox), the website, the NPM driver or the bookmarklet ?**
WebExtension (Chrome)

**What is the current behavior ?**
https://exchagerates.herokuapp.com/ shows Cowboy, Express, Erlang and Node. But I have built it with React which is never mentioned. Why is that?

**If the current behavior is a bug, please provide the steps to reproduce and if possible a demo of the problem.**
1. Visit https://exchagerates.herokuapp.com/
2. Check techonolgies

**What is the expected behavior ?**
Show React

**Which versions of Wappalyzer, and which browser / OS are affected by this issue ? Did this work in previous versions ?**
Just installed Wappalyzer

**Comment by kyletaylored** [comment]
There are a number of detections available, and different apps have different points of exposure. React, for example, is currently being detected through attributes (`data-react`), JS objects, and loaded scripts. We're always looking to improve the detection of apps, so [feel free to open a PR with additional detections](https://www.wappalyzer.com/docs)!
