### ISSUE TITLE
Hide logo in Firefox?

### ISSUE THREAD

**Issue by w4rner** [AliasIO/Wappalyzer#2821]
**Do you want to request a *feature*, a *new application detection* or report a *bug*?**
Feature

**Is your issue about WebExtension driver (Chrome & Firefox), the website, the NPM driver or the bookmarklet ?**
Firefox Extension

**What is the current behavior ?**
<img width="619" alt="image" src="https://user-images.githubusercontent.com/31451410/68225564-9f1f2b80-ffbe-11e9-93d8-dc3473217e9f.png">

Currently have to have some logo in the side of your address bar at all times. 
<img width="111" alt="image" src="https://user-images.githubusercontent.com/31451410/68225616-b2ca9200-ffbe-11e9-8c03-66df10776e14.png">

Is there a way of hiding the logo entirely? If not, feature request please.

**Comment by kyletaylored** [comment]
I'm not sure what you're asking. The icon represents the popup for the extension that you click to view all of the detected apps. In this screenshot, the Ruby Gem isn't a logo, it's _one of_ the detected apps (Ruby), and when you click it you can see all the Wappalyzer results.

Could you elaborate?

**Comment by AlexByte** [comment]
Do yo want to move extension from panel to menu.

**Comment by w4rner** [comment]
As AlexByte says, I want it so that I don't have to see a visual icon at all times on the browser. 

This is better design: the info from Wappalyzer only needs to be accessed at certain times for specific purpose (actively ascertain the tech stack on a website) and I should be able to bury it a little more.

w4rner

**Comment by AlexByte** [comment]
You can hide extension in forefox using context menu.

**Comment by kyletaylored** [comment]
This is a simple fix within Firefox, see the instructional GIF below.

![Nov-07-2019 23-59-14](https://user-images.githubusercontent.com/1759794/68453269-b7f43080-01ba-11ea-9f6c-42eae2618b07.gif)

**Comment by w4rner** [comment]
> This is a simple fix within Firefox, see the instructional GIF below.
> 
> ![Nov-07-2019 23-59-14](https://user-images.githubusercontent.com/1759794/68453269-b7f43080-01ba-11ea-9f6c-42eae2618b07.gif)

Thanks @kyletaylored: really helpful GIF. This is the first time an extension has appeared in the address bar rather than 'off to the right' for me. Curious, how did you create the GIF btw? I'm often finding myself wanting to share short instructional vids like this, and usually have to share a link to a Dropbox video file, but your approach is way better. What is the longest a GIF can feasibly be?

**Comment by kyletaylored** [comment]
I use the GIPHY app on Mac, but another free service that's pretty good is called [Loom](https://useloom.com).
