### ISSUE TITLE
Pop-up is blank

### ISSUE THREAD

**Issue by stemy2** [AliasIO/wappalyzer#2830]
**Do you want to request a *feature*, a *new application detection* or report a *bug*?**
Report a bug
**Is your issue about WebExtension driver (Chrome & Firefox), the website, the NPM driver or the bookmarklet ?**
Don't know
**What is the current behavior ?**
When i click on the adress bar icon, it give me a blank with no information other than the app name.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a demo of the problem.**
See here above.
**What is the expected behavior ?**
The information promised by the extension.
**Which versions of Wappalyzer, and which browser / OS are affected by this issue ? Did this work in previous versions ?**
Firefox 68.0.2
Trisquel 8 (based on ubuntu xenial)

**Comment by kyletaylored** [comment]
Can you provide a screenshot please? Also, any particular reason why you're using the Bookmarklet over the extension?

**Comment by stemy2** [comment]
I can't take a screenshot, the box disappears when i open the screenshot manager. The exact look of the box is a black header with the icon and the name of the app and the rest is blank.

I wanted to use it by curiosity.

**Comment by kyletaylored** [comment]
I just realized, I think I read that as you were using the Bookmarklet, but that was a misread. Are you using the Firefox extension or the Bookmarklet?

If it's the Bookmarklet, it could be a CORS issue, but you'd have to open your developer console and tell us what errors you see.

**Comment by stemy2** [comment]
The firefox extension.

**Comment by ClemHlrdt** [comment]
Same problem here using Firefox 71.0b9 (64 bits)

**Comment by unixfox** [comment]
Probably the same bug as https://github.com/AliasIO/wappalyzer/issues/2624

**Comment by stemy2** [comment]
> Probably the same bug as #2624

It is. Thanks.
