### ISSUE TITLE
Wappalyzer for Brave Browser

### ISSUE THREAD

**Issue by andrecasal** [AliasIO/Wappalyzer#2843]
I'd like to request the reopening of the [feature request issue for Wappalyzer for the brave browser](https://github.com/AliasIO/Wappalyzer/issues/1542). I can't bump it there because it has been closed to further replies.

Fyi, there are currently [more than 8 million users for the brave browser](https://cointelegraph.com/news/crypto-friendly-browser-brave-hits-8-million-monthly-active-users) and it's growing rapidly.

**Comment by AliasIO** [comment]
You can install Wappalyzer in Brave from the Chrome Web Store:

https://chrome.google.com/webstore/detail/wappalyzer/gppongmhjkpfnbhagpmjfkannfbllamg
