### ISSUE TITLE
Wappalyzer node module hanging

### ISSUE THREAD

**Issue by Rekicho** [AliasIO/wappalyzer#2845]
**Do you want to request a *feature*, a *new application detection* or report a *bug*?**

Report a bug

**Is your issue about WebExtension driver (Chrome & Firefox), the website, the NPM driver or the bookmarklet ?**

NPM driver

**What is the current behavior ?**

After Wappalyzer analyze function promise for website "https://www.gitlab.com/" (maybe also on other websites) fulfills, node sometimes hangs indefinitely. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a demo of the problem.**

This code snippet can be used along with Wappalyzer NPM version 5.8.4 to reproduce the bug:

```
const Wappalyzer = require('wappalyzer');
 
const url = 'https://www.gitlab.com';
   
const wappalyzer = new Wappalyzer(url);

wappalyzer.analyze().then((tech) => console.log(tech));
```

This prints the techonologies but then does not end.

**What is the expected behavior ?**

Node should exit after the promise is fulfilled.

**Which versions of Wappalyzer, and which browser / OS are affected by this issue ? Did this work in previous versions ?**

NPM version 5.8.4

**Comment by Rekicho** [comment]
To add on this, I used [wtf-node](https://www.npmjs.com/package/wtfnode) to try and understand what was lefting hanging and had the following results for open handles after ``analyze`` promise fulfills:

```
- File descriptors: (note: stdio always exists)
  - fd 1 (tty) (stdio)
  - fd 2 (tty) (stdio)
- Sockets:
  - 192.168.1.5:59240 -> 151.101.194.49:443
  - 192.168.1.5:59242 -> 13.107.246.10:443
  - 192.168.1.5:59244 -> 216.58.201.168:443
  - 192.168.1.5:59246 -> 151.101.132.143:443
- Timers:
  - (120000 ~ 2 min) (anonymous) @ [...]\node_modules\zombie\lib\xhr.js:123
  - (120000 ~ 2 min) (anonymous) @ [...]\node_modules\zombie\lib\xhr.js:123
- Intervals:
  - (1000 ~ 1000 ms) bound fire @ [...]\node_modules\zombie\lib\eventloop.js:96
```

**Comment by kyletaylored** [comment]
There is something going on, but the Promise is being resolved. I can look in the process queue and see some pending work, but I don't know why it's getting held up specifically on Gitlab. 

While it's hanging, you can inspect the process queue using `process._getActiveHandles`. Funny enough, if I change the User Agent from `Wappalyzer` to `Chrome`, I actually get more results, so my guess is Gitlab has some kind of WAF to protect against "bots" like Wappalyzer.

**Comment by AliasIO** [comment]
I'm unable to look into it now but i wonder if Zombie.js wasn't patched in this build. 

https://github.com/AliasIO/Wappalyzer/blob/master/patches/zombie-vm-timeout.patch

**Comment by zcaceres** [comment]
Same problem.

**Comment by kyletaylored** [comment]
Fixed in latest release.

**Comment by zcaceres** [comment]
You rock!
