### ISSUE TITLE
bug: extension detects Vue for some reason on Google search results page

### ISSUE THREAD

**Issue by Kurzdor** [AliasIO/Wappalyzer#2847]
**Do you want to request a *feature*, a *new application detection* or report a *bug*?**
Bug

**Is your issue about WebExtension driver (Chrome & Firefox), the website, the NPM driver or the bookmarklet ?**
Chrome extension

**What is the current behavior ?**
Wappalyzer detects Vue on Google search results page.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a demo of the problem.**

**What is the expected behavior ?**
Vue DevTools says that it can't detect any Vue instance on that page  

**Which versions of Wappalyzer, and which browser / OS are affected by this issue ? Did this work in previous versions ?**
MacOS Mojave 10.14.6 / Chrome 78.0.3904.97 / Wappalyzer 5.8.5

![image](https://user-images.githubusercontent.com/19878951/68893907-cf896700-072e-11ea-9285-6a41f7165662.png)

**Comment by ezralazuardy** [comment]
did you have try to clear your chrome cache? (ctrl + shift + R to clean reload the page). i've try your issue, but in my case, there is no vue appear in the wappalyzer's list

**Comment by Kurzdor** [comment]
@ezralazuardy ok, i don't see vue in wappalyzer anymore, but this is strange

**Comment by ezralazuardy** [comment]
i think it's your browser cache error.., maybe you can consider to close this issue?
