### ISSUE TITLE
Not crawling?

### ISSUE THREAD

**Issue by ron-pypl** [AliasIO/Wappalyzer#2855]
**Do you want to request a *feature*, a *new application detection* or report a *bug*?**

report a bug

**Is your issue about WebExtension driver (Chrome & Firefox), the website, the NPM driver or the bookmarklet ?**

NPM

**What is the current behavior ?**

Scans only depth 1

**If the current behavior is a bug, please provide the steps to reproduce and if possible a demo of the problem.**

I used the sample codes from the docs

**What is the expected behavior ?**

If *recursive* is specified, it should crawl the links within the website

**Which versions of Wappalyzer, and which browser / OS are affected by this issue ? Did this work in previous versions ?**

5.8.4

**Comment by AliasIO** [comment]
Fixed in 141750821be2d2f2cff6fd68d25c646e5cd8d9a2 and v5.8.6, thanks!
