### ISSUE TITLE
New icons not showing up on Wappalyzer.com

### ISSUE THREAD

**Issue by q--** [AliasIO/Wappalyzer#2858]
I changed the icons for a few apps to an SVG version in #2824, #2807 and #2811.  The icons show up in the extension, but not on Wappalyzer.com: [VideoJS](https://www.wappalyzer.com/technologies/videojs), [Laravel](https://www.wappalyzer.com/technologies/laravel) and [Symfony](https://www.wappalyzer.com/technologies/symfony).

A new app added recently in #2832 also has no logo on Wappalyzer.com: [Airform](https://www.wappalyzer.com/technologies/airform). The same goes for [MobX](https://www.wappalyzer.com/technologies/mobx) (added in #2823).

[Zimbra](https://www.wappalyzer.com/technologies/zimbra) (#2802), with a PNG logo instead of SVG, won't have its icon show up on the site either. Not all of these have been released as part of a stable build of Wappalyzer, but the VideoJS, Laravel and Zimbra PR's have.

Clicking "show image" on one of the missing icons gives this error page: 

![Error](https://user-images.githubusercontent.com/2470175/69232414-51dcb580-0b8b-11ea-9016-73abbff069a1.png)

**Comment by AliasIO** [comment]
Thanks, that's fixed.
