### ISSUE TITLE
New application detection request: Nextcloud

### ISSUE THREAD

**Issue by Ko-** [AliasIO/wappalyzer#2863]
**Do you want to request a *feature*, a *new application detection* or report a *bug*?**
New application detection.

**Is your issue about WebExtension driver (Chrome & Firefox), the website, the NPM driver or the bookmarklet ?**
WebExtension driver.

**What is the current behavior ?**
Does not detect Nextcloud. (It does detect ownCloud, the project where Nextcloud forked from. I believe that Nextcloud is more popular nowadays in terms of number of users and development activity.)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a demo of the problem.**

**What is the expected behavior ?**
Detect Nextcloud.

**Which versions of Wappalyzer, and which browser / OS are affected by this issue ? Did this work in previous versions ?**
Latest version.

This can be used for detection:
```html
<meta name="apple-itunes-app" content="app-id=1125420102">
```
[GitHub link](https://github.com/nextcloud/server/), [project main website](https://nextcloud.com/), [Wikipedia entry](https://en.wikipedia.org/wiki/Nextcloud).

**Comment by kyletaylored** [comment]
Just adding a few notes for detections here.

**HTML**
```html
<meta name="apple-mobile-web-app-title" content="Nextcloud">
```

**Javascript**
```
nc_lastLogin
nc_pageLoad
```

**Comment by Ko-** [comment]
I don't see this `apple-mobile-web-app-title` on an installation of Nextcloud 16.0.3. But `nc_lastLogin` and `nc_pageLoad` are there.

**Comment by Silberschleier** [comment]
I'm also working on this. On the instance I run, there is some inline javascript, referencing Nextcloud and also including the version.

Does anyone of you could post some links of public Nextcloud instances by any chance, so I could test my findings?
