### ISSUE TITLE
Invalid SSL certificate in the main site when entering the non-www-prepended URL

### ISSUE THREAD

**Issue by Eli-35** [AliasIO/Wappalyzer#2865]
**Do you want to request a *feature*, a *new application detection* or report a *bug*?**

Bug.

**Is your issue about WebExtension driver (Chrome & Firefox), the website, the NPM driver or the bookmarklet ?**

Website.

**What is the current behavior ?**

When user enters https://wappalyzer.com/ (I reached this URL from a link <a href="https://geekflare.com/what-technology-website-using/#WAPPALYZER">here</a>) the browser says SSL certificate is invalid (namely, NET::ERR_CERT_COMMON_NAME_INVALID), while adding the www or just typing wappalyzer.com in the search bar does not.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a demo of the problem.**

Follow the steps described above in any browser (I tested Edge and Chrome, both latest stable versions).

**What is the expected behavior ?**

The SSL cert should be valid, like the www-prepended URL. 

**Which versions of Wappalyzer, and which browser / OS are affected by this issue ? Did this work in previous versions ?**

My current setup is Windows 10 w/ Chrome & Edge, all software up to date. Also tested on Chrome @ Android 9 smartphone by 4G, same issue.

**Comment by q--** [comment]
See  #2358 #1862 #1863 (mostly  #1862)
