### ISSUE TITLE
Wrongly recognizing a React JS app as a Ruby and RoR app

### ISSUE THREAD

**Issue by zaroth** [AliasIO/Wappalyzer#2880]
**Do you want to request a *feature*, a *new application detection* or report a *bug*?**
bug

**Is your issue about WebExtension driver (Chrome & Firefox), the website, the NPM driver or the bookmarklet ?**
Firefox & website

**What is the current behavior ?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a demo of the problem.**

![image](https://user-images.githubusercontent.com/840021/70232343-855b3a80-175c-11ea-8fe0-5067b075e174.png)

On https://gmiclotte.github.io/gear-optimizer/#/ no React is detected. Ruby and Ruby on Rails are detected instead. As the source of the webapp can be seen on https://github.com/gmiclotte/gear-optimizer , this is totally wrong - no Ruby is used whatsoever, the app is entirely written in JS + React.

**What is the expected behavior ?**

Correctly detect React as used framework, don't detect Ruby and RoR (unless it's used by github pages and that is what causes the behavior).

**Which versions of Wappalyzer, and which browser / OS are affected by this issue ? Did this work in previous versions ?**
current versions as of today (20191205)

**Comment by kyletaylored** [comment]
These are two separate topics:

1. There is a [known issue](https://github.com/AliasIO/Wappalyzer/issues/2450) in detecting React apps (and other JS apps)
2. Ruby shows up because you're hosted on Github Pages, which is built on Ruby. It's part of the chain of inference.
