### ISSUE TITLE
Feature Request: Option to Disable Dark Mode

### ISSUE THREAD

**Issue by alivefromupstairs** [AliasIO/wappalyzer#2889]
Icons, IMO, really look bad with the while shadow.![image](https://user-images.githubusercontent.com/46059092/71035869-bbb19600-211c-11ea-934d-f0296df5b593.png)
 I don't particularly have dark mode enabled in chromium or system wide (manjaro linux with a window manager).
Can we have an option to disable/enable dark mode? or maybe add the white shadow only to icons that need it (e.g., Github Pages, as opposed to React or Ruby on Rails)?

**Comment by AliasIO** [comment]
This has been added in 5.9.0, along with updated styles.
