### ISSUE TITLE
New Application Detection Request : LitElement powered by polymer team

### ISSUE THREAD

**Issue by herberthobregon** [AliasIO/wappalyzer#2895]
**Do you want to request a *feature*, a *new application detection* or report a *bug*?**
new application detection
**Is your issue about WebExtension driver (Chrome & Firefox), the website, the NPM driver or the bookmarklet ?**
WebExtension driver (Chrome & Firefox)
**What is the current behavior ?**
not detecting any litelement technology on website
**If the current behavior is a bug, please provide the steps to reproduce and if possible a demo of the problem.**
not detecting any vuetify technology on website
**What is the expected behavior ?**
detecting litelement framework on website
**Which versions of Wappalyzer, and which browser / OS are affected by this issue ? Did this work in previous versions ?**
latest version

**Comment by herberthobregon** [comment]
// Can Run
`window.litElementVersions` is equal `["2.2.1"]`

**Comment by herberthobregon** [comment]
Update

**Comment by herberthobregon** [comment]
#  Can Run
window.litElementVersions != null

**Comment by nurbek91** [comment]
Hey @herberthobregon , lit-element, lit-html have been recently added.
Сan use your examples to see if everything is displayed now
If not send please links and what technologies should be added. Thanks mate!!
