### ISSUE TITLE
Add Linting or Unittest for pattern version syntax

### ISSUE THREAD

**Issue by kingthorin** [AliasIO/wappalyzer#2896]
It would be nice if updates (PRs) to apps.json were run through some sort of linting or unittest that validated pattern version syntax (https://docs.wappalyzer.com/dev/specification.html#version-syntax).

Then things like:
https://github.com/AliasIO/wappalyzer/blob/98814a0cddd31f6038c696b1a453a293c8e9423d/src/apps.json#L424

Wouldn't sneak in. I think that's supposed to literally mean version 7 (which doesn't seem addressed by the syntax spec), however there's no 7th capturing group and no capturing group at all in fact.

There are also these others that don't seem to make sense.
```console
"<input[^>]+name=\"ci_csrf_token\"\\;version:2+"
"\\/(?:coinhive|(authedmine))(?:\\.min)?\\.js\\;version:\\1?opt-in:"
"/<!--\\s*\\*\\s*FreeTextBox v\\d+ \\(([.\\d]+)(?:(?:.|\\n)+?<!--\\s*\\*\\s*License Type: (Distribution|Professional)License)?/i\\;version:\\1 \\2"
"<script [^>]+data-requiremodule=\"mage/\\;version:2",
"<script [^>]+data-requiremodule=\"Magento_\\;version:2",
"moin(?:_static(\\d)(\\d)(\\d)|.+)/common/js/common\\.js\\;version:\\1.\\2.\\3"
```

(There are likely others as well, but that's a sample.)

**Comment by AliasIO** [comment]
Those examples all seem valid to me, the spec does address returning a literal value instead of a back-reference. I'm currently adding validation for this though.

**Comment by kingthorin** [comment]
Thanks @AliasIO
