### ISSUE TITLE
Bug: Cloudflare on my website which doesnt use Cloudflare

### ISSUE THREAD

**Issue by Stryxus** [AliasIO/wappalyzer#2898]
Cloudflare shows up on my personal website although i dont use Cloudflare. Im actually using Azure CDN.

https://connorshearer.co.uk/

**Comment by aldi** [comment]
Seems right to me:
![2898](https://user-images.githubusercontent.com/15065804/71640515-34276380-2c94-11ea-8478-ad571f3fe4e4.png)

**Comment by Stryxus** [comment]
Hm odd. It was there until Wappalyzer update. Probably something was fixed without realizing it.
