### ISSUE TITLE
Possible EventEmitter memory leak console warning due to multiple event listeners

### ISSUE THREAD

**Issue by beanburrito99** [AliasIO/wappalyzer#2905]
**Platform**
Which platform does the bug apply to?

NPM

**Describe the bug**

When using the npm package to crawl multiple sites, you recieve a potential memory leak warning due to too many event listeners being added.

```
(node:226) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added to [process]. Use emitter.setMaxListeners() to increase limit
```

**To Reproduce**

1. Create a `test.js` file and paste in the code below
2. run `npm i wappalyzer` in the same folder as the `test.js` you just created
3. run `node test.js`

`test.js` code:

```javascript
const Wappalyzer = require('wappalyzer');

(async () => {
    const sites = [
        'https://www.google.com',
        'https://martinezdesigns.net', // shameless plug
        'https://www.yahoo.com/',
        'https://www.youtube.com',
        'https://twitter.com',
        'https://www.facebook.com',
        'https://www.reddit.com',
        'https://www.espn.com',
        'https://www.bing.com',
        'https://www.twitch.tv',
        'https://www.cnn.com/',
    ];

    const options = {
        debug: false,
        delay: 500,
        maxDepth: 3,
        maxUrls: 10,
        maxWait: 5000,
        recursive: true,
        userAgent: 'Wappalyzer',
        htmlMaxCols: 2000,
        htmlMaxRows: 2000,
    };
    await Promise.all(sites.map(async (site) => {
        const wappalyzer = new Wappalyzer(site, options);
        const json = await wappalyzer.analyze();
        console.log('Site:', site);
        console.dir(json, { depth: null });
    }));
})();
```

**Expected behavior**

The expected behavior still occurs: the package crawls and analyzes the sites.

However, the unexpected behavior is the warning in the console.

**Additional context**

It looks like this is due to the this line of code: https://github.com/AliasIO/wappalyzer/blob/master/src/drivers/npm/driver.js#L113

Every time a new instance of the `Wappalyzer` class (which makes a new instance of the `Driver` class) is made, it adds a new `uncaughtException` listener to the process.

By default a maximum of 10 listeners can be registered for a single event. 
https://nodejs.org/api/events.html#events_eventemitter_defaultmaxlisteners

**Comment by AliasIO** [comment]
Thanks, I removed that line. It should probably go in a higher level script anyway, if needed at all.
