### ISSUE TITLE
Wappalyzer is adding Laravel to my django project

### ISSUE THREAD

**Issue by Andre-Sekou** [AliasIO/wappalyzer#2908]
I have just created a django app to test my django installation. When browsing i was wondering what techs inside django itself and SURPRISE, Wappalyser shows up Laravel and PHP plus django and Python...

**Comment by Andre-Sekou** [comment]
<img width="869" alt="wappalyser-issue-github" src="https://user-images.githubusercontent.com/6539924/71927102-a6181500-318c-11ea-997f-9cc4433bd882.PNG">

Also this link:

**Comment by swiper** [comment]
Can you check if you have a cookie with the name `laravel_session`, maybe from another project running locally?
