### ISSUE TITLE
--help option for Docker image

### ISSUE THREAD

**Issue by abitrolly** [AliasIO/wappalyzer#2915]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I can't see command line help after typing `-h` or `--help` to command parameters.

**Describe the solution you'd like**
Add help option here https://github.com/AliasIO/wappalyzer/blob/master/src/drivers/npm/cli.js

**Comment by AliasIO** [comment]
Added in f2a42978597e18de28b5cca4e25c01fa3282fcf7.
