### ISSUE TITLE
HypeProxy.io .Net Core 

### ISSUE THREAD

**Issue by clintnetwork** [AliasIO/wappalyzer#2918]
Hi,

I try my website "hypeproxy.io" and the .net core framework does not appear, do you handle .net core framework?

Kind regards

**Comment by Triloworld** [comment]
If there exist unique identifier for this technology then - yes, this is bug.
Else, this run in background and no, we won't have that chance to add this even in future.

If you, in browser, see something specific on your website for ".NET Core Framework" then post it there. You are expert in that field. I can help add proper info about It. Then someone will check if this technology and identifier is ok and merge :)

I check and don't find any pattern ;/

**Comment by clintnetwork** [comment]
And what about cookie?

```
cookie: .AspNetCore.Session=
```

**Comment by Triloworld** [comment]
Great ! That will be the case. Change label to: Technology request
We waiting for fix (cookie have = in it) : https://github.com/AliasIO/wappalyzer/issues/2920

**Comment by clintnetwork** [comment]
Hi, sorry for the late, I think an user need to be connected!

Here an example, but you need to be registred.
https://hypeproxy.io/account/login
