### ISSUE TITLE
Not detecting OctoberCMS

### ISSUE THREAD

**Issue by FlusherDock1** [AliasIO/wappalyzer#2920]
**Platform**
WebExtension (Google Chrome, Mozilla Firefox)

**Describe the bug**
Extension didn't detecting OctoberCMS

**To Reproduce**
1. Go to https://octobercms.com/
2. See error

**Expected behavior**
Should detect by cookies.

**Comment by swiper** [comment]
This can be fixed by merging #2928, which fixes the cookie name value.

**Comment by kyletaylored** [comment]
The detection works as designed, the problem is that the home page does not initiate a cookie, you must first go to an account or registration page to initialize a cookie.

https://octobercms.com/account/register
