### ISSUE TITLE
Detection Request: Citrix VPN Server 

### ISSUE THREAD

**Issue by nrllh** [AliasIO/wappalyzer#2931]
It would be great, if you could add that to your detection. 

A sample page: https://aaa.newmont.com/vpn/tmindex.html

I'm not sure which method could be used here. I couldn't find any version details in cookie or source code.

**Comment by swiper** [comment]
This can be detected via:
```json
"js": {
    "AddHeaderAndBarForCitrix": ""
}
```

I could not find a way to detect the version.
