### ISSUE TITLE
Console Warning: 'DevTools failed to parse SourceMap...webextension-polyfill...'

### ISSUE THREAD

**Issue by czzonet** [AliasIO/wappalyzer#2932]
**Platform**
Which platform does the bug apply to?
- `Google Chrome` 
- `npm dev  vue-app`

**Describe the bug**
Console:
```txt
DevTools failed to parse SourceMap: chrome-extension://gppongmhjkpfnbhagpmjfkannfbllamg/node_modules/webextension-polyfill/dist/browser-polyfill.js.map
```

**Comment by hamidinfotech** [comment]
same for me

**Comment by afflexux** [comment]
And me.

**Comment by ana-arede** [comment]
+1

**Comment by Resetnak** [comment]
Same here

**Comment by mikeywil** [comment]
here too

**Comment by yesman234** [comment]
Same

**Comment by unbekannt3DE** [comment]
+1

**Comment by jvtecheto** [comment]
+1 
not solution yet?

**Comment by marcelogarbin** [comment]
any news?

**Comment by robclancy** [comment]
Why even send sourcemaps with it?

**Comment by AliasIO** [comment]
Fixed in https://github.com/AliasIO/wappalyzer/commit/62f881127c2cac5cb0d4a25fdfc09f0d2947a9e9#diff-81616a3b17429a2d7a410eca8a567de8R51

**Comment by annacv** [comment]
+1

**Comment by abdifatahali** [comment]
+++1

**Comment by lalitaryan1993** [comment]
Same here gppongmhjkpfnbhagpmjfkannfbllamg/node_modules/webextension-polyfill/dist/browser-polyfill.js.map

issue

**Comment by AliasIO** [comment]
This will be fixed in the next update.
