### ISSUE TITLE
Fix WHMCS detection

### ISSUE THREAD

**Issue by swiper** [AliasIO/wappalyzer#2940]
WHMCS updated their cookies with a random value, and is not being detected now. This can be easily fixed by detecting Javascript functions.

**Using the following detection _(instead of cookies)_, we can start detecting WHMCS again:**
```json
"js": {
    "WHMCS.client.registration.prefillPassword": ""
}
```

**Comment by hunsalz** [comment]
Hi @swiper, I tried to reproduce with https://demo.whmcsadmintheme.com/admin and just used 
     
` "js": {
        "WHMCS": ""
      }`

This seems sufficient to me. But I have to admit, I'm not familiar with WHMCS in any way.

**Comment by swiper** [comment]
Hello @hunsalz, that would even be better. Cannot test it right now, but the current method (cookie based, name `whmcs`) is not working (anymore).

**Comment by Triloworld** [comment]
Don't remove cookie for older version to proper detection (set version that is < 7.1 or when random cookie introduce)! 
Just add JS
