### ISSUE TITLE
Found broken link on site (Sencha Touch)

### ISSUE THREAD

**Issue by mylastsong18** [AliasIO/wappalyzer#2945]
**Platform**
Which platform does the bug apply to?
* Website

**Describe the bug**
The link for Sencha Touch is broken, according to Sencha it has been discontinued and you should instead use Sencha Ext JS. Maybe make a note that it's deprecated and have a link for the recommended replacement. Archive.org does have the old site saved so you could always link to that instead

**To Reproduce**
1. Go to 'https://www.wappalyzer.com/technologies/sencha-touch'
2. Click on 'Official Site'

**Expected behavior**
Link shouldn't be broken

**Additional context**
Here is a direct link to the broken site > https://www.sencha.com/products/touch/

Also sorry if this is the wrong place to submit this. Figured it was better than an email

**Comment by mylastsong18** [comment]
Interesting, the link itself is not broken but the link on Wappalyzer is

**Comment by AliasIO** [comment]
Looks like it needs the `www`, I'll add that in.
