### ISSUE TITLE
Detect Google Analytics while it is not present on website.

### ISSUE THREAD

**Issue by metemaddar** [AliasIO/wappalyzer#2946]
**Ubuntu 18.04**
Which platform does the bug apply to?
* WebExtension (Mozilla Firefox)
* [https://ketabrangi.ir/](https://ketabrangi.ir/)

**Describe the bug**
Wappalyzer detects google analytics. But there is no analytics on website.

**Additional context**
It seems it just checked for google site verification. But it is used for google search console and not google analytics.

**Comment by AliasIO** [comment]
I'm not seeing GA being reported. It may be a specific page that had a reference to it. Would you be able to restart your browser and check again? That should clear the extension cache.

**Comment by metemaddar** [comment]
Yes. I restarted browser and checked in incognito tab too. Also cleared cache. and Still seeing the GA icon. in wappalizer.
