### ISSUE TITLE
error: Could not unzip extension

### ISSUE THREAD

**Issue by Chizkiyahu** [AliasIO/wappalyzer#2949]
**Platform**
Which platform does the bug apply to?
* WebExtension Google Chrome

**Describe the bug**
when trying to add the google chrome extension get the error **Could not unzip extension**

**To Reproduce**
1. Go to [google chrome store](https://chrome.google.com/webstore/detail/wappalyzer/gppongmhjkpfnbhagpmjfkannfbllamg?)
2. Click on add
3. See error

**Comment by moerazem** [comment]
Same issue here. I tried to update the extension to 5.9.4

![Screen Shot 2020-02-23 at 1 26 49 PM](https://user-images.githubusercontent.com/122433/75111226-337dce80-5640-11ea-82f0-d1db5794403a.png)

**Comment by welkerjj** [comment]
I had the same issue--last night and this morning. Version of Chrome is current.

**Comment by AliasIO** [comment]
There's an issue with the review process, I'm hoping it'll be resolved soon.

**Comment by BLKStone** [comment]
I met the same issue, my chrome version is `Version 82.0.4067.0 (Official Build) canary (64-bit)`.

**Comment by atthaphonkajit** [comment]
same here..

Chrome : Version 80.0.3987.116 (Official Build) (64-bit)

**Comment by stardk** [comment]
The same with 80.0.3987.116 version

**Comment by AliasIO** [comment]
> There's an issue with the review process, I'm hoping it'll be resolved soon.

**Comment by AliasIO** [comment]
It's working again now, sorry for the wait.
