### ISSUE TITLE
Can't install extension

### ISSUE THREAD

**Issue by KeviinCosmos** [AliasIO/wappalyzer#2956]
**Win 10 64bit**
Which platform does the bug apply to?
* WebExtension (Google Chrome)

**Describe the bug**
Can't install the extension, getting this error: [https://sharex.wad.dk/wappalyzer.png](https://sharex.wad.dk/wappalyzer.png)

I used to have the extension for years, but i just removed all extensions and reinstalling those i need.

**Comment by oliverwehn** [comment]
Can confirm this. Tried to install the extension just a moment ago and also got an error message. 
![image](https://user-images.githubusercontent.com/992845/75434090-50244a00-5951-11ea-9cc2-caaaa4ac8557.png)

**Comment by voitsekhovskymax** [comment]
+1. Google Chrome 80.0.3987.122

**Comment by KeviinCosmos** [comment]
> +1. Google Chrome 80.0.3987.122

So it's the version?

**Comment by idzan** [comment]
https://github.com/AliasIO/wappalyzer/issues/2949 Problem is in Review process as Developer says. Just keep it locked and lock this thread also.
P.S.: I found that problem too after reinstalling system, before that is was working fine. Thanks Firefox, there plugins works fine.

**Comment by ProgramadorOri** [comment]
I got the same error a few minutes ago.

![image](https://user-images.githubusercontent.com/50775233/75482310-9047f480-5972-11ea-8c73-8333f0a30950.png)

**Comment by AliasIO** [comment]
v5.6.9 is still 'pending review'. It's taking a lot longer than normal, I emailed Google asking if they can prioritise it.

For now, you can clone this repository, navigate to 'about:extensions', enable 'Developer mode', click 'Load unpacked' and select the 'src/drivers/webextension` directory.

You can also use the [bookmarklet](https://www.wappalyzer.com/download), or Firefox/Edge.

**Comment by AliasIO** [comment]
It's working again now, sorry for the wait.
