### ISSUE TITLE
Suspected false-positive Genexus on google apps

### ISSUE THREAD

**Issue by CSSachse** [AliasIO/wappalyzer#2957]
**Platform**
Which platform does the bug apply to?
* WebExtension (Mozilla Firefox)

**Describe the bug**
Genexus is detected Google Drive, Gmail. I don't believe google uses this low-code platform for their core applications, they are not listed on genexus'  [Success Stories](https://www.genexus.com/en/company/success-stories), and genexus was only recently added on wappalyzer so I'm a bit skeptical that this inference is working correctly.

**To Reproduce**
Go to gmail.com and log it. Genexus is detected

**Expected behavior**
Probably should not be detected (correct me if I'm wrong)

**Additional context**
I haven't looked too deeply on how inferencing works, but the function `gx()` in the minified code might be triggering this? https://github.com/AliasIO/wappalyzer/pull/2944/commits/00f1e011d526843efde4f00668e13b793f27ea22#diff-557d7d60c04092a680ce152f367618c0R4027

**Comment by AliasIO** [comment]
This has been fixed in today's update.

**Comment by DiegoFleitas** [comment]
Ditto, I'm using the version 5.9.4 of the extension on Firefox
