### ISSUE TITLE
New version updates disrupt "Restore my tabs"

### ISSUE THREAD

**Issue by neolefty** [AliasIO/wappalyzer#2959]
**Platform**
Which platform does the bug apply to?
* WebExtension (Google Chrome, Mozilla Firefox)

**Describe the bug**
New version tab appeared, and it disrupted Chrome's normal restoration of tabs. I couldn't recover them anymore, and I am very frustrated.

**To Reproduce**

1. Open tabs
2. Hard-exit Chrome (for example with a forced reboot) before a Wappalyzer update
3. Start Chrome again, and Wappalyzer inserts the "Hi I have new features" tab.
4. Voila Chrome doesn't want to restore your tabs anymore, and shift-control-T doesn't help.

**Expected behavior**
Chrome offers option to "Restore My Tabs"

**Additional context**
Deleted Wappalyzer argh. Maybe someday I'll try it again but right now I'm mad.

**Comment by AliasIO** [comment]
I'm not sure how to work around that but there's an option in the extension setting to disable this behaviour. Uncheck the 'tell me about upgrades' box and you should not have this issue.
