### ISSUE TITLE
fail to detect CloudFlare on rawgit.loltek.net

### ISSUE THREAD

**Issue by divinity76** [AliasIO/wappalyzer#2971]
**Platform**
Firefox 68.5.0esr on Windows 10 x64
* WebExtension (Google Chrome, Mozilla Firefox)
* Website https://rawgit.loltek.net/

**Describe the bug**
https://rawgit.loltek.net/ is using cloudflare CDN, which is supported by wappalyzer ( https://www.wappalyzer.com/technologies/cloudflare ) , but for some reason, wappalyzer is not detecting cloudflare on the site.

**To Reproduce**
1. Go to https://rawgit.loltek.net/
2. check wappalyzer

**Expected behavior**
wappalyzer says "CloudFlare CDN"

**Additional context**
what actually happens: `No technologies detected.`

**Comment by amatzen** [comment]
Pretty sure, that "bug" applies due to the content-type of the page as `text/plain`. The headers in the data.json matches with the page.

**Comment by kyletaylored** [comment]
Currently picking up CloudFlare, marking as solved.

**Comment by divinity76** [comment]
@amatzen you're probably correct

@kyletaylored in what browser? it still doesn't work for me using 
`Firefox 78.6.1esr (64-bit)` + `Wappalyzer 6.5.22`  , nor does it work for me using `Google Chrome  87.0.4280.141` + `Wappalyzer 6.5.22`

**Comment by kyletaylored** [comment]
@kyletaylored in what browser? it still doesn't work for me using
> `Firefox 78.6.1esr (64-bit)` + `Wappalyzer 6.5.22` , nor does it work for me using `Google Chrome 87.0.4280.141` + `Wappalyzer 6.5.22`

I'm crazy. I was up late and looking into this, and I could've sworn it was working. I did find the issue, it is related to the `content-type: text/plain` header. While there's a ton of MIME types that could be detected, I imagine `text/plain` could be added for doing header detection on API responses, etc. I'll submit a PR.
