### ISSUE TITLE
CPU throttling

### ISSUE THREAD

**Issue by JefferyHus** [AliasIO/wappalyzer#2979]
**Platform**
Which platform does the bug apply to?
* WebExtension (Google Chrome, Mozilla Firefox)

**Describe the bug**
Lately my CPU was throttling and kinda worried me as I had no idea about the reason, I tried to debug and find the source. Later on I decided to check all chrome processes and found out one which is using over 20% of my CPU once I killed it, wappalyzer extension disappeared. Later on to just make sure it is the extension, I turned it on and my CPU hits over 50% of use and once I disable it, things goes back to normal.

**To Reproduce**
1. Enable the latest extension version on chrome
2. Open task manager and extend the chrome processes

**Expected behavior**
N/A

**Additional context**
I will just try and check the code now if there is any vulnerability that is causing this.

**Comment by kyletaylored** [comment]
Read this issue, you may have a similar issue: #2605

**Comment by AdityaAnand1** [comment]
I'm experiencing this as well, any solutions?

@kyletaylored That's a really large thread, which after reading, I didn't discern much of a solution. Am I missing something? 

Nevermind the cause, I simply want minimal CPU usage.

**Comment by kyletaylored** [comment]
@AdityaAnand1 Unfortunately, that's exactly the case - this crops up on a case by case basis and is not consistent across all users, meaning there is some external factor that is coming into play, such as another Chrome Extension or service that is conflicting and causing an issue.

For anyone who is having this issue, you need to open up the Chrome extension sandbox (found in the Extension settings) and run the Chrome profiler to see what exactly is taking up all the resources.

**Comment by AdityaAnand1** [comment]
Hold on. How come chrome extensions come into the picture? Doesn't it use a plain vanilla pupeteer chromium instance (devoid of any extensions)? Is it affected by my system's user installation of chrome?(!)

I have a crazy amount of ad blockers, script blockers and privacy related stuff on my personal chrome. Could that affect wappalyzer detection?

**Comment by AliasIO** [comment]
@AdityaAnand1 this issue is specifically about the WebExtension driver, which is the Chrome/Firefox/Edge extension.

**Comment by JefferyHus** [comment]
@AliasIO I don't think so, because I have multiple extensions and they are not using too much CPU. Once I turn on Wappalyzer the CPU usage goes up
