### ISSUE TITLE
Typo in apps.json

### ISSUE THREAD

**Issue by EmilieTrouillard** [AliasIO/wappalyzer#2998]
Hi,

I believe there is a typo in one of the regular expressions in the apps.json file, on [line 1166](https://github.com/AliasIO/wappalyzer/blob/master/src/apps.json#L1166): `"<link[^>]* href=\"^https?://edge\\.avangate\\.net/"`
[This example](https://regex101.com/r/SSLFs2/1) shows that it does not match the string it is supposed to. Instead, removing the second `^` seems to work, like in [this other example](https://regex101.com/r/RzynD1/1).

Best regards,

Emilie

**Comment by AliasIO** [comment]
Fixed, thank you!
