### ISSUE TITLE
Developer Docs are mising

### ISSUE THREAD

**Issue by sergey-nechaev** [AliasIO/wappalyzer#3001]
**Platform**
* Website
* Repo

**Describe the bug**
https://github.com/AliasIO/wappalyzer/blob/master/README.md has a link to `developer documentation`,  but it returns error 404: https://www.wappalyzer.com/docs

**To Reproduce**
1. Go to https://github.com/AliasIO/wappalyzer
2. Click on `developer documentation` link on the bottom
3. See error 404

**Expected behavior**
Developer docs link leads to correct page.

**Comment by AliasIO** [comment]
Fixed the link to point to https://docs.wappalyzer.com, thanks!
