### ISSUE TITLE
Google Shield - DDoS protection, like Cloudflare for journalist

### ISSUE THREAD

**Issue by Triloworld** [AliasIO/wappalyzer#3007]
Link:
https://projectshield.withgoogle.com/landing

Test by checking header and this if exist:
x-shield-request-id

Examples:
https://krebsonsecurity.com/
https://www.thelocal.com/
https://eclecticrhetoric.com/about/

**Comment by Triloworld** [comment]
I will try to add this, meantime it is accepted to add?

**Comment by AliasIO** [comment]
Go for it!

**Comment by Triloworld** [comment]
Ok, thanks.
After loading local chrome extension then I get no popup.
No documentation in that case ;/

I get:
TypeError: Failed to fetch
html/background.html:0 (anonymous function)

No popup visible so cannot test it ;/

**Comment by Triloworld** [comment]
Is category ok? (CDN or IaaS as not usually technology)
Version is properly test? 
Header show version and technology:
> via: 1.1 google

And solution:

> ^([0-9]\\.[0-9])\\;version:\\1 google

Pleas help about how to contribute. Docs need to be updated as "icon need to be visible on white background"

**Comment by Triloworld** [comment]
Fixed version recognization.
Need add to documentation about saving changes after running command. I change file before and It won't work. Saving and there is it :) Maybe have the original one.

**Comment by Triloworld** [comment]
<img width="1238" alt="Zrzut ekranu 2020-04-5 o 13 24 59" src="https://user-images.githubusercontent.com/2671726/78473410-c2523080-7740-11ea-962e-6a3551cc78fe.png">
