### ISSUE TITLE
regular expression matches empty string

### ISSUE THREAD

**Issue by kkaiser** [AliasIO/wappalyzer#3015]
Hello,

this is not necessarily a bug but the expression in https://github.com/AliasIO/wappalyzer/blob/master/src/apps.json#L7808 also matches empty strings as seen here: https://regex101.com/r/6A9XJL/2

It makes more sense removing the parentheses and question mark: `ATGPlatform/([\\d.]+)`

I know this might not be relevant since you want to extract the version only but in my case it causes a small issue in hyperscan.

**Comment by AliasIO** [comment]
Most headers match empty strings (like [this one](https://github.com/AliasIO/wappalyzer/blob/master/src/apps.json#L7829)). It shouldn't cause issues as the pattern is only executed when a matching header is found.
