### ISSUE TITLE
Missing icon php.svg for phpCMS

### ISSUE THREAD

**Issue by kkaiser** [AliasIO/wappalyzer#3018]
Hello,

[php.svg](https://github.com/AliasIO/wappalyzer/blob/master/src/apps.json#L13377) for phpCMS  is missing in the [icon directory](https://github.com/AliasIO/wappalyzer/tree/master/src/icons). 

However, there is a PHP.svg, all capital.

**Comment by sergey-nechaev** [comment]
Addressed here https://github.com/AliasIO/wappalyzer/pull/3013
