### ISSUE TITLE
Why is Wappalyzer redirecting links to unknown sources?!

### ISSUE THREAD

**Issue by andreabreu-me** [AliasIO/wappalyzer#3025]
**Platform**
Which platform does the bug apply to?
* WebExtension: Tested on Google Chrome (80.0.3987.149)
* Extension version: 5.9.30

**Describe the bug**
When I search on Google for example "namecheap" and then click on ad result of namecheap.com, then the browser goes through multiples locations, and ends in namecheap.com.

1 - https://advologysolutions.com/track2?gclid=CjwKCAjw7LX0BRBiEiwA__gNw7NiYyYX1Z67u3UyEUZWecKcGgWtVYQDF4pP47waa4I4ad6VOOdCDxoCfTkQAvD_BwE
2 - http://bestsschemes.com/
3 - https://www.namecheap.com/?utm_source=CJ&utm_medium=Affiliate&utm_campaign=9237744&ref=cj&affnetwork=cj&cjevent=feeabf4f79b111ea805b02190a18050d

**To Reproduce**
1. Go to google.com
2. Search 'namecheap'
3. Click on 'namecheap.com' ad search result
4. Browser should redirect multiple times

**Expected behavior**
No redirects

**Comment by smartsites** [comment]
I can not reproduce this. How do you know it's the wappalyzer extension problem?

**Comment by andreabreu-me** [comment]
It's not. Sorry, for a moment I thought because when I disabled this extension for some reason this behaviour has disappeared. I need to figure out why this is happening.
