### ISSUE TITLE
NPM Module memory leak on doing 100/sec

### ISSUE THREAD

**Issue by rahulvyas1** [AliasIO/wappalyzer#3027]
This is for the NPM module.

 I am running an m5a.8xlarge instance on AWS and trying to process tech data of 1 million domains. I am doing 100 wapps per second. And I can see the memory keeps rising and CPU reaches up to 200%

1. Launch AWS instance
2. Use a CSV file of domains and stream read 100 every second and process them using Wapp
3. I am using PM2 to monitor

You will see the CPU usage reaches 200% and memory increases 50mb every second.

My options- 

const options = {
  maxWait: 30000,
  userAgent: "Chrome",
};

**Comment by AliasIO** [comment]
Does it stabilise after 30 seconds at all? You're running up to 3,000 instances of Chromium this way so I'm not surprised it eats up resources.

**Comment by rahulvyas1** [comment]
> Does it stabilise after 30 seconds at all? You're running up to 3,000 instances this way so I'm not surprised it eats up resources. Are you using Zombie.js or Puppeteer?

My CPU has over 150% usage to it gets stuck. Is there any betteer way to run it other than on a large EC2? 

I am using puppteeer.

**Comment by AliasIO** [comment]
You can use Lambda with [chrome-aws-lambda-layer](https://github.com/shelfio/chrome-aws-lambda-layer) or ECS.

**Comment by rahulvyas1** [comment]
Lambda is too expensive. ECS-> Have you tested this?

**Comment by AliasIO** [comment]
I've used both for variable workloads but ECS is even more expensive. In your case I would batch requests and not start new Wappalyzer instances until others have completed. Is there a reason you can't let the process run for longer?

**Comment by rahulvyas1** [comment]
I will try putting these limits. Will probably use the agendajs (open source) for scheduling these jobs.

The reason for not letting them run for longer is that my instance stops responding..CPU usage is over 200%. I am tracking this using PM2 and i have to stop the node process.

**Comment by AliasIO** [comment]
I meant that you should run a small number of instances simultaneously so that you don't hit the CPU limit. It will probably take a few days to process all the URLs.

**Comment by rahulvyas1** [comment]
Hey, 

With lambda- what is the memory you set? Could you share the options?

**Comment by AliasIO** [comment]
1024MB is what I'd suggest.

**Comment by rahulvyas1** [comment]
Okay, that's a bit on the high end.

What about the options object?

**Comment by AliasIO** [comment]
With Lambda you get more CPU when you allocate more memory, which is what you'll need. If you use a lower number the function will run for longer and potentially cost more. What other options are you after?

**Comment by rahulvyas1** [comment]
I am running this in an EKS with M5a.24xlarge. But if I send 1000 requests per second, the wappalyzer returns empty response  for tech stack

Please share your EKS kubernetes yaml files would appreciate that

**Comment by rahulvyas1** [comment]
I ran 5x m5a.24xlarge 5000 requests/5 seconds and wappalyzer returns empty for almost most of the websites. AWS blocked our IP after we did 5 million and sent us abuse report.

The cost of AWS Lambda is massive high. for let's say 10 million websites

**Comment by AliasIO** [comment]
I'm not using EKS so I don't have those files for you. I'm not sure why you want to run such a large volume in a short amount of time, is this for an ongoing project or just a one-off? Of course it's going to be expensive.

**Comment by rahulvyas1** [comment]
Ongoing project. Lambda is computationally highly expensive, to be honest. For example processing 100Mil using Lambda would cost about 10k$+

**Comment by rahulvyas1** [comment]
Also, I want to ask- why the browser extension gives more technologies instead of the npm module?

What options to use with the npm module?

**Comment by AliasIO** [comment]
If there's a discrepancy between the extension and module, please create a separate issue with examples and I'll have a look at it.

And yes, 100M scans is going to be expensive if you want to do it fast. You can try using the Zombie.js browser, which is much lighter, but it won't be as accurate as Puppeteer.

**Comment by rahulvyas1** [comment]
Thanks, I will close this issue then.
