### ISSUE TITLE
Wappalyzer for Android (app)

### ISSUE THREAD

**Issue by bartcz** [AliasIO/wappalyzer#3029]
Hi,

please create a Wappalyzer app for Android. On Android would be nice to use Wappalyzer as well.

Thanks

**Comment by AliasIO** [comment]
You can use the free lookup tool on the website on mobile or install the extension on Firefox mobile. What other functionality would an app offer?

https://www.wappalyzer.com/lookup

**Comment by bartcz** [comment]
This is too complicated and unreliable. An Android app would be nice.

**Comment by AliasIO** [comment]
We now have an Android app:

https://play.google.com/store/apps/details?id=com.wappalyzer.twa
