### ISSUE TITLE
Wappalyzer breach

### ISSUE THREAD

**Issue by bugbaba** [AliasIO/wappalyzer#3031]
Hi Elbert,

I have been receiving multiple emails like these, indicating the breach of  wappalyzer data along with users emails.

![image](https://user-images.githubusercontent.com/29960776/79584897-a65d7000-80ec-11ea-95a7-a16314082144.png)

I have also forwarded the same to `elbert@...`

--
Regards,
@bugbaba

**Comment by AliasIO** [comment]
Hi @bugbaba,

You should have received the following message a few days ago. I'm sorry for what happened here.

> We respect the privacy of your personal information, which is why we are writing to advise you of an event that resulted in the possible disclosure of your personal data.
> 
> On 20 January 2020 our database was compromised due to a misconfiguration. No financial information or passwords were included in the breach.
> 
> The issue has been resolved and our website is working normally. There is no action you need to take.
> 
> If you requested a quote from our website before this date, your email address may have been included in the stolen data.
> 
> If you placed an order on our website before this date, your billing address may also have been included in the stolen data.
> 
> Some of our customers received an email from the perpetrator offering to sell stolen datasets. This data does not include personal information. If you receive such an email, mark it as spam and do not reply or click any links as it's likely a scam.
> 
> We're very sorry for the inconvenience and concern this has caused. We want to assure you we're doing everything we can to safeguard your personal information and will continue to monitor to investigate.
