### ISSUE TITLE
Wappalyzer confusing Azure Application Insights with Google Analytics

### ISSUE THREAD

**Issue by OnlyOnePro** [AliasIO/wappalyzer#3035]
**Platform**
Which platform does the bug apply to?
* WebExtension (Google Chrome, Mozilla Firefox)

**Describe the bug**
Wappalyzer detects Application Insights as Google Analytics.

**To Reproduce**
1. Create a ASP.NET Core 2.2 MVC sample project (Use Visual Studio or VSCode)
2. Add Application Insights SDK to the solution
3. Run the solution and when it finally loads, click on the extension

**Expected behavior**
Wappalyzer should not be confusing Application Insights as Google Analytics. The extension currenlty doesn't detects Application Insights, so the Analytics section of the detected technologies should be empty.

**Additional context**
I have been watching this error since ASP.NET Core 1.0; now on 2.2 it keeps happening. I tough it was a false positive beacuse some times it will show nothing detected and most of the times it shows Google Analytics.
The site in development has NO references or request to a Google Service whatsoever (not Google Fonts, nor Google reCaptcha, nor Google Analytics, nothing at all). All of the features are self-contained in the site and only do requests to external services for CDN content (like jQuery or Bulma.io)

**Comment by kyletaylored** [comment]
Can you point to an existing site that is running Application Insights already? Going through that reproduction is a lot of overhead to validate. My guess it it's probably either a cookie or global JS object that is shared.

```
"Google Analytics": {
      "cats": [
        10
      ],
      "cookies": {
        "__utma": "",
        "_ga": "",
        "_gat": ""
      },
      "icon": "Google Analytics.svg",
      "html": "<amp-analytics [^>]*type=[\"']googleanalytics[\"']",
      "js": {
        "GoogleAnalyticsObject": "",
        "gaGlobal": ""
      },
      "script": "google-analytics\\.com\\/(?:ga|urchin|analytics)\\.js",
      "website": "http://google.com/analytics"
    },
```

**Comment by OnlyOnePro** [comment]
I don't know sites that use them, and I am only able to develop locally due to my country's bad internet.

A shared cookie isn't, the site that I am currently developing uses Application Insights SDK and isn't using Cookies:

![image](https://user-images.githubusercontent.com/27441273/81354371-68bf8780-9099-11ea-9d2f-d1ae51634584.png)
That specific webapp uses cookies for Identity purposes, not Inisights.

Insights works mainly these days now by JS in the header or as a NPM dependency (https://github.com/Microsoft/ApplicationInsights-JS is their official repo with the two methods fairly descripted). The default cookies can be configured using those methods (ai_session for tracking the current session of the user and ai_user for tracking the actual user are the default names of the cookies).

This is a good explanation of AI and Cookies => https://stackoverflow.com/questions/31280710/managing-application-insights-cookies

Hoping that was helpful at least in some degree! 👍
