### ISSUE TITLE
Add detection for Reaction Commerce

### ISSUE THREAD

**Issue by rviscomi** [AliasIO/wappalyzer#3040]
[Reaction Commerce](https://reactioncommerce.com/) is an ecommerce tech stack not currently included in the technologies list. It was also recently acquired by Mail Chimp, so we may expect to see a surge in adoption.

It'd be great if someone familiar with that stack could help us identify strong detection signals so we can add it to the tool.

**Comment by rockeynebhwani** [comment]
@rviscomi I propose that we close this in Favor of https://github.com/AliasIO/wappalyzer/issues/3229.

Let's consolidate .. this will not be ready for 2020 web almanac though
