### ISSUE TITLE
Wappalyzer and Jira Service Desk

### ISSUE THREAD

**Issue by jtorrence1** [AliasIO/wappalyzer#3046]
**Platform**
Which platform does the bug apply to?
* WebExtension (Google Chrome, Mozilla Firefox)

**Describe the bug**
When accessing a Jira Service Desk portal with the Wappalyzer extension enabled, the form gives you a Page cannot load error and a bunch of errors hit the console

![image](https://user-images.githubusercontent.com/24799709/80155749-3da44680-8577-11ea-9d44-846f2ba33a4d.png)
![image](https://user-images.githubusercontent.com/24799709/80155774-49900880-8577-11ea-95e8-08cff9c53cfa.png)

**To Reproduce**
1. Navigate to a Jira Service Desk Cloud instance
2. Try to view a request or create a new request

**Expected behavior**
The form should load as it would normally without any errors.

**Comment by AliasIO** [comment]
Can you please let me know if this is still an issue in v6? The extension has been mostly rewritten.
