### ISSUE TITLE
Technlogy links from bookmarklet are broken

### ISSUE THREAD

**Issue by nctbrtc** [AliasIO/wappalyzer#3048]
On chrome browser, when I want to click on technology, it gets 404 error
For example: 
https://www.wappalyzer.com/applications/handlebars

**Comment by AliasIO** [comment]
Thanks, this has been fixed in 323dafd7bd5affa73ce7589fc6e1f443437259e9. The will propagate over the next few days.

**Comment by nctbrtc** [comment]
yaay ! 
thanks

**Comment by nctbrtc** [comment]
Links are broken again :(

**Comment by AliasIO** [comment]
Which version are you using?
