### ISSUE TITLE
Miniserve is Webhosting Panel not a Webserve

### ISSUE THREAD

**Issue by Linuxnizer** [AliasIO/wappalyzer#3054]
**Platform**
Which platform does the bug apply to?
* WebExtension (Google Chrome, Mozilla Firefox)
* NPM
* Bookmarklet
* Website

**Describe the bug**
Miniserve is reported as a webserver but its webhosting plane.

**To Reproduce**
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Additional context**

**Comment by kyletaylored** [comment]
Please provide additional information.
