### ISSUE TITLE
ServiceWorker blocked

### ISSUE THREAD

**Issue by mehmet-erdogdu** [AliasIO/wappalyzer#3060]
**Platform**
Which platform does the bug apply to?
* WebExtension (Google Chrome 81.0.4044.129, Mozilla Firefox)
* NPM
* Bookmarklet
* https://www.birdugun.com/ https://www.manaa.io/

**Describe the bug**
I am using Service Worker and caching some sites. But this extension blocked my service workers. I have this error in my Console Log. I disabled wappalyzer. Everything working normal. I want to use this extension but this is so painful

**To Reproduce**
1. Go to 'https://www.birdugun.com/ https://www.manaa.io/'
2. Click on 'F12' Developer Tools, Open Console
3. Scroll down to '...'

**Expected behavior**
Should not block Service Worker

**Additional context**
Console Error:
serviceworker:26 Uncaught (in promise) TypeError: Request scheme 'chrome-extension' is unsupported
    at serviceworker:26

**Comment by AliasIO** [comment]
I believe his has been resolved, please let me know if it's still an issue.

**Comment by mehmet-erdogdu** [comment]
i tested. fixed issue. thanks for helping.
