### ISSUE TITLE
Web page constantly shows progress indicator. 

### ISSUE THREAD

**Issue by mworkercom** [AliasIO/wappalyzer#3061]
**Platform**
Which platform does the bug apply to?
* Website

**Describe the bug**
Web page constantly shows progress indicator. 
Tested on various browsers, from various networks.

**To Reproduce**
1. Go to [https://www.wappalyzer.com/technologies/webpack](https://www.wappalyzer.com/technologies/webpack)
2. See endless "progress"

![image](https://user-images.githubusercontent.com/64523678/81099289-59163680-8f13-11ea-960f-7ddc458b9237.png)

**Expected behavior**
Show some technology stats, links to technology pages,  etc..

**Comment by AliasIO** [comment]
That's fixed, thanks!
