### ISSUE TITLE
Icons do not appear

### ISSUE THREAD

**Issue by mikkk3l** [AliasIO/wappalyzer#3072]
**Platform**
Which platform does the bug apply to?
* WebExtension (Google Chrome, Mozilla Firefox)
* NPM
* Bookmarklet
* Website

**Describe the bug**
A clear and concise description of what the bug is. No specific icons for each tecnology as previously,

**To Reproduce**
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Additional context**

![image](https://user-images.githubusercontent.com/15341836/81505948-4cb72280-92f3-11ea-99ca-fefb053468b4.png)

**Comment by AliasIO** [comment]
Fixed! Thank you.
