### ISSUE TITLE
Zombie vs pupeteer? When to use which?

### ISSUE THREAD

**Issue by AdityaAnand1** [AliasIO/wappalyzer#3082]
Are some technologies only detected with pupeteer? If so, which ones?

**Comment by AliasIO** [comment]
Only use Zombie.js if you want a browser with a very small footprint. It doesn't handle things like WebSockets and other modern APIs, Puppeteer is much more capable.

**Comment by AdityaAnand1** [comment]
> Puppeteer is much more capable

Yes, that's what I'm trying to figure out, more capable how? Can you give us an idea about what kind of technologies you've seen that zombie has trouble with? (Might be a good idea to mention this in docs too)

**Comment by AliasIO** [comment]
It's not so much technologies but some websites will fail to run in Zombie.js, for instance when they use web workers or WebSockets. I'm thinking of dropping support for Zombie.js.

**Comment by AdityaAnand1** [comment]
Welp. That is a giant red flag that should be mentioned in the readme 😅

**Comment by AliasIO** [comment]
Please see:

https://github.com/AliasIO/wappalyzer/issues/3081#issuecomment-633806251
