### ISSUE TITLE
Idea: Use nslookup to find technologies by DNS

### ISSUE THREAD

**Issue by AdityaAnand1** [AliasIO/wappalyzer#3090]
DNS values can tell us things about:

1. Host: AWS/Heroku/Digital Ocean etc.
2. Email hosting: Google business email
3. Usage of search webmaster tools
4. CDN usage
5. Subdomains

Bit of a treasure trove really 😁

**Comment by AliasIO** [comment]
I'd like the WebExtension to stay passive (i.e. not make any network requests of its own), but I have been thinking of optionally doing a deeper scan and look at common files like robots.txt and perhaps DNS. I'll leave this ticket open for now.

**Comment by AdityaAnand1** [comment]
Absolutely, we could make this another direction for the project, things that belong in the extension and extra stuff can go along in parallel, so that the extension only calls the extension relevant stuff and the code call gives you an option to call the extra bits.

Arguably, the extension could also be improved, if it didn't run client side and instead collected and aggregated data about all the websites in a central location. Radical new direction, I know but it could open up a lot of possibilities to go beyond what it is now 😁
