### ISSUE TITLE
Wappalyzer as a plugin for pupeteer

### ISSUE THREAD

**Issue by AdityaAnand1** [AliasIO/wappalyzer#3093]
If we have to scrape a large number of websites (and detecting technologies is one use case), then wappalyzer has to be run separately for all websites and the other scraper separately.

If wappalyzer was available as a pupeteer plugin as well (which would be a much better architecture too), it would allow users to simply add in wappalyzer to their existing web scraping stack. This would be extremely powerful.

Pupeteer has first class support for plugins too so this would fit right in.

**Comment by AliasIO** [comment]
That's interesting, I'll look into this when I get the chance.

**Comment by AliasIO** [comment]
Please see:

https://github.com/AliasIO/wappalyzer/issues/3081#issuecomment-633806251

**Comment by AdityaAnand1** [comment]
Was wondering whether there were any updates on this and saw this was closed 🤔 

This issue should be open, it has nothing to do with #3081.

This has more to do with: When one has to scrape a large number of websites via pupeteer, wappalyzer should work as a plug-and-play-and-get-tech-data in your own scraping processes.

I really think this is worth building, it would make wappalyzer way more powerful, allowing devs, who are already doing unrelated scraping, to simply plug in wappalyzer and get tech data as well 🔥

**Comment by AdityaAnand1** [comment]
Doesn't even have to be a plugin tbh, it could also support:

1. Exposing internal pupeteer instance: Let wappalyzer do it's thing first, then it returns the pupeteer page with the website still open for me to do the rest of the scraping (unrelated to tech data)
2. Perhaps wappalyzer can take a reference to a pupeteer page, provided by me, and then do it's thing.

Either of these, or the plugin approach would accomplish the same thing.

**Comment by AliasIO** [comment]
You can use your own Puppeteer instance with Wappalyzer core.

https://www.npmjs.com/package/wappalyzer-core
