### ISSUE TITLE
MaxListenersExceededWarning

### ISSUE THREAD

**Issue by AdityaAnand1** [AliasIO/wappalyzer#3094]
I keep getting the following when iterating through a list of websites.

![image](https://user-images.githubusercontent.com/13274079/82444573-12067480-9ac1-11ea-83e3-e4123f76a71c.png)

There is a memory leak somewhere. Any ideas?

**Comment by mzpqnxow** [comment]
I also see this issue, though i'm not sure it's a memory leak. I suspect it has more to do with a general exhaustion of some OS resource. That said I know nearly nothing about Node... I've been looking into various `sysctl` settings that may help. Sorry, just some conjecture, and I am not affiliated with this project

FWIW, it doesn't _seem_ to have any obvious adverse impact on the results. Though it is a bit troubling (and annoying) to see...

**Comment by AliasIO** [comment]
I've looked into this some time ago and there is no memory leak from what I can see. Running a lot of instances will register a lot event listeners, which is to be expected. The warning can be suppressed or just ignored, it shouldn't have any adverse affects.

**Comment by AdityaAnand1** [comment]
> Running a lot of instances will register a lot event listeners

This was just from running a single instance. Really should be looked at as it is clearly a problem, the better the underlying code the better the experience for everyone 😄

**Comment by mzpqnxow** [comment]
@AdityaAnand1 @AliasIO this appears to be a bug in the Node engine, introduced 12.9.0. So you can either downgrade or wait until Node releases a fixed version. This short version of this story is that it is not a fault in wappalyzer and this issue can be resolved. Read on for why.

Please see [this node issue](https://github.com/nodejs/node/issues/29239) for the initial discussion. This eventually points you to the pending Node 12.9.1 release [here](https://github.com/nodejs/node/pull/29321) which will be addressing this bug

Once 12.9.1 is released (which I imagine will be soon) this will go away and everyone can rejoice

I think you can resolve this and follow along on the PR and Issue in the Node project itself that I linked above (if you're interested)

**Comment by AliasIO** [comment]
Please see:

https://github.com/AliasIO/wappalyzer/issues/3081#issuecomment-633806251
