### ISSUE TITLE
Ability to specify client interface/IP address to use for network operations

### ISSUE THREAD

**Issue by mzpqnxow** [AliasIO/wappalyzer#3097]
When performing a wide-scale survey of sites, it is very beneficial to utilize multiple network cards simultaneously, or to simply force usage of a _specific_ card, rather than be at the mercy of the first NIC available with a default route, with the lowest route metric that is chosen by the kernel TCP/IP stack.

There are several reasons to do this, whether it be for network performance reasons when running a large amount of wappalyzer instances simultaneously, via something like GNU `parallel` or just  to reduce the chances of a site operator or automated WAF or other layer-7 inspection engine temporarily blocking or throttling requests. Please note, I utilize the tool on networks where I am properly authorized to use it (it is part of my job) but this still can lead to blocks when a single IP hits, e.g. and entire /24 in succession. Scaling out to multiple NICs (and thus source IP addresses) helps with this case

Many tools (whether they are security tools or enterprise tools) provide something like a `--source` or `--interface` option where the user can specify either the network interface to use or the IP address of the interface to be used to send and receive packets. These are admittedly more common with tools that take large lists of of inputs and have more aggressive transmission profiles than wappalyzer does, but it is not difficult to parallelize wappalyzer to the point that it can be perceived as aggressive- and this is sometimes needed depending on the scale of the task you need to accomplish

In a low level language like C, this is a very straightforward implementation, which is why it is so commonly implemented; after the socket is created using `socket()`  but before the connection to the remote host is attempted using `connect()`, a call to `bind()` is used to instruct the socket on which source IP address and port it should be "bound" to. By default, specifying a value of 0 for the port causes the OS TCP/IP stack to choose an ephemeral port

In higher level languages, I would expect a similar method is available- unfortunately I am not a JS developer, so I to implement this myself and send a PR would be difficult for me to find the time for.

One alternative is to shard the instances across different machines, each with a single interface, forcing each run to go through that machine's interface. Basically, just scale by getting entirely new machines. This is obviously a very expensive, inefficient and needlessly complex as it requires sharding the list of targets using ssh trust or some other mechanism

Another alternative is bonding multiple connections, but this is very invasive to the system, requires escalated privileges,and is much more complicated then simply providing a parameter on the command-line.

I've utilized this feature with several other tools, some of which I had to add the feature myself, others that already supported it. In some cases, this might be considered a feature for "advanced" users, since in some configurations with multiple default gateways, you _may_ need to set up some (simplistic) policy based routing rules so that the packet roundtrips correctly, but I feel that because the difficult/complexity of implementing the feature is generally very, very low it is a reasonable ask as an enhancement/new feature

Thanks, I appreciate the work that has been done to make wappalyzer such an excellent tool and am equally appreciative that is open-source. Because you are so open to collaboration, I've already added a handful of rules to my local installation that I plan to contribute via PR which hopefully will establish some good will to encourage implementation of this feature.

**Comment by AliasIO** [comment]
I'd be happy to include this if someone is willing and able to submit a pull request for it.

**Comment by mzpqnxow** [comment]
Terrific, thanks. Perhaps this means I'm going to have to pick up some JS. I'll leave this open until someone sends in a PR, whether it is me or someone else
