### ISSUE TITLE
Multiple YaML files as a practical and valuable alternative to current monolithic JSON for apps.json

### ISSUE THREAD

**Issue by mzpqnxow** [AliasIO/wappalyzer#3099]
I can't say this is a bug report, nor can I really say it is a feature request as much as I can say it is a request for comment from the developers.

I recently started working with Wappalyzer and found it to be an excellent tool, especially when compared with similar tools. I particularly like how easy it is to add new technologies and categories.

However, in my opinion, working with this data (apps.json) could  be made simpler to work with

JSON is great for machines reading structured data. It's also definitely readable by humans. However, YaML has major benefits over JSON in my opinion:

1. YaML is much easier for humans to read and write
2. YaML supports comments
3. Valid JSON is also valid YaML

I've been known to be a bit of aYaML evangelist (or maybe Zealot) but I think that the process of both adding/editing the apps data as well as the process of reviewing/merging/documenting it would be made much easier if the data was stored as YaML.

Because JSON is valid YaML, this could be done in a relatively unobtrusive way.

The drawbacks here I think would be the escaping/quoting requirements that may pop up when writing YaML by hand.

As an alternative, I've considered writing a simple Makefile that will convert the JSON to YaML while I am working with it, and then back to JSON when I am done. I'm OK with this, but I thought this still might be a point worth raising

In addition to switching from JSON to YaML, I can tell you that my experience in reading as well as adding new entries to the apps database in wappalyzer would be greatly improved if an `apps.d/` style approach was accepted. The apps.json file, being monolithic and containing every rule, is a bit clunky. I _do_ concede/understand that there is convenience in everything being available in one file, but from a development point of view, it makes more sense to me to have multiple files- perhaps for different categories of entries. These could be easily merged at run-time by simply concatenating the lists of structured data together. This could potentially make merging PRs cleaner with less conflicts- though maybe that's a solution for a problem that doesn't exist.

I'm not sure I can provide a technical explanation for my claim that as a result of the file being monolithic it is "clunky", but I do expect it to continue growing in size as time goes on. At some point, isn't one file just too much to deal with?

I think there could be a benefit in a switch from JSON to YaML, even if just for the ability to contain comments. I also believe there would be benefits to the apps file being module, so that categories could be kept logically separate. Perhaps there are other ways the file could be split.

I'm not expecting this idea to gain much traction, but I do appreciate the consideration and any thoughtful response. I would very much appreciate any explanation of why JSON was chosen in the first place- purely out of curiousity. I don't intend to argue this one to the death :)

Also, allow me to apologize in advance if this has all been hashed out before. I'm new to the app and am not familiar at all with the development history and/or the design and implementation choices

Thanks

**Comment by AliasIO** [comment]
JavaScript supports JSON natively and I'd like the WebExtension to stay dependency free. I don't think a single file is problematic, conflicts are rare and easy to resolve. I know what you mean about it being clunky though. Technologies can be in multiple categories so I don't think there's a clear way to split it into multiple files.

**Comment by mzpqnxow** [comment]
Fair enough. Should we close this?

Thank you for your thoughts and the quick response

**Comment by AliasIO** [comment]
Another benefit of using YAML is not having to escape the regular expressions, which is a bit weird the way it is now. I'd consider it if there was native support.

**Comment by mzpqnxow** [comment]
> Another benefit of using YAML is not having to escape the regular expressions, which is a bit weird the way it is now. I'd consider it if there was native support.

True, though YaML has some quoting/escaping issues of its own to deal with as well. Either way, I think we are in violent agreement. Thanks again
