### ISSUE TITLE
Typo in 'Cloudflare' name

### ISSUE THREAD

**Issue by rorymalone** [AliasIO/wappalyzer#3100]
**Platform**
Which platform does the bug apply to?
* All

**Describe the bug**
Typo in Cloudflare's name, under 'CDN' - should be Cloudflare, not CloudFlare

see: [www.cloudflare.com](https://www.cloudflare.com)

**Additional context**
Icon filename in source is also CloudFlare.png - not Cloudflare.png (_not user-visible_)

**Comment by AliasIO** [comment]
I'll update this, thanks!
