### ISSUE TITLE
Randomly gets stuck

### ISSUE THREAD

**Issue by AdityaAnand1** [AliasIO/wappalyzer#3101]
Try to scan over a few hundred URLs and wappalyzer is bound to get "stuck", as in:

```await new Wappalyzer(website, options).analyze();```

the above never completes, so for some reason the max wait period is being ignored. Can't really say much more about the cause since the method is a bit of a black hole, except that it happens randomly and always happens when scanning for ~20 minutes or so consistently after a few dozen websites.

Any ideas?

**Comment by AdityaAnand1** [comment]
I've had to implement my own custom race condition logic to bypass this, effectively, if the analyze() promise doesn't resolve in X seconds, give up and return (which, I thought was how max delay should have worked)

**Comment by AliasIO** [comment]
`maxWait` doesn't guarantee that the process will finish within that time. There needs to be an idle CPU cycle for `setTimeout` to fire, otherwise it keeps going indefinitely. Using `Promise.race` is your best option.

**Comment by AdityaAnand1** [comment]
I'm not sure if this is the same issue or not, but upon further use of the latest v6.0, my whole computer sometimes freezes up while or even after using wappalyzer.

So, the underlying issue remains.

I'm not sure, is it just me? Have you tried iterating through 100s of URLs? It hasn't worked properly for me once when going through a large number of URLs :/

I'm not sure what is happening. Maybe when CTRL+C-ing some memory leaks are there, the process doesn't exit fully or something else.

**Comment by AdityaAnand1** [comment]
Using the promise race method has the side effect that the wappalyzer promise never gets resolved which means that the resources allocated to it (page/browser) are never freed up.

This could be one cause for a slow but gradual rise in RAM/CPU usage leading to system freezes, which corresponds to what I'm seeing.

Perhaps it might make sense to implement a force reject after a specified max wait time within wappalyzer?

**Comment by AliasIO** [comment]
Are you batching your requests? You could do something like 10 URLs at a time. You should be able to free up resources with `wappalyzer.destroy()` and reinitialise if needed.

**Comment by AdityaAnand1** [comment]
> Are you batching your requests

Yes, I followed exactly as in the new readme. That seems to accelerate how quickly the problem occurs. (I've tried low memory - high memory, up to 32 GB RAM, desktops, servers, windows, linux => same problem everywhere, so it's not a system thing)

> You could do something like 10 URLs at a time

If one wappalyzer promise is stuck and doesn't return, then all 10 get stuck and don't return.

> You should be able to free up resources with wappalyzer.destroy()

Right now, I've only ever encountered three exit scenarios: 

1. It gets stuck, then I try to CTRL+C (forcefully exit) => `wappalyzer.destroy()` is never called
2. It gets stuck, then I have to reboot the system.
3. It's not stuck yet, but I want to stop the process manually when iterating over thousands of URLs = CTRL+C again, so `.destroy()` is literally never called in any scenario.

So, I'm not sure if `destroy()` is even useful in this situation.

Since I have thousands of URLs, I'd rather let wappalyzer run 24/7 on a server and never have to shut it down at all, so there's no use case for `.destroy()`

I'm surprised this doesn't seem to be a bigger issue 😕 If you'd like I can share a list of a few thousand URLs so you can iterate over it and reproduce it yourself.

**Comment by AliasIO** [comment]
The example in the README doesn't batch, you can do something like this:

```
const urls = []

while (urls.length) {
  const results = await Promise.all(
    urls.splice(0, 10).map(async (url) => ({
      url,
      results: await Promise.race([
        wappalyzer.open(url).analyze(),
        new Promise((resolve, reject) => setTimeout(() => reject(new Error('Timeout')), 30000))
      ])
    }))
  )
}
```

I'm running Wappalyzer in Lambda and ECS and haven't seen a process get stuck. I'm guessing it's because you're overloading the resources you have and you need to slow it down.
