### ISSUE TITLE
Mouse busy cursor blinking

### ISSUE THREAD

**Issue by AdityaAnand1** [AliasIO/wappalyzer#3102]
Whenever wappalyzer is running on my machine, churning through hundreds of URLs

![image](https://user-images.githubusercontent.com/13274079/82725778-069f8d00-9cfd-11ea-9c77-25cad70646ab.png)

the mouse cursor keeps having an epileptic seizure flickering between the normal/busy cursor a few times every second. 

Clearly, this is annoying. Is there a way to fix this? My best guess is that it's an underlying pupeteer thing that happens when you are opening closing tabs and that there must be some setting to remove all mouse cursor feedback.

**Comment by Julien-ADDREA** [comment]
Try to disable all other extension and reinstall wappalyzer

**Comment by AdityaAnand1** [comment]
This happens with the npm module, not the chrome extension.

**Comment by Julien-ADDREA** [comment]
> This happens with the npm module, not the chrome extension.

Hello, it is because of Puppeteer with each request that you make your cursor start to load for a short time, as you have several hundred calls your cursor starts blinking.

I recommend you run this on a server, or on Docker to isolate it from the operating system.
