### ISSUE TITLE
High number of cpu hungry "rogue" chromium instances

### ISSUE THREAD

**Issue by AdityaAnand1** [AliasIO/wappalyzer#3103]
I'm getting the sense that I'm pushing this library to it's limits, concurrently having multiple processes set up, churning through thousands of URLs:

This is on windows, AFTER killing ~5 processes iterating through URLs with wappalyzer

![image](https://user-images.githubusercontent.com/13274079/82726046-20da6a80-9cff-11ea-9f83-0095670832c1.png)

Whenever I try to do this, my computer (high end workstation) ends up grinding to a halt and I have to slowly force kill processes and even when the node processes are dead, the chromium processes stick around and for some reason they demand a ton of CPU usage.

I'm guessing for a similar reason, I haven't been able to use this in virtual machine/servers as well, it ends up eating too much memory/CPU - so much so that I have no other choice to kill the processes.

Any ideas how to solve this?

**Comment by AliasIO** [comment]
I'm not sure why the processes stick around. You could perhaps try using Docker and stop the container when the process is done.

**Comment by AdityaAnand1** [comment]
That doesn't really solve the problem, the container's memory will fill up and the container will just stop responding.

**Comment by AliasIO** [comment]
I'm currently working on a Puppeteer-only driver that will let you run multiple scans with a single browser instance, stay stuned.

**Comment by AliasIO** [comment]
Please see:

https://github.com/AliasIO/wappalyzer/issues/3081#issuecomment-633806251
