### ISSUE TITLE
Add Deno technology! 🦕

### ISSUE THREAD

**Issue by Kayoshi-dev** [AliasIO/wappalyzer#3114]
Now that Deno 1.0 is out it would be cool to see it in Wappalyzer! 
Sadly I don't think I have enough knowledge to do the pull request myself, so if someone wants to work on it, feel free to do it!

URL : https://deno.land/

**Comment by ralyodio** [comment]
I'm looking for wappzyler in Deno too!

**Comment by AliasIO** [comment]
Deno isn't something we can identify directly. If there any technologies that are known to use Deno, we may be able to use that.
