### ISSUE TITLE
Popup is dark in light theme when dark mode compatibility is enabled

### ISSUE THREAD

**Issue by swrobel** [AliasIO/wappalyzer#3116]
**Platform**
WebExtension 5.9.34 (both Google Chrome & Mozilla Firefox)

**Describe the bug**
The popup when clicking the extension icon is always dark when "Enable dark mode compatibility" is checked, even when using a macOS light theme.

Firefox
<img width="646" alt="Screen Shot 2020-05-27 at 9 48 59 AM" src="https://user-images.githubusercontent.com/157270/83049296-c93e4680-9fff-11ea-8df4-29aacb4cf804.png">

Chrome
<img width="492" alt="Screen Shot 2020-05-27 at 9 49 24 AM" src="https://user-images.githubusercontent.com/157270/83049117-84b2ab00-9fff-11ea-9314-9751687798a1.png">

**To Reproduce**
1. Check "Enable dark mode compatibility" option
1. Set operating system theme to Light
1. Click extension icon

**Expected behavior**
Light theme that is shown when "Enable dark mode compatibility" is unchecked should be shown

**Additional context**
cc @kyletaylored

**Comment by AliasIO** [comment]
This will be fixed in the next update, thanks!
