### ISSUE TITLE
Have a unique id per technology

### ISSUE THREAD

**Issue by AdityaAnand1** [AliasIO/wappalyzer#3117]
This repo's readme describes it well
https://github.com/Woorank/wappalyzer-wrapper

```
Convenience wrapper around wappalyzer library.

Cannonicalizes technologies by adding an id that remains constant between versions.
```

Example:

```
const wappalyzerWrapper = require('wappalyzer-wrapper');

await wappalyzerWrapper.analyze({ html, scripts, headers, js });

// [ 
//   { app: 'Google Analytics',
//     version: 'UA',
//     id: 'google-analytics',
//     categories: [ 'analytics' ] },
//   { app: 'jQuery',
//     version: '',
//     id: 'jquery',
//     categories: [ 'javascript-frameworks' ] } 
// ]
```

Uniquely identifying technologies would be requirement for any production app using this as part of it's stack. Should be pretty easy to add and it would be backward compatible.

**Comment by AliasIO** [comment]
The technology name is a unique identifier but it would be good to have a numeric ID or UUID in case the name is updated. The downside is that anyone who adds a technology through a PR will need to generate a unique ID.

**Comment by AdityaAnand1** [comment]
Hmmm, now that I think of it, will there ever be a technology name that is not unique? I'm not sure that it would be so we can keep using technology name as a unique identifier.

I think we can bench this for now, see if it comes up, best to keep PR process quick and easy.

**Comment by AdityaAnand1** [comment]
Ok, so I just realized that technology names keep changing with releases. We really need a unique identifier. 

I have to update my database every time I update wappalyzer, otherwise everything goes out of whack. 

If technology names are not constant, they cannot be treated as primary keys.

For example, "Locomotive" became "LocomotiveCMS" and dozens others have changed since 6.0.x. Any ideas how to fix this?

**Comment by AliasIO** [comment]
It's rare but names do change sometimes. When that happens I treat it as a brand new technology. You may be able to use the `cpe` field as the identifier if it's present.
