### ISSUE TITLE
Empty popup

### ISSUE THREAD

**Issue by smhmd** [AliasIO/wappalyzer#3118]
**Platform**
Which platform does the bug apply to?
* WebExtension (Google Chrome)

**Describe the bug**
After the recent update (`5.10.0`), the popup is empty on all sites:

![image](https://user-images.githubusercontent.com/46059092/83097080-23421900-a09f-11ea-8a9c-59fc684f98ef.png)

**To Reproduce**
1. Go to https://github.com/AliasIO/wappalyzer
2. Click on wappalyzer icon
3. It's empty

**Expected behavior**
To have the technologies listed.

**Comment by AliasIO** [comment]
I just pushed v5.10.1, let me know if that fixes it.

**Comment by amljs** [comment]
@AliasIO  Yes, v5.10.1 fixes the empty popup issue

![wappalyzer](https://user-images.githubusercontent.com/31209960/83100014-81392580-a0cc-11ea-98a4-dbdf3b24afb6.png)

**Comment by smhmd** [comment]
Fixed :+1:

**Comment by nixoncode** [comment]
Please Push the same Update For Microsoft edge. Its currently not working as well
