### ISSUE TITLE
Consider to increase the delay before Wappalyzer start analysing the page

### ISSUE THREAD

**Issue by lucamug** [AliasIO/wappalyzer#3121]
It seems that at least one technology cannot be detected because Wappalyzer is analysing the page before the technology is changing the DOM.

This may affect other technologies too.

I am reporting here a conversation happened in Slack about this topic:

## lucamug Apr 18th at 10:16 AM

I created a Regex to detect the "Elm-ui "library [https://github.com/AliasIO/wappalyzer/blob/master/src/apps.json#L3289]

This is the regex running properly in the terminal:
```
regex = "<style>[\\s\\S]*\\.explain > \\.s[\\s\\S]*\\.explain > \\.ctr > \\.s"; document.body.innerHTML.match(regex)
```
For example in https://freemovies.ltd/

But this seems not working when running in Wappalyzer. The library "Elm-ui" is not detected. Any hint?

One thing to note is that such HTML is not in the HTML source but it is generated dynamically by Javascript after the page load.

## Elbert  1 month ago

Wappalyzer runs on page load so it’s possible that’s the reason why

## lucamug  1 month ago 

@Elbert, thank you for the reply!
With the increase of SPAs, do you think it could make sense to delay the parsing of the DOM few hundred milliseconds? This is what, for example, the Google spider bot does.
Doing so, probably more things would be detectable

## Elbert  1 month ago

There is a slight delay. Are there no other ways to detect Elm?

## lucamug  1 month ago

Yes, I submitted the Elm detection recently (https://www.wappalyzer.com/technologies/javascript-frameworks/elm)
It has many false negative because it relies on a global variable that in many cases is not actually global, because webpack and parcel are wrapping it in an Self-Invoking Function.
I don't see any other way to detect Elm, unless I could analyze the Javascript source code that I think is not possible.
elm-ui is one of the most used library in Elm and it has a signature in the DOM.
My observation was that, maybe, the same as elm-ui is not detected, other technologies could also not be detected

**Comment by AliasIO** [comment]
I'm adding a 1 second delay in the next update, coming very soon.
