### ISSUE TITLE
[Chrome] Clicking a link in the extension popup does nothing

### ISSUE THREAD

**Issue by swrobel** [AliasIO/wappalyzer#3122]
**Platform**
WebExtension 5.10.1 (Google Chrome only)

**To Reproduce**
1. Open any website
1. Click extension icon
1. Click on any tech in the list
1. Nothing happens

**Expected behavior**
Clicking a tech opens a new tab with details on that tech.

**Additional context**
* Firefox is working as of 5.10.1 so maybe that fix broke Chrome?
* In Chrome, right-clicking on the tech & choosing "open in new tab" works but a regular left-click does nothing (that I can discern - no console logs shown when doing "inspect popup").
* "Create an alert for this website" also does nothing.

**Comment by BerkeAras** [comment]
I have the same issue too :(

**Comment by AliasIO** [comment]
I just pushed a silent update to fix this, it should hopefully come through soon.
