### ISSUE TITLE
__cfduid key also used by Marketo

### ISSUE THREAD

**Issue by ccharlton** [AliasIO/wappalyzer#3126]
**Platform**
* WebExtension (Google Chrome)

**Describe the bug**
Found instance where `__cfduid` was thought to be Cloudflare but was actually a Marketo cookie. (image attached)
![cfduid Marketo](https://user-images.githubusercontent.com/263843/83215396-b456d580-a11b-11ea-8d11-091219400612.png)

**Expected behavior**
Determine the 'domain' string further to verify which platform is pushing that cookie.

**Comment by tillkruss** [comment]
Marketo sits behind Cloudflare.

**Comment by kyletaylored** [comment]
I believe the issues has to do with 1st party and 3rd party cookies. If a cookie is being placed by another service that isn't the domain being detected, then should it be accounted for or not? For example, we could detect Marketo through JS objects or scripts, and not by the cookie being placed by an external script.

**Comment by kyletaylored** [comment]
Actually, I see that based on the latest update to the code, it's now using the `chrome.cookies` object, and when we pass in the `domain` attribute that matches the hostname, it also includes subdomains.

https://developer.chrome.com/extensions/cookies#method-getAll

string | (optional) domain | Restricts the retrieved cookies to those whose domains match or are subdomains of this one.
-- | -- | --

It looks like in my latest test, the CloudFlare cookie is actually being set by a subdomain, which is a CNAME alias for a Marketo path, so this actually makes a little sense now...

### Cookies on Pantheon.io
Includes subdomain, `learn.pantheon.io`

![Pantheon.io cookies](https://user-images.githubusercontent.com/1759794/86978854-7bac1200-c145-11ea-8c4f-2c6415b14e14.png)

### Pantheon subdomain
You can see the `learn.pantheon.io` subdomain pointed to a Marketo root landing page path.

![image](https://user-images.githubusercontent.com/1759794/86978998-c4fc6180-c145-11ea-8aeb-21f6c33c4cf6.png)
