### ISSUE TITLE
Doesn't seem to work in servers 

### ISSUE THREAD

**Issue by AdityaAnand1** [AliasIO/wappalyzer#3127]
So, for this library to truly scale up and support regular scanning of thousands (or millions) of URLs, it needs to be deployed on several servers, running in parallel.

Which means running in low memory conditions on barebones linux stack.

I've tried running this on VMs by AWS/Azure/GCM with same results everywhere. Specifically the `await wappalyzer.open(url).analyze()` method chokes everywhere, with no error.

I've done web scraping via pupeteer in cloud before, so I know that pupeteer itself is not the problem.

In order to better understand why this is happening, would it be possible to implement an optional debug logging flag? 

Say, we could provide a `log:true` or maybe `logLevel: 'TRACE|INFO|WARN'` along with the `options` which logs every step that wappalyzer performs (specifically before, after and during the `open` and `analyze` method statements). 

Right now I have no idea what is happening, other than seeing that it just gets stuck. Getting some log output would be the first step to debugging this 😄

**Comment by AliasIO** [comment]
You can get Puppeteer debug output with `env DEBUG="puppeteer:*"`. You can use `site.on('error', () => {})` and `site.on('log', () => {})` (with debug set to `true` in the Wappalyzer options).

**Comment by AdityaAnand1** [comment]
Ok, I'll try that.

Also, even on high memory servers, I left wappalyzer script running for ~20 minutes and now I'm no longer able to ssh into the instance at all.

So, it's not a high memory thing either.

**Comment by AdityaAnand1** [comment]
Was able to ssh and run the `top` command (albeit it took forever).

![image](https://user-images.githubusercontent.com/13274079/83230601-a77fc380-a1a7-11ea-82a0-7b0d8ef4b774.png)

* The server is completely sapped of memory, it would be using swap too much which explains freezing
* This is from iterating over just 1 URL at a time (which resulted in ssh being extremely slow), so if it cannot even handle one URL at a time, then batching would only make the problem worse.
* There are a lot of idle chrome processes sitting for a long time and for some reason, eating up memory and CPU <= My best guess is that these are those same unresolved promises that are left, since I'm using a race condition to break out of wappalyzer promise if it fails to resolve in 5 minutes.

**Comment by AdityaAnand1** [comment]
I have an idea, when the wappalyzer promise fails to return, I've just been sort of ignoring it (which means it stays open forever).

I can try one thing: If it doesn't resolve quickly (Say < 5 mins max), I'll do a `.destroy()` and restart the pupeteer instance, start fresh. So this might take care of cleaning up the stale instances. Will try and report back.

**Comment by AliasIO** [comment]
Yes, that's what I meant with my comment in the other ticket. You could call `destroy()` when a process times out and start it again.

I should also be able to expose Puppeteer's `page.close()` instead of `browser.close()`, which is essentially what `wappalyzer.destroy()` does.

**Comment by AdityaAnand1** [comment]
No matter what I do, it eventually manages to kill a machine slowly 😕 

![image](https://user-images.githubusercontent.com/13274079/83477191-58d86f00-a4b0-11ea-936d-6ef97c5abf2d.png)

I think next, I'll try using nodemon and force stop and restart node processes over and over again, hopefully killing whatever is hogging CPU/RAM in the process and starting over.

Is it possible to enable non-headless mode for pupeteer while debugging in wappalyzer? I'd just like to see for myself what is actually happening. Maybe there might be some clear indicators, like 100s of tabs being left open.

**Comment by AliasIO** [comment]
This should be much better in v6.0.6. You can now also call `destroy()` on the site instance if needed.
