### ISSUE TITLE
version mismatch

### ISSUE THREAD

**Issue by Kikobeats** [AliasIO/wappalyzer#3129]
<img width="1236" alt="Screenshot 2020-05-29 at 10 33 59" src="https://user-images.githubusercontent.com/2096101/83239280-f291da80-a197-11ea-925a-a28fb6edb752.png">

npm is reporting some 6.x versions living in the npm registry, but I can't see these tags there.

is it an error?

**Comment by AliasIO** [comment]
Ah, I didn't tag it but what's currently in the repo is what's on NPM.
