### ISSUE TITLE
How to use wappalyzer core

### ISSUE THREAD

**Issue by Kikobeats** [AliasIO/wappalyzer#3130]
Hello,

I always felt this library is doing too much: It should be focused on technology detection rather than get HTML step using puppeteer/jsdom and the rest of the stuff.

That can be easily delegated into a different package, making wappalyzer, simple, and easy to connect with any other package. IMO, it's an effort the library is assuming wrongly, losing the focus of detect technologies in a static way.

I just created [simple-wappalyzer](https://github.com/Kikobeats/simple-wappalyzer) for doing that, where the content is extracted using [html-get](https://github.com/microlinkhq/html-get)

```js
const getHTML = require('html-get')
const { url, html, statusCode, headers } = getHTML('https://kikobeats.com')
```

and then it is passed against wappalyzer:

```js
const result = await wappalyzer({ url, html, statusCode, headers })
```

I was able to do that since I created a [static browser](https://github.com/Kikobeats/simple-wappalyzer/blob/master/src/browser.js) (very similar to your old zombie browser) that essentially setup all the things in the way wappalyzer can consume them.

But at `wappalyzer@6`, `wappalyzer.analyze` is never a thing

```js
  test/index.js:13

   12:   )
   13:   const result = await wappalyzer({ url, statusCode, html, headers })
   14:   t.snapshot(result)

  Rejected promise returned by test. Reason:

  TypeError {
    message: '(intermediate value).analyze is not a function',
  }
```

I thought that's okay cause this is a major release and breaking change are allowed, but as much I review the code, it gets more complicated to follow and highly coupled to `puppeteer` logic.

I want to ask how to use `wappalyzer@6` without depending on puppeteer, or even better, how to connect `wappalyzer` with any others libraries in the most deterministic and simple way, just providing the data necessary, nothing more

**Comment by AliasIO** [comment]
You're right and I've been thinking about restructuring. Perhaps a separate `wappalyzer-core` package that's a dependency of `wappalyzer`.

Right now you _can_ call functions on `wappalyzer.js` directly, including `analyze()`, bypassing all the Puppeteer logic.

**Comment by Kikobeats** [comment]
@AliasIO I tried but no success, can you suggest me how parameters should be passed?

**Comment by AliasIO** [comment]
@Kikobeats if you can wait, I should have a much improved core package available in the next 1-2 weeks.

**Comment by AliasIO** [comment]
Here it is, please let me know what you think.

https://www.npmjs.com/package/wappalyzer-core

**Comment by Kikobeats** [comment]
Thanks for that, it's a better affordable interface 🙂

https://github.com/Kikobeats/simple-wappalyzer/pull/6

some changes I did:

- Fetch `apps` on build time, so always is up to date.
- Added a new `getMeta` function, essentially based on your implementation.
- Remove unnecessary things, like `statusCode`.

How does it look to you? PS: I invited you as a collaborator 🙂

**Comment by AliasIO** [comment]
Looks good!
