### ISSUE TITLE
Travis CI fails after modifying src/icons

### ISSUE THREAD

**Issue by wxh06** [AliasIO/wappalyzer#3138]
**Platform**
Travis CI

**Describe the bug**
The CI fails after modifying [`src/icons`](https://github.com/AliasIO/wappalyzer/tree/master/src/icons) directory.
It seems that this is caused by outdated build cache.

**To Reproduce**
1. Fork [`AliasIO/wappalyzer`](https://github.com/AliasIO/wappalyzer)
2. Create or delete files in [`src/icons`](https://github.com/AliasIO/wappalyzer/tree/master/src/icons), and modify [`src/apps.json`](https://github.com/AliasIO/wappalyzer/tree/master/src/apps.json)
3. Open pull request
4. See error such as `Error: Missing file for app "...": src/drivers/webextension/images/icons/...`, `Error: Stray file (no associated app): src/drivers/webextension/images/icons/...`, but the file is exist in [`src/icons`](https://github.com/AliasIO/wappalyzer/tree/master/src/icons)

**Expected behavior**
Run pr tests without the non-match cache of [`src/drivers/webextension/images/icons`](https://github.com/AliasIO/wappalyzer/tree/master/src/icons) in [`AliasIO:master`](https://github.com/AliasIO/wappalyzer/tree/master)

**Additional context**
#3136 <https://travis-ci.org/github/AliasIO/wappalyzer/builds/693066154>
#3137 <https://travis-ci.org/github/AliasIO/wappalyzer/builds/693158349>
#3141 <https://travis-ci.org/github/AliasIO/wappalyzer/builds/693788984>
#3147 <https://travis-ci.org/github/AliasIO/wappalyzer/builds/695628443>

**Comment by AliasIO** [comment]
The `src/icons` directory has been moved to `src/drivers/webextension/images/icons`.

**Comment by wxh06** [comment]
I know that. I've edited the comment.
It seems to be caused by the build cache of `src/drivers/webextension/images/icons`

**Comment by AliasIO** [comment]
Thanks, this has been fixed.
