### ISSUE TITLE
Google Ads + Bing Ads conversion tracking tags

### ISSUE THREAD

**Issue by craigpaddock** [AliasIO/wappalyzer#3143]
Love this extension!!!

Am I being greedy by asking for you guys to check for Google Ads and Bing Ads conversion tracking tags? 

Thanks!

**Comment by cpaddock56** [comment]
Any update on this?

**Comment by AliasIO** [comment]
Google Ads, Google Ads Conversion Tracking and Microsoft Advertising are currently included.

**Comment by cpaddock56** [comment]
THANK YOU
