### ISSUE TITLE
Empty box after last wappalyzer update on Microsoft Edge (Chrome based)

### ISSUE THREAD

**Issue by abbas0v** [AliasIO/wappalyzer#3144]
**Platform**
Which platform does the bug apply to?
* WebExtension (Microsoft Edge)

**Describe the bug**
Wappalyzer does not work properly after the last update. When I click on the Wappalyzer icon, only the blank white window opening. This issue happened after the last wappalyzer update.

![Annotation 2020-06-04 131420](https://user-images.githubusercontent.com/43417523/83745014-9e8a6880-a665-11ea-8ab8-85dfb8e934b0.png)

**Comment by AkgunFatih** [comment]
![Capture](https://user-images.githubusercontent.com/39423167/83926525-544ed780-a78a-11ea-9134-879c85fe07b4.PNG)

**Comment by fontvu** [comment]
Same for me (Edge 83.0.478.45) in both macOS 10.15.5 and Windows 10 (1903 and 2004), I have 3 devices.

**Comment by AliasIO** [comment]
This should be fixed in v6.0.4.

**Comment by AkgunFatih** [comment]
@AliasIO edge version is still on v5.10.0

**Comment by AliasIO** [comment]
@AkgunFatih It's in review currently.
