### ISSUE TITLE
Tech Request: Grafana

### ISSUE THREAD

**Issue by RandomRobbieBF** [AliasIO/wappalyzer#3145]
Hey,

I was thinking it would be worth adding grafana to the list of hits.

It looks like you can match on `grafana-app` inside the html and `Set-Cookie: grafana_sess` in the header.

Example systems:
https://play.grafana.org/login

Local docker version.

```
docker run -d -p 3000:3000 --name=grafana grafana/grafana
```

**Comment by AliasIO** [comment]
Added!
