### ISSUE TITLE
Hyperlink to Gihub for icons not working

### ISSUE THREAD

**Issue by deepakdp1989** [AliasIO/wappalyzer#3148]
**Platform**
Which platform does the bug apply to?
* Website

**Describe the bug**
This web page: https://www.wappalyzer.com/docs/dev/contributing has a hyperlink to https://github.com/aliasio/wappalyzer/tree/master/src/icons which doesn't open.

**To Reproduce**
1. Go to 'https://www.wappalyzer.com/docs/dev/contributing'
2. Click on 'src/icons'. Find using ctrl+f.
3. See error

**Expected behavior**
This web page should open a valid github page with the icons: https://github.com/aliasio/wappalyzer/tree/master/src/icons

**Comment by oyeyipowale** [comment]
hey @deepakdp1989, followed the steps to reproduce and I believe the issue has probably been fixed cuz I couldn't find `"src/icons"`. The closest I found was `"src/drivers/webextension/images/icons"` which worked fine. 👍

**Comment by deepakdp1989** [comment]
Adding a new application 

To add a new application, edit src/apps.json and add a square icon to src/icons (preferably an SVG file, otherwise a 64x64 or 32x32 PNG file).

Read the above line again and check. Use ctrl+f if needed

**Comment by deepakdp1989** [comment]
Hi @oyeyipowale, kindly check my comment above!

**Comment by AliasIO** [comment]
The links has been fixed.
