### ISSUE TITLE
Database type shows over WordPress as icon

### ISSUE THREAD

**Issue by frykandelbroadsje** [AliasIO/wappalyzer#3169]
**Platform**
Which platform does the bug apply to?
WebExtension (Mozilla Firefox)

**Describe the bug**
When I check out a WordPress site I expect, as has been the case before the recent update, a WordPress icon in the top right corner instead of the logo for MySQL. Now I have to click on Wappalyzer to find the technology they are using. I'd rather see the WordPress logo there because to me (and I guess many others) that's more important information

**To Reproduce**
1. Go to a WordPress website
2. Check out the Wappalyzer extention without clicking on it

**Expected behavior**
The logo of WordPress instead of the database type

![Screenshot when visiting a wordpress website](https://user-images.githubusercontent.com/61621807/84408165-1af3ed00-ac0c-11ea-92ee-a496d681a84d.png)

I can still see that it is a WordPress website, but I want to see that without having to click

**Comment by AliasIO** [comment]
Thanks, fixed in 94a4ee530625bb988e4dd12e7a66e867385b84b9. For now you can pin the CMS category in the popup to prioritise it.
