### ISSUE TITLE
Tech request: Blockbaud

### ISSUE THREAD

**Issue by bmagnantb** [AliasIO/wappalyzer#3170]
ran into wappalyzer not detecting this today:
https://www.blackbaud.com/

i'll try to take a closer look at this at some point to find some clear identifiers, but i haven't worked with this so can't say for sure right now.

**Comment by connorwhitman** [comment]
You were probably running into the bug many people were with the last major update: Issue https://github.com/AliasIO/wappalyzer/issues/3159

The site you listed is running Sitefinity for its CMS and Marketo for marketing automation (among other analytics & tracking tools).

**Comment by AliasIO** [comment]
Added, thanks!
