### ISSUE TITLE
Stopped Working

### ISSUE THREAD

**Issue by 8p-design** [AliasIO/wappalyzer#3172]
**Platform**
Which platform does the bug apply to?
* WebExtension (Google Chrome)

**Describe the bug**
Does not report wensite tech. All websites

**To Reproduce**
1. Go to 'website'
2. Click on 'the addon icon'
3. View that nothing is reported
4. See screenshot

**Expected behavior**
I expect it to show technology of the website

![Screen Shot 2020-06-11 at 16 59 28](https://user-images.githubusercontent.com/4120618/84438766-16780600-ac05-11ea-936e-c5263e5a6428.png)

**Comment by AliasIO** [comment]
Is this version 6.0.7?

**Comment by Silentxknight** [comment]
Still not properly working on YouTube, Showing less info, 
V-6.0.8

**Comment by 8p-design** [comment]
> Is this version 6.0.7?
6.0.8

**Comment by b1g0af** [comment]
Same here.
Wappalyzer: 6.0.8
Chrome: 83.0.4103.97
Windows: 10.0.17134 Build 17134

**Comment by tobiaslins** [comment]
I saw the same, now it's working again (6.0.8)

But I recognized some technologies are not recognized anymore that were working before. For example splitbee.io

Thanks!

**Comment by hsul4n** [comment]
Sometimes not working (6.0.8)

**Comment by AliasIO** [comment]
Please try 6.0.9. If there are still issues, please provide examples and I'll look into them.

**Comment by tobiaslins** [comment]
@AliasIO 6.0.9 fixed most of the tools. Splitbee.io is not found anymore https://github.com/AliasIO/wappalyzer/blob/master/src/apps.json#L10596-L10603

**Comment by Presskopp** [comment]
same for me, only working occasionally using 6.0.11

**Comment by henryz00** [comment]
Same here, not working on half the sites, version 6.0.15 on Chrome 83, macOS

**Comment by tobiaslins** [comment]
@AliasIO 
It still doesn't recognize it anymore using `script`.

```
"script": "^https:\\/\\/cdn\\.splitbee\\.io\\/sb\\.js",
```

this was working before. The behavior changed maybe? Let me know how to fix this

**Comment by AliasIO** [comment]
This will be fixed v6.2.3.
