### ISSUE TITLE
Window is out of bound on left

### ISSUE THREAD

**Issue by 8p-design** [AliasIO/wappalyzer#3173]
**Platform**
Which platform does the bug apply to?
* WebExtension (Google Chrome)

**Describe the bug**
When the Wappalyzer is on the LEFT in the toolbar (I have 27 icons), the window that opens goes out of bound on the left, so half of the window is hidden.

**To Reproduce**
place the icon on the left and click the app icon

**Expected behavior**
Align to left window edge

**Comment by AliasIO** [comment]
Is this still an issue? I can't reproduce it.

**Comment by 8p-design** [comment]
Seems resolved. Thanks
