### ISSUE TITLE
don't work on Microsoft Edge(Chromium)

### ISSUE THREAD

**Issue by liujiayii** [AliasIO/wappalyzer#3174]
**Platform**
Which platform does the bug apply to?
* WebExtension (Microsoft Edge, Mozilla Firefox)
* NPM
* Bookmarklet
* Website https://microsoftedge.microsoft.com/addons/detail/mnbndgmknlpdjdnjfmfcdjoegcckoikn

**Describe the bug**
Upgrade may be required,my English is bad ,sorry

**To Reproduce**
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Additional context**

**Comment by AliasIO** [comment]
An updated version is currently awaiting approval, it should become available soon.

**Comment by liujiayii** [comment]
thanks

**Comment by AliasIO** [comment]
Please let me know if this is still an issue?

**Comment by liujiayii** [comment]
Solved 
![image](https://user-images.githubusercontent.com/38902744/85084675-1df06e00-b208-11ea-9d9d-cf21e8006d53.png)
