### ISSUE TITLE
Detected technologies priorities changed

### ISSUE THREAD

**Issue by ali11007** [AliasIO/wappalyzer#3177]
**Platform**
Which platform does the bug apply to?
Happened on Chrome

**Describe the bug**
Detected technology icon has been changed to wordpress for those which implies wordpress. Before wappalyzer was showing that technology. (For example: Boom or Boldgrid)

**To Reproduce**
Visit websites like:
demo1.ov2.com
boldgrid.com

**Expected behavior**
Wappalyzer shows the technology's icon which implied wordpress.

**Comment by AliasIO** [comment]
It will display the first CMS it finds, for me it's actually showing Boom first for me on your first example.
