### ISSUE TITLE
Bookmarklet not working in Safari

### ISSUE THREAD

**Issue by sleepinzombie** [AliasIO/wappalyzer#3179]
**Platform**
Which platform does the bug apply to?
* Bookmarklet
* Website

**Describe the bug**
On Safari, using the bookmarklet doesn’t work anymore. It just opens an empty modal.

**To Reproduce**
1. Go to https://www.wappalyzer.com/download
2. Click on ‘Bookmarklet’

**Expected behavior**
The modal would contain technology Wappalyzer identified.

**Comment by bakerhimself** [comment]
I have the same issue, tried the bookmarklet with different browsers, still not working

**Comment by AliasIO** [comment]
It should be working again now.

**Comment by sleepinzombie** [comment]
Hello @AliasIO, the bookmarklet is not working again. Tested on the latest macOS Catalina & the latest stable build of iOS 14.
