### ISSUE TITLE
Extension is logging on the browser console

### ISSUE THREAD

**Issue by DaudiMuriu** [AliasIO/wappalyzer#3180]
**Platform**
Which platform does the bug apply to?
* WebExtension (Google Chrome, Mozilla Firefox)
* NPM
* Bookmarklet
* Website
Web extension for google chrome
**Describe the bug**
The Extension is logging on the browser console
**To Reproduce**
Steps to reproduce the behaviour:
2. Click on '...'
3. Scroll down to '...'

**Expected behaviour
<img width="1680" alt="wappalyzer 2" src="https://user-images.githubusercontent.com/33577405/84596561-28f17a00-ae67-11ea-837c-161755a996ae.png">
<img width="1453" alt="Wappalyzer" src="https://user-images.githubusercontent.com/33577405/84596565-2ee75b00-ae67-11ea-8081-4120eee354b4.png">

**
No logging on the browser console
**Additional context**

**Comment by machadomatt** [comment]
Same bug here, it happens on:
- Google Chrome 83.0.4103.97
- Brave 1.9.80 with Chromium: 81.0.4044.138
- Firefox Developer 78.0b6 (64-bit)
- Vivaldi 3.1.1929.34

Wappalyzer Extension Version: 6.0.9

**Comment by AliasIO** [comment]
Sorry about that, I'll push a fix today.
