### ISSUE TITLE
`cpe` property is not being returned anymore by the NPM driver

### ISSUE THREAD

**Issue by faheel** [AliasIO/wappalyzer#3183]
**Platform**
NPM

**Describe the bug**
The `cpe` property is not being returned anymore by the NPM driver, which seems to have been deleted in commit https://github.com/AliasIO/wappalyzer/commit/7cd761c2aeeb1cea9bed0659a3d18e72bb2f221e#diff-52a5c598939fc2481d3f8a891f85d3eaL546 when the NPM driver was refactored.

**To Reproduce**
1. Install the latest version of Wappalyzer from NPM.
2. Run Wappalyzer on wordpress.org:
   ```sh
   wappalyzer https://wordpress.org -r -D 2 -m 8 -w 10000 -t 1000
   ```
3. The `cpe` property is missing from all of the detected applications.

**Expected behavior**
The `cpe` property should be available for all of the detected applications. As earlier, its value should be `null` if it is not defined for an application.

**Comment by AliasIO** [comment]
Fixed in v6.0.12, thanks!
