### ISSUE TITLE
Add Fluent UI (aka Office UI Fabric)

### ISSUE THREAD

**Issue by Be1con** [AliasIO/wappalyzer#3185]
I started developing website based on React and [Fluent UI](https://developer.microsoft.com/en-us/fluentui#/), and this plug-in couldn't detect this framework. So, I would like to request this technology to be able to see on the plugin.

**Comment by kyletaylored** [comment]
You may request a new technology to be added but chances of having it included are greatly improved if you submit a pull request. Please refer to the [documentation](https://docs.wappalyzer.com/dev/contributing.html#adding-a-new-application).
