### ISSUE TITLE
Wappalyser not showing in Firefox 77.0.1

### ISSUE THREAD

**Issue by karlosb** [AliasIO/wappalyzer#3186]
**Platform**
Mac OSX 10.15.5
Firefox 77.0.1
* WebExtension (Google Chrome, Mozilla Firefox)
Wappalyser

**Firefox addons in use**
AdBlocker YoutTube
Privacy Badger
Web Developer

**Describe the bug**
Wappalyser icon (to display used website software/platforms) not showing in URL address bar, when loading any given website address.

**To Reproduce**
Load up any website URL and the issue is happening.

**Expected behavior**
Should show relevant software icons for website URL.

**Comment by imatamor** [comment]
I can confirm this issue is happening and it's not an exceptional case

**Comment by gizmecano** [comment]
I have to confirm that the extension still doesn't work with the last update I made this morning.

Furthermore, it's impossible to know **which exact version** of Wappalyzer is installed, because the devoted tab remains empty (cf. image).

![wapbug](https://user-images.githubusercontent.com/852661/84733536-c9968580-af9e-11ea-9dd2-5c284008cc0c.png)

**Comment by AliasIO** [comment]
I can't reproduce the issue, on the same version of Mac OS and Firefox.

Can one of you please navigate to `about:debugging#/runtime/this-firefox` and click `Inspect` on the add-on? There may be some errors logged in the 'Console' tab that explain what's happening.

**Comment by AliasIO** [comment]
I pushed v6.0.13 today, please let me know if that fixes it.

**Comment by GorkaPuente** [comment]
Hi,

I attach the screenshot of the console, there are several errors (v6.0.15):

![Screenshot 2020-06-17 at 09 48 50](https://user-images.githubusercontent.com/1804808/84870690-e8b91400-b07f-11ea-9fa4-aa6839b0f9af.png)

**Comment by GorkaPuente** [comment]
Sorry, now it works!

![Screenshot 2020-06-17 at 09 55 07](https://user-images.githubusercontent.com/1804808/84871307-a93ef780-b080-11ea-87b2-59a90217ea9a.png)

**Comment by AntonioRedondo** [comment]
I'm facing a similar issue on Firefox 76.0 and Wappalyzer 6.0.15. The icon doesn't show up anymore on the toolbar, neither the icon is available to be dragged into the bar from the 'Customise Firefox' screen.

The icon however appeared on the address bar. But it cannot be dragged outside it. You can remove it by right clicking the icon and pressing _Remove from Address Bar_. But then there is no way to put it back.

**Comment by karlosb** [comment]
Hi AliasIO, 

I've just updated to 6.0.13 but still no icon.

Here are my console errors:
<img width="1440" alt="1" src="https://user-images.githubusercontent.com/7140268/84896411-d51ba680-b09b-11ea-88e3-2a433c0a6e95.png">
<img width="1440" alt="2" src="https://user-images.githubusercontent.com/7140268/84896420-d8af2d80-b09b-11ea-82f9-8ac40e7b3d8c.png">
<img width="1438" alt="3" src="https://user-images.githubusercontent.com/7140268/84896427-dc42b480-b09b-11ea-8276-f538d7f58f13.png">

**Comment by gizmecano** [comment]
Well, I have just updated the extension through the Firefox process (`77.0.1`, 64bts).

The icon has reappeared in the URL bar, but the release notes are still not displayed.

Here is the content of the debugging console:

```
Erreur d’analyse XML : erreur de syntaxe
Emplacement : moz-extension://ac6232d2-a8c7-4277-a141-faeffe389483/rules/default.rulesets
Numéro de ligne 1, Colonne 1 : default.rulesets:1:1
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
    normalizeStorageError resource://gre/modules/ExtensionStorageIDB.jsm:831
    method chrome://extensions/content/child/ext-storage.js:273
    AsyncFunctionThrow self-hosted:697
uncaught exception: null
TypeError: Driver.cache is undefined driver.js:351:5
TypeError: Driver.cache is undefined driver.js:269:20
TypeError: Driver.cache is undefined 2 driver.js:351:5
wappalyzer | utils | Error: "An unexpected error occurred" utils.js:49:15
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
uncaught exception: null
wappalyzer | utils | Error: "An unexpected error occurred" utils.js:67:15
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
wappalyzer | utils | Error: "An unexpected error occurred" utils.js:67:15
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
wappalyzer | utils | Error: "An unexpected error occurred" utils.js:67:15
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
wappalyzer | utils | Error: "An unexpected error occurred" utils.js:67:15
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
wappalyzer | utils | Error: "An unexpected error occurred" utils.js:67:15
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
wappalyzer | utils | Error: "An unexpected error occurred" utils.js:67:15
wappalyzer | utils | Error: "An unexpected error occurred" utils.js:67:15
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
wappalyzer | utils | Error: "An unexpected error occurred" utils.js:67:15
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
wappalyzer | utils | Error: "An unexpected error occurred" utils.js:67:15
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
wappalyzer | utils | Error: "An unexpected error occurred" utils.js:67:15
wappalyzer | utils | Error: "An unexpected error occurred" utils.js:67:15
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
wappalyzer | utils | Error: "An unexpected error occurred" utils.js:67:15
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
wappalyzer | utils | Error: "An unexpected error occurred" utils.js:67:15
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
wappalyzer | utils | Error: "An unexpected error occurred" utils.js:67:15
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
```

**Comment by karlosb** [comment]
Wappalyzer appears to be now working again for some reason. 

So all good here. 

Just for reference: my setup is now Firefox 77.0.1 / Wappalyzer 6.0.15

**Comment by gizmecano** [comment]
I forgot to say my OS is Windows 10 Version 2004.

As release notes aren't displayed, I'm unable to find the exact version of Wappalyzer: it may be [6.0.15](https://addons.mozilla.org/en-US/firefox/addon/wappalyzer/versions/) (as I used the native Firefox updating process) or [6.0.13](https://github.com/AliasIO/wappalyzer/releases/tag/v6.0.13) (the last tagged release on the GitHub repository).

**Comment by AliasIO** [comment]
Is anyone still having an issue on 6.0.13?

**Comment by gizmecano** [comment]
> Is anyone still having an issue on 6.0.13?

The last version I installed (`6.0.15` and not `6.0.13` according to `about:addons` details) seems to work properly (only a minor issue persists: release note in the extension panel [remains empty as previously](https://github.com/AliasIO/wappalyzer/issues/3186#issuecomment-644531762)).

**Comment by AliasIO** [comment]
@gizmecano I don't see that tab at all.

<img width="689" alt="Screen Shot 2020-06-22 at 11 03 37 am" src="https://user-images.githubusercontent.com/77259/85239648-06b7b780-b478-11ea-8b4b-888724fb2427.png">

**Comment by gizmecano** [comment]
Oh! Really weird...

I paste below captures of the four tabs which are available in `about:addons` (internal path seems to be `addons://detail/wappalyzer@crunchlabz.com`).

Of course, texts content appears dissimilar due to translation.

I enlarged the last "_Notes de version_" ("Release notes") to show that it is wholly empty.

![1. details](https://user-images.githubusercontent.com/852661/85253944-79686900-b45f-11ea-809f-598ddca16937.png)

![2. options](https://user-images.githubusercontent.com/852661/85253976-8be2a280-b45f-11ea-9ecc-b76b401a2433.png)

![3. permissions](https://user-images.githubusercontent.com/852661/85253988-913fed00-b45f-11ea-9e05-27eea2053687.png)

![4. release-notes](https://user-images.githubusercontent.com/852661/85254007-9b61eb80-b45f-11ea-8723-7be47cdca9c2.png)
