### ISSUE TITLE
sphinx incorrect URL

### ISSUE THREAD

**Issue by amirmasoud** [AliasIO/wappalyzer#3189]
**Platform**
Which platform does the bug apply to?
* Website

**Describe the bug**
sphinx redirects to http://sphinx.pocoo.org/ which is not working and it should be https://www.sphinx-doc.org/en/master/ according https://github.com/sphinx-doc/sphinx.

**To Reproduce**
1. Go to 'https://www.wappalyzer.com/technologies/documentation-tools/sphinx'
2. Click on 'Visit webiste'
3. See error

**Expected behavior**
Should redirect to correct webiste.

**Additional context**
I would would make a PR if anyone points out to a how-to change technology url.

**Comment by wxh06** [comment]
Thanks!
Pull request #3190 will fix this issue.

**Comment by wxh06** [comment]
> I would would make a PR if anyone points out to a how-to change technology url.

See https://www.wappalyzer.com/docs/dev/contributing
For this case, just edit https://github.com/AliasIO/wappalyzer/blob/eb2dfc714aa03232dc7e6c87a9e807bff2369426/src/apps.json#L10581
