### ISSUE TITLE
Translation's not working in popup

### ISSUE THREAD

**Issue by wxh06** [AliasIO/wappalyzer#3191]
#### Platform
> Which platform does the bug apply to?

* WebExtension (Google Chrome)

#### Describe the bug
> A clear and concise description of what the bug is.

The popup is always in English, although the `_locales` file exists.

#### To Reproduce
> Steps to reproduce the behavior:

1. Change to another language
2. Click the Wappalyzer extension icon.

#### Expected behavior
> A clear and concise description of what you expected to happen.

Show popup in the current language.

#### Additional context
> Add any other context about the problem here.

It works correctly in the option page.

![屏幕快照 2020-06-18 上午10 10 18](https://user-images.githubusercontent.com/29367025/84969776-f6d46680-b14b-11ea-9bb4-0b4852949f7a.png)

**Comment by AliasIO** [comment]
Thanks, this will be fixed in the next update!

**Comment by wxh06** [comment]
@AliasIO It still doesn't work!
