### ISSUE TITLE
Does wappalyzer support ipv6 ?

### ISSUE THREAD

**Issue by doudouba** [AliasIO/wappalyzer#3195]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is, e.g. I'm always frustrated when [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by doudouba** [comment]
Does wappalyzer support ipv6? I have try,but not!

**Comment by doudouba** [comment]
for example:
docker run --rm  wappalyzer/cli http://[2008::140]:9090
{"urls":{"http://[2008::140]:9090/":{"status":0,"error":{"type":"NO_RESPONSE","message":"No response from server"}}},"applications":[],"meta":{"language":""}}
============
actually, it did not send out a package

**Comment by AliasIO** [comment]
That should work, are you getting an error? You may need to put the URL in quotes.
