### ISSUE TITLE
Not working on Chrome installed from chrome extension store

### ISSUE THREAD

**Issue by bgxdoc** [AliasIO/wappalyzer#3199]
Steps to reproduce:
1) download from https://chrome.google.com/webstore/detail/wappalyzer/gppongmhjkpfnbhagpmjfkannfbllamg?hl=en
2) install on latest windows chrome browser 
3) if you click on the wapplyzer extension after install it will simply show you the option of right click instead of showing the related technology of website.

**Comment by connorwhitman** [comment]
Check your version, there were issues ~ a month ago (See issue: https://github.com/AliasIO/wappalyzer/issues/3159).

Currently working on Chrome with Wappalyzer version 6.0.15 for me.
