### ISSUE TITLE
taking a long time problem;

### ISSUE THREAD

**Issue by yigerenwanshua** [AliasIO/wappalyzer#3206]
if domain is bad，The following code is take a long time ,such as request random url "https://mnasdoiawdlkal.com/"
sorry，i'm english is bad,

const links = await (    
      await page.evaluateHandle(() =>
        Array.from(document.getElementsByTagName('a')).map(         
          ({ hash, hostname, href, pathname, protocol, rel }) => ({
            hash,
            hostname,
            href,
            pathname,
            protocol,
            rel
          })
        )
      )
    ).jsonValue()

**Comment by AliasIO** [comment]
You can set `maxWait` to a lower value.

https://www.npmjs.com/package/wappalyzer

**Comment by yigerenwanshua** [comment]
The default of 5 seconds is acceptable to me,
"Array.from(document.getElementsByTagName('script'))"  this code get script tag is fast,
but  "document.getElementsByTagName('a')"， only get "a" tag is long ,It's a little strange

**Comment by yigerenwanshua** [comment]
not this problem,default 5 second is acceptable to me,i think because set maxwait，so not get document ,error show "document is not defined",so puppeteer use page.evaluateHandle execute JS get tag can take long time

**Comment by AliasIO** [comment]
I'm not seeing this behaviour even when setting `maxWait` to something low like `1`.

**Comment by yigerenwanshua** [comment]
oh,Maybe  my network didn't request DNS or slow
thinks
