### ISSUE TITLE
How can i add my CMS logo to wappalyzer to show my logo in used extensions list?

### ISSUE THREAD

**Issue by websolutiontools** [AliasIO/wappalyzer#3208]
I had written one CMS based on the Laravel framework. now I want, to show my CMS logo in the wappalyzer list in chrome extension. what should I do for this?

Thanks for your kindly reply.
WebSolution.tools

**Comment by kyletaylored** [comment]
You may request a new technology to be added but changes of having it included are greatly improved if you submit a pull request. Please refer to the [documentation](https://docs.wappalyzer.com/dev/contributing.html#adding-a-new-application).
