### ISSUE TITLE
Feature: pass custom headers to wappalyzer.open

### ISSUE THREAD

**Issue by hazcod** [AliasIO/wappalyzer#3214]
**Is your feature request related to a problem? Please describe.**
Sometimes the technology of authenticated websites needs to be inspected.

**Describe the solution you'd like**
The possibility to pass custom headers to all wappalyzer requests using the NPM wappalyzer library.

**Comment by AliasIO** [comment]
Added in 94c275b195591af7114c0ff1558613b27131d57a, thanks for the suggestion! You can either set them in the options or pass them to `site.open()`.
