### ISSUE TITLE
Track webAR as technology

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#3216]
This request is for adding support for webAR (e.g. Apple AR Quick Look OR via Google's Model viewer). More context here - https://discuss.httparchive.org/t/adoption-of-webar-in-ecommerce/1993

Not 100% sure on detection mechanism at this moment but Apple AR Quick look uses .usdz format and Android uses .gltf format and there is a model-viewer web component to render this which looks like this

<model-viewer alt="Astronaut model" src="Astronaut.gltf" ios-src="Astronaut.usdz" ar>

Useful articles - 
https://www.viewar.com/blog/how-ready-is-webar/
https://developers.google.com/web/updates/2019/05/model-viewer-ar

Example for testing - Search fur 'burberry surfboard' and access the product pages on iOS/Safari

**Comment by rockeynebhwani** [comment]
@AliasIO - I can do PR for this but which category you recommend for this? I can't find anything suitable.. or you want me to add a new category for this?

**Comment by AliasIO** [comment]
I think we can use 'Miscellaneous' for now.

**Comment by rockeynebhwani** [comment]
ok

**Comment by rockeynebhwani** [comment]
Whoever is picking this, can you use following information
Technology | Website | Pattern | Example site
------------ | ------------- | ------------- | -------------
WebAR|https://modelviewer.dev/|Look for presence of '<model-viewer' OR '.usdz' OR '.glb' in HTML|https://modelviewer.dev/examples/augmented-reality.html

**Comment by rockeynebhwani** [comment]
@AliasIO pls review

**Comment by rockeynebhwani** [comment]
This has been merged. Closing this
