### ISSUE TITLE
Improve Detection of AMP sites

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#3217]
**Is your feature request related to a problem? Please describe.**
AMP detection was added to Wappalyzer as part of https://github.com/AliasIO/wappalyzer/issues/2935 but in real world this doesn't provide good picture due to the way sites are build for AMP. Let me try to explain with some examples -

1) Sites which use two different URLS for AMP version (for whatever technical constraints they may have)

direct.asda.com has amp.direct.asda.com has AMP equivalent. Wappalyzer identified amp.direct.asda.com as sites with AMP framework but doesn't identify same for direct.asda.com even though direct.asda.com has AMP canonical tag 
<link rel="amphtml" href="https://amp.direct.asda.com/george/clothing/10,default,sc.html">

2) Another example 
https://www.snapdeal.com/product/redmi-note-8-pro-128gb/6917529702717010640 has AMP equivalent on https://m.snapdeal.com/product/redmi-note-8-pro-128gb/6917529702717010640/amp but main site is not classified using AMP even though it has AMP canonical tag.

If we mark primary site having AMP canonical as using AMP framework, it will help with analysis like this - https://discuss.httparchive.org/t/detect-amp-as-a-technology/1873/5

**Describe the solution you'd like**
Tag sites with AMP canonical tag as using 'AMP framework' as these sites most likely to have another URL running AMP. This will provide better visibility with respect to adoption of AMP technology.

**Describe alternatives you've considered**
None

**Additional context**
None

tagging @nathaniel-tokabot

**Comment by AliasIO** [comment]
Happy to include that, do you want to submit a pull request?

**Comment by rockeynebhwani** [comment]
@AliasIO Please review

**Comment by rockeynebhwani** [comment]
merged.. closing this
