### ISSUE TITLE
Improve detection of eCommerce sites using Schema.org

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#3218]
**Is your feature request related to a problem? Please describe.**
Currently detection of eCommerce sites is not very useful in scenarios where the site is not using a standard eCommerce platform (e.g. Shopify / BigCommerce). Many big enterprises have home grown eCommerce platforms which are not detected by wappalyzer currently. This will become more evident when in future sites move to Headless / API first architecture. 

**Describe the solution you'd like**
There is an easy solution to this if we detect eCommerce sites based on presence of Schema.org tags. Most eCommerce sites will have Schema.org tags implemented because of Google using these tags for SEO purpose. We can use presence of https://schema.org/Product as **another signal** to identify sites in eCommerce category. This will in addition to mechanisms we have today

we need to look for following in source of the page -

itemtype="http://schema.org/Product"

**Describe alternatives you've considered**

**Additional context**
This will not identify a site in eCommerce category when Wappalyzer is used on a page which is not a product page but even if we have this identified on some product pages, it can be of help.

**Comment by AliasIO** [comment]
Do you have a suggestion on how to present this in the popup? We could add a generic 'custom ecommerce platform' technology but I'm not sure how useful that would be.

**Comment by rockeynebhwani** [comment]
@AliasIO - This is a tricky one. I was thinking of adding a new category called 'Web Standards' and add Schema.org as technology and add eCommerce as associated category.

But problem with this is that Schema.org has different flavours and only Schema.org/Product is strong indicator eCommerce category. 

Or we can add each flavour of Schema.org but then are too many .. 

Any other thoughts? @rviscomi - Do you have any suggestions?

**Comment by AliasIO** [comment]
I think this is going beyond what I want the extension to do. We can use Schema.org attributes to identify specific technologies but I don't think we be should tracking web standards. Adding Schema.org to the Ecommerce category doesn't seem right either.
