### ISSUE TITLE
Track 'Cookie Consent Management' as a category

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#3219]
With tightening of privacy laws in various geographies (GDPR in EU / CCPA in California) , it will be good to track 'Cookie Consent Management' as a new category in Wappalyzer. Solutions like BuiltWith track this under category 'Cookie compliance system' and here is adoption graph of one such solution called 'OneTrust' - https://trends.builtwith.com/widgets/OneTrust

To start with, we can look at tracking big ones - 
- OneTrust/Optanon/CookiePro
- Cookiebot
- TrustArc

  {
    name: 'Optanon',
    homepage: 'https://www.cookielaw.org/',
    categories: ['utility'],
    domains: [
      '*.onetrust.com', // onetrust is the parent company
      '*.cookielaw.org',
    ],
    examples: ['cdn.cookielaw.org', 'geolocation.onetrust.com'],
  },
  {
    name: 'TrustArc',
    homepage: 'https://www.trustarc.com/',
    categories: ['utility'],
    domains: ['*.trustarc.com'],
    examples: ['choices.trustarc.com', 'consent.trustarc.com'],
  },
  {
    name: 'Cookiebot',
    homepage: 'https://www.cookiebot.com/',
    categories: ['utility'],
    domains: ['*.cookiebot.com'],
    examples: ['consent.cookiebot.com'],
  },

Got this patterns from third-party-web (https://github.com/patrickhulce/third-party-web/blob/master/data/entities.json5) (Thanks to @patrickhulce and other contributors)

I wish there was a separate category for 'cookie consent management' as part of third-party-web. Currently such solutions are listed within 'utilities' category

**Comment by AliasIO** [comment]
Happy to include it, I think we call the category 'Cookie compliance'. Do you want to add it?

**Comment by rockeynebhwani** [comment]
@AliasIO - Can I clarify if you have a category called 'Cookie Compliance' already OR do you want to use this name? I looked at https://github.com/AliasIO/wappalyzer/blob/master/src/apps.json but I can't find this category currently. Happy to add a new one which is called 'Cookie compliance'

**Comment by AliasIO** [comment]
There is no category for it yet but that's the name I'd like to use if you want to add it.

**Comment by rockeynebhwani** [comment]
@AliasIO - trying to add but what is 'priority' attribute for category. Can't find any documentation .. also, can I just add in English in all locales for now and let somebody else translate in future?

**Comment by rockeynebhwani** [comment]
I think I found out what priority is doing.. It's just the order of display in extension... I am going with priority 9 for this

**Comment by AliasIO** [comment]
That's correct. And yes, please use English in all the locales.

**Comment by rockeynebhwani** [comment]
@AliasIO - Done. please review and merge

**Comment by rockeynebhwani** [comment]
Notes for future detection - 
1) OneTrust can also be detected using 'optanon.blob.core.windows.net' (Example - www. optimizely.com)
https://optanon.blob.core.windows.net/consent/2beea5c0-5dc4-462e-924f-8b7eed8c2b4f.js

**Comment by rockeynebhwani** [comment]
Some more -

1) iubenda (https://www.iubenda.com/)

JS to look for - 

<script async="" src="//www.iubenda.com/cookie-solution/confs/js/252372.js"></script>

**Comment by rockeynebhwani** [comment]
@AliasIO - Question for you... We already have 'Quantcast' added to apps.json under 'Analytics category' and I want to add also under 'Cookie Compliance' category. Option 1 is that I just add another pattern to existing block and assign to category 10 and 67 but in that case, if a site is only using Quantcast  analytics offering, it will also list under 'Cookie Compliance'. What do you do in such situations. ? Another option is .. I rename existing entry to something like 'Quantcast - Analytics' and add a new entry 'Quantcast - Cookie Compliance'

**Comment by AliasIO** [comment]
Each product should be a separate technology. I think they should be called Quantcast Measure and Quantcast Choice:

https://www.quantcast.com/products/measure-audience-insights/
https://www.quantcast.com/gdpr/consent-management-solution/

**Comment by rockeynebhwani** [comment]
@AliasIO - Thanks.. Will use these names

**Comment by rockeynebhwani** [comment]
Note for future PR - This site is currently missing OneTrust detection (https://prioritypass.com/). Check for presence of 'otSDKStub.js'

**Comment by rockeynebhwani** [comment]
There are bunch of Shopify specific solutions if we want to expand this list (from https://avada.io/shopify/gdpr/)

![image](https://user-images.githubusercontent.com/1718757/88468452-e0a08f80-cedb-11ea-88f9-95a8de0331c1.png)

**Comment by rockeynebhwani** [comment]
One more - https://tealium.com/the-general-data-protection-regulation-gdpr/

**Comment by rockeynebhwani** [comment]
@AliasIO - I am trying to add a new vendor where detection can be based on presence of window.__cmpConfig js function.. I tried this and here is the example site - https://www.letudiant.fr/ but it doesn't work. Are you able to check why?

```
    "IAB Europe": {
      "cats": [
        67
      ],
      "icon": "iabeurope-tcf.png",
      "js": {
        "window.__cmpConfig": ""
      },
      "website": "https://iabeurope.eu/"
    }, 
```

**Comment by AliasIO** [comment]
`window.` is superfluous, try just `__cmpConfig` on its own.

**Comment by klosteinmann** [comment]
I think you might be missing a couple of cookie consent managment systems such as the one we use from consentmanager.net on our eShop GPDR / CCPA compliant which also supports TCF v2.0 from what i can tell. Will there be differenciating categorys, reports  for the TCF versions inside of Wappalyzer?
