### ISSUE TITLE
Track Communication Tools 

### ISSUE THREAD

**Issue by vfcampo** [AliasIO/wappalyzer#3220]
With the increase of remote communication due to the recent events, in-page communication tools are becoming  the rule for some businesses that are trying to get more engagement from their websites. 
These tools could be online scheduling systems  (calendly, vcita, etc) , Survey tools (Survey monkey, wufoo, google forms, etc) , webinars ( Gotowebminar, webex) or even chatboxes (we already have a category for those)
My suggestion here is to add a category for this family of tools or please let me know which of the existing categories should we use for such technologies 

To start with, we can look at the first group: online scheduling systems

**Comment by AliasIO** [comment]
I think we should create separate categories, also see #3225.

**Comment by AliasIO** [comment]
I added categories for Appointment scheduling and Surveys, and added Calendly. I'll be looking at adding others, too.

**Comment by vfcampo** [comment]
I will help

**Comment by vfcampo** [comment]
Google has a list of vendors that the support and we can use as a reference
to start with:
https://www.google.com/maps/reserve/partners

<https://www.vendasta.com/protect-local/?utm_medium=referral&utm_source=email-signature&utm_campaign=protect-local&utm_content=protect-local-main>

**Comment by AliasIO** [comment]
Added, thanks.
