### ISSUE TITLE
Derive Category from a Technology

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#3221]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to Imply a 'Category' from a 'Technology'. It will be helpful to have a Implied Category based on a technology being used. 

Take an example - Wappalyzer currently fails to identify lots of eCommerce platforms but presence of 'Google Analytics Enhanced eCommerce' (Which is under 'Analytics') can imply that a site is of category 'eCommerce' even if we can't say which eCommerce platform/technology.

**Describe the solution you'd like**
*Option 1*
Introduce concept of ImpliedCategory based on a technology

*Option 2*
Change categorisation of 'Google Analytics Enhanced eCommerce' from 'Analytics' to 'ECommerce'. This will improve the eCommerce categorisation but weaken the definition of eCommerce category as with this it will contain more than eCommerce platforms.

**Additional context**
By applying this logic, we were able to detect 239,480 sites additionally in eCommerce category.

SELECT
  url
FROM (
  SELECT
    DISTINCT url
  FROM
    `httparchive.technologies.2020_06_01_mobile`
  WHERE
    app = 'Google Analytics Enhanced eCommerce')
LEFT JOIN (
  SELECT
    DISTINCT url
  FROM
    `httparchive.technologies.2020_06_01_mobile`
  WHERE
    category = 'Ecommerce')
USING (url)

**Comment by AliasIO** [comment]
Perhaps it makes sense to just add Google Analytics Enhanced eCommerce to the Ecommerce category, even though it's not an ecommerce platform. Are there other cases like this?

**Comment by rockeynebhwani** [comment]
@AliasIO - I think of more cases like this .. For example - presence of a reviews provider like BazaarVoice / PowerReviews etc. can also indicate eCommerce category as reviews are typically for a product or service. At this moment, I think Wappalyzer is lacking coverage of such review providers but this can be another use case. 

OR - This is also a good use case - https://github.com/AliasIO/wappalyzer/issues/3218

**Comment by rockeynebhwani** [comment]
@AliasIO - BTW, I am ok to add Google Analytics Enhanced eCommerce to the Ecommerce category

**Comment by AliasIO** [comment]
@rockeynebhwani Let's do that then, I think it solves your use case without requiring major changes in the code.

**Comment by rockeynebhwani** [comment]
@AliasIO Please review

**Comment by rockeynebhwani** [comment]
@AliasIO  - I think you ended up reverting changes made in this issue by mistake. Please have a look at this commit - https://github.com/AliasIO/wappalyzer/commit/ec202c8f4af0328d4cd2d9b3a262c8d1296b7f60 

Can we please restore the change to categorise 'Google Analytics Enhanced eCommerce' under category '6'. This was an important check for web almanac eCommerce chapter.

**Comment by AliasIO** [comment]
Sorry, I didn't think this one through. I reverted this when I noticed it occupied the third spot in the ecommerce category, which is obviously not right:

https://www.wappalyzer.com/technologies/ecommerce/

Perhaps we can imply 'Cart Functionality', which is listed in Ecommerce. I added a special case for this on the website not not show it in the stats.
