### ISSUE TITLE
Discrepancy between npm package and chrome extension

### ISSUE THREAD

**Issue by AlbertPun** [AliasIO/wappalyzer#3222]
**Platform**
Which platform does the bug apply to?
* NPM

**Describe the bug**
There are far fewer technologies shown when I use the npm package compared to the chrome extension and npm global package.

**To Reproduce**

The example website I am using is http://www.wood-crafts.xyz/
I have also found other websites that exhibit this behavior.

Run the following code in node
```
const Wappalyzer = require('wappalyzer');
 
const urls = ['http://www.wood-crafts.xyz/']
 
;(async function() {
  const wappalyzer = await new Wappalyzer({
    userAgent: 'Wappalyzer',
    maxDepth: 3,
  })
 
  try {
    await wappalyzer.init()
 
    const results = await Promise.all(
      urls.map(async (url) => ({
        url,
        results: await wappalyzer.open(url).analyze()
      }))
    )
 
    console.log(JSON.stringify(results, null, 2))
  } catch (error) {
    console.error(error)
  }
 
  await wappalyzer.destroy()
})()
```

This returns Vue.js, Nuxt.js, and Node.js

However, when I use the chrome extension on http://www.wood-crafts.xyz/, I get far more technologies. I also see running the global wappalyzer npm package returns more technologies than the local wappalyzer package.

**Expected behavior**
I expect to see that the found technologies are consistent between the npm package and chrome extension

**Additional context**
I thought it was just an options issue, but I tried many different options and could not reproduct the chrome extension's output. How can I make sure the npm package returns all the technologies?

**Comment by AliasIO** [comment]
Using that exact code I get 16 results, which is the same as the extension and CLI output. There is no difference between the local and global install, unless you're running different versions.

**Comment by AlbertPun** [comment]
Looks like my versions were different. Thank you for looking into this!
