### ISSUE TITLE
Improve detection for SalesForce Commerce Cloud

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#3223]
**Is your feature request related to a problem? Please describe.**
Current detection of SalesForce Commerce Cloud misses some sites. For example - amp.direct.asda.com which is AMP version of direct.asda.com

**Describe the solution you'd like**
Check for presence of demandware.static in HTML in addition to current checks - 

**Describe alternatives you've considered**
Not Applicable

**Additional context**
Current detection

```
    "Salesforce Commerce Cloud": {
      "cats": [
        6
      ],
      "headers": {
        "Server": "Demandware eCommerce Server"
      },
      "html": "<[^>]+demandware\\.edgesuite",
      "icon": "Salesforce.svg",
      "js": {
        "dwAnalytics": ""
      },
      "script": "/demandware\\.static/",
      "website": "http://demandware.com"
    },
```
Change this to 

```
    "Salesforce Commerce Cloud": {
      "cats": [
        6
      ],       
      "headers": {
        "Server": "Demandware eCommerce Server"
      },
      "html": [
        "<[^>]+demandware\\.edgesuite",
        "/demandware\\.static/"
       ],
      "icon": "Salesforce.svg",
      "js": {
        "dwAnalytics": ""
      },
      "script": "/demandware\\.static/",
      "website": "http://demandware.com"
    },
```

**Comment by rockeynebhwani** [comment]
@AliasIO Please review

**Comment by rockeynebhwani** [comment]
@jrharalson - Do you have any more SFCC sites where detection is not working? We can try to address those as well before closing this.

**Comment by g3john** [comment]
Working on this
