### ISSUE TITLE
New Category: User Generated Content

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#3225]
This proposal is  to add a new cateogry called 'User Generated Content' and it can list providers like BazaarVoice / PowerReviews  etc. 

Technology | Website | Pattern | Example Page
------------ | ------------- | ------------- | ------------- 
BazaarVoice|https://www.bazaarvoice.com/|Presence of script bv.js OR domain apps.bazaarvoice.com OR domain apps.nexus.bazaarvoice.com in SCRIPT tag|https://direct.asda.com/george/collections/kids/boys/D28M63G1C3S1,default,sc.html?cm_sp=desktop-_-grghomepage-_-george-_-tier1_block1-_-200716link01shopboyssummer
PowerReviews|https://www.powerreviews.com/|?|?
Yotpo|https://www.yotpo.com/|Presence of script (just look for domain in script) `//staticw2.yotpo.com/Z1ia318TQD3H8cgES4O27MG5V4gPgT9PRiUZPs9P/widget.js`|https://www.stevemadden.com/ and https://www.rebeccaminkoff.com/
Reviews.io|https://www.reviews.io/|Look for a link with HREF  '*.reviews.co.uk' (Example - //bunchescouk.reviews.co.uk/) AND look for script from domain '//widget.reviews.co.uk' |https://www.bunches.co.uk/ AND https://www.julesb.co.uk/
TurnTo|https://www.turntonetworks.com/|?|
expertreviews|https://www.expertreviews.co.uk/

@AliasIO  - I can do a PR with some provider if you are happy with the proposal.

**Comment by AliasIO** [comment]
I think the categories should be more specific, e.g. 'Comment systems' (existing category), 'Reviews' and 'Surveys' etc.

**Comment by rockeynebhwani** [comment]
I am happy to add new category called 'Reviews' to start with

**Comment by AliasIO** [comment]
Perfect!

**Comment by rockeynebhwani** [comment]
@AliasIO - If we are restricting this to 'Reviews', it will also be good to imply eCommerce Category with this as reviews are always for a transaction/product/service which should put this any site in eCommerce category. What do you say?

**Comment by AliasIO** [comment]
I prefer not to clutter the category with non-ecommerce technologies, as they would show up here:

https://www.wappalyzer.com/technologies/ecommerce

On your end however you should be able to easily aggregate Ecommerce and Reviews into a single set, correct?

**Comment by rockeynebhwani** [comment]
Yes.. we can.. However, I think in long run move to Headless/Micro-services architecture, it will not be possible to identify eCommerce category (may take few years) and hence implied derivation may be needed but for now, we can do this join at our end.
