### ISSUE TITLE
New Category: Security

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#3226]
This proposal is to introduce a new cateogry called 'Security' and this can contain technologies like Bot Detection (e.g. PerimeterX / CyberFend / Google Re-captcha). Here are providers from Forrester report. Let's cover at least these 

![image](https://user-images.githubusercontent.com/1718757/87863123-9ce3de00-c94f-11ea-94f0-8c0642425045.png)

Detection pattern

Technology | Website | Pattern | Example Page
------------ | ------------- | ------------- | ------------- 
Perimeter X|https://www.perimeterx.com/| Presence of cookie '_pxvid'|https://direct.asda.com
Akamai Bot Manager|http://akamai.com/bot-manager| Look for any of the cookies "ak_bmsc", "bm_sv","bm_sz"|https://www.myntra.com/
Datadome |https://datadome.co/ | Look for cookies datadome-_zldt OR datadome-_zldp OR script js.datadome.co/tags.js| https://www.kurtgeiger.com/
Imperva|https://www.imperva.com/|Look for <script async type="text/javascript" src="/_Incapsula_Resource?SWJIYLWA=719d34d31c8e3a6e6fffd425f7e032f3&ns=1&cb=95495314"></script>|https://www.cotswoldco.com/
Reblaze |?|?|
ShieldSquare|https://www.shieldsquare.com/|?|?
Netacea|https://www.netacea.com/)
Castle|https://castle.io/)
Cloudflare|?|?|
CloudFilt|https://cloudfilt.com/|?|?|
F5|www.f5.com|?|?|

**Comment by AliasIO** [comment]
Happy to have that added.

**Comment by rockeynebhwani** [comment]
@AliasIO  - I see a category for 'Captchas' (Category 16). I think it's very limited... Shall we rename that to 'Security'? Most of these bot management soutions can also result in a Captcha exprience.

**Comment by AliasIO** [comment]
Yes, happy to rename that one.

**Comment by rockeynebhwani** [comment]
@AliasIO - Renamed the cateogry as discussed and added first 4 vendors from the table where patterns were known. 
Also, noticed that Incapsula (CDN Solution.. this was already in apps.json) has been renamed to Imperva (Bot protection solution). Found out this while making this change. (https://www.imperva.com/incapsula-moved/). Somebody should clean up these 2 later.

**Comment by f14stelt** [comment]
Please can you add nooder website security: www.nooder.net
The cookies used are NOODER_*

**Comment by rockeynebhwani** [comment]
@f14stelt - Please provide an example site to test Nooder.. Preferably not your own site.. a client of yours who is using Nooder so that we can test.

**Comment by f14stelt** [comment]
sure, you can test out vacban.wtf

**Comment by f14stelt** [comment]
@rockeynebhwani any news?
