### ISSUE TITLE
New Category: Accessibility

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#3228]
I am proposing a new category called 'Accessibility' and this can cover solutions like EqualWeb, UserWay, browsealoud, Recite me, Essential Accessibility, uRemediate, Adally.

Detection Patterns

Technology | Website | Pattern | Example site
------------ | ------------- | ------------- | -------------
EqualWeb | https://www.equalweb.com/| Presence of Script https://cdn.equalweb.com/core/2.1.0/accessibility.js | https://www.hobbs.com/
UserWay | https://userway.org/ | Presence of Script https://cdn.userway.org/widget.js | https://userway.org/
Texthelp | https://www.texthelp.com/en-gb/products/browsealoud/ | Presence of Script https://www.browsealoud.com/modules/3.0.5/browsealoud.js | https://www.texthelp.com/en-gb/company/we-work-with/
Recite me | https://reciteme.com/ | Presence of Script //api.reciteme.com/asset/js?key=2cc39bd137cd6779df3ecc149548cb0c1e592155 | https://www.westdevon.gov.uk/
Essential Accessibility | https://www.essentialaccessibility.com/ | Look for `<div class="essential-accessibility-link"><a href="https://www.essentialaccessibility.com/carilionclinic/?utm_source=carilionhomepage&amp;utm_medium=iconlarge&amp;utm_term=eachannelpage&amp;utm_content=header&amp;utm_campaign=carilionclinic" target="_blank"><img alt="Essential Accessbility Logo" class="accessibility-cc" src="/themes/custom/cc_theme/cc-front-end/dist/images/footer/ea-icon.png"></a></div>` | https://www.carilionclinic.org/
uRemediate| www.user1st.com | Presence of Script https://fecdn.user1st.info/Loader/head | https://kesslerfoundation.org/
Adally| https://adally.com/ | Presence of Script https://d2twz9av6or5hk.cloudfront.net/1.6/adally.js | https://www.survivalkit.com/
FACILiti|https://ws.facil-iti.com/| Presence of Script https://ws.facil-iti.com/tag/faciliti-tag.min.js | https://www.lacoste.com/
accessiBe|https://accessibe.com/|Presence of Script https://acsbap.com/apps/app/assets/js/acsb.js|https://accessibe.com/
audioeye|https://www.audioeye.com/|Presence of Script https://ws.audioeye.com/ae.js|https://www.dealer.com/
HikeOrders|https://hikeorders.com/|Presnece of script https://jsappcdn.hikeorders.com/main/assets/js/hko-accessibility.min.js|https://modshop1.com/
make sense|https://mk-sense.com/|Presence of Script //bezeq.mk-sense.com/aweb?license=428b0655-9bce-4c17-a1bc-7019ba588afc|https://www.audiocodes.com/
UsableNet|https://usablenet.com/|Presence of iFrame with pattern <iframe style="display:none;" src="https://*.usablenet.com/pt/switch"></iframe>|https://www.jcpenney.com/ and https://www.ae.com/intl/en

**Comment by AliasIO** [comment]
Green light from me!

**Comment by bazzadp** [comment]
Can we add AccessiBE? https://accessibe.com/

Also are there sub-categories? Should accessible overlays (which can cause more issues than they solve!) be defined in those as opposed to a general Accessibility category which might also include less controversial accessibility products?

Context btw: https://adrianroselli.com/2020/06/accessibe-will-get-you-sued.html

**Comment by rockeynebhwani** [comment]
@bazzadp  - Added AccessiBE's detection pattern. Interesting article.. I am afraid not my area of expertise. If there are any sub-categories, we will have to possibly go deeper in our analysis. Wappalyzer doesn't go that deep.

**Comment by rockeynebhwani** [comment]
Add few more to the list from https://www.whoisaccessible.com/ .. Some mentioned on this site seems to be consulting/testing firms.. excluded those

**Comment by adityapandey1998** [comment]
I will pick this up @rockeynebhwani

**Comment by rockeynebhwani** [comment]
@adityapandey1998  - I added a new provider in original table.. It's called Usablenet. See if you can take care of this also in your PR

**Comment by rockeynebhwani** [comment]
Closing this as PR has been merged
