### ISSUE TITLE
Increase coverage of eCommerce platforms

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#3229]
Add following eCommerce Platforms - 

Technology | Website | Pattern | Example site
------------ | ------------- | ------------- | -------------
ShiftCommerce|https://www.shiftcommerce.com/|?|www.matalan.co.uk
AbleCommerce|https://www.ablecommerce.com/|?|?
ReactionCommerce|www.reactioncommerce.com|One of the site has assets from CDN and another site only has copyright message in footer |https://material.bombur.de/ and https://shop.geospatial.com/
The Hut Group|https://www.thg.com/|Look for THEHUT-*.js|www.lookfantastic.com / https://www.burtsbees.co.uk/
Global-e|https://www.global-e.com/|Look for script https://web.global-e.com/|https://www.prettygreen.com/
Flow|https://www.flow.io/|Look for script https://cdn.flow.io/flowjs/latest/flow.min.js OR shopify-cdn.flow.io|https://www.mzwallace.com/ and https://www.outerknown.com/
Borderfree|https://www.borderfree.com/|look for bfx.js OR global.prd.borderfree.com|https://www.rebeccaminkoff.com/
Salesfloor|https://salesfloor.net/|look for src="/assets/scripts/salesFloor.js"|https://www.neimanmarcus.com/

**Comment by rockeynebhwani** [comment]
Have Added Hut Group for now as it's much bigger compared to others while we wait for pattern identification for others. @AliasIO  - Please review

**Comment by rockeynebhwani** [comment]
@AliasIO - question for you.. Tools like BuiltWith do a generic CART detection to determine eCommerce category (even if we can't detect exact platform). See example below - 

![image](https://user-images.githubusercontent.com/1718757/88240185-50194380-cc7e-11ea-962f-02f51812f80e.png)

I believe this detection is done by looking for /cart / basket /trolly etc. in link (this is my guess.. possibly there are few more patters).

What is your view on this? Do you instances like this in Wappalyzer ?

**Comment by AliasIO** [comment]
It's an odd one but we could add a technology called 'Cart functionality' in the Ecommerce category to serve as a catch-all. Not sure how reliable it is to detect cart functionality with generic patterns.

**Comment by rockeynebhwani** [comment]
We can keep it tight and tweak as necessary but only issue in this case will be two entries where there is a cart link and we also identify an eCommerce platform. Is there a way to suppress 'Cart functionality' if we detect an eCommerce platform?

**Comment by AliasIO** [comment]
We can't suppress it unless we add an `excludes` clause to every ecommerce technology. It's a little hacky but it might be ok to show both entries.

**Comment by rockeynebhwani** [comment]
ok.. let's do that for now. What logo and website link we use for this :-)?

**Comment by rockeynebhwani** [comment]
@AliasIO - We can go with exact match for following URL patterns to start with 

```
/cart
/basket
/checkout/
/bag
/trolley
```

**Comment by AliasIO** [comment]
The website link can be `https://www.wappalyzer.com/technologies/ecommerce/cart-functionality`. :)

Here's a generic cart icon:

```html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1"  width="24" height="24" viewBox="0 0 24 24">
   <path fill="#000000" d="M17,18C15.89,18 15,18.89 15,20A2,2 0 0,0 17,22A2,2 0 0,0 19,20C19,18.89 18.1,18 17,18M1,2V4H3L6.6,11.59L5.24,14.04C5.09,14.32 5,14.65 5,15A2,2 0 0,0 7,17H19V15H7.42A0.25,0.25 0 0,1 7.17,14.75C7.17,14.7 7.18,14.66 7.2,14.63L8.1,13H15.55C16.3,13 16.96,12.58 17.3,11.97L20.88,5.5C20.95,5.34 21,5.17 21,5A1,1 0 0,0 20,4H5.21L4.27,2M7,18C5.89,18 5,18.89 5,20A2,2 0 0,0 7,22A2,2 0 0,0 9,20C9,18.89 8.1,18 7,18Z" />
</svg>
```

**Comment by rockeynebhwani** [comment]
@AliasIO - I think generic 'Cart functionality' detection can be improved further by looking for a '-'. It currently matches `/Cart` but I think `/Cart-` should also be a safe match as - is a common practice in URL. Example site which will benefit from this - https://www.halfords.com/

**Comment by rockeynebhwani** [comment]
Note for self - I think we can extend detection for 'Cart Functionality' by extending the pattern for `/order`. Example site to test - https://almondfurniture.co.uk/

**Comment by rockeynebhwani** [comment]
@AliasIO - I had added Flow.io under eCommerce category as part of this commit on 26th July 2020 (https://github.com/AliasIO/wappalyzer/pull/3247/commits/c1dd10d8361afbd309eeb8eec03bcc1aaf463a0f)


But looks like your change on 6th Sep 2020 removed check for 'Flow.io' 
https://github.com/AliasIO/wappalyzer/commit/7f82ac6e729809dff1313ffe14db1fb6e2e8f643

I am assuming this was by mistake.. Can you please have a look ?

**Comment by AliasIO** [comment]
@rockeynebhwani I think it was too, I added it back in db20de16f46a51f3576af714d05db6334c7ebd28.

**Comment by rockeynebhwani** [comment]
@AliasIO - I see that Flow is now not being detected on www.mzwallace.com. I think we can enhance 'Flow' detection by checking for 'flow' window object. Example sites - www.mzwallace.com / https://www.charlesandcolvard.com/

![image](https://user-images.githubusercontent.com/1718757/122209852-e65ce600-ce9c-11eb-95a9-53915234807d.png)
