### ISSUE TITLE
Use Crowd sourcing to increase the Coverage

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#3230]
**Is your feature request related to a problem? Please describe.**
Currently only developers who feel comfortable with Open source projects and are familiar to navigate around GitHub can contribute to this project

**Describe the solution you'd like**
A more self-serve solution with a user friendly interface and drastically help increase the coverage. This is how I see it working - 
1) Provide a link in chrome extensions. Link will be called 'Report a missing technology'
2) Lot of time users of this extension will know a particular technology being used on a site and may want to contribute to enhance database. I can see lot of technology vendors doing themselves to increase their visibility. So, they click this link and go to a dynamic form which lists all categories. 
- User selects appropriate category
- User is given options for detection mechanims (cookie based / header based / META tag based / SCRIPT based / HTML based)
- User can choose one OR more of these and provide necessary information for detection
- User provides website link for the technology
- We should make 'logo' optional in this process as trying to find a right size logo can deter some people. We should render technology without logo if logo not provided.
- On sub-mission of the form, system should create a PR automatically which can be reviewed by likes of @AliasIO or other volunteers on the project

You can also create slightly more advanced flow to create a completely new category in self-service manner but that will be next step.

**Comment by AliasIO** [comment]
It's a good idea but I don't often see people pick up technology requests in issues. I don't always have time which is why I encourage pull requests, even though that does raise the barrier for people to contribute.
