### ISSUE TITLE
WebSphere Commerce sites are not being detected correctly

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#3236]
Current pattern in apps.json

```
   "IBM WebSphere Commerce": {
      "cats": [
        6
      ],
      "cpe": "cpe:/a:ibm:websphere_commerce_suite",
      "html": "href=\"(?:\\/|[^>]+)webapp\\/wcs\\/",
      "icon": "IBM.svg",
      "implies": "Java",
      "url": "/wcs/",
      "website": "http://ibm.com/software/genservers/commerceproductline"
    },
```
Sites failing detection - 
1) https://www.argos.co.uk/

Pattern in HTML of this site - 

`<a href="/webapp/wcs/stores/servlet/OrderTracking?langId=110&amp;storeId=10151" data-test="footer-track-your-order" class="Footerstyles__PrimaryLink-hc8b7s-3 eIUmim">Track your order</a>`

2) https://www.debenhams.com

`<a class="pw-link t-home__link-wrapper" data-tracking-id="hero banner £10 worth of points*-when you spend £50 or more  on beauty, skincare &amp; fragrance" href="/webapp/wcs/stores/servlet/Navigate?sfv=30%25+-+50%25&amp;ps=default&amp;catalogId=10001&amp;lid=//productsuniverse/en_GB/product_online%3DY/insearch%3D1/categories<%7Bproductsuniverse_59001%7D/0.0<discounted_percentage<100.0&amp;langId=-1&amp;sfn=DISCOUNT&amp;storeId=10701&amp;pn=1">`

**Comment by jrharalson** [comment]
Slight shift in the regex pattern works much better. Pushing a PR with the update now.  I'm using "a" "link" and "script" as they are references to the IBM url patterns that will drive higher detected then just the "a".  Site will use "/wcsstore/" and/or "/webapp/wcs/" in depending on the Site Context. 

"html": "(?:a|link|script)[^>]*(?:href|src)=\".*(\/wcsstore\/|webapp\\/wcs)",

**Comment by jrharalson** [comment]
[PR link|https://github.com/AliasIO/wappalyzer/pull/3239]
