### ISSUE TITLE
New Technology: SaleCyle

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#3237]
Add a new technology called - 'SaleCycle' (https://www.salecycle.com/)
Example Site - https://www.fortnumandmason.com/
Pattern detection can be based on - 
<iframe target="_self" title="SaleCycle" src="https://s.salecycle.com/receiver.html?sc_frame_id=86fc540a-be15-4490-806f-a8d73ca5895f" style="display: none; height: 0px; width: 0px;"></iframe>

Since 'SaleCycle' specialises in cart abandonment, it's safe to categorize this in under 'eCommerce' category (Category 6)

@AliasIO - If OK, I can do PR

**Comment by AliasIO** [comment]
Ok from me!

**Comment by g3john** [comment]
Picked up

**Comment by rockeynebhwani** [comment]
Closing this
