### ISSUE TITLE
Improve detection of Mobify

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#3238]
Current detection

```
    "Mobify": {
      "cats": [
        26
      ],
      "icon": "Mobify.png",
      "js": {
        "Mobify": ""
      },
      "script": "//cdn\\.mobify\\.com/",
      "website": "https://www.mobify.com"
    },
```
This misses sites like www.debenhams.com. Looks like Mobify has two implementations and we can improve this detection logic.

Also, Mobify is used as eCommerce platform for brands to delivry Adaptive/PWA solutions and every business using Mobify falls in eCommerce category. So, add eCommerce as additioanal category for Mobify

**Comment by drewzboto** [comment]
There's several different ways we deploy and two different ways we can detect:

Via a response header
`x-powered-by: Mobify`

Test sites:
- https://www.debenhams.com/
- https://www.additionelle.com/

Via including a script from either Mobify cdn (https://cdn.mobify.com or https://a.mobify.com). This is our legacy mode for mobile-only sites

Test sites:
- https://www.underarmour.co.uk/en-gb/
- https://www.mackage.com/ca/en
- https://www.soiakyo.com/ca/en
- https://www.spacenk.com/uk/en_GB/home-uk

These test sites use the older a.mobify.com
- https://www.hobbycraft.co.uk/
- https://www.tommybahama.com/ 
- https://www.grandinroad.com/
- https://www.frontgate.com/

**Comment by rockeynebhwani** [comment]
Thanks @drewzboto . Added to my PR. @AliasIO - Please review and merge

**Comment by rockeynebhwani** [comment]
Closing this as this change has been merged now.
