### ISSUE TITLE
Wappalyzer logo for Chrome extension is wrong

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#3240]
On Chrome, Wappalyzer extension shows logo of first detected technology instead of Wappalyzer logo. This makes it difficult to locate Wappalyzer among all other extensions. For example, in below screenshot, it's showing 'Facebook' logo instead of Wappalyzer logo

![image](https://user-images.githubusercontent.com/1718757/88226921-bbeeb280-cc64-11ea-8c12-f9ac8514db68.png)

**Comment by AliasIO** [comment]
There is a setting to turn this off. In the next update it will be off by default.
