### ISSUE TITLE
Nooder website protection and optimization

### ISSUE THREAD

**Issue by f14stelt** [AliasIO/wappalyzer#3241]
Hello,

I am from Nooder, a website security company, we would like you to add our service in detection.
Our ip range is 45.138.200.0/24

**Comment by rockeynebhwani** [comment]
@f14stelt - Detection is not based on IPs. Please look at this https://www.wappalyzer.com/docs/dev/specification and best way to get added is to submit a PR

**Comment by rockeynebhwani** [comment]
@f14stelt - You should look at this https://github.com/AliasIO/wappalyzer/issues/3226. If Nooder is like other companies mentioned in this issue, you can add to the list

**Comment by f14stelt** [comment]
Doing it
