### ISSUE TITLE
Additional Payment technologies

### ISSUE THREAD

**Issue by vfcampo** [AliasIO/wappalyzer#3242]
Hey @AliasIO 
Navigating in this page https://busyferns.ca/ I found put that they support multiple payment technologies we are not identifying form the homepage

Some of them are specific to the apple pay support :
![image](https://user-images.githubusercontent.com/55451462/88319317-35c08380-ccd9-11ea-96e2-7877388320b2.png)
 `"visa","masterCard","amex","interac"`
-> Apple Pay
-----> American Express
-----> MasterCard
-----> Visa
-----> Interact (Canada only)

They also support Shopify Pay:
![image](https://user-images.githubusercontent.com/55451462/88319982-2b52b980-ccda-11ea-98ce-fe0c7fde8a29.png)
![image](https://user-images.githubusercontent.com/55451462/88320069-4d4c3c00-ccda-11ea-9d65-1e1415c2297b.png)

And Paypal, that we should be able to identify but we are not: 
![image](https://user-images.githubusercontent.com/55451462/88320242-884e6f80-ccda-11ea-83cc-fbfb1bb3c4a4.png)

They also mention that the support google Pay 
![image](https://user-images.githubusercontent.com/55451462/88320464-da8f9080-ccda-11ea-8299-b165ac03c696.png)

But I only found evidence of supporting google merchant in their code:
![image](https://user-images.githubusercontent.com/55451462/88320617-13c80080-ccdb-11ea-90fa-9ca9be9342f5.png)

But when you enter in a checkout page, there you are able to see  it more clearly, ie: https://busyferns.ca/24400363625/checkouts/a7f0c0edfe66d137bca5222e8350bec3

![image](https://user-images.githubusercontent.com/55451462/88320963-a36daf00-ccdb-11ea-8168-97e3ec83d957.png)

![image](https://user-images.githubusercontent.com/55451462/88321221-08c1a000-ccdc-11ea-8439-89878ee1889b.png)

You may request a new technology to be added but changes of having it included are greatly improved if you submit a pull request. Please refer to the [documentation](https://docs.wappalyzer.com/dev/contributing.html#adding-a-new-application).

**Comment by vfcampo** [comment]
I think this is relevant to why google pay is supported by Shopify pay : https://news.shopify.com/hey-google-install-shopify-payments

**Comment by AliasIO** [comment]
I added several payment technologies in a340675c916edadda8dc64665e4340d816ba53b0 based on these patterns, but they're specific to Shopify. It's a start but we'll need more patterns to make detection more general.

**Comment by rockeynebhwani** [comment]
@AliasIO - Generic way to look for Apple Pay is to look for presence of file https://busyferns.ca/.well-known/apple-developer-merchantid-domain-association.txt

For example - this site has https://busyferns.ca/.well-known/apple-developer-merchantid-domain-association.txt

**Comment by AliasIO** [comment]
The extension doesn't make network requests so we can't check for the `.well-known` file. The meta tags are great though.

**Comment by rockeynebhwani** [comment]
@AliasIO - How will you se META for Amazon Pay example? There is no 'name' and 'content' property in it

**Comment by AliasIO** [comment]
@rockeynebhwani Like this: https://github.com/AliasIO/wappalyzer/commit/49d979e5305ca817e3bdaec260f8c52aed93455a#diff-557d7d60c04092a680ce152f367618c0R1021

**Comment by rockeynebhwani** [comment]
Thanks @AliasIO .. I see.. I was hoping to use META detection but I see that you have gone for HTML route in this case.

**Comment by rockeynebhwani** [comment]
@AliasIO - One more detection pattern for Amazon pay 
- Look for script https://static-eu.payments-amazon.com/OffAmazonPayments/gbp/lpa/js/Widgets.js (End point can also be https://static-na.payments-amazon.com depending on geography so best to look for static-*.payments-amazon.com
- Look for window.onAmazonPaymentsReady
- Example site - https://www.insulationsuperstore.co.uk/
- Amazon documentation on this - https://developer.amazon.com/docs/amazon-pay-onetime/add-a-button.html

**Comment by AliasIO** [comment]
@rockeynebhwani I added the script but `onAmazonLoginReady` appears to be for 'Login with Amazon', which I'll add as a social login technology.

**Comment by rockeynebhwani** [comment]
Thanks @AliasIO ..  I am seeing some detections not working  correctly. Have a look on https://niococktails.co.uk/ (see screenshot below). I am on 6.2.3 v of chrome extension

![image](https://user-images.githubusercontent.com/1718757/89732620-e05dd380-da47-11ea-88f3-8bdea4e0bb06.png)

**Comment by rockeynebhwani** [comment]
@AliasIO  - PayPal is not being detected on https://www.moonglow.com/?lang=fr. This link has PayPal meta data. We can use this to identify PayPal

<meta id="in-context-paypal-metadata" data-shop-id="24863224" data-venmo-supported="true" data-environment="production" data-locale="en_US" data-paypal-v4="true" data-currency="GBP">
