### ISSUE TITLE
New Category: Social Sign-in

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#3245]
@AliasIO  - I am proposing that we add a category to identify technologies like 'Sign-in with Apple' / 'Sign-in with LinkedIn' / Sign-in with GitHub' etc.

Do you have a preference for category name and priority ?

We will have to look for patterns like 

Sign-in Provider | Website | Pattern | Example site
------------ | ------------- | ------------- | -------------
Google Sign-in|?|<meta name="google-signin-client_id" / Presence of script https://apis.google.com/js/platform.js / OR presence of 'https://accounts.google.com/gsi/client'|www.wayfair.co.uk
Apple Sign-in|https://developer.apple.com/sign-in-with-apple/| <meta name="appleid-signin-client-id" / Presence of script appleid.auth.js|https://www.farfetch.com/uk/login.aspx
SAP Customer Data Cloud|https://www.sap.com/uk/acquired-brands/what-is-gigya.html|Presence of cdns.gigya.com/JS/gigya.js| Go to www.asos.com and check on sign-in page

Cover following to start with 

![image](https://user-images.githubusercontent.com/1718757/88427073-2aa94880-cdea-11ea-98de-3b1fa8572929.png)

**Comment by rockeynebhwani** [comment]
@AliasIO - Are you happy with this proposal? If yes, please confirm name and priority.

**Comment by AliasIO** [comment]
Yes I am, let's go with 'Social login'.

**Comment by rockeynebhwani** [comment]
@adityapandey1998 - Another one to add

- Provider Name - Okta
- Example site - https://console.perimeterx.com/user/login
- Pattern - Look for presence of okta-sign-in.min.js
