### ISSUE TITLE
Improve coverage of Tag Managers

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#3246]
Add following Tag Managers - 

Technology | Website | Pattern | Example site
------------ | ------------- | ------------- | -------------
IBM DDX|https://www.ibm.com/support/knowledgecenter/en/SSPG9M/DDX/DDX/ddx_intro_kc.html|?|?

These Tag Managers are already present in apps.json but are under other categories as a vendor provides more than one solution. 

Technology | Website | Pattern | Example site
------------ | ------------- | ------------- | -------------
Matomo / Piwik Pro | https://matomo.org/docs/tag-manager|JS function window.MatomoTagManager|https://www.georgeboom.com/
Tealium|https://tealium.com/products/tealium-iq-tag-management-system/|?|?
Signal|https://signal.co/customer-intelligence-solutions/tag-management/|No additional pattern required. Already in apps.json|https://direct.asda.com

**Comment by nurbek91** [comment]
@AliasIO Hey mate .Signal, Tealium , Matomo / Piwik Pro  - Looks like it's already implemented in tech.json 
#3504 newly added . Otherwise, there are not many of them.
