### ISSUE TITLE
[Firefox] Trimmed content when extension is pinned to the overflow menu

### ISSUE THREAD

**Issue by ocassio** [AliasIO/wappalyzer#3250]
**Platform**
Which platform does the bug apply to?
* WebExtension (Mozilla Firefox)

**Describe the bug**
Tech info window is trimmed when extension icon is pinned to overflow menu.
![ar](https://user-images.githubusercontent.com/6851647/88512628-eb504700-cff7-11ea-800a-57b18226f085.png)

**To Reproduce**
1. Install the extension
2. Right click on the icon
3. Select "Pin to Overflow Menu" item
4. Open overflow menu and click the extension icon

**Expected behavior**
Either a window should be the same size as without overflow menu, or the inner content should be aligned accordingly.
![er](https://user-images.githubusercontent.com/6851647/88512905-5ac63680-cff8-11ea-8c17-e9c2f34dc2b6.png)

**Comment by krystian3w** [comment]
Firefox limitation, addon may no privelages to enforce size.

**Comment by AliasIO** [comment]
Fixed in 8be327e141a947451701db517e364da720adfda0, thanks!

**Comment by ocassio** [comment]
After the last update:
![post_update](https://user-images.githubusercontent.com/6851647/89015580-52d40280-d328-11ea-9b21-ffa881597697.png)

**Comment by krystian3w** [comment]
But glitched with Polish (Poland) - too long strings in translation.

Also test Dutch (Netherlands) - the language is prone to long words.

**Comment by AliasIO** [comment]
This will be fixed v6.2.3.
