### ISSUE TITLE
Browser Toolbar Technology Icon Not Displaying

### ISSUE THREAD

**Issue by connorwhitman** [AliasIO/wappalyzer#3256]
Chrome Extension

Since the last update the icon in the toolbar no longer displays a technology icon, it's just the purple Wappalyzer logo.
Tech icons do show and are being properly detected when you expand the extension.

I inspected the html/background view and across multiple pages it didn't throw any errors.

Not a huge problem, but it's throwing off my 'at a glance what is this site using' flow :)

**Comment by AliasIO** [comment]
Please see #3249. You can enable the dynamic icon in the extension settings.
