### ISSUE TITLE
What kind of hardware does wappalyzer.com run on?

### ISSUE THREAD

**Issue by AdityaAnand1** [AliasIO/wappalyzer#3257]
Hello, I was looking around wappalyzer.com products and would love to know more about what's powering it.

* What kind of hardware does it run on? Normal compute or serverless? Containerized?
* How many instances do you typically have up and running at a time?
* How often do you scrape a website?

**Comment by AliasIO** [comment]
Wappalyzer will run on anything, I've used in on AWS EC2, ECS with Docker and Lambda.

**Comment by AdityaAnand1** [comment]
I meant what you use for the **wappalyzer.com product range specifically**.

How many instances do you have running forever (if any)? What class of hardware do you prefer (how much RAM, how many vCPUs etc.)

**Comment by AliasIO** [comment]
Ah, it's all serverless (Lambda + DynamoDB). To crawl I'm primarily using Lambda with 1GB RAM and a 15 minute timeout. It's not the cheapest option but it's convenient for varying workloads.

**Comment by AdityaAnand1** [comment]
Got it, is there a sample function for running wappalyzer on lambda somewhere? I'm wondering what kind of tweaking does it require to run on lambda.

**Comment by AliasIO** [comment]
It's just JavaScript so you don't need to tweak anything. The only limitation to get around is file size, as the Puppeteer dependency is too large for Lambda. This can be solved with Layers, e.g. using https://github.com/shelfio/chrome-aws-lambda-layer.
