### ISSUE TITLE
Add an option for user to toggle `Show the number of  Technology`

### ISSUE THREAD

**Issue by sss63232** [AliasIO/wappalyzer#3258]
## **Is your feature request related to a problem? Please describe.**

Hi @AliasIO 
I love wappalyzer, but the recently feature of `BadgeText` is really annoying to me. Our browser's top bar couldn't be messier more.

So I am wondering if we could add an option to turn off the number on icon.

## **Describe the solution you'd like**

Add an option to turn off keep `setBadgeText`. Like:
![2020-07-30 12-17-49 2020-07-30 12_18_57](https://user-images.githubusercontent.com/8876655/88880295-ee993c00-d25e-11ea-980f-accf63a2e215.gif)

## **Additional context**
If you think it's OK, I could help do the feature.

**Comment by AliasIO** [comment]
Added in 59240ffb939cba87ed4e6ccd76720bd4fc90a481, thanks!

**Comment by sss63232** [comment]
Fantastic!
