### ISSUE TITLE
The IBM WebSphere Portal was rebranded to HCL Digital Experience

### ISSUE THREAD

**Issue by amarques** [AliasIO/wappalyzer#3259]
IBM WebSphere Portal
Which platform does the bug apply to?
* Website

**Describe the bug**
The WebSphere Portal product was acquired by HCL Technologies, an big Indian company. So, all places when appear "IBM WebSphere Portal" should be "HCL Digital Experience". Link to more details:
https://www.theserverside.com/opinion/Whats-the-future-of-WebSphere-as-HCL-acquires-IBM-products

**To Reproduce**
Just open this page and rename the product name:
https://www.wappalyzer.com/technologies/cms/ibm-websphere-portal

**Expected behavior**
The product name should be: HCL Digital Experience

**Additional context**
I was not really sure this is a bug or feature, if was my mistake so sorry about that.

Thanks and Kind regards,
Anderson Marques

**Comment by AliasIO** [comment]
Updated in 44d62124131d414b5a00ca9d417c801a357bd0f5, thanks!
