### ISSUE TITLE
Magento platforms are showing cart functionlity

### ISSUE THREAD

**Issue by Adel-Magebinary** [AliasIO/wappalyzer#3264]
**Platform**
Which platform does the bug apply to?

Ubuntu

* WebExtension (Google Chrome, Mozilla Firefox)

Chrome

**Describe the bug**

Magento function is showing as cart functionality.

**Expected behavior**
Should show Magento.

**Comment by jrharalson** [comment]
@Adel-Magebinary Curious - Are you seeing both Magento and "Cart Functionality" in the Ecommerce category or are you seeing just 'Cart functionality', if so please share a site URL for review. 

The newer "Cart functionality" was added by @rockeynebhwani to help two fold - a) find site that showcase a "cart function" in general as well as b) provide additional context for site detection. We made a few changes to improve existing Ecommerce platform signals but there are some sites that still would not get trapped and this helps uncover more sites.

**Comment by rockeynebhwani** [comment]
@Adel-Magebinary - 'Cart Functionality' detection in addition to an eCommerce platform. It shouldn't really impact Megento detection. It should look like this.. If you share the site, we can definitely look into it for you.

![image](https://user-images.githubusercontent.com/1718757/89079695-f5b76b80-d37e-11ea-8475-2580c6a148c8.png)

**Comment by Adel-Magebinary** [comment]
hey guys, looks like it is fixed now. Thank you so much.

**Comment by rockeynebhwani** [comment]
We didn't change anything

**Comment by rockeynebhwani** [comment]
Closing

**Comment by rockeynebhwani** [comment]
@AliasIO - Please close this.
