### ISSUE TITLE
Logs timeout error to console

### ISSUE THREAD

**Issue by existentialcoder** [AliasIO/wappalyzer#3265]
**Platform**
Which platform does the bug apply to?
NPM

**Describe the bug**
npm package logs this error
Error: The website took too long to respond
    at Timeout.setTimeout [as _onTimeout] (/home/shrav/Desktop/workspace/TechstackCLI/node_modules/wappalyzer/driver.js:201:15)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

**To Reproduce**
1. Run wappalyzer await wappalyzer.open(url).analyze()
2. Error is logged into console even though the results are returned back

**Expected behavior**
Only results should be returned error should be thrown if any

**Additional context**

**Comment by existentialcoder** [comment]
![Screenshot from 2020-07-31 19-55-25](https://user-images.githubusercontent.com/32480876/89044631-d82ad780-d367-11ea-8d74-2e8ea4c19123.png)

**Comment by KirillZhdanov** [comment]
Same issue

**Comment by existentialcoder** [comment]
Adding options with maxWait as one minute when instantiating Wappalyzer fixed this for me

**Comment by BigFoxMedia** [comment]
Same for me.. I thought I was the only one.
@existentialcoder can you please share a snippet of the code on how to wrap my function and at what place using the maxWait?

Thanks!!

**Comment by BigFoxMedia** [comment]
Does anyone know what version to downgrade to before this bug was introduced?

**Comment by BigFoxMedia** [comment]
For anyone else that has this issue - uninstalling and then reinstalling v6.1.1 of both the main package and core - resolved the issue for me. So apparently this is a new bug introduced in the latest versions.

**Comment by existentialcoder** [comment]
```const wappalyzer = await new Wappalyzer({
    maxWait: units.ONE_MINUTE,
    recursive: true,
    userAgent: 'Wappalyzer',
    htmlMaxCols: 2000,
    htmlMaxRows: 2000,
  });

  await wappalyzer.init();
```
This fixed ir for me @BigFoxMedia

**Comment by AliasIO** [comment]
This has been fixed in v6.2.2.

**Comment by kiserbd** [comment]
Still i'm having the same issue after upgrade the version v6.2.2 @AliasIO

**Comment by AliasIO** [comment]
@kiserbd Can you show me an example?

**Comment by kiserbd** [comment]
@AliasIO I've tried with url https://ugmonk.com/collections/mens-best-sellers/products/realm-bone?variant=32288540524681 and got this 
![image](https://user-images.githubusercontent.com/1056658/89433860-a5685100-d764-11ea-8c8c-3b95b67fdad3.png)

**Comment by AliasIO** [comment]
@kiserbd The error is being captured correctly here so it's working as intended. You can increase the `maxWait` value if you're seeing a lot of websites timing out.
