### ISSUE TITLE
The content in the web extension menù is duplicating.

### ISSUE THREAD

**Issue by alsoGAMER** [AliasIO/wappalyzer#3276]
**Platform**
Which platform does the bug apply to?
* WebExtension (Mozilla Firefox)

**Describe the bug**
The content in the web extension menù is duplicating.

**To Reproduce**
1. Go to any website
2. Click on the extension icon
3. Then click a couple of times the toggle to turn off / on the extension on the site
4. The content is now duplicated

![image](https://user-images.githubusercontent.com/35269770/89128254-c165bb80-d4f4-11ea-9232-56de1b0f0f5b.png)
> an example of the bug using GitHub website as proof

**Expected behavior**
The content should be this:
![image](https://user-images.githubusercontent.com/35269770/89128299-199cbd80-d4f5-11ea-88a6-495dd1f241c5.png)

**Comment by AliasIO** [comment]
This will be fixed v6.2.3.
