### ISSUE TITLE
On toggling the Disable on this Website button the technologies get duplicated

### ISSUE THREAD

**Issue by Rohitbels** [AliasIO/wappalyzer#3277]
**Platform**
Which platform does the bug apply to?
* WebExtension (Google Chrome, Mozilla Firefox)
* 
**Describe the bug**
On toggling the Disable on this Website button the technologies get repeated.

**To Reproduce**
1. On chrome open the extension
2. Click on the toggle button that says 'Disable on this Website' on hover.
3. Click Again
4. Notice the duplication of technologies.

**Expected behavior**
Duplication should not happen

**Additional context**
Duplication goes away if you open the extension pop up afresh.

![image](https://user-images.githubusercontent.com/4401718/89318333-463f0980-d69c-11ea-95b7-44d1395d5483.png)

![image](https://user-images.githubusercontent.com/4401718/89318382-58b94300-d69c-11ea-81ac-72e80e29875c.png)

![image](https://user-images.githubusercontent.com/4401718/89318437-6c64a980-d69c-11ea-9296-f14d57fb98f5.png)

**Comment by AliasIO** [comment]
This was fixed in v6.2.3.
