### ISSUE TITLE
Safari extension

### ISSUE THREAD

**Issue by leonardofaria** [AliasIO/wappalyzer#3286]
Hi

Thanks for wappalyzer, it is a great product.

Now that Safari uses the web extension API, do you have any plans of offering a Safari extension? (related to https://github.com/AliasIO/wappalyzer/issues/1343)

Thanks

**Comment by AliasIO** [comment]
The extension works in Safari 14. I'm in the process of getting it onto the App Store but there's a lot of hoops to jump through.

<img width="594" alt="Screen Shot 2020-06-25 at 1 10 47 pm" src="https://user-images.githubusercontent.com/77259/89836545-55491e80-dbaa-11ea-875b-a24d2b565dee.png">

**Comment by leonardofaria** [comment]
Awesome! I am already running the developer/public betas of macOS, if you need beta user count on me :)

**Comment by AliasIO** [comment]
If you have Xcode beta installed you can try your luck with `yarn run build:safari`.

**Comment by hsul4n** [comment]
@AliasIO any a stable version is coming soon for safari

**Comment by AliasIO** [comment]
I'm still trying to get it onto the App Store, no ETA as of yet.

**Comment by pesqair** [comment]
> If you have Xcode beta installed you can try your luck with `yarn run build:safari`.

I might not know enough to do this correctly but I just get a plugin that says no technologies detected. 

thanks for the suggestion though

**Comment by AliasIO** [comment]
@pesqair I fixed a couple of issues today, it should work now.

**Comment by hsul4n** [comment]
Any updates, macOS Big Sur is live.

**Comment by AliasIO** [comment]
Hopefully soon, it's currently in review.

**Comment by AliasIO** [comment]
Success!

https://apps.apple.com/au/app/wappalyzer/id1520333300

**Comment by artchudov** [comment]
Is there any way to use it on Catalina?

**Comment by AliasIO** [comment]
@artchudov You need Safari 14, I think it might be available on Catalina?

**Comment by olimart** [comment]
@AliasIO It requires macOS 11
