### ISSUE TITLE
WebExtension shows generic "Cart Functionality" icon when an ecommerce tech is in use

### ISSUE THREAD

**Issue by ShayKorin** [AliasIO/wappalyzer#3287]
**Platform**
Which platform does the bug apply to?
* WebExtension (Google Chrome)

**Describe the bug**
There's a generic "Cart Functionality" tech on ecommerce sites, which the extension icon is defaulting to.
Examples: trubrain.com, skullcandy.com
Cart Functionality page on wappalyzer site: https://www.wappalyzer.com/technologies/ecommerce/cart-functionality

**To Reproduce**
1. Go to an ecommerce site, and see the extension icon is changing to a cart icon, which belongs to the technology "Cart Functionality".

**Expected behavior**
The icon should be of the main technology used to built the site.

Thanks!

**Comment by rockeynebhwani** [comment]
@ShayKorin  - are you talking about icon used for chrome extension ? This is what I see for skullcandy.com

![image](https://user-images.githubusercontent.com/1718757/90066711-00122780-dce6-11ea-8cfe-c84d03cd0311.png)

**Comment by AliasIO** [comment]
@rockeynebhwani If you enable the dynamic icon it will often show the 'Cart Functionality' icon instead of the 'Bigcommerce' icon (depending on which gets detected first). I'll see what I can do.

**Comment by AliasIO** [comment]
I addressed this by no longer displaying Cart Functionality in the extension pop-up. It's still being tracked and reported using the NPM module.
