### ISSUE TITLE
localhost extension cache

### ISSUE THREAD

**Issue by Chipsum** [AliasIO/wappalyzer#3290]
**Is your feature request related to a problem? Please describe.**
It's been clear I think about how wappalyzer deals with localhost , it's not a bug since localhost's websites share the same domain (localhost duh), but rather a feature to solve that problem.

**Describe the solution you'd like**
I try always to remove the extensions cache to allow wappalyzer rebuild new detection database, but that's not practical for a dev. Maybe allowing an options to refresh wappalyzer cache (or literally removing it) without the need to close the web browser and doing it manually , of course if there are other solutions that will be nice.
**Describe alternatives you've considered**
Doing it manually by removing the extension cache.
**Additional context**
that's it :).

**Comment by AliasIO** [comment]
There is a 'clear cached detections' button in the extension settings.

**Comment by Chipsum** [comment]
> There is a 'clear cached detections' button in the extension settings.

Oh I really never seen it before , u made my day thank u very much :smiley:
