### ISSUE TITLE
Invalid schema JSON: duplicate key

### ISSUE THREAD

**Issue by mwullink** [AliasIO/wappalyzer#3293]
Hi, parsing the schema json file fails because the "icon" key is present twice for "Adobe Experience Manager"

https://github.com/AliasIO/wappalyzer/blob/master/schema.json

"Adobe Experience Manager": {
			"cats": [
				1
			],
			"cpe": "cpe:/a:adobe:experience_manager",
			"html": [
				"<div class=\"[^\"]*parbase",
				"<div[^>]+data-component-path=\"[^\"+]jcr:",
				"<div class=\"[^\"]*aem-Grid"
			],
			"icon": "Adobe Experience Manager.svg",
			"implies": "Java",
			"script": [
				"/etc/designs/",
				"/etc/clientlibs/",
				"/etc\\.clientlibs/"
			],
			"icon": "Adobe.svg",
			"website": "https://www.adobe.com/marketing/experience-manager.html"
		},

**Comment by AliasIO** [comment]
Fixed in 84803bb91c9defdafa65ec0dfd9a6e10e054e35e, thanks.
