### ISSUE TITLE
Hi, I have a request. I want Wappalyzer to correspond to STUDIO.

### ISSUE THREAD

**Issue by sgnmio** [AliasIO/wappalyzer#3294]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is, e.g. I'm always frustrated when [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sgnmio** [comment]
STUDIO is this. https://studio.design/
it is Japanese CMS.

Them are good examples with STUDIO: 
https://design-ship.jp/ 
https://athome.cookpad.com/ 
https://erimiura.com/

**Comment by sgnmio** [comment]
When I use Wappalyzer for these sites, they are considered to have been made with Node.js.
It would be nice if they came to be regarded as made with STUDIO.

I'm sorry I'm not good at English.

Thank you,
Mio Sugano

**Comment by dunklesToast** [comment]
You could create a matcher matching this meta tag
`<meta data-n-head="ssr" data-hid="generator" name="generator" content="STUDIO">`
