### ISSUE TITLE
Add SSL category

### ISSUE THREAD

**Issue by nukerr** [AliasIO/wappalyzer#3312]
**Is your feature request related to a problem? Please describe.**
In Wappalyzer, there's no SSL category.

**Describe the solution you'd like**
Create an SSL category with SSL certs providers

**Describe alternatives you've considered**
x

**Additional context**
x

**Comment by AliasIO** [comment]
Thanks for the suggestion. I added a handful of certificate authorities in d2b11ffcbb1a50ee9a942aa3b1ceedb230d6e2a9. Unfortunately it doesn't look like there is a way to inspect certificates in Google Chrome so this only works in the NPM driver.
