### ISSUE TITLE
Performance improvement scope?

### ISSUE THREAD

**Issue by khanof89** [AliasIO/wappalyzer#3315]
Can we improve the perfomance by setting a data-dir explicitly which is not a temp directory? I understand this may take disk space and with time will be bigger, but we can run a cron to clean this directory every 12 hours or every day depending upon how fast it fills up the disk space ?

**Comment by AliasIO** [comment]
I added the ability to configure the directory with a `CHROMIUM_DATA_DIR` environment variable: ae845f79f329d936a83563530ee2aa9967da20ad.

**Comment by AdityaAnand1** [comment]
I am super interested in anything that improves performance. How does this work exactly? 😁

**Comment by AliasIO** [comment]
I don't think moving the data directory out of `/tmp` makes a difference unless you have a faster disk at another location.

**Comment by khanof89** [comment]
@AliasIO thank you so much ! one more request I have, can we just keep an instance of chrome running and just connect with it ? It may save startup time, though I have benefitted a lot from concurrent requests in a single chrome instance, but if we can connect with a running chrome instance instead of launching it everytime that will be awesome!

Thank you for such a wonderful project and such a speedy response. Can I buy you a coffee, if not purchasing your (wappalyzer.com) subscription ?

**Comment by AliasIO** [comment]
@khanof89 You should be able to set `wappalyzer.browser` to your own instance, instead of calling `wappalyzer.init()` and `wappalyzer.destroy()`.

If you like you can [sponsor me](https://github.com/sponsors/AliasIO) here on GitHub, or [PayPal](paypal.me/aliasio). Thank you!

**Comment by khanof89** [comment]
@AliasIO is it possible to use [puppeteer-cluster](https://github.com/thomasdondorf/puppeteer-cluster) to process a lot of urls at a time, and will it help performance improvement? 

Also, can we use GPU in anyway to boost performance ?

**Comment by AliasIO** [comment]
From what i understand puppeteer-cluster does the same thing: reuse the browser and run multiple pages parallel. It won't give you a performance benefit. I don't know about leveraging the GPU but I'd assume Chromium is already optimised for performance.

If performance is more important than accuracy, the are concessions you can make. E.g. you could run Wappalyzer over static HTML instead of in a fully functional browser with a JavaScript interpreter.

**Comment by khanof89** [comment]
I have tried to run the regex from technologies.json file against static HTML but it does not detect anything close to with what we can detect with the browser. Thanks man !

**Comment by AliasIO** [comment]
Wappalyzer used to run on Zombie.js, which uses Node.js and JSDOM to emulate a light-weight browser environment. It doesn't support APIs like WebSockets or Service Workers but it did a decent job. You can try finding an older version of Wappalyzer to see if that's good enough for your needs.
