### ISSUE TITLE
Detect technologies by passing data ?

### ISSUE THREAD

**Issue by khanof89** [AliasIO/wappalyzer#3366]
Is it possible to detect technologies by passing _headers_, _cookies_, _content_ and _scripts_ to one of the wappalyzer function ? I have another headelss process running which performs some other actions and then I will have all the above mentioned info about a website available with me, is it possible that I pass this info to wappalyzer and get an object as I would when using wappalyzer cli?

**Comment by AliasIO** [comment]
You can use [wappalyzer-core](https://www.npmjs.com/package/wappalyzer-core) for this.
