### ISSUE TITLE
Wappalyzer doesn't match script content RegEx

### ISSUE THREAD

**Issue by kpchand** [AliasIO/wappalyzer#3367]
**Platform**
* NPM

**Describe the bug**
Added a technology entry in technologies.json with a RegEx which will match inside script content.

The entry:

```
"matchMedia": {
            "website": "github.com",
            "cats": [
                59
            ],
            "html": "\\)\\{var\\s+n=window\\.matchMedia\\(e\\),r",
            "meta": {
                "generator": "DMX"
            }
        },
```

I have tried both all lower case and the one where case is exact. Would also like to know if regex matching is case sensitive?

**To Reproduce**

Go to https://www.goal.com/en-in. 
Run `node src/drivers/npm/cli.js https://www.goal.com/en-in`

Wappalyzer fails to match the following matchMedia JS content found in the web page:

`function(e,t){var n=window.matchMedia(e),r=this.list.find((function(e){return e.mql.media===n.media}));if(r&&(n=r.mql,t))return n.addListener(t),r.callbacks.push(t),r;var i={mql:n,callbacks:[]};return t&&(n.addListener(t),i.callbacks.push(t)),this.list.push(i),i},`

**Expected behavior**

Should have outputted _matchMedia_ as a used technology.

**Comment by AliasIO** [comment]
The regex works for me on the example you provided. Did you run `yarn run link`?

HTML patterns must include a `<` or `>` to avoid matching plain text. In this case it would be better to just use `"js": { "matchMedia": "" }`.

**Comment by kpchand** [comment]
> The regex works for me on the example you provided. Did you run `yarn run link`?
> 
> HTML patterns must include a `<` or `>` to avoid matching plain text. In this case it would be better to just use `"js": { "matchMedia": "" }`.

If I were to just use `"js": { "matchMedia": "" }` then how would I supply the regex? I am using 5 chars before and after wherever matchMedia is found in script src content to do a strong match.

Also I wanted to confirm if regex matching is case insensitive?
