### ISSUE TITLE
Add Tailwind CSS

### ISSUE THREAD

**Issue by martinleib** [AliasIO/wappalyzer#3382]
Website: https://tailwindcss.com/

Examples:
https://iworkedon.com/
https://tailwindtoolbox.github.io/Minimalist-Blog/

Script: 
- `unpkg.com/tailwindcss`
- `<link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">`

**Comment by honjes** [comment]
Do you know how tailwindcss can be detected on `https://iworkedon.com/` ?
Because i don't see it loaded over a link.

**Comment by q60** [comment]
maybe the devs of that page are not using Tailwind anymore. anyways, some of the pages I've made are using Tailwind. If you want I can link you to them.

**Comment by q60** [comment]
> Do you know how tailwindcss can be detected on `https://iworkedon.com/` ?
> Because i don't see it loaded over a link.

maybe the devs of that page are not using Tailwind anymore. anyways, some of the pages I've made are using Tailwind. If you want I can link you to them.

**Comment by honjes** [comment]
> If you want I can link you to them.
That would be great.

**Comment by ConradSollitt** [comment]
Most sites using Tailwind will likely use a version of it built for the site so I would expect very few sites will actually have a `tailwindcss` file. 

Here is a example of what the CSS classes in HTML looks like from the main site: https://tailwindcss.com/

![image](https://user-images.githubusercontent.com/57777521/110701271-d2229200-81a5-11eb-87f3-f09aa920c813.png)

I see two options for checking tailwind:

## Option (1) - Check for known specific classes

Query Selector for classes unique to tailwind such as `xl:max-w-screen-xl` and `lg:max-w-screen-xl`

```html
<!-- [https://tailwindcss.com/] uses [xl:max-w-screen-xl] with [mx-auto] -->
<header class="relative z-10 max-w-screen-lg xl:max-w-screen-xl mx-auto">

<!-- [https://iworkedon.com/] uses [lg:max-w-screen-xl] with [mx-auto] -->
<div class="relative max-w-xl mx-auto px-4 sm:px-6 lg:px-8 lg:max-w-screen-xl mt-20">
```

```js
// This would pick the above two sites but not [https://tailwindtoolbox.github.io/Minimalist-Blog/]
// NOTE - the ":" is escaped using "\\3A "
document.querySelectorAll('.mx-auto.xl\\3A max-w-screen-xl, .mx-auto.lg\\3A max-w-screen-xl')
```
The challenge will be finding enough classes that most tailwind sites use.

## Option (2) - Check ratio of elements that contain ":" in a class name

This test seems much easier and correctly determines tailwind for all 3 sites. Basically if more than 5% of elements on the page contain `:` then the page would imply usage of tailwind.

```js
(document.querySelectorAll('[class*=":"]').length / document.querySelectorAll('*').length) > 0.05
 ```

After glancing at the code and JSON definition file it looks like a new property/evaluation type would have to be added to handle the 2nd option. Additionally if a change for this is made a large list (or good size list) of sites using tailwind should be checked to see if tailwind is matched as the 5% number I gave may have to be tweaked.

* https://github.com/AliasIO/wappalyzer/blob/master/src/drivers/npm/driver.js
* https://raw.githubusercontent.com/AliasIO/wappalyzer/master/src/technologies.json
