### ISSUE TITLE
Add Divi to Page Builders being tracked

### ISSUE THREAD

**Issue by baddiedev** [AliasIO/wappalyzer#3384]
**Is your feature request related to a problem? Please describe.**
Not related to a problem

**Describe the solution you'd like**
I'd like to see [Divi](https://www.elegantthemes.com/gallery/divi/) added to the list of [Page Builder](https://www.wappalyzer.com/technologies/page-builders/) technologies being tracked. It would surely be a competitor for Elementor's market share.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by honjes** [comment]
Could you provide a site that was build using divi ?

Also this should be labeled as Technology request.

**Comment by baddiedev** [comment]
I agree it could be a Technology request, i couldn't figure out how to change the label after I posted it though.

Some examples of websites built using Divi...
  http://www.funkenginemusic.com/
  https://www.mattparryphotography.co.uk/
  http://mini-you.co.uk/
  https://impulse-eve.com/
  https://timelinemissions.com/

Links to more can be found [here](https://winningwp.com/divi-wordpress-theme-examples/) but a lot of them seem to be broken

**Comment by honjes** [comment]
Thanks for the links.

**Comment by rockeynebhwani** [comment]
@baddiedev @AliasIO - This can be closed as I see 'Divi' has been added.
