### ISSUE TITLE
Tech Request: Add Statamic CMS

### ISSUE THREAD

**Issue by shaykingsbury** [AliasIO/wappalyzer#3387]
Statamic CMS Site: https://statamic.com/

Example sites:

- https://www.mailerlite.com/
- https://usefathom.com/

Don't know the scripts 😬

**Comment by AliasIO** [comment]
Shay! Fancy meeting you here. I had a look but there doesn't seem to be any trace of the CMS anywhere in the websites' source code, which is pretty typical for static site generators. I don't think it can be added.

**Comment by shaykingsbury** [comment]
Such a sad story! I also had a look and can't see anything Stat specific. Oh well. Until next time.
