### ISSUE TITLE
Is bookmarklet still being supported?

### ISSUE THREAD

**Issue by jhdxr** [AliasIO/wappalyzer#3410]
**Platform**
Which platform does the bug apply to?
* Bookmarklet

**Describe the bug**
I tried to use wappalyzer bookmarklet today but it doesn't work. the console log indicates https://www.wappalyzer.com/bookmarklet/wappalyzer.js is not valid, and actually it looks like a 404 page now.

**Comment by AliasIO** [comment]
The bookmarklet has been deprecated but I restored the missing file, it should work for you now.

**Comment by jhdxr** [comment]
I confirm it works again. thanks.
