### ISSUE TITLE
Safari Extension?

### ISSUE THREAD

**Issue by xDenzil** [AliasIO/wappalyzer#3411]
Are there any plans to develop a safari extension? I hear with the new safari update it will be easier to migrate extensions available on chrome to work with safari as well.

**Comment by AliasIO** [comment]
See #3286.

**Comment by AliasIO** [comment]
https://apps.apple.com/au/app/wappalyzer/id1520333300

**Comment by xDenzil** [comment]
Nice! I've been checking every week for this. Thank you.

**Comment by xDenzil** [comment]
@AliasIO Hey is it possible to update the style so it matches other extensions in the toolbar?  I'm a designer so I don't mind volunteering if you're busy.
<img width="236" alt="Screenshot 2020-11-21 at 3 32 35 PM" src="https://user-images.githubusercontent.com/46894735/99887018-ebabc800-2c0e-11eb-851c-29456caa5ae4.png">

**Comment by AliasIO** [comment]
Yeah, would love to. It looks like Safari doesn't support `browserAction.setIcon` properly so we can't set it dynamically based on the user agent. I'll see what I can do.

![default-safari](https://user-images.githubusercontent.com/77259/99921389-339d2d00-2d7e-11eb-88f7-8c7e67647823.png)
