### ISSUE TITLE
Dockerfile NPM chromium error!

### ISSUE THREAD

**Issue by seyfullahkilic** [AliasIO/wappalyzer#3414]
**Platform**
Docker (images: debian)
* NPM
* NPM version: 6.14.8
* Node version: v14.13.0
* Yarn version: 1.22.5

**Describe the bug**
When I install the wappalyzer with yarn on debian image on ubuntu, I had got the following error:
"Failed to set up Chromium r800071! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download"

**Solution**
Then, I added following codes and resolved the bug.
RUN apt-get install udev chromium git -y
RUN npm i puppeteer

My Dockerfile:
```

FROM debian:stable
WORKDIR /app

ADD . /app

# Install dependencies
RUN apt-get update
RUN apt-get install -y python3 python3-pip git make gcc curl sudo libnss3-dev

#Node+NM sources
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash
RUN apt-get update && apt-get install -y nodejs

#YARN sources
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

#INSTALL yarn
RUN apt update && apt install yarn

#Settings
RUN apt-get install udev chromium git -y
RUN npm -v && node -v && yarn --version

# Clone wapplyzer
RUN git clone https://github.com/AliasIO/wappalyzer.git
WORKDIR /app/wappalyzer/

RUN npm i puppeteer
RUN yarn install
RUN yarn run link

ENTRYPOINT ["python3", "/app/file.py"]
```

**Comment by AliasIO** [comment]
I can't really help you with that. The official setup uses Alpine Linux and no Python, which works. https://github.com/AliasIO/wappalyzer/blob/master/src/drivers/npm/Dockerfile
