### ISSUE TITLE
PIXIjs webgl canvas

### ISSUE THREAD

**Issue by djmisterjon** [AliasIO/wappalyzer#3422]
**PIXIjs**: as **JavaScript Libraries**

**Official**:

- https://www.pixijs.com/
- https://www.pixiplayground.com
- https://pixijs.io/examples/#/demos-basic/container.js
- http://pixijs.download/release/docs/PIXI.html
- https://www.html5gamedevs.com/forum/15-pixijs/
- https://chrome.google.com/webstore/detail/pixijs-devtools/aamddddknhcagpehecnhphigffljadon

**Github**:

- repo:  https://github.com/pixijs
- core: https://github.com/pixijs/pixi.js

**Example site:**

- https://www.google.com/doodles/halloween-2018
- https://mmm.hsiao.science/
- https://art4globalgoals.com/en
- https://brandstudio.ru/en/
- https://bonk2.io/beta/
- https://game.hyeon.me/wbwwb/

**Detection script:**
```js
window?.PIXI?.VERSION || global?.PIXI?.VERSION || PIXI?.VERSION;
```
![image](https://user-images.githubusercontent.com/24865815/95682893-f1e16a00-0bb5-11eb-9e5b-63d8495cfd70.png)

**Note**: PIXI use **webgl** or **canvas** rendering (if webgl not available! (mostly in mobile), it fallback in canvas mode)
in most case , utility allow to see in what rendering mode.
```js
PIXI?.utils?.isWebGLSupported(); // true:webgl rendering  false:canvas rendering
```
except if for x reason the developer has chosen not to include utilities with a custom build in productions. (byDefault utility are include in core)
You will need use classic way : https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/By_example/Detect_WebGL

Developer tool also allow detect PIXIjs, see link in official.

**official logo:**
![256](https://user-images.githubusercontent.com/24865815/95683283-366e0500-0bb8-11eb-894d-67eaeaeb3064.png)

**Analytic**
https://www.similarweb.com/website/pixijs.com/

**Comment by AliasIO** [comment]
Thanks! This one has been added.
