### ISSUE TITLE
Docker hub image deleted?

### ISSUE THREAD

**Issue by tristanlatr** [AliasIO/wappalyzer#3429]
**Platform**
- Docker

**Describe the bug**
The offical docker image seems to no longer exists...

**To Reproduce**
```
docker pull wappalyzer/cli
Error response from daemon: pull access denied for wappalyzer/cli, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
````

**Expected behavior**
It should work no ?

**Comment by hugokernel** [comment]
Any information about that please ?

**Comment by dzmitry-savitski** [comment]
+1

**Comment by x0rzkov** [comment]
@AliasIO 

hope you are all well !

the same for me, what happened to them ? 

can you advise please ?

**Comment by AliasIO** [comment]
Sorry about that, the image has been restored. It hasn't been maintained for some time and is now deprecated. I recommend using the NPM package or building your own image if you want to use the latest.
