### ISSUE TITLE
Crashes with invalid certificate and probe set to true

### ISSUE THREAD

**Issue by HanXHX** [AliasIO/wappalyzer#3431]
**Platform**
Which platform does the bug apply to?
* NPM

**Describe the bug**

With an invalid certificate and when you use `prob` to true with a bad HTTPS web site (ex: Recent Worst on https://www.ssllabs.com/ssltest/analyze.html). Wappalyzer crashes.

Chrome uses `--ignore-certificate-errors` option. But `probe` seems using low level nodejs functions...

Ex:

```
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1506:34)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket._finishInit (_tls_wrap.js:948:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)
Emitted 'error' event on ClientRequest instance at:
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
}
```

Please note, you can bypass this issue by setting env var `NODE_TLS_REJECT_UNAUTHORIZED` to `0`.

**To Reproduce**

Note: Change `bad_url` variable

```js
const Wappalyzer = require('wappalyzer');

(async () => {

        const bad_url = 'https://google.com';

        const wappalyzer = await new Wappalyzer({ probe: true });
        await wappalyzer.init();

        const site = await wappalyzer.open(bad_url)
        const results = await site.analyze();

        console.log(results)
        await wappalyzer.destroy();
})();

```

**Expected behavior**
No crashes.

**Additional context**

Tested on many NodeJS 12 + Debian Buster (Docker or standard system)

**Comment by AliasIO** [comment]
Fixed in 07420925524f0ab82d38e96ef57478b2c416701e, thanks!
