### ISSUE TITLE
How wappalyzer detects database?

### ISSUE THREAD

**Issue by SmartManoj** [AliasIO/wappalyzer#3437]
Is it added manually?

**Comment by AliasIO** [comment]
Hi, yes. Have a look at https://github.com/AliasIO/wappalyzer/blob/master/README.md.

**Comment by SmartManoj** [comment]
The word 'database' is not found

**Comment by AliasIO** [comment]
Databases are usually identified indirectly. For instance when Magento is detected, MySQL is implied:

https://github.com/AliasIO/wappalyzer/blob/master/src/technologies.json#L7906
