### ISSUE TITLE
Add new product: Plesk 

### ISSUE THREAD

**Issue by nrllh** [AliasIO/wappalyzer#3441]
Hey,

You can recognize the Plesk (hosting management system) by using `x-powered-by` in Header.
It appears in the header as follows:

`x-powered-by: PleskLin`

It'd be also interesting to add Cpanel, but I don't have there the experience to identify it.

**Comment by AliasIO** [comment]
Plesk and cPanel are already being detected, let me know if it's not working anywhere.

**Comment by h1z1** [comment]
Not sure if it's worth opening another request for plesk or not but there are a couple other tokens to detect it with

```
<meta name="plesk-build" content="1800220207.23">
<meta name="plesk-revision" content="hash">
```

```
<script type="text/javascript" src="/ui-library/plesk-ui-library.min.js?1643980938"></script>

<div id="plesk-root"></div>
```

etc?

**Comment by AliasIO** [comment]
@h1z1 Please open a new issue for this, thanks!
