### ISSUE TITLE
Wappalyzer reports React for most of the sites, not using React

### ISSUE THREAD

**Issue by PatricNox** [AliasIO/wappalyzer#3444]
**Platform**
MacOS 

* Chrome

**Describe the bug**
Using the analyzer on websites, such as JIRA, bitbucket and w3schools, wappalyzer reports the site for using React. However, they're not.

**To Reproduce**

1. Go to w3school

ie. https://www.w3schools.com/cssref/css3_pr_overflow-x.asp

2. Click the extension to see what is used for the website

3. Note "react" being the JS framework. But in fact, it's not.

**Expected behavior**

I expect the report to not give false information.

![image](https://user-images.githubusercontent.com/31646653/97171201-580ce600-178d-11eb-8822-5766f415e398.png)

**Comment by PatricNox** [comment]
For even more confirmation I used this on my portfolio which I made myself, which is not in React, however wappalyzer says it is built in React.

https://patricnox.info/ 

![image](https://user-images.githubusercontent.com/31646653/97171311-8b4f7500-178d-11eb-962f-a6fdd03f9246.png)

**Comment by AliasIO** [comment]
Hi, it's not reporting React for me on the examples you provided. Do you perhaps have an extension installed that injects React into the pages for some reason?

**Comment by PatricNox** [comment]
Oh, it could be the Vue Devtools extension. Is that possible?

**Comment by AliasIO** [comment]
That's not it, I have Vue DevTools installed and it's unlikely that it'd be injection React into pages.

**Comment by PatricNox** [comment]
hmm.. That was my only suspect. 

This is my extensions list:

![image](https://user-images.githubusercontent.com/31646653/97406261-40527080-18f9-11eb-9b34-239bcbb63bd5.png)

**Comment by sasatefa2009** [comment]
@PatricNox @AliasIO

 **It's the WOT Web of Trust extension.**

I installed all of your extensions till I found it.

**Comment by PatricNox** [comment]
@sasatefa2009  Thank you so much!
