### ISSUE TITLE
Unable to match Uppercase cookies

### ISSUE THREAD

**Issue by Zer1t0** [AliasIO/wappalyzer#3458]
**Platform**
Which platform does the bug apply to?
WebExtension (and probably NPM)

**Describe the bug**
The names of the cookies are loaded in lowercase, so it fails to check when names contains uppercase letters.

When matching cookies (and maybe other items) in function `analyzeManyToMany`, the `items` object it accessed to extract values, in line 430, if the name of cookie contains uppercase letters, the `key` won't match (even if cookie name is spelled correctly in technologies.json) with any of the `items` keys and the rules won't be applied. 

I let you an example of a web page that returns JSESSIONID cookie (https://54.186.113.100/#/login) but Java is not recognize due to this bug.
![jsessionid](https://user-images.githubusercontent.com/17518559/97439857-013b1400-1927-11eb-96e7-9489c7cbacf4.png)

**To Reproduce**
Go to https://54.186.113.100/#/login or any other page that returns a JSESSIONID cookie.

**Expected behavior**
Java software is recognized.

**Additional context**
I did not test further, but maybe this bug could affect to other pair values such as headers.

Thank you for such an amazing extension.

**Comment by AliasIO** [comment]
Fixed in 59b55d3c29429dd219b7f241338222b6e200feb6, thanks!
