### ISSUE TITLE
styled-components doesn't seem to be accurately detected

### ISSUE THREAD

**Issue by mxstbr** [AliasIO/wappalyzer#3470]
**Platform**
* WebExtension (Google Chrome, Mozilla Firefox)

**Describe the bug**
styled-components is not accurately detected by the extension. For example, the styled-components.com website (which obviously uses it) does not report that technology:

<img width="1064" alt="Screenshot 2020-11-02 at 09 02 54" src="https://user-images.githubusercontent.com/7525670/97844131-c3553b80-1cea-11eb-98cf-38717923ba57.png">

**To Reproduce**
1. Go to https://styled-components.com
2. Click on the Wappalyzer extension

**Expected behavior**
It should report that styled-components is used, however that's not the case.

**Additional context**

The way to detect styled-components is to look for `<style>` tags that have either a `data-styled` or a `data-styled-components` attribute. These are the three potential states:

```HTML
<!-- Server-side rendered -->
<style data-styled data-styled-version="5.2.0">...</style>

<!-- Client-side rehydrated -->
<style data-styled="active" data-styled-version="5.2.0">...</style>

<!-- Legacy pre-v5 -->
<style data-styled-components>...</style>
```

I think the second one might not be handled correctly, looking at the current regexes? 

https://github.com/AliasIO/wappalyzer/blob/3367d2a858ba09ebd55494e73a00a1fe755f9c89/src/technologies.json#L16947-L16951

Looking at this, it might make sense to simply report styled-components being used if any `data-styled*` attributes are found on a `<style>` tag?

**Comment by AliasIO** [comment]
Fixed in https://github.com/AliasIO/wappalyzer/commit/3dbf0a54c54263b677bbd22e9083d05eaeee4d56#diff-ad6b5aefcc8c0ba3d7c9f4c9ba096652f7bae1235363a40bba4759f3abb374c4R16947

Thanks!
