### ISSUE TITLE
NPM package didn't detect  Google Analytics 

### ISSUE THREAD

**Issue by pralivera** [AliasIO/wappalyzer#3476]
**Platform**
Which platform does the bug apply to? NPM

**Describe the bug**
I tried to analyze the following URL and the result only displays a limited number of technologies and not identified  Google Analytics. Please find bellow result as well

URL : https://stratechia.com/
Results: 
{"urls":{"https://stratechia.com/":{"status":0,"error":"The website took too long to respond"}},"technologies":[{"slug":"wordpress","name":"WordPress","confidence":100,"version":null,"icon":"WordPress.svg","website":"https://wordpress.org","cpe":"cpe:/a:wordpress:wordpress","categories":[{"id":1,"slug":"cms","name":"CMS"},{"id":11,"slug":"blogs","name":"Blogs"}]},{"slug":"php","name":"PHP","confidence":100,"version":null,"icon":"PHP.svg","website":"http://php.net","cpe":"cpe:/a:php:php","categories":[{"id":27,"slug":"programming-languages","name":"Programming languages"}]},{"slug":"mysql","name":"MySQL","confidence":100,"version":null,"icon":"MySQL.svg","website":"http://mysql.com","cpe":"cpe:/a:mysql:mysql","categories":[{"id":34,"slug":"databases","name":"Databases"}]},{"slug":"nginx","name":"Nginx","confidence":100,"version":null,"icon":"Nginx.svg","website":"http://nginx.org/en","cpe":"cpe:/a:nginx:nginx","categories":[{"id":22,"slug":"web-servers","name":"Web servers"},{"id":64,"slug":"reverse-proxies","name":"Reverse proxies"}]},{"slug":"siteground","name":"SiteGround","confidence":100,"version":null,"icon":"siteground.svg","website":"https://www.siteground.com","cpe":null,"categories":[{"id":62,"slug":"paas","name":"PaaS"}]},{"slug":"sucuri","name":"Sucuri","confidence":100,"version":null,"icon":"sucuri.png","website":"https://sucuri.net/","cpe":null,"categories":[{"id":31,"slug":"cdn","name":"CDN"}]}]}

**Expected behavior**
It should return GA with the result JSON

**Comment by AliasIO** [comment]
It does detect GA for me. I can an error in your output which might be the reason:

> The website took too long to respond
