### ISSUE TITLE
Add squarespace ecomerce to the 

### ISSUE THREAD

**Issue by vfcampo** [AliasIO/wappalyzer#3513]
**Is your feature request related to a problem? Please describe.**
My team find frustrating that we are not able to identify a Squarespace e-commerce website using wappalizer

**Describe the solution you'd like**
Include Squarespace in the list of commerce technologies when the website is created with Square space and has the e-commerce module enabled.

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/55451462/98957949-6108f180-24c7-11eb-8ab2-e2646995dcb3.png)

Use the element depicted in the screenshot as fingerprints to identify whenever the e-commerce module is on

**Comment by nurbek91** [comment]
@vfcampo He mate. Added #3510 a few hours ago.

**Comment by vfcampo** [comment]
Sorry I checked yesterday and posted today.  I'm going to move the content there to prevent dups Thanks for the heads-up

**Comment by vfcampo** [comment]
Moved to #3510
