### ISSUE TITLE
Unchecked runtime.lastError: The message port closed before a response was received.

### ISSUE THREAD

**Issue by matthiasm11** [AliasIO/wappalyzer#3529]
**Platform**
Which platform does the bug apply to?
* WebExtension (Google Chrome)

**Describe the bug**
When visiting a website, f.e. https://www.google.com, the following error is thrown in the browser console:
`Unchecked runtime.lastError: The message port closed before a response was received.`

**To Reproduce**
1. Go to https://www.google.com
2. Open the console, the error is present.

**Additional context**
The error isn't always being thrown. Doing hard refreshes (CMD+R or CTRL+F5), it is appearing +-25% of the time.
I'm not the only person getting this, the review on November 12th on https://chrome.google.com/webstore/detail/wappalyzer/gppongmhjkpfnbhagpmjfkannfbllamg states the same error.
All other extensions are disabled.

**Comment by matthiasm11** [comment]
Similar old (fixed) issues:
- https://stackoverflow.com/questions/43154963/promise-error-the-message-port-closed-before-a-reponse-was-received
- https://github.com/AliasIO/Wappalyzer/issues/1487
- https://github.com/AliasIO/wappalyzer/issues/1489

**Comment by kamilkozak** [comment]
Same issue here. It appeared from version v6.4.14

**Comment by AliasIO** [comment]
Fixed in v6.5.17.
