### ISSUE TITLE
Drupal version presentation

### ISSUE THREAD

**Issue by macmladen** [AliasIO/wappalyzer#3538]
**Platform**
Which platform does the bug apply to?
* **All**
* WebExtension (Google Chrome, Mozilla Firefox)
* NPM
* Bookmarklet
* Website

**Describe the bug**
This is more of a suggestion than a bug: while detecting Drupal site version, it is always represented with an Drupal 9 icon which is misleading especially when there is a number in superscript on the icon which also looks like suggesting a version and not the number of technologies detected.

**To Reproduce**
1. Go to any Drupal site, e.g. drupal.org
2. The icon is Drupal 9 icon (and 13 technologies)

**Expected behavior**
Drupal 7 icon

**Additional context**
The icons are available all over the net, here are for 9 and 7 at least https://www.drupal.org/about/media-kit/logos

Drupal 9
![image](https://user-images.githubusercontent.com/572289/99373855-330a1f80-28c2-11eb-8fa1-c5a23fa69da6.png)

Drupal 8
![image](https://user-images.githubusercontent.com/572289/99373648-f2120b00-28c1-11eb-8017-ae0964f40a18.png)

Drupal 7
![image](https://user-images.githubusercontent.com/572289/99373970-592fbf80-28c2-11eb-930f-01a15089d42d.png)

**Comment by AliasIO** [comment]
It's a valid point but it would mean adding the different versions as separate technologies. Most technologies don't use version specific logos and I think using the most recent one is acceptable in this case.

**Comment by macmladen** [comment]
I agree it is acceptable.

However, I still think it is an interesting idea just as it would be to have a small number as a subscript on the icon to mark a version (W5, W4, React14, Angular 10...) as we all tend to grasp as much information with least effort.

Other than that, as a fellow developer, I would find it interesting and challenging to add "version_icon" to the "version" property to the technology.

Anyway, thanks for the great tool, it helps a lot.

**Comment by kyletaylored** [comment]
Given the lift it would take to add a version_icon and the unlikeliness that it would be added, I'm going to close this issue for now.
