### ISSUE TITLE
Add EasyUI Detection

### ISSUE THREAD

**Issue by alejandro-escobar-89** [AliasIO/wappalyzer#3547]
I'd like to request the inclusion of the [EasyUI](http://jeasyui.com/) front-end framework. Thanks.

**Comment by honjes** [comment]
Can you add some sites where the framework is used ?

**Comment by alejandro-escobar-89** [comment]
Yeah, no can do, sorry. Unfortunately it's not a very comon technology, but
we use it very often at my current job. That's why we wanted you guys to
include it in Wappalizer, so that we could chek out some other web apps
that work with it. Since it's an app-oriented framework (like ExtJS) I
don't know any public website that implements this technology. In any case,
thank you. Great job you guys are doing with this.

**Comment by AliasIO** [comment]
Our aim is to include widely used technologies so if an established user base can't be demonstrated it might not be a good fit!
