### ISSUE TITLE
Add a category for WebAssembly and JavaScript

### ISSUE THREAD

**Issue by kirisaki** [AliasIO/wappalyzer#3551]
**Is your feature request related to a problem? Please describe.**
I tried to add WebAssembly to technologies, but I noticed that there is no category which suit for it. "Programming Language" is about to suit, but not perfectly. "Programming Language" which already exists means probably as server-side language. Before, programming language runs in browser was only one language, JavaScript. But now, byte-codes compiled from WebAssembly run. WebAssembly is a programming language itself, but it's similar in that they are compiled and run on browsers. 

**Describe the solution you'd like**
Then, I suggest a category for WebAssembly and JavaScript. But I have no good idea for its name. "Web Platform" is in a too broad sense. "Client-side Platform"? I have never heard. Anyone has any idea? Anyway, I believe we need a new category for client-side technologies.

**Describe alternatives you've considered**
Just include WebAssembly to "Programming Language" only.

**Additional context**
X

**Comment by kirisaki** [comment]
I talked big about categories, but I'm starting to feel about ok  to just add category "Miscellaneous" with "Programming Language".

**Comment by AliasIO** [comment]
Let's use Programming Language even though it's not perfect. Node.js is similar, it's a runtime and not a language but we added it there anyway.

**Comment by kirisaki** [comment]
OK, let's run with it. I will make a PR.
But in the future, wanna make it indicate something different from other languages by something way.
Wappalyzer might be able to distinguish a language before compiled by reading wasm binary, if compilers deal with [custom sections](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Module/customSections).
Anyway, I think it's ok to close this issue for now. Or keep it open until the time?
I'll leave it to you/
