### ISSUE TITLE
Deal with events after first DOM rendered

### ISSUE THREAD

**Issue by kirisaki** [AliasIO/wappalyzer#3554]
**Is your feature request related to a problem? Please describe.**
I added #3553 detecting wasm, but it didn't work almost. [Only a wasm of this site](https://rhysd.github.io/vim.wasm/) could be detected. Difference of other sites is that the wasm is provided via service worker.

As far as I can read the code, I guess Wappalyzer analyses responses coming from start of first page request until first DOM rendered. Wasm byte-codes are read asynchronously by "dynamic import", so probably analysis finishes before done it, or Wappalyzer can't catch "dynamic import" event from the start. 

**Describe the solution you'd like**
I'd like you to consider to deal with asynchronous requests after DOM rendered. Then Wappalyzer must watch events infinitely, so we must worry about memory. It's OK to stop it adequate time ago, or when the tab isn't active. And need to test if can Chrome extensions catch dynamic import event.

**Describe alternatives you've considered**
Forget about after first DOM rendered.

**Additional context**
N/A

**Comment by AliasIO** [comment]
Wappalyzer waits 1 second after page load before analysing. We capture dynamic imports as longs as they happen within this time.

https://github.com/AliasIO/wappalyzer/blob/master/src/drivers/webextension/js/content.js#L14

**Comment by kirisaki** [comment]
I have examined, understood and remember, dynamic importing wasm is compiled into `fetch()` and `WebAssembly.Module.imports()`. This means wasm modules are not added to `document.scripts`. We can detect wasm at the website, I suppose that reason is the behavior of services worker. I don't know a lot of behavior of service worker yet.

Service worker aside, detecting wasm requires watching http accesses. And other various accesses would have benefit from this feature. For example, a SPA serves static files via something CDN, but Wappalyzer may can detect web framework by watching API calls.

**Comment by AliasIO** [comment]
Wappalyzer doesn't inspect network requests other than the initial page to optimise for performance. If a script is dynamically included Wappalyzer can usually still see any JS newly defined variables or DOM changes but only in the first second after page load. You're right that inspecting everything would be better for accuracy.

**Comment by kirisaki** [comment]
It's available to capture JS variables changing? Really? If so, Wappalyzer watches fetching dynamic importing then is able to detect wasm by analyzing byte-code! All it takes is reading only some bytes from the head.

**Comment by AliasIO** [comment]
What I meant is that if a script gets loaded asynchronously and executed, any globally accessible variables can be inspected.

Can you show me what it looks like when a website uses Wasm?
