### ISSUE TITLE
jsdelivr categorised as CDN

### ISSUE THREAD

**Issue by Kent1** [AliasIO/wappalyzer#3555]
**Platform**
Wappalyzer NPM module v6.3.12

**Describe the bug**
I see that jsdelivr reports to category 31 CDN. Isn't the goal of that category to detect CDN that serves the page itself, and not a few JS libs ?

**Comment by honjes** [comment]
jsDelivr is actual an cdn: https://www.jsdelivr.com/

**Comment by Kent1** [comment]
It is indeed. However, saying that the page use CDN technologies isn't quite right for me.
We should make the distinction of the url is using resources from CDN vs the website is served by a CDN (like cloudflare)

**Comment by honjes** [comment]
Hm i get wat you are saying  its a good point. Do you think there should be a new Category for that ?
Somthing like 'Script CDN' and 'Site CDN' ?

**Comment by Kent1** [comment]
I think that already been discussed, however never done maybe ?

I won't go through all issues i can find but here some examples:
https://github.com/AliasIO/wappalyzer/pull/1851
https://github.com/AliasIO/wappalyzer/pull/860
https://github.com/AliasIO/wappalyzer/issues/132
https://github.com/AliasIO/wappalyzer/pull/3381 (this is yours, and it has been accepted)

I think indeed we should split the category. Using a CDN resource or being served by a CDN.

**Comment by AliasIO** [comment]
I think it's fine in this case. I don't want to report a CDN when a website simply loads an image from CloudFront or CloudFlare but loading a script from jsDelivr does qualify as using the technology in my opinion.
