### ISSUE TITLE
invalid technologies.json 

### ISSUE THREAD

**Issue by savushkin-yauheni** [AliasIO/wappalyzer#3562]
https://github.com/AliasIO/wappalyzer/blob/ec98590f2005bb81f8207e5405b643a399e77667/src/technologies.json#L1744

Hi guys. Could you check this line ? It fails on it.
Json schema is invalid. 
general usage is broken: 
`wappalyzer xxx` - doesn't work.

**Comment by AliasIO** [comment]
Fixed in #3563, thanks!
