### ISSUE TITLE
Doesn't detect anything on localhost when using firefox

### ISSUE THREAD

**Issue by Floffah** [AliasIO/wappalyzer#3564]
**Platform**
Which platform does the bug apply to?
* WebExtension (Mozilla Firefox)

**Describe the bug**
When browsing to a site on localhost, the firefox extension does not detect anything

**To Reproduce**
start a localhost server that uses react and webpack or anything wappalyzer picks up, go to it on your browser

**Expected behavior**
wappalyzer shows you what technologies it uses

**Additional context**
![image](https://user-images.githubusercontent.com/27270386/100484404-35574f80-30f4-11eb-91ec-74bc7edf71b4.png)

firefox extension version 6.5.19
firefox version 83.0
windows version pro 10.0.19041.630

works fine on any website that is not hosted local. localhost and any website works on chrome and edge its just firefox that hates local sites

**Comment by AliasIO** [comment]
This has been bugging me as well but it seems to be a Firefox issue.

This call to `chrome.tabs.query` doesn't return anything when querying localhost with a port number:

https://github.com/AliasIO/wappalyzer/blob/master/src/drivers/webextension/js/driver.js#L468
