### ISSUE TITLE
Probe option causes program to hang for some sites

### ISSUE THREAD

**Issue by MattMartin1919** [AliasIO/wappalyzer#3595]
**Platform**
Which platform does the bug apply to?
* NPM

**Describe the bug**
It seems using the "probe" option causes Wappalyzer to hang on some sites when the robots.txt doesn't return.

**To Reproduce**
Set up a NPM instance and try to get the results from `store.acer.com` with and without the probe option.  You will see that the program hangs forever with the probe option set.

**Expected behavior**
Wappalyzer respects the "maxWait" option when trying to get the robots.txt url and throws an error after X seconds.

**Additional context**
Same problem on windows and mac.

This is my first time reporting a bug for Wappalyzer so please let me know if you need more info!

**Comment by AliasIO** [comment]
Fixed in 967785c339a5809c1773e4beca5af3be6ba2274c, thanks.
