### ISSUE TITLE
[Docs Tools] Please add Docute and Slate

### ISSUE THREAD

**Issue by John4266** [AliasIO/wappalyzer#3612]
Hello.
Please add:

Docute
Project Site: https://docute.org/
Example Site: https://telegraf.js.org/

Slate
Project Repo: https://github.com/slatedocs/slate
Example Sites:
https://slatedocs.github.io/slate/#introduction
https://yourwaifu.dev/sleepy-discord/documentation.html

Thanks.

**Comment by nurbek91** [comment]
@John4266 Hey mate . These technologies don't even have a logo. Are mainstream technologies enough?  I am not sure until ;)

**Comment by nurbek91** [comment]
Hey @John4266  
Example Site: https://telegraf.js.org/  using TypeDoc which added recently .
Example Site: https://yourwaifu.dev/sleepy-discord/documentation.html sing Docusaurus which identified already.

@AliasIO hey mate . i think here we can close this tech request

**Comment by John4266** [comment]
> 
> 
> Example Site: https://telegraf.js.org/ using TypeDoc which added recently .

Uhm, wdym?
I don't see it was added.
