### ISSUE TITLE
Make Wappalyzer regular expression execution asynchronous

### ISSUE THREAD

**Issue by q--** [AliasIO/Wappalyzer#362]
Currently, Wappalyzer is executing regular expressions right after the headers are received, the DOM of a web page is loaded and `load` events are fired. Testing these regular expressions every time will have the browser hang until they are executed.

It should be possible to offload this to a `Worker` process, so Wappalyzer won't block the main thread.

https://developer.mozilla.org/en-US/docs/Using_workers_in_extensions

**Comment by hbakhtiyor** [comment]
still not yet implemented?

**Comment by AliasIO** [comment]
With WebExtensions, this doesn't apply any more.

**Comment by AliasIO** [comment]
Implemented in 74bb8fa56aec8a9692bbdc5c086b957ff4950e5c. Looks like there is still a case for it.
