### ISSUE TITLE
ADD Movidesk 

### ISSUE THREAD

**Issue by JoaoADOSouza** [AliasIO/wappalyzer#3620]
You may request a new technology to be added but changes of having it included are greatly improved if you submit a pull request. Please refer to the [documentation](https://docs.wappalyzer.com/dev/contributing.html#adding-a-new-application).

**Comment by kyletaylored** [comment]
>Only widely used technologies are accepted. When creating the request, include ten or more links to websites that use the application, a GitHub page with at least 1,000 stars or anything that will help establish the size of the user base.

Please re-open when you have more information provided.
