### ISSUE TITLE
Woo commerce - payments

### ISSUE THREAD

**Issue by vfcampo** [AliasIO/wappalyzer#3621]
Hey Team , 
I would like to ask if is possible to add woocommerce payment module to the payments category
Below is a screenshot from this website (https://www.pintailcoffee.com/) with some of the elements to match this module:

-  **jquery.payment.min.js:** `<script type="text/javascript" src="https://www.pintailcoffee.com/wp-content/plugins/woocommerce/assets/js/jquery-payment/jquery.payment.min.js?ver=3.0.0" id="jquery-payment-js"></script>`
- **sv-wc-payment-gateway-payment-form.min.js**:  `<script type="text/javascript" src="https://www.pintailcoffee.com/wp-content/plugins/woocommerce-gateway-authorize-net-cim/vendor/skyverge/wc-plugin-framework/woocommerce/payment-gateway/assets/js/frontend/sv-wc-payment-gateway-payment-form.min.js?ver=5.8.1" id="sv-wc-payment-gateway-payment-form-v5_8_1-js"></script>`
- **sv-wc-payment-gateway-payment-form.min.css** :` <link rel="stylesheet" id="sv-wc-payment-gateway-payment-form-v5_8_1-css" href="https://www.pintailcoffee.com/wp-content/plugins/woocommerce-gateway-authorize-net-cim/vendor/skyverge/wc-plugin-framework/woocommerce/payment-gateway/assets/css/frontend/sv-wc-payment-gateway-payment-form.min.css?ver=5.8.1" type="text/css" media="all">`

<img width="809" alt="Screen Shot 2020-12-11 at 10 00 53 AM" src="https://user-images.githubusercontent.com/55451462/101928060-c4f00a00-3b9a-11eb-8fa2-290d5a9f13f8.png">

**Comment by nurbek91** [comment]
https://github.com/skyverge/wc-plugin-framework/tree/master/woocommerce
I see that this is a  skyverge team development
But they have many plugins. And which one is used on this site, I do not understand yet
I can offer this option:
where do we meet `sv-wc-payment-gateway-payment `we define as **Skyverge Checkout** ?? But i am not sure!
![image](https://user-images.githubusercontent.com/3456008/101943973-34efa600-3c16-11eb-9137-d2d71f02c5ac.png)
https://woocommerce.com/vendor/skyverge/

**Comment by vfcampo** [comment]
You are right Nurbek, this is the right option in this case
> sv-wc-payment-gateway-payment we define as Skyverge Checkout
