### ISSUE TITLE
[Feature Request] add proxy option back

### ISSUE THREAD

**Issue by u23a** [AliasIO/wappalyzer#3624]
The proxy option was added in #2298, but was removed in this commit https://github.com/AliasIO/wappalyzer/commit/ebfef67608aec4aa062fa1af7e186e39bf88203f.

Is it possible add the proxy option back?

**Comment by alitoufighi** [comment]
Is there any updates on this?

**Comment by AliasIO** [comment]
Added in 62e6b328482c5820eb21c74f3be01ccd26fcd560.
