### ISSUE TITLE
Json format issue in technologies.json 

### ISSUE THREAD

**Issue by bretfourbe** [AliasIO/wappalyzer#3636]
Hi,
I noticed the technologies.json file is not recognized as a valid json because of a missing colon here :
https://github.com/AliasIO/wappalyzer/blob/8eb0af914ee80f55e3f7feff32bfed33f958e6fe/src/technologies.json#L5344
and a missing comma here :
https://github.com/AliasIO/wappalyzer/blob/8eb0af914ee80f55e3f7feff32bfed33f958e6fe/src/technologies.json#L8655
Could you fix this please ?
Thank you

**Comment by AliasIO** [comment]
Merged, thanks!
