### ISSUE TITLE
Wappalyzer doesn't detect technology stack of many websites like whatsapp

### ISSUE THREAD

**Issue by dingus45191** [AliasIO/wappalyzer#3647]
Why doesn't wappalyzer detect technology used on many sites especially whatsapp, twitter and all FB stuff. It doesn't even detect full technology stack on one of my sites. Please fix this ASAP

**Comment by dingus45191** [comment]
will it take you forever to solve this. at least say something

**Comment by Johannes-Andersen** [comment]
If you see missing technologies, open a ticket and include what technology you want added and example websites where the technology is used. No need to be toxic and rude  

Have a read at https://github.com/AliasIO/wappalyzer/blob/master/CONTRIBUTING.md if you want to add the technology yourself by opening a pull request. It is a open-source project, so anyone can contribute.

**Comment by dingus45191** [comment]
https://web.whatsapp.com/ 

should show react
