### ISSUE TITLE
Detection for accessiBe not working

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#3652]
**Platform**
Which platform does the bug apply to?
* WebExtension (Google Chrome)

**Describe the bug**
Detection for accessiBe is not working. Example site - https://www.rainbowshops.com/

Current detection 
```
"AccessiBe": {
      "cats": [
        68
      ],
      "description": "AccessiBe is an automated web accessibility solution for ADA and WCAG compliance. The system scans and analyzes a website using AI technology, and applies all the required adjustments to become ADA and WCAG 2.1 compliant.",
      "icon": "Accessibe.svg",
      "scripts": "acsbap\\.com/.*/acsb\\.js",
      "website": "https://accessibe.com/"
    },

```
Looks like, we are missing a 'p' in script pattern.

`"scripts": "acsbapp\\.com/.*/acsb\\.js",`

**Comment by nurbek91** [comment]
Hey mate . Updated the technology.
`https://acsbap.com/api/app/assets/js/acsb.js
`
Old links still exist on some sites. There is a redirect to a new link

`https://acsbapp.com/apps/app/assets/js/acsb.js`

We now consider both options.

**Comment by AliasIO** [comment]
Thanks both!
