### ISSUE TITLE
Incorrect detection of Oracle Commerce

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#3667]
Example - https://www.terral03.com/

Oracle commerce is incorrectly detected as eCommerce platform.

This site seems to have link (href="https://www.bestbuy.com/site/searchpage.jsp?_dyncharset=UTF-8&id=pcat17071&iht=y&keys=keys&ks=960&list=n&sc=Global&st=wifi%20booster&type=page&usc=All%20Categories") which is messing up I think due to 'dyncharset' in the link

**Comment by kyletaylored** [comment]
I believe you're right. The detection is iffy at best, but it would be more ideal if we're able to match or parse query string parameters as that one seems unique to Oracle.
