### ISSUE TITLE
Improve Shopware detection

### ISSUE THREAD

**Issue by derweili** [AliasIO/wappalyzer#3687]
Shopware detection is currently not stable. 
This could be fixed by adding `/themes/Frontend/` as a rule to scripts.

**Comment by AliasIO** [comment]
Do you have some examples where the detection isn't working?

**Comment by derweili** [comment]
@AliasIO yes, this site: https://www.coffeecircle.com/

**Comment by kyletaylored** [comment]
Looking at what the current detection is, I would say it's pretty sufficient so far. Adding `themes/Frontend` would be too generic and promote false positives. Great example, I randomly found this site (bama.com.sg) that has a `/themes/frontend` directory, but is not a Shopware site by any means. That path could be used by many different applications that utilize a `/themes` directory in the root.

For Shopware, I would say additional detection should be focused on widgets and scripts they provide to be embedded.
