### ISSUE TITLE
Installed but Safari does not recognize it

### ISSUE THREAD

**Issue by luccaayerza** [AliasIO/wappalyzer#3689]
**Platform**
MacOS Big Sur
* WebExtension (Safari)
**Describe the bug**
It is installed but Safari does not recognize it as an extension.

**Comment by pi-dal** [comment]
Platform:
 - MacOS Big Sur
Brower:
 - Safari

![app](https://user-images.githubusercontent.com/53357798/116777098-0b3cfb80-aa9f-11eb-9773-04e37c15f3d4.png)
![safari](https://user-images.githubusercontent.com/53357798/116777106-26a80680-aa9f-11eb-905d-1f9d969ef112.png)

I __also had this problem__.
Now it doesn't look like that's a special case.
If you have a solution, __please @ me__.
Thanks

**Comment by EazyFTW** [comment]
I recently just got an M1 Mac and I seem to have this issue too. I'm running macOS Monterey (12).
