### ISSUE TITLE
Prestashop with Warehouse Theme is incorrectly detected 'Wordpress CMS'

### ISSUE THREAD

**Issue by dapinna** [AliasIO/wappalyzer#3690]
**Platform**
Prestashop with Wharehouse Theme which includes a customized version for Prestashop of Elementor

* WebExtension (Google Chrome, Mozilla Firefox)
Boot: Mozilla Firefox and Google Chrome

* Website
https://fishingtimeshop.com/

**Describe the bug**
'CMS: Wordpress' is detected, but it is an error due to the fact that there is the Warehouse Theme that brings with it a customized version for Prestashop, of Elementor for advanced editing of CMS pages (and more). It is probably assumed that Elementor only exists for Wordpress ... but there is a version for Prestashop too.

Probably the correct wording should be "CMS: Elementor"

**Comment by kyletaylored** [comment]
Confirmed that Elementor was being detected, and it implied WordPress. Given WordPress has many detections, I went ahead and removed the implied portion because WordPress would likely be detected anyways.
