### ISSUE TITLE
Add TypeDoc and AutoBuy.io

### ISSUE THREAD

**Issue by John4266** [AliasIO/wappalyzer#3698]
Hi. Please add the following:

1. TypeDoc:
Project Site: https://typedoc.org
Project Source: https://github.com/TypeStrong/typedoc
Project Icon: https://typedoc.org/images/logo-32.png
Example Site: https://telegraf.js.org

2. AutoBuy.io
Site: https://autobuy.io

**Comment by nurbek91** [comment]
@John4266 Hey mate . are there any examples link of using Autobuy ??
