### ISSUE TITLE
Possible memory leak?

### ISSUE THREAD

**Issue by rubybb** [AliasIO/wappalyzer#3699]
**Platform**
Which platform does the bug apply to?
* **WebExtension** (**Google Chrome**)

**Describe the bug**

![image](https://user-images.githubusercontent.com/10256477/104065403-eacdf600-51bc-11eb-8c98-c6d17e8e9ec4.png)

**To Reproduce**
1. Use extension.
2. Wait.
3. Memory never goes down, only up.

**Expected behavior**

The extension shouldn't be using so much memory.

**Additional context**

**Comment by AliasIO** [comment]
The extension caches detections for tabs and a number of websites, that might be what you're seeing here. There's an option to purge the cache in the extension settings.

**Comment by rubybb** [comment]
> The extension caches detections for tabs and a number of websites, that might be what you're seeing here. There's an option to purge the cache in the extension settings.

But surely the cache would have a ttl?

**Comment by AliasIO** [comment]
Yes, 24 hours. I'm not seeing runaway memory usage. Are you on the latest version? Where are you seeing those numbers? What settings do you have selected in the extension?

**Comment by rubybb** [comment]
![image](https://user-images.githubusercontent.com/10256477/107729160-4fdda580-6cad-11eb-9d7f-0679180c44c8.png)
I suppose it's not a memory leak, but I think it's still higher than it should be, no?

**Comment by andresespinosapc** [comment]
I also have problems with memory, after a while it goes up to 1.5GB

**Comment by AliasIO** [comment]
@andresespinosapc Does clearing the detection cache in the extension settings bring it back down?

**Comment by AliasIO** [comment]
This is fixed in the next update.
