### ISSUE TITLE
maxWait not working on some subdomain. It freezs

### ISSUE THREAD

**Issue by rubenkharel** [AliasIO/wappalyzer#3700]
**Platform**
Which platform does the bug apply to?
* node??? ig 

**Describe the bug**
Not sure what is causing it to wait too long to respond 
http://dev-app.k8s-demo.esewa.com.np
A subdomain like this is causing wappalizer to stop in the middle.

**To Reproduce**
wappalize on http://dev-app.k8s-demo.esewa.com.np this url

**Expected behavior**
Return the data but waits too long to respond, even max depth cant bypass this issue.

**Comment by AliasIO** [comment]
I tested it and it works correctly. This terminatates immediately:

```
wappalyzer http://dev-app.k8s-demo.esewa.com.np/ --max-wait=1
```

To get all the debug output from Wappalyzer and Puppeteer, you can run:

```
env DEBUG="puppeteer:*" node cli.js http://dev-app.k8s-demo.esewa.com.np/ -d --max-wait=1
```
