### ISSUE TITLE
Wrong link to Shop Pay's website

### ISSUE THREAD

**Issue by Harry-Yep** [AliasIO/wappalyzer#3731]
**Platform**

- Wappalyzer Website

**Describe the bug**

- Wrong link to Shop Pay's website

**To Reproduce**

1. click [https://www.wappalyzer.com/technologies/payment-processors/shop-pay/](https://www.wappalyzer.com/technologies/payment-processors/shop-pay/)
2. You will see it points to [https://pay.google.com/](https://pay.google.com/)

**Expected behaviour**

1. Edit it and direct it to the correct site, the right website is [https://shop.app/](https://shop.app/)

**Comment by kyletaylored** [comment]
It looks like `technologies.json` has the correct URL, so this might just be a website issue.

**Comment by AliasIO** [comment]
Fixed, thanks!
