### ISSUE TITLE
Update dev specification with new properties

### ISSUE THREAD

**Issue by kyletaylored** [AliasIO/wappalyzer#3733]
There have been some additional properties added to the technology spec that could an update for documentation, added to I'm guessing both the site and the contributing guidelines. New properties such as:

```
...
"pricing": [
    "mid",
    "freemium",
    "recurring"
],
"saas": true,
...
```

Looks like pricing does have some predefined attributes:
```
low|mid|high|freemium|poa|payg|onetime|recurring
```

**Comment by AliasIO** [comment]
This is in the README now.
