### ISSUE TITLE
Ability to detect tailwindcss

### ISSUE THREAD

**Issue by Lilkedus** [AliasIO/wappalyzer#3741]
Wappalyzer currently does not detect if a webpage is using tailwindcss. It would be great if it had this feature.

**Comment by nurbek91** [comment]
Hey mate could u send link on which site does the wappalyzer not find ?

**Comment by Lilkedus** [comment]
The following site uses tailwindcss but wappayzer does not detect it.

**Comment by kyletaylored** [comment]
@Lilkedus Please provide a URL.
