### ISSUE TITLE
Batch scanning with wappalyzer

### ISSUE THREAD

**Issue by ahmedsherif** [AliasIO/wappalyzer#3745]
**Wappalyzer CLI is a good tool but unfortunately, it scans only one URL at the time**

I did not understand the argument `  -b, --batch-size=...     Process links in batches`

I thought in the beginning that the CLI can take a file with the list of URLs to scan but this did not work. any ideas?

**Comment by ahmedsherif** [comment]
@kyletaylored

**Comment by ahmedsherif** [comment]
@AliasIO

**Comment by AliasIO** [comment]
When you analyse a website recursively (with `--recursive`), Wappalyzer will follow and process multiple links on the website in batches.

The README has example code for processing multiple websites in parallel using Node.js:

https://github.com/AliasIO/wappalyzer/blob/master/src/drivers/npm/README.md
