### ISSUE TITLE
Format consistency in technologies.json

### ISSUE THREAD

**Issue by bretfourbe** [AliasIO/wappalyzer#3748]
Hi !
I noticed that the following commit https://github.com/AliasIO/wappalyzer/commit/e3bf786826318160f4016b206f5dcd9853c50da0 introduce a new format for a "meta generator" field in technologies.json.
![image](https://user-images.githubusercontent.com/27951656/106782172-23d97900-664a-11eb-9379-f94d64d57608.png)
What I mean is that this kind of field used to be a regex string, but here it is a list.
So what do you think about using something like this instead to be more consistent:
![image](https://user-images.githubusercontent.com/27951656/106782694-c2fe7080-664a-11eb-9616-a8397daad0fa.png)
Thanks in advance.

**Comment by AliasIO** [comment]
All patterns can be either a string or an array of strings. This way a different `confidence` or `version` can be assign to each.

**Comment by bretfourbe** [comment]
Ok I see ! Thank you for your answer, I close the issue.
