### ISSUE TITLE
Technologies not detected when websites have multiple redirects

### ISSUE THREAD

**Issue by infosec-au** [AliasIO/wappalyzer#3763]
**Platform**
Which platform does the bug apply to?
* NPM

**Describe the bug**

When detecting technologies for a website which has multiple URL redirects, the full list of technologies do not get detected.

**To Reproduce**

1. Execute the following:

```
node src/drivers/npm/cli.js https://servicedesk-temp.ivpk.lt -t 1000 -D 10 -m 10 -w 100000 -P
```

Notice that the output contains the following:

```
{
  "urls": {
    "https://servicedesk-temp.ivpk.lt/": {
      "status": 0,
      "error": "net::ERR_ABORTED at https://servicedesk-temp.ivpk.lt/"
    },
    "https://servicedesk-temp.ivpk.lt/jira/servicedesk/": {
      "status": 303
    },
    "https://servicedesk-temp.ivpk.lt/jira/servicedesk/customer/portals": {
      "status": 303
    },
    "https://servicedesk-temp.ivpk.lt/jira/servicedesk/customer/user/login?destination=portals": {
      "status": 200
    }
  },
  "technologies": [
    {
      "slug": "nginx",
      "name": "Nginx",
      "confidence": 100,
      "version": "1.16.1",
      "icon": "Nginx.svg",
      "website": "http://nginx.org/en",
      "cpe": "cpe:/a:nginx:nginx",
      "categories": [
        {
          "id": 22,
          "slug": "web-servers",
          "name": "Web servers"
        },
        {
          "id": 64,
          "slug": "reverse-proxies",
          "name": "Reverse proxies"
        }
      ]
    }
  ]
}
```

**Expected behavior**

Detect the following technologies:

![image](https://user-images.githubusercontent.com/5241936/107453244-bb851d00-6b9e-11eb-9460-bc7037345c7e.png)

**Additional context**

I am trying to build a custom technology detection for Jira Service Desk, however I cannot get it to work because all Jira Service Desk endpoints perform 2 redirects before returning the HTML content we want to match on.

Every Jira Service Desk website I have tried has the same issue where only a subset of technologies are detected, instead of the technologies found in the contents of the final redirect.

**Comment by infosec-au** [comment]
@AliasIO this seems to be an issue with your paid service for technology lookups as well:

![image](https://user-images.githubusercontent.com/5241936/107454525-4ebf5200-6ba1-11eb-820b-3e34a724c822.png)

![image](https://user-images.githubusercontent.com/5241936/107454596-70203e00-6ba1-11eb-9e9d-c1b66f244e36.png)

**Comment by AliasIO** [comment]
The last redirect is `https://servicedesk-temp.ivpk.lt/jira/servicedesk/customer/user/login?destination=portals` where only Nginx is detected. You're probably logged in which explain why you're seeing those technologies?

**Comment by infosec-au** [comment]
Hi @AliasIO, thanks for such a fast response. I am not logged in.

![image](https://user-images.githubusercontent.com/5241936/107470408-7d4c2580-6bbf-11eb-918a-467d80d069a3.png)

The picture above is from an unauthenticated request to `https://servicedesk-temp.ivpk.lt/jira/servicedesk/customer/user/login?destination=portals`

It should be possible to detect the Service Desk version as an unauthenticated user however I cannot get Wappalyzer to detect it. Only the chrome extension detects a lot more technologies (still unauthenticated)

**Comment by AliasIO** [comment]
We're you logged in at some point? The detections are cached. When I view the page unauthenticated I only see Nginx reported in the extension.

**Comment by infosec-au** [comment]
@AliasIO  - No, this is a random host I have picked from the internet. I don't have any credentials for it.

I have tested this again in an incognito tab and here is what I am seeing:

![image](https://user-images.githubusercontent.com/5241936/107471263-fc8e2900-6bc0-11eb-99a9-3bbab7b50c17.png)

**Comment by AliasIO** [comment]
I'm seeing the same thing now. The issue seems to be with the aborted request (`net::ERR_ABORTED`), I get the same error when I request the URL directly. The error is coming from Puppeteer but I'm not sure why this happens.

```
node cli.js "https://servicedesk-temp.ivpk.lt/jira/servicedesk/customer/user/login?destination=portals" -P -d                    
wappalyzer | log | driver | Launching browser...
wappalyzer | log | page | Navigate to https://servicedesk-temp.ivpk.lt/jira/servicedesk/customer/user/login?destination=portals
wappalyzer | error | driver | Error: net::ERR_ABORTED at https://servicedesk-temp.ivpk.lt/jira/servicedesk/customer/user/login?destination=portals
    at Site.goto (/Users/elbert/Sites/wappalyzer/extension/src/drivers/npm/driver.js:764:13)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async Site.analyze (/Users/elbert/Sites/wappalyzer/extension/src/drivers/npm/driver.js:778:21)
    at async /Users/elbert/Sites/wappalyzer/extension/src/drivers/npm/cli.js:87:21
{
  "urls": {
    "https://servicedesk-temp.ivpk.lt/jira/servicedesk/customer/user/login?destination=portals": {
      "status": 0,
      "error": "net::ERR_ABORTED at https://servicedesk-temp.ivpk.lt/jira/servicedesk/customer/user/login?destination=portals"
    }
  },
```

**Comment by infosec-au** [comment]
@AliasIO 

Thanks for investigating further. I am not sure why this occurs either, but I wanted to highlight that it occurs for more than just the single URL I have provided.

I have not been successful with fingerprinting any Jira Service Desk instances. Here is a list you can try:

```
https://servicedesk-temp.ivpk.lt
https://servicedesk.westernnrg.com
https://support.bytesource.net
https://support-staging.barracudafx.com
```

I can provide more examples if you would like, however, these are simply taken from Censys using the following query: https://censys.io/ipv4?q=Jira+Service+Desk

**Comment by AliasIO** [comment]
Thanks, it must be something to do with the server response or JavaScript. I'm not sure what it's doing that Puppeteer doesn't like.
