### ISSUE TITLE
BigCommerce detection not working

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#3789]
**Platform**
Which platform does the bug apply to?
* WebExtension (Google Chrome, Mozilla Firefox)
* NPM
* Bookmarklet
* Website

**Describe the bug**
For some sites, BigCommerce detection is not working.

**To Reproduce**
1. Go to https://www.blackdiamondequipment.com/en_US/shop/built-for-beyond/
2. Check eCommerce section and you will not see 'BigCommerce'

Current detection logic - 
  
"BigCommerce": {
      "cats": [
        6
      ],
      "description": "BigCommerce is a hosted ecommerce platform that allows business owners to set up an online store and sell their products online.",
      "html": "<link href=[^>]+cdn\\d+\\.bigcommerce\\.com/",
      "icon": "BigCommerce.svg",
      "pricing": [
        "low",
        "recurring"
      ],
      "saas": true,
      "scripts": "cdn\\d+\\.bigcommerce\\.com/",
      "url": "mybigcommerce\\.com",
      "website": "http://www.bigcommerce.com"
    },

This site has this CDN when you look at the HTML but it's in an <IMG> tag 

`<img data-src="https://cdn11.bigcommerce.com/s-hgn1l9sh63/images/stencil/550w/attribute_rule_images/8367_source_1613594431.png" src="https://cdn11.bigcommerce.com/s-hgn1l9sh63/images/stencil/550w/attribute_rule_images/8367_source_1613594431.png" alt="Recon Access Mitts" class="fade-image lazy-image img-loaded" style="transition:opacity 0.4s ease-out;" data-v-37e7a394="">
`

**Comment by nurbek91** [comment]
@rockeynebhwani Hey mate , thanks , updated.
