### ISSUE TITLE
New category for Parked Domains

### ISSUE THREAD

**Issue by dan-processbolt** [AliasIO/wappalyzer#3796]
I would like to propose a new category for sites/domains that are parked at services such as GoDaddy.

Here's what I have thus far:
`  "categories": {
    "77": {
      "name": "Parked Domain",
      "priority": 1
    }
  },
  "technologies": {
    "Parked at GoDaddy": {
      "cats": [
        77
      ],
      "description": "GoDaddy is an American domain registrar.",
      "html": "webpackJsonpparking-lander",
      "icon": "godaddy.svg",
      "website": "https://www.godaddy.com/"
    },
    "Parked at Namecheap": {
      "cats": [
        77
      ],
      "description": "Namecheap is an American domain registrar.",
      "html": "Registered at Namecheap\\.com",
      "icon": "namecheap.png",
      "website": "https://www.namecheap.com/"
    },
    "Parked at Hover": {
      "cats": [
        77
      ],
      "description": "Hover is an American/Canadian domain registrar.",
      "html": "https:\\/\\/www\\.hover\\.com\\/\\?source=parked",
      "icon": "hover.png",
      "website": "https://www.hover.com"
    },
    "Parked at Sedo": {
      "cats": [
        77
      ],
      "description": "Sedo (an acronym for Search Engine for Domain Offers and stylised sedo) is a domain name and website marketplace and domain parking provider based in Cambridge, Massachusetts and Cologne, Germany.",
      "html": "Sedo Domain Parking",
      "icon": "sedo_logo.png",
      "website": "https://sedoparking.com/"
    },
    "Parked at Arsys": {
      "cats": [
        77
      ],
      "description": "Arsys is a Spanish domain registrar.",
      "html": "https:\\/\\/arsys\\.es\\/css\\/parking2\\.css",
      "icon": "arsys.png",
      "website": "https://www.arsys.es"
    },
    "Parked at MarkMonitor": {
      "cats": [
        77
      ],
      "description": "MarkMonitor develops software intended to protect corporate brands from Internet counterfeiting, fraud, piracy, and cybersquatting.",
      "html": "by MarkMonitor",
      "icon": "markmonitor.png",
      "website": "https://markmonitor.com/"
    }
  }
`

**Comment by AliasIO** [comment]
Happy to add this. Let's name the category 'Domain parking'.

Please use `dom` instead of `html` (see the [README](https://github.com/AliasIO/wappalyzer/blob/master/README.md)).

Do you want to submit a pull request for this?

**Comment by dan-processbolt** [comment]
I can create a pull request once I figure out how to re-write the stuff using dom instead of html for the identifiers........

**Comment by AliasIO** [comment]
If you can share some URLs of parked domains I can have a look and give you some examples. It's important to not match regular content, e.g. the string "GoDaddy is an American domain registrar" appears on a lot of websites that aren't parked domains.

**Comment by dan-processbolt** [comment]
OK, here are some examples:

GoDaddy:
http://2-three.com/

Arsys:
http://naellemoi.com/

Hover:
http://adoptadoor.com/

**Comment by AliasIO** [comment]
Thanks! The Hover one doesn't load for me but these should work:

GoDaddy:
```
"dom": {
  "#domainInfois": {
    "text": "is available on GoDaddy Auctions"
  }
},
"scripts": "wsimg\\.com/parking-lander"
```

Arsys:
```
"dom": {
  "link[rel='stylesheet'][href*='arsys.es/css/parking2.css']": {
    "attributes": {
      "href": ""
    }
  }
}
```
