### ISSUE TITLE
Bookmenow as an Appointment Solution

### ISSUE THREAD

**Issue by vfcampo** [AliasIO/wappalyzer#3810]
You may request a new technology to be added but changes of having it included are greatly improved if you submit a pull request. Please refer to the [documentation](https://docs.wappalyzer.com/dev/contributing.html#adding-a-new-application).
Category: /appointment-scheduling/
Name: Meeting Scheduler view: https://bookmenow.info/
Url patttern: https://bookmenow.info/book/*
Examples: 
- https://www.vendasta.com/
- https://bullseyedigital.agency/
- ![image](https://user-images.githubusercontent.com/55451462/109850251-e865a680-7c17-11eb-9c42-f4bec7cb583a.png)
Logo: 
- ![image](https://user-images.githubusercontent.com/55451462/109850757-780b5500-7c18-11eb-8e6c-0c5150319764.png)

**Comment by nurbek91** [comment]
Hey @AliasIO . Can I identify from the link that this website is using this widget.
If I understand, bookmenow only provides an embeddable link and the widget itself will always open after clicking on this link
Example:
https://bullseyedigital.agency/
https://bookmenow.info/book/timpringle/45-minutes

**Comment by AliasIO** [comment]
@nurbek91 Yes, that's fine in this case. 👌
