### ISSUE TITLE
[Docs Tool] Add mdBook Detection

### ISSUE THREAD

**Issue by John4266** [AliasIO/wappalyzer#3813]
Hello.
I would like to suggest you to detect the following Docs tool:
Name: mdBook
Source: https://github.com/rust-lang/mdBook
Example Site: https://x.synapse.to/docs/

**Comment by nurbek91** [comment]
@John4266 Hey mate  Unfortunately in example, I do not see any patterns by which we could define this technology.

**Comment by John4266** [comment]
hey @nurbek91
could you check again with the following examples?
https://x.synapse.to/docs/
https://telegrambots.github.io/book/index.html
https://doc.rust-lang.org/book/title-page.html

they all share the same script:

```
<script type="text/javascript">
            try {
                var theme = localStorage.getItem('mdbook-theme');
                var sidebar = localStorage.getItem('mdbook-sidebar');

                if (theme.startsWith('"') && theme.endsWith('"')) {
                    localStorage.setItem('mdbook-theme', theme.slice(1, theme.length - 1));
                }

                if (sidebar.startsWith('"') && sidebar.endsWith('"')) {
                    localStorage.setItem('mdbook-sidebar', sidebar.slice(1, sidebar.length - 1));
                }
            } catch (e) { }
        </script>
```

**Comment by nurbek91** [comment]
Hey @John4266, added thanks!
