### ISSUE TITLE
technologies.json see a bug

### ISSUE THREAD

**Issue by LztCode** [AliasIO/wappalyzer#3818]
**Platform**
Which platform does the bug apply to?
* Python

**Describe the bug**
this technologies.json There is a bug in the file. There is a problem with meta > generator. There is a list in the generator rule, but the generator field is basically a string. It is often wrong to call Python library to parse this file. I hope it can be improved

**To Reproduce**
1. Go to 'src/technologies.json'
2. Open it 
3. Scroll down to 'generator'
4. See some strings hava a list

**Expected behavior**
debug it

**Additional context**
  "AWStats": {
      "cats": [
        10
      ],
      "cpe": "cpe:/a:laurent_destailleur:awstats",
      "icon": "AWStats.png",
      "implies": "Perl",
      "meta": {
        "generator": "AWStats ([\\d.]+(?: \\(build [\\d.]+\\))?)\\;version:\\1"
      },
      "website": "http://awstats.sourceforge.net"
    },
    "Abicart": {
      "cats": [
        6
      ],
      "description": "Abicart is an ecommerce platform developed by the Swedish company Abicart AB.",
      "icon": "abicart.png",
      "meta": {
        "generator": [
          "Abicart",
          "Textalk Webshop"
        ]
      },
      "pricing": [
        "mid",
        "recurring"
      ],
      "saas": true,
      "website": "https://abicart.com/"
    },
    "AccessTrade": {
      "cats": [
        71
      ],
      "description": "AccessTrade is an affiliate marketing platform based on the CPA model developed by Interspace Co.",
      "dom": {
        "img[src*='.accesstrade.net'],img[data-src*='.accesstrade.net']": {
          "attributes": {
            "src": ""
          }
        }
      },
      "icon": "AccessTrade.png",
      "website": "https://www.accesstrade.ne.jp"
    },

**Comment by AliasIO** [comment]
Any pattern can be either a string or an array, so the formatting is correct. This issue would have to fixed in the library you're using.

**Comment by LztCode** [comment]
> Any pattern can be either a string or an array, so the formatting is correct. This issue would have to fixed in the library you're using.

However, some Python libraries, such as whatcms and webtech, rely on technology. JSON, and this feature will not be available. It's very difficult to fix so many Python  libraries, and some libraries are no longer maintained.

**Comment by AliasIO** [comment]
I recommend installing Wappalyzer through NPM and calling that from your Python script. The library you're using probably doesn't support the `dom` and `js` methods either.
