### ISSUE TITLE
Paypal express for woocommerce  websites

### ISSUE THREAD

**Issue by vfcampo** [AliasIO/wappalyzer#3829]
Please take a look at this website for example https://celticlife.com/

![image](https://user-images.githubusercontent.com/55451462/110846514-77566c80-8271-11eb-92a4-f9f51c181f27.png)
and this is the breadcrumb on the landing page
![image](https://user-images.githubusercontent.com/55451462/110846747-c1d7e900-8271-11eb-94b0-b1b0d73c3109.png)

This would be the checkout page and its references  (https://celticlife.com/checkout/)
![image](https://user-images.githubusercontent.com/55451462/110846276-38c0b200-8271-11eb-8577-5cb51034d0bd.png)

![image](https://user-images.githubusercontent.com/55451462/110846379-53932680-8271-11eb-92d8-c60cd2ab9b4e.png)

**Comment by AliasIO** [comment]
Done!
