### ISSUE TITLE
WebExt causes anchor link jumps to wrong position

### ISSUE THREAD

**Issue by fireattack** [AliasIO/wappalyzer#3831]
**Platform**
Which platform does the bug apply to?
* WebExtension (Google Chrome, Mozilla Firefox)

**Describe the bug**

When the WebExt is installed on browser, it affects some webpages and makes anchor links jump to wrong position.

**To Reproduce**

1. Install the webext (I tested on Chrome and Firefox)
2. Open https://github.com/rubygems/rubygems/pull/1191#issuecomment-84066938 , or any github link that is with an anchor.

**Expected behavior**

The page should be displayed with the highlighted comment aligned with the top hover bar:

![image](https://user-images.githubusercontent.com/4130991/110947118-5e979680-8305-11eb-8a0f-c7adc54a965b.png)

However, when wappalyzer webext is installed, the alignment is wrong:

![image](https://user-images.githubusercontent.com/4130991/110947221-8129af80-8305-11eb-8a74-b701f5c03249.png)

**Comment by fireattack** [comment]
Also, even if you "disable on this website" for GitHub, this bug still happens.

**Comment by AbhinavS96** [comment]
Seems like this issue was introduced in the latest update.

**Comment by fireattack** [comment]
This bug still exists.
