### ISSUE TITLE
Error: The object could not be cloned.

### ISSUE THREAD

**Issue by indaviande** [AliasIO/wappalyzer#3854]
**Platform**
Mac OS 11.2.3 (20D91)
Firefox Developer Edition 88.0b2 (64 bits)

**Describe the bug**
When opening the console the message "Error: The object could not be cloned." is appaearing linked to content.js.
I was able to identify Wappalyzer as the root cause when disabling/enabling each extension.

**To Reproduce**
1. Go to anny website with Wappalyzer activated
2. Check console & see the error.

**Comment by AliasIO** [comment]
Are you still seeing this behaviour? I never encountered it, perhaps it related to Firefox Developer Edition?

**Comment by indaviande** [comment]
No, i'm not seeing it anymore (on Firefox DE).

**Comment by AliasIO** [comment]
Thank you, I'll close this one then.
