### ISSUE TITLE
Eliminate noises by utilizing release histories

### ISSUE THREAD

**Issue by nrllh** [AliasIO/wappalyzer#3859]
Hi,

For [one of our studies](https://twitter.com/nrllah/status/1365266925266337795), we collected about 34k release histories manually and from GitHub repos. The goal was to drop noises delivered by Wappalyzer (of course these come from websites).
Is that something you can integrate into Wappalyzer to check if websites deliver the wrong version or not? If it's the case I can share our dataset: 

- release channel of 250 software products, these are mostly GitHub repos but it also contains rules to find the right product in GitHub tags.
- release history (34k) for about 250 software products (until 07.2020)

**Comment by AliasIO** [comment]
I'm not sure if I'm understanding you correctly. Do you mean Wappalyzer picks up on incorrect version numbers in certain cases?

**Comment by nrllh** [comment]
Wappalyzer pics up the version information in the right way, but there are too many websites that provide fake or dummy version information.

**Comment by AliasIO** [comment]
Thanks, that's interesting. I'm not sure how I'd use the dataset to fix this.

**Comment by AliasIO** [comment]
Thanks, that's interesting. I'm not sure how I'd use the dataset to fix this.

**Comment by nrllh** [comment]
We alredy did it in our study. I'll share our dataset. You can then use it. I'll let you know, when it's published.

**Comment by AliasIO** [comment]
I look forward to it. :)
