### ISSUE TITLE
Add "Elastic APM" to Analytics

### ISSUE THREAD

**Issue by xfoucron** [AliasIO/wappalyzer#3864]
Docs: https://www.elastic.co/guide/en/apm/agent/rum-js/current/index.html
GH Repo: https://github.com/elastic/apm-agent-rum-js

**Comment by xfoucron** [comment]
PR: #3865

**Comment by rockeynebhwani** [comment]
@AliasIO @xfoucron - Can we close this as this has been taken care in https://github.com/AliasIO/wappalyzer/pull/4162 ?
