### ISSUE TITLE
Cloudflare detection not working

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#3883]
**Platform**
Which platform does the bug apply to?
 WebExtension (Google Chrome)

**Describe the bug**
I am not seeing the CDN detection working on this site - https://direct.asda.com/george/clothing/10,default,sc.html

Site has cookie __cfduid and it has following headers -
cf-cache-status: DYNAMIC
cf-ray: 6410c7fabbdedc23-LHR
server: cloudflare

Detection logic currently in technologies.json is

    "Cloudflare": {
      "cats": [
        31
      ],
      "cookies": {
        "__cfduid": ""
      },
      "description": "Cloudflare is a web-infrastructure and website-security company, providing content-delivery-network services, DDoS mitigation, Internet security, and distributed domain-name-server services.",
      "headers": {
        "Server": "^cloudflare$",
        "cf-cache-status": "",
        "cf-ray": ""
      },
      "icon": "CloudFlare.svg",
      "js": {
        "CloudFlare": ""
      },
      "website": "http://www.cloudflare.com"
    },

**Comment by jakejarvis** [comment]
Cloudflare [announced they're deprecating `__cfduid`](https://blog.cloudflare.com/deprecating-cfduid-cookie/) next month... but maybe they are turning it off on some bigger sites earlier, or running some tests? That's the only thing I can think of right now.

Either way, as a heads up to whoever can remember, the `__cfduid` cookie will need to be removed from that list of fingerprints on/around May 10th. 😉

**Comment by AliasIO** [comment]
@rockeynebhwani Are you still having this issue? It's picking up Cloudflare for me.

**Comment by rockeynebhwani** [comment]
@AliasIO - Still not working for me. I have latest version of chrome extension and this is what I see

![image](https://user-images.githubusercontent.com/1718757/115855867-ab51af80-a423-11eb-8f55-edd9024026b7.png)

**Comment by AliasIO** [comment]
@rockeynebhwani Does a hard refresh of the page (Cmd+Shift+R) fix it? It looks like response headers are not received when a page is served from the browser cache ([`chrome.webRequest.onCompleted`](https://github.com/AliasIO/wappalyzer/blob/master/src/drivers/webextension/js/driver.js#L65) doesn't fire).

**Comment by rockeynebhwani** [comment]
Yes.. it works if I completely clear cookies and site data..

**Comment by AliasIO** [comment]
Right, I don't think we can change that. It will work on your first visit and the result will be cached for some time. After that it won't show until the browser cache expires.
