### ISSUE TITLE
Error: Could not find browser revision 818858. Run "PUPPETEER_PRODUCT=firefox npm install" or "PUPPETEER_PRODUCT=firefox yarn install" to download a supported Firefox browser binary.

### ISSUE THREAD

**Issue by rubenkharel** [AliasIO/wappalyzer#3924]
**Platform**
Which platform does the bug apply to?
* Nodejs Staging
* Ubuntu 20

**Describe the bug**
Wappalizer not able to launch the browser even though I have the following env variables set.
`PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium`
`PUPPETEER_PRODUCT=/usr/bin/firefox`
`CHROMIUM_BIN=/usr/bin/firefox` 😅

I tried changing the puppeteer version and directly assigning the chromium/firefox path to Wappalyzer's `driver.js`. 
What could cause this issue?

**Comment by AliasIO** [comment]
Try running Puppeteer in debug mode:

```
DEBUG="puppeteer:*" node src/drivers/npm/cli.js https://example.com
```
