### ISSUE TITLE
eclass (broadlearning)

### ISSUE THREAD

**Issue by c2xusnpq6** [AliasIO/wappalyzer#3926]
```
eclass.com.hk
eclass.hk ?
eclasscloud.hk
broadlearning.com
broadlearning.net
```

keywords:
`eClass Integrated Platform`
`server: eclass`
`eclasscloud.hk`

**Comment by c2xusnpq6** [comment]
```
BroadLearning Education (Asia) Limited. All rights reserved.
BroadLearning Education (Asia) Limited
{website_domain}/templates/
{website_domain}/ver.php ---> ej.*** or ip.***
```

**Comment by c2xusnpq6** [comment]
https://search.censys.io/search?resource=hosts&q=services.http.response.headers.server%3A+%22eClass%22+or+%22eClass+Integrated+Platform%22+or+%22BroadLearning+Education+%28Asia%29+Limited%22+or+%22eclasscloud.hk%22

https://search.censys.io/search?resource=hosts&q=%22eclass.com.hk%22+or+%22eclass.hk%22+or+%22broadlearning.com%22+or+%22broadlearning.net%22

**Comment by AliasIO** [comment]
Merged, thanks!
