### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by tuxayo** [AliasIO/wappalyzer#3953]
**Platform**
Which platform does the bug apply to?
* WebExtension (Mozilla Firefox)
* Website: example.org

**To Reproduce**
I doubt that it always happen, I noted a high CPU usage just now so I'm keeping my session open in case there is info I can provide before closing and maybe loosing the bug instance.

1. Go to https://example.org
2. F5
3. some process manager
4. See that web extentions process have a spike to 100% of one thread when the page is refreched
5. disable and enable wappalyzer to confirm it's the source of this CPU usage

**Additional context**
might be linked #2979 #2605
I hesitated to post there but it's only about Chrome, I my case it's Firefox dev edition 89.0b12

**Comment by AliasIO** [comment]
I made the analysis asynchronous to hopefully prevent it from hogging CPU (90f981000b70f7e02ae8168f360a797c9376621c).

**Comment by tuxayo** [comment]
Thanks :D

Version 6.7.0, can still reproduce

**Comment by AliasIO** [comment]
Wappalyzer works by evaluating hundreds to thousands of regular expressions on every page. A short spike in CPU usage might not be so bad, as long as it doesn't lock the browser. I'm not seeing CPU usage go that high on my machine, though.

**Comment by AliasIO** [comment]
Let me know if you're still seeing this in v6.7.4.
