### ISSUE TITLE
Invalid character in src/technologies.json

### ISSUE THREAD

**Issue by codypierce** [AliasIO/wappalyzer#3955]
**Platform**
Which platform does the bug apply to?
* WebExtension (Google Chrome, Mozilla Firefox)
* NPM
* Bookmarklet
* Website

**Describe the bug**
There is an invalid char in technologies.json at line 15699. Github action failed https://github.com/AliasIO/wappalyzer/commit/1e14d22647c9550e57443f3356dd54b1505e988d#diff-ad6b5aefcc8c0ba3d7c9f4c9ba096652f7bae1235363a40bba4759f3abb374c4

**To Reproduce**
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**
Loading technologies.json should not fail

**Additional context**

**Comment by codypierce** [comment]
Pending merge request fixes this. https://github.com/AliasIO/wappalyzer/pull/3954/commits/c9a8076f473de6bd8907a564bcb95bda5ce5856f

**Comment by AliasIO** [comment]
Merged!
