### ISSUE TITLE
Identifies only a few number of technologies

### ISSUE THREAD

**Issue by basnetsoyuj** [AliasIO/wappalyzer#3956]
**Platform**
Which platform does the bug apply to?
* NPM (wappalyzer-core)

**Describe the bug**
Returns only a few technologies.

**To Reproduce**
These are the arguments that I passed to `Wappalyzer.analyze()`:
https://gist.github.com/basnetsoyuj/192e4f9c656673df79e37458aa48cdce

>**Note**: Arguments have been passed in this format:
![image](https://user-images.githubusercontent.com/18349557/118715680-a2e26e00-b843-11eb-9d9c-d62bb83b6bd6.png)

**Expected behavior**
More technologies similar to what we get at https://www.wappalyzer.com/lookup/fashionnova.com
![image](https://user-images.githubusercontent.com/18349557/118713659-edfb8180-b841-11eb-8bc2-d5845fd43970.png)

However, got only 5. Here are the results: https://gist.github.com/basnetsoyuj/6261f974d5ce4284b216ab1f0e981f57

**Additional context**

Some might not have been identified because fashionnova.com loads some of the script tags asynchronously, so they were not present in the `scripts` argument.

But,

For example, 

* `cloudflare` that was present in the headers wasn't discovered
![image](https://user-images.githubusercontent.com/18349557/118715470-5ac34b80-b843-11eb-823f-436bec54cea6.png)

* `Boomerang` is not identified even though it is in the HTML.
![image](https://user-images.githubusercontent.com/18349557/118714458-4fbbeb80-b842-11eb-8181-7782d5899587.png)
![image](https://user-images.githubusercontent.com/18349557/118714724-724e0480-b842-11eb-851c-0d9a04be7007.png)

> Does `wappalyzer-core` not parse `js` property and variables from the HTML itself? Can we pass it separately? What about `dom`?

**Comment by AliasIO** [comment]
Without a browser environment the results are limited as `js` and `dom` both don't work. `headers` should work, make sure  each header value is passed in as an array.

If you have a list of matching JavaScript variables (`js`) and query selectors (`dom`), you can pass them in separately by calling `Wappalyzer.analyzeOneToMany()`:

https://github.com/AliasIO/wappalyzer/blob/master/src/wappalyzer.js#L428

You can see an example of this in the NPM driver:

https://github.com/AliasIO/wappalyzer/blob/master/src/drivers/npm/driver.js#L56

And here's how the WebExtension driver does it:

https://github.com/AliasIO/wappalyzer/blob/master/src/drivers/webextension/js/content.js#L179
https://github.com/AliasIO/wappalyzer/blob/master/src/drivers/webextension/js/inject.js
