### ISSUE TITLE
jQuery detects wrong version number

### ISSUE THREAD

**Issue by qfayet** [AliasIO/wappalyzer#3957]
**Platform**
Which platform does the bug apply to?
* WebExtension (Google Chrome, Mozilla Firefox)
* NPM

**Describe the bug**
On the site https://almond.consulting/, the version of jQuery is wrong.
In fact, it is corresponding to the version of jQuery UI.

**To Reproduce**
1. Go to 'https://almond.consulting/'
2. Click on 'Wappalyzer extension'
3. Scroll down to 'jQuery'
4. The version of jQuery is wrong (it should be: 3.5.1)

![image](https://user-images.githubusercontent.com/48323709/118745635-e2668580-b856-11eb-9b03-aeaf23c1c208.png)

**Expected behavior**
The version of jQuery should be: 3.5.1 (due to `.../wp-includes/js/jquery/jquery.min.js?ver=3.5.1`).

**Additional context**
The problem is that one of the regex to determine jQuery is too permissive : `jquery.*\.js(?:\?ver(?:sion)?=([\d.]+))?`
It match with: `.../wp-includes/js/jquery/ui/core.min.js?ver=1.12.1`
Maybe, it should use: `jquery[^/]*...` ?

**Comment by AliasIO** [comment]
This will be fixed in the next update, thanks!

**Comment by qfayet** [comment]
Great! Thanks to you!
