### ISSUE TITLE
Add `SvelteKit` (a framework for Svelte)

### ISSUE THREAD

**Issue by Zerotask** [AliasIO/wappalyzer#3962]
[My project](https://github.com/Zerotask/rust-jungle) is using Svelte (which is more like a compiler) and the actual Svelte framework called **SvelteKit**. On the website I just see Svelte (listed as framework), but it should also show me SvelteKit.

SvelteKit is kinda like next.js but for Svelte.

Website: https://kit.svelte.dev
Repository: https://github.com/sveltejs/kit
My hosted project as reference: https://rust-jungle.vercel.app/

**Comment by nurbek91** [comment]
Hey mate . Could you help me . What traces(fingerprints) can be used to identify this technology

**Comment by Zerotask** [comment]
@nurbek91 At the moment you can lookout for `sveltekit:prefetch`

Example from my homepage:
```html
<li class="svelte-k5k7in"><a sveltekit:prefetch href="/en" class="svelte-k5k7in">Home</a></li>
```

**Comment by nurbek91** [comment]
Hey mate @Zerotask  I want to add technology but can't find good examples for that. Could you send some links where this technology is used additional to https://rust-jungle.vercel.app .

**Comment by Zerotask** [comment]
- https://www.gitpod.io
- https://mk48.io
- https://gianmarco.xyz
