### ISSUE TITLE
Top-Right technology's name is not shown on many sites.

### ISSUE THREAD

**Issue by John4266** [AliasIO/wappalyzer#3966]
**Platform**
Which platform does the bug apply to?
* Web Extension (Version: 6.7.0)
* Firefox Beta (Version: 89.0b15 (64-bit))

**Describe the bug**
On most sites that i visit, the Top-Right technology's name is not shown.

**To Reproduce**

https://www.prepaiddigitalsolutions.com/
https://www.programmableweb.com/

1. Go to any of this sites.
2. Click on the Wappalyzer extension.
3. Look at the Top-Right technology.

**Expected behavior**
The technology name should be shown as usual.

**Additional context**
Pictures:
![1](https://i.imgur.com/J6H6hXg.png)
![2](https://i.imgur.com/TXxP5Wv.png)

**Comment by AliasIO** [comment]
Thanks, this is fixed in the upcoming update.
