### ISSUE TITLE
Cache pollution with sites using reverse proxy vs hostnames

### ISSUE THREAD

**Issue by kyletaylored** [AliasIO/wappalyzer#3969]
**Platform**
Which platform does the bug apply to?
* WebExtension (Google Chrome, Mozilla Firefox)

**Describe the bug**
There is an issue related to sites that are running reverse proxies, which maps paths to different origins or applications. For example:
* example.com -> NodeJS / Express site hosted on AWS
* example.com/fr-ca -> Drupal CMS site hosted on GCP
* example.com/blog -> WordPress CMS on Kinsta

The issue comes in when the cache combines all these sites technologies together, but it doesn't make sense what each proxied site is actually running.

**To Reproduce**
1. Clear extension cache
1. Go to https://www.acronis.com/en-us, see that the site is running no CMS
1. Go to https://www.acronis.com/fr-ca, see the site is running Drupal
1. Notice the popup lists technologies for both sites, despite being separate applications

**Expected behavior**
Either technologies should be isolated per path, or isolate grouped cached data by hostname.

**Additional context**
#3290 may be solved in this solution as well.

**Comment by AliasIO** [comment]
Added an option to hide cached detections in the results.

**Comment by kyletaylored** [comment]
Seems to work as expected when checked. Thanks!
