### ISSUE TITLE
Statamic

### ISSUE THREAD

**Issue by MavropaliasG** [AliasIO/wappalyzer#3971]
https://statamic.com/vs/wordpress

**Comment by nurbek91** [comment]
Hey @MavropaliasG   . I want to add technology but can't find good examples for that. Could you send some links where this technology is used

**Comment by MavropaliasG** [comment]
> Hey @MavropaliasG . I want to add technology but can't find good examples for that. Could you send some links where this technology is used

I am not affiliated with them, I just stumbled upon this CMS. Here's some examples https://builtwithstatamic.com/

**Comment by AliasIO** [comment]
Added, thanks!
