### ISSUE TITLE
Incorrect WordPress version detection from scripts

### ISSUE THREAD

**Issue by gpoetzelsberger** [AliasIO/wappalyzer#3974]
Version from scripts like

`wp-emoji-release.min.js?ver=123a8470218a212658684fa75e488c59 `

will be detected as WordPress version 123. 

example site: https://www.sportfamilie.at/

**Comment by AliasIO** [comment]
Fixed in 65c830a70dbc9ac190b7d81283f986d9f6b3b1c0, thanks!
