### ISSUE TITLE
Shopify detection not working for some high profile sites

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#3983]
Recently some high profile sites built on Shopify listed publicly but these site are not being detected being on Shopify by Wappalyzer

Sites in question - 
https://www.wearfigs.com/
https://www.oatly.com/

Current detection for Shopify is as below. Can we please check how we can improve this to increase coverage for Shopify?

    "Shopify": {
      "cats": [
        6
      ],
      "description": "Shopify is a subscription-based software that allows anyone to set up an online store and sell their products. Shopify store owners can also sell in physical locations using Shopify POS, a point-of-sale app and accompanying hardware.",
      "headers": {
        "x-shopid": "\\;confidence:50",
        "x-shopify-stage": "\\;confidence:50"
      },
      "html": "<link[^>]+=['\"]//cdn\\.shopify\\.com\\;confidence:25",
      "icon": "Shopify.svg",
      "js": {
        "Shopify": "\\;confidence:25",
        "ShopifyAPI": ""
      },
      "pricing": [
        "low",
        "recurring"
      ],
      "saas": true,
      "scripts": "sdks\\.shopifycdn\\.com",
      "url": "^https?//.+\\.myshopify\\.com",
      "website": "http://shopify.com"
    },

**Comment by rockeynebhwani** [comment]
BuiltWith detect Shopify correctly on both of these domains 
https://builtwith.com/wearfigs.com
https://builtwith.com/www.oatly.com

In fact, BuiltWith is able to detect these sites correctly as being on 'Shopify Plus'. It will be great if we can have two different detection for 'Shopify' and 'Shopify Plus'

**Comment by rockeynebhwani** [comment]
I see cookie '_shopify_s' on Shopify sites..  Can we check for this cookie? This will detect wearfigs.com correctly as Shopify site. I am not seeing this cookie on www.oatly.com

**Comment by AliasIO** [comment]
Merged, thank you.
