### ISSUE TITLE
Improve Wix detection to differentiate between Wix CMS and Wix Commerce

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#3984]
Last time Wix detection was updated in June-2019 by @DanShappir (https://github.com/AliasIO/wappalyzer/pull/2731/commits/f44f20f03618f6a5fd868dd38ce9db5e2e2f1407) and it seems things have moved on since then. Also, in last year's Web Almanac, we found it difficult to compare Wix with other eCommerce platform as Wix gets mapped to two categories (CMS and eCommerce)

Current detection is - 
   
 "Wix": {
      "cats": [
        1,
        6,
        11
      ],
      "cookies": {
        "Domain": "\\.wix\\.com"
      },
      "description": "Wix provides cloud-based web development services, allowing users to create HTML5 websites and mobile sites.",
      "headers": {
        "X-Wix-Renderer-Server": "",
        "X-Wix-Request-Id": "",
        "X-Wix-Server-Artifact-Id": ""
      },
      "icon": "Wix.svg",
      "implies": "React",
      "js": {
        "wixBiSession": ""
      },
      "meta": {
        "generator": "Wix\\.com Website Builder"
      },
      "pricing": [
        "low",
        "recurring"
      ],
      "saas": true,
      "scripts": "static\\.parastorage\\.com",
      "website": "https://www.wix.com"
    },

I have been chatting with @DanShappir on Twitter and I suggest following changes -

1) Currently test includes check for "wixBiSession": "". (As a fallback for "generator").  As per @DanShappir, This test is no longer valid for most Wix sites. If you still want a JS based fallback then check for "wixPerformanceMeasurements" instead. This is an object that is created on window during page load.

2) We should split it into two entries 'Wix CMS' / 'Wix Commerce'. As per @DanShappir, there is no "standard" method to identify eCommerce Wix sites. It's simply a question of which scripts are loaded into the page. He is able to provide a URL segment which we can use to identify eCommerce scripts, but there is no guarantee that these won't change in the future but we can adjust in future again if required.

Tagging @bobbyshaw and @rrajiv who are taking lead on Web Almanac 2021 for eCommerce chapter

**Comment by AliasIO** [comment]
Happy to split the two. I added the `wixPerformanceMeasurements` check for now.

**Comment by rockeynebhwani** [comment]
Thanks @AliasIO . Will wait for @DanShappir to provide URL pattern to detect eCommerce sites before we close this.

**Comment by DanShappir** [comment]
For identifying Wix sites, the generator is still the best and most reliable method.
Anything else should be used as a fallback.

Unfortunately we do not provide a generic marker to identify Wix sites that also have eCommerce functionality.
The best you can do is check whether a specific page downloads eCommerce related functionality.
Such functionality is downloaded from URLs that contain the substring "wixstores", such as:
`https://static.parastorage.com/services/wixstores-client-cart-icon/1.924.0/cartIconNoCss.bundle.min.js`
I hope this is something you can use.

**Comment by rockeynebhwani** [comment]
> Happy to split the two. I added the `wixPerformanceMeasurements` check for now.

@AliasIO  - Did you do a commit for this.  I can't find any references of `wixPerformanceMeasurements` in technologies.json

**Comment by AliasIO** [comment]
Added in b615607866b80c47261a0e3b7ae01a66ddfb1cf2. I'm looking for `wixstores` in `script#wix-viewer-model`, which works on the example.
