### ISSUE TITLE
Improve BigCommerce detection

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#3986]
Some of the BigCommerce based sites are not detecting BigCommerce. 

Example - https://yeticycles.com/

BuiltWith is able to detect this which means there is something we should be able to add. I don't know what needs to be added but creating this issue in case somebody knows - https://builtwith.com/yeticycles.com

Current BigCommerce detection - 

    "BigCommerce": {
      "cats": [
        6
      ],
      "description": "BigCommerce is a hosted ecommerce platform that allows business owners to set up an online store and sell their products online.",
      "dom": "img[data-src*='.bigcommerce.com'], img[src*='.bigcommerce.com']",
      "html": "<link href=[^>]+cdn\\d+\\.bigcommerce\\.com/",
      "icon": "BigCommerce.svg",
      "pricing": [
        "low",
        "recurring"
      ],
      "saas": true,
      "scripts": "cdn\\d+\\.bigcommerce\\.com/",
      "url": "mybigcommerce\\.com",
      "website": "http://www.bigcommerce.com"
    },

**Comment by AliasIO** [comment]
It works on product pages. The homepage appears to be powered by Prismic CMS.
