### ISSUE TITLE
Add SpeedCurve Lux RUM Solution

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#3991]
SpeedCurve provides a RUM (Real User Monitoring solution but currently we don't have detection for SpeedCurve

Example Site - https://www.everlane.com/
Pattern to look for - https://cdn.speedcurve.com/js/lux.js
Vendor site - https://www.speedcurve.com/features/lux/

**Comment by AliasIO** [comment]
Merged.
