### ISSUE TITLE
AfterPay detection not working

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#3993]
**Example site** - https://www.urbanoutfitters.com/shop/uo-kendra-linen-button-front-romper?color=030&type=REGULAR&quantity=1

**Current detection** - 

    "Afterpay": {
      "cats": [
        41
      ],
      "cpe": "cpe:/a:afterpay:afterpay",
      "description": "Afterpay is a 'buy now, pay later' platform that makes it possible to pay off purchased goods in fortnightly instalments.",
      "icon": "afterpay.png",
      "js": {
        "Afterpay": "",
        "afterpay_product": ""
      },
      "saas": true,
      "scripts": [
        "portal\\.afterpay\\.com",
        "static\\.afterpay\\.com"
      ],
      "website": "https://www.afterpay.com/"
    },

Should we add detection for something like aria-label="Afterpay"?

**Comment by AliasIO** [comment]
Updated, thanks!
