### ISSUE TITLE
Add new category for RUM solutions

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#3997]
@AliasIO - As part of Web Almanac project, we would like to report on adoption of various 'RUM (Real User Monitoring)' Tools but currently, there is no such category in Wappalyzer. We see some tools listed (e.g. Akamai mPulse) but that's categorised under category 10 (Analytics) and 47 (Development). I don't even know what else falls under category 47.

Will you be OK if we added a new category for RUM? We have lot of expert insights on detecting RUM solutions (it's listed on this thread - https://discuss.httparchive.org/t/who-are-the-top-rum-analytics-providers/15/11)

If you are in agreement, we can create a simple table with all providers and associated patterns so that those can be added to Wappalyzer.

Let me know.

**Comment by AliasIO** [comment]
Yes, sounds good.

**Comment by nurbek91** [comment]
Hey guys , i would rename category APM & RUM
But so far created  a RUM  category and added several new technologies and updated old technologies that are suitable for this category.

**Comment by rockeynebhwani** [comment]
Thanks @nurbek91. Categorisation for 'Akamai mPulse' can also be updated to reflect this category instead of categories 10 and 47.

**Comment by nurbek91** [comment]
Hey @rockeynebhwani , 
Akamai mPulse,
AppDynamics,
Boomerang,
Cloudflare Browser Insights,
Instana,
New Relic 
These technologies now also fall into this category now

**Comment by rockeynebhwani** [comment]
Thanks @nurbek91
