### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: The website took too long to respon

### ISSUE THREAD

**Issue by mandricmihai** [AliasIO/wappalyzer#4003]
**Platform**
Which platform does the bug apply to?
NPM version 6.7.4
I run from the cli, node js version 14.17.0

**Describe the bug**
When ran from the cli I get this errors logs and the process hangs.

(node:172) UnhandledPromiseRejectionWarning: Error: The website took too long to respond
--
at Timeout.&lt;anonymous&gt; (/var/task/nodejs/node_modules/wappalyzer/driver.js:312:18)
at listOnTimeout (internal/timers.js:555:17)
at processTimers (internal/timers.js:498:7)
 (Use `node --trace-warnings ...` to show where the warning was created)
(node:172) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
&nbsp; | 2021-06-08T17:41:19.686+03:00 | (node:172) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a

**To Reproduce**
Run from the cli, I', the code is like this:

```
await Promise.all([
				process_wappalyzer(result[0], wappalyzer),
                                process_wappalyzer(result[1], wappalyzer),
			])
```
process_wappalyzer has a try catch, that contains all the code, I was expecting this error to be catch by this try catch block, I think it propages to Promise.all(). Promise.all() has no .catch() 
wappalyzer.open() and site.analyze() are called inside the process_wappalyzer() in the try catch, I don't understand why the try catch is not catching the error.
Why should the Promise.all() fail because of a single website timeout?
**Expected behavior**
No warnings, no process hang.

**Comment by AliasIO** [comment]
Made some changes in 6625a034b17965e9e30234f8a27b4f7f03e64e50, can you see if this still happens in v6.7.5?

**Comment by mandricmihai** [comment]
Is working fine now. No more errors.

**Comment by AliasIO** [comment]
Thanks for confirming!
