### ISSUE TITLE
Salesforce CRM detection is not correct

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4014]
Example - Direct.asda.com

Chrome extension shows that site is using 'Salesforce' CRM. 

![image](https://user-images.githubusercontent.com/1718757/121881945-cfd15600-cd07-11eb-8e5b-93e2e4b24409.png)

I am very familiar with this site and this site doesn't use Salesforce for CRM. This site uses 'Salesforce Commerce Cloud' which is being detected correctly.

**Comment by AliasIO** [comment]
Wappalyzer will always report SF when SCC is detected. Maybe CRM is not the right category for it?

**Comment by rockeynebhwani** [comment]
I think this should be changed. There is no need to default 'Salesforce' under CRM category in this case.
