### ISSUE TITLE
Track MoveableInk

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4015]
Technology to track - https://movableink.com/
Example site - https://www.boden.co.uk/ / https://direct.asda.com
Detection -

Their JS is called 1.js
<script type="text/javascript" async="" src="//mi.boden.co.uk/p/js/1.js"></script>
<script type="text/javascript" async="" src="//migeorge.asda.com/p/js/1.js"></script>

They tend to load their JS as 1st party ... but we can look for path '/p/js/1.js'

**Comment by nurbek91** [comment]
Hey @rockeynebhwani , added
