### ISSUE TITLE
Borderfree Detection not working on some sites

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4023]
On some sites, borderfree detection is not working. Example sites - 
https://www.hanes.com/
https://www.saksfifthavenue.com/
https://www.neimanmarcus.com/

Please default to US site by changing the country flag as I noticed detection not working for US version.

Current detection 

    "borderfree": {
      "cats": [
        6
      ],
      "icon": "borderfree.png",
      "scripts": [
        "global\\.prd\\.borderfree\\.com",
        "wm\\.prd\\.borderfree\\.com",
        "bfx\\.js"
      ],
      "website": "https://www.borderfree.com/"
    },
 
How can we improve?
 - We can add check for cbt.js (cbt means 'cross border trade')
 - We can check for borderfree cookies which start with bfx
![image](https://user-images.githubusercontent.com/1718757/122648242-38616e00-d120-11eb-9c95-7af58c2ec41a.png)

Even after these checks, I think detection on https://www.neimanmarcus.com/ will not work. Will need something more to detect for this site.

**Comment by nurbek91** [comment]
Hey @rockeynebhwani  , updated
