### ISSUE TITLE
IP geolocation API

### ISSUE THREAD

**Issue by max-ostapenko** [AliasIO/wappalyzer#4041]
Hi,

Additionally to scanning Web Geolocation API calls I had the idea to check for third-party solutions as well.

Am I missing it in the technology list or IP geolocation API are already covered?
If not, let's add [some popular ones](https://geekflare.com/geolocation-ip-api/):

1. ipstack
website: https://api.ipstack.com/
repository: https://github.com/apilayer/freegeoip/

Detection:
request URL starts with `https://api.ipstack.com/`

2. ipify
website: https://www.ipify.org/
repo: https://github.com/rdegges/ipify-api

Detection:
request URL starts with `https://api.ipify.org` OR `https://api64.ipify.org` OR `https://geo.ipify.org/api/`

<del>3. IP Geolocation API
website: https://ipgeolocationapi.com/
repo: https://api.ipgeolocationapi.com/geolocate
Detection:
request URL starts with `https://api.ipgeolocationapi.com/geolocate`</del>
not popular based on HTTP Archive dataset

I have around 10 more on my draft...

**Comment by max-ostapenko** [comment]
I'm working on the detection of these.
Too many similar technologies to keep in **Miscellaneous**. 
What do you think about the category - should it go to **Geolocation**?

**Comment by AliasIO** [comment]
Hi Max! Yes, feel free to create a Geolocation category.

**Comment by nurbek91** [comment]
@max-ostapenko  Hey mate . Added a Geolocation category, now you can send PR under category 79 if you want, thanks!!

**Comment by max-ostapenko** [comment]
Thanks, added a PR with first technologies. #4048 

P.S. I avoided adding api.ipgeolocationapi.com because of the small amounts of websites.
