### ISSUE TITLE
Add 'browser fingerprinting' category

### ISSUE THREAD

**Issue by VictorLeP** [AliasIO/wappalyzer#4047]
For the Privacy chapter of the 2021 Web Almanac, we were considering to detect '[browser fingerprinting](https://w3c.github.io/fingerprinting-guidance/#browser-fingerprinting)' libraries (that create a unique identifier for a user/device based on their browser configuration). 
I don't think this is already listed as a separate category. Could it be useful to add a category for browser fingerprinting? It's somewhat similar to analytics, but more nefarious (which is why we want to study it separately).

Examples of libraries:

- https://fingerprintjs.com/ -- already listed as `FingerprintJS`, but under the catch-all 'JavaScript libraries' category
- https://www.npmjs.com/package/browser_fingerprint
- http://clientjs.org/ / https://github.com/jackspirou/clientjs
- https://github.com/BarkleyREI/lingerprint
- https://morioh.com/p/1d9017013df6 / https://github.com/mattbrailsford/imprintjs
- BlueCava: https://sync.graph.bluecava.com/js/bc.js
- others from NPM https://www.npmjs.com/search?q=keywords:browser%20fingerprinting

I could look into creating the fingerprints for these fingerprinting libraries (heh) if the category is added.

**Comment by AliasIO** [comment]
Sure thing, we'll add the category. :)

**Comment by rockeynebhwani** [comment]
Just a thought .. Some security solutions (e.g. PerimeterX and others in this category) may also do fingerprinting. We already take such solutions under 'Security' category.

**Comment by VictorLeP** [comment]
> Just a thought .. Some security solutions (e.g. PerimeterX and others in this category) may also do fingerprinting. We already take such solutions under 'Security' category.

True, although fingerprinting has applications beyond security, notably tracking. A separate category might better allow to distinguish whether a technology includes fingerprinting or not? (so for your examples, they would go both in the 'security' and 'fingerprinting' categories)

**Comment by rockeynebhwani** [comment]
@VictorLeP  - Fine with your proposal to assign such solutions to both categories

**Comment by AliasIO** [comment]
Added in #4051.
