### ISSUE TITLE
PerimeterX detection not working

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4061]
Example site - www.walmart.com

Current detection logic

    "PerimeterX": {
      "cats": [
        16
      ],
      "icon": "perimeterx.svg",
      "description": "PerimeterX is a provider of scalable, behavior-based threat protection technology for the web, cloud, and mobile.",
      "cookies": {
        "_px3": "",
        "_pxff_cc": "",
        "_pxhd": "",
        "_pxvid": ""
      },
      "js": {
        "_pxAppId": ""
      },
      "scripts": "client\\.a\\.pxi\\.pub/",
      "saas": true,
      "pricing": [
        "payg",
        "recurring",
        "poa"
      ],
      "website": "https://www.perimeterx.com"
    },

Walmart site seems to  have _pxAppId object

**Comment by Karbust** [comment]
It's working fine on Udemy with the cookie detection, however there's no `_pxAppId` present.

Wallmart doesn't seem to have those cookies present, but has the `_pxAppId` script tag.

**Comment by AliasIO** [comment]
It's being reported for me. Is it not working for you in the extension? It might be because the script is loaded asynchronously (i.e. late).

**Comment by Karbust** [comment]
> It's being reported for me. Is it not working for you in the extension? It might be because the script is loaded asynchronously (i.e. late).

You're correct, I refreshed after the first load and PermiterX detection popped-up.

**Comment by rockeynebhwani** [comment]
@AliasIO  - Yes.. it's showing now. Maybe it was just slow. We can close this.

**Comment by rockeynebhwani** [comment]
Also, example site to check 'Wix Commerce' as per suggestion from @DanShappir - https://www.coalandcanary.com/
