### ISSUE TITLE
SaleCycle Detection not working

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4062]
Example site - https://es.boohoo.com/

Current Detection 

    "SaleCycle": {
      "cats": [
        6
      ],
      "html": "<iframe[^>]+title=\"SaleCycle\"[^>]+src=\"[^>]+salecycle\\.com",
      "icon": "salecycle.svg",
      "website": "https://www.salecycle.com/"
    },

Above site has following 

<iframe target="_self" title="SaleCycle" src="https://s.salecycle.com/receiver.html?sc_frame_id=8da2952f-6022-473a-bc05-e448ad2577d3" style="display: none; height: 0px; width: 0px;"></iframe>

**Comment by nurbek91** [comment]
hey there , updated.
