### ISSUE TITLE
Track TradeDesk

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4065]
Example site - https://direct.asda.com/george/clothing/10,default,sc.html
Vendor site - https://www.thetradedesk.com/us

Detection - look for https://js.adsrvr.org/universal_pixel.1.1.0.js

You an also look for js object - ttd_dom_ready and TTDUniversalPixelApi

**Comment by nurbek91** [comment]
Hey there , added.
