### ISSUE TITLE
Detect Oracle Maxymiser

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4066]
Example site - https://www.matalan.co.uk/
Vendor site - https://www.oracle.com/uk/cx/marketing/personalization-testing/ 
Categories to be used - Personalisation and A/B Testing
Detection - look for https://service.maxymiser.net/api/eu/new.matalan.co.uk/1192b7/mmapi.js
JS object - I also see object called 'maxy' on this site but not 100% sure

**Comment by nurbek91** [comment]
Hey there , added
