### ISSUE TITLE
Detect ContentSquare

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4067]
Example site - https://www.matalan.co.uk/
Vendor site - https://contentsquare.com/
Detection - look for script t.contentsquare.net/uxa/f661eae0de153.js ... Use *.js in detection from t.contentsquare.net

**Comment by rockeynebhwani** [comment]
Another site for testing - https://es.boohoo.com/

**Comment by nurbek91** [comment]
Hey there , added.
