### ISSUE TITLE
Detect Salesforce Evergage

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4068]
Example site - https://www.matalan.co.uk/
Vendor site - https://www.salesforce.com/products/marketing-cloud/customer-interaction/
Detection - Check for https://cdn.evgnet.com/beacon/matalan/engage/scripts/evergage.min.js OR JS object 'Evergage'
Category - Personalisation 

Please note that Salesforce acquired Evergage.

**Comment by nurbek91** [comment]
Hey there , added
