### ISSUE TITLE
Detect RapidSpike

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4069]
Example site - https://www.matalan.co.uk/
Vendor site - https://www.rapidspike.com/
Category to be used - RUM
Detection - Look for https://cdn-assets.rapidspike.com/static/js/timingpcg.min.js

**Comment by nurbek91** [comment]
Hey there , added

**Comment by rockeynebhwani** [comment]
@nurbek91  - I see that you added this under category 13 and 16. I think we should explicitly check for timingpcg.min.js and add this under category 'RUM'

**Comment by nurbek91** [comment]
Ok, i will take a look!

**Comment by nurbek91** [comment]
Hey there , updated
