### ISSUE TITLE
Improve Outbrain Detection

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4070]
Example site where detection is not working - https://www.everlane.com/

Current Detection - 

    "Outbrain": {
      "cats": [
        5
      ],
      "icon": "Outbrain.png",
      "js": {
        "OB_releaseVer": "^(.+)$\\;version:\\1",
        "OutbrainPermaLink": ""
      },
      "scripts": "widgets\\.outbrain\\.com/outbrain\\.js",
      "website": "https://www.outbrain.com"
    },

Add additional checks -

Look for https://amplify.outbrain.com/cp/obtp.js
and JS objects like obApi and OB_ADV_ID

**Comment by nurbek91** [comment]
Hey there , updated
