### ISSUE TITLE
Detection for Sift not working

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4071]
Example site - https://www.everlane.com/

Current detection - 
    "Sift": {
      "cats": [
        10
      ],
      "icon": "Sift.png",
      "scripts": [
        "cdn\\.sift(?:science)?\\.com/s\\.js"
      ],
      "website": "https://sift.com/"
    },

Site has https://cdn.siftscience.com/s.js

**Comment by nurbek91** [comment]
Hey there , updated
