### ISSUE TITLE
Improve Osano detection

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4072]
Example site - https://www.hobbycraft.co.uk/

Current detection -

    "Osano": {
      "cats": [
        67
      ],
      "description": "Osano is a data privacy platform that helps your website become compliant with laws such as GDPR and CCPA.",
      "icon": "osano.png",
      "scripts": "cookieconsent\\.min\\.js",
      "website": "https://www.osano.com/"
    },

To improve detection, look for JS object 'Osano'.  Keep the current script detection as well

**Comment by nurbek91** [comment]
Hey there , updated
