### ISSUE TITLE
Track RichRelevance

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4077]
Vendor site - https://richrelevance.com/
Example site - https://www.notonthehighstreet.com/search?term=frame%20print&filter[category_id]=15000

Detection - https://media.richrelevance.com/rrserver/js/1.2/p13n.js

You can also look for cookies rr_session and rr_rcs and JS objects starting with rr_

**Comment by nurbek91** [comment]
Hey there , added
