### ISSUE TITLE
Track Snigel GDPR Consent

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4080]
Vendor site - https://www.snigel.com/adconsent/
Example site - https://www.w3schools.com/sql/sql_join_inner.asp
Category - Cookie Compliance
Detection - 

JS object --> _snigelConfig
Script --> cdn.snigelweb.com/sncmp/latest/sncmp_stub.min.js

**Comment by nurbek91** [comment]
Hey there , added
