### ISSUE TITLE
Improve DynamicYield detection

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4084]
Example Site where it's not being detected - https://www.houseoffraser.co.uk/brand/ann-summers

Current Detection - 

    "Dynamic Yield": {
      "cats": [
        74,
        76
      ],
      "cookies": {
        "_dy_geo": "",
        "_dy_ses_load_seq": ""
      },
      "description": "Dynamic Yield is a provider of automated conversion optimisation tools for marketers and retailers.",
      "icon": "DynamicYield.svg",
      "js": {
        "recommendationContext": ""
      },
      "scripts": "cdn\\.dynamicyield\\.\\w+/",
      "website": "https://www.dynamicyield.com"
    },

Improvement - Look for js object '_dy_memStore'

Also, there are bunch of other cookies start with '_dy_' on this example site which you add to improve detection

**Comment by nurbek91** [comment]
Hey there , updated
