### ISSUE TITLE
Add 'Moove GDPR Consent'

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4085]
Vendor site - https://www.mooveagency.com/wordpress/gdpr-cookie-compliance-plugin/
Example sites - 
https://www.fabbaloo.com/
https://www.phorest.com/

Detection - Look for JS object 'moove_frontend_gdpr_scripts'

Category - Cookie Compliance

**Comment by nurbek91** [comment]
Hey there , added . 
@AliasIO  Maybe it would be great that **`require`** worked for such cases except **themes**.
