### ISSUE TITLE
Improve 'Salesforce Commerce Cloud' detection to avoid false positives

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4090]
Current detection for Salesforce Commerce Cloud 

    "Salesforce Commerce Cloud": {
      "cats": [
        6
      ],
      "description": "Salesforce Commerce Cloud is a cloud-based software-as-a-service (SaaS) ecommerce solution.",
      "headers": {
        "Server": "Demandware eCommerce Server"
      },
      "html": [
        "<[^>]+demandware\\.edgesuite"
      ],
      "icon": "Salesforce.svg",
      "implies": "Salesforce",
      "js": {
        "dwAnalytics": ""
      },
      "pricing": [
        "poa"
      ],
      "saas": true,
      "scripts": "/demandware\\.static/",
      "website": "http://demandware.com"
    },

While analysing data for Web Almanac project, I am seeing false positives. I believe these are coming due to sites (like blog / affiliate etc.) linking to Demandware images which are served from demandware.edgesuite domain. 

We should remove below from the check

      "html": [
        "<[^>]+demandware\\.edgesuite"
      ],

Instead you add following checks -

- look for cookies 'dwsid' and 'dw_dnt'
- Look for js object 'dw'

These are better checks compared to looking for edgesuite links in HTML. 

Example sites
- https://direct.asda.com/george/clothing/10,default,sc.html
- https://es.boohoo.com/

Also update the website link to https://www.salesforce.com/uk/products/commerce-cloud/overview/

**Comment by rockeynebhwani** [comment]
Also, can we check why https://mitchell-fishing.co.uk/ is returning both 'Salesforce Commerce Cloud' and 'Shopify' as eCommerce platform. It's not possible. This site runs on Shopify.

![image](https://user-images.githubusercontent.com/1718757/123713080-8df9f100-d86b-11eb-8faa-2232d0ffa478.png)

P.S. - Global-e is listed correctly as that can work with both SFCC and Shopify

**Comment by AliasIO** [comment]
I'm not seeing SCC. Could you try clearing the detections cache on the latest version?

**Comment by rockeynebhwani** [comment]
@AliasIO  - Now, I am also not seeing SFCC for https://mitchell-fishing.co.uk/. 

Can we just apply fix for removing below from detection as I don't think it's really required and generating lots of false positives?

 "html": [
    "<[^>]+demandware\\.edgesuite"
  ],

**Comment by rockeynebhwani** [comment]
Another site which is not being detected for 'Salesforce Commerce Cloud' currently - https://www.reebok.co.uk/. This should also work when we add detection for cookie 'dwsid'

**Comment by rockeynebhwani** [comment]
@nurbek91  - Are you able to pick this?
