### ISSUE TITLE
Track Tealium Consent Management 

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4091]
Vendor site- https://docs.tealium.com/platforms/getting-started/consent-management/
Example sites - 
https://www.rvca.fr/
https://docs.tealium.com/platforms/getting-started/consent-management/

Detection - 

Look for a div with id '__tealiumGDPRecModal'

Note that we already have an entry for Tealium but we should add a new one just for 'Tealium Consent Management'

Category - Cookie Compliance

**Comment by nurbek91** [comment]
Hey mate , I do not see this identifier  in this example.

**Comment by rockeynebhwani** [comment]
@nurbek91 - From which country you are trying to access the site ? See DIV in screenshot 

![image](https://user-images.githubusercontent.com/1718757/126204683-4fbce3a2-ebdb-4561-89fd-32ba241039b9.png)

**Comment by nurbek91** [comment]
Hey there , added .

**Comment by noodles** [comment]
@AliasIO should this be closed?

**Comment by rockeynebhwani** [comment]
@noodles  - I still don't see working on example sites

**Comment by rockeynebhwani** [comment]
@AliasIO - Chrome extension version I have is 6.7.13 and that's the version I see in Chrome Web Store

![image](https://user-images.githubusercontent.com/1718757/131749762-ad95f1ca-4974-4f14-b76c-fb88b3f4b528.png)

**Comment by AliasIO** [comment]
@rockeynebhwani v6.8.3 Should come through soon, it's pending approval.
