### ISSUE TITLE
Fix 'Quantcast Choice' Consent Management logic

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4094]
Example site - https://www.skiphop.com/?id=skiphop&updateCountry=true (Select country as 'UK' from footer)

This shows 'Quantcast Choice' and 'OneTrust' under Cookie Compliance category.

For Quantcast, we have following detection - 

    "Quantcast Choice": {
      "cats": [
        67
      ],
      "description": "Quantcast Choice is a free consent management platform to meet key privacy requirements stemming from ePrivacy Directive, GDPR, and CCPA.",
      "icon": "Quantcast.png",
      "js": {
        "quantserve": ""
      },
      "scripts": "quantcast\\.mgr\\.consensu\\.org",
      "website": "https://www.quantcast.com/gdpr/consent-management-solution/"
    },
    "Quantcast Measure": {
      "cats": [
        10
      ],
      "icon": "Quantcast.png",
      "js": {
        "quantserve": ""
      },
      "scripts": "\\.quantserve\\.com/quant\\.js",
      "website": "https://www.quantcast.com/products/measure-audience-insights/"
    },

For 'Quantcast Choice' we shouldn't have JS object 'quantserve'. Looks like that's required only for 'Quantcast Measure'

**Comment by nurbek91** [comment]
Hey there , updated
