### ISSUE TITLE
Track 'orckestra' eCommerce platform

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4109]
Vendor site - https://www.orckestra.com/
Example sites - 
https://www.mondou.com/en-CA/
https://www.okpria.com/

Detection - 

Look for following - 
<meta name="Generator" content="C1 CMS Foundation - Free Open Source from Orckestra and https://github.com/Orckestra/C1-CMS-Foundation">

**Comment by nurbek91** [comment]
Hey there , added
