### ISSUE TITLE
Track 'Hubspot' cookie compliance

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4117]
Vendor site - https://knowledge.hubspot.com/reports/customize-your-cookie-tracking-settings-and-privacy-policy-alert
Example site - https://www.durangoboots.com/
Category - Cookie Compliance
Detection - look for a script loading from https://js.hs-banner.com/XXXXXXX.js (where XXXXXXX is dynamic)

**Comment by nurbek91** [comment]
Hey there , added
