### ISSUE TITLE
Fix detection for 'Flow' (Cross border Ecommerce platform)

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4118]
Lot of sites are wrongly detecting Flow.io cross border commerce platform due to our check being very generic

Current Detection

    "Flow": {
      "cats": [
        6
      ],
      "icon": "flow.png",
      "scripts": [
        "shopify-cdn\\.flow\\.io",
        "flow\\.min\\.js"
      ],
      "website": "https://www.flow.io/"
    },

Following example sites are incorrectly detecting - 

https://seniorconnections-va.org/ --> matches jquery.mosaicflow.min.js
https://monolithgraphics.com/ --> matches coverflow.min.js

There are many more such sites... For non-shopify platform, Flow JS loads from cdn.flow.io domain so we should add that within our detection. 

https://cdn.flow.io/flowjs/latest/flow.min.js

Example site to test - https://www.charlesandcolvard.com/

**Comment by rockeynebhwani** [comment]
While fixing this, we can also add check for js object 'flow'

**Comment by nurbek91** [comment]
Hey there , fixed false positive results
