### ISSUE TITLE
Track 'Segment Consent Management' 

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4119]
Example site - https://wisepops.com/
Category - Cookie Compliance
Detection - Look for presence of script 
https://www.unpkg.com/browse/@segment/consent-manager@1.3.0/commonjs/ (Detect version number from URL)

Vendor site - https://segment.com/blog/how-to-build-consent-management-into-your-site-in-less-than-a-week/

We already have an entry for Segment in technologies.json but segment has open sourced their consent management implementation so it's best to track 'Segment Consent Management' as a different entry under category 'Cookie Compliance'

**Comment by nurbek91** [comment]
Hey there , added
