### ISSUE TITLE
Track 'MyDukaan' Ecommerce platform

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4147]
Example - https://abhinavstore.in/
Vendor site - https://mydukaan.io/
Category - Ecommerce
Detection - Look for script with pattern https://apps.mydukaan.io/public/XXXXXXXX/apps.js

**Comment by nurbek91** [comment]
Hey mate . added as Dukaan . 
Perhaps this is the same project or a different one? http://www.mydukaan.com/

**Comment by rockeynebhwani** [comment]
@nurbek91  - No.. it's not the same

**Comment by nurbek91** [comment]
Ok thanks  , then did the right thing to leave the name MyDuakan behind them
