### ISSUE TITLE
TypeError: Wappalyzer.requires.map(...).flat(...) is not a function or its return value is not iterable

### ISSUE THREAD

**Issue by mayurtakawale88** [AliasIO/wappalyzer#4149]
**Platform**
Which platform does the bug apply to?
* Node 10

**Describe the bug**
Every time when I am trying to find cms used on the website, it is giving me a TypeError, please find the code which I am trying to run

`

                 var Wappalyzer = require("wappalyzer")
                 function getCms() {
                     return new Promise(async(resolve, reject) => {
                       try {
                         const options = {
                            debug: false,
                            delay: 500,
                            headers: {},
                            maxDepth: 3,
                            maxUrls: 10,
                            maxWait: 5000,
                            recursive: true,
                            probe: true,
                            userAgent: 'Wappalyzer',
                            htmlMaxCols: 2000,
                            htmlMaxRows: 2000,
                         };

                        const wappalyzer = new Wappalyzer(options)

                        await wappalyzer.init()

                        // Optionally set additional request headers
                        const headers = {}

                        const site = await wappalyzer.open("https://example.com", headers)

                        // Optionally capture and output errors
                        // site.on('error', console.error)

                        const results = await site.analyze()

                        log.info(JSON.stringify(results, null, 2))
                        await wappalyzer.destroy()

                        const { technologies } = results;
                        resolve(technologies)
                     } catch (err) {
                        reject(err)
                     }
               })
           }

           getCms().then(data => {
               console.log(data)
            })
`

**Comment by AliasIO** [comment]
Are you using the latest version? Your code works for me without any errors. Maybe try it with `debug: true`.

**Comment by mayurtakawale88** [comment]
@AliasIO I got the fix. I was trying with Node 10 and because of that, it was not working. When I shift to node 12, it works perfectly.

Thank you for the quick revert.
