### ISSUE TITLE
Track 'Lootly' Loyalty Solution

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4158]
Vendor Site - https://lootly.io/
Example Site - https://smartfurniture.com/
Detection - Look for Script like https://lootly.io/js/integrations/bigcommerce/script.js
Category - Ecommerce

We also added Smile loyalty solution recently as part of  https://github.com/AliasIO/wappalyzer/issues/4122. I was thinking if it makes sense to have a separate category for 'Loyalty Solutions' and dual categorised in Ecommerce if applicable.

**Comment by nurbek91** [comment]
Hey there, added
