### ISSUE TITLE
Improve 'SalesFloor' detection

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4159]
Example site - https://www.chicos.com/store/

Current Detection - 

    "Salesfloor": {
      "cats": [
        6
      ],
      "icon": "salesfloor.png",
      "scripts": [
        "salesFloor\\.js"
      ],
      "website": "https://salesfloor.net/"
    },

But it's not catching Chicos site. We can also add check for object 'salesFloorHost'

**Comment by nurbek91** [comment]
Hey there , updated
