### ISSUE TITLE
Improve detection for BigCommerce Ecommerce platform

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4160]
Current detection for BigCommerce is not detecting Wordpress sites using BigCommerce wordpress plug-in.

Example sites - 
https://www.podbike.com/
https://www.carluccios.com/shop/

Current detection -

    "BigCommerce": {
      "cats": [
        6
      ],
      "description": "BigCommerce is a hosted ecommerce platform that allows business owners to set up an online store and sell their products online.",
      "dom": "img[data-src*='.bigcommerce.com'], img[src*='.bigcommerce.com'], link[href*='.bigcommerce.com']",
      "icon": "BigCommerce.svg",
      "pricing": [
        "low",
        "recurring"
      ],
      "saas": true,
      "scripts": ".bigcommerce\\.com",
      "url": "mybigcommerce\\.com",
      "website": "http://www.bigcommerce.com"
    },

We can improve this by look for js object 'bigcommerce_config'

If we want to create a new entry for 'BigCommerce for Wordpress', site link can be - https://www.bigcommerce.co.uk/blog/bigcommerce-for-wordpress

**Comment by nurbek91** [comment]
Hey there , updated  original one .
