### ISSUE TITLE
Improve detection for 'Klarna' Payment

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4165]
Current Detection - 

    "Klarna Checkout": {
      "cats": [
        41,
        6
      ],
      "description": "Klarna Checkout is a complete payment solution where Klarna handles a store's entire checkout.",
      "icon": "Klarna.svg",
      "js": {
        "_klarnaCheckout": ""
      },
      "website": "https://www.klarna.com/international/"
    },

Example site missing detection - https://www.yumi.co.uk/

Detection - Look for https://eu-library.klarnaservices.com/lib.js

Also, may be we should just rename this to 'Klarna' instead of 'Klarna Checkout'. What do you think?

**Comment by rockeynebhwani** [comment]
Example site for North America - https://www.shopjustice.com/

Detection - https://na-library.klarnaservices.com/lib.js

I think we should just check for '*-library.klarnaservices.com/lib.js'

**Comment by rockeynebhwani** [comment]
Another implementation and detection which will not be caught by script detection

Example site - https://www.ilovedooney.com/

Check for cookies ku1-sid, ku1-vid, ku3-vid

Found this info from a site's cookie policy

![image](https://user-images.githubusercontent.com/1718757/125191861-80b20e80-e23c-11eb-9bbb-feab4c8994c4.png)

**Comment by nurbek91** [comment]
Hey @rockeynebhwani  ,  updated.
but did not rename it, it threatens the loss of statistics.
It would be possible to study more deeply and separate the platform and the payment system. But I didn't do it

**Comment by rockeynebhwani** [comment]
Thanks @nurbek91  - sounds good
