### ISSUE TITLE
Improve detection for 'DigitalRiver' Ecommerce platform

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4166]
Current Detection - 

    "DigitalRiver": {
      "cats": [
        6
      ],
      "cookies": {
        "X-DR-SHOPPER-ets": "",
        "X-DR-THEME": "^\\d+$"
      },
      "description": "Digital River provides global ecommerce, payments and marketing services.",
      "icon": "DigitalRiver.svg",
      "scripts": "/drh\\.img\\.digitalriver\\.\\w+/DRHM/",
      "website": "https://www.digitalriver.com"
    },

Sites which is currently not detecting this - https://www.jabra.co.uk/

We can detect by looking for https://js.digitalriver.com/v1/DigitalRiver.js

**Comment by nurbek91** [comment]
Hey there ,  updated.
