### ISSUE TITLE
Track 'AdRoll' Cookie Consent

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4167]
Vendor site - https://www.adroll.com/features/consent-management
Example site - https://us.upsellit.com/
Detection -  Look for DIV ID 'adroll_consent_container'
Category - Cookie Compliance

Note that we already have an entry for 'AdRoll'. Proposal here is to create a new entry for 'AdRoll Consent Management' under 'Cookie Compliance' category

**Comment by nurbek91** [comment]
Hey there ,  added .
