### ISSUE TITLE
'UpSellIt' detection not working

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4169]
Example site - https://www.jabra.co.uk/

Current detection - 

    "UpSellit": {
      "cats": [
        76
      ],
      "description": "UpSellit is a performance based lead and cart abandonment recovery solutions.",
      "icon": "UpSellit.png",
      "js": {
        "usi_analytics": "\\;confidence:25",
        "usi_app": "\\;confidence:25",
        "usi_commons": "\\;confidence:25",
        "usi_cookies": "\\;confidence:25"
      },
      "pricing": [
        "poa",
        "mid"
      ],
      "saas": true,
      "scripts": "www\\.upsellit\\.com/active",
      "website": "https://us.upsellit.com"
    },

While fixing this, it will also be good to categorise, this under Ecommerce (category 6) as all sites in this case will be Ecommerce.

**Comment by nurbek91** [comment]
Hey there ,  updated .
