### ISSUE TITLE
Improve detection of 'AudioEye' accessibility plug-in

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4171]
Current Detection - 

    "AudioEye": {
      "cats": [
        68
      ],
      "description": "AudioEye automatically evaluates and adjusts website content to be accessible.",
      "html": "<iframe[^>]*audioeye\\.com/frame/cookieStorage",
      "icon": "AudioEye.svg",
      "scripts": "audioeye\\.com/ae\\.js",
      "website": "https://www.audioeye.com/"
    },

Site where detection is not working - https://www.myfamilymobile.com/

Additional checks to add - Check for following cookies -

_aeaid
aeatstartmessage
aelastsite
aeatstartmessage

**Comment by nurbek91** [comment]
Hey there, updated . Thnaks , got also version and new icon
