### ISSUE TITLE
Improve detection for 'Cart Fuctionality' to detect more Ecommerce sites

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4172]
Currently, we have detection for generic tech called 'Cart Functionality'. This is helpful when we can't detect a specific Ecommerce platfrom. I am proposing to improve this detection further. 

Current Detection - 

    "Cart Functionality": {
      "cats": [
        6
      ],
      "description": "Websites that have a shopping cart or checkout page, either using a known ecommerce platform or a custom solution.",
      "dom": "a[href*='/cart'], a[href*='/basket'], a[href*='/trolley'], a[href*='/bag'], a[href*='/shoppingbag'], a[href*='/checkout'], [aria-controls='cart']",
      "icon": "Cart-generic.svg",
      "website": "https://www.wappalyzer.com/technologies/ecommerce/cart-functionality"
    },

We can look for presence of following JS variable - 

google_tag_params.ecomm_pagetype

ecomm_pagetype is something which is required for Google Dynamic remarketing implementation and sites are expected to populate this on all pages. This can help us increase the coverage for Ecommerce sites further..

Example site - https://www.mandmdirect.com/

Let me know what you think.

**Comment by nurbek91** [comment]
Hey there , updated .
