### ISSUE TITLE
Track 'LoyaltyLion' under Loyalty category

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4185]
Vendor site - https://loyaltylion.com/
Example site - https://www.mynamenecklace.com/
Category - Loyalty & Rewards
Detection - 

- check for object 'loyaltylion'
- check for script with pattern - https://sdk.loyaltylion.net/sdk/start/4b62216ba953eaaf819a1c0991aad612.js?t=202161310

**Comment by nurbek91** [comment]
Hey there , added .
