### ISSUE TITLE
Improve detection for 'Optimizely'

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4186]
Current Detection - 

    "Optimizely": {
      "cats": [
        74
      ],
      "icon": "Optimizely.svg",
      "js": {
        "optimizely": ""
      },
      "pricing": [
        "poa",
        "high"
      ],
      "saas": true,
      "scripts": "optimizely\\.com.*\\.js",
      "website": "https://www.optimizely.com"
    },

Not being detected on - https://www.factoryauthorizedoutlet.com/

Add additional check to look for cookie 'optimizelyEndUserId'

**Comment by nurbek91** [comment]
Hey mate , I do not see this identifier in cookies in this example.

**Comment by rockeynebhwani** [comment]
@nurbek91  - You can check this site to see cookie 'optimizelyEndUserId' - https://direct.asda.com/george/clothing/10,default,sc.html

Sometimes sites will use this technology only for a certain % of the visits... If you don't see this cookie, try some new sessions in incognito... you should see this with 2 or 3 sessions

**Comment by nurbek91** [comment]
Hey there , updated .
