### ISSUE TITLE
browser is undefined in destroy method

### ISSUE THREAD

**Issue by Ribeiro-Tiago** [AliasIO/wappalyzer#4190]
**Platform**
Which platform does the bug apply to?
* NPM

**Describe the bug**
`this.browser` is undefined in `Driver.destroy()`, so brower is never really closed

**To Reproduce**
- Follow the [usage documentation](https://github.com/AliasIO/wappalyzer/blob/master/src/drivers/npm/README.md)

**Expected behavior**
I expected the browser to close, but it doesn't so I end up using all the memory in the container that's running my app because of several unused opened browser instances

**Additional context**
It might also be a user issue and I'm just not calling the correct thing. But what I'm doing is:
```
const wappalyzer = new Wappalyzer({
    debug: isDebug,
    recursive: false,
    probe: true,
    maxDepth: 5,
    maxUrls: 1,
    delay: 1000,
    userAgent: `blah blah`,
})
const site = wappalyzer.open(url)
(...)
await site.analyze()
(...)
await wappalyzer.destroy()
```
I've also tried await site.driver.destroy(), but I get destroy is not a function
I've also added logs around the place the check for values and race conditions, and everything seems to be working as expected except Driver.destroy,

Running wappalyzer version 6.7.9

**Comment by Ribeiro-Tiago** [comment]
I realized that I wasn't calling `await wappalyzer.init()` and once I did the browser started closing on `wappalyzer.destory()`.

Now my question is, since `wappalzyzer.init` is called in `Site.goto()` (via `this.initDriver` that's defined on `Site` constructor), which, according to console.log and previous usage, `wappalyzer.init` does indeed get called and works correctly, why is `wappalyzer.browser` undefined ?

**Comment by AliasIO** [comment]
I can't see why it wouldn't be defined. Does it work correctly when you call `wappalyzer.init()` beforehand?

**Comment by Ribeiro-Tiago** [comment]
Yeah, if I specifically call it it works
