### ISSUE TITLE
Track 'Conversant' Cookie Compliance

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4191]
Vendor site - https://www.conversantmedia.eu/consent-tool
Example Site - https://www.dunelondon.com/
Category - Cookie Compliance
Detection - Look for script  https://cdn.conversant.mgr.consensu.org/gdpr/cmp/gdpr-cmp-stub.js

**Comment by nurbek91** [comment]
Hey there , added
