### ISSUE TITLE
Detection for 'Osano' not working

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4192]
Current Detection - 

    "Osano": {
      "cats": [
        67
      ],
      "description": "Osano is a data privacy platform that helps your website become compliant with laws such as GDPR and CCPA.",
      "icon": "Osano.svg",
      "js": {
        "Osano": ""
      },
      "pricing": [
        "freemium",
        "mid",
        "recurring"
      ],
      "saas": true,
      "scripts": "cookieconsent\\.min\\.js",
      "website": "https://www.osano.com"
    },

Example site - https://www.hobbycraft.co.uk/

I can see object 'Osano' on this site in my dev console but Chrome extension is not showing 'Osano' under Cookie Compliance category.

**Comment by nurbek91** [comment]
Hey @rockeynebhwani  , I also define it locally in the current versions. Perhaps js objects do not have time to load within 5 seconds. Added a line that additionally looks at the **js** file. I'll check it again after merge if it doesn't help I can add the **dom** identifier

**Comment by nurbek91** [comment]
It is necessary to update the extensions for Chrome to versions 6.7.10

**Comment by rockeynebhwani** [comment]
@nurbek91  - Thanks.. It's working now. We can close this.
