### ISSUE TITLE
Detection for 'ContentSquare' not working

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4193]
Current Detection - 

    "ContentSquare": {
      "cats": [
        58
      ],
      "description": "ContentSquare is an enterprise-level UX optimisation platform.",
      "icon": "ContentSquare.png",
      "js": {
        "CS_CONF.trackerDomain": ""
      },
      "pricing": [
        "poa"
      ],
      "saas": true,
      "scripts": "\\.contentsquare\\.net/",
      "website": "https://contentsquare.com"
    },

I don't see it working on any of the sites in my chrome extension. Example sites - 

https://contentsquare.com/gb-en/
https://es.boohoo.com/
https://www.feelunique.com/

**Comment by nurbek91** [comment]
![image](https://user-images.githubusercontent.com/3456008/126335867-df4ddc76-ecb2-4e6e-93d0-518277adaa7f.png)
I don't see any bugs, the technology is being determined. I also don't see how it would be possible to supplement it. 
The reason is the same as here #4192

**Comment by nurbek91** [comment]
It is necessary to update the extensions for Chrome to versions 6.7.10

**Comment by rockeynebhwani** [comment]
Thanks @nurbek91 . I see it working now. I see category for ContentSquare is 'User Onboarding'. What does it really mean? Category doesn't look correct for this.

**Comment by nurbek91** [comment]
Hey there , fixed category .

**Comment by rockeynebhwani** [comment]
Thanks @nurbek91
