### ISSUE TITLE
Add Detection for 'Affirm' BNPL solution

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4195]
Category - Payment Processors
Vendor site - https://www.affirm.com/
Example sites -
https://www.raneystruckparts.com/
https://www.onepeloton.com/shop/bike-plus/bike-plus-basics-package-us (On this site, you need to be on product page)

Detection -

Check for object 'affirm' / '_affirm_config'

**Comment by nurbek91** [comment]
Hey there , added.

**Comment by rockeynebhwani** [comment]
Thanks @nurbek91. This can be closed.
