### ISSUE TITLE
Add detection for 'Fast' Checkout

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4196]
Vendor site - https://www.fast.co/
Example site - https://www.renogy.com/48v-3500w-solar-inverter-charger/
Category - Ecommerce

Detection - 
- Check for JS object 'FAST_VERSION'
- Check for https://js.fast.co/fast-bigcommerce.js (This will be only for bigCommerce based website but no harm in adding this additional check)

**Comment by nurbek91** [comment]
Hey there , added.
