### ISSUE TITLE
Improve 'QuadPay' BNPL detection

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4197]
Current Detection - 

    "Quadpay": {
      "cats": [
        41
      ],
      "description": "Quadpay is a payment platform.",
      "icon": "Quadpay.svg",
      "js": {
        "QuadPayShopify": ""
      },
      "pricing": [
        "payg"
      ],
      "saas": true,
      "scripts": "\\.quadpay\\.com/quadpay-widget-([\\d.]+)\\.js\\;version:\\1",
      "website": "https://www.quadpay.com"
    },

Site where it's not being detected - https://www.gamestop.com/

I see following on the page.. can we add detection for quadpay.js ?

<div class="minicart" data-action-url="/on/demandware.store/Sites-gamestop-us-Site/default/Cart-MiniCartShow" data-quadpay-src="https://cdn.quadpay.com/v1/quadpay.js" data-sezzle-src="https://checkout-sdk.sezzle.com/checkout.js">

**Comment by rockeynebhwani** [comment]
Another example site - https://www.goldstarhoneybees.com/

On this site, we can look for JS Object - 'quadpayID'

**Comment by nurbek91** [comment]
Hey there , updated.
