### ISSUE TITLE
Track 'FlagSmith' Feature Flagging Solution

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4200]
Example Site - https://app.flagsmith.com/projects
Vendor Site - https://flagsmith.com/
Detection - Look for JS object 'flagsmith'

Category - Introduce new category as also suggested in https://github.com/AliasIO/wappalyzer/issues/4199

**Comment by nurbek91** [comment]
Hey there , added. But very bad with examples. Didn't find anything either. I asked technical support to help 
![image](https://user-images.githubusercontent.com/3456008/126537111-cc55cc14-d1b2-4bce-b17a-5bee4ba6ec31.png)
Perhaps later I will update this technology if they send examples

**Comment by rockeynebhwani** [comment]
@nurbek91 - Looks like this is working and we have 90 sites identified - https://www.wappalyzer.com/technologies/feature-management/flagsmith/. Can we close this?

**Comment by nurbek91** [comment]
@rockeynebhwani  Hey mate. Yes, we can probably close it. thanks
