### ISSUE TITLE
Track 'Axeptio' Cookie Compliance/Consent

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4202]
Vendor Site - https://www.axeptio.eu/en/home 
Example Site - https://www.axeptio.eu/en/home / https://www.mirakl.com/
Category - Cookie Compliance
Detection -

- Check for //static.axept.io/sdk.js 
- Check for JS object 'axeptioSettings'

**Comment by nurbek91** [comment]
Hey there , added.
