### ISSUE TITLE
Track 'Split' Feature flagging solution

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4203]
Example Site - https://fetchtruck.com/
Vendor Site - https://www.split.io/solutions/dark-launch/
Detection - Look for JS object 'splitio' or script like https://cdn.split.io/sdk/split-10.10.0.min.js

Category - Introduce new category as also suggested in https://github.com/AliasIO/wappalyzer/issues/4200 and https://github.com/AliasIO/wappalyzer/issues/4199

**Comment by nurbek91** [comment]
Hey there , added.
