### ISSUE TITLE
Offline environment

### ISSUE THREAD

**Issue by samiashton1989** [AliasIO/wappalyzer#4210]
****
Can we run without YARN?  

For example, install the Firefox Extension manually and run 
We need in Offline environment

**Comment by AliasIO** [comment]
You just need Yarn or NPM to install the dependencies. See the [README](https://github.com/AliasIO/wappalyzer/blob/master/README.md) on how to run Wappalyzer locally using the CLI or in Firefox.

**Comment by samiashton1989** [comment]
i install the add-on wappalyzer from fire fox site but mu question is this this add on work without any yarn or NPM?IS there any especial one or why?

**Comment by sebastianparker** [comment]
hi, how can I run node.js natively on web-container without installing it on the system?
something like this link: https://blog.stackblitz.com/posts/introducing-webcontainers/

**Comment by samiashton1989** [comment]
?
