### ISSUE TITLE
Improve detection for 'Bolt Payments'

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4234]
Example Site where detection is not working - https://www.go-parts.com/

Current Detection - 

    "Bolt Payments": {
      "cats": [
        41
      ],
      "description": "Bolt powers a checkout experience designed to convert shoppers.",
      "dom": "bolt-checkout-button",
      "icon": "Bolt.svg",
      "js": {
        "BoltCheckout": "",
        "bolt_callbacks": ""
      },
      "pricing": [
        "poa"
      ],
      "saas": true,
      "website": "https://www.bolt.com/",
      "xhr": "connect\\.bolt\\.com"
    },

What else you can check to improve detection -
- Check for JS objects 'BoltPopup' and 'BoltTrack'
- There is also an iframe with title 'Bolt Checkout'
![image](https://user-images.githubusercontent.com/1718757/126488918-365a04fa-e2ed-40ce-a56b-de906d46fe62.png)

**Comment by nurbek91** [comment]
Hey there , updated.
