### ISSUE TITLE
Rename 'Usabilla' to 'GetFeedback'

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4242]
SurveyMonkey acquired 'Usabilla' and new offering is now called 'GetFeedback'. See these articles -
https://techcrunch.com/2019/03/05/surveymonkey-acquires-web-survey-company-usabilla-for-80m/
https://www.globenewswire.com/news-release/2021/04/06/2205102/0/en/SurveyMonkey-Debuts-Rebrand-of-GetFeedback-CX-Platform.html

Vendor Site - https://www.getfeedback.com/
Example Site - https://www.chasecenter.com/home
You will see that Wappalyzer detects 'Usabilla' on this site but feedback widget says powered 'GetFeedback'. You can click 'Feedback' floating tab to see this OR screenshot attached

![image](https://user-images.githubusercontent.com/1718757/127006774-7fdac766-b54b-467a-bc41-dfe618b359f9.png)

Also, I think we should tag this in additional category of 'Surveys'. Currently it's tracked under 'Issue Trackers'

**Comment by AliasIO** [comment]
Updated, thanks!
