### ISSUE TITLE
Rename 'Kampyle' to Medallia

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4243]
Medallia acquired Kampyle - https://www.medallia.com/press-release/medallia-acquires-digital-voice-customer-leader-kampyle/

We have detection for Kampyle, we should rename it to Medallia... Kampyle site no longer exists and it redirects to https://www.medallia.com/

Also, Kampyle should be mapped to 'Surveys' category also. For example, feedback widget on this site https://www.bunnings.com.au/ is powered by Kampyle/Medallia but it's not shown under 'Surveys' category.

**Comment by AliasIO** [comment]
Updated, thanks!
