### ISSUE TITLE
SnapChat Pixel detection not working 

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4248]
Example site where detection is not working - https://www.ulta.com/

Current Detection - 

    "Snap Pixel": {
      "cats": [
        36
      ],
      "description": "Snap Pixel is a piece of JavaScript code that helps advertisers measure the cross-device impact of campaigns.",
      "icon": "Snap Pixel.svg",
      "js": {
        "__SnapPixel": "",
        "snaptr.pixelIdList": ""
      },
      "saas": true,
      "scripts": "intg\\.snapchat\\.com/",
      "website": "https://businesshelp.snapchat.com/s/article/snap-pixel-about"
    },

Detection improvement - We can additionally look for script https://sc-static.net/scevent.min.js

**Comment by AliasIO** [comment]
I don't think there's much we can do, the pixel loads in very late.

**Comment by rockeynebhwani** [comment]
Thanks @AliasIO. We can close this. I have now seen it working for me also sometimes.
