### ISSUE TITLE
Track 'Queue-It'

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4249]
Vendor Site - https://queue-it.com/
Example Site - https://www.ulta.com/
Detection - Look for JS object 'queueit' / 'QueueIt' / 'queueit_clientside_config'

**Comment by nurbek91** [comment]
@rockeynebhwani @AliasIO hey there 
Queue-it is a virtual waiting room platform designed to protect your website and mobile app from slowdowns or crashes during end-user peaks. Which **category** would you recommend?
**_widgets 
 booking 
real user monitoring 
performance_**

**Comment by AliasIO** [comment]
Performance I'd say.
