### ISSUE TITLE
Track 'Rockerbox'

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4256]
Example Site - https://www.wearfigs.com/
Vendor Site - https://www.rockerbox.com/
Detection - Look for script like https://rbqnb9ch.wearfigs.com/integrations

**Comment by rockeynebhwani** [comment]
Commenting so that issue doesn't get closed

**Comment by nurbek91** [comment]
@rockeynebhwani Hey mate, again ;), don't worry. They won't be closed without my PR. I will take care of your request in the coming days

**Comment by rockeynebhwani** [comment]
Thanks @nurbek91
