### ISSUE TITLE
Track 'Shopify Consent Management'

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4272]
Vendor Site - https://apps.shopify.com/customer-privacy-banner
Example Site - https://www.vikleliv.dk/
Category - Cookie Compliance
Detection - Look for script cookie_consent_shopify.js from domain cdn.shopify.com (example - https://cdn.shopify.com/s/files/1/0194/1736/6592/t/1/assets/cookie_consent_shopify.js)

**Comment by noodles** [comment]
Description - Customer Privacy Banner helps collect tracking consent from online store visitors in the EU in order to comply with regulations such as GDPR
Pricing - free
