### ISSUE TITLE
Track 'Clickio' Consent Management

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4279]
Vendor Site - http://www.gdpr.clickio.com/
Example Site - https://www.uktech.news/featured/shop-now-stress-later-which-bnpl-scheme-do-brit-shoppers-owe-the-most-to-in-2021-20210729
Category - Cookie Compliance
Detection - look for script //clickio.mgr.consensu.org/t/consent_219837.js

**Comment by noodles** [comment]
Description - Customer Privacy Banner helps collect tracking consent from online store visitors in the EU in order to comply with regulations such as GDPR
Pricing - free
