### ISSUE TITLE
Track 'Hulk' Cookie consent solution

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4289]
Vendor Site - https://www.hulkapps.com/products/gdpr-ccpa-cookie-manager-shopify-app
Example Site - https://orgain.com/
Category - Cookie Compliance
Detection - Check for script https://cookiebar.hulkapps.com/hulk_cookie_bar.js

**Comment by noodles** [comment]
Description: The Hulk GDPR/CCPA Compliance Manager lets you enable multiple compliance solutions on your Shopify site through geotargeting.

**Comment by noodles** [comment]
@AliasIO The [example site](https://orgain.com/) has the script URL inside an array, embedded in a tag injection script:

```<script>(function() {
  function asyncLoad() {
    var urls = ["...","https:\/\/cookiebar.hulkapps.com\/hulk_cookie_bar.js?shop=drink-orgain.myshopify.com","..."];
    for (var i = 0; i < urls.length; i++) {
      var s = document.createElement('script');
      s.type = 'text/javascript';
      s.async = true;
      s.src = urls[i];
      var x = document.getElementsByTagName('script')[0];
      x.parentNode.insertBefore(s, x);
    }
  };
```
It also includes a lot of escape characters.

Any ideas on how to detect this? A js pattern maybe?

**Comment by rockeynebhwani** [comment]
@noodles  - You can look for JS object 'hulkSetCookie'. That also will do the trick.
