### ISSUE TITLE
Option to connect puppetter via websocket for performance increase

### ISSUE THREAD

**Issue by taewookim** [AliasIO/wappalyzer#4313]
` await puppeteer.launch`

..is resource intensive. It's way more peformant to call puppetter.connect() to an existing pupetter browser. 

I'm a heavy user of puppeteer and you can get about 8 to 20x more page loads (depending on machine config) just by doing this.

Would it be possible to add an option to be able to do this?

**Comment by AliasIO** [comment]
What you can do is not call `wappalyzer.init()` and assign an existing instance to `wappalyzer.browser` instead. Does that help?

**Comment by taewookim** [comment]
I was looking for a way to pass the websocket to the docker container.

Any other way, instead of forking & making modifications?

**Comment by AliasIO** [comment]
I don't know about your setup but you should be able to create your own endpoint from a copy of [`cli.js`](https://github.com/AliasIO/wappalyzer/blob/master/src/drivers/npm/cli.js) that does what I described. Let me know if that doesn't work for you.

**Comment by tsagli7** [comment]
> What you can do is not call `wappalyzer.init()` and assign an existing instance to `wappalyzer.browser` instead. Does that help?

@AliasIO  could you please explain this a bit more? I currently have the same issue and there is no documentation of wappalyzer.browser. Or else could you just please give an example of how to replace the puppeteer.connect() in wappalyzer. Thank you.

**Comment by AliasIO** [comment]
Normally you'd run Wappalyzer like this:

```javascript
const Wappalyzer = require('wappalyzer')

const wappalyzer = new Wappalyzer()

await wappalyzer.init() // Launches a Puppeteer instance

const site = await wappalyzer.open(url)
```

If you want to use your own browser instance, you can skip `wappalyzer.init()` and assign the instance to `wappalyzer.browser`:

```javascript
const Wappalyzer = require('wappalyzer')

const wappalyzer = new Wappalyzer()

wappalyzer.browser = await puppeteer.launch() // Use your own Puppeteer launch logic

const site = await wappalyzer.open(url)
```

**Comment by tsagli7** [comment]
Thank you this is really helpful.
