### ISSUE TITLE
Track 'Frescojs'

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4318]
Vendor Site - https://www.frescojs.com/
Example Site - https://www.plumo.com/categories/Fashion/
Category - JavaScript libraries
Detection - look for JS object 'Fresco'

**Comment by nurbek91** [comment]
Is the vendor site abandoned? Maybe the project itself is also abandoned.

**Comment by rockeynebhwani** [comment]
@nurbek91  - I think we can use this as vendor site - https://github.com/staaky/fresco
