### ISSUE TITLE
Track 'recharge' Subscription Payments provider

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4338]
Vendor Site - https://rechargepayments.com/
Example Site - https://shop.momofuku.com/ OR https://shop.annmariegianni.com/
Category - Payment Processors / Ecommerce
Detection - look for script https://rechargeassets-bootstrapheroes-rechargeapps.netdna-ssl.com/static/js/recharge.js

**Comment by rockeynebhwani** [comment]
@AliasIO - I think it will be good to have a separate category for 'Subscriptions' types of solution. Currently, we are categorising these in 'Payment Processors' / 'Ecommerce'. What do you think? If you are OK, I can create a new category called 'Subscriptions' and categorise any relevant entries in technologies.json

**Comment by AliasIO** [comment]
I think Payment Processors is ok for these. Everything in 'Subscription' would also have to go into 'Payment Processors' so we're getting into subcategories. Companies like Stripe offer subscriptions but they wouldn't fit into the category as they do other services, too. That makes it harder to compare 'Subscription' services.
