### ISSUE TITLE
Add Open Classifieds

### ISSUE THREAD

**Issue by neo22s** [AliasIO/Wappalyzer#434]
Hello,

I am the developer of Open Classifieds, and we have more than 16.000 sites using it. let me know i you have any question.

**Comment by DaAwesomeP** [comment]
How can it be detected? Are there headers, code comments, scripts/styles loaded? The applications are detected with regex.

**Comment by neo22s** [comment]
Sure we add a header in the sites:

```
<meta name="author" content="open-classifieds.com">
```

For example. thanks

**Comment by DaAwesomeP** [comment]
Ok. That's easy. I 'll make a pull for it.

**Comment by neo22s** [comment]
Awesome! Thanks

**Comment by DaAwesomeP** [comment]
Does this fall under eCommerce, Marketing Automation, and Advertising Networks?

**Comment by DaAwesomeP** [comment]
I also found Open eShop. What categories does that fall under?

**Comment by neo22s** [comment]
Ecommerce. That would be great if you add both! Thanks

**Comment by gadcam** [comment]
@AliasIO I think you can close this issue.
