### ISSUE TITLE
Track 'Swagify'

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4346]
Vendor Site - https://swagify.com/
Example Site - https://shop.annmariegianni.com/
Category - Ecommerce / Personalisation
Detection - look for JS object 'Swagify'
                 - Look for CSS/JS loaded from domain //api.swagifyapp.com

**Comment by nurbek91** [comment]
Probably here the vendor will be different https://swagifyapp.com/
