### ISSUE TITLE
'Cookie Script' consent management detection not working in some cases

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4348]
Current Detection - 

```
    "Cookie Script": {
      "cats": [
        67
      ],
      "description": "Cookie-Script automatically scans, categorizes and adds description to all cookies found on your website.",
      "icon": "CookieScript.png",
      "scripts": "//cookie-script\\.com/s/",
      "website": "https://cookie-script.com/"
    },
```

It's not working on site - https://loox.app/

We should add a check for JS object 'CookieScript' and also make scripts check bit generic for sub-domains like 'ca-eu.cookie-script.com'

**Comment by nurbek91** [comment]
![image](https://user-images.githubusercontent.com/3456008/140640204-a611723b-312b-42d7-9ddb-1b49de6af0bb.png)
Now everything seems to be working
