### ISSUE TITLE
Track 'q4.cookieMonster' Cookie Consent/Compliance solution

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4352]
Vendor Site - https://q4mobile.github.io/q4widgets-jquery-ui/doc_html/q4.cookieMonster.html
Example Site - https://investors.bark.co/overview/default.aspx
Category - Cookie Compliance
Detection - Check for script https://widgets.q4app.com/widgets/q4.cookiemonster.0.1.5.min.js

**Comment by rockeynebhwani** [comment]
commenting to keep this issue open

**Comment by rockeynebhwani** [comment]
.

**Comment by nurbek91** [comment]
Hey @rockeynebhwani , added Q4 and one of widget Q4 Cookie Monster . But low latency and specific using area. Q4 is a investor relations websites and many widgets
