### ISSUE TITLE
Track 'Optimizely Geo-Targeting'

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4355]
Vendor Site - https://www.optimizely.com/
Example Site - https://www.onepeloton.com/
Category - 79 (Geolocation)
Detection - Check for geo2.js (Example - //cdn3.optimizely.com/js/geo2.js)

If sites having Optimizley have geo2.js loaded, this suggests that site is targeting customers based on Geolocation.

**Comment by nurbek91** [comment]
Perhaps this is one of the features related to AB testing. At least I did not see a separate product on their website that would specialize in geolocation

**Comment by rockeynebhwani** [comment]
Yes.. it's not a different product but a feature which can be detected based on JS file I mentioned
