### ISSUE TITLE
Proposal for a new category called 'Translation'

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4363]
It will be good to introduce a new category called 'Translation'. Currently we have bunch of language translation solution which are put in various categories -

Example - 
Bablic - Category for this is marked as 'Database Managers' (Category 3) and 'Hosting panels' (Category 9)
Weglot - Category for this is marked as 'Miscellaneous' (Category 19)

Having a separate category for 'Translation' will help analysing such solutions.

**Comment by AliasIO** [comment]
Let's add this. 👍
