### ISSUE TITLE
Improve 'Magento' detection

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4372]
Current Detection 

```
    "Magento": {
      "cats": [
        6
      ],
      "cookies": {
        "frontend": "\\;confidence:50"
      },
      "cpe": "cpe:/a:magento:magento",
      "description": "Magento is an open-source ecommerce platform written in PHP.",
      "html": [
        "<script [^>]+data-requiremodule=\"mage/\\;version:2",
        "<script [^>]+data-requiremodule=\"Magento_\\;version:2",
        "<script type=\"text/x-magento-init\">"
      ],
      "icon": "Magento.svg",
      "implies": [
        "PHP",
        "MySQL"
      ],
      "js": {
        "Mage": "",
        "VarienForm": ""
      },
      "magento": "Magento/([0-9.]+)\\;version:\\1",
      "oss": true,
      "scripts": [
        "js/mage",
        "skin/frontend/(?:default|(enterprise))\\;version:\\1?Enterprise:Community",
        "static/_requirejs\\;confidence:50\\;version:2"
      ],
      "website": "https://magento.com"
    },

```

Example Sites which are missing detection -
https://www.shoebacca.com/
https://www.superatv.com/

We can improve Magento discussion by looking for 'data-image-optimizing-origin' / 'data-media-backend' attribute in HTML tag -

<html lang="en" data-image-optimizing-origin="onboard" data-media-backend="https://www.superatv.com/media/">

These sites are built using Magento PWA Studio and this repo shows that how these attributes are set - https://github.com/magento/pwa-studio/search?q=data-image-optimizing-origin

BuiltWith tracks 'Magento PWA Studio' as a separate technology but I think it's also OK to extend Magento detection by adding this additional logic - https://trends.builtwith.com/shop/Magento-PWA-Studio

**Comment by nurbek91** [comment]
Magento PWA Studio merged with regular Magento
