### ISSUE TITLE
Proposal for new category to track 'Mobile Apps'

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4381]
It will be good to track if a site has Mobile apps. For example, I would like to see how many eCommerce sites also have mobile apps. 

We can track this using META tags and few other signals. Example - https://www.levi.com/GB/en_GB/

```
<meta data-vue-meta="1" name="apple-itunes-app" content="app-id=1481624020">
<meta data-vue-meta="1" name="google-play-app" content="app-id=com.levistrauss.customer">
```

We need to check for META tag with name 'apple-itunes-app' for iOS app and with name 'google-play-app' for Android app. 

@AliasIO - What do you think?

**Comment by AliasIO** [comment]
How would this appear in the extension, something like this?

> **Mobile apps**
> iOS
> Android

I think it might be confusing to mention that there is an app without linking to it.

**Comment by rockeynebhwani** [comment]
Hmm... Didn't think about that.. 

@AliasIO 

For Android apps, links are constructed like this (where 'com.levistrauss.customer' is app id from relevant META tag) - 

https://play.google.com/store/apps/details?id=com.levistrauss.customer

For iOS app, URLs have company name and app id both. Example - (1481624020 is app ID from relevant META tag) 

https://apps.apple.com/us/app/levis-shop-denim-more/id1481624020

But looks like company name is irrelevant so if you change URL to following, it will still work.

https://apps.apple.com/us/app/XXX/id1481624020

Now, I am not sure how to construct 'website' link in technologies.json using regex pattern from other attributes... Is there any way to do this?

**Comment by AliasIO** [comment]
It would have to link to the wappalyzer.com like the other technologies, where there would be a page listing websites using 'iOS' or 'Android'. It's a little weird as they're not actually technologies used by the websites. It's an interesting idea but I don't think it fits.

**Comment by rockeynebhwani** [comment]
@AliasIO  - We can also look at this in more generic way for META TAG as technology and see what type of META Tags a site is using. For example, BuiltWith tracks usage of ViewPort META - https://trends.builtwith.com/mobile/Viewport-Meta.

If we go with that approach, we will tracking usage of META tag 'apple-itunes-app' and 'google-play-app'. In terms of linking from chrome extension to a site -

- For 'apple-itunes-app, we will link to https://developer.apple.com/documentation/webkit/promoting_apps_with_smart_app_banners
- For 'google-play-app', I will have to find the relevant link

and if we are making it generic, for Viewport META, link can be https://www.w3schools.com/css/css_rwd_viewport.asp

**Comment by AliasIO** [comment]
Either way it relies on the developer including the relevant meta tags, the majority of websites that may have a mobile app may not include this. Would you still be able to get useful metrics from it?
