### ISSUE TITLE
Microsoft ASP.NET logo looks old

### ISSUE THREAD

**Issue by mohammad-hosein-shahpouri** [AliasIO/wappalyzer#4390]
**Logo Used for Microsoft ASP.NET is old and new looks like the attachment (Purple square with White Text)**

[NET_Logo.zip](https://github.com/AliasIO/wappalyzer/files/6983872/NET_Logo.zip)

**Comment by AliasIO** [comment]
Updated in 294cf33026511778ca5d79cc50b0cc5633870ed8, thanks!
