### ISSUE TITLE
Track 'Rise.ai' Gift Card solution

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4392]
Vendor Site - https://rise.ai/
Example Site - https://shopplanetblue.com/
Category - ?? @AliasIO  - which category you suggest for this? 'Payment Processors' / 'Ecommerce' ?
Detection - Check for scripts from domain 'https://strn.rise-ai.com/'
                 - Check for JS object 'Rise'

**Comment by nurbek91** [comment]
added as Loyalty&Rewards, Refferal marketing and requires Shopify
