### ISSUE TITLE
Track 'Swell Rewards' Loyalty solution

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4395]
Vendor Site - https://www.swellrewards.com/
Example Site - https://shopplanetblue.com/
Category - 84 (Loyalty & rewards)
Detection - Check for scripts loading from //cdn.swellrewards.com/
                 - Check for JS object 'swellAPI'

**Comment by nurbek91** [comment]
Updated Yotpo ,  Swell Rewards Is Now Yotpo Loyalty & Referrals
