### ISSUE TITLE
Track 'tapcart' Mobile app builder

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4396]
Vendor Site - https://tapcart.com/
Example Site - https://shopplanetblue.com/ OR https://www.gruntstyle.com/
Category - ??
Detection - 
1) look for script from domain //cdn.tapcart.com/ (Example site - https://shopplanetblue.com/)
2)  Look for link with URL having pattern 'id=co.tapcart.app'. Example url - https://play.google.com/store/apps/details?id=co.tapcart.app.id_HtQCwjEVza (Use https://www.isawitfirst.com/ as an example site for testing)
3) Look for META tag with name="tapcart-banner:appIcon" (Example site - https://vapor95.com/)

**Comment by nurbek91** [comment]
added to  miscellaneous category as agreed here #4686 and #4381 , also added required Shopify filter
