### ISSUE TITLE
Track 'Admo.tv' Advertising

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4399]
Vendor Site - https://www.pinterest.co.uk/
Example Site - https://www.admo.tv/
Category - 36 (Advertising)
Detection - Look for iFrame with id - admo-tv-d-ses

**Comment by nurbek91** [comment]
added to analytics category

**Comment by rockeynebhwani** [comment]
@nurbek91 this should be under 'Advertising' and not 'Analytics'

**Comment by nurbek91** [comment]
thanks for confirm , fixed
