### ISSUE TITLE
Track 'Ali Reviews' 

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4405]
Vendor Site - https://apps.shopify.com/ali-reviews
Example Site - https://anlan-brows.com/ OR https://knightswatchlondon.com/
Category - 90 (Reviews)
Detection - Check for JS object 'alireviews_tags'

**Comment by noodles** [comment]
168 x 168 image

![Ali Reviews](https://user-images.githubusercontent.com/183972/129858680-c8438dcd-6e7e-4db6-b8f3-c39a938a0adc.png)

https://cdn.shopify.com/app-store/listing_images/1ff5e1954776a87c29b55388172a662f/icon/CJWp5KK2r/ACEAE=.png?height=168&width=168
