### ISSUE TITLE
Improve 'Algolia' detection

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4413]
Current Detection - 

```
    "Algolia": {
      "cats": [
        29
      ],
      "description": "Algolia offers a hosted web search product delivering real-time results.",
      "icon": "Algolia.svg",
      "js": {
        "AlgoliaSearch": "",
        "__algolia": "",
        "algoliasearch.version": "^(.+)$\\;version:\\1"
      },
      "pricing": [
        "freemium",
        "payg"
      ],
      "saas": true,
      "website": "http://www.algolia.com"
    },
```

Site where it's not being detected - https://shop.coop.co.uk/

If you look at the Content-Security-Policy header for this, you will see various Algolia domains (*.algolia.io *.algolia.net *.algolianet.com)

`child-src blob:; connect-src 'self' *.algolia.io *.algolia.net *.algolianet.com *.api.coop.co.uk *.autoaddress.ie *.contentsquare.net *.demdex.net *.doorbell.io *.doubleclick.net *.foodieservices.com *.google-analytics.com *.oppwa.com *.optimizely.com api.coop.co.uk api.preprod.shop.coop.co.uk api.rollbar.com api.shop.coop.co.uk cdn.contentful.com cooperativegroup.tt.omtrdc.net doorbell.io euw-development-ecom-apim.azure-api.net euw-preprod-ecom-apim.azure-api.net euw-production-ecom-apim.azure-api.net oppwa.com the.sciencebehindecommerce.com www.facebook.com; default-src 'self'; font-src 'self' data: assets.digital.coop.co.uk irresistible.coop.co.uk; form-action 'self' *.oppwa.com oppwa.com; frame-src 'self' *; img-src 'self' data: *.adnxs.com *.awin1.com *.blob.core.windows.net *.contentsquare.net *.ensighten.com *.facebook.com *.google.co.uk *.google.com *.oppwa.com *.zenaps.com cdn.commerce.coop.co.uk cdn.test.commerce.coop.co.uk cm.everesttech.net csi.gstatic.com cx.atdmt.com dpm.demdex.net images.contentful.com images.ctfassets.net insight.adsrvr.org oppwa.com rt-1-dv-euw-retailapis-end-01.azureedge.net rt-1-pr-euw-retailapis-end-01.azureedge.net stats.g.doubleclick.net www.google-analytics.com; report-to default; script-src 'self' 'unsafe-inline' 'unsafe-eval' *.awin1.com *.doorbell.io *.ensighten.com *.facebook.net *.google-analytics.com *.googleapis.com *.oppwa.com *.optimizely.com *.smartsurvey.co.uk *.zenaps.com app.contentsquare.com assets.adobedtm.com ci-mpsnare.iovation.com contentsquare.com js.adsrvr.org mpsnare.iesnare.com oppwa.com t.contentsquare.net the.sciencebehindecommerce.com www.dwin1.com; style-src 'self' 'unsafe-inline' *.doorbell.io *.oppwa.com oppwa.com; worker-src blob:;
`

@AliasIO  - Can we add check using Content-Security-Policy? I don't see any examples like this in technologies.json

**Comment by AliasIO** [comment]
Yes we can, it's just a header.

**Comment by rockeynebhwani** [comment]
Adding more examples where detection is not working - 
- https://www.lacoste.com/gb/#query=top
- https://uk.loccitane.com/

**Comment by nurbek91** [comment]
@AliasIO If I understand correctly, this header is generated manually and the list in some cases may no longer be relevant?
After your confirmation, I can go through all the technologies and add headers where this moment would be skipped.

**Comment by AliasIO** [comment]
@nurbek91 I'm not sure I understand you correctly but yes, the CSP header is added by the website owner. We can update some up the technologies to use this header. Here's the CSP header for wappalyzer.com, where you can see things like Google Ads, GTM, Stripe, AWS, Vimeo, LinkedIn, reCAPTCHA and UptimeRobot. I'm actually no longer using LinkedIn but it's still in the CSP header. So using this header can result in incorrect detections sometimes but I think it's safe enough to use.

`default-src  'self'; style-src 'self' 'unsafe-inline' *.gstatic.com *.crisp.chat;  img-src 'self' data: *.linkedin.com *.google-analytics.com  *.googletagmanager.com *.doubleclick.net *.crisp.chat *.google.com  [...] *.google-analytics.com  *.googletagmanager.com *.doubleclick.net *.stripe.com *.wappalyzer.com  *.amazonaws.com *.uptimerobot.com wss://*.crisp.chat; worker-src 'none';  object-src 'none'; form-action 'self'; frame-ancestors 'none';  frame-src *.recaptcha.net *.stripe.com *.crisp.chat *.vimeo.com  *.google.com; media-src 'self' *.crisp.chat; font-src 'self'  *.crisp.chat`

**Comment by nurbek91** [comment]
@AliasIO Can be closed.
