### ISSUE TITLE
json error

### ISSUE THREAD

**Issue by ruNickStone** [AliasIO/wappalyzer#4419]
"Apple Pay": {
      "cats": [
        41
      ],
      "description": "Apple Pay is a mobile payment and digital wallet service by Apple that allows users to make payments in person, in iOS apps, and on the web.",
      "dom": [ "[aria-labelledby='pi-apple_pay']**"**, script#apple-pay" ],
      "icon": "Apple.svg",
      "js": {
        "ApplePay": "",
        "enableApplePay": "",
        "dw.applepay": ""
      },
      "website": "https://www.apple.com/apple-pay"
    },

invalid dom value.

**Comment by AliasIO** [comment]
Fixed, thanks!
