### ISSUE TITLE
Proposal for a new category 'Buy Now Pay Later'

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4422]
Buy Now Pay Later is a fast growing segment at the moment. It will be good to track 'BNPL' solutions under a single category. We currently have some solutions which we are tracking under generic payment processor category (e.g. Klarna / AfterPay). It will be good to move such solutions to this new category and add more... As of now, we have following open issues to track new BNPL solutions and across the globe there are many such solutions... 

Tabby - https://github.com/AliasIO/wappalyzer/issues/4293
Sezzle - https://github.com/AliasIO/wappalyzer/issues/4286
Payl8r - https://github.com/AliasIO/wappalyzer/issues/4280

@AliasIO  - What do you think?

**Comment by AliasIO** [comment]
Sure, we can add that in as 'Buy now pay later'. I'd still keep any technologies in this category in 'Payment processors' as well.
