### ISSUE TITLE
Github Technology Request' issue template links to a page that no longer exists

### ISSUE THREAD

**Issue by noodles** [AliasIO/wappalyzer#4424]
**Platform**
Which platform does the bug apply to?
* Github

**Describe the bug**
The 'Technology Request' issue template links to a page that no longer exists

**To Reproduce**
1. Open a new [Technology Request Issue](https://github.com/AliasIO/wappalyzer/issues/new?assignees=&labels=Technology+request&template=technology-request.md&title=)
2. The template text is as follows:

> You may request a new technology to be added but changes of having it included are greatly improved if you submit a pull request. Please refer to the [documentation](https://docs.wappalyzer.com/dev/contributing.html#adding-a-new-application).

3. Click on the [link](https://docs.wappalyzer.com/dev/contributing.html#adding-a-new-application) and get a 404 error. 

**Expected behavior**
Link should point to contribution relevant section on GitHub hosted page.

This:
https://github.com/AliasIO/wappalyzer/issues/new?assignees=&labels=Technology+request&template=technology-request.md&title=

Instead of:
https://docs.wappalyzer.com/dev/contributing.html#adding-a-new-application

**Additional context**
N/A

**Comment by AliasIO** [comment]
Fixed in a2439f314f825b30844327a04dca77f0a37b4bce, thanks!
