### ISSUE TITLE
Track 'Adalyser'

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4438]
Vendor Site - https://adalyser.com/
Example Site - https://www.isawitfirst.com/
Category - 36 (Advertising)
Detection - Look for script //c5.adalyser.com/adalyser-tracking-tag-v2.js 
                 - Look  for JS object 'adalyserModules'

**Comment by RomainClem** [comment]
I think there migh be an issue here, Wappalyzer detects Wheelio almost everywhere.

**Comment by rockeynebhwani** [comment]
@RomainClem  - Wheelio issue has been fixed in https://github.com/AliasIO/wappalyzer/issues/4550. New chrome extension version is yet to be released.

**Comment by RomainClem** [comment]
Very nice!
