### ISSUE TITLE
Track 'Uploadcare' widget

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4443]
Vendor Site - https://uploadcare.com/
Example Site - https://www.damart.co.uk/
Category - 5 (Widgets)
Detection - Check for script JS object 'uploadcare'

**Comment by nurbek91** [comment]
Some sites use this service's widget. Some sites use it as a СDN.
Since in pricing these two services are not separated from each other. After some thought, I added it to the IaaS category.
Also, when identifying by an extension, users may not see the widget.

**Comment by AliasIO** [comment]
@nurbek91 I think CDN may be more appropriate. IaaS is for things like AWS, Google Cloud and Azure.
