### ISSUE TITLE
Track 'AURYC'

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4485]
Vendor Site - https://www.auryc.com/
Example Sites - https://www.auryc.com/ OR https://vacations.united.com/
Category - 73 (Surveys)
Detection - Look for <div id="auryc-feedback-tab"

**Comment by nurbek91** [comment]
Hey @rockeynebhwani  , added as analytics tool , what do you think of the  Conversion rate optimization, or CRO category
