### ISSUE TITLE
Check the response headers of all requests linked to the main request

### ISSUE THREAD

**Issue by kevinfarrugia** [AliasIO/wappalyzer#4516]
**Is your feature request related to a problem? Please describe.**
Currently, wappalyzer only checks for response headers on the main request, but in some cases the response header is included in the response of a static file or possibly XHR request.

**Describe the solution you'd like**
Wappalyzer would check the response headers of all assets, files or XHR requested as part of the initial load.

**Describe alternatives you've considered**
Currently it is possible to check the response headers of a static asset by using that as the main request instead of the website. For example, you would use example.com/main.js instead of example.com as the URL, however this will omit any information which is associated with the domain and isn't a viable workaround.

**Additional context**
An example of a service which doesn't include headers on the main request but includes them on JavaScript and/or CSS files is [Akamai Resource Optimizer](https://developer.akamai.com/ion/adaptive-acceleration#resource-optimizer-automatically-optimize-website-resources) which is recognisable using
```json
      "headers": {
        "server": "^Akamai Resource Optimizer$"
      },
```

**Sample entry in technologies.json**
```json
    "Akamai Resource Analyzer": {
      "cats": [19],
      "headers": {
        "server": "^Akamai Resource Optimizer$"
      },
      "description": "Resource Optimizer leverages Zopfli and Brotli to automatically compress, cache, and deliver these files.",
      "icon": "akamai.svg",
      "implies": "Akamai",
      "pricing": ["poa"],
      "saas": true,
      "website": "https://developer.akamai.com/ion/adaptive-acceleration#resource-optimizer-automatically-optimize-website-resources"
    },
```

---

@AliasIO Do you think such a feature is possible or was it intentionally omitted? 

If you would like, I am able to take a look and create a PR if I find a solution.

**Comment by AliasIO** [comment]
We don't scan every request for performance reasons. We're probably running about 10K tests and doing this several times per page would be wasteful. We do look for hostnames in XHR requests but everything else happens during the initial request and on the page itself.
