### ISSUE TITLE
Clarify what accessibility overlays can do

### ISSUE THREAD

**Issue by mgifford** [AliasIO/wappalyzer#4521]
**Is your feature request related to a problem? Please describe.**
There's a lot of sales hype behind a lot of accessibility overlays.  These are JavaScript widgets that often claim to make the sites that use them accessible. Unfortunately, this isn't really possible.  You can see a good comparison of the reality vs the claims here https://overlayfactsheet.com

**Describe the solution you'd like**
Well, this https://github.com/AliasIO/wappalyzer/pull/4520

Essentially, I'd like them all to be described as being accessibility overlays and I would like to make sure that there are claims around accessibility. These widgets do help some people with disabilities but hurt others, so just trying to make sure that these claims are identified as such.

**Comment by AliasIO** [comment]
Merged, thanks Mike!
