### ISSUE TITLE
New Category for 'Website acceleration' technologies

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4527]
@AliasIO - I am proposing to add a new category for services/libraries which claims to help with improving the website speed. 

Here are some examples where I have raised issues but I don't have an appropriate category to use (apart from 'Miscellaneous') 

![image](https://user-images.githubusercontent.com/1718757/131420502-2f4b8223-0ae1-4345-bd48-52fe859dd7a6.png)

In addition to this, solutions like 'quicklink' and 'Instant.page' can also help with improving the perception of website speed. We have issues open for these also.. 

https://github.com/AliasIO/wappalyzer/issues/4331
https://github.com/AliasIO/wappalyzer/issues/4332

What do you think?

**Comment by AliasIO** [comment]
Sounds good. Maybe be a generic 'Performance' category?

**Comment by rockeynebhwani** [comment]
Sure.. We can go with the name 'Performance' for this. I will work on PR for this soon.
