### ISSUE TITLE
core-js versions detection

### ISSUE THREAD

**Issue by zloirock** [AliasIO/wappalyzer#4547]
In #4505 was fixed detection of `core-js` on sites. Now I see that the Chrome extension in the store updated and properly detect the existence of `core-js` on sites. However, seems it does not detect `core-js` version from `__core-js_shared__`.

![image](https://user-images.githubusercontent.com/2213682/131798007-14b7384b-b257-4f51-86fe-c7582f44cf6d.png)

@AliasIO are you sure that it should be `__core-js_shared__.versions[0].version`, not `__core-js_shared__.versions.0.version`?

**Comment by AliasIO** [comment]
You're right, it should be `__core-js_shared__.versions.0.version`. I'll push an update shortly.

Is there a different icon you'd like to use?

**Comment by zloirock** [comment]
> Is there a different icon you'd like to use?

Thanks, not now. I'll add a PR when it will be required.
