### ISSUE TITLE
Wheelio is always detected

### ISSUE THREAD

**Issue by AlexzanDev** [AliasIO/wappalyzer#4550]
**Platform**
Which platform does the bug apply to?
* WebExtension (Google Chrome, Mozilla Firefox)

**Describe the bug**
Wheelio is always detected, in every website.

**To Reproduce**
1. Visit a website that doesn't have Wheelio (ex. Google)

**Expected behavior**
Wheelio shouldn't be detected by Wappalyzer where is not available.

**Additional context**
Looking at the [`src/technologies.json`](https://github.com/AliasIO/wappalyzer/blob/master/src/technologies.json#L25058) file I noticed that Wappalyzer searches for the domain _wheelio.azureedge.net_, which doesn't exist. Instead, the Wheelio website fetches its script from the following domain: _wheelioapp.azureedge.net_. Is the software being always detected because the domain cannot be found?

**Comment by rockeynebhwani** [comment]
@AlexzanDev  - I am not seeing this on www.google.com. Can you please provide a screenshot and also the extension version which you have in your browser?

**Comment by bobbyshaw** [comment]
I have noticed this today as well. I was able to confirm experiencing it on a wide range of domains including www.google.com

If I had to guess, I think it's because signature looks for the existence of a "WheelEvent" js function when this is a native browser function (https://developer.mozilla.org/en-US/docs/Web/API/WheelEvent/WheelEvent).  

![Screenshot 2021-09-02 at 12 56 59](https://user-images.githubusercontent.com/553566/131839650-a78a2546-ccd7-43ef-9c97-98889d893fb4.png)
![Screenshot 2021-09-02 at 12 57 10](https://user-images.githubusercontent.com/553566/131839657-8e6df4c3-cec0-4159-aebf-ed51fc416c76.png)

**Comment by AlexzanDev** [comment]
> @AlexzanDev - I am not seeing this on [www.google.com](http://www.google.com). Can you please provide a screenshot and also the extension version which you have in your browser?

Yes, you can check it out below. Also, Wappalyzer version is the latest one, 6.8.3 (I redownloaded it from the Chrome Web Store this morning). GitHub too (as an example). Note: I already cleared Wappalyzer cache and I don't cache detections.

![Google](https://user-images.githubusercontent.com/35893655/131840692-f5557315-05db-432a-948c-7af4797c3fd6.png)
![GitHub](https://user-images.githubusercontent.com/35893655/131840610-84d5a0e7-9949-4a17-9747-6388680c3c42.png)

---

> I have noticed this today as well. I was able to confirm experiencing it on a wide range of domains including [www.google.com](http://www.google.com)
> 
> If I had to guess, I think it's because signature looks for the existence of a "WheelEvent" js function when this is a native browser function (https://developer.mozilla.org/en-US/docs/Web/API/WheelEvent/WheelEvent).
> 
> ![Screenshot 2021-09-02 at 12 56 59](https://user-images.githubusercontent.com/553566/131839650-a78a2546-ccd7-43ef-9c97-98889d893fb4.png)
> ![Screenshot 2021-09-02 at 12 57 10](https://user-images.githubusercontent.com/553566/131839657-8e6df4c3-cec0-4159-aebf-ed51fc416c76.png)

It might also be this, it's not to exclude.

**Comment by rockeynebhwani** [comment]
Thanks @bobbyshaw. Yes, it's due to wheelevent. My bad.. I didn't realise that this was generic event.. I will get it fixed.

**Comment by AlexzanDev** [comment]
@rockeynebhwani Thanks for the quick fix! Also thanks to @bobbyshaw, I didn't notice the WheelEvent check!

**Comment by rockeynebhwani** [comment]
@AlexzanDev - This has been merged. You can go ahead and close this.
