### ISSUE TITLE
Wheelio false positives

### ISSUE THREAD

**Issue by mxrch** [AliasIO/wappalyzer#4565]
**Platform**
Which platform does the bug apply to?
* WebExtension (Google Chrome, Mozilla Firefox)

**Describe the bug**
The widget Wheelio appears to be used on **every** site.

**To Reproduce**
1. Go on every sites (github.com, gmail.com, google.com, realpython.com, every sites)
2. Click on Wappalyzer

**Expected behavior**
I don't know so much about Wheelio but I doubt that it is used on all the internet, so the expectation is that it shouldn't appear on all sites.

**Comment by rockeynebhwani** [comment]
@mxrch - Thanks for raising this. This has been addressed as part of https://github.com/AliasIO/wappalyzer/issues/4550.
