### ISSUE TITLE
detect react correctly

### ISSUE THREAD

**Issue by gotjoshua** [AliasIO/wappalyzer#4588]
**Platform**
* WebExtension (Google Chrome, Mozilla Firefox)

**Describe the bug**
https://app.step.finance/#/dashboard uses React, but it does not show up in the wappalyzer extension

**To Reproduce**
1. Go to https://app.step.finance/#/dashboard
2. Click on the extension icon
3. notice lack of react
4. go to inspect the page and see that react dev tools are active

**Expected behavior**
show react

**Comment by AliasIO** [comment]
Fixed in ff3284e81dcf2b4438d9f3148672fa2dabc5cf5a, thanks!
