### ISSUE TITLE
Incorrect WordPress version detection for certain generator tags

### ISSUE THREAD

**Issue by gpoetzelsberger** [AliasIO/wappalyzer#4593]
A generator meta tag like

`<meta name="generator" content="WordPress.com">`

is detected as WordPress version ".". 
The generator tag seems to be used on sites hosted at wordpress.org

example site: https://blog.mbbka.org.uk/

**Comment by AliasIO** [comment]
Fixed in 57fe916762d3de65db501e07cb92705d936622cf, thanks!
