### ISSUE TITLE
Periodic appears in many websites  

### ISSUE THREAD

**Issue by mufidu** [AliasIO/wappalyzer#4594]
**Platform**
Which platform does the bug apply to?
* WebExtension (Google Chrome, Mozilla Firefox)

**Describe the bug**
Well, I don't think that [Google](https://google.com), [GitHub](https://github.com), [my website](https://mufidu.com), and many others use [Periodic](https://periodic.is/) on their site.

**To Reproduce**
1. Go to [Google](https://google.com), [GitHub](https://github.com), and other websites
2. Wait for a second
3. See Periodic appears in the extension.

**Comment by rockeynebhwani** [comment]
Thanks for reporting the issue. Create a PR for the fix.
