### ISSUE TITLE
Technology comparison pages returning 400 error

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4611]
@AliasIO  - I noticed that comparison pages for technologies are not working. 

Example URL - https://www.wappalyzer.com/compare/vtex-vs-shopify/

![image](https://user-images.githubusercontent.com/1718757/132990574-5805023a-0c90-4277-a357-bbc197d3707c.png)

**Comment by AliasIO** [comment]
Fixed, thank you.
