### ISSUE TITLE
Rename 'Preact' to 'Preact Helment'

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4643]
Currently we are tracking Preact using following 

```
  "Preact": {
    "cats": [
      59
    ],
    "description": "Preact is a JavaScript library that describes itself as a fast 3kB alternative to React with the same ES6 API.",
    "dom": "meta[data-preact-helmet='true']",
    "icon": "Preact.svg",
    "oss": true,
    "website": "https://preactjs.com"
  },
```

Better categorisation for this should be under 'JavaScript Libraries' with name 'Preact Helmet' as presence of data-preact-helmet META signifies the library 'Preact Helmet' and not the Preact framework itself. 

See thread - https://twitter.com/_developit/status/1438513651426553872

**Comment by AliasIO** [comment]
Fixed in #4644.
