### ISSUE TITLE
Track 'Astro'

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4645]
Vendor Site - https://astro.build/
Example Site - https://backlight.dev/ AND https://astro.build/
Category - 18 (Web frameworks)
Detection - These sites seem to have CSS with href path `/_astro/index-*.css`

Example - 
`<link rel="stylesheet" href="/_astro/index-1UfqC.css" type="text/css">`

**Comment by natemoo-re** [comment]
👋 Astro maintainer here!

I think the `/_astro` resource path might be going away, but we could certainly add a `<!-- Built with Astro -->` comment or a meta tag or something similar. I will bring it up to the team.

**Comment by AliasIO** [comment]
@natemoo-re I'm seeing some `astro-` class names and an `astro-root` element. Are they common? Could you provide more example of websites that use it?

Adding in a `generator` meta tag would be ideal, if possible.
