### ISSUE TITLE
Netlify detection is not working

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4665]
Example site - https://lifeandstyle.asda.com/

Please check why this is not working. This site has relevant headers.

**Comment by AliasIO** [comment]
It works for me in v6.8.14.

**Comment by kyletaylored** [comment]
Can also confirm it works for me.

![image](https://user-images.githubusercontent.com/1759794/134616816-1caadb59-d854-4932-a90f-14dc336b44ba.png)
