### ISSUE TITLE
Track 'Ookla Speedtest Custom'

### ISSUE THREAD

**Issue by John4266** [AliasIO/wappalyzer#4669]
Vendor Site - https://www.ookla.com/speedtest-custom
Example Sites:
https://www.att.com/support/speedtest/
https://www.hot.net.il/heb/Internet/speed/
https://www.bezeq.co.il/internetandphone/internet/speedtest/
https://www.partner.co.il/globalassets/global/speedcheck/index.html/
https://cellcom.co.il/production/Private/Internet/speedtest/
https://www.tpx.com/resources/bandwidth-speed-test/
https://www.pelephone.co.il/digitalsite/heb/support/general_info/pelephone-speed1/speedtest/
https://www.ccc.co.il/%D7%91%D7%93%D7%99%D7%A7%D7%AA-%D7%9E%D7%94%D7%99%D7%A8%D7%95%D7%AA/
Category - Widgets
Detection - Look for External JS imported from `https://c.speedtestcustom.com/static/js/testBundle.js?v=1638295285026`

**Comment by John4266** [comment]
i think this can go to Widgets category.
And i also found: https://www.meter.net/web-plugin/
which can also be embedded in a custom website.

**Comment by nurbek91** [comment]
.

**Comment by John4266** [comment]
@nurbek91 I've just updated the example with info on detection.

**Comment by John4266** [comment]
Hey @nurbek91 do you think you could implement this?

**Comment by nurbek91** [comment]
Hey @John4266 , I'll look again today, it seems there were very few active links last time

**Comment by nurbek91** [comment]
Hey @AliasIO , can be closed.

**Comment by John4266** [comment]
Thanks
