### ISSUE TITLE
Track 'HighStreet' Mobile app builder

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4686]
Vendor Site - https://www.highstreetmobile.com/
Example Site - https://www.vila.com/gb/en/home  OR https://www.jackjones.com/gb/en/home
Detection - Check for script from domain '//*.api.highstreetapp.com/'
- Check for JS object 'highstreetBanner'

**Comment by nurbek91** [comment]
https://www.g-star.com/en_gb/shop/jackets_and_blazers

**Comment by nurbek91** [comment]
Hey @rockeynebhwani  So far I have added examples. Help what category can that technology be attributed

**examples:**
https://www.g-star.com/en_gb/shop/jackets_and_blazers
https://www.vince.com/
https://www.ladress.com/en/home/
https://www.boutiquestories.com/
https://www.nydj.eu/

**Comment by rockeynebhwani** [comment]
@nurbek91 - I suggest that you go with 'Miscellaneous' for now. I have another issue open with respect to mobile apps here - https://github.com/AliasIO/wappalyzer/issues/4381. Though this doesn't fit in that category, my suggestion will be add such stuff in 'Miscellaneous' for now and take a call in future if having a separate category makes sense or not.

**Comment by nurbek91** [comment]
@rockeynebhwani thanks!!!
