### ISSUE TITLE
Track 'Partytown'

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4688]
Vendor Site - https://github.com/BuilderIO/partytown
Example Site - ??
Category - Performance
Detection - Check for script 'https://unpkg.com/browse/@builder.io/partytown@0.0.3/lib/'

**Comment by nurbek91** [comment]
Hey there , cant find examples like you  ; )

**Comment by nurbek91** [comment]
.

**Comment by rockeynebhwani** [comment]
@nurbek91  - This page is now using Partytown - https://www.builder.io/. You can see 'partytown' JS object

**Comment by nurbek91** [comment]
added , thanks!
