### ISSUE TITLE
"Re:amaze" dev issue

### ISSUE THREAD

**Issue by kingthorin** [AliasIO/wappalyzer#4696]
The icon entry for "re:amaze" is problematic for WIndows developers:
```
error: invalid path 'src/drivers/webextension/images/icons/Re:amaze.png'
```

https://github.com/AliasIO/wappalyzer/blob/master/src/technologies/r.json#L301-L317

I'm not sure if similar issues have come up before. I understand that the product or company does actually have a colon in it's name. However I'd suggest dropping it from all elements (it's not as if it exists in their DNS entries).

**Comment by AliasIO** [comment]
What do you mean by the last line? Renaming the icon should be sufficient, right?

**Comment by kingthorin** [comment]
Doesn’t the icon file name need to match the product name?

**Comment by kingthorin** [comment]
I could be assuming a relationship where there isn’t one.

**Comment by AliasIO** [comment]
It used to be a long time ago, we have an `icon` field now. Fixed here:

https://github.com/AliasIO/wappalyzer/blob/master/src/technologies/r.json#L301
