### ISSUE TITLE
Vimeo is not detected

### ISSUE THREAD

**Issue by John4266** [AliasIO/wappalyzer#4705]
**Platform**
Which platform does the bug apply to?
* WebExtension (Mozilla Firefox)

**Describe the bug**
Wappalyzer doesn't detect Vimeo video player in the following site: https://www.christophercarlone.com/

**To Reproduce**
1. Go to https://www.christophercarlone.com/
2. Open Wappalyzer
3. Look for Vimeo and see it isn't found.

**Expected behavior**
Wappalyzer should detect Vimeo

**Comment by AliasIO** [comment]
Fixed in 9220a20791a69861dd998db568dfbbc381df2a77, thanks!
