### ISSUE TITLE
Wrong JSON

### ISSUE THREAD

**Issue by 0xcrypto** [AliasIO/wappalyzer#4706]
I was importing these json files in firebase and found the json is wrong in z.json file: 

https://github.com/AliasIO/wappalyzer/blob/c39b10a06718bc5e2dd1affa8d7bfb96b31d3a3a/src/technologies/z.json#L372

**Comment by AliasIO** [comment]
Fixed in 32194e88d77f71d695e6121608628252e3aedc89, thanks!
