### ISSUE TITLE
Track 'Truefit'

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4733]
Vendor Site - https://www.truefit.com/en/Home
Example Sites - https://www.shoecarnival.com/kids_nike_little_kid_air_max_sc_swoosh_sneakers/116442.html
Category - Personalisation
Detection - Look for script from domain '//cdn.truefitcorp.com/'

**Comment by nurbek91** [comment]
@rockeynebhwani Hey there 
Vendor's site is not this by chance ?? https://www.truefit.com/en/Home

**Comment by nurbek91** [comment]
examples
https://www.landsend.com/
https://www.shoecarnival.com/
https://warpweftworld.com/

**Comment by nurbek91** [comment]
@rockeynebhwani understood the vendor here just from the previous request. All OK

**Comment by rockeynebhwani** [comment]
Thanks @nurbek91 .. Copy / paste error on my part...
