### ISSUE TITLE
Wappalyzer does not identify Typo 3 versions

### ISSUE THREAD

**Issue by tarraschk** [AliasIO/wappalyzer#4740]
**Platform**
Which platform does the bug apply to?
* WebExtension
* NPM

**Describe the bug**

Typo3 version is not properly detected on modern Typo3 deployments.

However, other solutions such as https://github.com/whoot/Typo3Scan can identify properly the Typo3 version of these websites.

This has been observed on Typo3 deployments version 4.5.25 and 10.X.

**To Reproduce**

1. Make a Typo3 analysis with the WebExtension, or with the CLI, on the following websites:
  - https://typo3.org/
  - https://typo3.fr/
2. Observe that WappAlyzer detects the Typo3 CMS, but not its version.
3. Run Typo3Scan on the same targets, observe that it finds their version.

**Expected behavior**

Identification of the Typo 3 versions.

**Additional context**

It seems that Wappalyzer identifies the Typoe 3 CMS, but does not identify properly the Typo 3 CMS versions on at least Typo 3 v4.5.25 and Typo 3 v10.X.

**Comment by AliasIO** [comment]
We may be able to add it detection for the major version number (e.g. 10 vs 11) but not as granular as what Typo3Scan is doing. They perform a very deep and specialised scan whereas we take a more general approach. If you have any examples of TYPO3 sites using different versions and pointers of what differences to look for, I'd be happy to add that in.
