### ISSUE TITLE
Support Government Design Systems like the USA's USWDS

### ISSUE THREAD

**Issue by mgifford** [AliasIO/wappalyzer#4749]
There are a bunch of government design systems. It would be useful to have them included here for those who are using them inside & outside of government. The [U.S. Web Design System (USWDS)](https://designsystem.digital.gov/) is used in [quite a few .gov sites](https://designsystem.digital.gov/getting-started/showcase/all/).

[USWDS stats from Builtwith.com](https://trends.builtwith.com/javascript/USWDS)

I didn't get a definitive response on the cookies from [https://sitechecker.pro/cookie-checker](https://sitechecker.pro/cookie-checker/?url=https%3A%2F%2Fdesignsystem.digital.gov%2F&f4xDur6SBquTACQg=8588e0d83b&_wp_http_referer=%2Fcookie-checker%2F)

I'm not entirely sure how to do this for the USWDS, but I'm guessing something like:

```
"USWDS": {
  "description": "A design system for the US federal government. Designed to make it easier to build accessible, mobile-friendly government websites.",
  "cats": [
    "1"
  ],
  "cookies": {
    "cookie_name": ""
  },
  "dom": {
    "#example-id": {
      "exists": "gov-banner",
      "exists": "nav-components",
      "attributes": {
        "class": "usa-nav__submenu",
        "class": "usa-graphic-list",
      },
      "properties": {
        "example-property": ""
      },
      "text": ""
    }
  },
  "dns": {
    "MX": [
      ".gov"
    ]
  },
  "js": {
    "Example.method": "/assets/js/vendor/uswds.min.js"
  },
  "excludes": "",
  "html": "<link rel="stylesheet" href="/assets/css/styles.css">",
  "url": "edesignsystem.digital.gov",
  "oss": true,
  "pricing": ["open source"],
  "website": "https://designsystem.digital.gov/",
}
```

What else do I need to do to get this included?

**Comment by AliasIO** [comment]
Added in 07d5739a94b303fd176a15546a850fb957bc2975, thanks!
