### ISSUE TITLE
menu not showing on correct screen

### ISSUE THREAD

**Issue by He1my** [AliasIO/Wappalyzer#478]
as can be seen from the attached screen shoot the wappalyzer menu is showing on the left edge of the second screen there, it is not on the correct primary screen as it should,
this happens when Firefox is maximized
![wappalyzer1](https://f.cloud.github.com/assets/5511583/2494947/b20ead66-b2de-11e3-8ba7-be9be8f5a895.jpeg)

**Comment by robme** [comment]
I'm experiencing this too. I have a dual monitor setup with a resolution of 1920x1080 (3840x1080 for both).

The Firefox window doesn't have to be maximised. It seems that if it is 1452* pixels wide or below, then Wappalyzer appears inside the Firefox window, but at 1453 pixels and above it goes to the far left of the other monitor.

<sup>*measured with jQuery(window).width(). The full width of the Firefox window including borders is 1467 pixels.</sup>

**Comment by Rewt0r** [comment]
I'm also experiencing this, even when I don't have a second monitor plugged in but have previously it keeps opening on the side.
