### ISSUE TITLE
This website hangs indefinitely: https://nugnes1920.com/

### ISSUE THREAD

**Issue by Overload119** [AliasIO/wappalyzer#4828]
**Platform**
Which platform does the bug apply to?
* Website

**Describe the bug**
Hanging.

**To Reproduce**
node src/drivers/npm/cli.js "https://nugnes1920.com/"

**Expected behavior**

**Additional context**

**Comment by AliasIO** [comment]
Hey, thanks! I disabled the PayPal link because it can't be used anonymously. You can send me a tip here:

https://www.buymeacoffee.com/aliasio
