### ISSUE TITLE
Non-Sitecore sites being misrepresented as Sitecore

### ISSUE THREAD

**Issue by owebboy** [AliasIO/wappalyzer#4847]
**Platform**
Which platform does the bug apply to?
- WebExtension (Google Chrome, Mozilla Firefox)

**Describe the bug**
Sitecore utilizes SC_ANALYTICS_GLOBAL_COOKIE to track user interaction between other sites. This cookie's scope can be set for all subdomains, even if the subdomain isn't a sitecore site. So, for the web extension, this cookie will be set for all web properties within a domain, be it a sitecore site or not. This would only occur in environments where cookies are being saved from site to site.

**To Reproduce**
1. Check cookie for msu.edu, see that SC_ANALYTICS_GLOBAL_COOKIE is set on the .msu.edu domain (Is a sitecore site)
2. Check cookie for tech.msu.edu, see that SC_ANALYTICS_GLOBAL_COOKIE is set on the .msu.edu domain (Not a sitecore site)

**Expected behavior**
- msu.edu should be seen as a Sitecore site.
- tech.msu.edu should not be seen as a Sitecore site.

**Comment by nurbek91** [comment]
@AliasIO ,Can be closed if everything is correct after merge.  Removed false positives through `requires` field.

**Comment by AliasIO** [comment]
Thanks!

**Comment by owebboy** [comment]
Thank you!
