### ISSUE TITLE
Inconsistent "scriptSrc" value type

### ISSUE THREAD

**Issue by CaledoniaProject** [AliasIO/wappalyzer#4879]
I just found out `scriptSrc` is not always an array of string

```
  "Act-On": {
    "scriptSrc": "/cdnr/\\d+/acton/bn/tracker/\\d+",
  },

  "Acquia Customer Data Platform": {
    ...
    "scriptSrc": [
      "^https?:\\/\\/.+\\.agilone\\.com",
      "^https?:\\/\\/scripts\\.agilone\\.com\\/latest\\/a1.js"
    ],
  },
``` 

Is it by design? This make it impossible to decode in golang

**Comment by CaledoniaProject** [comment]
Looks like almost every field has the same issue, can you change all of them to array instead?

**Comment by AliasIO** [comment]
It's by design and [documented](https://github.com/AliasIO/wappalyzer/blob/master/README.md), all patterns are either an object, or a string/array. Internally all strings are [transformed](https://github.com/AliasIO/wappalyzer/blob/master/src/wappalyzer.js#L389) to arrays.

**Comment by CaledoniaProject** [comment]
Thanks
