### ISSUE TITLE
Ember v4 not identified 

### ISSUE THREAD

**Issue by NullVoxPopuli** [AliasIO/wappalyzer#4881]
**Platform**
Which platform does the bug apply to?
* Website

I've only tested this on the website, but I assume the problem is e anywhere.

**Describe the bug**

Visit : https://www.wappalyzer.com/lookup/limber.glimdown.com

Observe: ember.js is not mentioned.

**Expected behavior**
Ember is identified as a technology used

**Additional context**
Here is the repo if you want to take a look:
https://github.com/NullVoxPopuli/limber/tree/main/frontend

**Comment by NullVoxPopuli** [comment]
thanks!!!!

**Comment by AliasIO** [comment]
It won't update for several weeks. A release needs to happen first and then gradually all data will be updated.
