### ISSUE TITLE
yarn run validate throws a warning

### ISSUE THREAD

**Issue by AbhinavS96** [AliasIO/wappalyzer#5024]
**Platform**
Which platform does the bug apply to?
* NPM

**Describe the bug**
yarn run validate throws a warning "WARN ENOENT: no such file or directory, stat './src/technologies/*.json'"

**To Reproduce**
just run: yarn run validate

Seems like jsonlint -qV ./src/technologies/*.json is looking for a strict match *.json than a regex match looping through all the json files.

**Comment by kyletaylored** [comment]
Can you paste the output? I'm not seeing this warning in the validation script.

```
➜  wappalyzer git:(master) yarn run validate
yarn run v1.22.17
$ yarn run lint && jsonlint -qV ./schema.json ./src/technologies/*.json && node ./bin/validate.js
$ eslint src/**/*.{js,json}
✨  Done in 7.12s.
```

**Comment by AbhinavS96** [comment]
@kyletaylored this is what I was seeing:
```
yarn run validate
yarn run v1.22.15
$ yarn run lint && jsonlint -qV ./schema.json ./src/technologies/*.json && node ./bin/validate.js
$ eslint src/**/*.{js,json}
WARN ENOENT: no such file or directory, stat './src/technologies/*.json'
Done in 12.34s.
```

**Comment by h1z1** [comment]
fwiw...

```
node_modules/yarn/bin/yarn run validate
yarn run v1.22.17
$ yarn run lint && jsonlint -qV ./schema.json ./src/technologies/ && node ./bin/validate.js
$ eslint src/**/*.{js,json}
Done in 2.81s.
```

Though it still ends up failing for reasons I have no idea..  same warning repeated hundreds of times..

```
(node:120277) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 Symbol(Events.FrameManager.FrameNavigatedWithinDocument) listeners added to [FrameManager]. Use emitter.setMaxListeners() to increase limit
100%
Converted 2,285 files.
No version number specified. Current version is 6.9.7.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by AliasIO** [comment]
@h1z1 You need to specify a version number when building, e.g. `yarn run build 1.0.0`. You can safely ignore the `MaxListenersExceededWarning` warning, it's not actually a memory leak. It happens because we're converting a lot of icon files at once.
