### ISSUE TITLE
Missing `puppeteer-core`

### ISSUE THREAD

**Issue by process0** [AliasIO/wappalyzer#5040]
**Platform**
Which platform does the bug apply to?
* NPM

**Describe the bug**

`puppeteer-core` is missing as a dependency. Added in https://github.com/AliasIO/wappalyzer/commit/f57710c3564976117b5a4f3f791138b0683ffd60 but not in `package.json`

```
$ CHROMIUM_BIN=/usr/bin/chromium node test.js
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'puppeteer-core'
Require stack:
```

**To Reproduce**

Install `wappalyzer` from npm. Run example script from npm with `CHROMIUM_BIN` set.

**Expected behavior**

Output example site wappalyzer results

**Comment by AliasIO** [comment]
Thanks, I changed it back to just using `puppeteer` instead of `puppeteer-core`.
