### ISSUE TITLE
Specify or whitelist technologies

### ISSUE THREAD

**Issue by adriaanvanrossum** [AliasIO/wappalyzer#5088]
I run an [analytics business](https://simpleanalytics.com) where we have multiple plugins that customers can install based on the technologies they use on their website. Wappalyzer helps a great deal to find out what technologies they use.

But it is a bit slow. We run way more checks then needed and for some websites it takes a while to run Wappalyzer.

It would be awesome to be able to specify which technologies we want to check for because we have a fixed list of plugins for technologies we offer.

I know specifying technologies is possible with `wappalyzer-core`, but love the crawler functionality built into Wappalyzer.

Maybe there is a way I don't know of, and otherwise I hope it's possible in the future.

A whitelist of technologies would already be a nice step.

**Comment by AliasIO** [comment]
I just did a quick test, the total time spent in `Wappalyzer.analyze` is less than a second. The delays don't come from the number of technologies but more likely the performance of the website that's being analysed.

For speed you can try the [API](https://www.wappalyzer.com/api), which returns near-instant, cached results.

**Comment by adriaanvanrossum** [comment]
That's fast enough. I don't think whitelisting the technologies would help much then. Thanks for the tip on the API. We can't use that though, because we don't want to send user data to an external service.

I think the most wait time comes from puppeteer. One way to optimize it would be running `Wappalyzer.analyze` on just the HTML (only a get request without puppeteer), and then start the puppeteer via `Wappalyzer.open` after that. So most of the technologies will be detected fast and the rest will show up later.

Or are there better ways to make the whole process faster?

**Comment by AliasIO** [comment]
Depending on your setup, you can reduce the browser start-up time by reusing a Puppeteer instance. You can pass `--no-scripts` to disable JavaScript, which can speed things up but many technologies won't be detected that way. Using only HTML without a full browser environment will yield very poor results as we use DOM methods and JavaScript for almost everything.

If you're concerned about user data, you can strip URLs down to just the hostname and pass that to the API. We only capture domains names that are public and you'll get results in under a second in most cases.

**Comment by adriaanvanrossum** [comment]
Thanks for those suggestions! I will experiment with them. Appreciate your help on this! Will report back if I find something working very well :)
