### ISSUE TITLE
Invalid JSON inside technology signatures

### ISSUE THREAD

**Issue by 0xInfection** [AliasIO/wappalyzer#5160]
**Platform**
* WebExtension (Google Chrome, Mozilla Firefox)
* NPM
* Bookmarklet
* Website

**Describe the bug**
The merge request #5155, introduced new signatures which has invalid JSON inside them. 

**To Reproduce**
https://github.com/AliasIO/wappalyzer/runs/4171207426?check_suite_focus=true

**Expected behavior**
All platforms making use of this source will break otherwise.

**Comment by AliasIO** [comment]
Fix merged, thanks!

**Comment by 0xInfection** [comment]
Thanks!
