### ISSUE TITLE
Java Server Faces not always detected

### ISSUE THREAD

**Issue by Yofial** [AliasIO/wappalyzer#5186]
**Platform**
Which platform does the bug apply to?
* WebExtension (Google Chrome)

**Describe the bug**
JavaServer Faces is not always detected.

**To Reproduce**
1. Go to [wappalyzer's list of goAnywhere detections](https://www.wappalyzer.com/technologies/miscellaneous/goanywhere/)
2. Navigate to one of them
3. Verify the extension did not detect Java Server Faces
4. Run from the console `document.querySelector("input[type='hidden'][name='javax.faces.ViewState']")` to see it should be detected (this is the `dom` detection code here: [j.json#L198](https://github.com/AliasIO/wappalyzer/blob/master/src/technologies/j.json#L198)) 

**Expected behavior**
Java Server Faces should be detected.

**Additional context**
GoAnywhere can really imply JSF, but it should work even without this implication.
It did work for me before this change to `dom` from `html` :[41ca47043a3f7748837f9b453c40a4e824a2488e
](https://github.com/AliasIO/wappalyzer/commit/41ca47043a3f7748837f9b453c40a4e824a2488e).
The change makes sense for performance reasons and should work, but does not seem to work

**Comment by AliasIO** [comment]
Fixed in 3f8ee7506bdd4b839030b43d65a96c4fb5647bc1, thanks!
