### ISSUE TITLE
Improve 'Laybuy' detection

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#5235]
Example pages where it's not working - 

1) https://www.bambinoandmore.co.uk/designer-boys/aurea-grey-and-white-fairsle-jumper
2) https://paylateralligator.com.au/furniture/bedside-table/led-bedside-table/artiss-bedside-table-2-drawers-rgb-led-side-nightstand-high-gloss-cabinet-black/

@nurbek91  - may be we should link for presence of link 'https://www.laybuy.com/what-is-laybuy' in HTML?

**Comment by nurbek91** [comment]
Hey @rockeynebhwani Added the ability to detect for one of your examples (frequency greater than 30),
The second example is unique, it had to be rejected

Hey @AliasIO Perhaps you can close this request.
By the way I added for afterpay and laybuy **requirescategory: 6** field for optimizations. I hope it will work correctly in Cart-generic cases
