### ISSUE TITLE
Track 'enable'

### ISSUE THREAD

**Issue by John4266** [AliasIO/wappalyzer#5302]
Vendor Site - https://www.enable.co.il/
Example Site - https://www.geektime.co.il/
Category - Accessibility

Detection - Check for media imported from domain https://enable.co.il
such as:
`<link rel='dns-prefetch' href='//cdn.enable.co.il' />`
`<script type='text/javascript' defer="defer" src='https://cdn.enable.co.il/licenses/enable-L2218jpqvxtlh2r-0718-5099/init.js?ver=1.3.2'></script>`

**Comment by AliasIO** [comment]
Merged, thanks!
