### ISSUE TITLE
Track 'Remix'

### ISSUE THREAD

**Issue by John4266** [AliasIO/wappalyzer#5303]
Vendor Site - https://remix.run/
Example Site - https://remix.run/
Category - Web frameworks

Detection - Find a script tag containing `window.__remixContext`

**Comment by nurbek91** [comment]
Hey there, сouldn't find examples.

**Comment by John4266** [comment]
> Hey there, сouldn't find examples.

Yea its a pretty new framework, here is an example i could find (for now) https://remix-jokes.lol/
I will post more if i'll find more.
