### ISSUE TITLE
Proxy support?

### ISSUE THREAD

**Issue by ralyodio** [AliasIO/wappalyzer#5318]
I'm using the npm library and would be nice to have a proxy option (with authentication)

**Comment by ralyodio** [comment]
I see its not supported anymore, is there anyway I can run the detection stuff with my own instance of puppeteer?

**Comment by AliasIO** [comment]
Yes, you can either set `CHROMIUM_WEBSOCKET` or copy [`cli.js`](https://github.com/AliasIO/wappalyzer/blob/master/src/drivers/npm/cli.js) and set `wappalyzer.browser` to your instance without calling `wappalyzer.init`.
