### ISSUE TITLE
Is it possible to avoid redirects to 3rd parties?

### ISSUE THREAD

**Issue by michael1026** [AliasIO/wappalyzer#5319]
When using the NPM package, it seems to follow redirects to 3rd parties, then analyzes them. Is it possible to disable this behavior? Here's an example of code where this happens...

```
async function wappalyze(url) {
  try {
    const wappalyzer = new Wappalyzer()
    await wappalyzer.init()
    const result = await wappalyzer.open(url).analyze()

    console.log(JSON.stringify(result, null, 2))
    await wappalyzer.destroy()
  } catch (error) {
    console.error(error)
  }
}
```

Output example...

```
{
  "urls": {
    "https://example.com/": {
      "status": 302
    },
    "https://someThirdParty": {
      "status": 200
    }
  },
  "technologies": []
}

```

Thanks!

**Comment by AliasIO** [comment]
Also see #5304. I'll be making some changes around this but I don't think the initial redirect should be avoided in normal cases. We could add an option to disable redirects completely if that helps.

**Comment by AliasIO** [comment]
This has been added in 1097edd. By default, cross-domain redirects are only allowed on the first request. To disable redirects on all requests you can set noRedirect to true or pass --no-redirect or -N.

**Comment by michael1026** [comment]
Thanks!
