### ISSUE TITLE
Detect Microsoft Exchange (Outlook web access) version 

### ISSUE THREAD

**Issue by fwininger** [AliasIO/wappalyzer#5329]
Exchange exposes its version in its headers.

A request on the /owa/ URI will provide a X-OWA-Version header in its response, with appropriate information.

/!\ IMPORTANT /!\ : the X-OWA-Version header can be lowercased, so the parser MUST be case-insensitive.

Some examples below already indexed on Shodan:

```
curl -v https://216.176.178.100/owa/ -k --silent 2>&1 | grep -i "X-OWA-Version"
< X-OWA-Version: 15.0.1497.26
```

```
curl -v https://185.17.193.231/owa/ -k --silent 2>&1 | grep -i "X-OWA-Version"
< x-owa-version: 15.1.2242.12
```

Ref : https://github.com/AliasIO/wappalyzer/blob/master/src/technologies/o.json#L1188

**Comment by AliasIO** [comment]
Thanks!
