### ISSUE TITLE
Calendar Hero

### ISSUE THREAD

**Issue by vfcampo** [AliasIO/wappalyzer#5334]
You may request a new technology to be added but changes of having it included are greatly improved if you submit a pull request. Please refer to the [contributing guide](https://github.com/AliasIO/wappalyzer/blob/master/CONTRIBUTING.md).

Name of the products: [ Calendar. Hero ](https://calendarhero.com/)

Example website: https://www.realcode.co.uk/contact/

- Suggested Category

Appointment scheduling

- Embedding:

![image](https://user-images.githubusercontent.com/55451462/143656408-32764f12-ca6a-4237-9880-ed93feb00e96.png)

- Scripts:

![image](https://user-images.githubusercontent.com/55451462/143656441-bb782744-681d-4ffe-9713-5bdd26f4fbc1.png)

**Comment by AliasIO** [comment]
This has been added, thanks!
