### ISSUE TITLE
incorrect X-Cart detection 

### ISSUE THREAD

**Issue by gemini133** [AliasIO/wappalyzer#5336]
https://www.wappalyzer.com/technologies/ecommerce/x-cart

please check the "Websites using X-Cart" section.

![image](https://user-images.githubusercontent.com/18028552/143675465-89158b30-d17c-44ee-82fa-c58942ffd47c.png)

I don't believe that they will use x-cart as their store.

I guess it's caused by the cookie: `"xid": "[a-z\\d]{32}(?:;|$)"` and not sure if it's safe to remove it.

**Comment by AliasIO** [comment]
Thanks!
