### ISSUE TITLE
Track 'Glitch'

### ISSUE THREAD

**Issue by John4266** [AliasIO/wappalyzer#5337]
Vendor Site - https://glitch.com / https://glitch.me
Example Sites:
http://hello-express.glitch.me/
https://meet-scheduler.glitch.me/
Category - PaaS (Probably)
Detection - `glitch.me` domain (still looking for other detection techniques)

**Comment by nurbek91** [comment]
Category - PaaS (Probably) +

**Comment by AliasIO** [comment]
Thanks!
