### ISSUE TITLE
Project URL changed for Choices.js

### ISSUE THREAD

**Issue by sitemapxml** [AliasIO/wappalyzer#5338]
**Platform**
Wappalyzer website
https://www.wappalyzer.com

**Describe the bug**
There is an invalid link for specific technology - Choices js library.

**To Reproduce**
1. Go to https://www.wappalyzer.com/technologies/miscellaneous/choices
2. Click on "Visit joshuajohnson.co.uk" button
3. There is an 404 page at folowing address: https://joshuajohnson.co.uk/Choices/

**To fix**
New project URL is: https://joshuajohnson.co.uk/choices-js/

**Comment by AliasIO** [comment]
Thanks!
