### ISSUE TITLE
Ant Design

### ISSUE THREAD

**Issue by cliffordfajardo** [AliasIO/wappalyzer#5349]
Ant Design is a React library with 75k+ stars on Github & is increasingly getting popular in the US.
- https://github.com/ant-design/ant-design

It looks like Ant Design was removed by accident in a previous commit?
- https://github.com/AliasIO/wappalyzer/issues/1996

I will likely dig into the code this weekend & contribute a pull request to have this added 👨‍💻

**Comment by nurbek91** [comment]
Hey @cliffordfajardo , 
1. changed technology category to from Javascript frameworks - > UI frameworks 
2. added the ability to determine the version
3. added open-source flag, description
 
I wanted to add `"requiresCategory": 12,`  to reduce the load, but I met examples where there are no javascript frameworks https://sixthcontinent.com/

**Comment by AliasIO** [comment]
Thanks!
