### ISSUE TITLE
Antv G6 graph visualization library

### ISSUE THREAD

**Issue by cliffordfajardo** [AliasIO/wappalyzer#5350]
Antv ' s G6 Graph visualization library
- https://g6.antv.vision/en/
- 8.5k stars
- extremely popular in Asia, and increasingly gaining popularity here in US

I will likely dig into the code this weekend & contribute a pull request to have this added 👨‍💻

**Comment by nurbek91** [comment]
Hey @cliffordfajardo , added Antv G6 and Antv G2. 
There are practically no examples for G6 on the net
If you have examples it would be great if you share.
Found only on the demos page on the official website.

**Comment by cliffordfajardo** [comment]
@nurbek91 - yeah its not as popular (yet) in the US, but its really popular in Asia
I'm using it at work right now its awesome! Expect to see it grow in popularity soon in the US & places outside Asia 😉

**Comment by AliasIO** [comment]
Thanks!
