### ISSUE TITLE
 I suggest adding the preceding matching character before the regular expression to each ‘json’ message to be matched.

### ISSUE THREAD

**Issue by zengxiangjiang** [AliasIO/wappalyzer#5379]
hello everyone
      The rule matching process uses regular expressions. Regular expressions are a performance killer. I think there is an initial screening before using regular expression matching, for example:
      To be matched: ‘Server: Apache/2.2.21 (Win64) PHP/5.3.10’, the characters in the corresponding application matching rule should be in it. If the matching character is not in the text to be matched, no regular expression matching is used.

So I suggest adding the preceding matching character before the regular expression to each ‘json’ message to be matched.

thanks

**Comment by AliasIO** [comment]
I like the idea but I'm not sure how it would work. Here's the pattern for Apache, for instance:

`(?:Apache(?:$|/([\\d.]+)|[^/-])|(?:^|\\b)HTTPD)\\;version:\\1`

How would you screen this? The technology name is not always in the pattern.

**Comment by AliasIO** [comment]
I did some testing and found that all the regular expressions combined run in about 300ms, with the slowest expressions taking 1-2ms.

I did [improve performance](https://github.com/AliasIO/wappalyzer/commit/91bcf03f8893c740ca553e1c2fdd7a5baaf7d038#diff-ad7c0e5878800a307cc8ca5b8b986a9565346764379d65c12a986ff0260b486dR518) by automatically by replacing `*` with `{0,250}` and `+` with `{1,250}` in all expressions to avoid scanning very long strings, which made a big difference.

Let me know if you still think performance is an issue. A preliminary string match is a good idea but will add a lot of maintenance and I'm not sure how much of a difference it will make.

**Comment by zengxiangjiang** [comment]
In fact, we look at the problem from a different perspective. My point of view is that in the matching process of a request information, it is not necessary to use regular expressions to match, rather than the execution time of a single regular.

Assuming that the request information we want to match will hit 10 applications, the number of regular matches can be reduced during matching. It is not necessary to match all regulars. The "preMatch" field is used to accomplish this.

Let's calculate the time consumption in the case of 100,000 requests.
Preset:
Number of application rules: 2090
Full regular expression matching time: 300ms
"PreMatch" field matching time: 0.0001ms (presumed value: use "bitrix(?:\\.info/|/js/main/core)..contains("bitrix");" 7ms for 100000 times )

Single regular time length: 0.2ms (inferred value: full regular expression matching time/number of rules)
Assume that the number of successful pre-matches is 1/3 of the total number of rules: 2090 (the number of applied rules)/3=697

Duration without pre-matching:
100000*300ms=30000000ms=30000s

Duration of pre-matching:
100000*(0.0001ms*300)=3000ms=3s
100000*(0.2ms*697)=13940000ms=13940s
Total: 3s+13940s=13943s
The result is obvious.

**Comment by AliasIO** [comment]
A string match is only about 60% faster than a simple regex match in my testing:

```javascript
let startTime = Date.now()
  
for (let i = 0; i < 100000000; i++) 'test'.includes('test')
  
console.log(Date.now() - startTime) // 2,349ms
  
startTime = Date.now()
  
for (let i = 0; i < 100000000; i++) /test/.test('test')

console.log(Date.now() - startTime) // 3,855ms
```

I'm not sure if it's worth optimising a 300ms process if it means writing `preMatch` values for about 3,000 technologies by hand. Apache can match `server: Apache` or `server: HTTPD` so it's not always possible to just use a single string match.

Maybe we can change specific cases like `/^Example$/` to `=== "Example"` automatically.

**Comment by zengxiangjiang** [comment]
I agree with you that maintaining matching rules is indeed a headache.

It would be great if some applications can be matched to use string matching instead of regular.
