### ISSUE TITLE
Generator detection seems broken

### ISSUE THREAD

**Issue by jdevalk** [AliasIO/wappalyzer#5384]
**Platform**
Which platform does the bug apply to?
* WebExtension (Google Chrome, Mozilla Firefox)
* NPM

**Describe the bug**
In detecting WooCommerce & WordPress (probably more, didn't test), the version number isn't properly detected. In fact it looks like the entire `meta` > `generator` detection doesn't work.

**To Reproduce**
1. Run `node src/drivers/npm/cli.js https://yoast.com/`
2. See that it doesn't detect a version number for WordPress and WooCommerce.

**Expected behavior**
I would expect it to be able to extract a version number from the `generator` tags.

**Comment by AliasIO** [comment]
Fixed, thanks! Multiple meta tags with the same name were not handled correctly, only the last value was used.
