### ISSUE TITLE
Track 'Accessibility ADApter™'

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#5401]
Vendor Site - https://adasitecompliance.com/accessibility-adapter-info/
Example Site - https://puffitup.com/collections/arizer/products/extreme-q-digital-remote-vaporizer-by-arizer
Category - Accessibility
Detection - Look for script using following patters -

https://adasitecompliancetools.com/ADApter.asp?cid=PFFITP

**Comment by nurbek91** [comment]
Hey @AliasIO Probably can be closed.
