### ISSUE TITLE
Single consistent JSON technology rule file

### ISSUE THREAD

**Issue by netbroom** [AliasIO/wappalyzer#5416]
**Is your feature request related to a problem? Please describe.**
We have been using just the JSON technology rule file for our detection but it breaks every time the JSON file moves or is renamed. It appears the file was split into alphabetical JSON files named by letter which has again broken our detection.

**Describe the solution you'd like**
I am requesting that there be one single JSON rules file in a location that will remain consistent so if developers are using their own library or language of choice they can choose to just parse the rules file. If a single file is not possible, splitting it into several files is acceptable as a solution for us but we are just requesting that this file structure (or directory location) remain consistent in the future.

**Describe alternatives you've considered**
In the past when the JSON file was renamed we just updated the file name on our end, but adding code to pull down JSON files for each letter of the alphabet, in addition to accounting for future changes that may happen unexpectedly, is not ideal or future-proof.

**Additional context**
We run a threat intelligence company that uses Wappalyzer's detection rules to detect technology running on malicious URLs. We love Wappalyzer so hopefully this is possible to implement so we can continue to use this beneficial technology without having to monitor updates to the detection rules.

**Comment by AliasIO** [comment]
The change was necessary because the file was getting so large it made editors struggle and it was no longer practical to view diffs on GitHub. The spec has remained largely unchanged for years but we'll continue to make improvements where it makes sense.

If you don't want unexpected changes you can use the technology definitions in a specific commit or release, or use our paid [API](https://www.wappalyzer.com/api). The `master` branch can change at any time.

I have been thinking of a way for me to announce breaking changes, I'm not sure what the best channel for this would be.

**Comment by netbroom** [comment]
Thanks for the quick response, that makes sense.

We do the scanning ourselves and run our data against the rules so we wouldn't be a good match for the API. Plus we want updates on new rules so definitely want to retrieve the latest.

It is probably cumbersome but just to think out loud, an ideal solution for our use case would probably to be a dump of a single JSON file with all the rules compiled. But I think unless that is feasible and worth it from your end we will just notify ourselves of breaking changes like problems parsing and adjust as necessary.

If you have any thoughts let us know, otherwise feel free to close. 🙂

**Comment by AliasIO** [comment]
No worries. The current a-z file naming format is unlikely to change any time soon so you can update your scripts accordingly. Depending on your setup you may be able to use the NPM package instead the raw JSON files.

I think I'll open a GitHub [discussion](https://github.com/AliasIO/wappalyzer/discussions) to announce any API changes so you'll be able to subscribe to that and get notified.

Thanks for being a sponsor! :)
