### ISSUE TITLE
No data for category with ID 61 

### ISSUE THREAD

**Issue by milosb793** [AliasIO/wappalyzer#5418]
**Describe the bug**
Seems like there's no category info for cat ID 61.

**To Reproduce**
1. Go to https://raw.githubusercontent.com/AliasIO/wappalyzer/master/src/categories.json
2. Click on scroll down to ID 60
4. See missing 61 category

**Additional info**
- The app `LocalFocus` is having category 61. 
- There is category info for ID 61 in `categories` here: https://raw.githubusercontent.com/glin/Wappalyzer/master/src/apps.json

![image](https://user-images.githubusercontent.com/5012355/145996710-2a285fe9-04e2-4be0-8e07-769efa4ffdda.png)

**Comment by AliasIO** [comment]
The category for LocalFocus has been changed to 25 (JavaScript Graphics). The `apps.json` file you linked to is out of date.

**Comment by milosb793** [comment]
How's that, and it's on master branch? Shouldn't it be up-to-date there?

**Comment by AliasIO** [comment]
The `apps.json` file you linked to is from a different repository. The current definitions are here:

https://github.com/AliasIO/wappalyzer/tree/master/src/technologies

**Comment by milosb793** [comment]
Oh, I see! 🙈 Thanks and sorry!
