### ISSUE TITLE
Wappalyzer is not detecting Umbraco CMS

### ISSUE THREAD

**Issue by John4266** [AliasIO/wappalyzer#5471]
**Platform**
Which platform does the bug apply to?
* WebExtension (Mozilla Firefox)
* Websites:
https://www.idf.il
https://www.iroads.co.il

**Describe the bug**
These sites are built with Umbraco CMS but Wappalyzer doesn't detect it.

**To Reproduce**
1. Go to any of the above sites.
2. Check Wappalyzer results.

**Expected behavior**
Wappalyzer should detect Umbraco CMS.

**Comment by AliasIO** [comment]
Fix merged, thanks!
