### ISSUE TITLE
REACT 

### ISSUE THREAD

**Issue by Marcking-hub-cloud** [AliasIO/wappalyzer#5473]
**Platform**
Which platform does the bug apply to?
all
**Describe the bug**
React is not a framework,  is a JavaScript library
**To Reproduce**
Open the React official site homepage

**Comment by AliasIO** [comment]
React is more like Vue.js and Angular than jQuery and Lodash, which is why it's categorised as such.

**Comment by metaloha** [comment]
React is a UI library. It says so on their website. `next.js` (for example) is a framework that implements React as its UI library; it's not a framework that wraps another framework. React has more in common with jQuery UI than with Angular or Vue.
