### ISSUE TITLE
Hashnode invalid url

### ISSUE THREAD

**Issue by sitemapxml** [AliasIO/wappalyzer#5482]
**Platform**
Which platform does the bug apply to?
Wappalyzer website - [wappalyzer.com](https://www.wappalyzer.com)

**Describe the bug**
Page for Hashnode technology not exist

**To Reproduce**
1. You can go to hashnode website [hashnode.com](https://hashnode.com/)
2. Open wappalyzer and click on Hashnode technology icon, under section "Blogs"
3. It will then take you to the following URL: 
https://www.wappalyzer.com/technologies/blogs/hashnode/?utm_source=popup&utm_medium=extension&utm_campaign=wappalyzer
4. That URL would then return 404 error page

**Comment by AliasIO** [comment]
It's there now, thanks. :)
