### ISSUE TITLE
Track 'VAPTCHA'

### ISSUE THREAD

**Issue by John4266** [AliasIO/wappalyzer#5498]
Vendor Site - https://en.vaptcha.com
Example Site: http://deepfacedrawing.geometrylearning.com/index_EN_621.html
Category - Security
Detection - Script imported from `https://v.vaptcha.com/v3.js`

**Comment by nurbek91** [comment]
Hey @John4266 , added to security category. Do you have pricing information for this product?

**Comment by John4266** [comment]
> Hey @John4266 , added to security category. Do you have pricing information for this product?

uh there is at least a Free version, tho i dont have info about the other pricing plans.

**Comment by nurbek91** [comment]
> > Hey @John4266 , added to security category. Do you have pricing information for this product?
> 
> uh there is at least a Free version, tho i dont have info about the other pricing plans.

ok, thanks!!
