### ISSUE TITLE
Provide evidence in cli output

### ISSUE THREAD

**Issue by EndPositive** [AliasIO/wappalyzer#5527]
**Is your feature request related to a problem? Please describe.**
We're using Wappalyzer in Docker to automatically detect technologies on our clients' websites. Wappalyzer is very reliable and accurate in this regard, well done! Our pentesters often complain that it is unclear how a certain technology was detected/determined. Until now, we always manually reference the technologies json to figure out what happened.  For a large number of technologies, it can be quite time-consuming to validate each.

**Describe the solution you'd like**
Wappalyzer adds evidence fields that describe how this technology was detected.

* [ ] Which pattern matched?
* [ ] What string was matched?
* [ ] Where was the string found? Headers, Script, HTML, etc.
* [ ] Was the technology found through implicits? If so which?

**Describe alternatives you've considered**
A simpler option would be to reference the json template used to for this technology only, but that would leave much information out.

**Comment by AliasIO** [comment]
We could perhaps emit an event when a [detection](https://github.com/AliasIO/wappalyzer/blob/master/src/drivers/npm/driver.js#L1126) occurs, the internal representation looks like this:

```javascript
[
  {
    "technology": {
      "name": "Amazon S3",
      "categories": [
        19
      ],
      "slug": "amazon-s3",
      "url": [],
      "xhr": [],
      "headers": {
        "server": [
          {
            "value": "^AmazonS3$",
            "regex": {},
            "confidence": 100,
            "version": ""
          }
        ]
      },
      
      ...
      
      "implies": [
        {
          "name": "Amazon Web Services",
          "confidence": 100
        }
      ],
      "excludes": [],
      "requires": [],
      "requiresCategory": [],
      "icon": "aws-s3.svg",
      "website": "http://aws.amazon.com/s3/",
      "pricing": [],
      "cpe": null
    },
    "pattern": {
      "value": "^AmazonS3$",
      "regex": {},
      "confidence": 100,
      "version": ""
    },
    "version": ""
  }
]
```

In this case the pattern `^AmazonS3$` matched a response header.

You'd need to create a of [cli.js](https://github.com/AliasIO/wappalyzer/blob/master/src/drivers/npm/cli.js) to listen for the events and add the results to the output and use that as the Docker entrypoint.

**Comment by EndPositive** [comment]
Cool, that output well suits our needs! I understand that you only want to emit an event in the official version and that I would need to maintain a separate entrypoint to include the details from that event in the output? Would you be willing to include both in the official version, possibly under a feature flag?

**Comment by AliasIO** [comment]
Fine. :) I added an option for extended output in c5909d314ed8032c366524df560f2b00c3025765. Pass `-e` or `--extended` and you'll get an additional field called `patterns` in the response.

**Comment by EndPositive** [comment]
Hi @AliasIO, thanks a ton for your work so far! Through some testing on v6.9.13, I still found it difficult to understand how a technology was found. For example, the output does not show which text matched the pattern regex. Furthermore, when using `--recursive`, it was not clear on which specific page the technology was found. Finally, the implies field was only added in the pattern for the technology that caused the imply. I've "reversed" this to a `implied_by` field.

Let me know what you think of the PR and if you think we need to output things differently.

**Comment by AliasIO** [comment]
I included the matched value in 5f629ad25a24694e6b1ab7bb60b8b5b565846d09.

I prefer to keep the outputs separate and not make big changes to include this.

You can use this JavaScript snippet to mix the extended output into results (outside of Docker), or port it to whatever language you're using:

```javascript
const { technologies, patterns } = results

technologies.forEach((technology) => {
  technology.evidence = {
    patterns: patterns[technology.name],
    impliedBy: Object.keys(patterns).reduce((names, name) => {
      patterns[name].some(({ implies }) =>
        implies.includes(technology.name)
      ) && names.push(name)

      return names
    }, []),
  }
})
```

The combined results looks something like this:

```
"technologies": [
  {
    "slug": "amazon-web-services",
    "name": "Amazon Web Services",
    "confidence": 100,
    "version": null,
    "icon": "aws.svg",
    "website": "https://aws.amazon.com/",
    "cpe": null,
    "categories": [
      {
        "id": 62,
        "slug": "paas",
        "name": "PaaS"
      }
    ],
    "evidence": {
      "impliedBy": [
        "AWS Certificate Manager",
        "Amazon Cloudfront",
        "Amazon S3"
      ]
    }
  },
  {
    "slug": "amazon-cloudfront",
    "name": "Amazon Cloudfront",
    "confidence": 100,
    "version": null,
    "icon": "Amazon-Cloudfront.svg",
    "website": "http://aws.amazon.com/cloudfront/",
    "cpe": null,
    "categories": [
      {
        "id": 31,
        "slug": "cdn",
        "name": "CDN"
      }
    ],
    "evidence": {
      "patterns": [
        {
          "type": "headers",
          "regex": "\\(CloudFront\\)$",
          "value": "1.1 236197b1350688f238411607ca197958.cloudfront.net (CloudFront)",
          "confidence": 100,
          "version": "",
          "implies": [
            "Amazon Web Services"
          ],
          "excludes": []
        },
        {
          "type": "headers",
          "regex": "(?:)",
          "value": "-62yXukgj-XT8FxRses04BNF-N0zXesjbBEpP3cGE_OqoVkeLbaF-A==",
          "confidence": 100,
          "version": "",
          "implies": [
            "Amazon Web Services"
          ],
          "excludes": []
        }
      ],
      "impliedBy": []
    }
  }
]
```

Note that the matched value can be very long (e.g. the entire HTML source code). When this happens I'm setting `value` to `null` to avoid huge outputs.

Keeping track of the URL in matches would require more changes but hopefully this helps.

**Comment by EndPositive** [comment]
Fair enough. Thanks again. Regarding the very long output, in the PR, I used `regex.exec()` to get the part that actual matched. I think that's far more useful than writing null or complete html. 

See https://github.com/AliasIO/wappalyzer/compare/master...EndPositive:regex-value

**Comment by AliasIO** [comment]
I'm including both in 50cb0ba2889eb8c2360fb5c1574e19987d660b78. The match is often empty as we use an empty regex to match any value, e.g. when testing if a header exists. The value may be useful in those cases.

**Comment by EndPositive** [comment]
Excuse me for keeping this open, but your additions suit our needs!
