### ISSUE TITLE
Sellix not detected

### ISSUE THREAD

**Issue by John4266** [AliasIO/wappalyzer#5528]
**Platform**
Which platform does the bug apply to?
* WebExtension (Ver. 6.9.11)
* Browser (Mozilla Firefox)

**Describe the bug**
Wappalyzer is not detecting Sellix (eCommerce) on https://motiontokens.com/

**To Reproduce**
1. Go to https://motiontokens.com/
2. Click on Wappalyzer extension m
3. Look for "Sellix"

**Expected behavior**
Should detect it.

**Comment by AliasIO** [comment]
Fixed, thanks!
