### ISSUE TITLE
Track 'Apache Guacamole'

### ISSUE THREAD

**Issue by John4266** [AliasIO/wappalyzer#5544]
Vendor Site - https://guacamole.apache.org
Example Site: https://tria.ge
Category - Remote Access (?)
Detection: A WSS request that returns the following:
Status Code: `101 Switching Protocols`
Header: `Sec-Websocket-Protocol: guacamole`

**Comment by nurbek91** [comment]
Hey @AliasIO, Is it possible to send WSS requests within the Wappalyzer?

**Comment by AliasIO** [comment]
This won't work as we don't monitor every request, including WSS requests (we only inspect headers sent with the page itself). @John4266 Is there another way to detect Guacamole?

**Comment by John4266** [comment]
Uhm, unfortunately i do not see any other signature for the technology.

**Comment by nurbek91** [comment]
Hey @AliasIO , can be closed.

**Comment by John4266** [comment]
Closed
