### ISSUE TITLE
Tidio Chat doesn't use React

### ISSUE THREAD

**Issue by vinhais** [AliasIO/wappalyzer#5562]
**Platform**
Which platform does the bug apply to?
* WebExtension (Google Chrome, Mozilla Firefox)

**Describe the bug**
React is indicated whenever Tidio is added to the site, I have tracked it and on all sites with Tidio it happens (regardless of using any JS framework or not)

**To Reproduce**
1. Create a blank page and add Tidio livechat
2. Watch the technologies, will be indicating Tidio and React

**Expected behavior**
React not inserted because of Tidio

**Additional context**
None

**Comment by nurbek91** [comment]
Hey @vinhais , could you send some links where the technology is erroneously defined
