### ISSUE TITLE
SoundCloud Widget is not detected on Wired.com

### ISSUE THREAD

**Issue by John4266** [AliasIO/wappalyzer#5584]
**Platform**
Which platform does the bug apply to?
* WebExtension (Mozilla Firefox)
* Website: https://www.wired.com/story/general-paul-nakasone-cyber-command-nsa/

**Describe the bug**
![Wappalyzer](https://i.imgur.com/xJf5jCs.png)
![SC](https://i.imgur.com/C0DcTIe.png)

**To Reproduce**
1. Go to https://www.wired.com/story/general-paul-nakasone-cyber-command-nsa/
2. Check Wappalyzer

**Expected behavior**
Should detect it.

**Comment by nurbek91** [comment]
Hey @John4266 ,I additionally added the scriptSrc attribute, but in your example there is an iframe by which the technology should already be determined. Strange but it doesn't work. Locally also failed during tests
