### ISSUE TITLE
Track 'ruxitagentjs'

### ISSUE THREAD

**Issue by John4266** [AliasIO/wappalyzer#5585]
Vendor Site - https://www.dynatrace.com/platform/real-user-monitoring/
Example Sites:
https://www.dynatrace.com/platform/real-user-monitoring/
https://www.gartner.com/
https://www.gov.il/
Category - RUM
Detection - `script` tag which `src`'s attribute contains the following regex `ruxitagentjs_(.*?)_(.*?)\.js`
Regex to match the following examples based on real data:
```
src="/ruxitagentjs_ICA2Vfhqru_10233220127140028.js"
src="/en/ruxitagentjs_ICA2Vfqru_10209210209190405.js"
src="/ruxitagentjs_ICA2QVafghjlqrtux_10231211201155045.js"
```

**Comment by nurbek91** [comment]
Hey @John4266 , thanks for request , added as Dynatrace RUM
