### ISSUE TITLE
Track 'happyfox' live chat

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#5612]
Vendor Site - https://www.happyfox.com/live-chat/#
Example Site - https://www.xlarge.com/default/3d-logo-crewneck-sweat/101214012022.html
Category - Live Chat
Detection - Check for assets loading from domain 'widget.happyfoxchat.com'

**Comment by nurbek91** [comment]
Hey @rockeynebhwani , added Live Chat and HelpDesk separately, thanks for request, I expect more requests from you if you plan, ready to add them ;)
