### ISSUE TITLE
Improve detection for 'Affirm'

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#5620]
Sites where detection for 'Affirm' Buy now pay later solution is not working - 

- https://www.bradybrand.com/products/cotton-jersey-wordmark-short-sleeve-brady-blue
- https://fellowproducts.com/products/raven
- https://www.drinkhydrant.com/products/hydration-mix?variant=39354549862489

On Shopify sites, BNPL is powered by Affirm via ShopPay so we can look for ShopPay related elements to improve Affirm detection - Look for `<p>` tag with `class="shopify-installments"`

**Comment by nurbek91** [comment]
Hey @rockeynebhwani , added as Shop Pay Installments which implies Affirm and Shop Pay , but couldn't test it locally. May be it will work on extension
