### ISSUE TITLE
lit-html and lit-element detection not working

### ISSUE THREAD

**Issue by justinfagnani** [AliasIO/wappalyzer#5630]
**Platform**
Which platform does the bug apply to?
* WebExtension (Google Chrome, Mozilla Firefox)
* Website

**Describe the bug**
Sites that definitely use lit-html and lit-element are not reporting that they do.

**To Reproduce**
1. Go to 'lit.dev
2. Click on Wappalzer extension
4. See that lit-html and lit-element are not listed

**Expected behavior**
lit-html and lit-element are listed

**Additional context**
The JS detection is here: https://github.com/AliasIO/wappalyzer/blob/master/src/technologies/l.json#L1305

We put our versions in an array, since a page can use more than one version. I'm not sure if the `0` in `litElementVersions.0` is problematic or not.

**Comment by AliasIO** [comment]
It's working for me on `master`, possibly it wasn't working before fb7eee340c57934ab33f2a348a65ea75594f7cce.

<img width="190" alt="Screen Shot 2022-02-23 at 10 04 43 am" src="https://user-images.githubusercontent.com/77259/155234467-c38ca3d5-8aec-4c07-9b86-c6590d81835a.png">

**Comment by justinfagnani** [comment]
I wonder if that commit could actually be related, since lit detection should use the DOM at all. Unless that was throwing before the JS properties were checked.

**Comment by justinfagnani** [comment]
Turns out lit-html and lit-element were added in https://github.com/AliasIO/wappalyzer/pull/5600 only 11 days ago. Closing!
