### ISSUE TITLE
Astro is not detected

### ISSUE THREAD

**Issue by sklar** [AliasIO/wappalyzer#5635]
**Platform**
Which platform does the bug apply to?
* WebExtension (Google Chrome)

**Describe the bug**
Technology is not detected by the browser extension.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to [Astro website](https://astro.build/)
2. Click on Wappalyzer button
3. Technology is not detected.

<img width="1017" alt="Screenshot 2022-02-25 at 10 15 34" src="https://user-images.githubusercontent.com/2298407/155741158-c4a6aaa7-3d05-4530-92fa-f6a1f83c130d.png">

**Expected behaviour**
Technology is detected.

**Additional context**

Astro was introduced in [v6.9.14](https://github.com/AliasIO/wappalyzer/releases/tag/6.9.14) by #5504.
If I understand it correctly, the detection is implemented by the `href` attribute pattern.

I dare to recommend seconding it with the `class` attribute pattern as it was in the original new technology request.
```
astro-[\d\w]{8,}
```

**Comment by nurbek91** [comment]
Hey @sklar updated, thanks!!!
