### ISSUE TITLE
Track 'Monaco Editor'

### ISSUE THREAD

**Issue by John4266** [AliasIO/wappalyzer#5636]
Vendor Site - https://github.com/microsoft/monaco-editor
Example Sites:
https://microsoft.github.io/monaco-editor/
https://godbolt.org/
https://www.typescriptlang.org/play
https://codedamn.com/playgrounds (Registration required)
Category - Rich text editors (?)
Detection - html/css class named `monaco-editor`

**Comment by nurbek91** [comment]
Hey @John4266 , added thanks!!
