### ISSUE TITLE
Track 'loadable-components'

### ISSUE THREAD

**Issue by John4266** [AliasIO/wappalyzer#5638]
Vendor Site - https://github.com/gregberge/loadable-components
Example Site: https://discord.com/guidelines
Category - JavaScript libraries OR JavaScript Frameworks
Detection - `script` tag with id of `__LOADABLE_REQUIRED_CHUNKS__` or `__LOADABLE_REQUIRED_CHUNKS___ext`

**Comment by nurbek91** [comment]
Hey @John4266 , added thanks!!
