### ISSUE TITLE
Improve detection of 'Vue.ai'

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#5681]
Site where detection is not working -

https://gramicci.com/pages/shop-the-look-mens

1) You can look for following comment in HTML  - `<!-- Vue.ai (noscript) -->`
2) You can look for attribute `data-msd-client-id` under SCRIPT tag

**Comment by nurbek91** [comment]
Hey @rockeynebhwani , updated thanks!!!
