### ISSUE TITLE
Improve detection for 'Sezzle' BNPL solution

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#5685]
Site where detection is not working -

https://www.tobi.com/product/77966-tobi-sweetness-swiss-dot-cotton-stripe-midi-dress?color_id=110872

- You can make the check generic to look for script from domain 'widget.sezzle.com' in addition to 'widget.sezzle.in'
- Also, you can look for META tag with name 'sezzle_cid'

**Comment by nurbek91** [comment]
Hey @rockeynebhwani , updated thanks!!!
