### ISSUE TITLE
Cloudimage (and other subdomains proxies)

### ISSUE THREAD

**Issue by clementduveau** [AliasIO/wappalyzer#5689]
I am looking to add Cloudimage. It is used if one of these conditions is true:

- Images are loaded from (unique_token).cloudimg.io
- Images are loaded from a domain which have (unique_token).cloudimg.io as a CNAME
- Responses of images requests include x-cloudimg-traceid header

I can make a pull request, but I am not sure that the current filters of Wappalyzer are able to filter that. Websites never use Cloudimage directly, it is always a subdomain, used for media images, sometimes JS/CSS. Is the `headers` filter analyzing those headers ? How could I filter that given the previous conditions ?

**Comment by nurbek91** [comment]
Hey @clementduveau , added thanks!!!
