### ISSUE TITLE
Track 'DPlayer'

### ISSUE THREAD

**Issue by John4266** [AliasIO/wappalyzer#5690]
Vendor Site - https://dplayer.js.org/ | https://github.com/DIYgod/DPlayer
Example Site: https://www.practicu.com/%D7%A7%D7%95%D7%A8%D7%A1-%D7%A8%D7%99%D7%90%D7%A7%D7%98-React
Category - Video Players
Detection - `video` tag with class `dplayer-video`

**Comment by nurbek91** [comment]
Hey @John4266 , added thanks!!!
