### ISSUE TITLE
Track 'Vuetify'

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#5706]
Vendor site - https://vuetifyjs.com/
Example site - https://rothys.com/products/the-point-dragon-fruit
Detection - Look for <style> tag with an id of 'vuetify-theme-stylesheet'.

**Comment by nurbek91** [comment]
Hey @rockeynebhwani , is this technology being used on this example?

Also, this technology is already on [Wappalyzer](https://www.wappalyzer.com/technologies/ui-frameworks/vuetify?utm_source=popup&utm_medium=extension&utm_campaign=wappalyzer)

By the way, added desc and remove html attribute which duplicate css attribute.

**Comment by rockeynebhwani** [comment]
Yes @nurbek91 .. this site is using this technology and it was not being shown in my chrome extension so I assumed that it's something new but hopefully this was just the case of improving detection.

**Comment by nurbek91** [comment]
Hey @rockeynebhwani , Is everything good now? If yes, you can close the PR.Thanks!!!

**Comment by rockeynebhwani** [comment]
thanks @nurbek91 .. yes... closing this..
