### ISSUE TITLE
GitBook not detected

### ISSUE THREAD

**Issue by John4266** [AliasIO/wappalyzer#5708]
**Platform**
Which platform does the bug apply to?
* WebExtension (Mozilla Firefox)

**Describe the bug**
Wappalyzer doesn't detect GitBook on https://book.hacktricks.xyz/

**To Reproduce**
1. Go to https://book.hacktricks.xyz/
2. Check Wappalyzer results

**Expected behavior**
Should detect

**Comment by nurbek91** [comment]
Hey @John4266 , fixed. Thanks!!!
