### ISSUE TITLE
Improve detection of 'Oracle Commerce'

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#5735]
Site where it's not working
 - www.chicos.com

Current detection 

```
  "Oracle Commerce": {
    "cats": [
      6
    ],
    "cpe": "cpe:/a:oracle:commerce_platform",
    "headers": {
      "X-ATG-Version": "(?:ATGPlatform/([\\d.]+))?\\;version:\\1"
    },
    "icon": "Oracle.png",
    "website": "http://www.oracle.com/applications/customer-experience/commerce/products/commerce-platform/index.html"
  },
```

What can you do to improve detection - 

- Look for presence of '/atg/commerce' in HTML

**Comment by nurbek91** [comment]
Hey @rockeynebhwani ,
Could you help with checking for updates.
I have added a description for  Oracle Commerce, Oracle Commerce Cloud, are they correct.?
About ATG - as I understand correctly, this is an IT company that deals with integration?

**Comment by nurbek91** [comment]
Our old link is being redirected 
http://www.oracle.com/applications/customer-experience/commerce/products/commerce-platform/index.html to -> https://www.oracle.com/cx/ 
is the name of the technology correct or should we rename it Oracle CX?

**Comment by rockeynebhwani** [comment]
ATG was an e-commerce platform which Oracle acquired number of years ago and renamed to 'Oracle Commerce' and now they offer two versions of if .. 'oracle commerce (on-prem)' and 'oracle commerce cloud (on cloud)'.

**Comment by rockeynebhwani** [comment]
@nurbek91  - you can use the new link but I suggest leave the name as-is as in industry it's still known as 'Oracle Commerce'..

**Comment by nurbek91** [comment]
@rockeynebhwani , ok thanks!!
