### ISSUE TITLE
Track 'Happy Returns'

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#5763]
Vendor Site - https://happyreturns.com/
Category - Ecommerce (We don't have a category for something like. Maybe it makes sense to introduce a category called 'Returns'). There are more solutions in market similar to HappyReturns.
Example Site - https://returns.rothys.com/
Detection - Look for Image URLs having '/images.happyreturns.com/' in URL path

**Comment by nurbek91** [comment]
Hey @rockeynebhwani , sent a PR.  Thanks!!.
Added category Returns, 
Technologies:
Happy Returns #5763
Narvar #5764
Loop Returns #5769 
Other technologies for this category will be added later.
I will consider them together with the technologies of a possible new AR category.
