### ISSUE TITLE
web-vitals usage is not being reported on many sites

### ISSUE THREAD

**Issue by philipwalton** [AliasIO/wappalyzer#5768]
**Platform**
Which platform does the bug apply to?
* NPM
* Website
* (perhaps others too)

**Describe the bug**

Wappalyzer does not report that the `web-vitals` JS library (added #4423) is being used on 559,859 pages where it is being used, according to the following query against the Feb 2022 HTTP Archive dataset:

```sql
SELECT count(DISTINCT  url)
FROM `httparchive.pages.2022_02_01_*`, UNNEST(JSON_VALUE_ARRAY(payload, '$._performance.web_vitals_js')) AS script
WHERE url NOT IN (SELECT url FROM `httparchive.technologies.2022_02_01_*` WHERE app = 'web-vitals')
```

Here are a few representative URL and their scripts that bundle the library:

| Page | Script |
| --- | --- |
| https://www.wagnwoofs.com/ | https://assets.squarespace.com/universal/scripts-compressed/common-f65827746f66fb6ef147d-min.en-US.js |
| https://www.graduationcapandgown.com/ | https://cdn.shopify.com/shopifycloud/boomerang/shopify-boomerang-1.0.0.min.js |
| https://www.hlcmuncie.com/ | https://assets.squarespace.com/universal/scripts-compressed/common-f65827746f66fb6ef147d-min.en-US.js |
| https://www.misspink.com.br/ | https://static.cdn-website.com/mnlt/production/2278/editor/apps/modules/runtime/24.a6bfb58e8c6278dcf090.js |
| http://alumni.wku.edu/ | https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194 |

For example:

```sh
npx wappalyzer https://sunrisebrasil.com
```

**To Reproduce**
1. `npx wappalyzer https://www.wagnwoofs.com/`
2. Notice the `web-vitals` is not found in the output

**Expected behavior**
The page should report that `web-vitals` is being used, as [the RegExp defined here](https://github.com/AliasIO/wappalyzer/blob/914999843eef781cd15b169035b638c682b7a674/src/technologies/w.json#L1660) should match (I've manually tested that it does match).

**Additional context**
I seems like this might be some sort of regression in Wappalyzer as it looks like [the number of matches has gone done recently](https://www.wappalyzer.com/technologies/rum/web-vitals/#:~:text=web%2Dvitals%20usage%20trend). Is it possible that something change in the script file contents search logic?

**Comment by AliasIO** [comment]
Thanks, this has been fixed in b8857de8eb5f88967260fd6b4f0ddda27675064f. Script were not being inpected at all. 🤔
