### ISSUE TITLE
Track 'Qwik'

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#5844]
Vendor site - https://github.com/builderio/qwik
Category - Web framewoks
Example Site - https://www.builder.io/
Detection - Look for 'q:version' attribute in HTML tag.

**Comment by steve8708** [comment]
hey @rockeynebhwani - we are making an update to Qwik now to support microfrontends. This means that q:version may not always be on the HTML tag, and instead can be on any element. So if we change this to instead just look for `document. querySelector('[q\\:version]')` we can catch that use case too

cc @manucorporat @mhevery
