### ISSUE TITLE
Track 'Obviyo'

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#5861]
Vendor site - https://www.obviyo.com/
Category - Personalisation / Shopify Apps
Example Site - https://www.pothosbeauty.com/products/charcoal-edge-styler
Detection - Look for script from domain '//h30-deploy.hiconversion.com/'

FYI - https://blendcommerce.com/blogs/shopify/hiconversion-is-now-obviyo

@nurbek91  - After raising this, I realised we already have an entry for 'HiConversion' under A/B Testing category. I think more appropriate categories are what I listed above and let's get this changed to it's new name 'Obviyo'

**Comment by nurbek91** [comment]
Hey @rockeynebhwani , thanks for info!!!
Removed HiConversion , add Obviyo
Category : Personalisation, Shopify app , requires: Shopify, update pricing, icon, desc.
