### ISSUE TITLE
Improve 'Optimizely' detection

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#5867]
Site where it's not working - https://bombas.com/

Current detection

```
  "Optimizely": {
    "cats": [
      74
    ],
    "cookies": {
      "optimizelyEndUserId": ""
    },
    "description": "Optimizely is an experimentation platform that helps developers build and run A/B tests on websites.",
    "icon": "Optimizely.svg",
    "js": {
      "optimizely": ""
    },
    "pricing": [
      "poa",
      "high"
    ],
    "saas": true,
    "scriptSrc": "optimizely\\.com.*\\.js",
    "website": "https://www.optimizely.com"
  },
```

Improve this by adding checks for following - 

- Check for additional JS objects 'optimizelyClient' and 'optimizelySdk'
- Check for script from UNPK CDN - //unpkg.com/@optimizely/optimizely-sdk/dist/optimizely.browser.umd.min.js

**Comment by nurbek91** [comment]
Hey @rockeynebhwani , everything works for me. 
![image](https://user-images.githubusercontent.com/3456008/159535692-ca7c7b9a-dc50-4fdc-b59a-fba9259a7b75.png)
But still updated, with help new attributes, it became possible to record the version.

**Comment by rockeynebhwani** [comment]
@nurbek91 - Sounds good. Not sure why it was not working for me...
