### ISSUE TITLE
Merge 'HightStreet' and 'NewStore'

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#5913]
See this - https://www.crunchbase.com/acquisition/newstore-acquires-highstreet-mobile--204f44b5

HighStreet Website is no longer active. Please merge 'HighStreet' with 'NewStore'

**Comment by nurbek91** [comment]
Hey @rockeynebhwani ,
Very few results for Highstreet. Not even statistics.
Created NewStore, without any changes other than the name.
NewStore offers a lot of products. Do you have any examples for them. I didn't find anything.

**Comment by nurbek91** [comment]
@rockeynebhwani ok, thanks mate!!
