### ISSUE TITLE
Track 'AVADA Size Chart'

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#5919]
Vendor site - https://apps.shopify.com/avada-size-chart
Category - Shopify Apps
Example Site - https://www.pacozy.com/
Detection - Look for script from domain '//sizechart.apps.avada.io/'

**Comment by nurbek91** [comment]
Hey @rockeynebhwani , added thanks!!
Make it little bit granular
Avada SEO - 13300
Avada Size Chart - 5300
Avada AVASHIP - 1300 results
Avada Boost Sales - 2660 results
