### ISSUE TITLE
Wappalyzer doesn't replace \\1, \\2 etc at the right side of a conditional (\\3?\\1.\\2.\\3:\\1.\\2) version pattern

### ISSUE THREAD

**Issue by q--** [AliasIO/Wappalyzer#594]
Consider the following version string: `\\;version:\\3?\\1.\\2.\\3:\\1.\\2`.

When match 1 is `8`, match 2 is `7` and match 3 is `6`, the version becomes: `8.7.6`.

When match 1 is `8`, match 2 is `7` and there is no match 3, the version becomes: `\1.\2`.

I'm using Chrome and the latest (GitHub) version of Wappalyzer.

**Comment by AliasIO** [comment]
Fixed in 978a882bdb536aa5a130a3b9c6251cca5c0960b3.

Only one instance of each back reference was replaced.
