### ISSUE TITLE
Add Option to choose wich Categories to detect / show

### ISSUE THREAD

**Issue by justb81** [AliasIO/Wappalyzer#650]
With now up to 43 categories and hundreds of apps to detect i often find pages with 10 and more apps detected. I think it should be on everyones own to select the categories which are interesting for themselfes.

## Feature Request ##
Add a multiselect field to the option dialog where i can unselect categories which i don't want to know of. At best, these categories would not be shown and not detected.

**Comment by AliasIO** [comment]
Continued in #864.
