### ISSUE TITLE
add CKAN

### ISSUE THREAD

**Issue by seralf** [AliasIO/Wappalyzer#683]
# CKAN:
ckan.org

the best option to recognize CKAN platform seems to be verify the header reported below

## headers

    Access-Control-Allow-Headers:X-CKAN-API-KEY, Authorization, Content-Type

**Comment by seralf** [comment]
it's possible to add an optional metadata:
```
<meta name="generator" content="ckan 2.5.2" />
```

**Comment by jvoisin** [comment]
It would be great to add a fingerprint for the footer too: ` <p><strong>Powered by</strong> <a class="hide-text ckan-footer-logo" href="http://ckan.org">CKAN</a></p>`
