### ISSUE TITLE
New application - Meteor.js

### ISSUE THREAD

**Issue by szarik88** [AliasIO/Wappalyzer#696]
It seems to me that the meteor is becoming so popular that he cannot be missed.
It is nodejs framework. Official site: https://www.meteor.com/

How to detect:
* in deploy version there is minified css with "?meteor_css_resource=true"
* in deploy version there is gloal JS variable "\_\_meteor_runtime_config__"

Example site: https://www.meteor.com/

**Comment by zimt28** [comment]
+1

**Comment by AliasIO** [comment]
Added.
