### ISSUE TITLE
[Meta] Should we establish a writing standard and good practices for apps.json file ?

### ISSUE THREAD

**Issue by gadcam** [AliasIO/Wappalyzer#732]
The apps.json is the core of Wappalyzer and now it is longer than 4000 lines, it contains almost 700 applications and there are more and more contributors so it is harder to keep its consistency i.e. the same writing style everywhere.
So I offer that we set up a writing standard to keep it simple to maintain and why not to automate some verification like useless capturing groups in the future.
- Should we use arrays or not when it's not needed ?
- Should we define an order for patterns fields ? The one used in https://github.com/ElbertF/Wappalyzer/wiki/Specification ?
- What is the right alphabetical sorting for the applications ? (should ELOG HTTP be before or after ELOG?)
- We need to avoid using groups and especially capturing group when not needed
- We need to avoid matching plain text with HTML patterns
- Should we use 0-9 or \\d ? I would say \\d

I think it is little things like that will make the project go forward faster because the "problems" in newcomer, but not only, pull requests are always the same because the writing standard of the apps.json is for the most untold. So we could reinvest the time we take to correct littles mistakes in useful contributions.

**Comment by toastal** [comment]
One easy win would be to add an [EditorConfig file](http://editorconfig.org/) like many other projects do. I know one issue I ran into was that my text editor is configured to trim trailing whitespace and one single objects in the `apps.json`didn't trim and it was showing in my diff. Just setting the whitespace with a config file like this could clear up a lot.

**Comment by ElbertF** [comment]
Good idea!

**Comment by ElbertF** [comment]
We now have a Vagrant/Docker development environment. Running `wappalyzer validate` will point out any errors in apps.json.

**Comment by ElbertF** [comment]
We now have a Vagrant/Docker development environment. Running `wappalyzer build` or `wappalyzer validate` will point out any errors in apps.json.

**Comment by ElbertF** [comment]
Added a .editorconfig file as well.

**Comment by ElbertF** [comment]
One more update, the build script now validates the JSON against [a schema](https://github.com/ElbertF/Wappalyzer/blob/master/schema.json), prettifies it and sorts all the keys alphabetically. I'd like to add some custom validation as well, e.g. to ensure HTML patterns can't match plain text.

**Comment by gadcam** [comment]
I think I can close this issue as most of the work has been done by @AliasIO @DaAwesomeP !
Sure we have yet things to do but we can debate about the idea in a pull request or in an issue.
(I would love to add a PNG compression to the build process but I can't figure out how to install Docker + Vagrant on Win 7 without Intel VT-x..)

**Comment by AliasIO** [comment]
You should be able to turn VT-x on in your BIOS, right? You can run all the scripts without Docker but you'll still need a VM with Linux (although Cygwin might work).

**Comment by gadcam** [comment]
I just checked in the BIOS to be sure but no my processor doesn't support VT-x. I hope it won't curb newcommers to contribute.. and it's too bad that it is not completely cross-platform !
Ok fine I will test it when I have time for it!

**Comment by AliasIO** [comment]
Otherwise you can just let Travis run the tests. :)
