### ISSUE TITLE
[FEATURE] Add Virtualmin (and Webmin, Usermin, Cloudmin if they fit in another category)

### ISSUE THREAD

**Issue by Outdoorsman** [AliasIO/Wappalyzer#749]
Virtualmin control panel has both an open source and paid version that is used by very large audience in the web hosting world.  It goes hand in hand with Webmin, Usermin, and Cloudmin which I would love to be added as well.

http://www.webmin.com/

**Comment by DaAwesomeP** [comment]
I have been using Webmin/Usermin/Virtualmin on and off over the years, and from looking at my installs, there is nothing that can really show that it is Webmin or one of the others except for a specific image or word "Webmin" anywhere.

**Comment by Outdoorsman** [comment]
I'm not sure how you determine things, but can you just search for this?  This is what is present when each of these is selected respectively:
```
<b><img src="/virtual-server/images/virtualmin.png" alt="items"> Virtualmin</b>
```
or this...
```
<b><img src="/images/webmin-small.png" alt="modules"> Webmin</b>
```
There's an additional ```<a>``` tag inside when it's not currently selected... looke like this:
```
<b><a href="newleft.cgi?mode=items"><img src="/virtual-server/images/virtualmin.png" alt="items"> Virtualmin</a>
</b>
```
and this...
```
<b><a href="newleft.cgi?mode=modules"><img src="/images/webmin-small.png" alt="modules"> Webmin</a>
</b>
```

**Comment by Outdoorsman** [comment]
If someone has a custom theme installed it's possible that this HTML would be different but I'm not really sure how many people run custom themes in Virtualmin/Webmin.

**Comment by DaAwesomeP** [comment]
I am trying the above but I think I hit a problem. @AliasIO Does Wappalyzer detect in the insides of frames?

**Comment by AliasIO** [comment]
Nope.

**Comment by DaAwesomeP** [comment]
Webmin, Virtualmin, and Usermin use a frame on the left for navigation and one on the right for content. All of the detection ideas above are in those frames. This should be closed.

**Comment by AliasIO** [comment]
Do the iframe's `src` attributes have any clues?

**Comment by Outdoorsman** [comment]
Here's the frame stuff...
```
<frameset cols="260,*" border="0" cz-shortcut-listen="true">
  <frame name="left" title="Navigation" src="newleft.cgi" scrolling="auto">
  <frame name="right" title="Content" src="newright.cgi?open=system&amp;auto=status&amp;open=updates&amp;open=common&amp;open=owner&amp;open=reseller&amp;open=vm2limits&amp;open=vm2usage" noresize="" scrolling="auto">
  ...
```

**Comment by Outdoorsman** [comment]
The frame src doesn't change when selecting back and forth between webmin and virtualmin. So I think that if you are limited to using frame src for detection you you can only safely say that the site is using Webmin but can't ensure Virtualmin unless the paramters are used... I'm pretty sure that that ```vm2limits``` and ```vm2usage``` parameters are referring to Virtualmin usage and limits.
