### ISSUE TITLE
[new category request] Data Management System

### ISSUE THREAD

**Issue by seralf** [AliasIO/Wappalyzer#758]
Hi adding CKAN support I notice that there isn't already one specific category where to fit it.
The optimal one would be "Data Management System", as well for DKAN (a CKAN functional clone, based on Drupal), Socrata, and other similar platforms designed to publish Open Data.
At the moment I added it under "CMS" which fit in some cases (these platform usually has some content management functionality), but the best choice would be add the new specific category, and use other cateogry like CMS or "API" (if it will be added) as 2nd, 3rd choice.

**Comment by ElbertF** [comment]
Unless we have a few more in the category you can use CMS or Miscellaneous for now. Perhaps even Database?

**Comment by seralf** [comment]
uhm database doesn't convince me as these kind of applications manage data
on a more abstract level (datasets).
So I already used the catagory CMS for CKAN, but even if there are a few of
these platforms, maybe a specific category could be useful. Moreover there
are cases where data are managed by CKAN and similar, and the "front" is
backed by wordpress/drupal: in those cases I feel could be useful to have a
disctinction between the two forms.
Just some idea :-)

2015-01-18 0:38 GMT+01:00 Elbert Alias <notifications@github.com>:
