### ISSUE TITLE
SPDY can't be detected on Google Chrome extension

### ISSUE THREAD

**Issue by Fonger** [AliasIO/Wappalyzer#764]
My website and facebook.com are both using SPDY 3.1
However, it can't be detected using Chrome version.
On Firefox, it works and correctly reports SPDY with a blue lighting icon

**Comment by Fonger** [comment]
It seems the ``X-Firefox-Spdy`` header is only sent when using Firefox.

```js
		"SPDY": {
			"website": "chromium.org/spdy",
			"cats": [ 19 ],
			"headers": { "X-Firefox-Spdy": ".*" }
		},
```


We can detect SPDY in Chrome by the following code used in SPDY indicator plugin
 https://github.com/rauchg/chrome-spdy-indicator/blob/master/indicator.js

```js
chrome.runtime.onMessage.addListener(function (res, sender) {
  var tab = sender.tab
    , showNoSpdy = !Number(localStorage.hideNoSPDY)

  if (res.spdy || showNoSpdy) {
    // show page action
    chrome.pageAction.show(tab.id);

    var icon, tooltip;
    if (res.spdy) {
      tooltip = 'SPDY';
      if (res.info.match(/^spdy\/2/)) {
        icon = 'spdy2';
      } else if (res.info.match(/^spdy\/3\.1/)) {
        icon = 'spdy3.1';
      } else if (res.info.match(/^spdy\/3/)) {
        icon = 'spdy3';
      } else if (res.info.match(/^spdy\/4/)) {
        icon = 'spdy4';
      } else if (res.info.match(/^spdy\/5/)) {
        icon = 'spdy5';
      } else if (res.info.match(/^quic\//)) {
        icon = 'quic';
        tooltip = 'QUIC';
      } else if (res.info.match(/^h2/)) {
        icon = 'http2';
        tooltip = 'HTTP/2';
      } else {
        icon = 'spdy';
      }
    } else {
      icon = 'no-spdy';
      tooltip = 'NOT SPDY';
    }
```

**Comment by MarceI** [comment]
Bump on this feature request but more so for HTTP/2 which is what SPDY has become. The same code  in the last comment from over a year ago is still relevant but I would only bother with HTTP/2 detection as [SPDY support is being pulled from Chrome in a couple of weeks](http://blog.chromium.org/2016/02/transitioning-from-spdy-to-http2.html).
