### ISSUE TITLE
Analyze js and css files content

### ISSUE THREAD

**Issue by m0sth8** [AliasIO/Wappalyzer#775]
Hi @ElbertF!

What do you think about analyzing js/css/fonts files content?
It will be great to take library/framework version from the content like in retirejs[0]

[0] https://github.com/bekk/retire.js/blob/master/repository/jsrepository.json#L249

**Comment by ElbertF** [comment]
Wappalyzer only analyses the main request, mainly for performance reasons. It's not perfrect but most JS and CSS frameworks can be detected this way.

**Comment by gadcam** [comment]
In my opinion it would enable us to detect much more framework and version of them but how about performance ? How should we implement it to detect more things but without sacrifying efficientness ? 
Why do you want to check fonts files content ?

**Comment by m0sth8** [comment]
This kind of analyze might be optional, but It's really useful for version detection. Usually developers don't remove license and version information from js and css files.
Also I don't think this might have a huge performance degradation. We should execute regular expressions only for the comments.

**Comment by q--** [comment]
@m0sth8 And how are we going to find the comments&hellip;?

For the DOM, there are ways to get the HTML comments. But I don't know if the browser offers an interface to access CSS / JS comments directly.

But if we can do this asynchronous, without performance degradation, I'm all for it.

**Comment by m0sth8** [comment]
Comments can be found with regular expressions.

I'm not sure about browser extensions, but I know how to do this in phantomjs. Cause we already did this in retirejs https://github.com/RetireJS/retire.js/pull/68/files#diff-f42388597448f2f5fc672d8ec636f0a2R24)

**Comment by AliasIO** [comment]
We may revisit this in the future but for now I'd like to stick with only analysing the main page. Perhaps there is a better way to look for computed CSS rules without scanning CSS files, like how we can look for JavaScript variables.
