### ISSUE TITLE
wrong detection about rails localhost:3000

### ISSUE THREAD

**Issue by 1ternal** [AliasIO/Wappalyzer#806]
when I'm using rails and react wrote apps, Wappalyzer show that I'm using php(80% sure) and ModX(80% sure).

**Comment by q--** [comment]
It's triggered by this pattern: https://github.com/AliasIO/Wappalyzer/blob/master/src/apps.json#L3292

**Comment by AliasIO** [comment]
I removed `assets/templates` and `assets/components` and lowered the confidence for that pattern.
