### ISSUE TITLE
Google Analytics incorrectly detected

### ISSUE THREAD

**Issue by yosimor** [AliasIO/Wappalyzer#810]
FYI: Using Wappalyzer (v2.36) with Chrome (v40.0.2214.115 m) showed __Google Analytics__ in use on www.notjustdiet.co.il , which turned out to be incorrect.

Viewing the same site via Firefox, or via a different Chrome profile, correctly showed that Google Analytics was *not* in use.

Could it be that "leftover" data from a previous visit to another site was causing this inaccuracy?

![notjustdiet-wappalyzer-googleanalytics](https://cloud.githubusercontent.com/assets/2733763/6428687/36c0ff96-bfb3-11e4-90f3-05981bd2268c.PNG)

**Comment by AliasIO** [comment]
It's not picking up GA for me but I just made some changes to the pattern. Could it be possible that GA is used on another page on that website?

**Comment by yosimor** [comment]
I just uninstalled and re-installed Wappalyzer on my Chrome.  Version remains at v2.36 (despite your pattern-changes?), but GA still being reported (incorrectly).

Both manual sanity-check as well as spidering with www.gachecker.com confirm that __*no*__ pages on that website are using GA.

**Comment by gadcam** [comment]
For me with Chrome Version 40.0.2214.115m and Wappalyzer 2.36 GA is not detected.. you should try with a fresh install it's maybe a cache bug.
