### ISSUE TITLE
Add Sunlight CMS

### ISSUE THREAD

**Issue by Studioartcz** [AliasIO/Wappalyzer#814]
Please look to this CMS: http://sunlight.shira.cz/

You can identify easy by parameter like this:
http://sunlight.shira.cz/?___identify

Here is a repo with new version 8 in beta:
https://github.com/sunlight-cms

In this time are about 3 thousand websites running on this cms and number will be grow up :)

**Comment by ShiraNai7** [comment]
I suggest using the generator meta tag instead. The `___identify` GET parameter is not very well suited for this and will be removed in the upcoming release.

Meta tag examples:

8.x

    <meta name="generator" content="SunLight CMS 8.0.0 BETA">

7.x

    <meta name="generator" content="SunLight CMS 7.5.3 STABLE0" />

6.x

    <meta name="generator" content="SunLight CMS 6.0.1" />

Versions  5.x and older do not expose themselves in any way.

**Comment by gadcam** [comment]
I think you can also search for the env var : <code>sl_indexroot</code> (if it's not only for sunlight.shira.cz)
