### ISSUE TITLE
Detect IBM WebSphere Commerce

### ISSUE THREAD

**Issue by JonathanGiglio** [AliasIO/Wappalyzer#819]
Can someone write a detector for WebSphere Commerce. Typical page source code strings include /wcsstore.

**Comment by craiglondon** [comment]
Could you provide a few URLs of sites using that CMS?   I think HomeDepot does, but I haven't looked in a few years.

**Comment by JonathanGiglio** [comment]
http://www.wacoal-america.com/

**Comment by craiglondon** [comment]
Might need to be tweaked, the code aready has this in it.

```
		"IBM WebSphere Commerce": {
			"cats": [
				6
			],
			"implies": "Java",
			"url": "/wcs/",
			"website": "ibm.com/software/genservers/commerceproductline"
		},
		"IBM WebSphere Portal": {
			"cats": [
				1
			],
			"headers": {
				"IBM-Web2-Location": "",
				"Itx-Generated-Timestamp": ""
			},
			"implies": "Java",
			"url": "/wps/",
			"website": "ibm.com/software/websphere/portal"
		},
```

**Comment by JonathanGiglio** [comment]
/wcsstore is also valid. I notice when I go to The Home Depot site that the icon for WebSphere Commerce doesn't show up in the list of running apps.

**Comment by craiglondon** [comment]
Since you work for IBM, perhaps you could tell us what to add/change in JSON file?  I looked at the header information for Newark.com and didn't see anything that screamed Websphere.  Maybe the wcsstore value in this
```
<link rel="stylesheet" type="text/css" media="all" href="/wcsstore7.00.30995.27/jawr/jawrTmp/text/bundles/global.css" />
```

**Comment by craiglondon** [comment]
Question, the JSON entry to be updated should be "IBM WebSphere Commerce", correct?

**Comment by JonathanGiglio** [comment]
Correct.

**Comment by craiglondon** [comment]
I think this REGEX is close for the HTML value in the JSON, but I'm sure someone could improve on my limited REGEX writing.

<((link)|script)\b[^>]*?\b((href|src))\s*=\s*(?:"((?:\/wcsstore\/"|[^"])*)"|'((?:\/wcsstore\/.+'|[^'])*)')

**Comment by craiglondon** [comment]
I'm also not sure what I need to change to get valid JSON
```
"html": "<((link)|script)\b[^>]*?\b((href|src))\s*=\s*(?:"((?:\/wcsstore\/"|[^"])*)"|'((?:\/wcsstore\/.+'|[^'])*)')",
```

**Comment by craiglondon** [comment]
The regex isn't 100% compliant with the JSON file, but here it is...

https://github.com/craiglondon/Wappalyzer/commit/5f05f7d64ce0d60ea8b43a0d60508d857f63a151

**Comment by q--** [comment]
Backslashes need to be escaped in JSON.

You can get a valid JSON escaped regex with this piece of JavaScript and your browser console:

    prompt("Copy valid JSON string:", JSON.stringify(  /^foo\s+bar$/i .source ));
Where `/^foo\s+bar/i` should be your regex.

**Comment by q--** [comment]
Also, some groups can be [made non-capturing](https://github.com/AliasIO/Wappalyzer/wiki/Specification#unnecessary-use-of-capturing-groups).
