### ISSUE TITLE
Wrong DNS querry + no querry cache

### ISSUE THREAD

**Issue by alexandregaltier** [AliasIO/Wappalyzer#821]
Hi,
Wappalyzer make DNS querry on wappalyzer-at-crunchlabz-dot-com and wappalyzer.com

wappalyzer.com is ok
wappalyzer-at-crunchlabz-dot-com  , supposed email .... could you check this problem ...

furthermore, on each page load, wappalyzer send feedback without dns cache.

23  11   5.187863  10.34.1.213 -> 10.34.100.49 DNS 74 Standard query 0x62ac  A wappalyzer.com
96  40  12.068421  10.34.1.213 -> 10.34.100.49 DNS 92 Standard query 0xd383  A wappalyzer-at-crunchlabz-dot-com

regards,

**Comment by AliasIO** [comment]
Where do you see this happening? There should only occasionally be a request to wappalyzer.com, not on every page. There should never be a request to wappalyzer@crunchlabz.com. The latter is the add-on ID for Firefox and isn't used for anything.
