### ISSUE TITLE
Icon in address bar is not retina

### ISSUE THREAD

**Issue by webyak** [AliasIO/Wappalyzer#823]
The icons in the dropdown look fine. It's just the icon in the address bar.

**Comment by vinkla** [comment]
+1 The extension works great. Though, retina support is needed!

**Comment by rippedspine** [comment]
+1

**Comment by aioue** [comment]
+1

**Comment by AliasIO** [comment]
Wappalyzer's icons are 16x16 (32x32 retina), chrome displays icons as 19x19 (38x38 retina). I don't believe there is way to define a specific size. Collecting new versions of every icon is not trivial.

**Comment by landerss0n** [comment]
+1

**Comment by AliasIO** [comment]
See #1004.

**Comment by DaAwesomeP** [comment]
SVG support should be added in #1012.
