### ISSUE TITLE
Incorrect detection of CMS

### ISSUE THREAD

**Issue by olesbykov** [AliasIO/Wappalyzer#826]
In last version i found this bug: http://oles.pp.ru/images/screenshot/oles/2015/2015-03-22_164228.png

**Comment by DesignWise** [comment]
I see it missing WordPress repeatedly 
![screen shot 2015-03-23 at 9 50 09 am](https://cloud.githubusercontent.com/assets/5914290/6783263/d91917e8-d146-11e4-8b9e-087edd9cc8e9.png)

**Comment by AliasIO** [comment]
Thanks guys, both will be fixed in the next update.
