### ISSUE TITLE
Google Analytics script blocking popup display

### ISSUE THREAD

**Issue by Hao-Wu** [AliasIO/Wappalyzer#827]
OS: Mac OSX 10.10
Browser: Chrome Version 42.0.2311.50 beta (64-bit)
Wappalyzer: Version 2.37

The Wappalyzer icon displays, but not clickable since previous chrome beta. 

In the address bar, there is also icon of "IP Whois & Flags Chrome & Websites Rating", this extension doesn't work either since last update of Chrome 42 beta. Maybe there are some changes of Chromium page action API.

**Comment by AliasIO** [comment]
The documentation hasn't changed. It's probably worth raising with the Chromium team?

https://developer.chrome.com/extensions/pageAction

**Comment by Hao-Wu** [comment]
I just took some time to investigate this issue, and found it caused by google analytics script blocking.
the ga.js insterts <script src="https://ssl.google-analytics.com/ga.js" async=""></script> into <head> section of popup.html
Connections to Google's service are reset or hang up in some area(e.g. China). So the popup.html can't display instantly after extension icon being clicked. The extension works fine if GA is loaded fast.

Not sure about whether it works if google analytics script tag is inserted at the bottom of page document, e.g. just before </body> tag.
