### ISSUE TITLE
Can't add page to bookmarks anymore in Chrome

### ISSUE THREAD

**Issue by edge0703** [AliasIO/Wappalyzer#828]
After the latest change, that put the Wappalyzer icon into the address bar, I can't add a webpage to the bookmarks anymore by clicking on the star. Simply nothing happens. This occurs on two separate computers in the latest version of Chrome on OSX Yosemite.

**Comment by AliasIO** [comment]
Thanks for reporting this here. I can't reproduce it in Linux or Windows 8.

**Comment by edge0703** [comment]
Tried it in Browserstack, and there it works. Strange ...

**Comment by gadcam** [comment]
Can't reproduce :  Win 7, Chrome 41.0.2272.101 m, Wappalyzer 2.37.

**Comment by AliasIO** [comment]
It sounds like a Chrome bug. By design the API doesn't let extension affects the browser UI and this shouldn't be possible.

**Comment by edge0703** [comment]
What would you suggest then?

**Comment by AliasIO** [comment]
If you can, try Wappalyzer on a fresh Chrome installation. May be worth reporting to the Chromium team as well. Are you running a beta version by any chance?

**Comment by edge0703** [comment]
Just found out that it hasn't to do with Wappalyzer at all. I can't even add a bookmark in the menu bar or with the shortcut. Maybe it's a general Chrome bug.

**Comment by AliasIO** [comment]
That's good to know, I'll go ahead and close this one.
