### ISSUE TITLE
Remembers technologies detected earlier

### ISSUE THREAD

**Issue by KolesnichenkoDS** [AliasIO/Wappalyzer#829]
I test my apps on local machine on 0.0.0.0:3000
At first I ran a WordPress site
Now I'm running a Node / ExpressJS app
And Wappalyzer detects both PHP with WordPress and Node with Express

**Comment by gadcam** [comment]
+1 I noticed it sometimes too but I didn't figured out when it occurs and why..

**Comment by AliasIO** [comment]
Results are cached for a while per domain. That way if an app can be detected on one page but not another, it will still be displayed. In most cases it's useful but can lead to odd results like this one.
