### ISSUE TITLE
Wappalyzer icon now appearing in my Chrome address bar instead of with other extensions. 

### ISSUE THREAD

**Issue by peterjohnjoseph** [AliasIO/Wappalyzer#830]
This may very well be something that you've included in the newest upgrade, but I couldn't find any reference to it.  My Wappalyzer icon used to appear with the rest of my Chrome Extensions, to the right of my address bar. Now, over the last few days, it is appearing in the address bar itself, next to the star bookmarks icon. 

I don't believe this is anything I did, as I don't think theres an option to add extensions to the address bar without it being a function of the plugin, which is why I came here to ask if this is in fact where the plugin is now supposed to be displayed, and if it can be changed back to the old extensions area. 

Thanks.
![screen shot 2015-03-25 at 11 29 13 am](https://cloud.githubusercontent.com/assets/3950235/6828100/37959822-d2e2-11e4-8294-bcb0b7cd4171.png)

**Comment by 1GR3** [comment]
Same thing happens over here and it gets even worse: after some time (it doesn't have nothing to do with clicking the button) the whole addressbar disappears. If i open a new tab and start typing dropdown menu with history will appear but the addressbar will remain hidden and i wont be able to access it anymore once I hit the enter.
Please help!

**Comment by AliasIO** [comment]
It's intentional, see #765. The address bar is more suitable for extensions that show information about a page. From the [documentation](https://developer.chrome.com/extensions/pageAction):

> Use the chrome.pageAction API to put icons inside the address bar. Page actions represent actions that can be taken on the current page, but that aren't applicable to all pages.
