### ISSUE TITLE
Extension button appears in the addressbar and making it disappear after some time

### ISSUE THREAD

**Issue by 1GR3** [AliasIO/Wappalyzer#831]
A couple of days ago, the extension button changed it's location from the area for extensions into the adressbar. After some time (it doesn't have nothing to do with clicking the button) the whole addressbar disappears. If i open a new tab and start typing dropdown menu with history will appear but the addressbar will remain hidden and i wont be able to access it anymore once I hit the enter.
Please help!
Crome v 41.0.2272.104 (64-bit) @ OS X 10.9.5

**Comment by AliasIO** [comment]
The Chrome API is purposely very restricted and doesn't let extensions affect the browser UI. There is a single line of code that adds Wappalyzer to the address bar, it's nothing unusual. It sounds like an issue with Chrome or your particular setup, it hasn't been reported by others.

**Comment by 1GR3** [comment]
I assume it has something to do with the stretching of the window (when testing responsiveness) but it doesn't happen every time when I shrink it down all the way.
