### ISSUE TITLE
[APP REQUEST]Firefox v30+: Icon is not showed in toolbar

### ISSUE THREAD

**Issue by mlacunza** [AliasIO/Wappalyzer#832]
Hi,
great extension, but in FF since many versions ago I can only see it in the URL bar and not in the toolbar like in chrome for example.

Many times your extension block me the url bar and I cant see the urls... because of the lot of icons showed, is possible then you can create the option to show the icon app + dropdown option for show the icon list in the toolbar? thanks!
Mario

**Comment by AliasIO** [comment]
You can untick "Display icons in URL bar" in the addon settings. This will add Wappalyzer as a single icon to the toolbar where you can move it around.
