### ISSUE TITLE
Where can i find the source code of the wappalyzer?

### ISSUE THREAD

**Issue by antique0811** [AliasIO/Wappalyzer#833]
as the title   
Where can i find the source code of the wappalyzer?
i really need it 
oh
and i want the php version

**Comment by AliasIO** [comment]
Depends what you mean, you already found the Github repository. The main file is this one:

https://github.com/AliasIO/Wappalyzer/blob/master/src/apps.json

You can find more information in the wiki:

https://github.com/AliasIO/Wappalyzer/wiki

**Comment by antique0811** [comment]
hey   i want to ask if wappalyzer has a php version

**Comment by AliasIO** [comment]
https://github.com/AliasIO/Wappalyzer/wiki/Drivers#php

**Comment by antique0811** [comment]
o   it's really  i want it               thx a lot

**Comment by antique0811** [comment]
hi Elbert                 
i finnaly understand the code of the php version's wappalyzer
but i think the apps in the apps.json is too little
it's only about 7000 lines 
so the detect result is not very detaild
is there any more detailed json file including more apps?

**Comment by AliasIO** [comment]
No, that's everything.

**Comment by antique0811** [comment]
i had test wappalyzer by firefox plugin and Ubuntu cli
sometime the plugin's result is more detail than the php cli version
i dont understand

**Comment by AliasIO** [comment]
Try the PhantomJS driver instead of PHP. The PHP driver can't evaluate JavaScript on websites and therefore yields fewer results.

You can also use Docker:

https://registry.hub.docker.com/u/wappalyzer/cli/

**Comment by antique0811** [comment]
oh  ,  i will go to see 
another little question
i dont really understand how wappalyzer detected the detail version of the apps?
the getVersion() function in the Appalication class seems not to  detect the detail version
but the result show the detail version
it confuses me 
I'm very stupid .....
can u just  explain this concisely ?

**Comment by AliasIO** [comment]
Look for the "Detect version number" comment in the `setDetected` function.

Version detection is part of the regular expressions. E.g. `Drupal (\d)\\;version:\\1` captures `8` in the string `Drupal 8`.
