### ISSUE TITLE
Detects Backdrop CMS as Drupal

### ISSUE THREAD

**Issue by klonos** [AliasIO/Wappalyzer#835]
[Backdrop CMS](http://backdropcms.org) is a fork of Drupal. It is detected as Drupal by Wappalyzer though.

Their website is built in Backdrop CMS. If you check the page source, you'll find multiple instances of the phrase "Backdrop CMS" or the url http://backdropcms.org. There is also the word "Backdrop", but that is [too generic and in fact an actual thing](https://www.google.com.au/search?q=define+backdrop) and might cause false positives.

They do use a ```generator``` meta tag though that you can reliably use:

```<meta name="Generator" content="Backdrop CMS 1 (http://backdropcms.org)" />```

**Comment by AliasIO** [comment]
Fixed in 0e5aaa44dcd181d473c7b5eaed513ae210986aab.

**Comment by klonos** [comment]
Thanx!
