### ISSUE TITLE
jQueryUI is not detected on jqueryui.com

### ISSUE THREAD

**Issue by tandr** [AliasIO/Wappalyzer#837]
If you go to the site and go to "Demos" section (say, http://jqueryui.com/button/ ) jQueryUI is not detected on the site by Chrome extension

**Comment by dfrankland** [comment]
http://jqueryui.com/button/ uses an iframe to display an example with the jquery-ui.js script, but the site itself does not load jquery-ui.js so this is not a bug.

**Comment by tandr** [comment]
So let me understand the logic here. Whatever is used on a site, so in essence, appears as part of it (interactive or not) - but it came from CDN in a iframe it is not counted as "used by the site"?

**Comment by dfrankland** [comment]
An `<iframe>` is essentially a different webpage embedded onto another webpage, like looking through a window into someone else's house. You can't quite tell if they have Comcast by looking at the color of their walls.

But if you go to the webpage that the '<iframe>' is embedding http://jqueryui.com/resources/demos/button/default.html then you can see that Wappalyzer does detect it. This is like actually going inside the other house and checking out that they have Comcast, HD, and over 2000 channels including HBO.

**Comment by tandr** [comment]
Yes, iframe comes from different website altogether, and I understand you sort of counting not "presentations", but "servers" in this case. To me it feels like it is more of "lets grab window from the other house, and install it on ours" or "lets project on the wall whatever is going on in the other house and call it "window in our house", and this is the reason why I think it should be counted towards the site I am currently seeing/visiting. Yes, it might get accounted towards 2 sites, but in case of iframe coming from CDN it might not get counted at all, and I am not sure which is worse.

**Comment by dfrankland** [comment]
I understand where you are coming from, but there are a more issues created trying to account for `<iframe>` than not accounting for them...

1. What if there is an `<iframe>` nested within an `<iframe>` within an `<iframe>`?
    * This could cause a massive hit to performance considering all of the regexs would need to run against many webpages.

2. What if the `<iframe>` is an external webpage?
    * Then we would have to deal with same-origin policy which is difficult to overcome (http://en.wikipedia.org/wiki/Same-origin_policy).

3. Et cetra...

**Comment by tandr** [comment]
Sorry, I did not realize that multi-level iframe will cause perf problems. Parsing past first level of iframes might be an overkill, but at least first level feels like a good idea (is it even possible from extension level?). Would it be possible as very minimum to parse first level of iframe, and/or add an option to "drill deeper", so when I see something interesting and curious what is that, I can get  a correct result? More often than not I don't care about frameworks used, so I don't need icon to display anything. But when I do, I don't care if it will take additional 5 seconds to figure it out.

I am not sure how matching is done, or what access even permitted for extensions, so I am shooting into dark here, sorry...  Would it be possible (for some frameworks) to figure if they are used or not just by looking at file names that come from network? Then regex could targeted against smaller set of rules that will check just for that particular framework. Would this speed things up a bit?

Thank you very much!

**Comment by dfrankland** [comment]
It is possible to do this and would be a great feature to have, but in my opinion though, it seems that it would be beyond the scope of this extension.

If you want to take the extra 5 seconds to see what is being used, then I recommend you use the [ Chrome DevTools ] (https://developer.chrome.com/devtools) to inspect the page for `<iframe>` and open them in a new tab. This way Wappalyzer will detect everything in the tab you opened properly, this is how I discovered that jQueryUI was using an `<iframe>`. Optionally you could use something like [ Open Frame ] (https://chrome.google.com/webstore/detail/open-frame/kdhjgkkaacdhdioocfbpmhjidbinfajj?hl=en) Chrome Extension to open them without inspecting the page.

**Comment by klonos** [comment]
I think that it is a great idea to have an option to drill down one level and that option to be off be default. In that case, I think that whatever is detected in the iframe should be noted (say with an ```i``` to the right of the item) as well as whatever is used both on the main page and in the iframe (say with a ```i+```).
