### ISSUE TITLE
HubPress is detected as Ghost

### ISSUE THREAD

**Issue by FelixINX** [AliasIO/Wappalyzer#842]
All site runing [HubPress](http://github.com/hubpress/hubpress.io) is detected as Ghost.

See in the attached images.
![capture d ecran 18](https://cloud.githubusercontent.com/assets/8009156/7105888/cf0150fc-e0fc-11e4-9788-aa51862e129b.png)

**Comment by q--** [comment]
Looks like HubPress is trying to be compatible with Ghost, at least to some degree: https://github.com/HubPress/hubpress.io/issues/55
