### ISSUE TITLE
Support for semantic-ui

### ISSUE THREAD

**Issue by Dineshs91** [AliasIO/Wappalyzer#844]
It is a web UI framework. Here's the link [semantic-ui](http://semantic-ui.com/)

**Comment by jw-psychopomp** [comment]
Agreed. 

Will review specs for pull requests; should think detection rather easy, whereas a majority of CSS classes are prepended with ``.ui``.

**Comment by Dineshs91** [comment]
Can't we detect from external stylesheet and external script included in the page, like from below

```
<script src="/dist/semantic.min.js"></script>
<link rel="stylesheet" type="text/css" class="ui" href="/dist/semantic.min.css">
```

**Comment by q--** [comment]
It also appears to set a global variable `semantic
