### ISSUE TITLE
Wappalyzer not working on FF 34.0.5 anymore

### ISSUE THREAD

**Issue by Tahajvm** [AliasIO/Wappalyzer#845]
Hi,
I had a problem with a adware add-one so i had to remove FF and reinstall it and beck to an FEBE backup.
But Wappalyzer does not working anymore! ONLY showing a cube on address-bar,
I'm using the latest ver (3.0.15)

**Comment by Tahajvm** [comment]
also i created i new FF profile and install Wappalyzer 3.0.15 on it but only showed cube and "no application detected" message!

**Comment by klonos** [comment]
You are using an outdated version of Firefox. Latest is 37.0.1, can you please try to upgrade first and then retry: https://www.mozilla.org/en-US/firefox/all/

**Comment by Tahajvm** [comment]
FF is updated to latest version (37.0.1) but same message (no application detected)!

**Comment by Tahajvm** [comment]
In New version some of other addone not working too (DownthemAll & NoScript)
![noscript](https://cloud.githubusercontent.com/assets/12019874/7227664/a2038b4e-e767-11e4-9354-675b26e4b849.png)
![dta](https://cloud.githubusercontent.com/assets/12019874/7227681/c0fc56b6-e767-11e4-9c66-9aac849e5039.png)
![wappa](https://cloud.githubusercontent.com/assets/12019874/7227686/ceeda824-e767-11e4-8ff6-5d3e956f5831.png)

**Comment by klonos** [comment]
[Electrolysis](https://wiki.mozilla.org/Electrolysis) perhaps? If so, try disabling it.

**Comment by Tahajvm** [comment]
I dont have Electrolysis, 
This is very strange...
I downgraded FF to V34 (in V37 not working at all) and now some times(!!!!) Wapplyzer is working
I do not change anything and do not know why sometime it's not working...
Plz see the attached snapshots
![940207](https://cloud.githubusercontent.com/assets/12019874/7337148/87856e6a-ec33-11e4-98ac-0eaef744c345.png)
