### ISSUE TITLE
False positive for Twitter Bootstrap on Dell.com

### ISSUE THREAD

**Issue by greglockwood** [AliasIO/Wappalyzer#847]
According to Wappalyzer, Twitter Bootstrap is used on http://www.dell.com. This is likely because there is indeed a reference to a JS file "Bootstrap.js". However, if you look at the actual JS file, at http://nexus.ensighten.com/dell/Bootstrap.js, you will see it is not at all related to the Twitter Bootstrap JS  file. It just happens to be called the same thing.

I could not see any other things on the site that indicated that it did use Twitter Bootstrap at all.

Perhaps the heuristics for detecting Twitter Bootstrap could be tightened up a little?

**Comment by peterbenoit** [comment]
There are a lot of false positives for Bootstrap. Simply because there's a library on the page named bootstrap (albeit a common coding term), doesn't mean bootstrap is being used. Ensighten is a prime example of this.

**Comment by brunowego** [comment]
Another false-positive for [Flexbox Grid](http://flexboxgrid.com/).
