### ISSUE TITLE
react.js is not recognized (properly)

### ISSUE THREAD

**Issue by fibric** [AliasIO/Wappalyzer#850]
While React is being recognized on web.whatsapp.com, its not recognized on facebook.com, digitalocean.com, dropbox.com (logged id), etc

Version of React is being recognized on web.whatsapp.com, but its not on www.scoop.it, mail.yahoo.com (modern view), etc

when react is used, additionally webpack or browserify can be detected.

**Comment by Ambroos** [comment]
Webpack detection in the most reliable way has been submitted a while back, React detection isn't always that easy. You can check it manually by looking at `data-reactid` in the source, but I'm not sure Wappalyzer can do full HTML checks for specific attributes.

**Comment by AliasIO** [comment]
What do you mean by full HTML checks? If it's in the DOM within a second of loading the page, Wappalyzer can read it.

**Comment by Ambroos** [comment]
It usually will be, sometimes it's even in the plain HTML returned from the server (with server-side rendering).

You can spot it this way:
`<div data-reactid=".1zu95ir9q80">` or `<div data-react-checksum="-1651522896">`.
The contents of `data-reactid` and `data-react-checksum` are not predictable, and they can both appear on practically any element in the whole document (including meta, script and style tags). Basically, as soon as anything on the page has a `data-reactid` or `data-react-checksum`-attribute, something on the page is rendered with React (server- or client-side).

Examples: 
 - [Flipboard web](https://flipboard.com/) for pure client-side React
 - [VivaVlaanderen](http://vivavlaanderen.radio2.be/) for server-rendered React in combination with client rendering.

(The easy way is checking for `window.React`, but websites with recent build systems like Webpack or Browserify don't usually expose anything to the window object.)

Maybe I'm wrong, but is it 'easy' to detect something like this with Wappalyzer right now?

**Comment by AliasIO** [comment]
Yes, very easy: `"html": "<[^>]+data-react"`.

**Comment by fibric** [comment]
https://twitter.com/ReactJSNews/status/616347551776649216

**Comment by fjaguero** [comment]
Is there any update on this? PR needed?

**Comment by AliasIO** [comment]
Fixed in 0b66239e3df844c4be871367a25b4157248f0fce.

**Comment by fibric** [comment]
cool :)
