### ISSUE TITLE
Add Landing Page Builder as a category

### ISSUE THREAD

**Issue by mattcoady** [AliasIO/Wappalyzer#854]
Can we get Landing Page Builder as a category? There's a growing number of these applications including Unbounce, Landerapp, LeadPages, PageWiz, Landingi....

**Comment by AliasIO** [comment]
Sure. I don't think we have any applications that fit this category currently, would you like to add them?

**Comment by mattcoady** [comment]
Yup, Unbounce is currently in Wappalyzer. I'll see if I have time to do the others later on.
