### ISSUE TITLE
Sort Results

### ISSUE THREAD

**Issue by EvanGoss** [AliasIO/Wappalyzer#859]
It would be nice to have some sorting options for the Wappalyzer results.  My preference would probably be to make the default sort to be by category (Analytics, Cache Tools, JS Frameworks, etc), but it seems sensible to add a user option to sort by application or category.

**Comment by AliasIO** [comment]
It makes sense to group results by category and sort them by application. We already have a priority list for categories to pick the main icon in the Chrome extension (i.e. CMS first, miscellaneous last).
