### ISSUE TITLE
Too many computing with regex

### ISSUE THREAD

**Issue by kissarat** [AliasIO/Wappalyzer#863]
I use Wappalyzer (chrome driver) in my extension and saw that every page analyzed by 625 regexes. There are nice fingerprints format (apps.json) now, but it's easier, faster (less computing) and more reliable (all js may be in one archive) to detect corresponding objects such as window.jQuery, window.Drupal for example. These objects always contains version, list of plugins, so we can detect more information. This approach can be used in phantomjs, chrome, firefox drivers only.

**Comment by AliasIO** [comment]
The thing with JavaScript variables is that the extension needs to index it first before searching through it. It would have to recursively go through the `window` object which holds hundreds of properties, each of which could also hold hundreds of properties. It would be more accurate but not better for performance.

For security, the only JavaScript Wappalyzer executes on a page is to get the list `window` properties. It doesn't call methods directly.

We also wouldn't remove the old method of detecting version numbers; the more the better (for accuracy).

The is a slight delay between a page load and the time Wappalyzer kicks in. This is to ensure it doesn't block loading of the page. 600 Expressions seems like a lot but I don't believe it's an issue at this point.

**Comment by AlexByte** [comment]
@AliasIO Why is it not safe to access the window directly?

**Comment by AliasIO** [comment]
Content scripts have solved the security issue but I want to avoid executing arbitrary scripts on web pages so as not to break them. `querySelector` is definitely faster though, we should implement it.

**Comment by AlexByte** [comment]
How executing JavaScript code can break page?

**Comment by AliasIO** [comment]
In many different ways of course. The version of jQuery can be checked by executing `jQuery.fn.jquery`. Running that on a website that doesn't have jQuery installed will result in a type error. This example can easily be avoided but executing functions on pages can lead to unexpected results. For instance, it's unclear what happens when you run `$()` on a website, the function name is used by jQuery, Prototype and other frameworks.

**Comment by AlexByte** [comment]
@AliasIO You can not execute methods, but check for existence.

**Comment by AliasIO** [comment]
It works the other way though, we gather the full list of variables first and then look for matches. Getting a list of variables and methods recursively is not practical.

**Comment by AlexByte** [comment]
@AliasIO i [suggest](https://github.com/AliasIO/Wappalyzer/issues/863#issuecomment-327461945) to asking window directly to check for existence of properties.

**Comment by AliasIO** [comment]
We probably could. I've shied from executing more than a few lines of code in the context of web pages as any error will interfere with people's browsing. In most cases global variables are good enough.

**Comment by AlexByte** [comment]
@AliasIO off-topic: normal people watching the console log?

**Comment by AlexByte** [comment]
@AliasIO code can be wrapped in try catch, then the console will not have errors. But a simple property check can not lead to an error at all

**Comment by AliasIO** [comment]
Could be worth looking into, it's probably more efficient to check for the existence of properties then to run a regex over all of them.

**Comment by AlexByte** [comment]
@AliasIO it is important that you can check not only the global properties

**Comment by AlexByte** [comment]
@AliasIO >  what does it mean to interfere with people's browsing ? there will only be an error in the console.
