### ISSUE TITLE
Category selection in options

### ISSUE THREAD

**Issue by kissarat** [AliasIO/Wappalyzer#864]
According to what I said in https://github.com/AliasIO/Wappalyzer/issues/863 about performance, a good solution may be selecting what categories to scan in options page, it reduce amount of computing and extra info in popup.

**Comment by AliasIO** [comment]
I'm not against this idea, the Firefox add-on used to have this option. I do prefer sensible defaults over options however, it makes testing easier and keeps the code base lean. I wouldn't mind getting some more opinions on this.

**Comment by klonos** [comment]
I see the logic behind this request, but I always want to scan for everything. So, I do like the way the extension works currently.
