### ISSUE TITLE
Hello I have a question

### ISSUE THREAD

**Issue by vdanelia** [AliasIO/Wappalyzer#867]
I'm Interested how your extension detects CMS and other resources?
Thank you

**Comment by vdanelia** [comment]
Great Extension, Thanks for that :+1:

**Comment by AliasIO** [comment]
By looking at HTML source code, HTTP response headers, JavaScript variables and URLs. You can find the list of application signatures here:

https://github.com/AliasIO/Wappalyzer/blob/master/src/apps.json

**Comment by vdanelia** [comment]
Thanks :+1:
