### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ramones79** [AliasIO/Wappalyzer#869]
Hello,
I have a question: the Wappalyzer addon for Firefox shows me, that one of the domains I take care of, is using Java, as one of the technologies used.
However, there is no Java use as far as I know. Could you suggest if that report is correct and where is it coming from specifically  or if the Wappalyzer is confused (I used online technology checkers and they did not detect any Java presence).
Is it possible, that the use of Google code (for GA etc) is confusing Wappalyzer?
The domain in question: www.anidoadoption.org

Thank you

**Comment by q--** [comment]
The page has the variables `__gwt_stylesLoaded` and `__gwt_scriptsLoaded`, which are used by the Google Web Toolkit, which uses Java.
