### ISSUE TITLE
Stats on Wappalyzer.com may not be getting updated

### ISSUE THREAD

**Issue by q--** [AliasIO/Wappalyzer#870]
The numbers for [Web Mail](https://wappalyzer.com/categories/web-mail) have been the same since at least [May 5](https://archive.is/KfBd4), which leads me to suspect the data on Wappalyzer.com isn't getting updated.

**Comment by AliasIO** [comment]
You're right, I was wondering why tha database has been so stable as of late... Should be fixed now. Well spotted, thank you.

**Comment by q--** [comment]
Here we go again. [reCAPTCHA](https://wappalyzer.com/applications/recaptcha) was last updated December 11, [phpMyAdmin](https://wappalyzer.com/applications/phpmyadmin) on December 10 and [AdSense](https://wappalyzer.com/applications/google-adsense) on December 9.

Perhaps you should write an automatic test for this or something.
