### ISSUE TITLE
"long list" link at https://wappalyzer.com/suggestions is dead

### ISSUE THREAD

**Issue by q--** [AliasIO/Wappalyzer#872]
As the title says, the link called "long list" at https://wappalyzer.com/suggestions is dead.

**Comment by AliasIO** [comment]
Nice catch, fixed.

**Comment by klonos** [comment]
...still leads to a 404 error page on github.

**Comment by q--** [comment]
Works for me. Perhaps you're seeing a cached page?

**Comment by klonos** [comment]
Could be. Now it works. Sorry for the noise.
