### ISSUE TITLE
Detection for OpenERP/Odoo 

### ISSUE THREAD

**Issue by sotogarcia** [AliasIO/Wappalyzer#877]
Now, Wappalyzer doesn't recognize OpenERP/Odoo as server technology. Odoo was an ERP platform but since 8.0 version it can act as content management system for web and online shop platform.

It is written in Python using, among other technologies, jQuery and Bootstrap.

**Type of application**: ERP / CRM and CMS
**Website**: [https://www.odoo.com](https://www.odoo.com)

**Comment by dfrankland** [comment]
Just made a pull request for this: Add Odoo #878

Cheers!
