### ISSUE TITLE
Chrome Extension installed but no Wappalyzer Icon showing

### ISSUE THREAD

**Issue by CNXTim** [AliasIO/Wappalyzer#884]
All looks OK in Chrome Extensions, but no icon is showing...

**Comment by urbanit** [comment]
Check at the right end of your address bar...

**Comment by q--** [comment]
@ElbertF which reminds me, you've got to update the picture at
https://wappalyzer.com/installed.

2015-06-12 17:12 GMT+02:00 urbanit <notifications@github.com>:

**Comment by urbanit** [comment]
![wappalyzer](https://cloud.githubusercontent.com/assets/1871551/8133181/6ccda9b8-112f-11e5-9eb8-4c04e25da2f2.jpg)

**Comment by CNXTim** [comment]
Doh! yeah did that, silly me :(
