### ISSUE TITLE
High level overview of the regexes

### ISSUE THREAD

**Issue by fxfactorial** [AliasIO/Wappalyzer#893]
I was wondering why some html regex values have a trailing \\;version.... and some don't. 

Any explanation is appreciated.

**Comment by AliasIO** [comment]
The spec has more information:

https://github.com/AliasIO/Wappalyzer/wiki/Specification

Let me know if that doesn't answer your question.

**Comment by fxfactorial** [comment]
Much appreciated.

**Comment by fxfactorial** [comment]
@AliasIO The spec page talks about a "combined confidence". So many of the fields in apps.json might have a confidence, presumably combined confidence means the sum each confidence?

**Comment by AliasIO** [comment]
Correct, the combined confidence value of any patterns that match. If a pattern matches which has no confidence value specified it defaults to 100%.

**Comment by fxfactorial** [comment]
so say we have 

"Some App"" { "headers : { "Server": "....\\; confidence :90}, implies: "PHP"}

Does this mean the total is 190? That can't be right, right?

**Comment by AliasIO** [comment]
That's right, although it's capped at 100%. In the example when the header matches we're already 100% sure it's PHP. It makes more sense to use 50% for two patterns so that if we find both, we're confident we have a positive match.

**Comment by fxfactorial** [comment]
I'm confused about the usage of the version syntax. Can you provide an example of consequence? Like Apache Tom cat for example.

**Comment by AliasIO** [comment]
A better example might be Ruby on Rails. If the `Server` header is found, Rails is reported as 50% sure. If the `Server` and `X-Powered-By` headers are found it's reported as 100% sure. If the `csrf-param` meta tag exists as well it's still 100% sure.

In the case of Apache Tomcat, if either or both of the headers are found it's reported as 100% sure.

**Comment by fxfactorial** [comment]
Sorry, I meant about https://github.com/AliasIO/Wappalyzer/wiki/Specification#version-syntax not the confidence.

**Comment by AliasIO** [comment]
Ah, right.

`Apache-Coyote(/1\\.1)?\\;version:\\1?4.1+:`

This is using a ternary operator. If `\\1` (the first capture group) has any value, the version is reported as `4.1+`. Otherwise the version number is blank.

`\bTomcat\b(?:-([\\d.]+))?\\;version:\\1`

This is an exact match. If `\\1` has a value, this value is reported as the version number.

**Comment by fxfactorial** [comment]
Looking at this one: 
```
		"MoinMoin": {
			"cats": [
				8
			],
			"env": "^show_switch2gui$",
			"implies": "Python",
			"script": "moin(?:_static(\\d)(\\d)(\\d)|.+)/common/js/common\\.js\\;version:\\1.\\2.\\3",
			"website": "moinmo.in"
```
And comparing to the Spec as written in the JSON spec, how is one supposed to interpret that `version:\\1.\\2.\\3`?

**Comment by q--** [comment]
First capture group + literal dot + second capture group + literal dot +
third capture group.

2015-07-31 22:55 GMT+02:00 Edgar Aroutiounian <notifications@github.com>:

**Comment by fxfactorial** [comment]
Thank you, made perfect sense.
