### ISSUE TITLE
Regex Question, accounting for single and double quotes

### ISSUE THREAD

**Issue by craiglondon** [AliasIO/Wappalyzer#895]
How do I update this string to account for single or double quotes on HTML attributes?

In the apps.json
Valid
```
"html": "<div class='dynamicDiv' id='dd\\.\\d\\.\\d'>",
```

Valid Regex, but not valid JSON
```
"html": "<div class=("|')dynamicDiv("|') id=("|')dd\\.\\d\\.\\d("|')>",
```

**Comment by AliasIO** [comment]
Escape the double quotes (once). Also use non-capturing groups if you're not using backreferences, i.e. `(?\"|')` or a character set, i.e. `[\"']`.

`"html": "<div class=[\"']dynamicDiv[\"'] id=[\"']dd\\.\\d\\.\\d[\"']>",`

**Comment by q--** [comment]
>    (?\"|')

That should be:
    (?:\"|')
