### ISSUE TITLE
phantomjs driver unknown error

### ISSUE THREAD

**Issue by redabhr** [AliasIO/Wappalyzer#903]
example :
```
reda@h2o:~$ phantomjs driver.js  -v http://www.marit.ma
[wappalyzer debug] w.init
[wappalyzer debug] w.driver.init
[wappalyzer debug] driver.init
[wappalyzer debug] TypeError: undefined is not an object (evaluating 'f.addEventListener')
{"applications":[]}
```

**Comment by lucaferri** [comment]
I have the same same issue using the phantomjs bin inside vagrant.
This is a big problem because it doesn't let me test my fixes for other issues.

**Comment by lucaferri** [comment]
I don't know what happened, but I destroy and recreate the vagrant machine and now it works.
