### ISSUE TITLE
New Extension Infastructure (just an idea)

### ISSUE THREAD

**Issue by DaAwesomeP** [AliasIO/Wappalyzer#908]
I was thinking about how the extension works, and it seems a tad inefficient. The current system works fine, but it could be improved. Every time the extension/addon updates, it is usually because of a database update and not an actual change to how the addon works. I think that it would work better if the addon simply downloaded the `apps.json` and images every once in a while (daily, weekly, or monthly when there is an update and depending on the setting) instead of getting a full update to the entire extension.

This would make adding and fixing items in the database go live faster. It could simply download from the master on GitHub (only if the build is passing) or the most recent release/tag. You could probably use the secret environment variables in Travis CI and have it upload the minified apps.json and compressed images to a GitHub pages repo/branch or another CDN every time a build passes. The extension would be able to only download the changed or added images instead of all of them.

Lastly, it would make the initial download size and install time of the addon smaller since the `apps.json` and image wouldn't have to be included.

This is just an idea and would automate the build process even further as well as lower the need for real updates and maintenance as often.

**Comment by klonos** [comment]
I wanted to file an issue for this myself, but you beat me to it @DaAwesomeP. It just makes sense to have the actual addon be updated whenever the actual code that does its magic is changed, but not the detection patterns. It's a similar situation as FoxClocks for example: the addon itself has not been updated for some time now, but its database gets updated (with configurable update check intervals).

I say :+1:

**Comment by AliasIO** [comment]
It makes sense but I'm not a fan of the idea. Pushing builds is more reliable, makes it easier to deal with bug reports, probably more secure and there is no dependency on a website. I'm not sure how downloading images would work either, perhaps using localStorage?

**Comment by DaAwesomeP** [comment]
I see. GitHub Pages could be used as the CDN. It's fast (it uses Fastly as its backend), very reliable, secure, and free. The database could be versioned (by date would be easiest) and updated at set time intervals. The data would be downloaded to a temp folder. It's just an idea. Please close this if you don't like it; I don't want to work on something that will be rejected.

**Comment by AliasIO** [comment]
I'll leave it open for further discussion, for now.

I don't think it's a problem that the extensions are always a bit behind with apps.json. I could simply push releases more often but it doesn't matter that much.

**Comment by rugk** [comment]
I'm also in favour of @AliasIO's approach: no DB updates by the addon itself.
As the update process in modern browser happens automatically and is easy and very secure. (think of Mozilla which recently added signing of their add-ons to Firefox)
