### ISSUE TITLE
"Warp" false-positive detections because matches substring

### ISSUE THREAD

**Issue by kolen** [AliasIO/Wappalyzer#910]
Detects [here](http://webmail.vasslatam.com/webmail/), but there's IceWarp ``Server:IceWarp/11.1.2.0``, different product.

```
		"Yesod": {
			"cats": [
				18,
				22
			],
			"headers": {
				"Server": "Warp/\\d+(\\.\\d+)+"
			},
			"implies": "Haskell",
			"website": "www.yesodweb.com"
		},
```

Maybe regex for headers should match whole string, not substring, so it will be not required to add ``^`` and ``$`` in every regex in ``apps.json``?

Also, Warp does not mean Yesod, but it's another issue.

**Comment by AliasIO** [comment]
Substring matches are useful though, adding a `^` is the right solution here.
