### ISSUE TITLE
Dont work in Firefox v40

### ISSUE THREAD

**Issue by mlacunza** [AliasIO/Wappalyzer#930]
Hi
I just upgrade my FF to v.40 and the extension dont work. Im using Ubuntu 15.04 64 bits uptodate.

**Comment by davegraver** [comment]
I agree with @mlacunza. The toolbar icon is not showing up. The address bar option is working.

**Comment by mlacunza** [comment]
@davegraver correct! I just test the address bar option and its working after restart FF. Anyways my address bar show a lot of icons :( waiting the fix :)

**Comment by gadcam** [comment]
Firefox 40.0.2, Win 7, Wappalyzer 3.0.16 : everything is working as usual.

**Comment by davegraver** [comment]
@gadcam I'm using Firefox 40.0 on Mac OS X 10.9.5 (Mavericks) and the Wappalyzer icon is not showing from the available list. See Attached.
![screen shot 2015-08-14 at 1 32 58 pm](https://cloud.githubusercontent.com/assets/3105166/9279956/11365d4e-4289-11e5-9b90-d71213be40f9.png)

**Comment by gadcam** [comment]
I think it's a firefox problem as nothing has changed for the addons in the release note. Try to update to 40.0.2 (could be linked to mozalloc.lib was missing from the xulrunner package (1168291) ?). I can not help you more.

**Comment by mlacunza** [comment]
@davegraver The same here under Ubuntu FF 40.0

**Comment by mlacunza** [comment]
@gadcam I'll wait for the Ubuntu update to that version.

**Comment by AliasIO** [comment]
It's not working for me in either in Firefox 42.0.a2 (Developer Edition). I'm also unable to move it back to the address bar without restarting.

**Comment by mlacunza** [comment]
In Windows 8 the same bug :(

**Comment by mlacunza** [comment]
FF update today in Ubuntu and still nothing.. I dont know but wappalyzer is
the only extension dont working after updates... the icon is missing in the
toolbar, only visible icon in the url bar, and this dont let me see
anything there... can you fix this? if its an error in FF like dev, did you
report it?

Saludos / Best regards

Mario Lacunza
Email:: mlacunza@gmail.com
Personal Website:: http://www.lacunza.biz/
Hosting:: http://mlv-host.com/
Mascotas Perdidas:: http://mascotas-perdidas.com/
Skype: mlacunzav

Lima - Peru

2015-08-16 17:46 GMT-05:00 Elbert Alias <notifications@github.com>:

**Comment by akwala** [comment]
+1

**Comment by AliasIO** [comment]
This should be fixed in 36a0ac90259877e400f0b3c86435b5b66037fc25. Can you please help me test by installing 3.1.0 from the following URL?

https://wappalyzer.com/wappalyzer_firefox.xpi

**Comment by davegraver** [comment]
@AliasIO It worked!!!

**Comment by AliasIO** [comment]
If anyone else wants to test it, set `xpinstall.signatures.required` to `false` in `about:config` first in order to install unsigned add-ons.

**Comment by q--** [comment]
Works fine for me, both in the address bar and in the toolbar button-mode.

Time to push an update, I suppose.

**Comment by mlacunza** [comment]
Yes! works fine for me too!

Saludos / Best regards

Mario Lacunza
Email:: mlacunza@gmail.com
Personal Website:: http://www.lacunza.biz/
Hosting:: http://mlv-host.com/
Mascotas Perdidas:: http://mascotas-perdidas.com/
Skype: mlacunzav

Lima - Peru

2015-08-24 7:19 GMT-05:00 q-- <notifications@github.com>:

**Comment by miynat** [comment]
Unfortunately, it doesn't work for me. (Firefox 40.0.2 , Windows 8.1)

**Comment by AliasIO** [comment]
@miynat Can you go into more detail? Can you verify you have 3.1.0 installed and say what does and doesn't work?

**Comment by miynat** [comment]
I'm sorry I should be more explicit.

Yes, I've 3.1.0 installed you mentioned in this comment - https://github.com/AliasIO/Wappalyzer/issues/930#issuecomment-133779992

It isn't showing up neither at the URL bar nor at the toolbar.

Any further details I can give?

**Comment by q--** [comment]
@miynat Can you go to `about:addons` and check if it's enabled, just in case?

**Comment by miynat** [comment]
Yes, it is enabled (Last Updated : 24th August 2015 Monday) -

![wappalyzer](https://cloud.githubusercontent.com/assets/1431760/9521023/c0765eda-4cd4-11e5-9ae6-4320ef80d756.JPG)

**Comment by AliasIO** [comment]
@miynat It's a big ask but if you could run Wappalyzer using the SDK we can have a look at the debug logs.

https://github.com/AliasIO/Wappalyzer/wiki/Drivers#mozilla-firefox

**Comment by miynat** [comment]
I will try to do my best but I couldn't get a debug log so far.

I've installed *node.js* and *jpm*.
Cloned the Wappalyzer repository, changed directory to *src/drivers/firefox*.
Run **jpm init** (with default values) and **jpm run**
After these steps I'm stuck, actually I couldn't figure out how to get debug logs.

Any help?

**Comment by miynat** [comment]
I gave it another try :

*~Wappalyzer\src\drivers\firefox* > **jpm run**
JPM [info] Starting jpm run on Wappalyzer
JPM [error] Error: The addon has no valid entry point. Either create an entry point
at `./index.js`, or set the `main` property to a valid path in
your addon.

No luck!

**Comment by AliasIO** [comment]
Right, I didn't know CFX was replaced with JPM. Please try again with the latest code.

**Comment by ghazal** [comment]
FF 40.0.3
FF Developer Edition 42.0a2
OSX
Wappalyzer now works beautifully in both with today's update.
The icon is where it should be : in the toolbar.

**Comment by miynat** [comment]
I tried with version **3.1.1**, and here is the exceptions I get:

*~\code\Wappalyzer\src\drivers\firefox* > **jpm run**
JPM [info] Starting jpm run on Wappalyzer
Creating XPI
JPM [info] XPI created at ~\AppData\Local\Temp\wappalyzer@crunchlabz.com-3.1.1.xpi (78ms)
Created XPI at ~\AppData\Local\Temp\wappalyzer@crunchlabz.com-3.1.1.xpi
JPM [info] Creating a new profile
console.log: wappalyzer: [wappalyzer debug] main: install
console.log: wappalyzer: [wappalyzer debug] w.init
console.log: wappalyzer: [wappalyzer debug] w.driver.init
console.error: wappalyzer:
  Message: [Exception... "Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIChannel.open]"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame ::
ync :: line 94"  data: no]
  Stack:
    readURISync@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/net/url.js:94:16
read@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/self.js:55:12
w.driver.init@resource://gre/modules/commonjs/toolkit/loader.js -> resource://wappalyzer-at-crunchlabz-dot-com/driver.js:349:23
driver@resource://gre/modules/commonjs/toolkit/loader.js -> resource://wappalyzer-at-crunchlabz-dot-com/wappalyzer.js:146:10
w.init@resource://gre/modules/commonjs/toolkit/loader.js -> resource://wappalyzer-at-crunchlabz-dot-com/wappalyzer.js:236:4
exports.main@resource://gre/modules/commonjs/toolkit/loader.js -> resource://wappalyzer-at-crunchlabz-dot-com/driver.js:20:3
run@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/addon/runner.js:151:1
startup/</<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/addon/runner.js:86:7
Handler.prototype.process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:867:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:746:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:688:37

console.error: wappalyzer:
  Message: [Exception... "Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIChannel.open]"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame ::
ync :: line 94"  data: no]
  Stack:
    readURISync@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/net/url.js:94:16
read@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/self.js:55:12
w.driver.init@resource://gre/modules/commonjs/toolkit/loader.js -> resource://wappalyzer-at-crunchlabz-dot-com/driver.js:349:23
driver@resource://gre/modules/commonjs/toolkit/loader.js -> resource://wappalyzer-at-crunchlabz-dot-com/wappalyzer.js:146:10
w.init@resource://gre/modules/commonjs/toolkit/loader.js -> resource://wappalyzer-at-crunchlabz-dot-com/wappalyzer.js:236:4
exports.main@resource://gre/modules/commonjs/toolkit/loader.js -> resource://wappalyzer-at-crunchlabz-dot-com/driver.js:20:3
run@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/addon/runner.js:151:1
startup/</<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/addon/runner.js:86:7
Handler.prototype.process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:867:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:746:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:688:37

console.log: wappalyzer: [wappalyzer debug] unload: shutdown

**Comment by klonos** [comment]
@miynat: if you wrap your code in triple [grave accents](https://en.wikipedia.org/wiki/Grave_accent), it'll be more readable. See [this](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks) :wink:

**Comment by miynat** [comment]
Done! Thanks for the tip.

**Comment by akwala** [comment]
Confirming fix in Wappalyzer 3.3.1. The icon and dropdown now appear on the toolbar.

**Comment by miynat** [comment]
Any updates about this issue?

**Comment by miynat** [comment]
Don't know it is related or not, but **Bookmarklet** at the https://wappalyzer.com/download page is working just fine.

**Comment by AliasIO** [comment]
@miynat Please see https://github.com/AliasIO/Wappalyzer/issues/946#issuecomment-143390634.
