### ISSUE TITLE
Time to revise the app icon policy?

### ISSUE THREAD

**Issue by q--** [AliasIO/Wappalyzer#938]
Currently, new icons added to Wappalyzer must be 32×32 PNG images. Additionally, there are still 16×16 PNG's from before. As #823 points out, this is not the ideal size for everything. Retina in Chrome needs larger images, for all other cases they are scaled down to the correct size. Some applications only have a 16×16 icon, in which case the generic icon is used instead. When a vector version of a logo is available (as is the case with PDF.JS, for example), it's converted to a PNG before adding it to Wappalyzer.

All of this seems undesirable to me. I think the icon policy needs some thought. For example, perhaps it would be desirable to set the minimum icon size at 32×32 but increase the upper limit, store multiple sizes of the icon, find a way to incorporate vector graphics when available etc.

Thoughts?

**Comment by AliasIO** [comment]
Downscaling, say, 64x64 to 16x16 won't always looks great so we'd have to keep multiple sizes of icons. Currently we're simply loading `<app name>.png`, not sure how that would work with multiple sizes and/or filetypes. SVG icons would be ideal but I doubt we'd find many.

**Comment by aioue** [comment]
App should support higher resolution images and SVG if they are available. You could use mipmaps for multiple fixed image sizes.

**Comment by AliasIO** [comment]
Let's continue this in #1004. We can start using 64x64 PNGs now and begin accepting SVGs after making the neccesary changes.

**Comment by DaAwesomeP** [comment]
SVGs will work with #1012.
