### ISSUE TITLE
Option to enable both "Display icons in URL bar" and "display toolbar button" 

### ISSUE THREAD

**Issue by Altezza** [AliasIO/Wappalyzer#952]
Since there's no solution to a decade old dual monitor issue in Firefox, I believe this option would help us, who uses our dual monitor setup, to view icons in the URL bar and click on the toolbar button for more information. Displaying Wappalyzer icon as the toolbar button would be great for this option.

Wappalyzer's panel should be enable only for the toolbar button instead of the URL bar due to our dual monitor setup. Or... when clicking on the URL bar, the panel should displays under the toolbar button.

**Comment by AliasIO** [comment]
That's a fairly big change for workaround that feels somewhat counterintuitive and I don't see being used much.
