### ISSUE TITLE
Graphs at application pages on Wappalyzer.com don't show any data beyond August 21

### ISSUE THREAD

**Issue by q--** [AliasIO/Wappalyzer#965]
The category pages appear to get updated, but the graphs at the bottom of the application pages don't show any data beyond August 21. Additionally, some applications added months ago (such as MadAdsMedia) are still showing the "No data available at this time" page.

**Comment by AliasIO** [comment]
Thanks for catching that, again. I moved the website database and forgot to update a configuration file.
