### ISSUE TITLE
'No applications detected' message when clicking on application icon

### ISSUE THREAD

**Issue by Bazaid** [AliasIO/Wappalyzer#966]
the addon worked perfectly for a short period of time, and now it detected but when i click on them to see more information i get ''No applications detected'' message.
picture : http://puu.sh/knDyG/30c488620d.png
page that i tested on : https://addons.mozilla.org/en-US/firefox/addon/wappalyzer/
i also tried on different websites and still got the same message 

-----------------------------------------------------------
using FireFox Developer Edition 42.0a2 (2015-09-21)

**Comment by KenjiroPL** [comment]
I think, i have the same problem. Wappalyzer detects applications and shows them in address bar, but after clicking it shows message "No applications detected". Using dedicated icon it works - just clicking icons from address bar do not show proper list.
--
Firefox 45.0.2 with multiple windows opened

**Comment by Bazaid** [comment]
re-install the plugin i did and now it works
