### ISSUE TITLE
wappalyzer.com on AWS amazon web service 

### ISSUE THREAD

**Issue by preovaleo** [AliasIO/Wappalyzer#977]
Hello,

It's nice to use piwik but why do you give all your data to amazon web service ?
It seems like a good idea but at the end it's useless

Or perhaps you just don't like google analytics ?

**Comment by rugk** [comment]
> perhaps you just don't like google analytics ?

I don't like it too. :smile: 

IMO Piwik - even if it's hosted on AWS - is still better than Google Analytics.
But besides this only the public website is tracked with Piwik. The [app-internal tracking](https://github.com/AliasIO/Wappalyzer/blob/3c9d9e4efa91a5fd5918b6020476783821564ec1/src/drivers/chrome/js/driver.js#L209-L226) is done using an own technology as far as I see.

**Comment by rugk** [comment]
BTW he does not seem to dislike GA generally: https://github.com/AliasIO/Wappalyzer/issues/994

**Comment by AliasIO** [comment]
The website and extensions use encrypted connections, not sure what you mean by data being shared with AWS.

**Comment by preovaleo** [comment]
hello,

Ok, i can't be really sure that they do stat.
But really, they have easily access to your private key so this is really tempting.

My point was that Amazon can easily do stat of who using your app, even in encrypted connection they can see IP. and perhaps they do stat about what they see.

**Comment by rugk** [comment]
> not sure what you mean by data being shared with AWS.

Your server is hosted on AWS...
https://geoip.flagfox.net/?ip=54.173.152.159&host=ad.wappalyzer.com
https://whois.domaintools.com/wappalyzer.com

@preovaleo
Well... the solution is easy: Disable tracking in the settings and everything is fine. :smiley:

**Comment by AliasIO** [comment]
Yes, I know where it's hosted. :) 

@preovaleo You're right that they could get the private key pretty easily. At least it's stored on the disk and not in their key management service so they'd have to go through some effort to find it. Unfortunately this will always be the case unless you own the infrastructure, dedicated in-house servers aren't an option for me.

What is dislike most about Google and the likes is their ability to correlate data. With Fiber, DNS, Chrome, Gmail, Analytics and Search they can create a pretty complete picture of a person's online behaviour. Using a different company for each service largely solves this problem.

**Comment by rugk** [comment]
> With Fiber, DNS, Chrome, Gmail, **Analytics** and Search they can create a pretty complete picture of a person's online behaviour.

*Harrumph*... https://github.com/AliasIO/Wappalyzer/issues/994 :wink: 

> Unfortunately this will always be the case unless you own the infrastructure, dedicated in-house servers aren't an option for me.

Yes, but there are many other (smaller) hosting providers than AWS, which would already address the problem the TS has. So that's no excuse. :wink:

**Comment by AliasIO** [comment]
The GA tracking calls have been removed a very long time ago, I just forgot to delete the ga.js file.

I'm not sure if moving to a smaller host would address the issue. If you're worried about companies like AWS or Akamai receiving your IP address you should probably use a VPN or not use the Internet.

**Comment by preovaleo** [comment]
thank you for your answer.
