### ISSUE TITLE
Sites are sometimes listed twice at Wappalyzer.com

### ISSUE THREAD

**Issue by q--** [AliasIO/Wappalyzer#980]
Some application pages at Wappalyzer.com have sites appear more than once in the list. For example, [the page for phpSQLiteCMS](https://wappalyzer.com/applications/phpsqlitecms) has two domain names that are listed twice.

**Comment by AliasIO** [comment]
Fixed, thanks. Looks like this could happen when there was very little recent data, the table contained some stale information.
