### ISSUE TITLE
Add libraries defined by Retire.JS in Wappalyzer

### ISSUE THREAD

**Issue by math1985** [AliasIO/Wappalyzer#982]
[Retire.js](https://github.com/RetireJS/retire.js/blob/master/repository/jsrepository.json) is 'a scanner detecting the use of JavaScript libraries'.

It currently scans for 22 libraries, of which 12 are already included by Wappalyzer.

The remaining 10 libraries that are included in RetireJS but not in Wappalyzer are the following:

[] jquery-migrate
[] jquery-ui-dialog
[] jquery-ui-autocomplete
[] jquery-ui-tooltip
[] jPlayer
[] sessvars
[] easyXDM
[] plupload
[] DOMPurify
[] DWR

The definitions file from RetireJS is located here: https://github.com/RetireJS/retire.js/blob/master/repository/jsrepository.json

Perhaps it would be an idea to add the missing libraries to Wappalyzer?

**Comment by math1985** [comment]
I didn't follow the commit log - is this item closed as "won't fix" or have all items been added?

**Comment by AliasIO** [comment]
I prefer to leave plugins (such as jquery-ui-tooltip) out of Wappalyzer. If you feel there is a popular library that's missing, please submit a pull request.
