### ISSUE TITLE
You seriously show jokes?

### ISSUE THREAD

**Issue by rugk** [AliasIO/Wappalyzer#991]
![funny02](https://cloud.githubusercontent.com/assets/11966684/10554441/ca967f06-7463-11e5-84a9-66c2f892b2cc.png)
![funny01](https://cloud.githubusercontent.com/assets/11966684/10554440/ca95e3a2-7463-11e5-9ea7-2fe33b381f1a.png)

Besides that I don't understand these two jokes (err... sorry) I also don't think that's such good for a serious addon.
So what about a setting to disable this (as it also takes up extra room)?

**Comment by rugk** [comment]
Okay just found out that `40% sure` really seems to be something serious and seems to be part of the detection.
At the first view it was just not clear what is meant by it.

**Comment by q--** [comment]
Look at the response headers for [that page](https://scotthelme.co.uk/http-2-is-here/). That site's headers say it's using Google PageSpeed vesion `I can haz?!`.

**Comment by rugk** [comment]
Ah so that's the cause. :laughing: 
Okay, so I think I can close this issue. (unless you want to add a version "verification" their :smiley:)
