### ISSUE TITLE
Does not show locale strings (language)

### ISSUE THREAD

**Issue by rugk** [AliasIO/Wappalyzer#992]
Although my browser language is set to German and I see that there is a []German translation](https://github.com/AliasIO/Wappalyzer/blob/3c9d9e4efa91a5fd5918b6020476783821564ec1/src/drivers/firefox/locale/de-DE.properties) everything is still displayed in English.

**Comment by AliasIO** [comment]
That's because not all strings have been translated.

https://github.com/AliasIO/Wappalyzer/blob/master/src/drivers/firefox/locale/de-DE.properties
