### ISSUE TITLE
Still shows features used by previous site when Firefox-internal stuff is diaplayed

### ISSUE THREAD

**Issue by rugk** [AliasIO/Wappalyzer#993]
Test site: http://stlab.adobe.com/wiki/images/d/d3/Test.pdf (go from here: http://stlab.adobe.com/wiki/index.php/File:Test.pdf)

![pdfjs](https://cloud.githubusercontent.com/assets/11966684/10554652/cdc5ef7a-7465-11e5-9333-defc8429b1af.png)

It seems there it only shows the list of the previous site.

Firefox 41.0.2

**Comment by q--** [comment]
It does. Wappalyzer detects technologies used by *web sites*, so if a website hosts its own copy of pdf.js ([example](https://mozilla.github.io/pdf.js/web/viewer.html)) it will be detected. Wappalyzer was never meant to show you what software you're using on your *own* computer, so it won't tell you whether you're viewing PDF's using the Adobe Reader plug-in or Nuance or PDF.js or Foxit or any other reader.

**Comment by rugk** [comment]
Ah okay. So PDF documents (downloaded and viewed by PDF.js in FF) should not be detected.
However in this case it should at least not display the technologies of the previous visited site. (see screenshot)
So the list there should be empty AFAIK.

**Comment by rugk** [comment]
I noticed this also happens when you display a single image.
You can reproduce it e.g. by right-clicking on a user avatar here and choosing "Show image". Wappalyzer is still showing the tools of the previous site.

**Comment by rugk** [comment]
Why do you close all taht bugs? They are not fixed just because you close them...

Please reopen. AFAIK this issue is not fixed yet.

**Comment by AliasIO** [comment]
@q-- Is right that this is by design, Wappalyzer remembers which applications are used per hostname.

**Comment by rugk** [comment]
Mhh, okay still strange to see e.g. "MediaWiki" appearing as a used technology when viewing a PDF file.
