### ISSUE TITLE
Why do you use Google Analytics in Chrome?

### ISSUE THREAD

**Issue by rugk** [AliasIO/Wappalyzer#994]
In Chrome, but not in Firefox you seem to [use Google Analytics](https://github.com/AliasIO/Wappalyzer/blob/3c9d9e4efa91a5fd5918b6020476783821564ec1/src/drivers/chrome/js/ga.js). Why?

You already have [your own tracking technology](https://github.com/AliasIO/Wappalyzer/blob/3c9d9e4efa91a5fd5918b6020476783821564ec1/src/drivers/chrome/js/driver.js#L209-L226) implemented with an opt-out, so that's a way I can accept.

But as far as I see the Google Analytics tracking method in the Chrome addon seems to have no opt-out. IMO that's not a fair way to do it and you should at least add an opt-out.

**Comment by AliasIO** [comment]
Please feel free to submit a pull request to remove it. Firefox used to have it too but I'm not actually using it anymore.
