### ISSUE TITLE
Add Contributing.md

### ISSUE THREAD

**Issue by rugk** [AliasIO/Wappalyzer#995]
What about adding a Contributing guide?

Mainly this of course should focus on adding new entries to the db.
It should answer some basic questions like what format to use, possibly (coding) style stuff and so on.

**Comment by AliasIO** [comment]
Like this?

https://github.com/AliasIO/Wappalyzer/wiki/Contributing

**Comment by rugk** [comment]
Ah you use the wiki...
Yes like this.

But as the Contributing.md is quite popular and is even displayed by GitHub when someone wants to contribute I think at least adding a link there would be good. I've created a PR for this: https://github.com/AliasIO/Wappalyzer/pull/997

**Comment by gadcam** [comment]
+1: I think it's better to use this file than the wiki because the documentation is a part of the project and we can track the changes in the documentation relatively to the changes in the code. (And it's GitHub independent)

**Comment by AliasIO** [comment]
The wiki is also GitHub independent, it's just another repository that you can clone. I'm not opposed to having some documentation in the main repo but at least this way it's all in one place.

**Comment by rugk** [comment]
> The wiki is also GitHub independent, it's just another repository that you can clone.

Yes. :smile: 
And you can [also track the changes](https://github.com/AliasIO/Wappalyzer/wiki/Contributing/_history).

**Comment by gadcam** [comment]
@AliasIO : I didn't know that.
@rugk : You are right but you can not do a single commit to push changes to the code and documentation and so track the changes in the documentation relatively to the changes in the code.

**Comment by AliasIO** [comment]
Which is mainly useful for source code documentation. In this case only the latest version of the documentation is valid.
