### ISSUE TITLE
Compatibility with  Electrolysis (e10s)

### ISSUE THREAD

**Issue by rugk** [AliasIO/Wappalyzer#996]
According to http://arewee10syet.com/ Wappalyzer currently works with e10s, but it's 'shimmed' which means some compatibility layers make sure it works.
Of course the best thing would be if the addon would be '100% compatible' with e10s - especially for performance reasons.

Resources:
* https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/
* https://developer.mozilla.org/en-US/Add-ons/Working_with_multiprocess_Firefox

**Comment by AliasIO** [comment]
I'm not sure what that means, we're using the latest version of the SDK. We do use some legacy code the get multiple icons into the address bar, I'm not quite ready to remove that yet.

**Comment by rugk** [comment]
I cannot find Wappalyzer on http://arewee10syet.com/ anymore. So can anyone retest it?

BTW: Please reopen this issue until it is confirmed that Wappalyzer is compatible with e10s.

**Comment by AliasIO** [comment]
I'm using Wappalyzer on Firefox with e10s enabled without issues.

**Comment by rugk** [comment]
Nice

**Comment by rugk** [comment]
BTW you can use [ACP](https://addons.mozilla.org/de/firefox/addon/add-on-compatibility-reporter/) to get to know of e10s issues or submit such.

**Comment by rugk** [comment]
@AliasIO You may also mark this add-on as compatible if possible.
