### ISSUE TITLE
Test samples in app.json

### ISSUE THREAD

**Issue by rugk** [AliasIO/wappalyzer#999]
Maybe include a link to https://regex101.com/ for the regular expressions in the apps.json. This way you can later easily check the RegExp if something does not work.
Especially there you can also use a unit tester so you can easily test it with a lot of examples.

As you [can't add comments](https://stackoverflow.com/questions/244777/can-i-use-comments-inside-a-json-file) in a JSON file you maybe have to add a new field.

If you'd rather not like to add this directly in the JSON what about at least recommending in the wiki for including it in the PR description.

**Comment by q--** [comment]
The apps.json file shouldn't be used to put contribution instructions IMO.
Suggestions for tools that can be used by contributors, if desired, should
be added to the wiki. (If it's necessary – it's fairly easy to Google for
an online RegExp tester, after all.)

2015-10-18 12:31 GMT+02:00 rugk <notifications@github.com>:

**Comment by rugk** [comment]
I don't only mean the tool as such, but including the such a URL into the `app.json`: https://regex101.com/r/rO3eZ0/1 (I've just choose 1C-Bitrix as an example)

So e.g. this could be added like this
`
{
	"apps": {
		"1C-Bitrix": {
			"cats": [
				1
			],
			"headers": {
				"Set-Cookie": "BITRIX_",
				"X-Powered-CMS": "Bitrix Site Manager"
			},
			"html": "(?:<link[^>]+components/bitrix|(?:src|href)=\"/bitrix/(?:js|templates))",
			"html_regex101": "https://regex101.com/r/rO3eZ0/1",
			"implies": "PHP",
			"script": "1c-bitrix",
			"website": "www.1c-bitrix.ru"
		},
 `

This way later uses could simply check what this regexp is matching.

**Comment by AliasIO** [comment]
I'd be more in favour of including sample values that must pass validation. That way we can automate it. It would something like this:

```
{
    "apps": {
        "1C-Bitrix": {
            "cats": [
                1
            ],
            "headers": {
                "Set-Cookie": "BITRIX_",
                "X-Powered-CMS": "Bitrix Site Manager"
            },
            "html": "(?:<link[^>]+components/bitrix|(?:src|href)=\"/bitrix/(?:js|templates))",
            "tests": {
                "html": [
                    "src=\"/bitrix/templates/1c-bitrix-new/images/vlogo.png\"",
                    "src=\"/bitrix/templates/1c-bitrix-new/images/16.png\"",
                    "src=\"/bitrix/js/main/core/core_db.min.js?14328132264928\"",
                    "href=\"/bitrix/js/main/core/css/core_image.min.css?14293595955405\""
                ]
            }
            "implies": "PHP",
            "script": "1c-bitrix",
            "website": "www.1c-bitrix.ru"
        },
```

**Comment by gadcam** [comment]
+1 for the validation idea but wouldn't this make skyrocket the weight of the extension ?
Could we put these tests in another specific file ? Or do you think it's better to keep everything in the same place and as it make it easier to understand and improve patterns (and why not trim it during the build) ?

**Comment by rugk** [comment]
> I'd be more in favour of including sample values that must pass validation. 

Yes, that's good too. Maybe a better way than putting these samples somewhere else.

**Comment by AliasIO** [comment]
@gadcam In the worst case scenario it will double the size of apps.json, adding 150KB. We could also strip out the tests in the build script.

**Comment by gadcam** [comment]
>We could also strip out the tests in the build script.

If we do that I have no further comments.
It will be another step forward no enable anyone to contribute with an almost complete knowledge on how work the pattern and Wappalyzer.

**Comment by rugk** [comment]
> In the worst case scenario it will double the size of apps.json, adding 150KB. We could also strip out the tests in the build script.

If you care about the filesize of the app.json we could just use a new .json file for this (e.g. `test.json`). Obviously `test.json` does not have to be included in the add-on, but just used for CI tests.

**Comment by DaAwesomeP** [comment]
@rugk I like that idea. For simplicity, `apps.json` could contain the tests so that only one file will contain all of the info as it does now. Then at build the tests in it could be removed after they are run.

**Comment by rugk** [comment]
> Then at build the tests in it could be removed after they are run.

Yeah, that's also possible.

**Comment by siparker** [comment]
there also those of us that dont build the entire thing and just use the driver wappalyzer.js and apps.json
I think this should def be in a seperate file. or am i missing something i should be doing.? sorry for noobing

**Comment by rugk** [comment]
Yes maybe a separate file `tests.json` or `validation.json` is a nice idea.

**Comment by rugk** [comment]
Why did you close it?

**Comment by ScionOfBytes** [comment]
Any progress on this? This is a pretty good idea.

**Comment by rugk** [comment]
shh #badbot :no_bell::robot::no_bell:
